### ISSUE TITLE
Better documentation of `dynamic_include`

### ISSUE THREAD

**Issue by toots** [ocaml/dune#10057]
The documentation for `dynamic_include` is too brief and should include a meaningful example (also the rule stanza is incorrect): https://dune.readthedocs.io/en/stable/dune-files.html#dynamic-include

I have a typical usecase, which is to generate a list of rules to build doc files based on the original source files and I cannot find a pattern to make it work.

Here's what I have so far, based on the current doc:

top-level `dune`:
```dune
(subdir
 doc
 (dynamic_include ../gendune/doc/dune.inc))

(subdir
 gendune/doc
 (rule
  (target dune.inc)
  (deps
    (source_tree ../../doc))
  (action
   (with-stdout-to
    %{target}
    (run ./gen_dune.exe ../../doc)))))
```

And for `gendune/doc/dune`:
```dune
(executable
 (name gen_dune)
 (modules gen_dune))
```

But this fails with some circular dependency issue:
```
Error: Dependency cycle between:
   dynamic_include gendune/doc/dune.inc in directroy doc
-> _build/default/gendune/doc/dune.inc
-> dynamic_include gendune/doc/dune.inc in directroy doc
-> required by alias default in dune:19
```

It's not obvious to me how to make this work since the `gen_dune.exe` executable needs all the files to be present. If I remove the `deps` above, the files are not present when `gen_dune.exe` is executed.

As an aside, not being able to co-locate these rules is rather unfortunate.

**Comment by rgrinberg** [comment]
It's indeed rather unfortunate, but you will need to factor your rules into more directories. In particular, building your code generator should be done outside of `doc`. So you could imagine having `gendoc` as a sibling directory to `doc`.

**Comment by toots** [comment]
> It's indeed rather unfortunate, but you will need to factor your rules into more directories. In particular, building your code generator should be done outside of `doc`. So you could imagine having `gendoc` as a sibling directory to `doc`.

Well this is what I don't understand. This is already the case in my example:
```
doc/<doc files>
gendune/doc/gen_dune.ml
```
But the problem is that `gen_dune.ml` dynamically lists all the files in `doc/` to generate its rules, leading to a circular dependency.

**Comment by rgrinberg** [comment]
Could you create a minimal reproducible example of the issue? I'll take a closer look.

**Comment by toots** [comment]
Thanks for looking into it. Here's a minimal example: https://github.com/toots/dune-dynamic-import-issue

**Comment by rgrinberg** [comment]
Okay, it seems like you need to move your `(dynamic_include ..)` somewhere outside the `doc` directory. Unfortunately, there's no to make this work at the moment without partial loading of rules in a directory.

**Comment by toots** [comment]
Ok thanks I'll think about how we could reorganize the files.

**Comment by emillon** [comment]
@toots I've written a doc about this in #10154 ([rendered here](https://dune--10154.org.readthedocs.build/en/10154/howto/rule-generation.html)), I think it should explain how to achieve this. Let me know what you think.

**Comment by toots** [comment]
Thank you! It is very useful. I have been able to use it to implement a dynamic import for our doc generation. For the tests, though, it is unclear if the pattern will provide any benefit: the tests already have a lot of dependencies in created files and etc so having another level of indirection with the `run/` and `generate`/ subfolders adds a lot of complexity.

Thanks for the hard work nonetheless!
