### ISSUE TITLE
Non-deterministic crash invoking mkdir during package build

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#10076]
During some package builds I see a non-deterministic code error inside `Fpath.mkdir_p` when creating a directory inside the sandbox for building a package.

E.g.
```
Internal error, please report upstream including the contents of _build/log.
Description:
  ("failed to create parent directory",
  { t_s =
      "_build/.sandbox/8cc1e2f4b23197a3c96d399a8e8423d5/_private/default/.pkg"
  })
```

I tried modifying dune to print the path of the missing parent directory and can manually confirm that the directory is present.

Here's a repo containing a small project for reproducing the problem: https://github.com/gridbugs/dune-mkdir-crash-repro

**Comment by gridbugs** [comment]
I'm unable to reproduce this issue when running `dune build` with `-j1`.

**Comment by gridbugs** [comment]
Similarly, if I remove sources of parallelism by replacing calls to `Memo.parallel_map` with `Memo.sequential_map` in pkg_rules.ml, or setting `DUNE_CONFIG__BACKGROUND_SANDBOXES=disabled` the problem appears to go away.

**Comment by gridbugs** [comment]
Also, if I add a call to `Unix.stat` on the directory immediately before printing the error, that branch stops being taken. This could just be changing the interleaving of threads such that this issue never comes up. Makes it hard to debug though.

```patch
diff --git a/otherlibs/stdune/src/fpath.ml b/otherlibs/stdune/src/fpath.ml
index eab87535c..e6d01a972 100644
--- a/otherlibs/stdune/src/fpath.ml
+++ b/otherlibs/stdune/src/fpath.ml
@@ -40,6 +40,7 @@ let rec mkdir_p ?perms t_s =
          | Created -> Created
          | Already_exists -> Already_exists
          | Missing_parent_directory ->
+           let _stats = Unix.stat t_s in
            (* But we just successfully created the parent directory. So it was
               likely deleted right now. Let's give up *)
            Code_error.raise "failed to create parent directory" [ "t_s", Dyn.string t_s ]))
```

**Comment by gridbugs** [comment]
Also I'm unable to reproduce the problem when running dune with `strace`.

**Comment by rgrinberg** [comment]
Are you able to reproduce this in the main branch?

**Comment by gridbugs** [comment]
Nope, this appears to now be fixed.
