### ISSUE TITLE
`depends` on nested package names (like `foo.bar`) in `dune-project` are reported as error

### ISSUE THREAD

**Issue by arbipher** [ocaml/dune#10073]
## Expected Behavior

I found this problem after upgrading `dune` to `3.14.0`.
`dune build` reports errors on dependencies (`depends`) in the `dune-project` file for nested package names e.g. `logs.lwt` `core_kernel.pairing_heap`.

The expected behavior is to accept them as previously.

## Actual Behavior

```console
$ dune build
File "dune-project", line 62, characters 25-49:
62 |  (depends core_unix core_kernel.pairing_heap))
                              ^^^^^^^^^^^^^^^^^^^^^^^^
Error: "core_kernel.pairing_heap" is an invalid package dependency.
Package names can contain letters, numbers, '-', '_' and '+', and need to
contain at least a letter.
Hint: (core_kernel (= pairing_heap)) would be a correct package dependency
```

This error is false and the fixing in the hint makes an incorrect `.opam` file.

## Reproduction

- PR with a reproducing test: 

1. Please allow me to be lazy for not making a PR test. It could be easy to reproduce by adding one nesting package e.g. `core_kernel.pairing_heap` to any `dune-project` at hand. 
2. The generated `opam` file will contain `"core_kernel" {= "pairing_heap"}`, which is an invalid nested  package name
3. `opam install .` reports an error. Change the `depends` entry back to `core_kernel.pairing_heap` then the `opam install .` works.

## Specifications

- Version of `dune` (output of `dune --version`) 3.14.0
- Version of `ocaml` (output of `ocamlc --version`)
- Operating system (distribution and version):

## Additional information 

I search for the changelog and I wonder it may be related to #9472.

**Comment by rgrinberg** [comment]
Writing `(depends core_kernel.pairing_heap)` in your `dune-project` file isn't correct, and you should write `(depends core_kernel)`. The `(depends ..)` field accepts package names, while `core_kernel.pairing_heap` is a library name. The error message is guiding you in right direction, and your previous metadata was wrong.

**Comment by arbipher** [comment]
Thanks for the explanation! I thought of this, but an incorrect local experiment confused me (so I closed it but reopened it).
I will close this issue.
