### ISSUE TITLE
Add newline after error message

### ISSUE THREAD

**Issue by tedbauer** [ocaml/dune#1008]
Hello,

Running OSX 10.12.6, iTerm2 Build 3.1.7

When I run `dune build bin/my_project.bc`, I receive some warning about a dune requirement (in my case, it said "These parentheses are no longer necessary with dune, please remove them."), and then no newline is inserted, which looks a bit wonky.

**Comment by diml** [comment]
Hmm, we have unit tests for this so I'm a bit surprised by this. Could you provide some reproduction steps?

**Comment by tedbauer** [comment]
I can create a project with this directory structure:

* `test/`
    * `lib/`
        * `libfile.ml`: contents are simply `let x = 2`
        * `libfile.mli`: contents `val x : int`
        * `dune`: contents are `(library (name testlib))`
    * `test.ml`: contents are `let _ = print_endline "Test"`
    * `dune`: contents are `(executable (name test) (libraries (testlib)))`

Then, with the working directory as `test`, I run `dune build test.bc`, and receive the following error:

```
File "dune", line 1, characters 35-44:
These parentheses are no longer necessary with dune, please remove them.
```
except, there is no newline at the end of this error message.

**Comment by diml** [comment]
Indeed, I can reproduce this as well. I fixed the issue in master, thanks for the report!
