### ISSUE TITLE
Docs: the “Stanza Reference” section is in “Getting Started and Core Concepts”, which is un-intuitive

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml/dune#10114]
This makes it harder to find the stanza reference when searching it in the table of contents.

**Comment by nojb** [comment]
I agree.

**Comment by shonfeder** [comment]
Since the top-level has a `Reference manual` section and the stanza reference is evidently a reference, I would expect to find it in the former, and I would think it were out of place if at the top-level.

**Comment by nojb** [comment]
The Stanza Reference was moved under "Reference Manual" in #9904, so I guess this issue is fixed.

**Comment by shonfeder** [comment]
Ooo! I forgot to check master and was just going off the published docs. Thanks!
