### ISSUE TITLE
Unable to lock ocaml.org due to undeclared pin-depends in its dune-project

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#10120]
Running `dune pkg lock` in the [ocaml.org repo](https://github.com/ocaml/ocaml.org) produces the error:
```
Error: Unable to solve dependencies for the following lock directories:
Lock directory dune.lock:
Can't find all required versions.
...
- olinkcheck -> (problem)
    No known implementations at all
...
- tailwindcss -> (problem)
    No known implementations at all
...
```

The `olinkcheck` and `tailwindcss` packages are not in the opam repo and are pinned in this project's opam file but the `dune-project` file doesn't mention the fact that they are pinned.

Should we detect cases when a package is specified in both `dune-project` and an opam file but only pinned in the opam file, and use the opam pinning behaviour in such a case?

**Comment by rgrinberg** [comment]
> Should we detect cases when a package is specified in both dune-project and an opam file but only pinned in the opam file, and use the opam pinning behaviour in such a case?

In my experience it's usually simpler to have a single source of truth for metadata. I would assume that if a user wants to use pin-depends, they should really just stick to writing the opam files manually.

I'd say for now ocaml.org can write a workspace file with the pins set there.

**Comment by gridbugs** [comment]
That sounds reasonable. Do you think we should make it an error to attempt to lock a project with dependencies in its `dune-project` file that are pinned in the opam file? Similar to how the list of dependencies in both files must agree. The error you get when attempting to solve the project when the solver doesn't know about the pins is confusing since they are explicitly pinned in the opam file (which the solver ignores when the dune-project is present).

**Comment by rgrinberg** [comment]
We could make it a warning. I imagine the `pin-depends` still have some utility with people that want to use both dune and opam simultaneously, or a subset of the team still uses opam

**Comment by gridbugs** [comment]
But specifically when running `dune pkg lock`, if there are packages pinned in the opam file but not in dune-project or dune-workspace, we know that the outcome will either be a solver error (if the package doesn't exist in the opam repo) or unexpected behaviour (if the package does exist but the pinned version is different). I can't imagine a scenario where attempting to lock ocaml.org in its current state will do what the user intended.

But it's impossible to express opam pins in dune-project/dune-workspace, and vice versa, so we can't require that if the package is described in both opam and dune-project, then both files must agree on pins. I guess the rule should be that if a package is spec'd in dune-project, then dune will ignore pinning information found in its opam file when locking, and print a warning if the opam file contains pinning info. Does that make sense?

**Comment by rgrinberg** [comment]
>  I guess the rule should be that if a package is spec'd in dune-project, then dune will ignore pinning information found in its opam file when locking, and print a warning if the opam file contains pinning info. Does that make sense?

I think that makes sense, yes.

Btw, I don't think this issue is a blocker. It can be easily worked around by writing the equivalent dune pins in the project or workspace (recommended) file.

**Comment by gridbugs** [comment]
It's only a blocker in the sense that building ocaml.org is one of the goals of the package management MVP (though in this case the problem is with ocaml.org).

**Comment by rgrinberg** [comment]
Is not writing any additional dune metadata a requirement? If we can afford writing some metadata, then the workarounds I proposed should be sufficient for now.

**Comment by gridbugs** [comment]
I think for this issue it will be sufficient to send a PR to ocaml.org adding pins in their dune file.

**Comment by tmattio** [comment]
> I think for this issue it will be sufficient to send a PR to ocaml.org adding pins in their dune file.

Absolutely, that's completely fine for us (ocaml.org maintainers)

**Comment by rgrinberg** [comment]
I agree. I would also recommend putting the pins in the workspace file for now so that users that don’t want to use alpha quality dune pkg can just continue with their usual workflow.

**Comment by gridbugs** [comment]
Why is it that putting the pins in the workspace file will allow users to avoid using dune pkg?

**Comment by rgrinberg** [comment]
I assume that some users are still using released versions of dune. Those are going to be slightly different from the dune we intend them to use - built from the main branch. So to make sure their workflow is undisturbed, we can move all the experimental stuff needed for package management into a separate workspace file that has to be activated with a command line flag.You could also just maintain the work in a separate branch as you’re doing now. It’s just that when the MVP is out, we’ll ask more people to experiment but we’ll still not have stability guarantees. So it would be good to minimize the impact for those not experimenting by minimizing changes to non optional metadata. On Feb 28, 2024, at 12:26 AM, Stephen Sherratt ***@***.***> wrote:﻿
Why is it that putting the pins in the workspace file will allow users to avoid using dune pkg?

**Comment by rgrinberg** [comment]
Yes, that’s how I would do it.

**Comment by gridbugs** [comment]
@tmattio I have created a PR adding a workspace file here: https://github.com/ocaml/ocaml.org/pull/2105

**Comment by gridbugs** [comment]
This is no longer an issue since https://github.com/ocaml/ocaml.org/pull/2105 is merged.
