### ISSUE TITLE
Incorrect executable stanza in documentation

### ISSUE THREAD

**Issue by ankhers** [ocaml/dune#1013]
I was just going through the documentation [here](http://dune.readthedocs.io/en/latest/dune-files.html#executable). It currently says that the executable stanza should look like 

```
(executable
  ((name <name>)
   <optional-fields>
  ))
```

Unfortunately I get an error stating that the parens around `name <name>` are no longer required. Based on my own testing, I was able to get it working using the following structure.

```
(executable
 (name main)
  <optional-fields>
 )
```

I would be more than happy to submit a PR if my findings are in line with how it is supposed to work.

**Comment by ttamttam** [comment]
Seems OK to me. Go ahead.
