### ISSUE TITLE
Sha checksums

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#10134]
I noticed that many packages have checksums that aren't md5. E.g.

```
sha256=9170f1a11ade7f4d98a584a5be52bb6b91415f971c6e75894331b46b18b98f09
```

or

```
sha512=25582731170f2f80eed281c48af4904d1d00ef88a38d1b17853395c19a326d7b11e42c17b69f639402c467ff6f9b83a2e9d4dbab7255ac25d466b85a55674bd0)
```

We should make sure that we support these.

**Comment by gridbugs** [comment]
These are already supported in dune lockfiles, e.g. here is the lockfile that gets generated for the `sexplib0` package which has a sha256 hash:
```
(version v0.16.0)

(build
 (run dune build -p %{pkg-self:name} -j %{jobs}))

(depends ocaml dune)

(source
 (fetch
  (url
   https://ocaml.janestreet.com/ocaml-core/v0.16/files/sexplib0-v0.16.0.tar.gz)
  (checksum
   sha256=86dba26468194512f789f2fb709063515a9cb4e5c4461c021c239a369590701d)))
```

**Comment by rgrinberg** [comment]
Right, I think they are indeed supported. We just need  to make sure we extend the test suite to prove this and make sure we never regress.

**Comment by gridbugs** [comment]
Makes sense. I've opened a PR that adds tests for each supported hashing algorithm: https://github.com/ocaml/dune/pull/10156
