### ISSUE TITLE
Idea/Proposal: Explicit Support for Vendoring

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1016]
## Problem

dune's modularity allows for seamless vendoring. This is a good starting point, but it does reveal some weaknesses of the current naive approach. This proposal tries to motivate the benefits for creating a mechanism to mark directories as "vendored" to allow for dune to treat this directories in some special ways. As an initial proposal, I suggest a `(vendored)` stanza that will mark the directory its defined (recursively) as vendored.

The end goal of this proposal to make it transparent to switch a dependency from an external to vendored mode and to make it trivial to update vendored deps. That is without modifying any build files or sources.

## Automatic exclusion from coverage and profiling tools

This is for the upcoming bisect support.

## Enable the env stanza for workspaces that include more than one scope

The reason why `(env ..)` doesn't work for configuring all opam packages in a scope is that it would be incorrect to apply such customizations to vendored packages. If we know which directories are vendored, we'll be able to lift this general restriction on `env` and only apply on the vendored dirs.

## Automatic adjustment of the `@test` alias

The tests for the vendored dependencies can automatically be disabled. This is pretty obvious.

## Automatic adjustment of the `@install` alias

Currently, naive vendoring will pollute the `@install` alias with artifacts defined in vendored libs/exes. These artifacts should be as hidden as possible and hence automatically treated as private. This is already something that users currently do by stripping the public_name fields from their vendored packages. If dune knows which packages are vendored it would do this adjustment automatically (not include the vendored artifacts in `@install`) and would still allow the public_names of vendored artifacts to be used.

## Package private names for vendored dependencies

Today, if one wants to vendor a library then the library should be renamed so that the package doesn't conflict with packages that use the non vendored of the package. If dune understands which libraries are vendored, then it will be able to this renaming automatically. I don't want to spend time describing something elaborate here, so here's a simple description for how it would work for `(wrapped false)` vendored libraries. It should be easy enough to extend this to wrapped libraries as well.

* The `(wrapped false)` library will now be `(wrapped true)`
* Some random name would be generate for the lib name E.g. `vendored_lib<digest>`.
* Users of this vendored library in the project will automatically get the `-open vendored_lib<digest>` flag which will make it possible to use the unmangled names.

The main issue with this approach is that it doesn't really work for vendored libs with `c_stubs`. We can either just disable this kind of name mangling for libs with c stubs or just warn people about this issue.

I'm cc'ing some prominent users of vendored dependencies for feedback: @avsm @samoht and @jordwalke

**Comment by diml** [comment]
The parts about install and test look good to me. I don't follow the part about `env`; what changes are you suggesting?

Could you also describe what problem the last part is solving?

**Comment by diml** [comment]
> I think that if we knew which libraries are the ones which are vendored, we wouldn't want have to reset the env.

What is the issue to solve though? You can now write environment settings in the dune-workspace file and they'll be applied everywhere, which is what @avsm was asking for I believe.

> This is for situations when you'd like to publish libraries that use vendored dependencies. 

Alright, so first of all we need to discuss whether this is a feature we would want to support at all. AFAIK, vendoring libraries in other libraries is generally considered bad practice, so it's not clear to me we should support this in Dune in the first place.

**Comment by jberdine** [comment]
>>  at the root of every project, the environment is the same as the 
>> initial one
>>  otherwise that'd be an issue for vendoring

Is this the reason that if I put an env stanza in the workspace file 
that defines some profiles, context declarations later in the workspace 
file do not pick up the preceding definitions?

That is, it does not work if I inline 
https://github.com/ocaml-ppx/ocamlformat/blob/master/dune into 
https://github.com/ocaml-ppx/ocamlformat/blob/master/dune-workspace.in 
where "does not work" means the dev and release profiles have default 
configuration instead of that specified in the env stanza.

**Comment by diml** [comment]
This looks like a bug, the env stanza in the workspace file should override dune's internal default.

**Comment by diml** [comment]
I had a look, it was a bug in the code handling the `(merlin)` field. Fixed by https://github.com/ocaml/dune/pull/1114

**Comment by rgrinberg** [comment]
> What is the issue to solve though? You can now write environment settings in the dune-workspace file and they'll be applied everywhere, which is what @avsm was asking for I believe.

Yeah, but I don't think that this behavior is intuitive.

> Alright, so first of all we need to discuss whether this is a feature we would want to support at all. AFAIK, vendoring libraries in other libraries is generally considered bad practice, so it's not clear to me we should support this in Dune in the first place.

This is a bad practice that we seem to partake in ourselves in dune :) We vendor cmdliner after all

**Comment by diml** [comment]
> Yeah, but I don't think that this behavior is intuitive.

Personally, I find it intuitive: the workspace file controls the global development environment and individual projects can modify their own environment. Do you have a concrete use case in mind where this is not enough?

> This is a bad practice that we seem to partake in ourselves in dune :) We vendor cmdliner after all

Only for the dune binary though, we don't redistribute it as a library. This scenario is fine.

**Comment by rgrinberg** [comment]
> Personally, I find it intuitive: the workspace file controls the global development environment and individual projects can modify their own environment

I agree with this, I just don't see why the inheritance chain is broken. Projects can still modify their own environments.

> Do you have a concrete use case in mind where this is not enough?

Nope. The behavior did surprise the first time however.

> Only for the dune binary though, we don't redistribute it as a library. This scenario is fine.

I'd be ok with imposing this restriction on vendored libs: a vendored lib may only be used in a private library or an executable.

**Comment by diml** [comment]
> I just don't see why the inheritance chain is broken

This is because dune allows you to organize your workspace as you wish. For instance, one might do:

```
$ git clone git@github.com:me/foo
$ cd foo
$ git clone git@github.com:me/bar
```

Given that this case is supported, an `env` stanza in `foo/dune` must definitely not leak in `foo/bar`.

> I'd be ok with imposing this restriction on vendored libs: a vendored lib may only be used in a private library or an executable.

In this case we don't need to do anything special. It already works well.

**Comment by avsm** [comment]
Ive just run into this with realworldocaml's vendoring -- the automatic adjustments to not include `(vendored)` directories into the test and build default stanzas would be particularly useful there.  The parts about `env` are less critical now that there is a workaround.

**Comment by rgrinberg** [comment]
Thinking about this more and using dune's own vendoring needs in the short term makes me think this proposal is a bit too crude. Some things that are missing:

* It's not enough to mark which libraries are vendored. We also want to publish libraries in dune, but use them "as vendored". Take Fiber, it would be ideal if it was just a normal public library, but dune would consume it always from the local repository (even when `-p` is used).

* If we publish Fiber, we really don't want to Stdune to be usable by users of Fiber. So we really want Stdune to be included inside of Fiber's archive, but it's cmi's would not be installed.

* While the above will solve the issue with stdune, it would be quite useful to depend on a library in *private* mode. E.g. if we'll list `stdune` in Fiber's `private_libraries`, then Stdune will be usable in the .ml files.

Yes, this solution is a bit of a hack and doesn't work when we expose stdune types in Fiber. But I argue that we should never expose Stdune types in Fiber if we want Fiber to be generally usable. Yes, using things like `Ordering.t` it useful, but we should refrain from doing so as users will are more likely to use use stdlib, base, containers. Therefore I argue that the hack above is exactly what we need to make Fiber usable.

**Comment by rgrinberg** [comment]
Indeed. Those 2 aliases make this stanza even more useful.
