### ISSUE TITLE
Windows: Error: CreateProcess(): No such file or directory when PATH contains unicode characters

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/dune#10180]
This is all explained in https://github.com/janestreet/spawn/issues/57

## Specifications

- Version of `dune` (output of `dune --version`): 3.5.0 (but the same code is used in the latest version)
- Operating system (distribution and version): Windows (using Cygwin Terminal but it shouldn't matter)

**Comment by emillon** [comment]
Once you have opened the PR against upstream spawn, you can post the link here and I'll update the repo we use to vendor patches.
