### ISSUE TITLE
Support multiple versions of expected output

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1020]
One issue for expect tests is that they don't work so well when the output is in some way dependant on the environment. The simplest example of this is when the output is dependant on the compiler version such as here:

https://github.com/mjambon/atd/pull/143#issuecomment-405156525

It would be if there was a way to provide multiple versions of the expected output and configure the tests to pick the correct output based on some variables. This should really work for variables that we can control ourselves. E.g. the version of the compiler or the availability of some library. This is to guarantee that updating the tests would update all versions rather than just one.

**Comment by diml** [comment]
Have you tried to suppress the differences via post-processing of the output?

**Comment by rgrinberg** [comment]
It wouldn't really be practical. As the expected output here is generated OCaml code. I prefer to do post-processing when I can't actually test all the version combinations. Since I can in this case, avoiding the post-processing seems better.

**Comment by diml** [comment]
Ok, so  I guess we need the small expression language and an expected field in `test` stanzas?

**Comment by rgrinberg** [comment]
I don't think this feature is the right way to go anymore. The workflow for updating all of these versions is going to be tiresome.
