### ISSUE TITLE
If a dependency is pinned from a local directory, changes made to that directory should take effect immediately

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#10227]
Currently if a dependency is pinned from a local directory and you make changes to that directory, the change isn't visible to the dune project until it removes the copy of the pinned dependency in `_build` (e.g. by running `dune clean`). When working on libraries, I expect a common use case will be to temporarily pin the local source of the library into a project that uses the library in order to test the library as a dependency of that project. It's easy to forget to run `dune clean` after each change to the library and this can lead to confusing results when recent changes aren't picked up.

**Comment by rgrinberg** [comment]
A test case reproducing this would be very helpful

**Comment by gridbugs** [comment]
Ah I didn't realize that this was already the intended behaviour and indeed dune behaves this way in simple cases. I'll make a repro for the case I found where changes are ignored.

**Comment by gridbugs** [comment]
Oh I think my problem is actually with how `(source (copy ...))` behaves in lockfiles rather than the pin stanza. I'll close this and make a new issue.
