### ISSUE TITLE
Fail to preprocess when mixing bisect_ppx with other preprocessors in dune files

### ISSUE THREAD

**Issue by NathanReb** [ocaml/dune#1025]
## What's wrong

I'm having troubles migrating my `jbuild` files to `dune` files. Whenever `bisect_ppx` is involved with some other preprocessors I get one of the following errors:
```
.ppx/bisect_ppx+lwt_ppx+ppx_bin_prot+ppx_blob+ppx_deriving.std+ppx_deriving_yojson/ppx.exe: unknown option '-corrected-suffix'.
```
```
Error: Uninterpreted extension 'eq'.
```

It seems to work fine when `bisect_ppx` is the only ppx.

## How to reproduce it

I looked a bit into it and managed to reproduce the error with a minimal example.
When trying to build a binary from the following `a.ml` file:
```ocaml
let _ = [%eq: int] 1 2

let () =
  Printf.printf "He who controls the spice controls the universe\n"
```
with the following `dune-project`:
```
(lang dune 1.0)
```
and `dune` file:
```
(executable
  (name a)
  (preprocess
    (pps
      ppx_deriving.std
      bisect_ppx
    )
  )
)
```
I get the following error:
```
$ dune build a.exe
      ocamlc .a.eobjs/a.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/nathan/.opam/test/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I .a.eobjs -I /home/nathan/.opam/test/lib/bisect_ppx/runtime -I /home/nathan/.opam/test/lib/ppx_deriving -I /home/nathan/.opam/test/lib/result -no-alias-deps -o .a.eobjs/a.cmo -c -impl a.pp.ml)
File "a.ml", line 1, characters 10-12:
Error: Uninterpreted extension 'eq'.
```
If I try to build it with the same `dune build a.exe` invocation but the following `jbuild` instead:
```
(jbuild_version 1)

(executable
  (
    (name a)
    (preprocess
      (pps
        (
          ppx_deriving.std
          bisect_ppx
        )
      )
    )
  )
)
```
It works perfectly fine!

Do you have any idea what's going on here? I'd be happy to help fixing it if you can point me in the right direction!

**Comment by diml** [comment]
Thanks for the report. The issue is caused by this line in bisect_ppx: https://github.com/aantron/bisect_ppx/blob/master/src/ppx/bisect_ppx.ml#L11. Removing it should fix this issue, /cc @aantron 

The issue is that bisect_ppx runs the entry point of the ppx driver, so any rewriter that is linked after bisect_ppx on the command line will not be taken into account. The reason it worked with jbuilder and not with dune is that the linking order changed between jbuilder and dune for on-demand ppx drivers.

**Comment by aantron** [comment]
@diml Thanks for the diagnosis. I believe we added that line (with @rgrinberg) because we needed to emulate an old-style (standalone executable) PPX. How should that be done?

**Comment by diml** [comment]
@aantron as long as you have `(kind ppx_rewriter)`, dune takes care of it and automatically builds and installs a old-style `ppx.exe` in the library directory. The generated META file supports both old and new style.

**Comment by rgrinberg** [comment]
@aantron I believe that might have been from our initial port which attempted to do it with the original ocamlbuild system. You should be able to just safely remove that line. If you're using dune, then we'll generate a compatibility ppx binary that will automatically run the driver with bisect turned on.

**Comment by rgrinberg** [comment]
Okay, this can be closed. I made a PR in bisect to fix this.

**Comment by aantron** [comment]
Thanks @diml, @rgrinberg. We'll fix it in Bisect, do a release, and I'll ping this issue when it's all out and ready.

BTW the Bisect PR is https://github.com/aantron/bisect_ppx/pull/173.

**Comment by aantron** [comment]
Ok, Bisect_ppx 1.3.4 Is now installable from opam, with this problem fixed. Thanks for the report, and the PR :)
