### ISSUE TITLE
pkg: can't build `topkg`

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#10271]
Building a project which depends on the package `topkg` and the library of the same name produces this error:
```
Cannot find file /home/s/src/depend-on-bonsai/_build/.sandbox/1baf2a8f6e615fe1eb21ee01304fc8d8/_private/default/.pkg/ocamlfind/target/lib/findlib/findlib.cma.
Exception: Compenv.Exit_with_status 125.
-> required by _build/_private/default/.pkg/topkg/target
```

**Comment by gridbugs** [comment]
The problem is that the file `_build/_private/default/.pkg/ocamlfind/target/lib/toplevel` is generated containing paths that refer into ocamlfind's build sandbox, and the sandbox is deleted after ocamlfind is built. For example the file begins:
```
(* $Id$ -*- tuareg -*- *)

(* For Ocaml-3.03 and up, so you can do: #use "topfind" and get a
 * working findlib toploop.
 *)

#directory "/home/s/src/depend-on-bonsai/_build/.sandbox/1baf2a8f6e615fe1eb21ee01304fc8d8/_private/default/.pkg/ocamlfind/target/lib/findlib";;
```

The build script for `topkg` includes the `toplevel` file via the `#use` directive and fails because sandboxed paths no longer refer to anything.

**Comment by gridbugs** [comment]
As a temporary workaround I have added a line to the build command for the fork of ocamlfind I'm using while developing dune package management:
```
["sh" "-c" "sed s#/_build/.sandbox/[^/]*/_private/#/_build/_private/# src/findlib/topfind > src/findlib/topfind.new && mv src/findlib/topfind.new src/findlib/topfind"]
```
That removes the sandbox component of the paths in `topfind`.

That workaround revealed another issue building topkg: The c stubs introduced in https://github.com/ocaml/ocamlfind/pull/72 make it impossible to load `findlib.cma` into the bytecode interpreter which is needed by `topkg`'s build script.

Specifically the build script loads `topfind` with the `#use` directive (here: https://github.com/dbuenzli/topkg/blob/5142ce55b8e325b593eca88fd6f6e08ca809317b/pkg/pkg.ml#L2) and the `topfind` file tries to load `findlib.cma` with `Topdirs.dir_load`.

The error is:
```
Exception: Symtable.Error _.
Raised at Symtable.of_prim in file "bytecomp/symtable.ml", line 102, characters 16-56
Called from Symtable.patch_object.(fun) in file "bytecomp/symtable.ml", line 219, characters 29-43
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Topeval.load_compunit in file "toplevel/byte/topeval.ml", line 218, characters 2-46
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Topeval.really_load_file in file "toplevel/byte/topeval.ml", line 289, characters 8-63
Re-raised at Topeval.init in file "toplevel/byte/topeval.ml", line 298, characters 2-132
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Topdirs.dir_load in file "toplevel/topdirs.ml", line 136, characters 21-55
Called from <unknown> in file "/home/s/src/depend-on-bonsai/_build/_private/default/.pkg/ocamlfind/target/lib/toplevel/topfind", line 34, characters 2-148
Called from Topeval.load_lambda in file "toplevel/byte/topeval.ml", line 89, characters 4-14
-> required by _build/_private/default/.pkg/topkg/target
```

As a workaround I have removed https://github.com/ocaml/ocamlfind/pull/72/commits/061afee3b528b496224dd69179610a966d4ba9cc from my fork of `ocamlfind`.

With the two workarounds I described I'm able to build topkg.

**Comment by gridbugs** [comment]
Oh I forgot there was one additional issue that arose after working around the above. Building topkg would give the error:
```
Error: This rule defines a directory target "default/.pkg/topkg/target" that
matches the requested path "default/.pkg/topkg/target/lib/topkg-care" but the
rule's action didn't produce it
```

I worked around this by forking topkg and removing the `topkg-care` package from `topkg`'s META file (they are both grouped into the same file even if you're only installing `topkg` which seems to confuse dune).

After those 3 workarounds topkg now builds.

**Comment by gridbugs** [comment]
The symtable error is now fixed in https://github.com/ocaml/ocamlfind/pull/72 (thanks @Leonidas-from-XIV).

I've created the issue https://github.com/ocaml/dune/issues/10291 to track the problem with the topfind file.

I'll keep this issue open to track the problem with topkg-care.

**Comment by gridbugs** [comment]
I can no longer reproduce the topkg-care issue so I'm optimistically closing this.

**Comment by NoahTheDuke** [comment]
I've run into this when trying to build odoc locally:

```
#=== ERROR while compiling topkg.1.0.7 ========================================#
# context     2.3.0 | macos/arm64 | ocaml.4.14.2 | https://opam.ocaml.org#38fed1a4c7c23e7b713c214f9cb2f1cc44c9ad68
# path        ~/personal/odoc/_opam/.opam-switch/build/topkg.1.0.7
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build --pkg-name topkg --dev-pkg false
# exit-code   125
# env-file    ~/.opam/log/topkg-89986-946886.env
# output-file ~/.opam/log/topkg-89986-946886.out
### output ###
# File /Users/noah/.opam/default/lib/findlib/findlib.cma is not a bytecode object file.
# Exception: Compenv.Exit_with_status 125.
```

Apple M3 Pro, Sonoma 14.5.

**Comment by Leonidas-from-XIV** [comment]
This looks like you're building using OPAM. That's not related to Dune.

**Comment by NoahTheDuke** [comment]
oops, my apologies
