### ISSUE TITLE
Provide an escape hatch for ".opt" detection

### ISSUE THREAD

**Issue by jorisgio** [ocaml/dune#1028]
It appears that `run` stanza will always try to use .opt version of an executable if available, and i don't see any way to disable this.
this can be a problem for using for instance `campl4` as you cannot invoke `camlp4o` so you need to build a cmxs.

**Comment by diml** [comment]
We should probably change that indeed. You should be able to make it work by statically linking a camlp4 executable though.

**Comment by jorisgio** [comment]
to be honest that's a minor/niche issue, i barely opened an issue because that was unexpected behavior and this kind of "magic" semantic can be surprising. But it might not be worth fixing

**Comment by nojb** [comment]
This has been fixed in #2543
