### ISSUE TITLE
Digest-db deserialisation error

### ISSUE THREAD

**Issue by tmcgilchrist** [ocaml/dune#1032]
When building a dune project we are intermittently seeing this error:

```
jbuilder build @install
File "_build/.digest-db", line 1, characters 28-28:
Error: s-expression followed by data
```

This is with `dune --version 1.0.0` on `ocaml 4.04.2` using Centos/Linux.

I'm not familiar with the code in dune, but the file looks like a binary serialisation of some s-expressions. Has anyone seen this issue?

**Comment by diml** [comment]
This error should happen if you build a project with `dune` or the `jbuilder` binary shipped with dune and then build it again with an old jbuilder (not the one shipped with dune). Is it possible that this is what's happening here?

Moving forward, all these files are versioned, so dune will do the right thing in case of version mismatch.

**Comment by tmcgilchrist** [comment]
Thanks for the suggestion, I'll have to do some more digging in our build scripts.

**Comment by rgrinberg** [comment]
@tmcgilchrist any updates no this?

**Comment by tmcgilchrist** [comment]
Current state of play is we have an opam file with `dune {build & >= "1.0.0"}` so it should be using that.
We also have a lock file made from `opam switch export` which has 
```
dune 1.0.1 installed
...
jbuilder transition installed
```
When we run `opam switch import <lockfile> -y` some packages are requesting jbuilder.

```
....
  - install jbuilder                1.0+beta19.1                [required by variantslib, textutils_kernel, stringext, etc.]
...
```

We are blocked on `v0.10.0` of `variantslib` due to other packages, in particular `tls`.

**Comment by rgrinberg** [comment]
Alright, please re-open if you encounter this issue again.
