### ISSUE TITLE
Error when compiling dune 3.14.2

### ISSUE THREAD

**Issue by nkhlmn** [ocaml/dune#10368]
## Expected Behavior
dune compiles successfully

## Actual Behavior
error is thrown when attempting to compile

## Reproduction
I got this when trying to do `opam update` followed by `opam upgrade`. Also received this message when trying to init a new dune project in a local switch.

## Specifications

- Version of `dune` (output of `dune --version`): Currenly on 3.14.0; error happens when trying to compile 3.14.2
- Version of `ocaml` (output of `ocamlc --version`): 5.1.0
- Operating system (distribution and version): macOS 14.0

## Additional information 

- Error output:

```
#=== ERROR while compiling dune.3.14.2 ========================================#
# context     2.1.5 | macos/arm64 | ocaml-base-compiler.5.1.0 | https://opam.ocaml.org#689abe19
# path        ~/.opam/5.1.0/.opam-switch/build/dune.3.14.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml boot/bootstrap.ml -j 7
# exit-code   2
# env-file    ~/.opam/log/dune-25466-e0ccac.env
# output-file ~/.opam/log/dune-25466-e0ccac.out
### output ###
# ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot -I +unix unix.cma boot/libs.ml boot/duneboot.ml
# ld: warning: search path '/opt/homebrew/Cellar/zstd/1.5.5/lib' not found
# ld: library 'zstd' not found
# clang: error: linker command failed with exit code 1 (use -v to see invocation)
# File "boot/duneboot.ml", line 1:
# Error: Error while building custom runtime system



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build dune 3.14.2
└─
```

**Comment by anmonteiro** [comment]
@nkhlmn can you use OCaml 5.1.1 instead?

There was a rather exceptional breaking change between 5.1.0 and 5.1.1 that should fix your issue: https://discuss.ocaml.org/t/ocaml-5-1-1-incoming-breaking-change-in-the-marshal-module/13457

**Comment by nkhlmn** [comment]
@anmonteiro i'm getting the same error with 5.1.1

**Comment by nkhlmn** [comment]
Using 5.1.1 with the flag to disable compression as described [here](https://github.com/ocaml/ocaml/issues/13035#issuecomment-2001977220) seems to work.

**Comment by emillon** [comment]
thanks for the report. that's indeed an ocaml issue.
