### ISSUE TITLE
Dune changes to invalid directory to build when building jbuilder dependencies

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/dune#1039]
When you have a `dune-project` file in your repository `dune` will wrongly assume when building your opam dependencies that the project root is the project directory and not the root directory at the dependency, therefore trying to write to `project-root/_build/log` instead of `project-root/_opam/.opam-switch/.../jbuilder-dependency.1.0/_build/log` which will fail in OPAM 2.0~rc2+ since it is sandboxed.

Initially filed as https://github.com/ocaml/opam/issues/3471 but the problem seems to be with dune since it apparently changed how it finds the project root.

**Comment by Leonidas-from-XIV** [comment]
The reproducer will most likely stop working once https://github.com/ocaml/opam-repository/pull/12382 is merged, because that will set the `-p` flag which seems to also set the `root` path so it will most likely be correct again.

**Comment by rgrinberg** [comment]
So this isn't actually a bug? `-p` is indeed required to build stuff in "release mode" aka for opam.

**Comment by rgrinberg** [comment]
dune addresses this problem better. The `dune-project` file is useful for this (among other things).
