### ISSUE TITLE
fatal error: CoreFoundation/CoreFoundation.h: No such file or directory

### ISSUE THREAD

**Issue by leana8959** [ocaml/dune#10394]
## Expected Behavior
Dune installs correctly.

## Actual Behavior
Dune doesn't install correctly with the error `src/fsevents/fsevents_stubs.c:15:10: fatal error: CoreFoundation/CoreFoundation.h: No such file or directory`.

This happens with `dune` 3.6.0 and 3.14.2.

Here's the error log:
```text
# context     2.1.5 | macos/arm64 |  | https://opam.ocaml.org#3ae17654
# path        ~/univ-repos/skeletons/necro/_opam/.opam-switch/build/dune.3.14.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml boot/bootstrap.ml -j 9
# exit-code   2
# env-file    ~/.opam/log/dune-2492-ab7007.env
# output-file ~/.opam/log/dune-2492-ab7007.out
### output ###
# ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot unix.cma boot/libs.ml boot/duneboot.ml
# ./.duneboot.exe -j 9
# cd _boot && /Users/leana/univ-repos/skeletons/necro/_opam/bin/ocamlopt.opt -c -g -I +threads fsevents_stubs.c
# src/fsevents/fsevents_stubs.c:15:10: fatal error: CoreFoundation/CoreFoundation.h: No such file or directory
# compilation terminated.
#
```

## Specifications

- Version of `dune` (output of `dune --version`): 3.14.2
- Version of `ocaml` (output of `ocamlc --version`): 4.12.1
- Operating system (distribution and version): Darwin 23.4.0, macOS 14.4.1

**Comment by emillon** [comment]
sorry, this is likely an `opam` issue, not a `dune` one. can you report it [over there](https://github.com/ocaml/opam/issues/new)?
thanks!

**Comment by leana8959** [comment]
Thanks for the reply! I'll do that.
Though is this more of an opam-package issue or an opam issue ?

Thanks !

**Comment by emillon** [comment]
I'd say, start with ocaml/opam since it might be an `opam init` thing.
