### ISSUE TITLE
_build/default/jbuilder.install missing

### ISSUE THREAD

**Issue by themaddoctor** [ocaml/dune#1040]
version 1.0.1

Following the instructions to build and install from README.md:

ocaml bootstrap.ml
./boot.exe
./_build/default/bin/main_dune.exe install

The following <package>.install are missing:
- _build/default/jbuilder.install
You need to run: dune build @install

Nope. Can't do it. Can't build dune until dune is installed. Nope.

**Comment by themaddoctor** [comment]
Same behavior with version 1.0.0

**Comment by hhugo** [comment]
specifying `dune` as follow works for me:  
```
ocaml bootstrap.ml
./boot.exe
./_build/default/bin/main_dune.exe install dune
```
@diml, I'll let you update the README

**Comment by diml** [comment]
I updated the README. BTW, with master you don't need to do `main_dune.exe install dune`, `main_dune.exe install` will do as the `jbuilder.opam` file is no longer present.
