### ISSUE TITLE
dune rebuilds everything when output of coqdep changes

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#10424]
Consider the following situation:

You have a file `a.v` and `b.v` in you coq.theory. You compile everything by running `dune build`. Now in `a.v` you add `Require b.`. This changes the expected output of coqdep and then you rebuild.

In 3.13 only a.v would be rebuilt, since that is the only file that changed.

In 3.14-main both a.v and b.v are being rebuilt.

cc @ejgallego

**Comment by emillon** [comment]
is this a duplicate of #10149?

**Comment by Alizter** [comment]
Completely missed that sorry.

**Comment by emillon** [comment]
no worries!
