### ISSUE TITLE
regression: ocaml-protoc-plugin

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#10447]
Hi,
ocaml-protoc-plugin (up to latest version 5.0.0) fails to build with `main`. This is caused by https://github.com/ocaml/dune/pull/10382.
Our options for 3.16.0 are:
- revert the change
- version the change against lang dune 3.16
- declare the package was relying on a bug, set bounds and send a patch
I haven't checked the project in question so I'll let @gridbugs decide what's best.
Thanks

**Comment by rgrinberg** [comment]
I think this was already fixed in https://github.com/ocaml/dune/pull/10442. Shouldn't this deserve a point release?

**Comment by emillon** [comment]
thanks, I hadn't seen this. yes, it looks like the better solution
