### ISSUE TITLE
Opam template in dune-project file

### ISSUE THREAD

**Issue by yawaramin** [ocaml/dune#10452]
This is a feature request. Currently if we want to use opam fields that are not supported by `dune-project` (eg `available`), we have to use an `.opam.template` file and then dune merges this file into its generated opam file.

Instead of maintaining a separate file, how about adding a new `template` stanza for `dune-project` that could just contain the opam fields as a string? Eg:

```
(lang dune 3.6)

...

(template "
available:
  arch = ...
")
```

This saves us the hassle of having two separate files for opam file management (three, since we should probably count the generated opam file itself).

**Comment by rgrinberg** [comment]
The idea of extending templates isn't a direction we're going to pursue. The whole point of generating opam files is to translate dune metadata to opam metadata for backwards compatibility. As a result, users are intentionally limited to the subset of dune features that can be reasonably translated to opam. If a user would like to use some opam specific feature, he is welcome to do so and use opam's metadata format. Using templates was a hack that was needed in the beginning, but now it's main use is creating poorly behaved packages that work differently depending on if they are being built by dune or by opam.

In this particular case, the solution is to make the `available` field first class by allowing `enabled_if` for packages. I think we already have a ticket for that.
