### ISSUE TITLE
Bonsai no longer builds with dune package management

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#10473]
There's a regression resulting in the following error when using dune to build the dependencies of the package "bonsai" (which we've been using to evaluate dune package management):
```
ocamlfind: Config file not found - neither /Users/s/src/depend-on-bonsai/_build/.sandbox/afd0d45a7d1cb969e78f1a490724f4c3/_private/default/.pkg/ocamlfind/target/lib/findlib.conf nor the directory /Users/s/src/depend-on-bonsai/_build/.sandbox/afd0d45a7d1cb969e78f1a490724f4c3/_private/default/.pkg/ocamlfind/target/lib/findlib.conf.d
make: *** [install] Error 2
-> required by _build/_private/default/.pkg/zarith/target
```

The regression was introduced in https://github.com/ocaml/dune/commit/3ea5444cd7b2874a10add601b9043b5d38662a96

PR which changes back the offending line: https://github.com/ocaml/dune/pull/10474

I don't yet understand why that change caused the regression.

**Comment by Leonidas-from-XIV** [comment]
Complete shot in the dark, but maybe it has something to do with `OCAMLFIND_DESTDIR` that is set to the wrong place? However, I am wondering why it would then complain about the config file, maybe somehow `OCAMLFIND_CONF` is being set to something invalid?

**Comment by gridbugs** [comment]
This was fixed by https://github.com/ocaml/dune/pull/10474.
