### ISSUE TITLE
Allow to mention the current directory in (ignored_subdirs ...) stanza

### ISSUE THREAD

**Issue by andreypopp** [ocaml/dune#1047]
In [esy][] we fetch dependencies' sources into `node_modules` directory. That means a couple of `dune` files end up there (from dependencies) and confuse `dune` unless we put a `dune` file in a project root with
```
(ignored_subdirs (node_modules))
```

That extra `dune` file adds up to others (`dune-project` and `dune` files per compilation unit), I'd rather not impose another burden on esy+dune users to create it and maintain (the error due to non-ignored `node_modules` is the one beginners with esy+dune stumbl;e upon most often).

Therefore I'm wondering if there's a way to add a mechanism to ignore the current directory in `(ignored_subdirs ...)` stanza so that esy could put one at `node_modules/dune` automatically.

[esy]: https://esy.sh

**Comment by aantron** [comment]
Also ran into this today. Another option is to allow `ignored_subdirs` in `dune-project`, but I'm not sure what all the consequences of that would be, e.g. for esy.

**Comment by andreypopp** [comment]
> Another option is to allow ignored_subdirs in dune-project, but I'm not sure what all the consequences of that would be, e.g. for esy.

My idea was to make esy automatically add `node_modules/dune` which ignores all dirs inside `node_modules`. Editing `dune-project` (which is at the project root) automatically is something I don't want to do — really scary when tooling messes up with your files.

**Comment by andreypopp** [comment]
This is not high priority for esy anymore as we now generate
```
(ignored_subdirs <long list of all dir inside node_modules>)
```

Having `(ignored_subdirs *)` or `(ignored_subdirs all)` would be better though.

**Comment by diml** [comment]
@rgrinberg nope. And I just realized that we forgot to remove the extra parentheses for this stanza. At least using globs isn't incompatible with deprecating the parentheses now. Plus since it is technically a breaking change, we could only allow globs if you don't put the parentheses.

**Comment by ELLIOTTCABLE** [comment]
> My use case is a project that has both a BuckleScript/NPM build system, and a Dune one.

Same here; and just ran into this problem today.

```
$ dune build @install
    ocamldep src/.excmd_parser.objs/uAX31.ml.d
Error: Conflict between the following libraries:
- "gen" in _build/default/node_modules/@elliottcable/bs-gen/src
- "gen" in /Users/ec/Sync/Code/excmd-parser/_opam/lib/gen
    -> required by library "sedlex" in /Users/ec/Sync/Code/excmd-parser/_opam/lib/sedlex
This is not allowed.
```

Not personally using esy, and the workaround for those of us not building a build-system is fairly easy (add a root-level `dune` file with no content but `(ignored_subdirs (node_modules))` worked for me); but it'd be nice to have more flexible path declaration in the ignore-declaration.

Personally, although I don't have control of a consumer's *whole* `node_modules`, like esy does, I'd still like to ship a `./dune` file with `(ignored_subdirs *)` to npm, so *consumers* of my BuckleScript libraries don't need to worry about this.

**Comment by andreypopp** [comment]
@rgrinberg yes thanks! closing this then.
