### ISSUE TITLE
the manual...

### ISSUE THREAD

**Issue by houndofsound** [ocaml/dune#1049]
so the hello_world example shows jbuilder implicitly translates ml to cmo. good.
this implies it can do so for all the ml files of a project.
but the manual doesn't suggest how a set of files can be specified. 
it does say to consult the :metadata-format section for the syntax details.
only trouble is, it's not there!

it uses, but doesn't define 'names', 'files' ....

**Comment by diml** [comment]
It's unclear to me what you are asking for. Could you precise?

**Comment by houndofsound** [comment]
Well, the manual has a broken link (a non-existent part of the
manual?) as mentioned.
and my expectation of this link was to find out the formal syntax of Dune and
discover exactly how to specify a project comprised of multiple files,
something I cannot find
an example of in the manual and that experimentation has not revealed.

**Comment by houndofsound** [comment]
the :ref:metadata-format string under "jbuild specification" is meant
to be a link.
OK, looks like I'm looking at the old manual. I don't know how I got
there (history gone).
the new manual has a corrected link.
... and it looks like (modules ..) is what I wanted!
cheers.

**Comment by diml** [comment]
Cool. I'm closing this issue then.
