### ISSUE TITLE
Dune expects .so files generated even when shared libraries are not supported

### ISSUE THREAD

**Issue by aantron** [ocaml/dune#1051]
See ocsigen/lwt#599. @rgrinberg, can you move the most relevant details into a comment on this issue?

**Comment by aantron** [comment]
Also ccing @gruenewa and @lvicentesanchez from the original Lwt issue.

**Comment by diml** [comment]
Is the issue that when the OCaml compiler is not configured to support shared library, then `ocamlmklib` won't produce a `.so` while dune expects that it will?

**Comment by rgrinberg** [comment]
@diml yeah, that's the gist of it.

**Comment by diml** [comment]
Ok. We can determine whether the compiler support shared libraries by looking for `SUPPORTS_SHARED_LIBRARIES` in the `Makefile.config` file installed by ocaml in `ocamlc -where`. 

Dune already supports a `(no_dynlink)` field for libraries, so I believe that all that needs to be done is mimic the behavior of `(no_dynlink)` systematically when `SUPPORT_SHARED_LIBRARIES` is set to `false`.
