### ISSUE TITLE
Customize workspace via environment variable

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1053]
# Problem

It's quite useful to be able to customize builds opam builds in bulk without having to edit build scripts.

# Proposal

We already have a mechanism for making build customization that are never part of a release build and hence can always be inserted. This mechanism is the workspace file which can now be used to select the profile, change standard compiler flags, among other things. Being able to specify this workspace file more easily would open to door to adding a flag to an entire opam switch without changing a single build script.

There are 2 possibilities to implement this future. One is to allow users to specify the workspace contents in the env var. The other possibility is to have the user input a filename. Both are almost interchangeable and have their own minor adjustments. I don't have a particular preference towards either one.

**Comment by diml** [comment]
The second possibility has the advantage that we have somewhere to point errors to, plus it fits well with the CLI.

**Comment by rgrinberg** [comment]
This shouldn't be an issue to implement, so if anyone would like to give this a hand, please reach out.
