### ISSUE TITLE
pkg: lock is stat'ing the current directory like an opam repository

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#10541]
I noticed that when `dune pkg lock` runs, it looks for files in the current directory with a naming scheme similar to an opam-repository: 

```
newfstatat(AT_FDCWD, "/home/etienne/src/dune/packages/ocaml/ocaml.4.09.2", 0x7ffe320108b0, 0) = -1 ENOENT (No such file or directory)

  % time     seconds  usecs/call     calls    errors syscall                          
  ------ ----------- ----------- --------- --------- ----------------                 
   49.56    0.037018           0     74266     56713 newfstatat                       
   33.63    0.025115           0     56689     56688 readlink       
```

That's a lot of system time, and I don't think we're expecting to see these files to be here.

NB this is from `dune pkg lock` in the dune tree.

**Comment by emillon** [comment]
(I'll investigate to see where these calls come from)

**Comment by emillon** [comment]
Interesting, it comes from:

```ocaml
      OpamFile.OPAM.read_from_string
        contents
        ~filename:(Path.to_string path |> OpamFilename.of_string |  > OpamFile.make)
```

Then opam tries to determine the `realpath` of that argument, and does so by stat'ing the whole directory tree.

**Comment by rgrinberg** [comment]
Ouch. I suppose we can just get rid of it here.

**Comment by rgrinberg** [comment]
@emillon i think you've fixed this?

**Comment by emillon** [comment]
There's a part in opam that still does that which is harder to change, but yes I think I've done what I wanted to do here.
