### ISSUE TITLE
Bug upgrading .dune -> .config/dune

### ISSUE THREAD

**Issue by mmottl** [ocaml/dune#1055]
When upgrading from a previous version, the `.dune` directory is moved to `.config/dune`, i.e. we end up with `.config/dune/.dune`.  This is probably not intended, the `.dune` should be `.config/dune` rather than be contained in it.

**Comment by diml** [comment]
This doesn't look right indeed. However, I can't reproduce this issue:

```
$ mkdir -p ~/.config/dune
$ echo "blah" > ~/.config/dune/config
$ dune build
File "/home/jdimino/.config/dune/config", line 1, characters 0-4:
Error: Invalid first line, expected: (lang <lang> <version>)
```

It seems to me that dune is correctly looking for `~/.config/dune/config`.

**Comment by mmottl** [comment]
Yes, `dune` looks in the right place for reading its configuration.  It's just the upgrade step that moves the old configuration directory into the wrong position.

**Comment by diml** [comment]
What upgrade step are you thinking about? Dune doesn't do this for instance. In fact this file hasn't changed, it was already called `~/.config/dune/config` with jbuilder since when we introduced it the new name had already been chosen.

**Comment by mmottl** [comment]
I just realized that it's `dune-release` that's causing this issue.  I'll resubmit the bug report there.  It would be great if the release functionality could be integrated into `dune`.

**Comment by rgrinberg** [comment]
I'm for integrating dune-release on the condition that it would shed its dependencies and adopt itself to dune's coding style/conventions.
