### ISSUE TITLE
ppx_inline_tests enables backtrace mode non-deterministically

### ISSUE THREAD

**Issue by ejgallego** [ocaml/dune#10560]
We have some expect Coq tests that produce output, the output will include backtrace information the flag is set in the runtime.

These tests live under the runtest alias, together with some inline_tests for the libraries.

Recently, we did the following reorganization:

Before : library Util, library Core that depends on Util. Core uses inline tests, test executable depends on Core 
After : we move the inline tests to Util, remove the inline tests from Core

Now, running the tests, before, they didn't contain backtrace information, after they do. That seems quite bizarre / non-deterministic?

**Comment by emillon** [comment]
any chance there's a `Printexc.record_backtrace` call in one the libraries' init code?

**Comment by ejgallego** [comment]
Nope, `ppx_inline_test` is supposed to do it tho, so it gets linked to the executable. I will submit a small reproduction test ASAP.

**Comment by rgrinberg** [comment]
If your test is sensitive to the backtrace, why don't you just add `Printexc.record_backtrace foo` to the top of your test? That way it will work no matter how backtraces were set outside. This way you don't have to know who is setting it.

In any case, I don't think there's a dune bug here. We don't touch the setting at the moment, and if we did it would be intentional.

**Comment by ejgallego** [comment]
> If your test is sensitive to the backtrace, why don't you just add Printexc.record_backtrace foo to the top of your test? That way it will work no matter how backtraces were set outside. This way you don't have to know who is setting it.

We could do something like that, but for existing projects this would require a large amount of work, including modifications on existing developer workflow, flags settings, etc... I am still not convinced the pain is worth the gain.

I still don't expect my build system to mess with runtime settings, but I admit I may be too old school here.

> I don't think there's a dune bug here

If that's not a dune bug, where should we assign the bug?

**Comment by rgrinberg** [comment]
Well we already changing the runtime environment when running your binaries. We add everything in _build/install to your PATH for starters.

Likely the issue lies in one of the libraries that are being linked to your test. One of them is setting `Printexc.record_backtrace` and we do not know which one. Setting a breakpoint in gdb on this function and looking at the backtrace is probably the most promising way to debug this issue.

**Comment by hhugo** [comment]
This is a default in base
https://github.com/janestreet/base/blob/b6430a41ba658335aaeff796b37c10b1d1803637/src/backtrace.ml#L29C1-L30C1
>   (* We turn on backtraces by default if OCAMLRUNPARAM doesn't explicitly mention them. *)

**Comment by ejgallego** [comment]
> base is used by the runtime code of ppx_inline_tests

This I was aware, but why moving the tests to `Util` makes the status of the flag change?

To be clear, I'm not complaining that the flag is set or not set, I'm complaining that the flag value changes by moving the tests to another library.

So we have this setup:
- `main <-{deps}-- Myapp <-{deps} <- Util

Then if place the inline tests in `Myapp` the behavior is different that if place the tests in `Util`

**Comment by hhugo** [comment]
Your `core` lib doesn't depend on util so the compiler doesn't link it to build `test.exe`.
Adding a dependency on util (such as adding an inline test that reference util) make the ocaml compiler link util (and transitively ppx_inline_test runtime lib and base)

**Comment by ejgallego** [comment]
Thanks @hhugo , in the original example `core` depends on `util` tho:

https://github.com/ejgallego/inline_tests_printexn/blob/959fadd8b70e5aa2d2e796cff176405fe3116c7b/dune#L10-L16

In my real example I'm sure `core` was calling `util`, but thanks for this info, I'll investigate on the example a little bit more. (moreover in my example, we use `-linkall` for the executable, but that wasn't needed to reproduce).

**Comment by hhugo** [comment]
>  in the original example core depends on util tho:

The dune dep is not what the compiler cares about, `core` doesn't depend (implementation wise) on `util` based on `ocamlobjinfo core.cmxa`

**Comment by rgrinberg** [comment]
I think we've come to the conclusion that there's not much that can be done by dune here. Please re-open if you have a concrete suggestion on what dune can do to help.

**Comment by ejgallego** [comment]
Indeed I'm not sure how Dune can help here.

I think we should still try to clarify at the level of the whole OCaml eco-system what the ownership of the backtrace flags is; I have seen very different assumptions across different projects, which makes it hard to control it in situation such as Coq where the flag is pretty sensitive.

I'll check locally with OCaml devs and maybe submit an issue upstream.

**Comment by ejgallego** [comment]
Hi folks, I had a quick discussion about backtrace flag status ownership with @gasche , I'm not sure if / what we should do here, I'll try to summarize my understanding of the situation:

- backtraces can be set either via `Printexn` or via `OCAMLRUNPARAM`, the first overrides the second
- applications in general want to control the flag themselves, for example in Coq, the flag has large performance impact
- dune (and JS libs?) want to enable backtraces by default as indeed, it is quite useful for beginners and devs alike

So indeed, it seems to me that the only change we need in Coq is to replace the conditional enable of backtraces with always setting the backtrace status instead of assuming it is `off` by default.

As far as I can see the linking solution should not be a problem _as long_ as the library setting the flag checks that `OCAMLRUNPARAM` is not going to be overriden.

For Coq, that's a bit more tricky, as I'm not sure how to solve the case where:
- dune sets the `OCAMLRUNPARAM=b` flag, in which case Coq wants to ignore it
- the users sets `OCAMLRUNPARAM=b` , in which case we don't want to ignore it.
