### ISSUE TITLE
ocamllex: Shorthand not supported anymore

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/dune#1056]
When I use `(ocamllex (lexer))` as I did in `jbuilder` and [is documented](https://dune.readthedocs.io/en/latest/dune-files.html#ocamllex) in dune, it fails:

```
File "dune", line 1, characters 0-18:
Error: field modules missing
```

When I then switch to

```
(ocamllex
  (modules (lexer))
```

It fails because the parentheses are not necessary anymore, so the documentation is not yet updated from the `jbuild` syntax.

When I remove the parens it, it just works as usual.

**Comment by jberdine** [comment]
See also #1054

**Comment by Leonidas-from-XIV** [comment]
Thanks, it looks like my issue is a duplicate.

**Comment by jberdine** [comment]
Your patch fixes more points in the docs than mine, so probably better to use yours.
