### ISSUE TITLE
Misinterpretation of `META`'s `exists_if` directive by `dune`.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/dune#10563]
It seems that `dune` misinterprets the semantics of `META`'s `exists_if` field. 

The package should exist if any of the file is exists (see [this page](http://projects.camlcity.org/projects/dl/findlib-1.9.6/doc/ref-html/r759.html)), not all of them. Basically [this line](https://github.com/ocaml/dune/blob/478179551bc1531a849c6e8e75aec73168dfc15c/src/dune_findlib/package0.ml#L59) should be turned into an `List.exists`. 

This hides the latest cmdliner (1.3.0) release on 32-bit platforms, see https://github.com/ocaml/opam-repository/pull/25924

**Comment by nojb** [comment]
Good detective work; fix as suggested in #10564.
