### ISSUE TITLE
[PROPOSAL] Support -opaque mode for faster compilation

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1058]
Compilation speed matters more than the quality of binaries in development. With that in mind, and the fact that we already make a similar trade-off for jsoo, I propose that we compile all interfaces with `-opaque` in the `dev` profile.

To reap the benefits we'll have to conditionally create our rules so that cmx dependencies are omitted (I believe that cmo's are already done this way) in the opaque mode that would be enabled by default in `--dev`. 

I don't have a great suggestion for the option name itself, but if we tentatively call it `(compile opaque)` (and `(compile no_opaque)`), then this flag should be appear in the env stanza. This way users will be able to make the trade off between compilation vs runtime speed on a per directory level. The only complication that I believe this will create is that the dependencies for cmx includes will have to calculated carefully. We'll need an additional flag for `Lib.t` such as `opaque: bool` to know whether we should get the cmi or cmi+cmx deps for that library. 

I have a prototype of the new `-opaque`-aware rules running, and I should be able to make a PR for this feature if the proposal is accepted.

EDIT: A couple of points that I've forgotten to mention:

* This feature will probably not work for external libs. Those are going to be usually compiled without `-opaque` anyway (b/c of `--release` mode). This limitation could of course be lifted if we add a flag for opacity in external libs

* Should this feature be automatically on 4.02.3? I know that `-opaque` isn't supported there, so maybe it's best to just disable it rather than seek workarounds.

**Comment by Chris00** [comment]
Out of curiosity, what kind of speed improvement (in %) are we talking here?

**Comment by rgrinberg** [comment]
I managed to get a  300ms reduction on a 4.5s clean build (building cohttp-lwt-unix). Not the most convincing result, but I think the real value of this mode will be in situations with incremental compilation. It should allow for much less recompilation, which unfortunately is harder to measure than I have time for now. Additionally, I have a hunch that will result in better parallelism and will pay off when building on machines with many cores, but I'm not confident enough in this assertion yet.

**Comment by diml** [comment]
Just to be clear, not mentioning cmx dependencies in the rules might not be enough. I haven't checked, but I believe that even if a mli file was compiled with `-opaque`, the compiler will still read the cmx file if it can find it in the search path. i.e. `-opaque` only means: be quiet if you cannot find the cmx file. Could you check whether this is true or not? If that is indeed true, then this feature is a lot more complicated to implement as we need to effectively store the cmx files in a separate directory.

**Comment by lpw25** [comment]
If the mli file is compiled with `-opaque` then the compiler will not even look for the `.cmx` file.

**Comment by rgrinberg** [comment]
@diml does my proposal look alright then? Seems like we'd be able to stick to the simple version.

Btw, even if we had to put the .cmx files in a separate dir, I don't think it would complicate the implementation so much. And anyway, we'll need separate object dirs for private modules for example.
