### ISSUE TITLE
%{bin:program} and program do not behave the same

### ISSUE THREAD

**Issue by hongchangwu** [ocaml/dune#1059]
According to the documentation `(run %{bin:program} ...)` and `(run program ...)` should behave in the same way. However in some cases this doesn't seem to be true.

In my `bin/dune` I have

```
(install
 (section bin)
 (files program))
```

In my `test/dune` I have

```
(rule
 (targets output)
 (deps input)
 (action (run ${bin:program} ...)))

(alias
 (name runtest)
 (package program)
 (action (diff output.expected output)))
```

When I run `dune runtest`, I get

```
Error: Program ${bin:program} not found in the tree or in PATH  (context: default)
```

If I replace ` ${bin:program}` with `program` then it works.

P.S. this used to work with `jbuilder`.

**Comment by rgrinberg** [comment]
Did you forget to rename the `$` to `%`? Note that dune changed the syntax of variables to avoid clashes when embedding shell commands.

**Comment by hongchangwu** [comment]
@rgrinberg yeah that is it. My tuareg dune mode was still happily highlighting the `${bin:program}` syntax so I didn't notice anything was wrong.

**Comment by Chris00** [comment]
@hongchangwu I'm in the process of updating Tuareg-dune.  Hopefully, I'll do a new release in a couple of days...
