### ISSUE TITLE
Promote only works in dev builds

### ISSUE THREAD

**Issue by Timmmm** [ocaml/dune#10598]
There's a compiler called [Sail](https://github.com/rems-project/sail) that generates an `ast.ml` OCaml file during build with this rule:

```
(rule
 (target ast.ml)
 (deps
  (:ast ast.lem))
 (mode (promote (until-clean)))
 (action
  (progn
   (run lem -ocaml %{ast}))))
```

This works fine except there's [an unfixed bug in Merlin](https://github.com/ocaml/merlin/issues/1761) which means it won't let you go-to-definition if the definition is in `_build`. The recommended workaround is to promote the file to the source directory. Not ideal but I thought I'd give it a try by adding this:

```
 (mode (promote (until-clean)))
```

This works in dev builds `dune build`, but for some reason in release builds (`dune build --release`) Dune just completely skips over the rule - it doesn't just not promote `ast.ml`, it doesn't generate it at all.

## Reproduction

```
git clone git@github.com:Timmmm/sail.git user/timh/promote
cd sail
opam install . --deps-only
dune build --release
```

You'll get a load of errors about the `Ast` module missing. Try again but without `--release` and it works.

## Specifications

```
❯ opam --version
2.1.4
❯ dune --version
3.14.0
❯ ocaml --version
The OCaml toplevel, version 5.0.0
❯ cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.9 (Ootpa)
```

**Comment by emillon** [comment]
Yes, that's intended. `--release` implies `--ignore-promoted-rules`.
`--release` roughly means "what makes sense for opam integration", and is described [here](https://dune.readthedocs.io/en/stable/explanation/opam-integration.html).

If you just want to select the release profile without all this extra logic, use `--profile release` instead of `--release`.
But since you're using this in development (hence merlin), the default profile is usually more appropriate.

Thanks

**Comment by Timmmm** [comment]
That's... confusing. Is the idea of promotion that the generated file is checked into Git and you have some check in CI to ensure it is up to date? I've done that before in non-OCaml projects and it works quite nicely (as long as the generated file doesn't depend on build settings). But that also means `promote` isn't really a suitable workaround for https://github.com/ocaml/merlin/issues/1761.

**Comment by rgrinberg** [comment]
> But that also means promote isn't really a suitable workaround for https://github.com/ocaml/merlin/issues/1761.

Indeed it's not
