### ISSUE TITLE
Invalid handling of expected test output that starts with a `>`  in cram directory tests

### ISSUE THREAD

**Issue by wintersteiger** [ocaml/dune#10608]
## Expected Behavior

Say `run.t` of a cram directory test looks like this:

```
  $ echo "> myoutput"
  > myoutput
```

then `dune runtest --auto-promote` should not update the expected output.

## Actual Behavior

Dune keeps adding a line containing `  > myoutput`  every time I run it with `--auto-promote`:

```
  $ echo "> myoutput"
  > myoutput
  > myoutput
  > myoutput
  > myoutput
  > myoutput
  myoutput: not found
  myoutput: not found
  myoutput: not found
  myoutput: not found
  [127]

```

## Specifications

Dune 3.11.1
OCaml 5.2.0
Ubuntu 22.04

**Comment by emillon** [comment]
I thought there was an open issue about this, but maybe I was thinking of #5828.

In summary, that's just how cram tests are. They rely on in-band signaling (command output intersects with command names) so they can't work with commands that include `>` or `$` as part of their output. Here, this parses the output as `echo "> myoutput" myoutput`. (You'll have the same type of interaction with `echo '$ ls'`).

You'll have to postprocess these, using `sed` or similar.

Thanks

**Comment by wintersteiger** [comment]
Yes, but it would be trivial for `--auto-promote` to recognize when it attempts to insert commands instead of expected output. 

(Also, IMHO it's fine to improve upon the original cram spec after 15 years and insert an empty line or an escape character between commands and expected output.)
