### ISSUE TITLE
Library dependencies ordering causing inconsistent assumptions over interface

### ISSUE THREAD

**Issue by horlogeislux** [ocaml/dune#10606]
Hello,

I am using `dune` as my build system for an OCaml project.
I reviewed the [reference for library dependencies](https://dune.readthedocs.io/en/stable/reference/library-dependencies.html).
However it does not specify that the order of libraries matters, and while building my executable I would expect the same warnings or errors, regardless of their ordering.
Thank you for your guidance.

## Expected Behavior

I would expect a "Files ... make inconsistent assumptions over interface" error in the minimal working example below, regardless of the order of `lib_a` or `lib_b`.

## Actual Behavior

The behavior I faced was that in one ordering (`lib_a` `lib_b`), `ocamlopt` prints out the helpful error message ("Files ... make inconsistent assumptions over interface"), but with another ordering (`lib_b` `lib_a`), both `dune` and `ocamlopt` let `lib_a`'s code prevail silently.

1. Is this caused by missing documentation?
2. Is this caused by `dune`?
3. Should this be caught by `ocamlopt` every time or is this behavior justified?

## Reproduction

1. `make`: outputs an error at link time (expected and desired)
2. In ./dune, uncomment the second version of the libraries stanza
3. `make`: does not output an error, and uses `lib_a`'s code (unexepected and undesired)

## Specifications

- Version of `dune` (output of `dune --version`): 3.15.3
- Version of `ocaml` (output of `ocamlc --version`): 4.14.2
- Operating system (distribution and version): Ubuntu 22.04.4 LTS; 6.5.0-35-generic; x86_64

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag):
- The minimal working example [https://github.com/horlogeislux/liborder-dune](https://github.com/horlogeislux/liborder-dune)
- [The two dune build gists](https://gist.github.com/horlogeislux/2e3b63b450463b4ccd35bf3783031844)

**Comment by nojb** [comment]
> * Is this caused by `dune`?

No (although sorting the dependent libraries could be done to obtain a more stable result).

> * Should this be caught by `ocamlopt` every time or is this behavior justified?

Maybe. I think here you get away due to the dead-code optimization of `ocamlopt` which discards one of the `Common` modules. If you add `-linkall` to your linking flags, you should get an `ocamlopt` error due to trying to link two modules with the same name into the final executable.

May be worth opening an issue upstream: https://github.com/ocaml/ocaml/issues

**Comment by horlogeislux** [comment]
> > * Is this caused by `dune`?
>
> No (although sorting the dependent libraries could be done to obtain a more stable result).

In the two gists, both `Running[8]` lines always list the two libraries in alphabetical order (independently of the specified order in the `dune` file), which is why I made this hypothesis.
Would you mind explaining to me why ?

> 
> > * Should this be caught by `ocamlopt` every time or is this behavior justified?
> 
> Maybe. I think here you get away due to the dead-code optimization of `ocamlopt` which discards one of the `Common` modules. If you add `-linkall` to your linking flags, you should get an `ocamlopt` error due to trying to link two modules with the same name into the final executable.

Then I am surprised the dead-code optimization does not work the same in both (symmetric) cases.

I added a new branch `linkall` in the [minimal working example](https://github.com/horlogeislux/liborder-dune) to confirm this hypothesis, by adding `(ocamlopt_flags (:standard -linkall))`.
I indeed get a more descriptive error from `ocamlopt` in _both_ cases:
`Error: Files lib_b/lib_b.cmxa and lib_a/lib_a.cmxa both define a module named Common`.

Is it good practice to always use `-linkall` ? I've read the corresponding [manual page](https://www.ocaml.org/manual/5.2/native.html#s%3Anative-options) but cannot figure out the drawbacks (if any).

> May be worth opening an issue upstream: https://github.com/ocaml/ocaml/issues

Thank you for your advice, I will open this issue there too. 😄

**Comment by nojb** [comment]
> > > * Is this caused by `dune`?
> > 
> > 
> > No (although sorting the dependent libraries could be done to obtain a more stable result).
> 
> In the two gists, both `Running[8]` lines always list the two libraries in alphabetical order (independently of the specified order in the `dune` file), which is why I made this hypothesis. Would you mind explaining to me why ?

Indeed the include flags of the compilation command ("8") are always sorted; however the libraries passed to the linking command ("12") appear in the same order as in the Dune file, which is what causes the puzzling behaviour: the main module of the executable is compiled in both cases agains the same `Common` module (because the compilation flags are always sorted), but in one of the cases, the compiler is being asked to link it against a different `Common` module, which causes the failure.

**Comment by nojb** [comment]
> Is it good practice to always use `-linkall` ? I've read the corresponding [manual page](https://www.ocaml.org/manual/5.2/native.html#s%3Anative-options) but cannot figure out the drawbacks (if any).

No, this flag is meant only for use in specific situations; in general, one shouldn't use it as it may considerably increase the final size of the executable.

**Comment by horlogeislux** [comment]
> > > > * Is this caused by `dune`?
> > > 
> > > 
> > > No (although sorting the dependent libraries could be done to obtain a more stable result).
> > 
> > 
> > In the two gists, both `Running[8]` lines always list the two libraries in alphabetical order (independently of the specified order in the `dune` file), which is why I made this hypothesis. Would you mind explaining to me why ?
> 
> Indeed the include flags of the compilation command ("8") are always sorted; however the libraries passed to the linking command ("12") appear in the same order as in the Dune file, which is what causes the puzzling behaviour: the main module of the executable is compiled in both cases agains the same `Common` module (because the compilation flags are always sorted), but in one of the cases, the compiler is being asked to link it against a different `Common` module, which causes the failure.

Thank you for your confirmation, your analysis is then the same as mine.
About the sorted compilation flags, could you tell me where this logic is in `dune`'s source code ? I looked for it before opening this issue, but to no avail.

Thank you for your kind help, I will mark the issue as closed and will report it to `ocaml`.

**Comment by nojb** [comment]
> About the sorted compilation flags, could you tell me where this logic is in `dune`'s source code ?

The include paths are sorted here, as a side-effect of being put in a set:

https://github.com/ocaml/dune/blob/034e352f5cde97e6866e44e29815da917d022e16/src/dune_rules/lib_flags.ml#L158-L160
