### ISSUE TITLE
`copy_files`: should Dune error out if no files are found?

### ISSUE THREAD

**Issue by jchavarri** [ocaml/dune#10646]
Right now, Dune is lenient in the way `copy_files` work. If I do:

```
(copy_files foo/bar.txt)
```

But if the file `foo/bar.txt` doesn't exist, Dune will proceed just fine, as far as I can tell.

I wonder if it should error out if no files to copy are found given a glob? So that users can also get some help to maintain their `dune` files clean and avoid wasteful work for Dune (parsing, resolving globs, looking for inexistent files...)

**Comment by rgrinberg** [comment]
Raising an error in newer versions of dune seems fine. We could always introduce a mode to disable this check if somebody will need it.
