### ISSUE TITLE
Unbound modules in .ocamlinit

### ISSUE THREAD

**Issue by dalps** [ocaml/dune#10648]
## Context

I hope this is the right place to troubleshoot this issue.

I'm working in VS Code. I use `dune utop` and .ocamlinit files a lot to test my code within a dune project.

Whenever I open a library module or a `Stdlib` module inside an `.ocamlinit` file, I get an `Unbound module` error from `ocamllps` and any definition referencing the module becomes a red underline mess.

So the only way to debug an .ocamlinit is: run `dune utop`, check for errors there, quit the REPL if there's any, fix and repeat; which is not a very ergonomic workflow for initializing utop in a dune project.

## Expected Behavior

IntelliSense provided by `ocamllsp` working properly in .ocamlinit files and recognizing opened modules.

## Actual Behavior

`ocamllsp` throws an `Unbound module` error in the editor, and suggests calling `dune build`. This is what it looks like:

![image](https://github.com/ocaml/dune/assets/96267363/ba4f29fc-80aa-4059-a57b-33b36e3ced8d)

Calling `dune build` or `dune build .ocamlinit` doesn't help, the errors persist.

Is dune not linking my .ocamlinit? How do I tell dune to add the .ocamlinit to the build chain?

## Reproduction

1. Create a dune project `dune init proj foo` and open it in VS Code
2. Create an `.ocamlinit` in the root of the project and type `open Foo`
3. An error from `ocamllsp` like the above image should pop up

## Specifications

- Version of `dune` (output of `dune --version`): 3.15.2
- Version of `ocaml` (output of `ocamlc --version`): 5.2.0
- Operating system (distribution and version): Ubuntu 22.04 on WSL 2
- Version of `ocaml-lsp-server` (output of `opam list`): 1.18.0~5.2preview

**Comment by nojb** [comment]
The `.ocamlinit` file is not compiled, it is only read and interpreted by the toplevel, so I don't think that OCamlLSP/Merlin will be able give you typechecking on that file. In any case, I don't think this is something that Dune could do much about; if anything you should ask in the Merlin or OCamlLSP issue trackers.

**Comment by rgrinberg** [comment]
To re-iterate nojb, dune does not use .ocamlinit for anything. .ocamlinit is a feature of the toplevel (utop in your case), so there's not much that we can do.

**Comment by dalps** [comment]
Thank you, this helped narrow down the problem at least.
