### ISSUE TITLE
5.3 support: rename of ocamlc -config variables

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#10652]
In https://github.com/ocaml/ocaml/pull/13201 (more precisely, in https://github.com/ocaml/ocaml/commit/51e5cf226b39986abf03cbaad47cf49a1c35bc69), some variables in `ocamlc -config` is reworked:

- `ocamlc_cflags` -> `bytecode_cflags`
- `ocamlc_cppflags` -> `bytecode_cppflags`
- `ocamlopt_cflags` ->`native_cflags`
- `ocamlopt_cppflags` -> `native_cppflags`

This can be tested by building for example `base64.3.4.0` on `5.3+trunk`.

In terms of implementation, we need to change the key names in `ocaml_config` and `configurator`, in a way that uses the right key depending on the current ocaml version.

**Comment by rgrinberg** [comment]
Was there any justification from the compiler devs for making this change? Seems like it's going to cause a lot of breakage and I'm not sure what the benefits are.

**Comment by nojb** [comment]
I don't think this was discussed. My impression is that the change was done without thinking about the potential breakage. I think it would be a good idea to bring this up upstream.

**Comment by anmonteiro** [comment]
This is already being discussed in the original PR.

**Comment by emillon** [comment]
This can be closed once #13244 is merged
