### ISSUE TITLE
Point to (alias) when action field is absent

### ISSUE THREAD

**Issue by jchavarri** [ocaml/dune#10685]
Sometimes, I use `rule` stanzas to consolidate two inner targets, e.g.:

```clojure
(rule
 (alias parent)
 (deps
  (alias child_one)
  (alias child_two)))
```

But I get `Error: field action missing` from Dune, so I end up using something like this:

```clojure
(rule
 (alias parent)
 (deps
  (alias child_one)
  (alias child_two))
 ; empty action
 (action (progn)))
```

I wonder why is the `action` field required? Is there anything wrong with having a rule with no action, but just putting together a bunch of `deps`? And as a side question: is there a better way for empty actions than using `progn`?

**Comment by nojb** [comment]
This is precisely what the `alias` stanza allows you to do:
```
(alias
  (name parent)
  (deps (alias child_one) (alias child_two)))
```
It may make sense to merge the two concepts, but that's a separate discussion to be had.

**Comment by jchavarri** [comment]
Thanks @nojb ! Do you think it'd make sense to have the error message point users from the `rule` stanza to the `alias` stanza to facilitate discovery?

**Comment by emillon** [comment]
Thanks, I relabeled accordingly. I used `docs` but the recommended way is to improve the error message by adding a hint when the field is absent.

**Comment by emillon** [comment]
@maiste will have a look later
