### ISSUE TITLE
ocaml 5.2: warning 53 with (wrapped (transition))

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#10689]
When using `(wrapped (transition))` with ocaml 5.2, warning 53 (misplaced-attribute) triggers. This seems to be a bug in the ocaml compiler (see https://github.com/ocaml/ocaml/issues/13054#issuecomment-2205839590) but we might be able to work around it in dune.

**Comment by nojb** [comment]
As explained in https://github.com/ocaml/ocaml/issues/13054#issuecomment-2206790839, I believe this is rather a bug in the way Dune implements these "transition" modules.

**Comment by emillon** [comment]
Thanks. This is a bit over my head TBH:

> Dune first builds `bar.cmi` and `bar.cmo` from `bar.ml-gen` and this part works well (`bar.ml-gen` contains a top-level attribute but no `.cmi`). However, when it is the turn of the native-code compiler, `bar.cmi` already exists (and contains the expected deprecation attribute), so the top-level attribute in `Bar.ml-gen` is correctly ignored by the compiler, hence the warning.

What would be a good way to do this? I can see 2 ways:
- generate a `mli` file with the attribute, and a `ml` file without it. this is an extra compilation step.
- ignore warning 53 when building the native part.

is there a better way?

**Comment by nojb** [comment]
> is there a better way?

I cannot think of anything. At this point, maybe disabling w53 is the easiest quick fix.
