### ISSUE TITLE
Stuck on `Processing 1/3` after `opam install dune`

### ISSUE THREAD

**Issue by OmerKural** [ocaml/dune#10701]
## Expected Behavior
Install `dune` using command `opam install dune` successfully.

## Actual Behavior
Stuck here:
>opam install dune
The following actions will be performed:
=== install 1 package
  ✶ dune 3.16.0

><><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Processing  1/3: [dune.3.16.0: extract]

I have been waiting on this for half an hour now. I suppose it shouldn't take that much time to complete installing.

After interrupt with `Ctrl+C`:
><><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] User interruption

><><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ ▼ fetch dune 3.16.0
└─
╶─ No changes have been performed

## Reproduction
Install `opam` version `2.2.0`.
Run command: `opam install dune`

## Specifications

- Version of `dune` (output of `dune --version`):
- Version of `ocaml` (output of `ocamlc --version`): 2.2.0
- Operating system (distribution and version): Windows 10

**Comment by emillon** [comment]
Hi,
At that point, the sources of `dune` haven't even been retrieved, so I would suspect that this issue is more relevant to ocaml/opam.
