### ISSUE TITLE
Oneshot webserver used in some pkg tests fails to send large files

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#10741]
This issue seems to be related to the webserver shutting down before the transfer is complete. I thought I fixed the issue in https://github.com/ocaml/dune/pull/10705, but it still happens for sufficiently large files. As this is a race between the transfer completing and the server shutting down, the maximum size for a successfully transferred file is platform-specific. On my linux machine, I can consistently reproduce this issue attempting to transfer a 20MB file.

Reproduced in https://github.com/ocaml/dune/pull/10742

**Comment by rgrinberg** [comment]
Maybe we should switch to a more reliable HTTP server in our tests. No reason to develop one inside the repo.

**Comment by gridbugs** [comment]
Yeh fair point. Maybe there's something in opam that fits our needs.

**Comment by moyodiallo** [comment]
I've tried reducing the buffer of `webserver_oneshot` from 4096 to 512 and it turns out working super well. I even tried to test it with 1000M #10742 and still working. Maybe the transfer is faster when the buffer is lower.
