### ISSUE TITLE
Dune generated opam files are not correct when the version is `= version`

### ISSUE THREAD

**Issue by FardaleM** [ocaml/dune#10758]
## Expected Behavior
When `generate_opam_files` is enabled and a dependency has the constraint `(= version)`, the opam file should contain the constraint `{= version}`

## Actual Behavior
The constraint is currently `{= "version"}`.

## Reproduction

By using the following `dune-project` file:
```
(lang dune 3.13)

(generate_opam_files true)

(package
  (name bug)
  (depends (bug-lib (= version)))
)
```
and the following `dune` file:
```
(executable
 (name bug))
```
with an empty `bug.ml` file, the command `dune build` will generate the `bug.opam` file.

## Specifications

- Version of `dune` (output of `dune --version`): 3.16.0
- Version of `ocaml` (output of `ocamlc --version`): 5.2.0
- Operating system (distribution and version): Debian Unstable

**Comment by emillon** [comment]
Hi,
This is the intended behavior, there's no difference between `"version"` and `version` in dune files. To generate `version` variable in opam files, use `:version` in the dune file:

    (depends (bug-lib (= :version)))

I'll add that as an example in the docs.
