### ISSUE TITLE
pkg: discussion on how could be the support for `depexts` (system dependencies)

### ISSUE THREAD

**Issue by moyodiallo** [ocaml/dune#10765]
This issue is about gathering some ideas on how dune package management could support depexts (system dependencies).

Opam uses `opam-depexts` plugin to handle them. During an installation of an opam package, opam takes the information from opam file field named `depexts` and install them according to the OS system.

Dune doesn't support `depexts` yet, since pkg management that could change. So the question could be, how to integrate this functionality and what could be the expectations.

Some questions came to my mind:
- having a `depexts` stanza inside dune-project ?
- proposing the user to install the `depexts` when the build failed ?
- before starting the build install all the depexts ?
- proposing the install commands according to the OS system ?

**Comment by rgrinberg** [comment]
There was some discussion here as well https://github.com/ocaml/dune/issues/9294

**Comment by moyodiallo** [comment]
> There was some discussion here as well #9294

I didn't notice, most of the cases are already listed there and this one could be closed.
