### ISSUE TITLE
Error building library with indirect dependency on object file

### ISSUE THREAD

**Issue by Hsodergren** [ocaml/dune#10785]
There seems to be a problem when building libraries with indirect dependencies to object files. That is, when calc.ml depends on dep.c which in turn depends on add.o.

I get the following error:
```
/usr/bin/ld: lib/add.o: in function `add':
add.c:(.text+0x0): multiple definition of `add'; lib/libc_test_stubs.a(add.o):add.c:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
```

The issue is also discussed at [discuss.ocaml.org](https://discuss.ocaml.org/t/build-error-when-using-c-stubs-and-external-object-file/15041).

## Reproduction

- PR with a reproducing test: [pull request](https://github.com/ocaml/dune/pull/10784)

## Specifications

- Version of `dune`: 3.16.0
- Version of `ocaml`: 5.2.0

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag): [dune verbose output](https://gist.github.com/Hsodergren/ed2d33f921fdc6ab5cc1382fdba122a5)

**Comment by nojb** [comment]
Thanks, I believe #10783 should fix it. Can you give it a try and confirm?
