### ISSUE TITLE
[dune-pkg] Relocking files with `dune build`

### ISSUE THREAD

**Issue by maiste** [ocaml/dune#10842]
Following the discussion during the _Dune Dev Meeting_ ([cf notes](https://github.com/ocaml/dune/wiki/dev-meeting-2024-08-21)), there was the discussion about re-locking the file with `dune build` and `dune build --watch`. The retain solution was:

- `dune build` would print an error message when it is run, and it detects the dependencies have changed. The message would ask the user to re-run `dune pkg lock`. The user could then re-run `dune build` and the error about the dependency must be gone.
- `dune build --watch` would pause and display a message asking for the user to run the `dune pkg lock. Once it is done, it would unpause automatically as the _watch mode_ would detect the dependencies have changed. Thus, it would recompute the dependency graph and re-build what needs to be re-built. This would be done by checking the dependency hash and check when it changes.

This solution is a compromise between _auto-locking_ and _full manual locking_, as it would prevent the user to have their dependencies updated without noticing. 

There are some questions left here:
- Should we add a config flag to have this as an experimental feature, or should it automatically detect the lock file and be available without it?
- Is there a way in the current behavior of Dune to ""pause"" the _watch mode_?
- @rgrinberg, you mentioned the fact that people could hard-code the _opam_ commit in their workspace file, and we could take it into account when rebuilding. Is this something we want to consider here, or should we exclude this for now? IIUC, running `dune pkg lock` will ~`opam update` our package set: do we want to warn the user if the _commit_ is hard-coded?

**Comment by rgrinberg** [comment]
> Should we add a config flag to have this as an experimental feature, or should it automatically detect the lock file and be available without it?

It seems like the behavior is a strict improvement so there's no need for a flag.

> Is there a way in the current behavior of Dune to ""pause"" the watch mode?

You don't need to pause anything manually. It's enough to just verify the lock file before generating any rules. An error during this stage, would prevent dune from doing anything.

>  you mentioned the fact that people could hard-code the opam commit in their workspace file, and we could take it into account when rebuilding. Is this something we want to consider here, or should we exclude this for now? IIUC, running dune pkg lock will ~opam update our package set: do we want to warn the user if the commit is hard-coded?

I'd say let's not do anything for now. Would like to hear some demand from users before developing this workflow further.

**Comment by maiste** [comment]
Closing this issue as it has been done in #10851 and #10852.
