### ISSUE TITLE
[Windows] external C libraries flags break linking

### ISSUE THREAD

**Issue by dmtrKovalenko** [ocaml/dune#10844]
## Expected Behavior

When there is a c stubs and there are compiler flags provided Windows build should behave the same way as linux build. 

Here is an example of foreign stabs with custom flags provided using dune configurator
```
 (flags
  (-w -40 -w +26)
  (:include png_flags.sexp))
 (foreign_stubs
  (language c)
  (names ReadPng)
  (flags
   (:include png_c_flags.sexp)))
```

## Actual Behavior

I made a simple repository with a C library that perfectly compiles and runs on windows https://github.com/dmtrKovalenko/test_opam_windows/actions/runs/10505853189 until you are trying to provide some external dependencies

Here is my [other PR](https://github.com/dmtrKovalenko/odiff/pull/104) with totally same build system but the C library are linking with external dependencies and now for some reason on the very last step when linking the final executable it fails with **all the symbols not defined even the caml runtime symbols**

```
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: io/tiff/libTiff_stubs.a(ReadTiff.o): in function `read_tiff_file_to_tuple':
/cygdrive/d/a/odiff/odiff/_build/default/io/tiff/ReadTiff.c:14: undefined reference to `__imp_caml_get_domain_state'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: /cygdrive/d/a/odiff/odiff/_build/default/io/tiff/ReadTiff.c:33: undefined reference to `__imp_caml_ba_alloc'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: /cygdrive/d/a/odiff/odiff/_build/default/io/tiff/ReadTiff.c:45: undefined reference to `__imp_caml_alloc_tuple'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: /cygdrive/d/a/odiff/odiff/_build/default/io/tiff/ReadTiff.c:46: undefined reference to `__imp_caml_modify'
```

## Reproduction

- Making PR into dune would be pretty complicated here is a reproducable issue in the open source repository. Just try to build the PR: 
https://github.com/dmtrKovalenko/odiff/pull/104
## Specifications

- Version of `dune` (output of `dune --version`): 3.16.0
- Version of `ocaml` (output of `ocamlc --version`) 5.2.0
- Operating system (distribution and version): windows-x64

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag):
https://gist.github.com/dmtrKovalenko/32d8d98732589275cd4bebb971792e33

**Comment by nojb** [comment]
Your log shows that the linking command is passing `-cc gcc`; this may be related to the failure. Note that this flag does not just expect just the executable name, but the whole command; it is not for casual use in any case (see https://github.com/ocaml/ocaml/issues/12284#issuecomment-1574812420).

![image](https://github.com/user-attachments/assets/b1948013-e731-41eb-8cde-9d10ab0821ee)

**Comment by dmtrKovalenko** [comment]
Thanks and it was definitely one of the issues. But with your help I was able to nail down all the other issues.
