### ISSUE TITLE
Redirecting the stderr of Dune causes recompilation of C stubs

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#10882]
Dune decides whether to pass `-fdiagnostics-color` to the (GCC-style) C compiler or not depending on whether `stderr` is a terminal or not. This means that if one does `dune build 2>/dev/null` followed by `dune build`, the second command will rebuild all C stubs, which seems wrong.

One way to approach this may be to always make pass the `-fdiagnostics-color` flag to GCC, but filter out the ANSI codes in Dune, like it does in other cases (if I understand correctly).

**Comment by nojb** [comment]
cc @MisterDA

**Comment by anmonteiro** [comment]
This is only tangentially related, but it looks like we have the same issue for the OCaml compilers:

https://github.com/ocaml/dune/blob/d9b0e2e3d9e14068a4a3e7ad25277666d3914279/src/dune_rules/global.ml#L8-L11


e.g. in OCaml 5.2 where `Misc.Style.inline_code` is either bold text or quoted text depending on `!Color.enabled`, you can write a cram test that behaves differently according to whether it's piped to `cat` or not
