### ISSUE TITLE
stdune pp dependency outdated

### ISSUE THREAD

**Issue by JasonGross** [ocaml/dune#10934]
You need to install `pp` version 1.2.0. There are some incompatible changes in version 2.0.0.
This dependencies seems to have been fixed in the opam repository but not in the [dune's github repository](https://github.com/ocaml/dune/blob/3f31387ec20b3d6f920999bdae35cdcfdd16667a/stdune.opam#L18)

_Originally posted by @vouillon in https://github.com/ocaml-wasm/wasm_of_ocaml/issues/80#issuecomment-2359325061_

-------

So it seems https://github.com/ocaml/dune/blob/3f31387ec20b3d6f920999bdae35cdcfdd16667a/stdune.opam#L18 needs updating

**Comment by Leonidas-from-XIV** [comment]
Fixed by @gridbugs in #10938 by updating our code to 2.0.
