### ISSUE TITLE
pkg: Failure on non-atoms in `depends` fields

### ISSUE THREAD

**Issue by Julow** [ocaml/dune#10956]
## Expected Behavior

Dune works differently than Opam for some advanced formula, is here any way to achieve this with the newest Dune ?

## Actual Behavior

Odoc's opam file has dependencies like these:

```
depends: [
  ("ocaml" {< "4.04.1" & with-test} | "sexplib0" {with-test})
  ("ocaml" {< "4.07.0" & with-test} | "bisect_ppx" {with-test & > "2.5.0"})
]
```

These means that we depend on `"sexplib0" {with-test}`, but only if the solution also includes `ocaml >= 4.04.1`. Similarly for bisect_ppx.

```
File "odoc.opam", line 1, characters 0-0:
Error: Expected formula to be a conjunction of atoms but encountered non-atom
term 'ocaml {< "4.04.1" & with-test} | sexplib0 {with-test}'
```

## Reproduction

Running `dune pkg lock` in https://github.com/ocaml/odoc shows the bug.

## Specifications

- Dune version `17071ec`

**Comment by Leonidas-from-XIV** [comment]
Thanks for the report. We're aware of this issue in as ticket #10837 with proposed solution in #10918.

**Comment by Julow** [comment]
Thanks! Sorry I failed to find it.
