### ISSUE TITLE
base and dune.configurator are incompatible

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1097]
Since both offer a toplevel `Caml` module. Implementing #1017 should fix this issue I believe if we are sick of renaming stuff.

This is affecting real users as shown here: https://discuss.ocaml.org/t/from-jbuilder-to-dune-with-a-ctypes-project/2371/3

**Comment by diml** [comment]
#1017 would only cause `caml.cmi` to not be installed, right? I don't believe that's enough as for the linking step all compilation unit names must be unique.

**Comment by rgrinberg** [comment]
Ah yeah, I agree that wouldn't be enough. Automatic name mangling for the private libs, and corresponding `-open` for the users of these libs would solve this issue however.

**Comment by rgrinberg** [comment]
I believe diml already fixed this.
