### ISSUE TITLE
When ocamlformat is installed as a dev-tool, `dune fmt` promotes stale versions of files

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#10991]
When `DUNE_CONFIG__LOCK_DEV_TOOL=enabled` is set (or when using the Dune Developer Preview), running `dune fmt` always promotes the file in the state it was in when `dune fmt` was first run.

To reproduce:
1. Run `dune fmt` to format the project
2. Change a file
3. Run `dune fmt` a second time

The changed file will be reverted back to its state after the first invocation of `dune fmt`.

Repro test added in https://github.com/ocaml/dune/pull/10993

Fixed in https://github.com/ocaml/dune/pull/10990

**Comment by maiste** [comment]
As #10990 has been merged should we consider closing this?
