### ISSUE TITLE
Failure of [coqc --config] with Coq in a workspace

### ISSUE THREAD

**Issue by rlepigre** [ocaml/dune#11011]
Variable expansion based on the output of `coqc --config`, such as `%{coq:version.major}`, is broken when Coq itself is in the workspace. This leads to errors like the following:
```
Error: Could not expand %{coq:version.minor} as running coqc --config failed
```
The reason making `coqc` fail is that it does not know where to find the standard library.

This can be reproduced using the following:
```bash
mkdir workspace_bug
cd workspace_bug

echo "(lang dune 3.8)" > dune-workspace

git clone git@github.com:coq/coq.git

mkdir test
echo "(rule (action (with-outputs-to coq-version.txt (echo \"%{coq:version.major}\"))))" > test/dune

dune build test
```

CC @ejgallego @Alizter

**Comment by rlepigre** [comment]
Note that I'd expect at least the expansion of variable that do not depend on the standard library (like version stuff) to always work, regardless of whether the standard library is available in the workspace or not.

**Comment by Alizter** [comment]
@rlepigre It is a quirk of Coq, at least at the time, that the standard library location was required to output the version.

Not sure what the best fix is here.

**Comment by rlepigre** [comment]
Yeah, that's what I was thinking. Another option would be to rely on `coqc -boot -noinit --version` instead.

**Comment by Alizter** [comment]
@rlepigre IIRC `-boot -noinit` had not effect on this, but this may have changed.

**Comment by rlepigre** [comment]
On the version I tested (basically 8.19) it has an effect for `--version`. It does not have an effect for `--config` though.

**Comment by ejgallego** [comment]
Thanks again for the report @rlepigre , I am wondering on your test case tho, don't you define a `(lang coq ...)` version?

I was under the impression we had fixed this, but indeed, let's look into what is going on.

**Comment by rlepigre** [comment]
I'm not sure what you mean with `(lang coq ...)` @ejgallego, I do have the following in `coqlib/dune-project`:
```
(lang dune 3.8)
(using coq 0.8)
(name coqlib)
```

**Comment by ejgallego** [comment]
I meant on the example above, you do: `echo "(lang dune 3.8)" > dune-workspace` , so I wonder what dune lang version the example in `test` picks.

Indeed, I don't think the test should be even accepted, `coq:` variables should be disabled if you don't declare a `dune-project` with the right setup.

**Comment by ejgallego** [comment]
Indeed @rlepigre I think https://github.com/ocaml/dune/pull/10631 should have fixed this.

But that won't happen until Dune 3.17 I'm afraid, but maybe you can backport the patch?

**Comment by rlepigre** [comment]
Ah, I see, thanks! I somehow missed that issue and MR.

**Comment by ejgallego** [comment]
Easy to miss, as the changelog for `main` now is on several files under `doc/changes`.

I wouldn't be surprised if we have more problems in this area, please don't hesitate to reopen.
