### ISSUE TITLE
Failed to download dune tar

### ISSUE THREAD

**Issue by nojaf** [ocaml/dune#11018]
## Expected Behavior

`curl -fsSL https://get.dune.build/install | sh` downloads dune and other magic.

## Actual Behavior

```
curl: (22) The requested URL returned error: 404

error: Failed to download dune tar from "https://get.dune.build/2024-10-17/x86_64-unknown-linux-musl/dune-2024-10-17-x86_64-unknown-linux-musl.tar.gz"
```

## Reproduction

I was trying this in Gitpod, but I'm assuming this is a larger issue.

1. Optional, open new gitpod or devcontainer
1. `curl -fsSL https://get.dune.build/install | sh`

## Specifications

- Version of `dune` (output of `dune --version`):
- Version of `ocaml` (output of `ocamlc --version`)
- Operating system (distribution and version):

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

## Additional information 

Please add some CI so this works very day going forward.

**Comment by maiste** [comment]
As it is related to the distribution and not to the code of Dune, I have reopened this issue in [ocaml-dune/binary-distribution](https://github.com/ocaml-dune/binary-distribution/issues/98), the repository in charge of publishing the dune preview.

I close this one.
