### ISSUE TITLE
[1.1] Problem when omitting `name` field?

### ISSUE THREAD

**Issue by ejgallego** [ocaml/dune#1102]
Dear Dune devs,

when building a simple project with Dune 1.1 I get:

```
     ocamlc .c.find.objs/c.find.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/egallego/.opam/4.07.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w -49 -g -bin-annot -I .c.find.objs -no-alias-deps -o .c.find.objs/c.find.cmo -c -impl c.find.ml-gen)
File "c.find.ml-gen", line 2, characters 13-20:
Error: Syntax error
```

if I add the `name` field the error goes away. The contents of the sample project are:

```sexp
(* file: /dune *)
(library
 (public_name c.find)
 (libraries dune.usexp))
```

```ocaml
(* file /f.ml *)
let _ = Usexp.Atom.of_int 3
```

**Comment by rgrinberg** [comment]
Ah that's right, not all public names are valid names. We should really validate the name even after defaulting. In your case you will indeed need to pick a valid `name` as `c.find` will not work as a module name.

**Comment by rgrinberg** [comment]
Another possibility for us is to replace the dots with underscores. So the implied `name` would be `c_find`. Not sure what is better.

**Comment by hcarty** [comment]
Explicit names are probably better than rewriting something automatically.  Automatic rewriting would require coming up with a well-defined set of rewriting rules.

Agreed, though, that having a friendly error message in this case is important.

**Comment by diml** [comment]
```
(* file: /dune *)
(library
 (public_name c.find)
 (libraries dune.usexp))
```

FTR, `dune.usexp` is an internal library and is not currently part of the public API of dune. In particular it is not covered by the semantic versioning of dune and its API is likely to change.
