### ISSUE TITLE
Flag duplication in `external-lib-deps` suggestion

### ISSUE THREAD

**Issue by hcarty** [ocaml/dune#1106]
When building a project with multiple missing dependencies:
```
$ jbuilder build --dev
File "src/proxy/jbuild", line 5, characters 20-27:
Error: Library "lwt_ppx" not found.
Hint: try: dune external-lib-deps --missing --profile dev --profile dev @install
```
`--profile dev` is listed twice.  `dune` will reject the invocation unless the extra `--profile dev` is removed.

**Comment by emillon** [comment]
Thanks for the bug report. I think that we can just remove the profile in that case.

**Comment by hcarty** [comment]
Thanks for the quick fix!
