### ISSUE TITLE
A flag to `dune runtest` to exit after first test failure

### ISSUE THREAD

**Issue by WardBrian** [ocaml/dune#11060]
## Desired Behavior

A `--fail-fast` (or even better, `--max-failures=N`, where N=1 means "exit after the first test failure") flag, for circumstances where the important thing is not which tests failed, but simply that _some_ did. 

## Example
This has several uses, but one would be to make [mutation testing](https://github.com/jmid/mutaml) a bit easier and more efficient

**Comment by Alizter** [comment]
`--stop-on-first-error` is what you are after.
