### ISSUE TITLE
[PROPOSAL] Dynamic packages

### ISSUE THREAD

**Issue by nholland94** [ocaml/dune#1112]
# Problem

Currently, dune determines packages that are available to build by looking at `.opam` files in the root directory. This is a pain point for large repositories which include many packages. It would be nice to be able to dynamically specify packages that are available for a dune project.

# Proposed Solution

Instead of loading all packages into a map once at the start of loading a dune project, rewrite package resolution to attempt to build a `<package-name>.opam` first, then load the package info from that file in the build directory. This would allow dune projects to code generate these files from the root dune project file in whatever manner they wish to.

Alternatively, the root dune project file could have a special entry to specify extra packages available in the project that are not defined by a `.opam` file. Dune could then generate a `.opam` file for the specified packages.

**Comment by diml** [comment]
Generating opam files is fine. What would be hard is generating dynamically new package names. Currently all the package names that exist are now statically, which simplifies a lot things.

The goal is to eventually get dune to generate the opam files. At this point packages will indeed be declared in the `dune-project` file. The syntax is not set yet, but it could look like this:

```scheme
(lang dune 1.x)
(name blah)
(packages foo bar)
```

Even if we don't generate opam files yet, this `package` stanza could be added now if it's useful.

**Comment by hcarty** [comment]
@diml Having a `package`/`packages` stanza in `dune-project` to avoid the need for `*.opam` files would be very nice to have.  Particularly for executable projects which may not be targeting opam now or potentially ever (ex. experiments and private projects).

**Comment by diml** [comment]
Ok. This is simple change, are you happy to write a PR for it?

All you need to do is modify the `parse` function in `src/dune_project.ml` as follow: add `and package_names = field "packages" (list string)` just after the `and version = ...` and then somehow merge the `package_names` and `packages` variables. `packages` is a map from package names to `Package.t` values and is built by looking at the opam files in the current directory.

**Comment by rgrinberg** [comment]
You are now allowed to define packages in the dune-project file.
