### ISSUE TITLE
Install the "flexdll" package in the toolchains directory on windows

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#11158]
Dune installs the ocaml compiler package to ~/.cache/dune/toolchains when using package management features. On unix systems the compiler has no dependencies so the only package that must be installed this way is the compiler itself. However on windows the compiler (specifically ocaml-base-compiler) depends on the package [flexdll](https://github.com/ocaml/flexdll). On windows, flexdll must be installed to the toolchains directory along with the compiler in order to resolve the compiler's dependency on flexdll.

**Comment by gridbugs** [comment]
Note that dune currently has some logic for rewriting the compiler's build and install commands to install the package to the toolchains directory rather than inside the project's _build directory. This logic is highly specialized to build and install commands for the ocaml-base-compiler's opam package ind it won't generalize to flexdll.

**Comment by gridbugs** [comment]
This turns out not to be necessary. When ocaml is built it needs access to flexdll but after that point flexdll can be removed. Thus there's no reason to keep flexdll around in a user-wide place such as the toolchains dir. Installing it into the _build directory of the first dune project that needs the compiler is an acceptable solution, so no work here is needed.

**Comment by nojb** [comment]
> When ocaml is built it needs access to flexdll but after that point flexdll can be removed.

Are you sure? `flexlink` is used as a linker on Windows, it is used whenever OCaml builds an executable or plugin in native code.

**Comment by nojb** [comment]
> That has been my experience. I built and installed the compiler manually, pointing `./configure` at a checkout of flexdll. Then I deleted flexdll and tried using the compiler and it worked fine. @dra27 is there a case where it's necessary to still have flexdll around when the compiler is running?

Note that depending on how you configure OCaml, `flexlink` will be installed next to the compiler.

**Comment by dra27** [comment]
> That has been my experience. I built and installed the compiler manually, pointing `./configure` at a checkout of flexdll. Then I deleted flexdll and tried using the compiler and it worked fine. [@dra27](https://github.com/dra27) is there a case where it's necessary to still have flexdll around when the compiler is running?

Sorry for the slow reply - the flexdll package is indeed _not_ needed after the compiler has been built. As @nojb correctly notes, `flexlink` will have been built with the compiler and installed to the bin directory, and the lib directory will contain an extra subdirectory `flexdll` containing the two required objects.

The sources kick around in opam because we don't have a neat way in opam packages at the moment to specify that sources come from multiple places (but it's on my radar for the future!)
