### ISSUE TITLE
The `dev-switch` Makefile target doesn't work on Windows

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#11157]
The `dev-switch` target uses commands like `test` and `awk` which are not available on windows.

**Comment by nojb** [comment]
I don't understand: if you have `make` available in your environment, then surely you would have `test` and `awk`, no? What am I missing?

**Comment by gridbugs** [comment]
I use the `ezwinports` distribution of `make` which is a winget package that only includes the `make` program. At the time of writing I was using powershell for windows development and didn't have any other posix tools in my path. I've since switched to using git bash as my shell and it comes with `test` and `awk`. It's also possible to modify your PATH in powershell to allow those commands to run from powershell.

I'm willing to concede that this was user error and a more experienced windows user wouldn't run into this issue.

**Comment by gridbugs** [comment]
Closing this as using ocaml on windows requires a bunch of unix tools already, and so `test` and `awk` will likely already be installed when users try to run `make dev-switch` on windows.
