### ISSUE TITLE
Handling of `=` and quotes in `run` stanzas

### ISSUE THREAD

**Issue by maroneze** [ocaml/dune#11168]
## Expected Behavior

When running a `run` command in a rule, I didn't expect it to be affected by the presence of quotes and/or `=` sign.

## Actual Behavior

Commands inside a `run` stanza seem to be modified, at least for some programs (`pandoc`, in my case). I couldn't find any mentions to it [in the documentation](https://dune.readthedocs.io/en/stable/reference/actions/run.html).

For instance, consider the commands below, used to produce a small test project with an empty `.md` file and a `run` stanza using pandoc:

```
dune init proj test
cd test
mkdir doc; touch doc/doc.md
echo "(rule
  (targets doc.pdf)
  (deps doc.md)
  (action (run pandoc --metadata title=\"Doc Manual\" %{deps} -o %{targets}))
)" > doc/dune
```

(The escaped quotes are due to using `echo` to write them to a file.)

Running `dune build` results in:

    pandoc: Doc Manual: withBinaryFile: does not exist (No such file or directory)

Using `--verbose` provides a hint as to why this happens:

    (cd _build/default/doc && /usr/bin/pandoc --metadata title= 'Doc Manual' doc.md -o doc.pdf)

It seems that Dune not only replaced the double quotes with single quotes (which should be fine), but it also added a space after the `=` sign (which breaks it).

Therefore, if I remove the double quotes and the space in `"Doc Manual"`, it works. Or if I replace the `run` command with a `system` command where everything is inside double quotes (and thus the inner quotes are escaped), it works.

So, I wonder if this is intentional, but inevitable (in which case it might be worth a quick mention in the doc), or a bug.

## Reproduction

Run the commands from the code example above.

## Specifications

- Version of `dune` (output of `dune --version`): 3.16.1
- Version of `ocaml` (output of `ocamlc --version`): 5.1.1
- Operating system (distribution and version): Fedora 40

**Comment by nojb** [comment]
The command-line passed to `(run)` is first parsed into "atoms" before the final command-line is built and invoked. Literal double quotes delimit such atoms; in particular I think that what you want is `"title=Doc Manual"` to appear in your Dune file, since you want this whole string to be passed as a single argument to the program. Makes sense?

**Comment by Leonidas-from-XIV** [comment]
I think this is a very good explanation and the solution should fix @maroneze's problem.

I'm closing this; feel free to reopen if there's still some parsing issue or something of that sort.
