### ISSUE TITLE
FreeBSD

### ISSUE THREAD

**Issue by ndowens** [ocaml/dune#1116]
I just ported dune to freebsd on my machine, if I try to use it to build packages that use jbuilder I get

jbuilder build @install --dev
     getconf (internal)
getconf: no such configuration parameter `_NPROCESSORS_ONLN'

**Comment by diml** [comment]
Does the build succeed or fail? Basically dune tries a few commands to determine the number of jobs it can use and ignore the ones that fails. However, it's possible that we forgot to ignore stderr.

**Comment by ndowens** [comment]
It succeeds.
