### ISSUE TITLE
Allow cascading flags

### ISSUE THREAD

**Issue by dra27** [ocaml/dune#113]
It would be useful to have some way of being able to set some stanzas at a higher level - especially `flags`, `ocamlc_flags` and `ocamlopt_flags`. For example, developer builds may want to include either more warnings or `-warn-error A` and it's slightly tedious to have to convey that to multiple jbuild files.

Perhaps `flags` could be added to `jbuild-workspace`? Or have some setting propagate from jbuild files at a higher level (for example, `src/jbuild` containing flags which get automatically added in `src/lib1/jbuild`, `src/lib2/jbuild` but are conveniently ignored for `vendor/externallib/jbuild`)?

**Comment by diml** [comment]
I was thinking of adding a `(defaults ...)` stanza to set the defaults for the given sub-tree. And we might want to specify different flags for release/development modes as well.

For `vendor/...` we don't need anything special, there is already a notion of scopes in jbuilder: a scope is a sub-tree starting where at least one `<package>.opam` exists, and scopes are exclusive. This is quickly mention in the manual, to precise the scope of private libraries. I need to move it to the terminology section.

**Comment by dra27** [comment]
Sounds good! At the moment, I'm making cheeky use of `#use` in OCaml syntax to pull in common things

**Comment by diml** [comment]
This is now supported in master. The syntax is `(env ...)`.
