### ISSUE TITLE
Highlight multi-line errors

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#1131]
Since #1121 we have a way to highlight error locations, but this is limited to errors that are on a single line. Something like this would work:

```
File "dune", line 3, characters 4-234:
3:  (something
4:      something
5:  )
```

This should be pretty easy to implement, and I'm happy to guide someone in implementing this.

**Comment by anuragsoni** [comment]
@emillon if this is still up for grabs, i'd like to work on this.

**Comment by emillon** [comment]
Absolutely! I'll address this on the PR itself.

**Comment by CraigFe** [comment]
This looks like it could be closed :slightly_smiling_face:

**Comment by diml** [comment]
Indeed!
