### ISSUE TITLE
Unknown constructor include_subdirs

### ISSUE THREAD

**Issue by ddickstein** [ocaml/dune#1145]
The `include_subdirs` stanza is not working for me and I'm not sure why. While I don't have any subdirectories of `src` at the moment I plan to in the future, which is why I want to add this line here now.

Dune version: 1.0.1

Directory structure:
```
ocaml/
  hello-world/
    src/
      hello_world.ml
      dune
    dune-project
  dune-workspace
```
My dune-workspace file is empty.
My dune-project file just has the line "(lang dune 1.0)"
My dune file looks like this:
```
(include_subdirs unqualified)
(executable (name hello_world))
```
When I run `dune build hello-world/src/hello_world.exe` I get the following error:
> File "hello-world/src/dune", line 1, characters 1-16:
> Error: Unknown constructor include_subdirs

**Comment by rgrinberg** [comment]
Your dune version is too old. Include subdirs was introduced in 1.1.0.
