### ISSUE TITLE
dune utop error message could be clearer

### ISSUE THREAD

**Issue by dra27** [ocaml/dune#1149]
As it happens, I'd never used `dune utop` before - the man page is not entirely clear that you need an argument: `SYNOPSIS` only lists optional arguments and `OPTIONS` doesn't really hint at it. I inadvertently skipped the one line in `DESCRIPTION` which mentions it!

The error message when running `dune utop` in a directory which doesn't define a library also needs improving:

```
[dra@ocamldefang syslog-message]$ dune utop
Don't know how to build .utop/utop.exe
```

It could be:

```
No library found in the current directory, did you mean to specify a directory
e.g. dune utop lib
```
or it could even list the directories under the current one which do define libraries?

**Comment by emillon** [comment]
That's a good point, thanks for the report!

I'll check if it's possible to build that list of suggestions, or at least improve the error message.
