### ISSUE TITLE
Track dependencies at the env level

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#1152]
As discussed in https://github.com/ocaml/dune/pull/1147#issuecomment-413882650, we should track when `(env)` changes and trigger a rebuild in that case.

**Comment by rgrinberg** [comment]
Another thing that will be useful here is to add a way to get the environment at the action level. Naturally, this should respect the `setenv` action.

**Comment by rgrinberg** [comment]
@emillon this can be closed now?

**Comment by emillon** [comment]
Yes, that's mostly taken care of by #1186. I think `setenv` works correctly since the env is passed. The rest will be taken care of by #1147.
