### ISSUE TITLE
Compilation to Javascript does not terminate when using the "variants workaround"

### ISSUE THREAD

**Issue by jonathan-laurent** [ocaml/dune#1174]
Hi everyone,
I need to use library variants in one of my projects and found the following workaround to be very useful: https://github.com/diml/variants-workaround. I tried to compile the (very short) example provided in this repo into Javascript but it makes dune hang forever:

```
git clone git@github.com:diml/variants-workaround.git
cd variants-workaround
jbuilder build --profile dev --display=short test/test.bc.js # Hangs forever
```

Note that the problem disappears when compiling with the `release` profile:

```
jbuilder build --profile release --display=short test/test.bc.js # This works
```

Therefore, the issue probably has to do with dune's [separate compilation mode](https://jbuilder.readthedocs.io/en/latest/jsoo.html). Does anyone have an idea what's happening here?

**Note:** I am using jbuilder 1.1.1, js_of_ocaml 3.2.1 and ocaml 4.06.1.

**Comment by jonathan-laurent** [comment]
Note that I would be more than happy to help fixing this issue if someone can suggest me a place to start.

**Comment by rgrinberg** [comment]
The variants workaround is going to be obsolete quite soon. Instead of extending it, perhaps you'd be interested in test driving our actual virtual libraries feature? It's still experimental, but it will be available real soon now™

**Comment by jonathan-laurent** [comment]
@rgrinberg 
This is a good point. I would be happy to test drive your virtual libraries feature (and in particular check how it interacts with jsoo).

**Comment by rgrinberg** [comment]
Sure, so there's basically full support for virtual libraries and implementations in master, you just need to enable it in your dune project file. You can do it by adding a line like to your dune-project file:

```
(using in_development_do_not_use_variants 0.1)
```

You can then use the standard `(virtual_modules ..)` and the `(implements ..)` fields. The first field specifies which modules are left unimplemented (they're mli only) and the second field specified which virtual library is being implemented.

**Comment by jonathan-laurent** [comment]
Thanks! I will be looking at this.

**Comment by jonathan-laurent** [comment]
@rgrinberg I just realized my mistake: I was using `jbuild` files instead of `dune` files. After renaming the config files and removing parentheses in them as suggested by dune, everything works perfectly. 

This is my bad, I believed "jbuild" and "dune" files could be used interchangeably.

Tell me if you are still interested in getting the project with jbuild files generating the runtime error above.

**Comment by rgrinberg** [comment]
Oh no, there's no need. The above error is caused by the temporary mechanism that we have to explicitly enable virtual library support. When this support is ready, we will get rid of this extra stanza in the dune-project file. We appreciate any testing of this feature, so please don't hesitate to make bug reports and ask questions.
