### ISSUE TITLE
untar files -- strange behaviour and possible feature request

### ISSUE THREAD

**Issue by sapristi** [ocaml/dune#1176]
Hello,
I have been trying to use dune to unpack (say from a tar archive) a set of files (through the `system`  user command). 

What happened is that during the first `dune build` after a `dune clean`, the files were unpacked as expected, but if I ran `run build` once again without cleaning up, the unpacked files would disappear.

I guess it could be solved by setting the files as targets, but maintaining the dune file for this would be too much trouble.

Do you know of a way unpacking files with dune could be easy to do ?
Thanks,

**Comment by rgrinberg** [comment]
I think explicitly listing the targets is the only option. Dune can't really discover the targets for you. The best you can do is generate a dune file after reading the tar files.

**Comment by sapristi** [comment]
Ok I'll look into doing that, thank you !
