### ISSUE TITLE
dune hangs during build if it encounters an error

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#1191]
I can't trace this down any further, but it's reproducible with these instructions via dune on git rev 265adc8eae6978fa96bf69bbbf571b2c9b8d83c8 (but also happens on latest released version)

With only OCaml and dune installed (and in particular, with no ocamlfind and hence no findlib.top):

```
git clone git://github.com/avsm/platform
cd  platform
git checkout e98df99ef5e62f35c4245a64fc29b94ebc932bee
make
```

This builds for a while, showing the error message that findlib.top isnt present, but then the build hangs forever.  It completes fine if ocamlfind is installed and the missing library error message disappears:

```
Done: 3893/5188 (jobs: 4)
```

No apparent processes running, so it seems to have deadlocked internally.

**Comment by rgrinberg** [comment]
is this reproducible with 1.9? Seems unlikely

**Comment by avsm** [comment]
I’ll reopen if so, not seen it in ages
