### ISSUE TITLE
How to pass `-option <value>` to ppx rewriters?

### ISSUE THREAD

**Issue by jberdine** [ocaml/dune#1194]
Is there a way to pass options with arguments to ppx rewriters?  I have a command such as:
```
.ppx/bisect_ppx+ppxlib.runner@llair/ppx.exe -exclude-file ../../.bisect-exclude --cookie 'library-name="trace"' -o src/trace/trace.pp.ml --impl src/trace/trace.ml -corrected-suffix .ppx-corrected -diff-cmd - -dump-ast
```
that works (from the build context directory), but I don't know how to write the dune file so that `-exclude-file ../../.bisect-exclude` gets passed to the ppxlib.runner. If I have `(preprocess (pps ... bisect_ppx  -exclude-file ../../.bisect-exclude ppxlib.runner))`, then dune does not know that `-exclude-file` takes an argument and reports that `Error: Library "../../.bisect-exclude" not found.`

**Comment by rgrinberg** [comment]
Dune uses a `--` separator in the `pps` constructor to separate the list of preprocessors from the list of arguments that don't look like options. This is documented here: https://dune.readthedocs.io/en/latest/dune-files.html#preprocessing-with-ppx-rewriters

Side note: As cute as this is, this is unintuitive to users and isn't consistent with the rest of dune. I wish we just went with a separate field for the preprocessor options.

**Comment by jberdine** [comment]
That works, Thanks!

A note just FYI re documentation, at least to me, putting `ppxlib.runner` in the `pps` phrase has fallen into the category of "magic bit of boilerplate that happens to work". I thought it had to come last in `pps`, and using this `--` separator seems to require putting the options after the rewriters, and at least the ones with arguments need to come all together at the end, not next to the rewriter to which they apply. To me, it would be much more intuitive to write e.g.
```
(preprocess
 (pps
   (ppx_compare)
   (ppx_trace --debug)
   (bisect_ppx -exclude-file ../../.bisect-exclude)
   ppxlib.runner))
```
to use sexps to indicate how to parse the libraries and args, perhaps omitting parens around rewriters without args.

**Comment by diml** [comment]
@jberdine in dune files, you should no longer have to write `ppxlib.runner`. It is selected automatically as soon as you use at least one ppx rewriter using ppxlib. The ppxlib driver supersedes the ocaml-migrate-parsetree driver and there should normally be no reason to prefer the ocaml-migrate-parsetree one if you already depend on ppxlib, that's why it's no longer a choice.

Regarding the grouping of options, the only problem is that it would give the wrong impression that the command line options are passed to individual ppx rewriters and that in particular you can use the same option names for different ppx rewriters, which is not the case.

**Comment by jberdine** [comment]
Thanks, good to know the runner is not needed.

Re option grouping, yes I now realize that the args are not passed to individual rewriters. But I still think it would be a better UI, and can image a future where the option registration in ppxlib and dune work together to automagically rename things to avoid clashes and make the pleasant fiction a reality. :-)

**Comment by rgrinberg** [comment]
> Regarding the grouping of options, the only problem is that it would give the wrong impression that the command line options are passed to individual ppx rewriters and that in particular you can use the same option names for different ppx rewriters, which is not the case.

This feels like a limitation of driver's relying on command line flags to pass options. It seems feasible that this limitation will not be permanent.

**Comment by jberdine** [comment]
What is a better / the best way to pass options to rewriters? I guess env variables could be used, but is hiding them from the build system really a good idea?

**Comment by rgrinberg** [comment]
The build system could generate a configuration file that the driver could read for example Sexps seem quite capable for this.

**Comment by diml** [comment]
There are several solutions, but the more we complicate things and the harder it becomes to run the pre-processing by hand and debug things. Currently it's quite simple: you can run one ppx.exe command with straightforward  command line arguments.

**Comment by diml** [comment]
I wrote a concrete proposal in #2020
