### ISSUE TITLE
passing options to test stanzas

### ISSUE THREAD

**Issue by samoht** [ocaml/dune#1195]
The new test stanza is great but it doesn't seem to be possible to pass options to the executable. Would be great to be able to do something like:

```
(test
 (modules   test)
 (libraries test_lib))
 (args      (-q --color=always)))
```

or something similar.

**Comment by emillon** [comment]
Yes, at the moment it's hardcoded:

https://github.com/ocaml/dune/blob/265adc8eae6978fa96bf69bbbf571b2c9b8d83c8/src/gen_rules.ml#L193

Providing `(args)` seems to be a good interface for this :+1:

**Comment by diml** [comment]
What about `(action (run %{prog} -q --color=always))`? That should handle even more cases.

**Comment by rgrinberg** [comment]
Action seems preferable as well. I'm wondering why `%{prog}` over `%{test}` for example.

**Comment by diml** [comment]
No reason, `%{test}` seems good
