### ISSUE TITLE
more flexible dependencies in libraries 

### ISSUE THREAD

**Issue by c-cube** [ocaml/dune#1208]
I hit a difficulty when trying to write OCaml bindings to a rust library, for relatively convoluted reasons.

The current state of things (very hackish): https://github.com/c-cube/batsat/tree/ad7643449dc594c942d78db85cb936b5ea66a570/src/batsat-ocaml

The situation right now is as follows. I'd like to write stubs for the rust library `batsat_c` (which is defined just for this purpose, it exposes a set of C-compatible symbols). However, using stable rust, I can't use [ocaml-rs](https://github.com/zshipko/ocaml-rs) which means I have no realistic way to write the stubs in rust (the C macros are not available in rust).

Therefore I'm trying to have a C file in my bindings which bridges OCaml values with the rust C API. That's fine, but I have no clear way of telling dune to build the rust library (by calling cargo) before it builds the stubs, since a library can only depend on other OCaml libraries. If I could state "library foo depends on calling this rule" it would help a lot.

The current hack: have the C stubs file be "generated" (a no-op, actually) by a rule which by side effects builds the rust library.

**Comment by rgrinberg** [comment]
Thanks for making the ticket Simon.

> If I could state "library foo depends on calling this rule" it would help a lot.

Have you tried the `link_deps` field? https://dune.readthedocs.io/en/latest/dune-files.html?highlight=link_deps

**Comment by c-cube** [comment]
It seems like it would help, but it's only available for executables apparently.

**Comment by emillon** [comment]
I can probably extend this to libraries. As a temporary solution, does (ab)using `preprocessor_deps` to declare a dependency to the other target work?

**Comment by c-cube** [comment]
I have a temporary workaround now (the rust lib for writing stubs in rust now works for me).

**Comment by avsm** [comment]
in the yaml bindings, i build a separate c library (https://github.com/avsm/ocaml-yaml/tree/master/vendor) and then link that into the ocaml code (https://github.com/avsm/ocaml-yaml/tree/master/ffi/lib) -- makes for slightly more verbose rules but much more flexible C compilation.

**Comment by Alizter** [comment]
The situation today is that we can set up custom rules with directory targets which we can call cargo in. Therefore closing the issue. @rgrinberg feel free to reopen if you disagree.
