### ISSUE TITLE
Add linking mode for embedded C bytecode

### ISSUE THREAD

**Issue by drjdn** [ocaml/dune#1216]
I think having a linking mode for the  `compilation mode byte`  and `binary kind object` to a C-file would be a useful addition to `dune` using `extension` name `.bc.c`.  To illustrate why I think this would be of use I've created the following [repo](https://github.com/drjdn/ocaml_c_pkg).

**Comment by diml** [comment]
That seems fine. This part of the code is relatively self-contained, so it should be easy to add this mode. Are you happy to give it a go? I can give you some pointers if yes

**Comment by drjdn** [comment]
Sure, I can give it a try.  Any pointers you can provide would be appreciated.
