### ISSUE TITLE
[PROPOSAL] Change the Default Target

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1220]
# Problem

Continuous user reports lead me to believe that the current invocation of `$
dune build` is needlessly confusing for user. It seems like no amount of
documentation is going to address this, so I think we should simply change the
default behavior to something more intuitive.

# Solution

A more intuitive default alias would consist of the following targets

* All `@install` targets
* All library artifacts for private libraries except for META files
* All defined executables
* All targets of user defined rules (except aliases)

The default alias would remain to be `@install` when used with the `-p` flag.
This is technically a breaking change, but it should only affect makefiles,
build scripts, and other non critical infrastructure. Also, the default target
is a superset of the old target. So the potential for breakage is quite small. I
definitely think that the UI is worth it.

The proposed name for this all inclusive alias shall be `@all`.

**Comment by andreypopp** [comment]
Some feedback from my usage of dune.

I want to be able:

- to build everything (all libs/executables) in a project
- to build a specified lib, executable
- to build & run all tests in a project
- to build & run specific tests in a specified lib/executable

I think the most intuitive way for me to build libs and executable is to refer to a directory with a `dune` file (and given how much emphasis dune puts on file system based configuration I think this is fair assumption).

This is how it currently works:
```
% esy b dune build ./esy
Don't know how to build esy
```

Instead I'd expect `dune` to build all artifacts (libs and executables) defined `./esy/dune` file.

Again, as I said above, referring by path is the most intuitive step for me as I placed `esy/dune` file and I have a clear mapping in my head from `dune` files to artifacts.

**Comment by diml** [comment]
Thanks for the feedback. For tests you can already do that via `dune runtest`. For instance:

```
$ dune runtest # build and run all the tests
$ dune runtest src # build and run all the tests in the test/ directory (recursively)
$ dune runtest test # build and run all the tests in the test/ directory (recursively)
```

We could extend this to `dune build`, so that when it is passed a directory it builds the default target in this directory.

**Comment by rgrinberg** [comment]
> We could extend this to dune build, so that when it is passed a directory it builds the default target in this directory.

Yeah, me and Andrey discussed this as well. But I think it's a bit ambiguous when a user adds a rule that generates a target with the same name as a directory. One suggestion that came up is to add a trailing `/` to distinguish file targets and directory targets, but this isn't really intuitive. On the other hand, it might only be necessary when there is such a name conflict, so it's not so bad.

**Comment by diml** [comment]
What behavior do you expect in this case? It is not possible to create a file that has the same name as a directory, so the best we can do in such a case is report an error.

**Comment by rgrinberg** [comment]
I thought about a case like:

```
foo/
dune
```

Where

```
$ cat dune
(rule (targets foo) ..)
```

And there's no dependency on the `foo` directory. Anyway, this might be an error already? So we can safely ignore it.

**Comment by diml** [comment]
Currently, depending on what you build it will either succeed or result in a weird error. We could improve the situation by always making it an error, but definitely not try to support it given that there is a 99% chance that this is a user mistake.

**Comment by yminsky** [comment]
I'm not sure that I have much constructive to say except to support this PR. I've found this to be a confusing hole in Dune's UI from the beginning. `dune runtest` already behaves quite reasonably in this regard, and having `dune build` do the same would be great. I also like Jeremie's idea that `dune build src` would build @all in src. That's the current behavior of Jenga, and as Jeremie knows, we've found it to be quite convenient.

**Comment by rgrinberg** [comment]
Then I think this proposal is settled and we can fold the idea of interpreting directory targets as `@all` aliases. I will try and get this in for 1.3

**Comment by rgrinberg** [comment]
I'd like to work on the "directory target to default alias conversion" feature separately. @diml what's the correct way to check if a target is a directory? Checking for existing directories isn't enough, as some can be created as a result of rules.

**Comment by diml** [comment]
We can simply provide this feature on the command line and only for directories that exist in the source tree. That seems acceptable to me.

**Comment by rgrinberg** [comment]
Sure, but this seems like a bit of a cop out. Can't we just set use `targets_of` and then check that it's non empty perhaps?

**Comment by diml** [comment]
That's not going to be enough for directories such as `_doc` or `.ppx` where the targets are generated on-demand. Restricting this feature to source directories seems like a good enough starting point.

**Comment by rgrinberg** [comment]
Done
