### ISSUE TITLE
[PROPOSAL] Development Alias

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1221]
# Problem

Development often requires type checking code and generating files for the IDE. This should be as fast possible and shouldn't be bogged down by irrelevant slow downs caused by creating archives, linking executables, etc.

# Solution

Create a minimal alias that would include the following:

* All `.cmt`, `.cmti`, and `.cmi` targets.
* All .merlin files.
* Whatever else that might be required for development

Here are some proposed named for this alias:

* `@dev`. pros: can easily include other dev artifacts
* `@typing`. pros: explains what we're actually doing (trying to type check our code base)
* `@check`. pros: familiar to users of `cargo check`. This proposed alias is inspired by cargo.

**Comment by diml** [comment]
I like `@check`

**Comment by andreypopp** [comment]
Could this be `dune check` or `dune dev` command instead?

**Comment by rgrinberg** [comment]
Sure, that's basically how `dune runtest` works anyway.

**Comment by rgrinberg** [comment]
This is addressed in master.
