### ISSUE TITLE
allow same module in more than one library?

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#1230]
How hard would it be to support this? The use-case is when you have a large collection of "plugins" and you want to bundle different subsets of these in separate libraries, but there can be overlap between them.

**Comment by diml** [comment]
What about using rules to copy the .ml files?

**Comment by nojb** [comment]
Indeed, I had not thought of that 😄; I will give it a try and report back. Thanks!

**Comment by nojb** [comment]
Closing, as it looks like it should work.
