### ISSUE TITLE
test stanza does not respect their `package` field

### ISSUE THREAD

**Issue by samoht** [ocaml/dune#1231]
In https://github.com/mirage/ocaml-cohttp/pull/631

I got this `dune` file, defining a test belonging to the `cohttp-async` package:

```
(test
  (name      test_async_integration)
  (package   cohttp-async)
  (libraries cohttp_async_test async_unix base core async_kernel oUnit
             cohttp-async))
```

but I got:

```
$ dune runtest -p cohttp-lwt-jsoo
...
File "cohttp-async/test/dune", line 5, characters 13-25:
Error: Library "cohttp-async" not found.
Hint: try: dune external-lib-deps --missing -p cohttp-lwt-jsoo @runtest
...
```

**Comment by samoht** [comment]
And If I rewrite the `dune` file to:

```
(executable
  (name      test_async_integration)
  (libraries cohttp_async_test async_unix base core async_kernel oUnit
             cohttp-async))

(alias
  (name   runtest)
  (package cohttp-async)
  (action (run ./test_async_integration.exe)))
```

then the error disappear.

**Comment by emillon** [comment]
It's a bit weird, the `package` and `deps` fields seem to be correctly plumbed. (deps are reset for expect tests, which seems a bit strange but this is not the case here)

**Comment by samoht** [comment]
Can you replicate with https://github.com/mirage/ocaml-cohttp/pull/631/commits/a512b747f206df479ba6da95a818f80a494f0429 ?

**Comment by emillon** [comment]
Got it! That's the part of `Gen_rules` that checks stanzas for packages. I'll prepare a fix!
