### ISSUE TITLE
bug: dune infers a parent directory as root even though the current one has a `dune-project` file.

### ISSUE THREAD

**Issue by jaredly** [ocaml/dune#1242]
My directory setup is
```
my-project/
  my-project.opam
  dune-project
  examples/
     some-example/
       dune-project
       some-example.opam
```

running dune in the `some-example` directory should treat that directory as root, instead of climbing up to the `my-project` directory

**Comment by Khady** [comment]
It is not a bug. See the doc here: https://dune.readthedocs.io/en/latest/usage.html?highlight=root#finding-the-root
It says that it takes the outermost ancestor directory.

**Comment by diml** [comment]
Indeed, this the intended behavior. You can force the root via `dune --root <dir>`
