### ISSUE TITLE
Simplified syntax for common case of (copy ...) ?

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#1244]
The common case of `(copy ...)` is copying a file from another directory to the current one with the same name.

What do you think of interpreting `(copy src)` as `(copy src (basename src))` ?

(same for `(copy# ...)`)

**Comment by rgrinberg** [comment]
I think that's how `copy_files` already works so it makes sense.

**Comment by rgrinberg** [comment]
This is easy enough to do so if anyone's curious about implementing this, we can give some guidance.

**Comment by nojb** [comment]
I took a quick look at doing this; the only "tricky" point is inferring the target of such an abbreviated action, which requires making the type of paths less abstract than they are now which altogether seemed to me to result in uglier code.

In any case, #1323 addressed this issue as well for me, so as far as I am concerned, we could close this one.

**Comment by nojb** [comment]
Not really important.
