### ISSUE TITLE
How to make dune compile with musl instead of glibc?

### ISSUE THREAD

**Issue by vog** [ocaml/dune#1249]
What is the recommended way to tell dune to compile against the `musl` libc instead of the `glibc` libc on a system where both are available?

(e.g. a Debian system, where `glibc` is the default, with installed packages `musl-dev` and `musl-tools`)

For example, is it possible to tell `dune` to use the `musl-gcc` wrapper instead of `gcc`?

Related: https://github.com/mmottl/sqlite3-ocaml/issues/31

**Comment by diml** [comment]
I believe the simplest solution for this is to configure the OCaml compiler to use the `musl` libc.

**Comment by emillon** [comment]
It might be tricky to do so at the `dune` level since the ocaml compilers invoke the toolchain by themselves as well.

One solution would be to create an opam switch that uses the musl toolchain. There are existing switches that do so, like `4.06.1+musl+static+flambda`.

**Comment by vog** [comment]
Thanks. I'll try that.

**Comment by vog** [comment]
For the sake of completeness: I tried, but experienced some issues compiling that OCaml switch on Debian. See also: https://github.com/ocaml/opam-repository/issues/12769
