### ISSUE TITLE
Preferred way to organize project in multiple folders?

### ISSUE THREAD

**Issue by rnd4222** [ocaml/dune#1251]
What is the preferred way to organize my project into multiple folders?
Should I make every folder as a separate (public) library, and then aggregate it as one, top-level lib (which is then published to opam, for example)?

**Comment by diml** [comment]
Dune supports both modes. You can use `(include_subdirs unqualified)` to describe a library whose source files are spread across multiple directories, or you can create multiple libraries as you describe.

If it doesn't make sense for your users to use the various parts independently, then the multi-directory library approach is probably the best one.

**Comment by rgrinberg** [comment]
@rnd4222 If you're content with Jeremie's answer, would you consider closing this issue?

**Comment by ejgallego** [comment]
One question related to this one, if one has a project `bar` such that:
```
bar/dune-project
bar/comp1
bar/comp2
```
both `comp` have as `dune`:
```
(library
  (public_name bar.comp1))
```

How could I tell Dune to wrap both `Comp1` and `Comp2` wrap modules under a global `Bar` one?
