### ISSUE TITLE
Substitute Install Paths?

### ISSUE THREAD

**Issue by japendergrass** [ocaml/dune#1253]
Is there a mechanism to substitute install paths (e.g., `$prefix`) into a generated file during build?

I expected to be able to accomplish this using a `rule` with like
```
(rule 
     ((targets (project.conf))
       (deps    (project.conf.in))
       (action (run sed -e /\${prefix}/%{prefix}/g %{deps} > %{target})))
```

But `%{prefix}` (or `bindir`, `libdir`, etc) is not listed as a substituted variable in the documentation.

**Comment by diml** [comment]
Not currently, dune doesn't know the value of these parameters. Related ticket: https://github.com/ocaml/dune/issues/1185

**Comment by diml** [comment]
And this one as well: https://github.com/ocaml/dune/issues/680

**Comment by rgrinberg** [comment]
Well `$ dune install` works without rebuilding the artifacts. To substitute installation directories, we'd need to configure these variables and then run the build. This would be a fairly significant change to dune, do you have some motivation for why you'd like this variables to be substitutable?

**Comment by kit-ty-kate** [comment]
I stubbled upon the same issue about a lack of `%{prefix}` (or similar) variables in https://github.com/mirage/mirage-solo5/pull/61 which currently uses `opam config var lib` when compiling the package to know where a required directory (which is not a library) is.

**Comment by jeremiedimino** [comment]
@kit-ty-kate looking at the mirage-solo PR makes me wonder: shouldn't it be opam's job to extend the `PKG_CONFIG_PATH` variable?

Regarding the original question, during the build we don't know the installation prefix, so we'd need to introduce a configure step to make that possible, which as @rgrinberg pointed out is a significant change. Perhaps we should add that one day though.

On a related note, @bobot is working on a general solution to the problem of data needed at runtime: #3104. That seems worse looking at.

**Comment by ejgallego** [comment]
@bobot can we close this?

**Comment by rgrinberg** [comment]
I think we can. @bobot can re-open if he disagrees.
