### ISSUE TITLE
dynlink missing in meta.ml

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#1264]
`dune` fails to find `dynlink` in the absence of `ocamlfind`.

**Comment by diml** [comment]
@dra27 that's why the compiler should install its `META` files...

**Comment by dra27** [comment]
@diml - that would be fine if the compiler also took control of the format! Otherwise, we must either *require* ocamlfind or workaround its absence - it feels a bit "having and eating" to say we don't require ocamlfind but then require the environment to act as though it were installed 🙂

**Comment by diml** [comment]
All we need is to have this information in a machine readable form so that dune can read it rather than maintain it in parallel.
