### ISSUE TITLE
Dune fails to fully ignore an ignored subdir

### ISSUE THREAD

**Issue by vog** [ocaml/dune#1269]
I have a project where the main `dune` file excludes a certain subdir `mysubdir`:

```lisp
(ignored_subdirs (mysubdir ...))
```

However, when running Dune:

```sh
dune build ...
```

it still complains about a symlink in that subdir:

```
Path mysubdir/subpath1 has already been scanned. Cannot scan it again through symlink mysubdir/subpath2
```

Is this a bug? How can I make Dune *really* ignore the ignored subdirs?

**Comment by diml** [comment]
Basically, ignoring a sub-directory means that dune will not try to interpret `dune` and other configuration files in it, however it may still access files in it if explicitly requested on the command line or by a user rule. It basically means to treat the sub-directory as a binary blob.

Maybe you have something like `(deps ... (file_tree x))` that is causing the source tree to be deeply scanned?

In any case, we should probably rename this stanza and add a way to make a sub-directory invisible to dune.

**Comment by diml** [comment]
What about this interface:

```scheme
(subdirs_state (<regexp> {normal,data,hidden}))
```

For instance:

```scheme
(subdirs_state (test-inputs data) (blah hidden))
```

`data` would have the same meaning as `ignored_subdirs`, and `hidden` would effectively make the sub-directory invisible to dune.

**Comment by vog** [comment]
I find your argument quite convincing and would like to go into a different direction.

Yes, ignored subdirs might still provide important files for the Dune build, which happens to be true for my specific use case as well.

However, that alone doesn't imply that Dune should make assumptions about the structure of ignored_subdirs. Quite the contrary: Since this is outside Dune's realm, Dune should make as few assumptions as possible.

For example, if a file within an ignored subdir is referenced by a custom build rule, then Dune shouldn't care about symlinks et etc.

However, I do see that for the specific case of `(file_tree ...)`, enforcing a non-cyclic structure is simpler and more robust to implement than adding symlink support.

So I'd like to ask for a slightly different problem resolution:

Is it possible that the error quoted above appears only for sub directories that a actually included via `(file_tree ...)`?

**Comment by diml** [comment]
That seems reasonable. In fact it shouldn't be too hard to support; if you look at the type `Dir.contents` in `src/file_tree.ml`, all you need to do is make the `sub_dirs` field be lazy. Would you be willing to give a try and see if it fixes the problem in your case?

**Comment by vog** [comment]
I wanted to have a look at it, but surprisingly, I'm no long able to reproduce this issue.

This is very strange, as I'm pretty sure I didn't upgrade OCaml, nor my OPAM setup, nor Dune since then.

So I'll have a look at it to see when this issue appears again.

**Comment by rgrinberg** [comment]
We now have a proper ignore stanza. The old ignore stanza is equivalent to `data_only_dirs`
