### ISSUE TITLE
Dune tests stanza and runtest no longer works with multiple tests?

### ISSUE THREAD

**Issue by TheAspiringHacker** [ocaml/dune#1276]
In an OCaml project, I had the following Dune file:

    (tests
      (names test_env test_integration test_syntax test_type test_typecheck)
      (libraries base emelle)
      (preprocess (pps ppx_jane)))

When I ran `dune runtest`, all the tests would get executed.

After upgrading to Dune 1.2.0, `dune runtest` raises the error:

    Multiple rules generated for _build/.aliases/main/test/runtest-decee903a70d612bb35f9747eb00e4b2:
    - test/dune:2
    - test/dune:2

Removing all of the tests except one removes the error.

I did not check the version of Dune with the expected behavior because I didn't think that I would have any problems upon upgrading.

Skimming the repository's releases page, I did not see any notes that would explain the change in behavior as a feature. Purely out of speculation, perhaps https://github.com/ocaml/dune/pull/1248 changed the behavior?

**Comment by rgrinberg** [comment]
Do you have a small reproduction case?
