### ISSUE TITLE
[IDEA] $ dune eval

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1279]
## Problem

Right now tools like [dune-release](https://github.com/samoht/dune-release/pull/46#issuecomment-421793387) rely on parsing to fetch information like the dune project's name. We should make this information more readily available.

## Solution

Rather than inventing a DSL for querying dune projects, or a complex set of command line options to make this information available, I propose a simpler mechanism: `$ dune eval`. This would be a single new command that would evaluate dune s-expressions representing dune actions and potentially print their results. For example, this is how we could fetch the project name:

```
$ dune eval '(echo %{project-name})'
```

Naturally, this could easily be extended to extract whatever information we'd want without bloating the CLI. The nice thing about this mechanism is that it could also be used for other purposes. Here are some possibilities:

* It could be used as a lightweight shell scripting language
* As a dune "repl"
* A mechanism for querying the currently running dune instance

## Issues

The one issue with this mechanism is that it would still be awkward to dump information organized in a tree like mechanism. To address that, we could have dune actions that would simply generate w/e structured information we needed as s-exps. E.g, an action like `(echo (lib-info <lib-name>)))`

**Comment by Chris00** [comment]
For tools like dune-release, wouldn't it be better to simply have a library to query?

**Comment by diml** [comment]
An OCaml library would be nice indeed.

**Comment by Chris00** [comment]
>  Just to access the project files?

At first, I guess it is enough.  It can always be enriched later.
