### ISSUE TITLE
[RFC] New computation model for dune

### ISSUE THREAD

**Issue by diml** [ocaml/dune#1280]
This proposal descibe a new computation model for Dune. The aim is to improve performance, sharing, memory usage as well as to increase the expressive power of Dune. For instance with this new model it will be trivial to support including generated files in `dune` files.

From the point of view of Dune developers and in the future plugin authors, this new model is simple, general and makes it easy to understand where the build system adds overhead to user specified computations in order to minimise recomputation. It will also provide good support for profiling and debugging computations. Additionally, it will naturally benefit from multi-core.

## Problem this proposal is solving

In a given build, there are two kinds of computations: the computations done by external commands and the computations done by the build system itself. The former are already well understood and correctly tracked by the build system, however the latter are currently not properly tracked by Dune. As a result, they are not shared between runs of Dune or between different workspaces. This is fine for small projects as these computations are generally fast, however it doesn't scale to large workspaces.

Build systems such as Jenga allow to share the results of such internal computation in a single process in polling mode, but not across processes.

## Overview of the new model

The new model is simply a system that memoizes pure functions. The ouputs of functions may or may not be serializable. Outputs that are serializable may be be shared between runs and workspaces and will provide cut-off points during recomputation. Inputs must always be serializable.

The API is as follow:

```ocaml
module Input : sig
  type 'a t
  ...
end

module Output : sig
  type 'a t
  ...
end

val memoize
  :  name:string
  -> 'a Input.t
  -> 'a Output.t
  -> ('a -> 'b Comp.t)
  -> ('a -> 'b Comp.t) Staged.t
```

Where `Comp.t` is essentially the `Fiber.t` monad but that addionnally tracks the effect of the computation, such as reading/writing files, evaluating globs or evaluating other memoized functions.

Because the function is expected to be pure, it will not be necessary to recompute it on a given input when none of the observations it made during its previous execution changed. Additionally, when the memory usage becomes a problem, Dune will be able to forget intermediate results, at the expanse of needing to recompute them when they become needed again.

## Encoding the build system

In this model, the user simply needs to provide a function to build a file:

```ocaml
val build_file : Path.t -> unit Comp.t
```

In particular, there is nothing special about running external commands. To run an external command, we simply use a primitive:

```ocaml
val run : Path.t -> string list -> Effects.t -> unit Comp.t
```

However, it is still necessary to manually specify the effects of the command given that the build system cannot infer them.

## Migration plan

1. implement the memoizing and `Comp` API, except for writes effects
2. replace `Vfile_kind` by memoized functions
3. replace all global hash tables by memoized functions
4. replace the rule generator callback by a memoized function
5. dismantle `Super_context.t`
6. replace the static file tree by `Comp.t` primitves
7. share values between builds in polling mode
8. make values persistent by storing them on disk or in a database
9. implement writes in `Comp`
10. more refactoring to get the final `build_file` encoding

At step 7, polling builds will become really fast even on big workspaces. At step 8, the startup time of dune will be much faster. When combined with a shared artifact cache, startup times even on fresh workspaces will be really fast. Steps 9 and 10 are simply to make the programming model even nicer, in preparation for plugins.

**Comment by nojb** [comment]
👍

FTR I am porting a large build system to `dune` (on Windows mostly) and am experiencing long startup times.

**Comment by avsm** [comment]
I think we could also adapt the opam2 sandboxing scripts to enforce Effect.t execution in a fine-grained way for writes.

**Comment by rgrinberg** [comment]
@nojb would you mind quantifying the long startup times for us. For example, how many modules/libraries/executables does your workspace contain and how long does it take to do a 0 rebuild?

**Comment by nojb** [comment]
Yes, I will try to get some numbers; but probably in a couple of days, my plate is full at the moment.

**Comment by rgrinberg** [comment]
How does this relate to: https://github.com/ocaml/dune/pull/414 ? Do we want to switch to a direct API first?

**Comment by diml** [comment]
This basically supersedes #414. Though some of the ideas such at the `Observation` module can  be kept.

**Comment by lpw25** [comment]
Two quick suggestions. Firstly, I think it might be better to give the memoizations their own type. So:

```ocaml
module Memo : sig
  type ('a, 'b) t

  val create
    :  name:string
    -> 'a Input.t
    -> 'a Output.t
    -> ('a -> 'b Comp.t)
    -> ('a, 'b) t

  val apply : ('a, 'b) t -> 'a -> 'b Comp.t

end
```

I think this makes things a bit clearer, and it also allows you to add more operations on memoized things later if needed.

Secondly, I suspect that you should really be putting the creation of a memoized thing inside the `Comp` monad. So:

```ocaml
  val create
    :  name:string
    -> 'a Input.t
    -> 'a Output.t
    -> ('a -> 'b Comp.t)
    -> ('a, 'b) t Comp.t
```

because you need to take account of the dependencies used when creating the `('a -> 'b Comp.t)` as well as the dependencies it uses when executed. You could avoid that by prohibiting `create` from being called within a `Comp.t` (e.g. by detecting such cases and raising an exception), however I think that you will often find that you don't know which memoized functions you want to create until you've made some observations of the file system. If you force the memoized to be top-level then people will have to do closure-conversion by hand in those cases, but if you make the creation of the memoized part of the monad/arrow then they can just close over the data and all the dependencies will be correctly tracked.

**Comment by diml** [comment]
Giving the memoizations their own type seems good. For the other part, I'm basically planning to only allow memoizing functions at the toplevel. That forces the user to completely specify all the inputs, but on the other hand I find it easier to reason about and in general it should result in less things being considered as input of the function.

**Comment by rgrinberg** [comment]
> For instance with this new model it will be trivial to support including generated files in dune files.

Does that mean that we also plan to lift the restrictions that the list of targets needs to be static?

**Comment by diml** [comment]
The list of targets of a rule will still be static, however we will be able to compute the list of rules dynamically.

Eventually, we could completely get rid of rules altogether, that's the idea of "write effects". This makes the API even nicer, however this might impact a bit the UI. For instance, it might be harder to interpret `dune build <file>` as it won't be clear beforehand what needs to be evaluated to produce the file.

**Comment by lpw25** [comment]
If you have:

```ocaml
val define_section
  :  Pattern.t
  -> ('a, 'b) t Lazy.t
  -> ('a, 'b) t
```
from the discussion in #414 then you can still know what to build for `dune build <file>` since you just run the sections of the script that say that they might build `<file>`.

**Comment by diml** [comment]
Indeed

**Comment by diml** [comment]
For `Comp.t`, I'm wondering if it is worth having a new monad or if we can't simply reuse `Fiber.t` given that they are very similar. I suppose what I want to write is something like this:

```ocaml
module Fiber : sig
  type ('a, _ 'effect) t

  val perform : 'a 'effect -> ('a, _ 'effect) t

  val handle_effects
    :  perform:('a 'effect -> ('a, _ no_effects) t)
    -> ('a, _ 'effect) t
    -> ('a, _ no_effects) t
end
```

That would allow to use generic fiber functions with any kind of computations, though it's not valid OCaml.

I'm thinking of something like this:

```ocaml
module type Fiber = sig
  type 'a effect
  type 'a t

  val perform : 'a effect -> 'a t
end

module Fiber : Fiber with type _ effect = unit

module type Effect : sig
  type 'a t
end

module Make(Effect : Effect) : sig
  include Fiber with type 'a effect = 'a Effect.t

  val handle_effects : perform:('a Effect.t -> 'a Fiber.t) -> 'a t -> 'a Fiber.t
end
```

It's less generic but it should be enough for dune.

**Comment by lpw25** [comment]
You're getting very close to monad transformers or algebraic effects there. I guess the full algebraic effects version might look something like:
```ocaml
type 'a handler =
  { return : 'a -> 'a Fiber.t;
    perform : 'b. 'b Effect.t -> ('b -> 'a Fiber.t) -> 'a Fiber.t; }

val handle_effects : 'a handler -> 'a t -> 'a Fiber.t
```
so you can supply a return case and you get a full continuation for the perform case.

**Comment by lpw25** [comment]
(I'm not suggesting that you should use the full algebraic effects version -- just illustrating how your suggestion relates to the more general concept.)

**Comment by rgrinberg** [comment]
I'm closing this as the main feature has been implemented. Perhaps we should have a separate ticket for Leo's section feature however.
