### ISSUE TITLE
Colors do not (but could) work on Cygwin

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#1283]
Using `dune` on Windows automatically disables colors. However, colors can be safely used under Cygwin. We fixed this for the OCaml compiler in https://github.com/ocaml/ocaml/pull/1406 and is included in 4.07.

There is a (unexposed) primitive [`caml_sys_isatty: out_channel -> bool`](https://github.com/ocaml/ocaml/blob/28c337fecbebfc064c06ae0ba35a1107b0b58493/utils/terminfo.ml#L18) used to decide whether to enable colors or not. It could be used by `dune` as well (from 4.07 onwards of course).

**Comment by diml** [comment]
That seems reasonable.

**Comment by diml** [comment]
It seems that simply removing the `not Sys.win32` in `colors.ml` should be enough since we already call `Unix.isatty` which is implemented using `caml_sys_isatty`. However, I assume that it will not do the right thing in the standard Windows console?

**Comment by nojb** [comment]
Indeed, I had forgotten about that. Re the Windows console it should still be OK, because `TERM` is not typically set in that case.

**Comment by diml** [comment]
Ok, let's try it then: https://github.com/ocaml/dune/pull/1290

**Comment by diml** [comment]
This should now work
