### ISSUE TITLE
Building custom aliases fail with `js_of_ocaml` dependency issue

### ISSUE THREAD

**Issue by rauanmayemir** [ocaml/dune#1302]
When I run `dune build @myalias`, I get the following failure:

```
Error: Library js_of_ocaml-compiler not found (context: default)
Hint: opam install js_of_ocaml-compiler
```

Here's an example of custom alias: https://github.com/briskml/brisk/blob/d4185a6663bdec20eb4fe293af87ee54046c8a14/dune#L5-L9

Currently, I have to run build with `--profile=release` to suppress the error.

**Comment by rauanmayemir** [comment]
I have a monorepo that hosts a mixed set of libs and executables targeting macOS and Linux (some for both, some for linux, some for macos only).

Using custom alias was supposed to be a workaround for having adjustable `ignored_subdirs`. So e.g running `dune build @linux` would ignore macOS targets.

**Comment by diml** [comment]
I see. What about using [the default alias](https://dune.readthedocs.io/en/latest/usage.html#default-alias)? I.e `(alias BRTesterMac/default)` instead of `(glob_files BRTesterMac/src/*)`?

BTW, would #1184 help?

**Comment by rauanmayemir** [comment]
I tried running `dune build @core/lib/default`, but it doesn't build anything, log suggests dune is only doing its getconf/printconf thing. (there's only library [config](https://github.com/briskml/brisk/blob/d4185a6663bdec20eb4fe293af87ee54046c8a14/core/lib/dune))
`(alias BRTesterMac/default)` doesn't work either. (do I need to explicitly set up default target in `BRTesterMac` to pull stuff from `BRTesterMac/src`?)

Is that a new feature? I'm testing on dune `v1.1.1`.

I thought toggling ignored subdirs would help, but learning about aliases, it doesn't feel right to me to dynamically 'blind' dune to some folders compared to having specific target aliases.

**Comment by diml** [comment]
It was added in 1.0.0. If it is not defined explicit there is an implicit definition. It's odd that it doesn't work. What happens if you use instead `(alias_rec BRTesterMac/install)`?

**Comment by rauanmayemir** [comment]
Same thing. I don't get any actual build.

```
; $root/dune

(alias
 (name mac)
 (deps
   (alias_rec BRTesterMac/install)))
```

```
; $root/BRTesterMac/src/dune

(executable
 (name app)
 (libraries brisk_cocoa)
 (flags (:standard
        (-runtime-variant d -verbose -g)
 ))
 (modes object))

(install
  (package brisk)
  (section bin)
  (files (app.exe.o as app.o)))
```

**Comment by diml** [comment]
I just tried on my machine and it seems to work for me with `(alias BRTesterMac/default)`. The build fails as I'm on Linux, however it does look like it tries to build `BRTesterMac/src/app.exe.o`:

```
$ esy dune build @mac --debug-dependency-path
      ocamlc renderer_cocoa/lib/Cocoa_stubs.o (exit 2)
[...]
Cocoa_stubs.c:1:24: fatal error: Cocoa/Cocoa.h: No such file or directory
compilation terminated.
-> required by renderer_cocoa/lib/Cocoa_stubs.o
-> required by renderer_cocoa/lib/libbrisk_cocoa_stubs.a
-> required by BRTesterMac/src/app.exe.o
-> required by _build/install/default/bin/app.o
-> required by brisk.install
-> required by alias install
-> required by alias mac
-> required by alias mac
```

**Comment by diml** [comment]
Sure:

```
(alias
 (name mac)
 (deps
   (alias BRTesterMac/default)
   (alias install)))
```

**Comment by diml** [comment]
Ah wait, I realized that I should have removed the second dependency.

**Comment by diml** [comment]
Oh, yh I see the problem... The `install` alias depends on the `<package>.install` files at the root of the project, but not on individual elements. This means that it is empty in `BRTesterMac`. Maybe we should change that.

That said, in this particular case I wonder if what we need is not something to declare that some elements are only for a given platform, i.e.:

```
(install
 (package brisk)
 (section bin)
 (enabled_if (= %{system} macos)))
```

For a quick workaround, you can manually define alias `mac` in `BRTesterMac/src/dune` as follow:

```
(alias
  (name mac)
  (deps app.exe.o))
```

**Comment by rauanmayemir** [comment]
>  something to declare that some elements are only for a given platform

In my opinion, injecting this sort of variables makes for kinda leaky abstractions as `system` is not something I could control with config.
On the other hand, we're approaching the `target`s subject. :)

I think that this particular case might benefit from having a way to constrain by alias.

```
(install
 (package brisk)
 (section bin)
; default ↓
; (enabled_if (default))) 
 (enabled_if (mac)))
```

(I admit I found a hammer and looking for nails, but from what I've seen so far, aliases are already being used extensively in dune projects)

**Comment by diml** [comment]
What would `enabled_if (mac)` mean?

**Comment by rauanmayemir** [comment]
Trigger the rule for `dune build @mac` unless `@install` alias is being called explicitly, essentially constrain rules by aliases set.

But I think discussing the use of `<package>.install` would be more productive. I remember your notes about controlling the `<package>.opam` with dune to allow some flexibility, `<package>.install` seems like an extension of that idea.

**Comment by diml** [comment]
From a higher level point of view, would you expect that the following sequence of commands installs `app.o` in `DESTDIR/bin`?

```
$ dune build @mac
$ dune install
```

or is it simply a way to trigger the build of `app.o`?

**Comment by rauanmayemir** [comment]
Indeed, I would not expect `dune install` to work the way it would if I were running the 'full' build.
For doing install, I'd need to properly isolate each sub-project into its own package or do some sort of pre-release eject.

**Comment by diml** [comment]
Ok, in this case, is there any advantage of using an `install` stanza rather than a plain `alias` one? i.e. you could write this in `BTersterMac/src/dune`:

```
(alias
 (name mac)
 (deps app.exe.o))
```

And `dune build @mac` will build it for sure.

**Comment by rauanmayemir** [comment]
You're right. I shouldn't have used `install` for this case, putting an alias there works fine.
How would I go in case of `dune build @linux` if it only contains libraries? This doesn't build anything:
```
(alias
 (name linux)
 (deps
  (alias core/default)
  (alias renderer_term/default)))
```

**Comment by diml** [comment]
I suppose you can depend on the cma or cmxa:

```
(alias
 (name linux)
 (deps
  (alias core/core.cma)
  (alias renderer_term/renderer_term.cma)))
```

**Comment by rauanmayemir** [comment]
Yeah doing that helps. It's not as nice as setting dune on to build 'whatever is there' in that dir, but makes the job done.

Do you think current behavior with `glob_files` should be changed or just be recommended against using it?

**Comment by diml** [comment]
Yh, we had this discussion recently with @rgrinberg. I guess for libraries it's a bit odd as you can't do much with just a built library.

The behavior of `glob_files *` is the right one. We could store the js files generated by jsoo in a separate directory I suppose, that would prevent them from being included in `glob_files *`. That would make sense given that they are not always present and their presence depends on the build profile.

**Comment by rgrinberg** [comment]
> The behavior of glob_files * is the right one. We could store the js files generated by jsoo in a separate directory I suppose

I've also considered this. I think this would be ideal.

I also wouldn't recommend users to depend on archive files directly as it encourages non portable rules. Soon we're going to add an `@all alias to every directory which should make things a little more straightfoward

**Comment by rgrinberg** [comment]
@diml I wonder if we should just let the install target be more dynamic by letting it include a list of files. I recall we discussed this before, what was the objection against that again?

**Comment by diml** [comment]
Since we now have the `@all` alias, is moving the files still relevant?

**Comment by diml** [comment]
Ok, for cm* files, we were careful as there were users about these files. For .cma.js files, if nobody references them explicitly, it's fine to move them without notice. Additionally, the rules are not always setup, depending on the build profile. So it seems fine to me to move them without notice

**Comment by rgrinberg** [comment]
This is fixed for libraries. Note that `(glob_files dir/*)` will still include `.js` files when dir defines executables. Fixing that would unfortunately be more intrusive.
