### ISSUE TITLE
dune build hangs under Windows

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#1303]
I am getting this when trying to build `master` under Windows:
```
...
ocamldep returned unexpected output for _build/default/src/stdune/either.ml:
-> required by src/stdune/.stdune.objs/either.ml.d
-> required by src/stdune/.stdune.objs/either.ml.all-deps
-> required by src/stdune/stdune.cmxa
-> required by bin/main_dune.exe
-> required by _build/install/default/bin/dune.exe
-> required by dune.install
...
```
and then it hangs a little while later.

- The particular file reported changes each time.
- I am starting from a clean tree (`git clean -fdx`) and using the `ocaml bootstrap.ml` method.
- **It works fine if I pass `-j 1`**
- Maybe related to #1299 ?

**Comment by diml** [comment]
It might be related to the changes to the scheduler indeed. We recently started using system threads to acknowledge various source of events. Although given the way we use threads it should work the same between Unix and Windows.

I've seen similar transient errors in the past though. One things that is frustrating about ocamldep is that when it fails it fails silently and still returns with exit code 0.

**Comment by nojb** [comment]
I did this, but am not sure what I am looking for...

**Comment by diml** [comment]
I was wondering if ocamldep was seeing a truncated or inexistant `.ml` file for instance.

**Comment by diml** [comment]
In which case it would output nothing.  Thinking about it again, it's not going to help as the file copy will be done by Dune itself. We'd need to change the ocamldep command itslef to check that. You could try that by replacing `get_ocaml_tool_exn "ocamldep"` in `src/context.ml` by another command that saves the input somewhere.

**Comment by diml** [comment]
That doesn't explain why it hangs though...

**Comment by diml** [comment]
BTW, is it easy to reproduce? I.e. any chance you could bisect the issue to see if it is #1299 or another commit?

**Comment by nojb** [comment]
Yes, it happens every time. Will check which commit it is and come back here.

**Comment by nojb** [comment]
I think the culprit is 0c4503b4.

**Comment by nojb** [comment]
Thanks for the quick fix!
