### ISSUE TITLE
Fail on AppVeyor

### ISSUE THREAD

**Issue by Chris00** [ocaml/dune#1339]
Dune 1.2.1 fails on AppVeyor with [the message](https://ci.appveyor.com/project/kennknowles/ocaml-freetds/build/1.0.15#L390):
```
Fatal error:
File ".\src\format\opamFormat.ml", line 328, characters 9-15: Assertion failed
```

**Comment by diml** [comment]
I believe this failure is from opam. There is no `opamFormat.ml` file in dune.

**Comment by Chris00** [comment]
Right, reported too fast! :-)  (This happened at the time of the transition to Dune.)
