### ISSUE TITLE
Dune doesn't recognize manual revert of executables

### ISSUE THREAD

**Issue by kyldvs** [ocaml/dune#1342]
1. Change some files
2. Build the executable for your project `./_build/default/bin/foo.exe`
3. Manually revert `./_build/default/bin/foo.exe` in your source control
4. Running build again does not re-update `foo.exe` to be based off of the current source (bug)

I guess something is cached that causes dune to not update the executable when you've manually reverted it. Workaround right now is to do some sort of change in the source, build, then revert the change, then build.

(@jordwalke This is the bug I was talking about)

**Comment by diml** [comment]
This doesn't look right indeed. I submitted a PR to fix this.

Out of curiosity, why do you commit your `_build`?

**Comment by kyldvs** [comment]
We don't commit the entire `_build`, just the `.exe` (which we do have to manually add because `_build` is intentionally ignored otherwise).

It's so that people can checkout the repo and use the executables immediately without needing to set up our Reason build pipeline.

**Comment by diml** [comment]
I see. Dune has some support to promote targets to the source tree and keep them up to date, that could be useful here.

**Comment by kyldvs** [comment]
Maybe we can look into improving that then, cc @jordwalke
