### ISSUE TITLE
"modifying a dependency" test sometimes fails

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#1355]
Since #1343, the `action-modifying-a-dependency` test seems to be flaky. Sometimes it passes, sometimes not. Any idea why @diml ?

**Comment by diml** [comment]
Is it only on OSX or on Linux as well? OSX timestamps are not precise and this has caused issues in the past, I'm wondering if that's the same thing here.

**Comment by diml** [comment]
Added some debug output in #1359

**Comment by rgrinberg** [comment]
Unfortunately, this breaks the tests on OSX as `-d` is not an option for `touch` on OSX.

**Comment by emillon** [comment]
Does OSX touch support -t? in that case we can hardcode a date in the future. Not great, but that would work.

**Comment by rgrinberg** [comment]
Seems like it:

```
     -t      Change the access and modification times to the specified time instead of the current time of day.  The argument is of the form ``[[CC]YY]MMDDhhmm[.SS]'' where each pair
             of letters represents the following:

```
