### ISSUE TITLE
`jbuilder subst -p name` leads to an error

### ISSUE THREAD

**Issue by hannesm** [ocaml/dune#1360]
when I execute the following command: `opam pin add charrua-core --dev` (using opam2, jbuilder.transition, dune.1.3.0 here), I get the following error:

```
#=== ERROR while compiling charrua-core.0.10 ==================================#
# context     2.0.0 | freebsd/x86_64 | ocaml-base-compiler.4.06.1 | pinned(git+file:///usr/home/hannes/devel/mirage/charrua-core#HEAD#83d7c15c)
# path        /usr/home/hannes/.opam/4.06.1/.opam-switch/build/charrua-core.0.10
# command     /usr/home/hannes/.opam/4.06.1/bin/jbuilder subst -p charrua-core
# exit-code   1
# env-file    /usr/home/hannes/.opam/log/charrua-core-88899-60459a.env
# output-file /usr/home/hannes/.opam/log/charrua-core-88899-60459a.out
### output ###
# Error: cannot determine name automatically.
# You must pass a [--name] command line argument.
```

from the opam file in question:
```
build: [
  ["jbuilder" "subst" "-p" name] {pinned}
  ["jbuilder" "build" "-p" name "-j" jobs]
  ["jbuilder" "runtest" "-p" name "-j" jobs] {with-test}
]
```

IIRC #954 was the reason to add `"-p" name` to a wide range of opam packages, and #960 adjusted `subst` behaviour. from what I can tell, one solution is to move the package to dune (but that won't fix the opam files in opam-repository).

**Comment by hannesm** [comment]
@rgrinberg thanks for your quick answer. since there are 697 occurences of `"jbuilder" "subst"` in opam-repository (out of which only 3 pass "-n"), I've the feeling that an intermediate fix is necessary.

**Comment by hannesm** [comment]
hmm, unclear to me which subset of the above mentioned packages are problematic

**Comment by hannesm** [comment]
> The subset of packages that are problematic are those that don't have an opam package that is a prefix of all other packages.

ah, thanks! any way of finding out which opam packages match this?  if it's a small enough amount, we can update them and don't need additional logic in dune. from a brief skim over the opam-repository, `ppx_cstruct` is one of them (and already passes `--name` to `subst`), and charrua being the only other one (but I may have missed some).

**Comment by diml** [comment]
We can check the [dune-universe](https://github.com/dune-universe/dune-universe) to get an idea

**Comment by diml** [comment]
I had a look and the packages that need a `--name` argument are the following ones:

- charrua-client.0.10
- charrua-client.0.9
- charrua-client.0.10
- charrua-client.0.9
- charrua-client-lwt.0.10
- charrua-client-lwt.0.9
- charrua-client-lwt.0.10
- charrua-client-lwt.0.9
- charrua-client-mirage.0.10
- charrua-client-mirage.0.9
- charrua-client-mirage.0.10
- charrua-client-mirage.0.9
- charrua-core.0.10
- charrua-core.0.9
- charrua-core.0.10
- charrua-core.0.9
- charrua-unix.0.10
- charrua-unix.0.9
- charrua-unix.0.10
- charrua-unix.0.9
- dns.1.0.0
- dns.1.0.1
- dns-async.1.0.0
- dns-async.1.0.1
- dns-lwt.1.0.0
- dns-lwt.1.0.1
- dns-lwt-unix.1.0.0
- dns-lwt-unix.1.0.1
- dryunit.0.3.1
- dryunit.0.4.0
- dryunit.0.4.1
- dryunit.0.5.0
- kicadsch.0.2.0
- kicadsch.0.3.0
- mirage-dns.3.0.0
- mirage-dns.3.0.1
- netchannel.1.7.1
- netchannel.1.8.0
- plotkicadsch.0.1.4
- plotkicadsch.0.2.0
- plotkicadsch.0.3.0
- xenstore_transport.0.9.6
- xenstore_transport.1.0.0
