### ISSUE TITLE
Improve the behavior of build interruption

### ISSUE THREAD

**Issue by ejgallego** [ocaml/dune#1363]
Dear Dune devs,

when interrupting a build [`Ctrl-C` in Linux] current progress of the build is not saved. It would be great if Dune could try to preserve some of the performed work.

**Comment by diml** [comment]
Indeed, I started a branch to make dune handle signals gracefully, I'll push what I have so far.

**Comment by diml** [comment]
I pushed the code in #1366

**Comment by ejgallego** [comment]
To what me respects this issue can be closed, as #1366 has been working beautifully in LInux so far.

Maybe @diml wants to keep it open as it seems there is still work to do for Windows?

**Comment by diml** [comment]
Ok, I created #1389 to track signal handling on Windows.
