### ISSUE TITLE
wrapped false; META missing name; opam cannot find

### ISSUE THREAD

**Issue by tomjridge** [ocaml/dune#1367]
The repo here:

https://github.com/tomjridge/p1_core

(commit 25663fa86384a36361f0d91a13d97519a168bc5e)

has a subdir src with the following dune file:
```

; (include ../dune) automatically included?

(library
  (name p1_core)
  (public_name p1_core)
  (wrapped false)
;  (preprocess (pps ppx_deriving_yojson))
  (libraries tjr_lib))

; (include_subdirs unqualified)

```
After building, trying to install using dune succeeds, but the META file is missing a name, so appears invisible to opam (opam list does not show the p1_core library).

What am I missing?

**Comment by tomjridge** [comment]
The META that is installed into .opam looks like:

```
version = "opam??"
description = ""
requires = "tjr_lib"
archive(byte) = "p1_core.cma"
archive(native) = "p1_core.cmxa"
plugin(byte) = "p1_core.cma"
plugin(native) = "p1_core.cmxs"

```

**Comment by tomjridge** [comment]
By way of contrast, `ocamlfind list` does show the library

**Comment by diml** [comment]
There is no name in META files. opam doesn't read META files, these files are read by tools such as `dune` or `ocamlfind`. The only way to make opam see a package is to let opam install it. You can install local packages using the `opam pin` functionality.

**Comment by tomjridge** [comment]
dune --help gives:

```
       install
           Install packages using opam-installer.

```
Isn't this using opam?

**Comment by diml** [comment]
Ah, this comment needs to be updated as we are no longer using `opam-installer`. BTW, installing something with `opam-installer` won't make opam see it. I don't know if this is considered bug or not though.

**Comment by diml** [comment]
I checked and `dune --help` doesn't mention opam-installer in recent versions of dune.

**Comment by tomjridge** [comment]
Thanks for your help!
