### ISSUE TITLE
Formatters: ocamlformat only depends on .ocamlformat in the current dir

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#1369]
As discussed in #1252, it would be nice if each `ocamlformat` invocation could depend on all the `.ocamlformat` files, including those higher in the directory hierarchy. The formatting should already be correct because `--name` is passed and config files are resolved from there, but at the moment, no reformatting will be triggered when a `.ocamlformat` that is higher up is modified. The linked bug includes some pointers about how to implement this.

**Comment by hhugo** [comment]
FYI, maybe useful (but probably needs more work on the ocamlformat side),
 ocamlformat has an option to print where configs comes from (`--print-config`)
```
$ ocamlformat --print-config src/Source.ml > /dev/null
margin=77 (/home/hugo/ocamlformat/.ocamlformat:1)
wrap-comments=true (/home/hugo/ocamlformat/.ocamlformat:2)
```

**Comment by samoht** [comment]
We were discussing with @gpetiot about that as well, and maybe an option to expand the full ocamlformat configuration at a particular directory would be useful, e.g.:

```
$ ocamlformat --print-full-config src/
margin=77
wrap-comments=true.
...
```

And `dune` could just cache the output of that command.

**Comment by emillon** [comment]
I think we'll have to start with a coarse overapproximation (formatting for all ocaml files depends on all .ocamlformat files) which is sound.

Is it correct to say that `ocamlformat` will only consider files named `.ocamlformat` in the source directory and all parent directories until `--root`?

If that's the case, it's probably fine to just add all of these using `Build.if_file_exists`. We don't even need special support from `ocamlformat` itself except for `--root`.

**Comment by gpetiot** [comment]
> Is it correct to say that `ocamlformat` will only consider files named `.ocamlformat` in the source directory and all parent directories until `--root`?

We also consider:
- $XDG_CONFIG_HOME/.ocamlformat
- $OCAMLFORMAT (options can be set in the environment variable)
- in a near future, .ocp-indent files will also be considered (https://github.com/ocaml-ppx/ocamlformat/pull/445)

**Comment by gpetiot** [comment]
It is not considered when `--root` is passed, my bad.
