### ISSUE TITLE
[feature] sphinx support ?

### ISSUE THREAD

**Issue by ejgallego** [ocaml/dune#1377]
Dear Dune developers,

in Coq, we use Dune to build the Sphinx-based documentation as the Sphinx build depends on several build artifacts; this turns out to be very convenient.

The main question is how to generate the right install rules for the generated documentation. Indeed, `(rule ...)` will only work for files in the same directory, and it seems to us that we'd like to keep the build in a separate directory. We can use some workarounds but indeed it doesn't seem very elegant.

What is the plan wrt Sphinx?

**Comment by diml** [comment]
I suppose one way to handle this would be to allow a rule to produce a whole directory. We do something like this for odoc for instance as we don't know what files it produces in advance. However, this is currently not very well integrated, so this would need some more work to support installation.

**Comment by rgrinberg** [comment]
Special support for sphinx is unlikely, but it seems like this feature is along the lines of dune supporting to build artifacts by calling out other build systems (usually make). We already partially support that, so it makes senes to extend the support.

**Comment by ejgallego** [comment]
Indeed going the same way than what is done for `odoc` seems reasonable, thanks!

**Comment by rgrinberg** [comment]
Well odoc is receiving quite special treatment - support on that level doesn't seem likely. I'm thinking about support along the lines of `self_build_subs_archive`. But as @diml said, we'll need a richer target specification language.

**Comment by ejgallego** [comment]
The way we are generating the install rule now is by a generated file that indeed dumps the full contents of the directory and can be promoted if they do change. But indeed having a directory as a target would save us from doing that I think.

**Comment by ejgallego** [comment]
> I suppose one way to handle this would be to allow a rule to produce a whole directory.

I wouldn't mind for now allowing a rule to generate targets also in the subdirs, already the dependency on the docs says `(source_tree doc/sphinx)` even if that mode has to be specially enabled.

This way, we could generate a `dune` file and promote it when the doc build changes.

**Comment by ejgallego** [comment]
The thing is that for Coq we can workaround the same-dir restriction as each call to `coqc` produces a single file, thus we generate several dune files.

**Comment by rgrinberg** [comment]
Btw, another feature to support would be to check in and install the generated manual in man/info form. Readthedocs is nice, but it's handy to have the manual accessible locally as well. So in addition to directory targets, it would be nice to have the man/info targets along with the promotion rules.

I believe that @Khady proposed this initially.

**Comment by Khady** [comment]
Yep and I have worked on it. It is in a branch somewhere in my computer. But I am not sure of what is actually the good way to do it. Either store the man and info in the git repo all the time. Which means that people who modify the doc must also update the man and info. Or we created them on the fly when dune is compiled. But only for people who have sphinx installed on their computer. Let me know what solution you think is the best and I'll push what I have.

**Comment by diml** [comment]
I believe that to build the doc, we need not only sphynx but also the readthedoc theme, so it might be hard to detect when the doc can be built without errors. Storing them in the git repo is probably the easiest solution.

Ideally, it would be a service that automatically update it and pushes the result to github so that contributors don't have to install sphynx. I wonder if it's something that can be automated with github actions (/cc @avsm).

**Comment by jordwalke** [comment]
Attempting to implement the feature request in [this pull request](https://github.com/ocaml/dune/pull/1547)

**Comment by rgrinberg** [comment]
The right tools to implement this feature are now present:

1. We have support for directory targets.
2. The install stanza can take an `(:include ..)` form that can select whatever files need to be installed.
