### ISSUE TITLE
ppx_deriving_yojson.runtime, order of libraries when building exe

### ISSUE THREAD

**Issue by tomjridge** [ocaml/dune#1380]
Hi,

Not sure if this is an issue for dune, or for ppx_deriving_yojson...

In the file here:

https://github.com/tomjridge/tjr_lru_cache/blob/master/test/dune

I am trying to build an exe using the tjr_lru_cache library, which depends on lots of other libraries.

The build succeeds! (Good!)

But if the ppx_deriving_yojson.runtime lib is moved after tjr_lru_cache library then I get an error that the ppx...runtime cannot be found, but is required by isa_btree (a library very early on in the dependency chain).

Indeed, isa_btree is a library that uses ppx_deriving_yojson, but it doesn't need ppx_deriving_yojson.runtime (because it is only a library). isa_btree is not built by dune but by a simple Makefile. Clearly any exe linking against a lib that uses ppx_deriving_yojson will need ppx....runtime. And I assume that the ordering somehow matters because ppx_deriving_yojson occurs early in the dependency chain.

Anyway! The question is: what do you advise in situations like this? Do we need to consider the order of the library dependencies? Or somehow always include a dependency on ppx_deriving_yojson.runtime even in libraries with no executables? Or is there some way to specify that exes have additional dependencies?

Thanks

**Comment by diml** [comment]
I don't whether this applies to ppx_deriving_yojson, however the general idea about ppx runtime libraries is that `ppx_foo` generates code that references `ppx_foo.runtime`. Given that, any code that uses `ppx_foo` needs to depend on `ppx_foo.runtime`, whether it is a library or executable.

Given your description, I believe that `isa_btree` should depend on `ppx_deriving_yojson.runtime`.

**Comment by tomjridge** [comment]
OK, thanks. That fixes the issues.
