### ISSUE TITLE
Better handling of signals on Windows

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml/dune#1389]
Currently, we don't exit cleanly on Windows when the user presses Control+C

**Comment by nojb** [comment]
OK, so I tried again with a clean environment and it seems to work now (native console); not sure what was the problem before. Apologies for that!

For info, `omake` (compiled as a native Windows program) is able to handle CTRL-C also when running under Cygwin. It may be worth exploring how it does that at some point.

**Comment by diml** [comment]
Ok, it's worth investigating what omake does indeed. In the meantime, should we enable handling of signals on Windows? i.e., when running under cygwin, does calling `Sys.set_signal Sys.sigint ...` make the behavior worse?

**Comment by nojb** [comment]
No, it doesn't. I think we should enable it back.

**Comment by diml** [comment]
Ok, I enabled it in master

**Comment by rgrinberg** [comment]
@nojb does this work for you? can we close?

**Comment by nojb** [comment]
> @nojb does this work for you? can we close?

I think so, I routinely use CTRL-C to cancel builds and mostly it seems to work.
