### ISSUE TITLE
menhir: unknown option '--infer-write-query'

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#1392]
Hi,

It seems that the new menhir features pass `--infer-write-query`. This makes the test suite fail if an older menhir version is used. I saw this comment:

https://github.com/ocaml/dune/blob/e853f98f4b3fa72b15713f901e04555f7cb74fce/src/menhir.ml#L10-L13

But this seems a bit too recent to just require it. For example, `reason` cannot use this menhir version.

What would it take to support older versions?

Thanks!

cc @fpottier

**Comment by diml** [comment]
We talked about this problem by email before support for the infer mode was made optional. Now that it can be disabled, I suppose that we can remove the constraint in `dune.opam`.

**Comment by emillon** [comment]
What about the test suite? Shall we skip this test if the menhir binary is too old?

**Comment by diml** [comment]
Yh, I suppose there is no choice. Alternatively, we could use drop the reason dependency by using a dummy refmt binary as for the ocamlformat tests. That would allow to install a more recent version of menhir in the CI.

**Comment by emillon** [comment]
I think it's safe to close this as reason is no longer installed as of f23922c947caa22b6b09703e110752b3447caecc.
