### ISSUE TITLE
The argument of `self_build_stubs_archive` is ignored

### ISSUE THREAD

**Issue by diml** [ocaml/dune#1393]
The argument of the `self_build_stubs_archive` is completely ignored, which doesn't seem right. It should be the name of the C library built by the user.

**Comment by nojb** [comment]
Just to clarify, if `(self_build_stubs_archive foo)` is given, the C stubs are expected to be named `libfoo_stubs%{ext_lib}` and `dllfoo_stubs%{ext_dll}` (independently of the name of the OCaml library) ?

**Comment by diml** [comment]
Currently the name that matters is the name of the library, i.e. if you have:

```scheme
(library
 (name foo)
 (self_build_stubs_archive bar))
```

then the C stubs are expected to be named `libfoo_stubs%{extlib}` and `dllfoo_stubs%{ext_dll}`. The name `bar` is just ignored.

**Comment by diml** [comment]
What we want is indeed the behavior you describe.

**Comment by nojb** [comment]
Got it, thanks.
