### ISSUE TITLE
OSL syntax is not canonical

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#1394]
Hi,

I'm porting some `jbuild` files to `dune` syntax.

The following is accepted:

    (flags (-bin-annot -safe-string -w "A-40-42-44-48" -warn-error "+1..49" -warn-error "-15"))

I'd expect an error message, since this is jbuild syntax. The following works (I'd expect this to be the only supported one):

    (flags -bin-annot -safe-string -w "A-40-42-44-48" -warn-error "+1..49" -warn-error "-15")

But this one also works:

    (flags (((-bin-annot -safe-string -w "A-40-42-44-48" -warn-error "+1..49" -warn-error "-15"))))

It will be a bit difficult to change because it's a breaking change but I think we need to fix this.

Thoughts?

**Comment by diml** [comment]
The argument of `flags` is a DSL, the *ordered set language*. `( ... )` is just a construction in this DSL, that's why these examples are accepted. I guess we could require the DSL to be in the smallest form possible, to improve readability. We could enforce that in 2.0.

**Comment by emillon** [comment]
Ah, I didn't think that it could be OSL grouping. I was expecting an extra `(enter)` or something. I'll add a pointer to 2.0.

**Comment by emillon** [comment]
As the reporter of this issue, I don't think that this is super important to have. As a maintainer, this is the kind of checks we could add to a linting tool, but in any case we can close.
