### ISSUE TITLE
[Doc] Roadmap cross-compilation missing

### ISSUE THREAD

**Issue by exced** [ocaml/dune#1412]
Hi there,
It seems the cross-compilation roadmap link  is broken in the README.

### Reproduction link
[https://github.com/ocaml/dune/](https://github.com/ocaml/dune)
[https://github.com/ocaml/dune/blob/master/ROADMAP.md](https://github.com/ocaml/dune/blob/master/ROADMAP.md)

### What is expected?
Cross-compilation roadmap page opens

### What is actually happening?
Page not found

I read the contributions guidelines

**Comment by diml** [comment]
We can reformulate this sentence now that cross-compilation is supported.

**Comment by diml** [comment]
This is now fixed
