### ISSUE TITLE
Generated alias module is installed with ml-gen extension

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1414]
As the `gen-opam-install-file` tests indicate, the sources for the generated alias module are installed with an inconvenient extension (`.ml-gen`). If we're installing this generated file, I think it makes sense to rename it to an `.ml` file.

**Comment by diml** [comment]
That seems fine. FTR, the reason we use `.ml-gen` during the build is to that it is not picked up by `(glob_files *.ml)`. Given that the user doesn't know about this file, it might be surprising otherwise.

**Comment by diml** [comment]
(I clicked "close and comment" by accident)

**Comment by emillon** [comment]
This has been fixed by #1425.
