### ISSUE TITLE
Cross project environment settings

### ISSUE THREAD

**Issue by diml** [ocaml/dune#1419]
It seems that it is sometimes desirable to have `env` settings that cross project boundaries. Currently, the only way to do that is via the `dune-workspace` file, however it is not very fine grained. We could add an alternative stanza, such as `cross_project_env` whose scope wouldn't stop at the project boundaries. Alternatively, we could put such configuration in specific `dune-env` files.

**Comment by emillon** [comment]
What kind of grain would be necessary ? It seems to me that `dune-workspace` is the way to go. `(env)` already supports scoping by context, so it could also be used to scope per project from `dune-workspace`.

**Comment by diml** [comment]
IIUC, it's to set flags globally for vendored projects. i.e. by writing something in `vendor/dune`. Though I'm not sure either why `dune-workspace` is not enough. /cc @avsm @dra27

**Comment by diml** [comment]
In a real project I would expect the following organization though:

```
dune    # contains project specific env settings
src/
  # stuff that needs the project env settings
test/
  # stuff that needs the project env settings
vendor/
  # stuff for which we don't know whether the project specific env settings are good or not
```

**Comment by rgrinberg** [comment]
Yeah, indeed it is. Personally, I have no problem with reorganizing my project around to simplify the build system config, but I many people object to this.

Is a `dirs` option for the env stanza a bad idea? You could change the dune file in your example to be:

```
(env
 (dirs src test)
 ..)
```

Or even:

(env
 (dirs :standard \ vendor)
 ..)

**Comment by emillon** [comment]
If `src` and `test` are in the same project, how about the following:

    (env
      (project thisproject)
      ..
    )

It can catch the vendor directory which corresponds to other projects.

**Comment by rgrinberg** [comment]
project selection seems quite interesting as well. The only problem with it is that it's really not consistent with how we do such selection in other parts of dune. However, this is really because we added the concept of projects much later on.

**Comment by Khady** [comment]
I also thought that nested projects inheriting from parents projects was a feature. Which was pretty convenient to set flags for a specific part of the tree. The env stanza of dune-workspace can be use to emulate some of the behavior. But we will have to write adjustments in all the projects of some specific trees.
Also dune-workspace is not very nice when multiple workspaces can be nested. We have 3 workspaces A, B and C that are nested like A is root folder, which contains B, which contains C. dune-workspace of A would overwrite dune-workspace of B and C. That's a problem for us.

**Comment by diml** [comment]
I opened #1442 to track this issue.

**Comment by diml** [comment]
Regarding the `dune-workspace` file, there has to be a single one. It's not clear how to compose several `dune-workspace` file, in particular how to compose build contexts defined in several `dune-workspace` files. That's why `dune-workspace` in sub-directories are ignored.

> However, this is really because we added the concept of projects much later on.

They were called just "scopes" before, but it was the same scoping rules. The scoping rules in Dune where initially thought for the case where the primary target is opam: each project is a set of opam packages and is a self-contained unit.

It seems to me that we should revisit how all this works, but for now I'm wondering if we shouldn't just add a flag in the `dune-workspace` file to change the behaviour of the `env` stanza globally. For instance, when writing `(env_cross_projects true)` in the `dune-workspace` file, the `env` stanza would always inherit from parent projects. It would then be up to the person creating the workspace to choose the inheritance model.

**Comment by diml** [comment]
@Khady, could you describe your use case a bit more?

**Comment by Khady** [comment]
@diml sorry I missed the notification. I think we can take advantage of the new env behavior, without the cross project. So this should be fine.

**Comment by diml** [comment]
Great. At this point there doesn't seem to be much demand for such a feature, so I'm closing this ticket.

**Comment by davidmlw** [comment]
> In a real project I would expect the following organization though:
> 
> ```
> dune    # contains project specific env settings
> src/
>   # stuff that needs the project env settings
> test/
>   # stuff that needs the project env settings
> vendor/
>   # stuff for which we don't know whether the project specific env settings are good or not
> ```

Are there some progress on this issue? I think it is a very common demand when multiple project are working together, with each project a dedicate dirctory or git sub module.
