### ISSUE TITLE
Dune Global Compilation Flags causes ocamlc compilation error "unknown option -O3"

### ISSUE THREAD

**Issue by cyocum** [ocaml/dune#1427]
While I was doing some investigation into using dune 1.3.0 more effectively in [Cucumber.ml](https://github.com/cucumber/cucumber.ml), I added the stanza from the quick start guide entitled ["Setting the OCaml compilation flags globally"](https://jbuilder.readthedocs.io/en/latest/quick-start.html#setting-the-ocaml-compilation-flags-globally). While I was running the profile `dune build --profile release`, I received the following error:

```
...
.../.opam/4.07.0+flambda/bin/ocamlc.opt: unknown option '-O3'.
...
```
You can see the code on the helpfully named ["dune-stuff"](https://github.com/cucumber/cucumber.ml/tree/dune-stuff) branch.  Is there a way to either add a conditional to the dune file which skips -O3 for ocamlc or something that I have forgotten to do when creating the top-level dune file?

**Comment by ejgallego** [comment]
You may need to use `(ocamlopt_flags -O3)` instead of `(flags ...)`, as the -O flag is only understood by the native compiler.

**Comment by cyocum** [comment]
That seems to have fixed the issue.  Thank you very much.

**Comment by joprice** [comment]
Should this be mentioned here? https://dune.readthedocs.io/en/stable/quick-start.html#setting-the-ocaml-compilation-flags-globally

**Comment by ejgallego** [comment]
@joprice I guess this is already covered in https://dune.readthedocs.io/en/latest/concepts.html#ocaml-flags , but indeed if you have an idea on how to make the documentation better please submit a pull-request

**Comment by joprice** [comment]
I was thinking that the quickstart recommending it will lead people to hit this frequently. Maybe the example could use another flag or use ocamlopt_flags instead of flags.

**Comment by ejgallego** [comment]
Indeed, adding `(ocamlopt_flags )` to the example could be nice.
