### ISSUE TITLE
Alias module should be private whenever a lib interface module exists

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1432]
#1431 got me thinking that we should really just make the generated alias module private whenever the user writes an explicit interface file. This would prevent the leakage of names like `Base__` in the base library for example.

**Comment by diml** [comment]
That would be nice if we could, though I'm not 100% sure that no cmi file will refer to `Base__.X` rather than `Base__X`. This needs some experimentation.

**Comment by rgrinberg** [comment]
Indeed it it not possible. We get errors like `Error: The module Base.Array is an alias for module Base__.Array, which is missing` without the cmi for `Base__`
