### ISSUE TITLE
Overwriting `install` action.

### ISSUE THREAD

**Issue by wieczyk** [ocaml/dune#1434]
It is more a question than issue. Sorry, I did not know where could I ask.

Is it possible to overwrite `install` action? I tried `(rule (targets install)...` but it did not work.

I am actually doing something dirty and not required by any serious project. I am preparing a project for students and I would like somehow disable 'dune install', but keep 'dune build' easy to use. I am just trying to save students from accidentally installing 'current version' in the system/opam.

If it is not possible then it is OK, but any dirty-hack is also OK.

**Comment by rgrinberg** [comment]
> It is more a question than issue. Sorry, I did not know where could I ask.

Asking here is fine. discuss.ocaml.org is another place where the devs answer questions.

There is no way to over write the install action, but you can simply not mark any executables or libraries as public. This will make `$ dune install` a no-op.

**Comment by wieczyk** [comment]
Thank for your time.

I tried, but it also made `dune build` a no-op. When I build some modules by hand, for example by `dune source/student_plugin/student_plugin.cma` then `dune install` installs some `META` files for findlib.

**Comment by rgrinberg** [comment]
Yes, this is a bit of an issue. In dune 1.5, we plan to have an `@all` alias that will in fact build everything for you. For now, as a workaround you can do something like for your students:

```
(alias
 (name default)
 (deps lib1/foo.cma lib2/bar.cma))
```

etc.

**Comment by rgrinberg** [comment]
#1409 is the relevant ticket for 1.5 btw.
