### ISSUE TITLE
How to disable -g?

### ISSUE THREAD

**Issue by wieczyk** [ocaml/dune#1440]
Hi,

```
dune build --verbose
```
Tells me that -g is almost always enabled, even if I put those lines into `dune` file:

```
(env
    (dev
        (flags (:standard -g -w -39-33-26-27))
    )
    (release
        (flags (:standard -w -39-33-26-27))
    )
)
```

Can I remove `-g` ? :-)

**Comment by rgrinberg** [comment]
Is the `-g` flag causing you any issues? I don't think it's possible at the moment, but if there's a use case for it, then we might allow it

**Comment by wieczyk** [comment]
I am wondering if it can affect performance (especially for the byte code). I guess collecting frames (names?) for backtrace could affect execution time.

**Comment by rgrinberg** [comment]
AFAIK `-g` will only affect binary size. It should not affect runtime speed.
