### ISSUE TITLE
Ocamformat presets

### ISSUE THREAD

**Issue by gtrak** [ocaml/dune#1443]
Is there a way to use a preset with `dune build @fmt`.  It doesn't seem to be documented, and we'd like to experiment with this.

**Comment by jberdine** [comment]
Do you mean you want to configure the behavior of ocamlformat when called by `dune build @fmt`? If so, it is configured the same way as without dune: primarily using .ocamlformat files. See ocamlformat's [README](https://github.com/ocaml-ppx/ocamlformat/blob/master/README.md) and `ocamlformat --help` for more info. If you mean something else, can you clarify?

**Comment by gtrak** [comment]
It seems ocamlformat presets are supplied via a command-line flag, but I don't see a way to pass any through dune.

https://github.com/ocaml-ppx/ocamlformat/blob/master/README.md#preset-profiles

**Comment by gtrak** [comment]
Ah, I should have read a little closer:
You can use 
```
profile = <name>
```
in .ocamlformat
