### ISSUE TITLE
Can't kill `dune exec ...` with C-c

### ISSUE THREAD

**Issue by anmonteiro** [ocaml/dune#1451]
Starting with Dune 1.4, it looks like when running my executable with `dune exec myProgram.exe` I can't send C-c to kill it anymore

**Comment by samoht** [comment]
Same issue here.

**Comment by diml** [comment]
Hmm, it's easy to fix for `dune exec` but in fact the same issue exist for all programs started by dune :/ We'll need to copy&paste `Unix.create_process` to fix this  properly
