### ISSUE TITLE
Emacs mode: `dune-keywords-regex` is not found

### ISSUE THREAD

**Issue by bixuanzju** [ocaml/dune#1452]
How to reproduce:
1. Press `C-c . l`
2. Minibuffer shows "Error: (void-variable dune-keywords-regex)"

**Comment by iitalics** [comment]
Hello, I understand that this issue is fixed, but I recently downloaded Dune from OPAM and this issue still exists on the package manager and that is very frustrating (dune mode is completely unusable). How long until this fix is pushed?

**Comment by iitalics** [comment]
Well, it appears I'm getting an old Dune version (1.2.1) for some reason so I will look into why that is, but it would be desirable if some sort of back-porting is possible because these typos entirely break dune-mode

**Comment by emillon** [comment]
That's an unfortunate typo, but I don't think there's any disadvantage to upgrading to the latest dune version (there are no extra dependencies or dropped compatibility).
