### ISSUE TITLE
Do not build .cmt .cmti files for non merlin context

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1460]
These do not seem very useful for other contexts. Yes, building these files will probably not save so much time, but they can get quite big so it's a nice space saver.

**Comment by emillon** [comment]
Not sure whether it's relevant, but we need to install these files anyway. How does that work at the moment, are they picked from the merlin context already or just the default one?

**Comment by rgrinberg** [comment]
Hmm, you're right. The default context is used for installation and hence it should always include these .cmt and .cmti's.

I suppose we should make the .cmt and .cmti's available only in the merlin and the default context.

As a side note, it should be possible to select the installation context in the workspace as well.

**Comment by diml** [comment]
BTW, is merlin the only consumer of cmt files?

**Comment by emillon** [comment]
Some static analysis tools like [dead_code_analyzer](https://github.com/LexiFi/dead_code_analyzer) work by reading cmt files.

**Comment by diml** [comment]
Shouldn't we keep them all the time then? It might be hard to know in advance whether the user will need them.

**Comment by rgrinberg** [comment]
I see, nevertheless I think they're much less used than they're actually built in multi workspace setup. How about a `bin-annot` workspace option that is automatically enabled for merlin and default contexts? This way users can enable them if they'd like to use a special context for dead code elimination or whatever else that might need these files.

**Comment by jberdine** [comment]
> I see, nevertheless I think they're much less used than they're 
> actually built in multi workspace setup.

Definitely true in my experience.

> How about a `bin-annot` workspace option that is automatically enabled 
> for merlin and default contexts?

I like this suggestion. But by 'default' do you mean the one built by 
`dune build -p`, that is, `release`?

**Comment by rgrinberg** [comment]
> I like this suggestion. But by 'default' do you mean the one built by
`dune build -p`, that is, `release`?

Yes, in this case the context would be `default`. This is the name of the context when there's no workspace file.

**Comment by jberdine** [comment]
> > I like this suggestion. But by 'default' do you mean the one built 
> by
> `dune build -p`, that is, `release`?
>
> Yes, in this case the context would be `default`. This is the name of 
> the context when there's no workspace file.

Ah, ok. FWIW, I would never have guessed that from `dune build --help`.

**Comment by rgrinberg** [comment]
Yeah, that's a bit unfortunate. The directories in `_build/` are separate by context (except for `install`). On the other hand, this isn't the most useful information for users anyway.

**Comment by rgrinberg** [comment]
In the end, this isn't so easy to do as it breaks the install targets in all contexts where bin-annot is disabled. Therefore, unless there's really strong demand from users it's not worth doing.
