### ISSUE TITLE
Document how to disable warning-as-errors

### ISSUE THREAD

**Issue by XVilka** [ocaml/dune#1465]
Wasn't able to find any mention of this in the documentation, I had some warnings when using jbuilder, was just ignoring them, after migration to dune it enforces them as errors. I believe many people will meet this problem upon conversion.

**Comment by emillon** [comment]
It's true that it's a bit hidden in the documentation at the moment.

You can disable that behavior by passing `--profile release` to `dune`.

Note that `dune` still ships a `jbuilder` binary that ignores warnings by default, so this means that you can convert your `jbuild` files to `dune` files, while continuing to use the `jbuilder` executable which will ignore the warnings.

**Comment by rgrinberg** [comment]
Perhaps we can add this in the FAQ?
