### ISSUE TITLE
How to specify the ocaml verison?

### ISSUE THREAD

**Issue by qdwang** [ocaml/dune#1468]
I got this warning
```
this use of xxx relies on type-directed disambiguation,
it will not compile with OCaml 4.00 or earlier.
```
How can I set a flag to force using the OCaml >= 4.00?

**Comment by rgrinberg** [comment]
Do you mean you want to set the flag for OCaml >= 4.00 only? If so, then you're luck and you can just set the flag normally. Dune will not compile on OCaml <= 4.02 anyway so you won't be able to support earlier versions than this if you're using it.
