### ISSUE TITLE
Test stanza overwritten action should trigger an error if lang < dune 1.2

### ISSUE THREAD

**Issue by NathanReb** [ocaml/dune#1471]
The possibility to overwrite the default `action` for a `test` stanza was released with dune `1.2` (see #1248) but using it doesn't trigger an error even if `lang` is set to an earlier version of dune.

Here I have the following `dune-project`:

```
(lang dune 1.0)
```

and the following `dune` file:

```
(test
  (name testsuite)
  (libraries
    alcotest
    terminal_size
  )
  (action
    (setenv LD_PRELOAD ./%{dep:dllmock_ioctl.so}
      (run %{test})
    )
  )
)

(rule
  (targets dllmock_ioctl.so)
  (action (run %{cc} -shared -o %{targets} %{dep:mock_ioctl.c}))
)
```

and running `dune runtest` goes just fine.

I can work on a minimal project triggering this if you need.

**Comment by NathanReb** [comment]
cc @emillon

**Comment by emillon** [comment]
Yes, the field is missing a `Syntax.since` :confused: . I'll deal with it (unless you're interested in fixing it).

**Comment by NathanReb** [comment]
sure, I'll give it a go!

**Comment by rgrinberg** [comment]
FYI, I'm not so sure if it's worth fixing retroactively. We risk breaking things for users and we don't gain very much.

**Comment by rgrinberg** [comment]
I don't have a strong opinion on this however so if you think this is preferable then feel free to do it.

**Comment by emillon** [comment]
@NathanReb the idea is to use the pattern described [in this comment](https://github.com/ocaml/dune/pull/1147#issuecomment-426284802).

@rgrinberg yes, I agree that it's a concern. Maybe we can accept the behaviour and emit a warning, like `since ~fatal:false (1, 2)` ?

**Comment by rgrinberg** [comment]
That seems reasonable as well.

**Comment by emillon** [comment]
I think I'll sleep on it. @diml any opinion about how/whether to fix this?

**Comment by diml** [comment]
The `~fatal:false` idea seems good to me.

**Comment by emillon** [comment]
OK! Let's go with `~fatal:false`. @NathanReb let's discuss further details on the PR!
