### ISSUE TITLE
breaking change in the behavior of self_build_stubs_archive

### ISSUE THREAD

**Issue by c-cube** [ocaml/dune#1472]
I have a line `(self_build_stubs_archive (libbatsat_stubs))` in a rust+ocaml project, which works fine with dune 1.3 (with a custom rule to build `libbatsat_stubs.a` and `dllbatsat_stubs.so`). With dune 1.4 I get an error:

```
No rule found for src/batsat-ocaml/src/liblibbatsat_stubs_stubs.a
No rule found for src/batsat-ocaml/src/dlllibbatsat_stubs_stubs.so
```

so clearly the semantics of self_build_stubs_archive` changed. My `dune-project` contains `(lang dune 1.3)` btw.

**Comment by nojb** [comment]
I think you need to replace `(libbatsat_stubs)` by just `(batsat)`. This was a bug in `dune` where the argument to `self_build_stubs_archive` was actually ignored. See #1393 for more info.

**Comment by c-cube** [comment]
Ah, good to know, it works on 1.3 if I replace the field indeed.
