### ISSUE TITLE
dune exec'd programs ignore signals

### ISSUE THREAD

**Issue by copy** [ocaml/dune#1480]
In dune 1.4.0, a program that was started using dune exec becomes uninterruptible by Ctrl-C on Linux. Probably related to https://github.com/ocaml/dune/pull/1366.

**Comment by rgrinberg** [comment]
I believe this is fixed in master. Can you confirm please?

**Comment by copy** [comment]
Yep, it's working on master already.

**Comment by seanpoulter** [comment]
Hey! I'm new to OCaml and ran into this problem this weekend. It looks like 1.5 has been released with the fix but isn't available when I `opam install dune` or `opam upgrade dune`. Any tips? Thanks!

FYI: I've linked back to this issue from https://discuss.ocaml.org/t//2908.
