### ISSUE TITLE
Add support for nested subcommands

### ISSUE THREAD

**Issue by shonfeder** [ocaml/dune#1482]
This is desired for the ideal implementation of #1448 (as discussed in https://github.com/ocaml/dune/pull/1448#issuecomment-430005834 and following).

Currently, cmdliner doesn't support nested subcommands (as already noted in https://github.com/ocaml/dune/pull/5#issuecomment-281114594), and it's not clear from dbuenzli/cmdliner#24 whether it plans to.

Depending on how things shape up on dbuenzli/cmdliner#24, adding support will either mean mean updating or extending the vendored cmdliner.

**Comment by rgrinberg** [comment]
#3936 addresses this

**Comment by shonfeder** [comment]
Closed in #3946
