### ISSUE TITLE
Variable expansion in copy_files

### ISSUE THREAD

**Issue by NathanReb** [ocaml/dune#1487]
I'm wondering what you would think about allowing variable expansion in `copy_files`.

What made me consider that is the following dune file I have in `pkcs11`:

```
(test
  (name test_driver)
  (deps dllpkcs11_fake%{ext_dll})
  (libraries
    oUnit
    pkcs11
    pkcs11.driver
  )
  (preprocess
    (pps
      ppx_deriving.std
    )
  )
)

(copy_files ../../fake/dllpkcs11_fake.{so,dll})
```

And would be really nice to be able to write:

```
(copy_files %{project_root}/fake/dllpkcs11_fake%{ext_dll})
```

So that it doesn't depend on the folder's location within the project and it's consistent with the `deps` field in the `test` stanza.
I guess there should be plenty of other nice use of vars in there as well.

As always, I'm happy to help with this I you feel like it's worth doing it!

**Comment by rgrinberg** [comment]
Sure, this is would be useful.

**Comment by rgrinberg** [comment]
This was fixed sometime ago.
