### ISSUE TITLE
understanding a project requires reading the .opam file & all jbuild files

### ISSUE THREAD

**Issue by jaredly** [ocaml/dune#149]
In order to get my head around a project, I need to
- read the `project.opam` file(s) to see what external dependencies are needed
- read all `jbuild` files in the project to see what binaries and libraries are exported

I would much rather have just one place to look!

I can imagine
1) extending the `.opam` format to list public libraries & executables, and then *not* specifying that information in the `jbuild` files OR
2) making a new project-level file that you can auto-generate the `.opam` file from, which lists external dependencies, and all installable libraries and executables

Maybe this isn't something y'all are interested in, but I think it would make understanding a new project much more straightforward!

**Comment by diml** [comment]
For adding stuff to the opam file, I suppose this would have to be discuss on the opam project. I would definitely not go the way of adding yet another layer generating opam and jbuild files.

What I would suggest is a command `jbuilder describe` that describes what libraries and executables will be installed. Not that after a successful build, you can also look at the `_build/install/default` directory to see exactly what will be installed.

**Comment by jaredly** [comment]
`jbuilder describe` would definitely help! (doesn't help for browsing code on github, though :/)

**Comment by UnixJunkie** [comment]
I'm also not fan of the several jbuild files. Looks like the many _tags ocamlbuild fans were putting everywhere in a source tree (scattering of the build info).

**Comment by dra27** [comment]
@UnixJunkie - except that for jbuilder, having separate jbuild files is a fundamental part of its being composable.

**Comment by rgrinberg** [comment]
The only problem that I personally have with this spread of jbuild files is that it can create quite a bit of redundancy between the files. For example, specifying the same dependencies over and over. But to solve that, jbuilder would need to have some sort of meta language with bindings (as diml contemplated before). Until that issue is settled, I'm not sure if it makes sense to consider this only for aesthetic reasons.

**Comment by diml** [comment]
Technically it wouldn't really be a problem to have a single jbuild file for a whole project, but I don't think jbuilder will ever force users to do so.

@rgrinberg, aren't aliases enough to avoid specifying the same dependencies in multiple places?

**Comment by rgrinberg** [comment]
@diml Not quite. For example, how would I reuse the same set of library dependencies for 2 different stanzas? I know I can factor things into libraries, but it's not always a good option.

**Comment by rgrinberg** [comment]
jbuild files being spread across multiple directories is a feature. It makes it quite easy to vendor and move around libraries in a single workspace.

To remove the redundancy between jbuild & opam files, I'd suggest looking into generating opam files from jbuild files.
