### ISSUE TITLE
Unix signal handling

### ISSUE THREAD

**Issue by hnfmr** [ocaml/dune#1490]
Sorry I am new to OCaml, but when I built a binary using dune, the signal handling is ignored, which is handled properly when I build the binary manually.

Here is the binary source (bin/server.ml):
```
open Sys

let () =
  set_signal sigint (Signal_handle (fun _ -> print_endline "Caught SIGINT"; exit 1));
  Unix.sleep 3
```
bin/dune:
```
(executable
  (name server)
  (libraries unix))
```
When I build with `dune exec bin/server.ml` and it ignores Ctrl+C...

When I build with the following
```
ocamlfind opt -verbose -linkpkg -package unix bin/server.ml
```
and invoke `./a.out`
```
./a.out
^CCaught SIGINT
```
It works fine. Could someone shed some light to me? Maybe my Dune configuration is not correct? Thank you!

**Comment by diml** [comment]
This is a regression in Dune 1.4.0, it is fixed in the master of Dune. We are going to do a minor release soon including the fix to this problem.

**Comment by hnfmr** [comment]
Thank you @diml 
I saw a few related issues after posting this one. I will close this one.
