### ISSUE TITLE
Make ppx runner executable paths shorter

### ISSUE THREAD

**Issue by andreypopp** [ocaml/dune#1497]
We are hitting issues on Windows due to long paths of ppx runner executables. Details here https://github.com/esy/esy/pull/530.

Suggestion by @jordwalke:

> We can currently only construct file paths of length 260 characters, and the segment of the ppx driver path _build/default/.ppx/jbuild/ppx_assert+ppx_compare+ppx_custom_printf+ppx_inline_test+ppx_sexp_conv+ppx_variants_conv+ppxlib.runner is already 130. That combined with our CI running inside of a deep directory causes us to exceed the limit. And it could likely exceed the limit even without deep paths, if someone's project directory happens to be nested deeply and they use a lot of ppx plugins.

> Could Dune instead hash the ppx driver names, then write out some metadata file that people can introspect if they are curious to know which runner contains which plugins?

Response by @diml:

> Sure, using a hash of the ppx rewriter set should be fine. Could you open an issue on the Dune github?

**Comment by diml** [comment]
Thanks. The only technical difficulty is that we need both direction:

1. converting a ppx rewriter set to a hash (easy)
2. converting back a hash to a ppx rewriter set (hard)

To implement the second part, we can keep a table mapping hashes to ppx rewriter sets. We will add an entry to this table every time we compute the hash of a ppx rewriter set. What this means is that running `dune build .ppx/<hash>/ppx.exe` from a clean tree will fail as this table won't be populated, but apart from that everything should still work the same.

**Comment by emillon** [comment]
When is the second direction used?

**Comment by diml** [comment]
Basically, when we need to process a .ml files with ppx_a and ppx_b, we say: I need the ppx driver for ppx_a and ppx_b, which is currently translated to a path of the form `_build/default/.ppx/ppx_a+ppx_b/ppx.exe`. Then, later on during the build there is a point where we need to know how to build `_build/default/.ppx/ppx_a+ppx_b/ppx.exe`. In gen_rules.ml, we notice that this path is of the form `_build/default/.ppx/<something>`, so we interpret it a special way and we translate back the string `ppx_a+ppx_b` as a set of ppx rewriter.

**Comment by emillon** [comment]
Could it be possible to generate the ppx rule without relying on its name at all? ie when a .ml file requires ppx_a and ppx_b, we derive a ppx name, and add a rule to preprocess the source file and another rule to generate the ppx driver?

**Comment by diml** [comment]
We want the ppx driver to be shared between all users of the ppx rewriter set `{ppx_a, ppx_b}` though. So this rule must be generated only once.
