### ISSUE TITLE
Using ocamlformat in dune - what configuration?

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#1502]
Hi,

Now that we have (partial) support for formatting ocaml source code in dune, it is a good time to format its source code.

I think that we all agree that the main benefit is not having to think about it, so any configuration is good, but it's also the time where we need to pick a configuration.

I had a look at the default profile, and the only items worth changing are IMO the following:

### doc-comments=before

In the existing code base, the comments are before. This can be checked with `git grep -C1 '(\*\*'`. If this is something we want to preserve, we should add this option.

### field-space=loose

According to `git grep '\w[:=]' src/**/*.ml`, the only cases we do not use spaces are for labelled arguments. That also avoids the default `{ field= expr }` which looks a bit off (I know...).

### let-and=sparse

By default, `ocamlformat` tries to put all parts of the `and` declaration on the same line. This is incompatible with our preprocessor for `let%map`: it rewrites some lines as `let%map a = b and c = d in` which leads to a parse error.

### sequence-style=terminator

By default `ocamlformat` puts a space before sequence operators. `git grep ' ;$'` reveals that we don't do that.

### type-decl=sparse

By default `ocamlformat` tries to fit type declarations onto a single line. According to `git grep '^\s\+|.\+|' src/**/*.ml | grep -v -- '->'`, we don't do that (we do for pattern matching, though).

I pushed a [use-ocamlformat branch](https://github.com/ocaml/dune/tree/use-ocamlformat) with the code base reformatted using that style; if we agree about the configuration I'll open a proper PR with CI checks, make targets, etc.

**Comment by diml** [comment]
Thanks for looking at this! I looked at the branch and it looks good to me. I'm personally happy to go ahead with this style. Regarding `doc-comments=before` I initially used this style as this is what we use at Jane Street and I personally like this style, however if people generally prefer to have comments after, I'm happy to go with the flow and have them after.

I just noticed that comments are sometimes oddly formatted, such as:

```ocaml
    (** [add_action store alias ~stamp action] arrange things so that
      [action] is executed as part of the build of alias
      [alias]. [stamp] is any S-expression that is unique and
      persistent S-expression.
  *)
    val add_action :
         build_system
      -> t
      -> context:Context.t
      -> loc:Loc.t option
      -> ?locks:Path.t list
      -> stamp:_
      -> (unit, Action.t) Build.t
      -> unit
```

I would have expected:

```ocaml
    (** [add_action store alias ~stamp action] arrange things so that
        [action] is executed as part of the build of alias
        [alias]. [stamp] is any S-expression that is unique and
        persistent S-expression.
    *)
    val add_action :
         build_system
      -> t
      -> context:Context.t
      -> loc:Loc.t option
      -> ?locks:Path.t list
      -> stamp:_
      -> (unit, Action.t) Build.t
      -> unit
```

Do you know if something can be done about this?

**Comment by emillon** [comment]
`wrap-comments=true` will do that, but it will also destroy ascii art banners (that can be seen as a feature maybe?). I pushed a commit that does that.

**Comment by jberdine** [comment]
Note that even with `wrap-comments=true`, comments of the form:
```
(* blah
 * blah
 * blah
 *)
```
should be left alone, preserving manual formatting. The `*`s must align vertically though.

**Comment by diml** [comment]
Ok, I personally prefer `wrap-comments=true`. That way most comments get nicely formatted. The only annoying thing is regarding `{[ ... ]}` code blocks that are being formatted like normal text :/

For the ascii art banners, I suppose we can just get rid of them since it's not a very common thing. It's something I picked up when I was writing DOS programs...

**Comment by emillon** [comment]
Ah I thought it was en emacs thing. I'll open a PR to change these to "normal" comments.

**Comment by samoht** [comment]
> Ok, I personally prefer wrap-comments=true. That way most comments get nicely formatted. The only annoying thing is regarding {[ ... ]} code blocks that are being formatted like normal text :/

I think these should be fixed by https://github.com/ocaml-ppx/ocamlformat/pull/460

**Comment by diml** [comment]
Great!

**Comment by diml** [comment]
I suggest that we wait for:

- the next release of ocamlformat, in particular so that we can benefit from the auto-formatting of doc comments
- big PRs that are in flight to be merged, to avoid painful rebases. In particular #1489

and then start using ocamlformat.

**Comment by emillon** [comment]
LGTM, but the rebases shouldn't be too painful: it amounts to resetting to the meaningful change and reformatting. There's a conflict, but the resolution is automatic.

**Comment by diml** [comment]
Ack. Is `git rebase` expected to work on does the user have something special to do?

**Comment by emillon** [comment]
No, there will be a manual command which should look like `git checkout --theirs && dune build @fmt --auto-promote`. I'll post it in the PR so that it's easier to rebase against.

**Comment by diml** [comment]
Ok, as long as we have a good story for rebasing across the switch to ocamlformat, then we don't need to wait for other PRs to be merged.

**Comment by emillon** [comment]
Indeed, it might be a bit more complicated than what I said. More precisely, to rebase an old branch it will probably be necessary to do it in 3 steps: rebase the branch just before the formatting happened in master; rebase across the reformatting commit (this is the step I described before); rebase the branch against master.

**Comment by hhugo** [comment]
https://github.com/hhugo/merge-fmt should help with the rebase story. I've had good result with js_of_ocaml after turning on ocamlformat.

**Comment by emillon** [comment]
We enabled ocamlformat (though with a custom config) so I think we can close this. Thanks everyone!
