### ISSUE TITLE
Different :include behavior between 1.3.0 and 1.4.0

### ISSUE THREAD

**Issue by Khady** [ocaml/dune#1508]
It seems that the way flags and includes are working has changed
between 1.3.0 and 1.4.0. I don't see anything about it in the
changelog.

We have a dune project with a toplevel dune file that defines the env
for most of the libs and binaries in this project. Two profiles are
defined in this env, and they share mostly the same flags. The common
flags are stored in a `dune_flags.sexp` file, to avoid
duplication. And they are inserted using `:include`.

In a lib project, we have a lib that is supposed to use the env
defined in the project root. So it doesn't define any specific flags.

This pattern used to be working. We could compile the library without
problem, from any place in the dune project. With 1.4.0, the only way
to build the lib is to launch `dune build` from the `lib` directory.

The project tree looks like this:

```
$ tree
.
├── dune
├── dune_flags.sexp
├── dune-project
└── lib
    ├── dune
    └── mylib.ml
```

With dune 1.3.0

```
$ dune clean
$ dune build lib/mylib.a
$ dune utop lib
...
# Mylib.name;;
- : string = "a nice name"
```

With dune 1.4.0

```
$ dune utop lib
No rule found for lib/dune_flags.sexp
File "lib/dune", line 1, characters 0-23:
1 | (library
2 |  (name mylib))
Error: No rule found for lib/dune_flags.sexp
$ dune build lib/mylib.a
No rule found for lib/dune_flags.sexp
File "lib/dune", line 1, characters 0-23:
1 | (library
2 |  (name mylib))
Error: No rule found for lib/dune_flags.sexp
$ cd lib
$ dune build mylib.a
Entering directory '/tmp/dune'
```

`/dune`:

```lisp
(env
 (dev
  (flags (:include dune_flags.sexp)))
 (ci_build
  (flags (:standard (:include dune_flags.sexp) -warn-error +A-d))))
```

`/dune_flags.sexp`:

```lisp
; the default flags in this project
(-thread -strict-formats -strict-sequence -short-paths -safe-string -w +a-4-40..42-44-45-48-58)
```

`/dune-project`:

```lisp
(lang dune 1.0)
```

`/lib/dune`:

```lisp
(library (name mylib))
```

**Comment by diml** [comment]
The 1.4 behaviour definitely looks wrong

**Comment by Khady** [comment]
thanks
