### ISSUE TITLE
dune utop doesn't work when not launched from project root

### ISSUE THREAD

**Issue by Khady** [ocaml/dune#1518]
I have a project that looks like this:

```
$ tree
.
├── dune-project
└── subp
    └── lib
```

I has a root directory with multiple sub directories. Each directory contains libs/executables. In one of them `subp`, there is a another subdirectory `lib` which contain a lib.

`dune utop subp/lib` from the project root works.

`dune utop lib` from the `subp` directory fails with `Cannot find directory: lib`

**Comment by diml** [comment]
Looks like a missing use of `Common.target_prefix`
