### ISSUE TITLE
Support for -custom when building bytecode and native executables.

### ISSUE THREAD

**Issue by modlfo** [ocaml/dune#1519]
I was trying to create a project where I can build both, native and bytecode executable, but the bytecode should be linked a custom runtime (passing the flag `-custom`). the only way I have found to pass the flag is by adding a link flag as:

```
(executable ...
   (link_flags -custom)
)
```
 
However, this method pass the `-custom` flag when linking the native executable. The build fails because when linking the native, the flag is not accepted.

It would be nice to being able to build both targets without needing to change manually the dune file every time.

**Comment by ygrek** [comment]
`(ocamlc_flags (-custom))` used to work for this.
But with dune 2 it doesn't work anymore because final linking stage omits include dirs with lib*_stubs.a libraries.

**Comment by diml** [comment]
Could you try with Dune master? I remember seeing some changes related to this recently.

**Comment by ygrek** [comment]
Did `opam pin add --dev-repo dune`. Result same. When `ocamlc_flags (-custom)` is specified I observe (compared to dune 1) that `-I` to dependent libraries are missing from final link command.

**Comment by diml** [comment]
Hmm, thinking about this again passing `-custom` to `ocamlc_flags` was probably working a bit by chance and only in some cases. When linking with `-custom`, the dependencies should be different than when linking without. So Dune should know that you are passing `-custom`.

A more robust option is to add a new linking mode for this case, such as`byte_with_stubs_statically_linked_in`.

BTW, `-custom` is being deprecated in favour of a new `-output-complete-exe` option.

**Comment by ygrek** [comment]
> passing -custom to ocamlc_flags was probably working a bit by chance and only in some cases

I realized smth was fishy as -custom was not included in link command, only in compile commands, and found out that cma has a field "force custom", that was enabling -custom link of final executable.

> When linking with -custom, the dependencies should be different than when linking without

why so?

> A more robust option is to add a new linking mode for this case, such as byte_with_stubs_statically_linked_in.

yes please :)

**Comment by diml** [comment]
>> When linking with -custom, the dependencies should be different than when linking without

> why so?

When you link the stubs dynamically, the compiler will look for .so files, just to make sure the C functions will be available at runtime. When you link the stubs statically, the compiler will look for .a files to link in the C functions statically. Dune need to know that in order to make the right files available to the compiler.

>> A more robust option is to add a new linking mode for this case, such as byte_with_stubs_statically_linked_in.

> yes please :)

Alright, it's on the todo list. If someone wants to work on it right now, please let yourself know, otherwise it'll be done at some point.

**Comment by diml** [comment]
I started working on it: https://github.com/ocaml/dune/pull/3076
