### ISSUE TITLE
Hash collision error after upgrading to dune 1.5

### ISSUE THREAD

**Issue by shinzui** [ocaml/dune#1524]
After upgrading dune to 1.5, I started getting a hash collision error when running dune build in watch mode. The error does not occur when running dune build without the `-w` flag.  

The full error:

```
Hash collision between set of ppx drivers:
- ppx_compare, ppx_deriving.std, ppx_sexp_conv, ppx_variants_conv
- ppx_compare, ppx_deriving.std, ppx_sexp_conv, ppx_variants_conv
Had errors.
```

I am running OCaml `4.07.0`, dune `1.5.0`, and OPAM `2.0.1` on macOS Mojave `10.14`.

**Comment by diml** [comment]
Thanks for the report, it's just a table that wasn't cleared between builds...

**Comment by diml** [comment]
I had a quick look, however it seems that the build requires a custom version of llvm. An isolated repro would be helpful, or at least a branch that is easy to build with what is available in the main opam repository.

**Comment by rgrinberg** [comment]
I wonder if it's a case sensitivity issue. Are you referring to these ppx's consistently case wise? Is this issue present on all platforms?

**Comment by kandu** [comment]
same here. After upgrading from dune 1.4 to 1.5.1, it reports
```
dune build --workspace dune-workspace.dev --root .
Hash collision between set of ppx drivers:
- ppx_expect
- ppx_expect
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 1
```
If more than one context is defined in dune-workspace.

to reproduce the issue
```
(library
  (name collision)
  (modules collision))

(library
  (name test)
  (modules test)
  (libraries collision)
  (inline_tests)
  (preprocess (pps ppx_expect)))
```
with two empty ml files (collision.ml, test.ml) and run `dune build @runtest`

**Comment by diml** [comment]
Ah, this must be when using several build contexts at once, let me have another look at the code.

**Comment by VMatthijs** [comment]
Not sure if this is the right place to post this, but I'm getting a similar error when trying to run

`opam install ocaml-migrate-parsetree-windows` :
`#=== ERROR while compiling ocaml-migrate-parsetree-windows.1.0.11 =============#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.07.0 | git://github.com/ocaml-cross/opam-cross-windows
# path        ~/.opam/4.07.0/.opam-switch/build/ocaml-migrate-parsetree-windows.1.0.11
# command     ~/.opam/4.07.0/bin/jbuilder build -p ocaml-migrate-parsetree -j 7 -x windows
# exit-code   1
# env-file    ~/.opam/log/ocaml-migrate-parsetree-windows-5794-05296d.env
# output-file ~/.opam/log/ocaml-migrate-parsetree-windows-5794-05296d.out
### output ###
# Hash collision between set of ppx drivers:
# - ppx1, ppx2
# - ppx1, ppx2`

**Comment by rgrinberg** [comment]
@VMatthijs which version of dune is that?

**Comment by VMatthijs** [comment]
Dune version 1.5.1 .

**Comment by rgrinberg** [comment]
Would you mind trying this out with master or the upcoming dune 1.6?

**Comment by VMatthijs** [comment]
Of course! Any tips on how to switch to 1.6 without messing up my opam? Or is it safe to just clone the repo and install?

**Comment by VMatthijs** [comment]
Just tried it with master and I'm still getting the same error. :-( Will try with dune 1.4 next.

**Comment by rgrinberg** [comment]
`$ opam pin add dune --dev-repo` should do the job. You could also just wait for 1.6 as the release has already been submitted to opam and we're just waiting for the merge.

**Comment by VMatthijs** [comment]
That still pointed me to dune.1.5.1. However, `opam pin add dune.1.6 --dev-repo` did the job to get dune.1.6.

**Comment by VMatthijs** [comment]
Hmm. I'm still getting the same error, no matter what I try. Do you think this is likely to be a dune error? Or is the problem more likely to be in ocaml-migrate-parsetree-windows?

**Comment by VMatthijs** [comment]
Thank you!! I got it from https://github.com/ocaml-cross/opam-cross-windows .

**Comment by VMatthijs** [comment]
Thank you for looking into this, @rgrinberg ! It'd be so cool if this were fixed and we could get our project cross compiling to Windows. :-)

**Comment by diml** [comment]
@rgrinberg we should indeed use the host context

**Comment by diml** [comment]
although I need to double check again, we might need the main context when building the compat driver. We could indeed store only library names rather that the `Lib.t` values, it just means that we have to do one more lookup when building the driver, though this only happens once per driver so it shouldn't be a big deal

**Comment by VMatthijs** [comment]
Thank you! It works now for me. :-)
