### ISSUE TITLE
Linking C libraries for inline test runners

### ISSUE THREAD

**Issue by psteckler** [ocaml/dune#1530]
I have an OCaml library that gets built by dune, which calls code in a Linux dynamic library (using the `Ctype.Foreign` mechanism). I have other OCaml code that calls this OCaml library, from which dune builds an executable. That executable shows errors when it's run, unless I add flags to the dune file so that the OCaml compiler links against the Linux library (it's librocksdb.so).

The library also contains inline tests, and I see the same kind of error when the inline test runner executes. The solution should be to link against the same Linux library when the inline test runner, run.exe, is built. I don't see how to do that from the dune file.

Do I need to modify dune to do that linking?

Also, there is an example in the dune documentation about adding (OCaml) libraries which suggests I could write a clause like this:
```
(inline_tests (libraries some_lib))
```
For me, dune 1.4 rejects this syntax. Instead, it accepts:
```
(inline_tests ((libraries (some_lib))))
```
This mechanism doesn't have to do with the issue described above, just that I tried the syntax when fiddling with the dune file.

**Comment by psteckler** [comment]
I added the linker flags to the code in `inline_tests.ml` that builds the test runners, allowing them to succeed.

So, consider this issue to be a feature request, to add a clause like `linker_flags` to the `inline_tests` clause.

**Comment by diml** [comment]
Adding `linker_flags` to `inline_tests` seems good.

Regarding the syntax, was that in a `jbuild` file? For backward compatibility, `jbuild` files use the old syntax that has more parentheses. The syntax with less parentheses should work inside `dune` files.

**Comment by psteckler** [comment]
Yup, that was a `jbuild` file, sorry for the confusion.

**Comment by jvillard** [comment]
Unearthing this thread to note that we implemented a workaround for this in Infer: https://github.com/facebook/infer/commit/6850305beeda2baff0c1e1e08a9c8e467e52cb0f

Apologies for this abomination, I'm trying to implement adding `link_flags` to `inline_tests` in dune next.
