### ISSUE TITLE
Document what Dune project (name) does

### ISSUE THREAD

**Issue by brendanlong** [ocaml/dune#1532]
I found that Dune requires (name) when I try to pin ocaml-freetds, but it doesn't seem to require it for local building. Is this something I should add to all projects? What do I do if git repo contains multiple packages (i.e. pgx has 4 opam packages).

[The documentation](https://jbuilder.readthedocs.io/en/latest/project-layout-specification.html#dune-project-files) just says:

> Sets the name of the project

While I'm looking at this, it looks like `(version)`'s documentation is similar and `(fmt)` is completely missing.

**Comment by diml** [comment]
It's required by `dune subst`. Otherwise, it is currently just used in error message. You should add one for any project that you release. The only reason it is optional is so that you don't have to come up with one for quick hacking. Regarding the version, it's basically pending #880.

**Comment by rgrinberg** [comment]
I'm closing this issue as the documentation change requested has been committed. @brendanlong feel free to re-open for further improvements (or just send PR's)
