### ISSUE TITLE
Absolute installation path at compile time

### ISSUE THREAD

**Issue by rlepigre** [ocaml/dune#1534]
I need dune to generate an OCaml configuration file containing something like
```ocaml
let datafile = "/path/to/some/directory/file.data"
```
where `file.data` is installed by dune in, say, the `share` section.

However, there does not seem to be any reliable way for me to know where that section will effectively lie after installation. And I need to write this information in the file.

Does anyone have a solution to my problem?

**Comment by ejgallego** [comment]
This is indeed a problem, we have a few hacks in Coq; see #1185

**Comment by ejgallego** [comment]
Indeed we try to avoid all hardcoded paths, but it is not clear to us what the best way to access "system dirs" is in OCaml.

**Comment by diml** [comment]
I guess when using opam, you can use the `OPAM_SWITCH_PREFIX` environment variable. In general, I'm not sure what the best solution is. #1185 should indeed help with this; the idea is to implement the "right method" once and for all so that individual packages don't have to bother with these questions.

**Comment by ejgallego** [comment]
Sadly `OPAM_SWITCH_PREFIX` won't cover lots of scenario on mildly popular packages :(

**Comment by rlepigre** [comment]
Something that would seem reasonable to me would be to allow a module to be replaced by another one (with the same signature) at installation time (maybe re-linking stuff in the process), and this second module could be generated in an environment where variables are given for effective paths for install sections.

For example, we could imagine something like the following:
```
(rule
  (targets config.ml)
  (action (with-stdout-to config.ml
    (echo "let data = "%{workspace_root}/folder/file.data"\n")))
  (action_install (with-stdout-to config.ml
    (echo "let data = "%{share}/somewhere/file.data"\n"))))
```
In that case, `config.ml` is generated using the standard `action` at build time. However, it is regenerated with `action_install` at installation time, requiring linking the executable files and library files relying on the `Config` module.

Alternatively, support for configuration (doing the mostly the same thing, in a safer but less flexible way) could be added. It is often the case that configuration files only contain data of  rather simple types: strings, lists of strings, booleans...

**Comment by diml** [comment]
For the purpose of testing, I'd like to try #1185. It's both simpler to implement and simpler for developers. 

The idea of adding `dune configure` has been floating around for a while, and I believe it'll eventually be added to dune.

**Comment by diml** [comment]
I suppose you could have a library implementing the same logic in C. Regarding Debian, there is nothing at the moment, though we have been talking about it. @avsm is especially interested in this topic.

**Comment by ejgallego** [comment]
@bobot IIUC we can close this issue as it was fixed by sites?
