### ISSUE TITLE
alias to build documentation for a single package

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#154]
I have a workspace with around 80 packages in it, and I want to build the docs for just a single one.

`jbuilder build @doc` tries to build all the packages, so that doesn't work.

`jbuilder build _doc/mirage-types-lwt/index.html` does build the index.html, but not the css and associated rules for `mirage-types-lwt`

Is there a doc alias for a single package among a larger set that is available?
cc @djs55

**Comment by diml** [comment]
There is no alias for a single package, however the `@doc` alias is recursive so you can do this:

```
$ jbuilder build @foo/doc
```

to build the doc of everything under `foo/`

**Comment by avsm** [comment]
Hm that doesnt work;

```
$ jbuilder build @mirage-types-lwt/doc
No rule found for alias mirage-types-lwt/doc

$ jbuilder build _doc/mirage-types-lwt/index.html
    ocamldep mirage-stack/lwt/mirage_stack_lwt.depends.ocamldep-output
    ocamldep mirage-stack/src/mirage_stack.depends.ocamldep-output
      ocamlc mirage-stack/src/mirage_stack.{cmi,cmo,cmt}
      ocamlc mirage-stack/lwt/mirage_stack_lwt.{cmi,cmo,cmt}
      ocamlc mirage/types/mirage_types.{cmi,cmo,cmt}
      ocamlc mirage/types/lwt/mirage_types_lwt.{cmi,cmo,cmt}
        odoc mirage-stack/src/mirage_stack.odoc
        odoc mirage-stack/lwt/mirage_stack_lwt.odoc
        odoc mirage/types/mirage_types.odoc
        odoc mirage/types/lwt/mirage_types_lwt.odoc
        odoc _doc/mirage-types-lwt/index.html
```

**Comment by diml** [comment]
that's weird. It works when I do it for JS packages:

```
$ jbuilder build @base/doc
...
```

**Comment by avsm** [comment]
Ah it has to be a subdirectory reference and not a package name.

So in my case, `jbuilder build @mirage/types/lwt/doc` works!

Leaving this open to submit a docs PR

**Comment by rgrinberg** [comment]
@avsm I'm pretty sure this is already documented under aliases. Note that this behavior works for all aliases (runtest, install, etc.)
