### ISSUE TITLE
Improve error message for `%{lib:...}`

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1541]
See this comment: https://github.com/ocaml/dune/pull/1537#issuecomment-438438925

Making a ticket so that we don't forget to fix this.

cc @ejgallego

**Comment by jorisgio** [comment]
This also happens with `%{bin:...}` when the given name is not a binary in path and yields a very confusing error.

**Comment by rgrinberg** [comment]
@jorisgio I'm unable to reproduce your issue with in the latest version. Could you try 1.11 please?

**Comment by jorisgio** [comment]
@rgrinberg  https://github.com/jorisgio/dune-repro still same error message in 1.11

**Comment by rgrinberg** [comment]
I see, so the issue is expanding `%{bin:..}` in the `deps` field. I suppose that should work as well.

I'll add some tests cases for both forms in the deps field.

**Comment by rgrinberg** [comment]
This is fixed in master
