### ISSUE TITLE
odoc: use upcoming support-files-targets command

### ISSUE THREAD

**Issue by aantron** [ocaml/dune#1556]
Currently, Dune is [hardcoded to assume](https://github.com/ocaml/dune/blob/79076ae2f2493a9f1e95ea61e2e1017729faedd1/src/odoc.ml#L304) that the only static file generated by odoc is `odoc.css`. However, odoc is now also generating `highlight.pack.js`.

As a consequence, Dune [deletes `highlight.pack.js`](https://github.com/ocaml/dune/blob/79076ae2f2493a9f1e95ea61e2e1017729faedd1/src/build_system.ml#L1152) on the first rebuild of docs during directory cleanup, and does not have odoc re-generate it (which Dune wouldn't do anyway, if it expected odoc to generate the file in the first place). So, after a rebuild, `highlight.pack.js` is missing.

Since the set of files odoc generates is likely to change over time, odoc is adding an `odoc support-files-targets` command (ocaml/odoc#232). Dune should use this during docs builds. We'll probably need to add a conflict with versions of odoc that don't have `support-files-targets` (`<= 1.3.0`).

Since this requires running the `odoc` binary to assemble build rules, it complicates builds in which `odoc` itself is also being built.

The issue with `highlight.pack.js` was originally reported in ocaml/odoc#153.

**Comment by diml** [comment]
In the meantime, what about we simply add `highlight.pack.js` as a static target, and add a conflicts with versions of odoc that don't generate this file?

**Comment by aantron** [comment]
Opened #1557.
