### ISSUE TITLE
[compat] Fix build with OCaml 4.08 `trunk`

### ISSUE THREAD

**Issue by ejgallego** [ocaml/dune#1559]
As of today, Dune build is broken with OCaml `trunk` "4.08" as the upstream `List` module declares a `List.t` type, conflicting with the one in Dune.

It would be great if a compat fix could be implemented so we could use Dune with `trunk`. Note that I am not familiar with the current schedule of OCaml so requesting this fix may be premature [imagine the `List.t` addition gets reverted upstream].

**Comment by diml** [comment]
Indeed. Ideally, we shouldn't use include and manually import the function we use in dune. That would make the code more robust against upstream changes.

**Comment by ejgallego** [comment]
> Indeed. Ideally, we shouldn't use include and manually import the function we use in dune. That would make the code more robust against upstream changes.

Yup, I have prepared a quicker fix for the moment at #1561

**Comment by ejgallego** [comment]
Fixed by #1561
