### ISSUE TITLE
dune should depend on `base-threads`

### ISSUE THREAD

**Issue by kayceesrk** [ocaml/dune#1563]
Dune.1.3.0 introduced support for interrupting and restrarting builds on file changes. See https://github.com/ocaml/dune/commit/0c4503b4c2bbf23652d4f80b4fc9916e92349317. This introduced dependency on `Threads` library. This is not captured in dune's OPAM file. Unfortunately, this is breaking multicore CI. Multicore OCaml does not support threads library yet and installing dune > 1.3.0 deadlocks the build. I discussed this with @dra27 and he agrees.

**Comment by diml** [comment]
That seems fine

**Comment by diml** [comment]
Done in #1564

**Comment by kayceesrk** [comment]
Great. Thanks!
