### ISSUE TITLE
How to disable assertions?

### ISSUE THREAD

**Issue by tomjridge** [ocaml/dune#1569]
I'm unsure what I should do to disable assertions for an executable I am building. Perhaps this is something to do with profiles? I'm not sure what the dev and release profiles actually do.

For reference, the dune file for the exes is:

```
(executables
  (names tjr_kv_test test)
  (libraries tjr_kv lwt.unix tjr_profile))
```

Thanks

**Comment by tomjridge** [comment]
Found in documentation. Please ignore this.

**Comment by tomjridge** [comment]
Actually, I am still having trouble. Now my dune file is:

```
(executables
  (flags -noassert)
  (names tjr_kv_test test)
  (libraries tjr_kv lwt.unix tjr_profile))
```

But still assertions are enabled.

**Comment by rgrinberg** [comment]
Where are your assertions located? If they're in your libraries (tjr_kv and tjr_profile), you will need to compile those libs with `-noassert` as well.

**Comment by tomjridge** [comment]
Ah! OK. Thanks. Is there anyway to somehow enable/disable this across a bunch of projects? Each project is a library with its own .opam file etc. They are mostly subdirectories of a single "parent" directory.

**Comment by tomjridge** [comment]
Some of the projects are not dune-enabled, so I guess some tinkering is required (at least).

**Comment by rgrinberg** [comment]
If all of your libraries are dune, you could look into using profiles. For example, a dune file in the root of all your libraries with:

```
(env
 (release
  (flags (:standard -noassert)))
```

Would enable the flag for all libraries. 

https://dune.readthedocs.io/en/latest/dune-files.html#env

**Comment by tomjridge** [comment]
Thanks very much Rudi!
