### ISSUE TITLE
Watch mode rebuilds continuously if DUNE_BUILD_DIR is set

### ISSUE THREAD

**Issue by andreypopp** [ocaml/dune#1578]
In esy we set `DUNE_BUILD_DIR` so that build dir is out of source and we can have multiple of them for a single project (building simultaneously for different targets and etc).

The problem is that `dune build -w` does not converge with such configuration
(below is the output w/o touching any files):

```
% esy b dune build --watch
Success.
Success.
Success.
Waiting for filesystem changes...
```

The location `DUNE_BUILD_DIR` points to is still within the source tree:

```
_esy/default/store/b/<hash>
```

It might be dune reacts to itself (to artifacts placed by dune there).

If I add

```
(ignored_subdirs (_esy))
```

to `dune` file it **doesn't** help.

If I make `dune` build into `_build` dir (deleting `DUNE_BUILD_DIR` from the env) then it **does** help.

I suspect watch mode doesn't respect ignored directories.

How to repro:

```
% npm install -g esy@0.4.3
% git clone https://github.com/esy-ocaml/hello-ocaml
% cd hello-ocaml
% esy
% esy b dune build --watch
```

**Comment by diml** [comment]
> I suspect watch mode doesn't respect ignored directories.

Yes, that's the case. This is slightly complicated to support as we can't configure the file watcher dynamically. We'd have to stop and restart it whenever such a configuration changes.

**Comment by andreypopp** [comment]
Not an issue with esy anymore.
