### ISSUE TITLE
`dune build` needs two invocations to consider the tree clean.

### ISSUE THREAD

**Issue by ejgallego** [ocaml/dune#1581]
I found this issue in the context of [porting lablgtk to dune](https://github.com/garrigue/lablgtk/pull/14) , after a first `dune build`, the second `dune build` without modifying anything in the tree will still rebuild some targets.

Steps to reproduce:
```
git clone https://github.com/ejgallego/dune-ddup.git
cd dune-ddup
dune clean && dune build && dune build --display=short
```
Result I get in my machine:
```
  ocamlc src/.lablgtk2.objs/gutf8.{cmo,cmt}
```

**Comment by rgrinberg** [comment]
I cannot reproduce on OSX. The second build command does not rebuild anything for me.

**Comment by ejgallego** [comment]
Indeed I have seen some kind of non-determinism in this test as it sometimes rebuilds more than once, for example:
```
$ dune clean && dune build && dune build --display=short
      ocamlc src/.lablgtk2.objs/gutf8.{cmo,cmt}
$ dune clean && dune build && dune build --display=short
      ocamlc src/.lablgtk2.objs/gpointer.{cmo,cmt}
      ocamlc src/.lablgtk2.objs/gutf8.{cmo,cmt}
```

**Comment by ejgallego** [comment]
I am seeing this often, but I am at a loss on how to debug it. Any tips where to start looking?

**Comment by diml** [comment]
You can try adding a few printf in the code to print the stats and digests of the files, in `Utils.Cached_digest`. That might reveal something interesting.

**Comment by ejgallego** [comment]
Uh, it seems the `ocamlopt` call is generating a `cmt`file too?
```
(cd _build/default && strace -e rename /home/egallego/.opam/4.07.1/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w -6-7-9-10-27-32-33-34-35-36-50 -g -I src/.lablgtk2.objs -I src/.lablgtk2.objs/.private -intf-suffix .ml -no-alias-deps -opaque -o src/.lablgtk2.objs/gutf8.cmx -c -impl src/gutf8.ml)
rename("src/.lablgtk2.objs/gutf8.cmt45bad8.tmp", "src/.lablgtk2.objs/gutf8.cmt") = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=8432, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
+++ exited with 0 +++
```

**Comment by ejgallego** [comment]
So indeed that is the problem, I was suspecting that from the start, but it seems very bizarre, doesn't it?

**Comment by ejgallego** [comment]
So this was a typical stale environment variables problem, from some very old OPAM setup I had `export OCAMLPARAM="_,bin-annot=1"` in some init file, and this was triggering the problem.

I am closing, should however Dune clean `OCAMLPARAM`? That's hard to tell I guess.

**Comment by diml** [comment]
well, we could but that's starting to be complicated. Dune already supports setting flags globally via the `env` mechanism. It seems better to me to support only one method but support it well.

**Comment by diml** [comment]
It feels like `OCAMLPARAM` was designed for times where it was difficult to set flags globally

**Comment by ejgallego** [comment]
Indeed, I don't think Dune should mess with `OCAMLPARAM`, maybe at most warn if it's set and unset it.

It feels to me that as you point out, allowing Dune to run with a non-empty OCAMLPARAM will create all kind of problems due to `(env ...)` not being faithful anymore.
