### ISSUE TITLE
Dune suggests incorrect packages

### ISSUE THREAD

**Issue by jstolarek** [ocaml/dune#1582]
Say I have this in my `dune` file:

```
(library (libraries menhirLib))
```

If Menhir isn't installed dune will suggest:

```
$ dune external-lib-deps --missing --only-packages foo --profile development @install
Done: 0/0 (jobs: 0)Error: The following libraries are missing in the default context:
- menhirLib
Hint: try: opam install menhirLib
```
But `menhirLib` does not exist as a separate package - it is part of `menhir` - and so following dune's suggestion ends in an error:

```
$ opam install menhirLib
[ERROR] No package named menhirLib found.
```

**Comment by diml** [comment]
Indeed, unfortunately there is no way for Dune to find out that `menhirLib` is provided by the `menhir` package. Usually, OCaml packages install libraries that have the same name has the package name, or are of the form `<package-name>.something`, so dune assumes that this is the case and that's way it suggests to install `menhirLib`.

**Comment by rgrinberg** [comment]
I'm closing this ticket for now as there's really not much dune can do. If the information to map packages <-> libraries will appear somewhere, we will fix dune to take advantage of it.
