### ISSUE TITLE
[bug] cross compilation when trying to generate .install file

### ISSUE THREAD

**Issue by clecat** [ocaml/dune#1595]
I'm having an issue when trying to generate a .install file for my project while using a toolchain:
`dune build -x esp32 -p gpio-esp32` is working fine but `dune build -x esp32 -p gpio-esp32 gpio-esp32.install` returns `driver.c:4:25: fatal error: driver/gpio.h: No such file or directory` (error solved when using `-x esp32`).

Looks like specifying the toolchain did not work in the second case.
Is this a bug or a misuse of some configuration ?

**Comment by diml** [comment]
Could you compare what dune tries to build in both cases? For instance by passing `-j1 --display short` and  comparing the output.

**Comment by clecat** [comment]
Working build:

    ocamldep src/.gpio.objs/gpio.ml.d [default.esp32]

    ocamlc src/.gpio.objs/gpio.{cmi,cmo,cmt} [default.esp32]

    ocamlopt src/.gpio.objs/gpio.{cmx,o} [default.esp32]

    ocamlopt src/gpio.{a,cmxa} [default.esp32]

    ocamlc src/driver.o [default.esp32]

    ocamlmklib src/libgpio_stubs.a [default.esp32]

    ocamlc src/gpio.cma [default.esp32]


The other one:


    ocamldep src/.gpio.objs/gpio.ml.d

    ocamlc src/.gpio.objs/gpio.{cmi,cmo,cmt}

    ocamlopt src/.gpio.objs/gpio.{cmx,o}

    ocamlopt src/gpio.{a,cmxa}

    ocamlc src/driver.o (exit 2)

    (cd _build/default/src && /home/charlie/.opam/4.06.0+32bit/bin/ocamlc.opt -g -I /home/charlie/.opam/4.06.0+32bit/lib/cstruct -I /home/charlie/.opam/4.06.0+32bit/lib/parsexp -I /home/charlie/.opam/4.06.0+32bit/lib/sexplib -I /home/charlie/.opam/4.06.0+32bit/lib/sexplib0 -ccopt -g -o driver.o driver.c)
    
    driver.c:4:25: fatal error: driver/gpio.h: No such file or directory
    
    compilation terminated.
    
    ocamlc src/gpio.cma


Looks like the esp32 toolchain is definitely not used in the second case
(forgot to mention it, this is the version 1.5.1 of dune)

**Comment by clecat** [comment]
Working build:

    ocamldep src/.gpio.objs/gpio.ml.d [default.esp32]

    ocamlc src/.gpio.objs/gpio.{cmi,cmo,cmt} [default.esp32]

    ocamlopt src/.gpio.objs/gpio.{cmx,o} [default.esp32]

    ocamlopt src/gpio.{a,cmxa} [default.esp32]

    ocamlc src/driver.o [default.esp32]

    ocamlmklib src/libgpio_stubs.a [default.esp32]

    ocamlc src/gpio.cma [default.esp32]


The other one:


    ocamldep src/.gpio.objs/gpio.ml.d

    ocamlc src/.gpio.objs/gpio.{cmi,cmo,cmt}

    ocamlopt src/.gpio.objs/gpio.{cmx,o}

    ocamlopt src/gpio.{a,cmxa}

    ocamlc src/driver.o (exit 2)

    (cd _build/default/src && /home/charlie/.opam/4.06.0+32bit/bin/ocamlc.opt -g -I /home/charlie/.opam/4.06.0+32bit/lib/cstruct -I /home/charlie/.opam/4.06.0+32bit/lib/parsexp -I /home/charlie/.opam/4.06.0+32bit/lib/sexplib -I /home/charlie/.opam/4.06.0+32bit/lib/sexplib0 -ccopt -g -o driver.o driver.c)
    
    driver.c:4:25: fatal error: driver/gpio.h: No such file or directory
    
    compilation terminated.
    
    ocamlc src/gpio.cma


Looks like the esp32 toolchain is definitely not used in the second case
(forgot to mention it, this is the version 1.5.1 of dune)

**Comment by diml** [comment]
We added support for this a while ago, so I don't remember all the details. After the first invocation, what `<package>.install` file is created?

BTW, is the package called `gpio` or `gpio-esp32`? I'm looking at the opam files in the [opam-cross-windows repository](https://github.com/ocaml-cross/opam-cross-windows) and the build command are of the form: `dune build -x windows -p lwt ...`. So if the package is called `gpio`, then you should type:

```
$ dune build -x esp32 -p gpio ...
```

and I believe it will create a `gpio-esp32.install` file.

**Comment by diml** [comment]
This was designed so that existing opam files require as little modification as possible, in this case `s/dune build/dune build -x <target>/` is enough

**Comment by clecat** [comment]
The file "gpio-esp32-esp32.install" is created
The package is called gpio-esp32, but the module is gpio:
```
(library
 (name        gpio)
 (public_name gpio-esp32)
 (c_names     driver)
 (no_dynlink)
 (libraries   cstruct))
```

**Comment by diml** [comment]
Ok, yh the module name doesn't really matter for the package name. Is there still something to do regarding this PR? Maybe the documentation  could be improved?

**Comment by clecat** [comment]
Yes thanks, it's okay for me.
Documentation is always welcome, but it's more an error from me than a lack of informations

**Comment by diml** [comment]
Alright, I'm closing this issue then.
