### ISSUE TITLE
Store aliases in a single DB

### ISSUE THREAD

**Issue by ghost** [ocaml/dune#1605]
Currently, an alias is represented by a plain file in `_build/.aliases` that contains the checksum of its dependencies. However, these files tend to have long paths, causing issues on Windows.

We should instead store the aliases in a single DB file stored in `_build`, that is loaded and saved just like other DB files.

**Comment by rgrinberg** [comment]
One issue with this proposal is that it will badly break the makefile generation. The general issue is that it won't be possible to express dependencies on aliases in the makefiles anymore. One concrete case where this is important is when we setup our fake glob rules for example.

I think those makefile rules aren't really reliable, and we have a better story for bootstrapping so in my opinion, it's alright to break this. @diml is this ok?

**Comment by diml** [comment]
Yh, it seems fine to break it. Additionally, it shouldn't be too hard to recover makefile generation if we wanted to.

**Comment by rgrinberg** [comment]
as discussed with @snowleopard, this isn't needed anymore.

**Comment by snowleopard** [comment]
Just to clarify: we might still want to push these files into a database in future. It just doesn't seem like a priority for now.
