### ISSUE TITLE
dune-project vs dune-workspace

### ISSUE THREAD

**Issue by mc10** [ocaml/dune#1611]
It's not really obvious to me what the difference between dune-project and dune-workspace is. I am aware of the [dune-project files](https://dune.readthedocs.io/en/latest/project-layout-specification.html#dune-project-files), [finding the root](https://dune.readthedocs.io/en/latest/usage.html#finding-the-root), and [workspace configuration](https://dune.readthedocs.io/en/latest/usage.html#workspace-configuration) sections in the manual, but they don't really distinguish between the use cases for the two files. Are they equivalent to each other?

**Comment by rgrinberg** [comment]
You're right that it's not entirely intuitive. The gist of it is that dune-project files define the project root and some general metadata for the project. While workspace files are used to define environment specific (often times) configuration. The idea is that you always check in dune-project files, but dune-workspace files should only be checked in if you want others to replicate your config. Another point of distinction is that a dune workspace may include more than dune project.

**Comment by mc10** [comment]
Alright, I'll close this for now then. Thanks for the explanation!
