### ISSUE TITLE
private modules must be in modules and private_modules fields?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/dune#1618]
Hello,
I feel this is awkward. I was forced to write this:
```
(library
  (name        bst)
  (public_name bst)
  (modules bisec_tree myArray)
  (private_modules myArray)
  (libraries batteries))
```
So that my library compiles with dune.
I would have preferred not to have to repeat the myArray module.
Regards,
F.

**Comment by diml** [comment]
yh, the idea is that `modules` select the modules in the current directory that are attached to the stanza, while `private_modules` and other module selector fields select subsets from the set defined by `modules`. In particular, if you have only one library and no executables in the current directory, then you do not need a `modules` field.

**Comment by rgrinberg** [comment]
Indeed, this is awkward but we are unlikely to make the behavior more clever. We suggest to have a directory per library stanza so that you never have to write a `modules` field.
