### ISSUE TITLE
another `.exe` issue on Windows

### ISSUE THREAD

**Issue by fdopen** [ocaml/dune#167]
There is another `.exe` related problem triggered by js_of_ocaml (beside https://github.com/janestreet/jbuilder/pull/123#issuecomment-310377392): jbuilder complains it can't find `${lib:ppx_tools:ppx_metaquot}` (or `${lib:ppx_tools:rewriter}`) , because the file is named `ppx_metaquot.exe`/`rewriter.exe` under Windows (see: https://github.com/ocsigen/js_of_ocaml/blob/af437fe0467f15d96dae3965f5e3c10dd8f272e1/ppx/ppx_deriving_json/lib/jbuild#L10 ).

**Comment by diml** [comment]
It should work if you replace `${lib:...}` by `${libexec:...}`. /cc @hhugo

**Comment by fdopen** [comment]
No, it still doesn't work with libexec. backtrace:
```
Raised at file "src/import.ml", line 409, characters 7-28
Called from file "src/build_system.ml", line 359, characters 47-76
Called from file "set.ml", line 326, characters 37-58
Called from file "src/build_system.ml", line 359, characters 4-85
Called from file "src/build_system.ml", line 411, characters 6-46
Called from file "src/future.ml", line 93, characters 8-12
```

Btw. the generated `js_of_ocaml-ppx.install` contains the following:

```
lib: [
  "_build/install/default/lib/js_of_ocaml-ppx/META" {"META"}
  "_build/install/default/lib/js_of_ocaml-ppx/opam" {"opam"}
  "_build/install/default/lib/js_of_ocaml-ppx/ppx_js.exe" {"ppx_js.exe"}
  "_build/install/default/lib/js_of_ocaml-ppx/deriving/ppx_deriving_json.cmi" {"deriving/ppx_deriving_json.cmi"}
  ...
]
libexec: [
  "_build/install/default/lib/js_of_ocaml-ppx/ppx.exe"
]
...
```

The exe extension to `ppx_js` is now added by jbuilder (jbuilder.1.0+beta9 didn't add it), but the file is listed under `lib:`, not `libexec:`. Even if it would work, there would still be an inconsistency, how the `.exe` extension is handled.

**Comment by diml** [comment]
What is the exception being raised?

For ppx_js, it must be because jsoo explicitly installs it in the `lib` section. What inconsistency are you thinking about?

**Comment by XVilka** [comment]
@fdopen is this still an issue for dune 2.0? Also with `js_of_ocaml` updated multiple times since...

**Comment by dra27** [comment]
The original problem has definitely gone away, if only by the passage of time (at least, I just built that part of js_of_ocaml), and I'm not sure that the original issue still stands. If that's wrong, please feel free to re-open or create a fresh issue.
