### ISSUE TITLE
Ctrl+C doesn't work well in watch mode

### ISSUE THREAD

**Issue by diml** [ocaml/dune#1671]
It seems that it is just killing the file watcher...

**Comment by copy** [comment]
This problem still persists on dune 1.6.3 in certain cases, for example with:

```
(executable (name test) (public_name test))
```

```ocaml
module F = Foo
```

Both the missing opam file error and the missing cmi file error are repeated.

**Comment by diml** [comment]
This looks like a different issue, could you open a ticket for it?

**Comment by rauanmayemir** [comment]
I'm having this issue with `1.7.2` on macOS.

I'm running dune with a custom alias that recursively handles creating some target configs, generating xcode project, running xcodebuild, and finally executing target product. Surprisingly, it does it so well that I settled for the watch mode to be used as a live reloading mechanism for time-being and postponed the hot-reloading with dynlinking and whatnot.

However, pressing Ctrl+C would not kill the process, sometimes even after I kill -9 fswatch pid (simple kill wouldn't help). I thought this was an fswatch monitor not being properly shut down, but it's actually an orphan dune process lurking in bg. Though it's not consistent and usually happens after several cycles of kill/rebuild/relaunch.

**Comment by aalekseyev** [comment]
I can't easily reproduce dune process going to background, but for me dune at least reliably does `assert false` when I Ctrl+C it while the build is running, which seems broken enough.

We're working on a fix.

This PR could be also relevant: https://github.com/ocaml/dune/pull/1902 (it's not going to fix anything here, but it might change behavior significantly).

**Comment by aalekseyev** [comment]
@rauanmayemir, if you could try with dune 1.8.0 (which is being released) (or anything past f595dcb), that would be appreciated.

**Comment by rauanmayemir** [comment]
@aalekseyev Can confirm no issues on 1.8.2 so far. 👌
