### ISSUE TITLE
Support -pp in .merlin

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1694]
We'd like to support general preprocessors with merlin using the new `-pp` flag but dune's preprocessing is a bit too general to use this flag. Dune allows for any action to act as a preprocessor but it's not that simple to encode as a `-pp` argument. I see a few workarounds:

* Generate a shell script for a preprocessing action and use it as a `-pp` argument
* Generate and OCaml script for an action and use that as the `-pp` argument
* Create a general binary that will interpret dune actions. This action will be executed as the `-pp` argument with the action serialized appropriately.

Anyone have any other suggestions? Or preferences for any of the options above?

**Comment by diml** [comment]
We could restrict this support to simple preprocessing actions, i.e. only the ones of the form `(run ... %{input-file})`.

**Comment by rgrinberg** [comment]
That's fine for now but I think it will be annoying once we allow for composing preprocessors via pipes. So this would really count only as a short term workaround.
