### ISSUE TITLE
Dune runtime failure Regression building reason master branch.

### ISSUE THREAD

**Issue by jordwalke** [ocaml/dune#1735]
Passes:
`#847bc67b2f02ab51c6ea524b34dbbfa8cc221a32`
Passes:
`#081e1011c5d28b609a0e189c8ea121e6076cd337`
Passes:
`#0fccd3792294a76ed5c89637d449898a988e2bae`
Fails:
`#cd213cd4953e66f5927ed0c4838f56700973c15d`
Fails:
`#528ed3abf592382e294816c1766e189e27a05e0b`
Fails:
`#cfeb84a08be48e93040d047f90d99fa0be25308a`
Fails:
`#723e17baf1d74ac7c47a9dbc69a00c1b9d7d2ecb`

Reason master branch started failing with the following:

```
Error: exception Invalid_argument("Option.value_exn")
Backtrace:
Raised at file "src/build_system.ml", line 1361, characters 9-14
Called from file "src/fiber/fiber.ml", line 91, characters 8-15
```

And then after building it prints a really confusing error message about segfaulting and uncertainty and mindkilling and little-death which I'm not sure is relevant to this observed error.

I'll post more details as I find them but this looks like it's a problem with the Dune implementation so I thought I'd flag it before your next release.

It looks like the commit cd213cd4953e66f5927ed0c4838f56700973c15d caused the regression:
cc @bobot

**Comment by avsm** [comment]
minor edit to original report to link the regressing commit id

**Comment by rgrinberg** [comment]
We should just add a mandatory `message:string` argument to `Option.value_exn`. The error messages are not useful at all otherwise.

**Comment by rgrinberg** [comment]
@jordwalke Could you try running this again with [this patch](https://github.com/ocaml/dune/pull/1739)

**Comment by jordwalke** [comment]
Sure, I'll try with the patch, but on reason master, you just add:

```
  "resolutions": {
    "@opam/dune": "ocaml/dune:dune.opam#cd213cd4"
  },
```

To the `esy.json`, then run `esy` from the root directory.

**Comment by jordwalke** [comment]
Running `esy` after adding this to `esy.json`: to test your patch:

```
"resolutions": { "@opam/dune": "rgrinberg/jbuilder:dune.opam#179dbd78"},
```

**Comment by rgrinberg** [comment]
I tried doing `$ esy` with your `resolutions` and could not reproduce. Perhaps this is a windows issue? I'll try and prepare something that will make this easier to debug.

**Comment by jordwalke** [comment]
This was not on Windows, it was on Mac.

**Comment by andreypopp** [comment]
The offending `Option.value_exn` is at https://github.com/ocaml/dune/blob/c2c9bf17ab5d981dd9aa9e34861d816e073f6645/src/obj_dir.ml#L99 which calls `Path.descendant` which doesn't work with non local paths (in case of esy we set `DUNE_BUILD_DIR` to an absolute path outside of dune workspace).

**Comment by diml** [comment]
Hmm, it should still work for path in the build directory, it seems that it is `Path.descendant` that's wrong. I'm having a look.

**Comment by jordwalke** [comment]
Thanks for the fix @diml and thanks for debugging @andreypopp .
