### ISSUE TITLE
Fix virtual libraries and preprocessing

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1762]
Reproduction case is for reason https://github.com/ocaml/dune/pull/1741 but this is likely an issue with all preprocessing.

**Comment by jordwalke** [comment]
Is this going to be fixed soon? I'd really like to use virtual libraries for a project.

**Comment by rgrinberg** [comment]
Unfortunately, you'll have to wait a while longer. I'm going on vacation next week and dune's codebase isn't yet ready to implement the desired fix. We will certainly fix this for 1.7 however.

For now I fear the workaround is to use OCaml without preprocessing or to setup manual `refmt` rules.

**Comment by jordwalke** [comment]
The manual formatting rules are pretty difficult to use.  I think I'll have to wait to use virtual libraries.

**Comment by rgrinberg** [comment]
Fixed

**Comment by jordwalke** [comment]
Thank you! Virtual Libraries are so great.
