### ISSUE TITLE
:include in library dependencies

### ISSUE THREAD

**Issue by cmr** [ocaml/dune#1776]
In Coda, I need to depend on either `digestif.c` or `digestif.ocaml` based on our build configuration. `libraries` does not use the OSL, so `:include` of a generated file doesn't work. https://github.com/CodaProtocol/coda/commit/75a3ac024783d8bc38cbfc6ce7136662565f1a44 is the sort of thing I would like to be able to do.

**Comment by rgrinberg** [comment]
Indeed it is annoying that one cannot choose an implementation conditionally. Currently, your best bet is to define executable stanzas for both variants (and possibly share code via an intermediate library).

Unfortunately, conditional selection of implementations (or variants) is not all that close for now.

**Comment by cmr** [comment]
Well, if anyone wants a nice hack to get it working, [here it is](https://github.com/CodaProtocol/coda/blob/master/src/lib/coda_digestif/dune).

**Comment by rgrinberg** [comment]
Indeed we should. Although I'm not sure this is enough as the user is asking for user defined variables. But I believe we have a proposal for that as well.

I'm closing this ticket as we have other ones open that will resolve this problem and supporting a general `(:include ..)` in `libraries` will certainly not happen.
