### ISSUE TITLE
Type-checker infers a recursive type, even though -rectypes is off

### ISSUE THREAD

**Issue by fpottier** [ocaml/dune#1782]
I have come across a code snippet where OCaml 4.07.1 infers a recursive type, even though `-rectypes` is off.

The code is as follows:
```
type ('a, 'b) segment =
  | SegNil  : ('a, 'a) segment
  | SegCons : ('a * 'a, 'b) segment -> ('a, 'b) segment

let color (* : type a b . (a, b) segment -> int *) =
  fun s ->
    match s with
    | SegNil ->
        0
    | SegCons SegNil ->
        0
    | SegCons _ ->
        0
```
Here is the inferred type:
```
val color : ('a * 'a as 'a, 'a) segment -> int = <fun>
```

If I uncomment the type annotation, the code is accepted (as it should be).
If I turn on `-principal`, the code is rejected (as it should be).

Still, I find it strange that a recursive type is allowed to appear when `-rectypes` is off.

**Comment by diml** [comment]
Could you grep the filename in `_build/log` to see what flags are passed to the compiler? You can also run the following command to see what Dune considers the default flags are in the directory where the file is:

```
$ dune printenv <directory>
```

**Comment by fpottier** [comment]
Oops, sorry, I intended to create this issue in the OCaml repository!
