### ISSUE TITLE
Dune links stale c stubs

### ISSUE THREAD

**Issue by rauanmayemir** [ocaml/dune#1789]
When you have a library with C stubs and an executable that depends on that library and stubs, any changes in C stubs doesn't get picked up by dune during linking.

I had this issue in `object` mode (`exe.o`).

E.g. this is the example of executable: https://github.com/briskml/brisk/blob/4880ad8d8ae1e255caa43a65ebc21ff7085e522a/examples/components-macos/bin/dune.

And this is the library with c stubs:
https://github.com/briskml/brisk/blob/4880ad8d8ae1e255caa43a65ebc21ff7085e522a/renderer-macos/lib/dune.

Any change in any of the C files doesn't affect the executable. We checked with `ag` that those changes are present in any of `.cmx`, `.a`, but the executable will contain older code.

**Comment by diml** [comment]
What version of dune are you using? I remember that we fixed something similar in the past

**Comment by rauanmayemir** [comment]
It's the very latest: `1.6.3`.

**Comment by diml** [comment]
I'm trying to write a reproduction case but I'm not succeeding. I put my attempt [here](https://github.com/diml/dune/commit/973751e3cefc41d82af6b1950a2f8c4db1aac3fc). Do you mind trying to extend the test to match your case better? The goal is to get `Message 1` printed twice to show that the executable is not relinked.

I also tried building `brisk` at the revision you pointed, however I'm having trouble doing so:

```
$ esy
info esy 0.3.4
info checking https://github.com/ocaml/opam-repository for updates...
info checking https://github.com/esy-ocaml/esy-opam-override for updates...
info resolving esy packages: done                        
info solving esy constraints: done         
info resolving npm packages: done
.... fetching @opam/menhir@opam:20181113error: cannot read the directory
  fetching path:link-dev:./renderer-macos
esy: exiting due to errors above

$ [upgrade esy to latest version]

$ git clean -dfx
$ esy
info esy 0.4.10 (using esy.json)
error: corrupted esy.lock lock
you might want to remove it and install from scratch
error: error: parsing "link-dev:renderer-macos": : not a path
         
  reading lock /usr/local/home/jdimino/brisk/esy.lock
esy: exiting due to errors above
$ git clean -dfx
$ rm -rf esy.lock
$ esy
info esy 0.4.10 (using esy.json)
info checking https://github.com/ocaml/opam-repository for updates...
info checking https://github.com/esy-ocaml/esy-opam-override for updates...
error: link-dev:./renderer-macos doesn't exist           
  reading package metadata from path:link-dev:./renderer-macos
  resolving metadata @brisk/macos@path:link-dev:./renderer-macos
esy: exiting due to errors above
```

**Comment by rauanmayemir** [comment]
I'm gonna try to reproduce it with your test case.
You need to install `esy@next`.

**Comment by rauanmayemir** [comment]
In `examples/components-macos`, run `esy` and then `esy run`.

**Comment by rauanmayemir** [comment]
I couldn't reproduce it in your test case because it's the same workspace, I also couldn't reproduce it in a simple esy workflow where everything is in the same package.

However, here's a fully autonomous repro: https://github.com/rauanmayemir/repro1789. The issue appears to be with external libs, even though they are correctly rebuilding. You could check it with something like:

```
ag --search-binary -i 'message2' _esy/default/store/b/repro1789_lib*
```

**Comment by diml** [comment]
Ah I see. Yes, with external libs that's expected because we don't really know that they have C stubs. I suppose we could assume that any .a in the library directory is associated to the library, but that feels a bit ad-hoc :/

However, in master we are storing a bit more metadata when installing libraries, so we could effectively properly setup dependencies on these files for libraries that where compiled with dune.It might already work actually.

**Comment by andreypopp** [comment]
@diml I did a repro on top of you commit — https://github.com/andreypopp/dune/commit/dbe57cf2b983c66d6009bbfab10d94f85247a530

So what I've found out is that it repros only if we point `OCAMLPATH` to a symlink farm (`_build/install/...`), if I do `dune install --prefix` then it works as expected and picks up the changes. esy also does install via symlink farm for packages in dev and this is why we are seeing this behaviour.

Could the reason be symlinks are treated differently for external libs for some reason?

**Comment by andreypopp** [comment]
even more strange — sometimes it fails and sometimes it passes, not sure what's the reason for this

**Comment by diml** [comment]
@andreypopp are you on OSX? Just asking as the precision of the times in the file stats are to the second on OSX. Dune hashes files to determine when they change, and it uses the file stats to avoid re-hashing everything all the times. As a result, sometimes these tests are sensible to how fast they run on OSX :/

**Comment by rauanmayemir** [comment]
I tried my repro with dune `master` and it's correctly pinning fresh stubs. 😂😂

**Comment by diml** [comment]
@rauanmayemir, great! That must be due to the work we did on `dune-package`.

@andreypopp it depends how you modify the C stubs. If the project is small, and the edits and calls to `dune` are done by a machine, it is possible to be bitten by this problem. If they are done by a human, it is much less likely; you would have to build, edit, save and build again in less than a second.

**Comment by andreypopp** [comment]
@diml yeah, sorry, I haven't read the response from @rauanmayemir that he's not reproducing it with master anymore.

Guess this is a non issue then!

**Comment by rauanmayemir** [comment]
This is great. I'll get back to you once I try `master` on the real project with convoluted stubs.

**Comment by rauanmayemir** [comment]
Can confirm this works on my objc stubs, too. 🎉

**Comment by rgrinberg** [comment]
@rauanmayemir feel free to re-open if you encounter this issue again.
