### ISSUE TITLE
Configurator.V1 discards PKG_CONFIG_PATH on most platform

### ISSUE THREAD

**Issue by vsiles** [ocaml/dune#1790]
If I'm not mistaken, from https://github.com/ocaml/dune/blob/master/src/configurator/v1.ml#L515 the environment variable `PKG_CONFIG_PATH` is discarded on all platform but macos. Shouldn't we set `env` to this value instead of "" ?

**Comment by diml** [comment]
Note that the string that is constructed in the other branch is `"env PKG_CONFIG_PATH=... "`. The `env` variable is then added at the beginning of the shell command that is executed, so on platforms other than osx, `PKG_CONFIG_PATH` should be unchanged.

However, this might be related to #1785

**Comment by vsiles** [comment]
I just tested on a macbook and I have the same behavior, PKG_CONFIG_PATH is ignored. I'll check the other pull-request, thanks !

**Comment by vsiles** [comment]
Here is a small project the shows what is happening to me: https://github.com/vsiles/dune-pkg-config-test. I tested it both on linux and macos, with opam 2 / ocaml 4.06.0 / 4.07.1 and and up to date dune (even with a freshly compiled dune). In all cases PKG_CONFIG_PATH seems ignored

**Comment by vsiles** [comment]
Ok... my bad, it works nicely, I just got confused with pkg itself and my code that happens a "lib" before doing the query... with pc files named correctly, it works ok. I'll just have to contact my admin to rename them correctly on our server :D
