### ISSUE TITLE
dune build traverses entire file system

### ISSUE THREAD

**Issue by hannesm** [ocaml/dune#1791]
I'm using dune 1.6.3 and FreeBSD (13-CURRENT). When I do a `dune build` in a cloned copy of https://github.com/mirage/arp.git it traverses my entire file system. My expectation was that it'd only build the packages specifies in the top level (`arp` in dune-project, or `arp` and `arp-mirage` since there exist opam files). A workaround is to use `dune build --root .`. Is this behaviour intentional? If this is the case, at least for me it is very surprising.

An excerpt from `ktrace` (if you need more detailed traces, please let me know):
```
 35493 dune     CALL  open(0x8009d2120,0x120004<O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC>)
 35493 dune     NAMI  "/usr/home/hannes/devel/mirage/arp"
 35493 dune     RET   open 3
 35493 dune     CALL  fstatfs(0x3,0x7fffffffd6b8)
 35493 dune     RET   fstatfs 0
 .. [various mmap calls] ...
 35493 dune     CALL  getdirentries(0x3,0x801876000,0x1000,0x80050c4c8)
 35493 dune     RET   getdirentries 784/0x310
 35493 dune     CALL  getdirentries(0x3,0x801876000,0x1000,0x80050c4c8)
 35493 dune     RET   getdirentries 0
 35493 dune     CALL  close(0x3)
 35493 dune     RET   close 0
 35493 dune     CALL  open(0x8009f30c0,0x120004<O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC>)
 35493 dune     NAMI  "/usr/home/hannes/devel/mirage"
 35493 dune     RET   open 3
 35493 dune     CALL  fstatfs(0x3,0x7fffffffd6b8)
 35493 dune     RET   fstatfs 0
 35493 dune     CALL  getdirentries(0x3,0x801876000,0x1000,0x80050c4c8)
 35493 dune     RET   getdirentries 4080/0xff0
 35493 dune     CALL  mmap(0,0x7000,0x3<PROT_READ|PROT_WRITE>,0xc001002<MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12)>,0xffffffff,0)
 35493 dune     RET   mmap 34385428480/0x801880000
 35493 dune     CALL  mmap(0,0x7000,0x3<PROT_READ|PROT_WRITE>,0xc001002<MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12)>,0xffffffff,0)
 35493 dune     RET   mmap 34385457152/0x801887000
 35493 dune     CALL  getdirentries(0x3,0x801876000,0x1000,0x80050c4c8)
 35493 dune     RET   getdirentries 4096/0x1000
 35493 dune     CALL  mmap(0,0x7000,0x3<PROT_READ|PROT_WRITE>,0xc001002<MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12)>,0xffffffff,0)
 35493 dune     RET   mmap 34385485824/0x80188e000
 35493 dune     CALL  mmap(0,0x7000,0x3<PROT_READ|PROT_WRITE>,0xc001002<MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12)>,0xffffffff,0)
 35493 dune     RET   mmap 34385514496/0x801895000
 35493 dune     CALL  getdirentries(0x3,0x801876000,0x1000,0x80050c4c8)
 35493 dune     RET   getdirentries 4096/0x1000
 35493 dune     CALL  getdirentries(0x3,0x801876000,0x1000,0x80050c4c8)
 35493 dune     RET   getdirentries 88/0x58
 35493 dune     CALL  getdirentries(0x3,0x801876000,0x1000,0x80050c4c8)
 35493 dune     RET   getdirentries 0
 35493 dune     CALL  close(0x3)
 35493 dune     RET   close 0
 35493 dune     CALL  open(0x8009f3640,0x120004<O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC>)
 35493 dune     NAMI  "/usr/home/hannes/devel"
 35493 dune     RET   open 3
 35493 dune     CALL  fstatfs(0x3,0x7fffffffd6b8)
 35493 dune     RET   fstatfs 0
 35493 dune     CALL  getdirentries(0x3,0x801876000,0x1000,0x80050c4c8)
 35493 dune     RET   getdirentries 3704/0xe78
 35493 dune     CALL  getdirentries(0x3,0x801876000,0x1000,0x80050c4c8)
 35493 dune     RET   getdirentries 0
 35493 dune     CALL  close(0x3)
 35493 dune     RET   close 0
 35493 dune     CALL  open(0x8009f3480,0x120004<O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC>)
 35493 dune     NAMI  "/usr/home/hannes"
 35493 dune     RET   open 3
```

**Comment by diml** [comment]
It is intentional indeed, it allows users to nest projects and workspaces. This is documented [here](https://dune.readthedocs.io/en/latest/usage.html#finding-the-root). Is that an issue in practice? Dune only scans the ancestors directories, so it should be fast.

**Comment by hannesm** [comment]
Thanks for the explanation and pointer to the documentation. The behaviour I saw was confusing since (a) I don't see any "Entering directory ..." output as described in the docs. And (b) I had a `dune-project` file in my home directory which I used for testing a project - which lead to a recursive scan of all files and directories within my home directory. Now that I removed this dune-project file, it works much better. Feel free to close this issue - in my opinion (a) is at least an inconsistency between documentation and implementation.

**Comment by diml** [comment]
I just tried this on my laptop: I created a `~/dune-project` file and run `dune build` in a sub-directory. With 1.6.3, the `Entering directory ...` message is indeed not printed. However, it is printed with master, so the issue must have been fixed since the last release. I remember that we did some work on the startup and scheduler, this issue must have been fixed as a side effect.
