### ISSUE TITLE
allow some files to not be reformatted with @fmt

### ISSUE THREAD

**Issue by hhugo** [ocaml/dune#1793]
I've mentioned that in a comment already (#1252 (comment)).
It would be nice to be able to specify exceptions on a per file basis. It's useful when a file do not parse (e.g file preprocessed with cppo) or when a file is automatically generated (e.g. by ocamllex, yacc, menhir, ...).

**Comment by emillon** [comment]
I agree that it is useful to do that.

`#!` files with a `.ml` extension are also possible candidates for exclusion (at the moment, they can cause problems with `ocamlformat` and it's good to have an alternative to renaming them).

For now, a new parameter to the `(using)` stanza will do the trick, but when this is less experimental, and there's no `(using)` stanza anymore, I'm not sure where this will be configured.

**Comment by hhugo** [comment]
the alternative is to implement this is ocamlformat (a `.ocamlformat-ignore` file ?)

**Comment by diml** [comment]
Is all that's left to do here is declare the dependency on `.ocamlformat-ignore` files? And possibly, as an optimisation, dune could read these files and not call `ocamlformat` at all for such files.

**Comment by hhugo** [comment]
dependency on `.ocamlformat-ignore`, yes. For the rest, i'll let you decide

**Comment by emillon** [comment]
OK, will do that. We might need a more generic way to ignore files, so that it includes reason and dune files, but in the meantime I'll record the dependency.
