### ISSUE TITLE
Unexpected type reported in type error 

### ISSUE THREAD

**Issue by SkySkimmer** [ocaml/dune#1794]
~~~ocaml
module M = struct
  type a
  let f (x:a) = x
end

type b = M.a

let _ = M.f 2
~~~
Got:
>Error: This expression has type int but an expression was expected of type b

Expected:
>Error: This expression has type int but an expression was expected of type M.a

In the original case `b` is an alias with some semantic meaning (even though as an alias it can't produce a strong guarantee) like https://github.com/coq/coq/blob/506136d60c0dcc4fc2a2ca83ef3b586fbede55a2/kernel/names.mli#L118 (and `f` was https://github.com/coq/coq/blob/506136d60c0dcc4fc2a2ca83ef3b586fbede55a2/kernel/names.mli#L56)

This behaviour is because of -short-paths (I guess from #1743 ?). I haven't reviewed the history of that commit but the commit message only talks about `ocamlc -i`, would it be possible to avoid using -short-paths for other commands (and also avoid putting it in .merlin)?

**Comment by diml** [comment]
This seems like an OCaml bug, could you report it [upstream](https://caml.inria.fr/mantis/main_page.php)? `-short-paths` is in general beneficial for developers, so disabling it in Dune doesn't seem right.

**Comment by SkySkimmer** [comment]
https://caml.inria.fr/mantis/view.php?id=7911

**Comment by SkySkimmer** [comment]
Looks like they don't think it's a bug either

**Comment by diml** [comment]
Indeed. Looking at the example again, it doesn't look like a bug to me either. In any case, there is not much we can do in Dune.

**Comment by SkySkimmer** [comment]
Very well then

**Comment by rgrinberg** [comment]
@SkySkimmer Perhaps you could try making it a private type alias:

```
type b = private M.a
```

And then you'll have to do all the coercions explicitly. That shouldn't be so bad, if there's really a semantic meaning to your alias.

In general, you really want `-short-paths` as without it you will be really disappointed by the error messages, especially in the presence of `wrapped` libraries.
