### ISSUE TITLE
deprecate no-keep-locs in favour of virtual libraries

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#1816]
Now that virtual libraries are in master, perhaps we should deprecate `no-keep-locs` to encourage everyone to move to them:

> (no_keep_locs) undocumented, it is a necessary hack until this is implemented:
> https://github.com/ocaml/dune/issues/921

A deprecation warning would help spot legacy uses of cmi hacks (e.g. checkseum)

**Comment by diml** [comment]
Sounds good
