### ISSUE TITLE
runtest blocking

### ISSUE THREAD

**Issue by MathieuDutSik** [ocaml/dune#1818]
I had some experience recently with a test that was failing. It was not failing by reporting an error but instead going into an infinite loop without exiting.
The problem is that "dune runtest" did not report what was happening. I could not know which test was inducing that behavior. The "dune --verbose runtest -j 1" was showing additional info but only for the compiler, not the tests that were currently running forever.
The tests are supposed to be helpful and so it would be great to be able to have plenty of info on demand.

**Comment by rgrinberg** [comment]
The info is available when you pass `--no-buffer` to `$ dune runtest`. Unfortunately, that may cause test output to overlap so it is not on by default.

**Comment by rgrinberg** [comment]
If the above doesn't solve the issue for you, feel free to re-open.
