### ISSUE TITLE
Unbound module for obviously existing module

### ISSUE THREAD

**Issue by alinpopa** [ocaml/dune#182]
Hi,

I'm keep getting the following error when trying to build a silly project (https://github.com/alinpopa/abc), using jbuilder:

```
jbuilder build --only-packages=abc @install
    ocamldep bin/main.depends.ocamldep-output
      ocamlc src/abc__.{cmi,cmo,cmt}
    ocamldep src/abc.depends.ocamldep-output
      ocamlc src/abc__Abc_lib.{cmi,cmo,cmt}
      ocamlc src/abc.{cmi,cmo,cmt}
    ocamlopt src/abc__.{cmx,o}
      ocamlc src/abc.cma
      ocamlc bin/main.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /usr/local/bin/ocamlc.opt -w -40 -warn-error A -g -bin-annot -I /Users/alin/.opam/system/lib/base -I /Users/alin/.opam/system/lib/base/caml -I /Users/alin/.opam/system/lib/base/shadow_stdlib -I /Users/alin/.opam/system/lib/base64 -I /Users/alin/.opam/system/lib/bin_prot -I /Users/alin/.opam/system/lib/bin_prot/shape -I /Users/alin/.opam/system/lib/biniou -I /Users/alin/.opam/system/lib/bytes -I /Users/alin/.opam/system/lib/cohttp -I /Users/alin/.opam/system/lib/conduit -I /Users/alin/.opam/system/lib/core -I /Users/alin/.opam/system/lib/core_kernel -I /Users/alin/.opam/system/lib/core_kernel/base_for_tests -I /Users/alin/.opam/system/lib/easy-format -I /Users/alin/.opam/system/lib/fieldslib -I /Users/alin/.opam/system/lib/fmt -I /Users/alin/.opam/system/lib/ipaddr -I /Users/alin/.opam/system/lib/ipaddr/unix -I /Users/alin/.opam/system/lib/jane-street-headers -I /Users/alin/.opam/system/lib/logs -I /Users/alin/.opam/system/lib/lwt -I /Users/alin/.opam/system/lib/magic-mime -I /Users/alin/.opam/system/lib/num -I /Users/alin/.opam/system/lib/ppx_assert/runtime-lib -I /Users/alin/.opam/system/lib/ppx_bench/runtime-lib -I /Users/alin/.opam/system/lib/ppx_compare/runtime-lib -I /Users/alin/.opam/system/lib/ppx_expect/collector -I /Users/alin/.opam/system/lib/ppx_expect/common -I /Users/alin/.opam/system/lib/ppx_expect/config -I /Users/alin/.opam/system/lib/ppx_hash/runtime-lib -I /Users/alin/.opam/system/lib/ppx_inline_test/config -I /Users/alin/.opam/system/lib/ppx_inline_test/runtime-lib -I /Users/alin/.opam/system/lib/re -I /Users/alin/.opam/system/lib/result -I /Users/alin/.opam/system/lib/sexplib -I /Users/alin/.opam/system/lib/sexplib/0 -I /Users/alin/.opam/system/lib/sexplib/unix -I /Users/alin/.opam/system/lib/spawn -I /Users/alin/.opam/system/lib/stdio -I /Users/alin/.opam/system/lib/stringext -I /Users/alin/.opam/system/lib/typerep -I /Users/alin/.opam/system/lib/uchar -I /Users/alin/.opam/system/lib/uri -I /Users/alin/.opam/system/lib/uri/services -I /Users/alin/.opam/system/lib/variantslib -I /Users/alin/.opam/system/lib/yojson -I /usr/local/lib/ocaml -I /usr/local/lib/ocaml/threads -I src -no-alias-deps -I bin -o bin/main.cmo -c -impl bin/main.ml)
File "bin/main.ml", line 3, characters 5-12:
Error: Unbound module Abc_lib
make: *** [build] Error 1
```

I have two modules that are part of the `src/` folder, and I'm accessing them from the `bin/main.ml` module; when accessing the `Abc` module, all seems fine, but it complains for the `Abc_lib`; I can't really understand what's going on; the thing is that I have a similar project where a similar scenario works fine;
a bit strange is also the fact that I'm able to see this line `ocamlc src/abc__Abc_lib.{cmi,cmo,cmt}`, and also, looks like the module is accessible by this name `Abc__Abc_lib`, but I'm pretty sure that's not the "normal" way to do that.
Might be something that I'm terribly missing here? A typo, or something?

Thanks.

**Comment by rgrinberg** [comment]
If you add `(unwrapped false)` to your library stanza then things should work as you  expect.  By default, jbuilder will prefix all of your modules with the `name` prefix you provided in your library stanza. So in fact, in your current project, you would access the module  as `Abc.Abc_lib`.

Another option for you is to simply rename your Abc_lib module to Lib and pick another name for abc.ml

**Comment by dra27** [comment]
Minor typo - @rgrinberg meant `(wrapped false)` but I think there is a bug, or at least a missing warning here. You can't refer to Abc_lib (or anything else in the library) at all because src/abc.ml is masking the pack name - abc.cmi is the interface for src/abc.ml where it should be

```ocaml
module Abc_lib = Abc__Abc_lib
module Abc = Abc__Abc
```

I'm not sure whether it should be an error to define a module with the same name as the library, or whether jbuilder is not mangling something correctly.

**Comment by rgrinberg** [comment]
@dra27 thanks for the correction. Actually, the ability to write your own alias file is a very useful feature. It lets you only include the modules you want to be "public" for example. Here's an example in base:  https://github.com/janestreet/base/blob/master/src/base.ml

**Comment by dra27** [comment]
Good point! Perhaps it would be better if it were explicit that one was doing that in the jbuild file, though?

**Comment by rgrinberg** [comment]
I don't have any strong feelings on changing the jbuild file, but perhaps we should add a warning in cases where the user is prefixing their module names with the library name (as in this ticket).

**Comment by alinpopa** [comment]
Thanks guys; I honestly don't think there's any problem with this thing, but I've only missed the fact that having a module with the same name as the package, will hide the access to all other modules; I knew about `(wrapped false)`, but I didn't see, till now, where it would be useful.
I haven't read the entire manual very careful, but maybe worth having this thing (i.e. if having a module with the same name as the package, will have this affect of public/private visibility) specified as part of the manual, if not already?
Anyway, please feel free to close this issue.

**Comment by rgrinberg** [comment]
I'll close this as I can't really think of a way to improve the error message in this case. Detecting an unbound module error and being smart suggesting alternatives sounds nice, but deciphering compiler output isn't very appetizing.
