### ISSUE TITLE
Ctrl+C still doesn't properly kill the file watcher

### ISSUE THREAD

**Issue by copy** [ocaml/dune#1827]
As a follow-up to #1671: This problem still persists on dune 1.6.3 in certain cases, for example with:

```
(executable (name test) (public_name test))
```

```ocaml
module F = Foo
```

Both the missing opam file error and the missing cmi file error are not properly killed by Ctrl+C.

**Comment by diml** [comment]
What version of dune are you using? I can't reproduce this error with master

**Comment by copy** [comment]
I was using 1.6.3. It's indeed working on master already. Looks like the fix didn't make it into 1.6.3. Sorry about the noise!
