### ISSUE TITLE
watch mode: "build system already initialized"

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#1836]
Hi,

`dune runtest -w` seems broken under 1.7.0.
The first run works, but once a file is modified, the following is displayed:

```
Description:
("build system already initialized")
Backtrace:
Raised at file "src/stdune/exn.ml", line 38, characters 5-10
Called from file "src/main.ml", line 99, characters 2-74
Called from file "src/fiber/fiber.ml", line 95, characters 6-13
Had errors.
```

**Comment by rgrinberg** [comment]
Hmm, that check does look suspicious. If we're running the build system in polling mode, we expect to initialize it more than once I think.
