### ISSUE TITLE
Add pkg-config tests to configurator

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1838]
They've been the cause of serious regressions such as #1833 in the past.

**Comment by Chris00** [comment]
To be clear: you are fine to depend on `conf-pkg-config` for tests, right?

**Comment by rgrinberg** [comment]
Yeah, I think we have plenty of tests that require external dependencies. But for the quoting issue, I'm thinking that it would be enough to have a mock `pkg-config` that would simply prints its arguments and give a fake return code. It should be enough to make sure we are running it as we expect.

**Comment by rgrinberg** [comment]
@Chris00 I'm taking care of this

**Comment by rgrinberg** [comment]
There's a PR for this.
