### ISSUE TITLE
Deprecation warnings shouldn't be fatal by default

### ISSUE THREAD

**Issue by NathanReb** [ocaml/dune#1843]
I recently deprecated a type in `yojson` and although I should've done things a bit differently it came with a lot of unwanted breakage, see https://github.com/ocaml-community/yojson/issues/79 and https://github.com/ocaml-ppx/ppx_deriving_yojson/pull/91.

Not all of these issues are directly related to dune but it made me think about how dune handle those warnings by default and it seems odd.

Making deprecation warnings fatal breaks the whole logic behind deprecation cycles. We deprecate values and types in a library to help users gently migrate their code before breaking compatibility in a later major release. If the warning is fatal, it makes deprecation a breaking change on its own.

As a maintainer I don't feel like asking users to change their build profiles everywhere and thus I end up running around fixing stuff like I just broke compatibility in a minor release which I didn't.

As I already mentioned it in https://github.com/ocaml-community/yojson/issues/79, I'm not sure what the best way to handle those is. Completely silencing it is too much but we probably don't want too much noise on the build output either.

I'm really curious about what the dune team thinks about this so please let me know!

**Comment by rgrinberg** [comment]
Note that they're only fatal in the dev profile. But I'm also in favor of changing the default to be non-fatal. At this point, quite a few users voiced their support for this and I think that we should pick defaults that accommodate as many users as possible.

**Comment by NathanReb** [comment]
> Note that they're only fatal in the dev profile

Indeed and I was actually counting on that when deprecating that type for it not to break "production" builds but it turns out it was still bothering most people.

I like the `dev` profile because it's very strict and doesn't let you get around with most warnings which results in very clean code but maybe be it shouldn't be the `dev` profile as when developing I guess most people don't want to be bothered by warnings. This strict profile feels more like a CI or quality profile than a dev one but that's a bit out of scope of this issue as I think what matters most here is the default.

**Comment by rgrinberg** [comment]
In any case, if other maintainers are on board I'm for this change. Let's see what @emillon or @diml have to say.

**Comment by emillon** [comment]
I agree that warning 3 shouldn't be fatal, especially since this is something that you can't fix as a developer - you'd need to fix your dependencies sometimes.

**Comment by rgrinberg** [comment]
> especially since this is something that you can't fix as a developer - you'd need to fix your dependencies sometimes.

In what situations does this affect you? When you install dependencies via opam, those are built in the `release` profile in which such warnings are non fatal.

**Comment by NathanReb** [comment]
This can be an issue if you use a `ppx` or a code generator which produce code that uses the deprecated values.

**Comment by emillon** [comment]
Yes, that was the situation I was thinking of as well.

**Comment by rgrinberg** [comment]
Looks like this is unlikely to change
