### ISSUE TITLE
Watermarking with multiple opam packages

### ISSUE THREAD

**Issue by hannesm** [ocaml/dune#1844]
First of all, thanks for your amazing work on dune!

In some repositories, such as https://github.com/mirage/mirage, we have multiple opam packages that are released at the same time. It looks like only the opam package mentioned in `dune-project` gets watermarks (esp. version number) in their `META` file:
```
$ mirage --version
v3.4.1
$ ocamlfind query -format %v mirage
3.4.1
$ ocamlfind query -format %v mirage-runtime
[unspecified]
$ ocamlfind query -format %v mirage-types
[unspecified]
$ ocamlfind query -format %v mirage-types-lwt
[unspecified]
```
(see as well the generated documentation which only carries version information for the `mirage` package at https://mirage.github.io/mirage/)

It is not clear to me whether this is actually an issue with dune, or whether the setup in the mirage repository needs to be adjusted. Any hints would be highly appreciated.

**Comment by diml** [comment]
No problem, glad you find it useful!

Are you using `dune-release` to do the release? If yes, then it is `dune-release` that handles the watermarking for the release tarballs. The missing version number for the `mirage-*` packages looks indeed wrong. Dune tries to read the version number from the opam file, and looking at the tarball for 3.4.1, it looks like the version number is only inserted in the `mirage.opam` file but not the `mirage-xxx.opam` ones. /cc @samoht

**Comment by hannesm** [comment]
yes, this was released using dune-release -- so we can close this issue, and open a new one at the dune-release repository which needs to be enhanced to embed the version into all opam files!?

**Comment by diml** [comment]
Yep, that seems right to me.
