### ISSUE TITLE
dune utop does not pass c++ libraries to the linker

### ISSUE THREAD

**Issue by anton-trunov** [ocaml/dune#1849]
I can build the project with `dune build` on my machine just fine, but when I try to start the toplevel with `dune utop <lib> --verbose` I get a linker error:
```
Command [2] exited with code 2:
$ (cd _build/default && /Users/anton/.opam/coq.dev/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w -24 -g -o src/lang/base/.utop/utop.exe -custom -linkall -warn-error -31 -I /Users/anton/.opam/coq.dev/lib/base
...

Undefined symbols for architecture x86_64:
  "_BN_CTX_free", referenced from:
      PubKey::comparePreChecks(PubKey const&, std::__1::shared_ptr<bignum_st>&, std::__1::shared_ptr<bignum_st>&) const in libscilla_cpp_deps_stubs.a(PubKey.o)
      Schnorr::Sign(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, unsigned int, unsigned int, PrivKey const&, PubKey const&, Signature&) in libscilla_cpp_deps_stubs.a(Schnorr.o)
      Schnorr::Verify(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, unsigned int, unsigned int, Signature const&, PubKey const&) in libscilla_cpp_deps_stubs.a(Schnorr.o)

...

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "_none_", line 1:
Error: Error while building custom runtime system
```

 If I manually add to the failing command something like

```
-cclib -lstdc++ -cclib -lcrypto
```

the error goes away.

**Comment by anton-trunov** [comment]
A workaround for this would be very much appreciated!

**Comment by rgrinberg** [comment]
Just to confirm, are those flags being passed when you're building any other binary with the C++ library in question as a dependency?

**Comment by anton-trunov** [comment]
Yes, for example when I do `dune build --verbose`, I get
```
...
Running[266]: (cd _build/default && /Users/anton/.opam/coq.dev/bin/ocamlopt.opt -cclib -lstdc++ -cclib -lcrypto -g -o tests/testsuite.exe -I /Users/anton/.opam/coq.dev/lib/base
...
```

**Comment by rgrinberg** [comment]
Do you have a project that I can reproduce? I would like to create a test case for this.

**Comment by anton-trunov** [comment]
While trying to build a minimized example I found that the issue was on our side.
We had `(flags (-cclib -lstdc++ -cclib -lcrypto))` for the executables, but the library's `dune` file didn't know anything about that. I'm sorry about the confusion.

When I add
```
(c_library_flags -lstdc++ -lcrypto) 
```

the project compiles and `dune utop <lib>` works, but I get new warnings from `ranlib`:
```
$ dune build --profile release
...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: src/cpp/libscilla_cpp_deps_stubs.a(generate_dsa_nonce.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: src/cpp/libscilla_cpp_deps_stubs.a(generate_dsa_nonce.o) has no symbols
...
```

Is this the right way to tell the linker to use C++'s standard library? Thanks in advance!

**Comment by diml** [comment]
Yep, that looks like the right way. I'm not too sure what the compilation error is about though :/ That seems like an OSX specific error. /cc @rgrinberg and @avsm in case they have seen this error before.

**Comment by rgrinberg** [comment]
The object file doesn't define any symbols I guess. I have no idea why it needs to be linked. @anton-trunov there doesn't seem to be an issue here. Let us know if something doesn't work.
