### ISSUE TITLE
Add first class glob handling to Build_system

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#1851]
Extracted from the discussion at: https://github.com/ocaml/dune/pull/1622

The advantages are twofold:

* We will no longer need to manually maintain the glob rules.
* We'll be able to output nicer looking rules.

**Comment by rgrinberg** [comment]
Jotting down some notes on how such support could be added (in case anyone is interested in giving it a try):

* Cases where we loop over the files (`Deps.paths` and `Deps.parallel_iter`) will need to be adjusted to call `targets_of` to get the full list of dependencies

* `Deps.trace` needs to be changed as it should now evaluate the glob (@diml might confirm or deny this)

* The various `rules_for` functions need to be changed to account for globs.

**Comment by diml** [comment]
Regarding the trace, it all depends whether we want to allow to depend on the evaluation of the glob only. For instance, `echo *.txt > file` depends on the evaluation of `*.txt` but doesn't actually depend on the `.txt` files. We can't express that in dune currently.

**Comment by rgrinberg** [comment]
Globs are now first class
