### ISSUE TITLE
Allow (c_names ...) in (executable ...)

### ISSUE THREAD

**Issue by Niols** [ocaml/dune#1858]
Hello,

By discussing with @diml in #1832 (thanks again), I discovered the `(modes object)` stanza in order to build a C library from OCaml code super easily. However, in my case, we wrote a little piece of C wrapper around that library in order to have more C-like access points.

I think it would be nice to be able to declare this wrapper as C stubs in the `(executable ...)` stanza, that is to have `(c_names ...)` allowed in there (and probably `(cxx_names ...)` as well). Do you think it's reasonable?

**Comment by rgrinberg** [comment]
Would this proposal work for you as well: https://github.com/ocaml/dune/pull/1786

You will be able to define an executable using pure C. Note that we'll still probably add support to `{c,cxx}_names` to the executable stanza.

**Comment by Niols** [comment]
In my case, it's indeed a pure C piece of code that depends on my OCaml library, but the goal is to build an object file and not an executable. However, as I guess it's very similar, could that be a feature in this PR?
