### ISSUE TITLE
"hello_world" failed "with 4.06.1+lto" switch when dune build @install

### ISSUE THREAD

**Issue by ehirdoy** [ocaml/dune#1865]
$ ~/src/dune/example/sample-projects/hello_world$ dune --version
1.7.2
$ ~/src/dune/example/sample-projects/hello_world$ dune build @install
    ocamlopt lib/hello_world.{a,cmxa} (exit 2)
(cd _build/default && /home/ehirdoy/.opam/4.06.1+lto/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -a -o lib/hello_world.cmxa lib/.hello_world.objs/native/hello_world.cmx)
File "_none_", line 1:
Error (warning 63): The required module Hello_world was built without -lto. Linking it in -lto mode will probably not be possible.

**Comment by dra27** [comment]
You should be able get it to work either by suppressing warning 63 or adding `(flags -lto)`. However, it’s not really Dune’s job to work out of the box with unofficial patches to OCaml!

**Comment by ehirdoy** [comment]
Right.
Strange thing is that "opam (re)install" works with the same code....
I'm wondering why only "dune build @install" fail?
I thought both call the same backend build options.....

--8<-----8<-----8<-----8<-----8<-----8<---
ehirdoy@ehirdoy-vm:~/src/dune/example/sample-projects/hello_world$ opam reinstall .

<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
[hello_world.1.0] synchronised from file:///home/ehirdoy/src/dune/example/sample-projects/hello_world

The following actions will be performed:
  ↻ recompile hello_world 1.0*

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⊘ removed   hello_world.1.0
∗ installed hello_world.1.0
Done.

**Comment by ehirdoy** [comment]
dune adds "-opaque" flag by default. This seems conflicts "-lto" in 4.06.1+lot switch.

**Comment by rgrinberg** [comment]
Yeah, that's indeed a problem. Doesn't flambda always need .cmx files? In which case, the `--dev` profile wouldn't work. Let's see if @lpw45 can confirm.
