### ISSUE TITLE
dune missing library, opam says its there

### ISSUE THREAD

**Issue by vcapra1** [ocaml/dune#1873]
I have a dependency called 'sets', which has been build in a local directory 'dep/sets'.

`opam list` gives the following:

`sets                1.0.0       pinned to version 1.0.0 at file:///...`

But `dune utop` gives

`Error: Library "sets" not found.`

I've seen https://github.com/ocaml/dune/issues/272 but that's pretty old and uses jbuild, which is now deprecated.

**Comment by rgrinberg** [comment]
`$ dune utop` will only load the libraries in your current workspace. If you aren't depending on `sets` anywhere then `$ dune utop` will not load it.

**Comment by rgrinberg** [comment]
Do you have a project somewhere that we can reproduce?

**Comment by vcapra1** [comment]
Here's a minimal example that produces the error: https://github.com/vcapra1/opam_lib_test

Note the command that causes the error is actually `dune utop src`, because that's where the source code is.

**Comment by jnfoster** [comment]
I am seeing similar behavior.

I have installed a package locally and `ocamlfind` knows about it...
```
% ocamlfind query petr4
/Users/nate/.opam/4.07.0/lib/petr4
```

Yet when I try to build a package that depends on it, `dune build` fails:
```
dune build
File "XXX", line 4, characters 23-28:
4 |  (libraries ... petr4 ...)
                    ^^^^^
Error: Library "petr4" not found.
```

**Comment by jnfoster** [comment]
Digging a little deeper, `dune`'s [documentation](https://github.com/ocaml/dune/blob/master/doc/usage.rst#finding-external-libraries) says it finds external libraries starting with the path returned by `ocamlfind printconf path`, which doesn't seem to be what I'm seeing here.

**Comment by rgrinberg** [comment]
@jnfoster what does `$ dune installed-libraries` say in your case? In particular, how does this list differ from `$ ocamlfind list`?

**Comment by jnfoster** [comment]
Running these commands,
```
% dune installed-libraries | cut -f1 -d " " > dune-libs
% ocamlfind list | cut -f1 -d " " > ocamlfind-libs
% diff dune-libs ocamlfind-libs
```
yields:
```
96a97
> dune
165a167
> merlin
205a208
> odoc
216a220
> opam-publish
232a237
> petr4
305a311
> ppxfind
```

**Comment by diml** [comment]
At least for `dune` and `ppxfind`, these libraries definitely don't exist. I'm pretty sure it is the same for `merlin`, `odoc`, `opam-publish`. I don't know about `petr4`.

If you look in the repository of dune for instance, there is no library with `(public_name dune)`. With ocamlfind, all the intermediate names must exist. So because `dune.configurator` exist, then `dune` must exist as well. We could extend dune to add empty intermediate libraries, though it feels a bit off to allow depending on libraries that don't exist.

**Comment by jnfoster** [comment]
Thanks. I now see that my `public_name` declarations were wrong.

**Comment by rgrinberg** [comment]
I believe this is now resolved. @jnfoster Don't hesitate to ask more questions or open more issues.

**Comment by jnfoster** [comment]
Whoops. Indeed it is fixed. Sorry for forgetting to close it!

The issue is that I was confused about how names work.

**Comment by jakubrpawlowski** [comment]
@jnfoster 
> Thanks. I now see that my public_name declarations were wrong.

I'm running into similar issue. Do you remember what was wrong with the public_name?

**Comment by jakubrpawlowski** [comment]
Turns out the problem for us was that the package was pinning itself through Makefile. Removing pin made it usable by other libraries.
