### ISSUE TITLE
[RFC] Static meta-programming

### ISSUE THREAD

**Issue by diml** [ocaml/dune#1879]
This ticket describe a proposal for static meta-programming with dune, i.e. where the user wants to generate part of theirs source files and commit the generated parts in the repository.

Overview
--------

This proposal is an evolution from the [cinaps](https://github.com/janestreet/cinaps) project. The motivation for this project are described [in this blog post](https://blog.janestreet.com/trivial-meta-programming-with-cinaps/).

In particular, it is more integrated and allows to use libraries in cinaps code snippets, which is a common request from cinaps users. This proposal improves and simplifies the way cinaps operates. The result is so simple that I propose to integrate it directly in dune rather than rely on an external tool.

Spec
----

When a user writes `(static_metaprog)` in their `dune` file, dune will enable static metaprogramming for the current directory. More precisely, it will interpet special comments in various source files as small pieces of OCaml code that output the text following them.

More precisely, OCaml source files might contains the following special forms:

```ocaml
(*$ <ocaml-code> *)
<text printed by ocaml-code>
(*$*)
<text under the control of the user>
```

When calling `dune build @lint`, dune will ensure that the generated text blocks are up-to-date, i.e. that they correspond to the text printed when executing the OCaml code. To avoid complexity, the format is completely textual, i.e. dune will not try to parse the files and will simply textually look for `(*$`. This allows to easily support a wide range of formats without hassle. This is how cinaps works and users have been happy with it so far.

Supported files includes:

- OCaml files, using the `(*$ ... *)` syntax
- Reason and C files, using the `/*$ ... */` syntax
- dune files, using the `;;$ ...` syntax

### Using libraries in code generator comments

It is often the case that we want to share code between the code generator comments. For this purpose, a user may specify a list of libraries and a preprocessor in the `(static_metaprog)` stanza:

```scheme
(static_metaprog
 (libraries codegen)
 (preprocess (pps blah)))
```

These will be in effect inside the special code generator comments

Implementation
--------------

Dune will generate a .ml files from the various source files in the direcoty containing code producing the updated files. More precisely, the generated .ml file will look like this:

```ocaml
Dune_static_metaprog.process_file
  ~file_name:"foo.ml"
  ~file_contents:{|<contents of foo.ml>|}
  (fun () -> let module M = struct
Dune_static_metaprog.copy_input <start-offset> <end-offset>;;
<first embed code generator snippet>
Dune_static_metaprog.copy_input <start-offset> <end-offset>;;
<second embed code generator snippet>
...
);;
Dune_static_metaprog.process_file
  ~file_name:...
```

The `Dune_static_metaprog.process_file` function will redirect `stdout` to a temporary file to capture the text printed by the embed code generator snippets. After processing a file, if the new file contents doesn't match the original one, a `<file>.static-metaprog.corrected` file will be generated with the new contents. This file will be diffed and promoted using the usual rules.

Dune will then compile and execute this file as part of the `lint` alias.

**Comment by ygrek** [comment]
(blog post link doesn't point to blogpost)

**Comment by diml** [comment]
Ooops, indeed. Thanks for letting me know. I updated  the link

**Comment by diml** [comment]
Replaced by #2269. I initially wanted to have the runtime lib be part of dune, but given that we are headed in the direction of distributing the libraries separately it seems better to stick to the original cinaps project.
