### ISSUE TITLE
Regression from 1.6 to 1.7 for libraries with archives in subdirectories

### ISSUE THREAD

**Issue by jberdine** [ocaml/dune#1885]
I'm seeing build failures with 1.7.* that work well with 1.6.3, in particular due to bec9fbb95c79dd04d3027be6ccfc9c66fba58d9c from https://github.com/ocaml/dune/pull/1329.

I don't have a self-contained repro yet, but figured I'd open an issue in case there are any quick comments. The symptom is warnings (that a later commit makes into errors) such as:
```
File unavailable: /Users/jjb/.opam/sledge/lib/llvm/llvm_analysis.cmxa
```
This come from building a library with `(libraries llvm.analysis ...)` in its `dune`. Note that the `llvm_analysis.cmxa` file is actually present as `/Users/jjb/.opam/sledge/lib/llvm/static/llvm_analysis.cmxa`. Note the added `static` directory. This comes from the `META.llvm` file, which declares packages with archives in the `static` subdirectory:
```
name = "llvm"
version = "7.0.0svn"
description = "LLVM OCaml bindings"
archive(byte) = "static/llvm.cma"
archive(native) = "static/llvm.cmxa"
directory = "llvm"

package "analysis" (
    requires = "llvm"
    version = "7.0.0svn"
    description = "Intermediate representation analysis for LLVM"
    archive(byte) = "static/llvm_analysis.cma"
    archive(native) = "static/llvm_analysis.cmxa"
)
```
I don't know if `META` files are not supposed to do that, but it worked with dune 1.6.

FWIW, looking at the patch, the use of `basename` [here](https://github.com/ocaml/dune/commit/bec9fbb95c79dd04d3027be6ccfc9c66fba58d9c#diff-8828fb37258a6e3cca668a8169428ea0R75) looked suspicious to me.

**Comment by diml** [comment]
That's definitely a bug in Dune. The `basename` you pointed is indeed the culprit: the same `make` function is used to construct` `Lib.t` values for both internal and external libraries and it is wrong in the case of external libraries. Thanks for debugging this.
