### ISSUE TITLE
How to create a statically linked library ?

### ISSUE THREAD

**Issue by vsiles** [ocaml/dune#1904]
Hi !
I need to create a ml executable statically linked to the Pcre library. Some stubs exists for dynamic linking https://github.com/mmottl/pcre-ocaml. I'm have no clue how I can go from all this and the libpcre.a I want to link to a statically linked binary.

Is it possible ? Can anyone help ?

Best regards,
Vincent

**Comment by diml** [comment]
If you want to statically link a C library, then it is the C linker you have to convince of doing so. You can try adding `(link_flags :standard -cclib -static)` to your `executable` stanza.

**Comment by vsiles** [comment]
@diml  During my attempts, I tried something similar, but then all the libraries (even `-lz` or `-lm` which are automatically added) where considered static. Is it possible to specify only a single library as static instead of all of them ?

**Comment by diml** [comment]
TBH, I'm not sure. Have you looked in the ld manual?

**Comment by vsiles** [comment]
Looks like it's possible with ld using something like  `-Bstatic -lmystaticlib -Bdynamic ..rest of libs...`

**Comment by diml** [comment]
I see. In dune, we don't know the full set of C libraries that will be linked in. Well, we could find it out but it is a non-negligible amount of work. It would be a lot easier to implement this feature at the compiler level.

**Comment by Alizter** [comment]
I don't think we have any plans to know the set of C libraries that will be linked in. I agree that it might be something for a compiler to worry about.
