### ISSUE TITLE
investigate impact of not passing compilation flags to the linking step

### ISSUE THREAD

**Issue by ghost** [ocaml/dune#1916]
this is a ticket to investigate 'the impact of not passing compilation flags to the linking step (which might be acceptable)'

some context:
based on the doc. some stanzas get to have user defined flags to be added either at compilation or linking time, and to ocamlc or ocamlopt via following fields:

> for stanzas library, executable(s) & env:
"specify OCaml _compilation_ flags"
-flags,
-ocamlc_flags
-ocamlopt_flags

> for library only:
-(library_flags (<flags>))
"is a list of flags that are passed as it to ocamlc and ocamlopt when building the library _archive_ files"

>executable
-(link_flags <flags>)
"specifies additional flags to pass to the _linker_"

dune adds latter two only at linking time (as per the doc. says) & first one at linking & compilation time.
being the first one to be investigated since is passed too at linking, therefore, currently having no field to pass flags only for compilation, which is not an issue & very acceptable to me

**Comment by rgrinberg** [comment]
Are there plans to update this ticket? Otherwise I'm not sure we have anything to respond here.

**Comment by Alizter** [comment]
@rgrinberg I guess there is nothing else we can do for this.
