### ISSUE TITLE
"dune runtest" is one-size-fits-all

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#1936]
Hi,

At the moment, `@runtest` is used for two slightly different use cases:

- it is used to centralize all checks when building a package. In particular, it is the recommended way to setup CI.
- it is also used locally when developing, either manually invoking `dune runtest` from an editor, or in a separate terminal in watch mode. This is at the center of the "feedback loop" used when doing TDD for example.

I believe that these two use cases are subtly different: the first one checks invariants that should be true for each commit, while the second one needs invariants that should always be true.

This is not an issue for most projects; however here are a few cases where these differ:

### Benchmarks

Some checks are not meaningful to be done in CI. For example, a library can provide a benchmark executable that takes several minutes to run. If this is aliased to `@runtest`, the CI will get very slow. If it is not aliased, the executable can diverge from the library and not build anymore. In that case, a good tradeoff would be to build the benchmark executable in CI, but not run it.

### Acceptance tests

Conversely, some checks are to expensive to be run in the main feedback loop. For example, there can be both fast unit tests (that break and change often) and slow acceptance tests (that break and change rarely). In that case, it could make sense to run the slow tests only in CI.

### Autoformatting

`@fmt` checks that the project is correctly formatted. That is great to enforce at the commit level, but can get in the way when developing: sometimes, it's helpful to quickly run a test without reformatting everything. This is particularly useful in environments when there is no editor support for autoformatting.

### Lint rules

Some code bases have style rules that can be enforced by external tools. For example, it might be against policy to use `when` in pattern matching, and this can be enforced by a ppx. It is useful to enforce this in CI, but this can get in the way when doing quick prototyping.
To some extent, some compiler warnings fit in this case as well: unused variables, or deprecation warnings (#1843) could be checked only in CI; but at the moment it is the compiler's duty to check this. In a parallel (or future) world where this is checked by an external tool, we could make these checks less frequently.

There are some partial solutions to this problem:
- some projects add `dune build @fmt -p name {with-test}` directly in the `opam` file.
- it is possible to define a directory structure that separate slow checks from fast checks, so that something like `dune runtest -w tests/unit` works for giving fast feedback
- the `@check` alias (#1221, #1447) was designed to some extent for this case

I am not sure how to solve this problem. I suppose that a convention similar to `@check` for things that should be built when quickly iterating would be useful, but that's only part of the story (for example, it does not solve the benchmark use case).

Thanks!

**Comment by diml** [comment]
I suggest the following: defining more fine grained aliases, refining the directory structure and adding new build profiles. It is very easy to do with Dune via the various configuration files. Then we experiment with them for a while and see what works best. Once we find the right settings, we can integrate them more pervasively in Dune. Feel free to do that for Dune itself.

**Comment by emillon** [comment]
Thanks. I think that there are some conventions that are emerging in mirage, such as defining `@bench` and `@fuzz`, we can see if there's a pattern in a few releases :slightly_smiling_face:

**Comment by aij** [comment]
I'm curios: Why do you list format checking as separate from lint rules? Would it not make sense to treat it as just another lint rule?

**Comment by emillon** [comment]
It's indeed similar, but in the current implementation formatting can be fixed automatically, and failing is detected when the fixed version is different from the one in the source tree. Linting is a bit more general, as sometimes there's no "fix" command for some rules. We can definitely put these under the same category though.

**Comment by rgrinberg** [comment]
Note that dune is simply taking inspiration from existing tools here as well. `fmt` is a standard action in other languages. AFAIK that doesn't include other kinds of linting. Tbh, most linting should be done as part of the build process if it's so important. My main motivation for adding the lint alias was to have full support for developing base using dune.

**Comment by Alizter** [comment]
What is the conclusion here? Any actions we can take / discuss?

**Comment by emillon** [comment]
As written, this issue is not actionable, so I think it should be closed.
