### ISSUE TITLE
Dune using gcc instead of g++

### ISSUE THREAD

**Issue by WhoAteDaCake** [ocaml/dune#1945]
I'm expirementing with some bindings to C++ and noticed, that I would get errors when compiling, when I looked into build logs it has shown that dune was running `/usr/bin/gcc` instead of `/usr/bin/g++`.

My code can be found [here](https://github.com/WhoAteDaCake/ocaml-ai-experiments/tree/setup).
Is there a way to fix this, or am I doing something wrong?

[log.txt](https://github.com/ocaml/dune/files/2963984/log.txt)

My dune file:
```
(library
 (public_name hello_world)
 (cxx_names hello_stubs)
 (cxx_flags (--std=c++14 -fPIC -I/usr/local/include/opencv4 -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_contrib -lopencv_legacy -lopencv_stitching)))
```
dune version **1.8.2**

**Comment by WhoAteDaCake** [comment]
I guess a temporary fix is to add `-x c++` flag

**Comment by kit-ty-kate** [comment]
I got the same issue. Here is a smaller test case:
`dune`:
```
(library
  (name test)
  (wrapped false)
  (cxx_names test)
  (modules ))

(executable
  (name test)
  (modules test)
  (libraries test))
```
`test.cpp`:
```cpp
extern "C" {
int* f() {
  int* x = new int;
  return x;
}
}
```
`test.ml`:
```ocaml
external f : unit -> int = "f"
```
When trying to compile this project, we get an error and the log file is the following:
```
# dune build test.exe
# OCAMLPARAM: unset
$ /usr/bin/nproc > /tmp/dune5c15c6.output 2> /dev/null
$ /home/kit_ty_kate/.opam/4.07.1/bin/ocamlc.opt -config > /tmp/dune73a113.output
$ (cd _build/default && /usr/bin/gcc -I /home/kit_ty_kate/.opam/4.07.1/lib/ocaml -O2 -fno-strict-aliasing -fwrapv -fPIC -g -o test.o -c test.cpp)
$ (cd _build/default && /home/kit_ty_kate/.opam/4.07.1/bin/ocamlmklib.opt -g -o test_stubs test.o)
$ (cd _build/default && /home/kit_ty_kate/.opam/4.07.1/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -o test.exe -I . test.cmxa .test.eobjs/native/test.cmx)
> /usr/bin/ld: ./libtest_stubs.a(test.o): in function `f':
> /tmp/test/_build/default/test.cpp:3: undefined reference to `operator new(unsigned long)'
> collect2: error: ld returned 1 exit status
> File "caml_startup", line 1:
> Error: Error during linking
[2]
```
It would be indeed good to have a C++ compiler instead of the C compiler and to also add the right flag to link the standard library.

**Comment by rgrinberg** [comment]
Shouldn't these flags be set in the cpp flags of `ocamlc -config`?

**Comment by kit-ty-kate** [comment]
I can't see any `cpp` flags in the latest stable version of OCaml I have locally at least.

**Comment by rgrinberg** [comment]
What I had in mind was `ocamlopt_cppflags`, but I suppose it's not the job of OCaml to be setting this stuff.

**Comment by hongchangwu** [comment]
AFAIK, OCaml doesn't differentiate between C and C++ compilers. I had similar issue when linking libraries with C++ stubs.

My workaround for @kit-ty-kate's example is
```scheme
(executable
  (name test)
  (modules test)
  (libraries test)
  (link_flags -cc g++))
```

Not sure if there is a better way.
