### ISSUE TITLE
Passing on flags to ocamlmklib

### ISSUE THREAD

**Issue by prateek-khandelwal** [ocaml/dune#1948]
While writing stubs for a C file, I noticed that a shared object is also created and then installed to stublibs folder under the site-libs of ocaml distribution.

The problem I face with this is that I am not able to specify the `rpath` in  which would be used by the ocamlmklib command, and thus, this particular shared object ends up having it's rpath as a hardcoded path. I tried using `ocamlopt_flags`, however it doesn't get passed on to the ocamlmklib command.

Since the I need the `rpath` to be based on origin, rather than linking against a hardcoded path, I used `(no_dynlink)` flag so that the shared object is not created, and this does stop dll from getting created. ( I can see that we add `-custom` to ocamlmklib command when this flag is provided )

Can someone please suggest what would be the correct way to pass `rpath` to ocamlmklib command ? am I using the wrong flag option ?

**Comment by diml** [comment]
You should be able to pass flags to `ocamlmklib` by setting the `c_library_flags` field

**Comment by prateek-khandelwal** [comment]
Thanks for the pointer !
I did try it, however, I think I am making a mistake. I can see that ocamlmklib takes `-rpath` as an option, however, I am still not able to get it working as expected. 

I can see that even if I manually pass `-rpath \$ORIGIN` as an option to the ocamlmklib call, this is still causing an issue, as gcc ends up getting `:$ORIGIN` as an option. 

I understand that as far as dune is concerned, this is an ocamlmklib issue and OCaml mailing list would be the best place to ask this question, however, I wanted to know if you have faced similar issue in past ?

**Comment by diml** [comment]
Personally, I never used `rpath`

**Comment by prateek-khandelwal** [comment]
Sure. Thanks a lot for your comment.
