### ISSUE TITLE
docs: generate docs for dependecies

### ISSUE THREAD

**Issue by meadofpoetry** [ocaml/dune#1949]
Cargo has a neat feature: it could generate a documentation for both local project libraries and their dependencies [1]. It's very convenient for a developer to be able to browse all the documentation related to the project, whether it's for external or internal libraries.

Since dune already tracks all dependencies and use odoc for doc generation, would it be possible to generate docs for external dependencies as well?

[1] https://www.mankier.com/1/cargo-doc

**Comment by diml** [comment]
Yep. We discussed this in the past and it should be pretty easy to do. In fact, we already do something similar for js_of_ocaml: we compile .cma.js files on the fly for external dependencies.

**Comment by emillon** [comment]
This now exists as `dune build @doc-new` so I'm closing this issue. Thanks
