### ISSUE TITLE
Make it possible to pass a ppx in a env stanza

### ISSUE THREAD

**Issue by ulrikstrid** [ocaml/dune#1957]
This feature would make it possible to conditionally add `bisect_ppx` only when running tests.

There might be more ppxes that also would benefit from this that I don't know of.

**Comment by emillon** [comment]
Hi!

I believe that this can be marked as a duplicate of #57, which discusses how to properly support `bisect_ppx`.

We arrived to a conclusion that is described in this issue, now we just have to implement it 🙂.

Thanks!
