### ISSUE TITLE
Dune hangs

### ISSUE THREAD

**Issue by bobzhang** [ocaml/dune#1960]
`dune exec main.exe` takes around 20s, it would be nice to provide some better error message.
`dune exec ./main.exe` works

**Comment by diml** [comment]
We need a bit more context to understand this report :)

**Comment by rgrinberg** [comment]
If I had to guess, `$ dune exec main.exe` had to do some non trivial rebuilding to run. The subsequent `$ dune exec ./main.exe` on the other hand was with a clean build. I would like to see a timing comparison with `--no-build` instead.

**Comment by bobzhang** [comment]
<img width="274" alt="Screen Shot 2019-03-20 at 11 22 11 PM" src="https://user-images.githubusercontent.com/747051/54696927-af85b180-4b67-11e9-80a4-38166e3655b2.png">

**Comment by diml** [comment]
Ah, so the issue is that we don't display the progress bar by default in `dune exec`. If you run `dune exec --display progress ./main.exe`, then you should see what's happening.

**Comment by bobzhang** [comment]
```
stock>time dune exec --display progress main.exe
Error: Program "main.exe" not found!
Done: 0/0 (jobs: 0)
real    0m34.751s
user    0m7.361s
sys     0m18.243s
```

**Comment by rgrinberg** [comment]
@bobzhang is it possible to give us a project where we can try and reproduce this?

I will go through the 2 code paths to see what could be the difference.

**Comment by bobzhang** [comment]
I can not share the stuff. But it looks like dune takes lots of time in some dirs even if I declared it clearly in dune file using `ignored_subdirs`

**Comment by rgrinberg** [comment]
Could you post your values for `ignored_subdirs` and `data_only_dirs`.

Btw, what version of dune are you using? `ignored_subdirs` isn't recommended you should use `dirs` to specify these patterns if you can
