### ISSUE TITLE
FLG -open Lib added on the library itself

### ISSUE THREAD

**Issue by jchavarri** [ocaml/dune#1962]
Dune version: 1.8.2.

When running Merlin on the sample project [`hello-ocaml`](https://github.com/esy-ocaml/hello-ocaml) it errors out with `Unknown module Lib`.

I've managed to repro with both `reason-language-server` and `ocamlmerlin-lsp` so I'm starting to think this could be an issue on how Dune generates `.merlin` files for libraries. In this case, there is a `lib` folder with this [dune config](https://github.com/esy-ocaml/hello-ocaml/blob/master/lib/dune):

```
(library
  (name lib)
  (public_name hello-ocaml)
  (libraries lambda-term lwt)
)
```

And the generated `.merlin` file has this line added at the very end:
```
...
FLG -open Lib -w -40
```

That line is the one that I believe confuses Merlin –and any other tool based on this file– because it tries to compile the file with the `-open` flag included, which is pointing to the library itself.

**Comment by jchavarri** [comment]
> I've managed to repro with both `reason-language-server` and `ocamlmerlin-lsp`.

It turns out this was not true. I tried again with `ocamlmerlin-lsp` and could not repro so I guess this is an issue with `reason-language-server`, I'll track this issue over there.

Still don't understand why the `.merlin` file of a library contains an `-open` pointing to itself but oh well 😅

**Comment by rgrinberg** [comment]
It's just an artificact of how module aliases work in dune. It's the reason why modules don't need to use a qualified name to refer to other modules in the same library. See the module alias file that dune generates.

**Comment by jchavarri** [comment]
@rgrinberg Thanks for explaining, that makes a lot of sense.
