### ISSUE TITLE
How to install a profile to a prefix?

### ISSUE THREAD

**Issue by jberdine** [ocaml/dune#1971]
Perhaps this is my failure to read the docs, but I have not been able to figure out how to tell dune to install a particular profile to a specified prefix. I assumed that the following would work:
```
$ dune install --profile=release --prefix=_install/release my_package
Cannot specify --prefix or --libdir when installing into multiple contexts!
```
But the error message indicates that I have misunderstood something.

Is this possible? If not, is it hard to support?

For context, up to now I have not needed `dune install` much, but using the support in #1930 for versioning would involve running `dune install` to produce executables used for long/remote testing, as `dune build` alone does not set the version. In this use case, it is necessary to be able to `install` the various profiles simultaneously. Also note that even if it was acceptable to put files into opam-controlled directories, it is still the case that multiple profiles share the same opam switch.

**Comment by diml** [comment]
You can use `--context` to select one particular build context. Currently, you can't run one command to install all the build contexts at once unless they are installed in their default locaiton.

I suppose we could allow to pass `--prefix` several times, such as:

```
$ dune install --context a --prefix _install/a --context b --prefix _install/b
```

It shouldn't be hard to support, though I don't know if it's easy to do that with cmdliner. Another option would be to allow variables in the prefix:

```
$ dune install --prefix _install/%{context}
```

> Also note that even if it was acceptable to put files into opam-controlled directories, it is still the case that multiple profiles share the same opam switch.

Yh, this is not handled properly at the moment and dune will just silently override files when this happens :/

BTW, do you need to deploy executables from several build contexts at once? I have a simple solution in mind for the case where you want to deploy them from a single build context.

**Comment by jberdine** [comment]
It would be no problem if I had to run `dune install` once for each context specifying a different prefix for each.

But with
```
dune install --prefix=install/dev --context=dev my_package
```
I get
```
dune: unknown option `--context'.
```
(`--context` seems to be accepted only for `utop` and `exec` subcommands)

I do need to deploy executables from multiple (usually 2) contexts at once. There is one that includes lots of internal assertions and is slow, and another that is faster. The assertions in the slow one are good for catching bugs, but it is too slow to run large tests, which the faster one is used for.

**Comment by diml** [comment]
Ah, I thought this was supported for some reason. We should definitely support that. Supporting a `%{context}` variable seems simple enough and should be useful as well so I think we should do both

**Comment by rgrinberg** [comment]
@diml This is slightly complicated by the fact that we need slightly different rules to install from a different context. The rules need to create the .install files from the correct context I think. Currently, there's no way the user can control that. Perhaps we should create `.install` files in every context so that we don't need to rebuild anything to install from multiple contexts?

**Comment by jberdine** [comment]
Aren't there already `.install` files in each context? I normally build using a command such as:
```
dune build _build/dev/src/foo.exe _build/release/src/foo.exe _build/dev/foo.install _build/release/foo.install
```

**Comment by rgrinberg** [comment]
Ah yes, then disregard my comment. So this feature should be easy to implement. @jberdine perhaps you want to give it a try?

**Comment by jberdine** [comment]
I can try to have a look and see if I can avoid death-by-arrows.

**Comment by diml** [comment]
Haha, well you shouldn't need to deal with arrows for this. It's all in `bin/install_uninstall.ml`. Looking at the code, I believe all you need to do is filter the `install_files` list when a `--context` arugment is passed.  And also not raise. You can use `Import.Main.find_context_exn setup context_name` to make sure the context exists.

**Comment by diml** [comment]
@jberdine do you want to look at this in the end? If not, we'll just do it. It's quite a simple change and it seems useful.

**Comment by jberdine** [comment]
@diml I haven't had a chance to look at this, sorry. I wouldn't be unhappy if someone else did this. My interest is just to have the feature. The use case is to avoid one of the things that makes it necessary to have a wrapper Makefile for a mainly-dune build system. But it isn't the last such point, so it hasn't been a top priority so far.

**Comment by diml** [comment]
@jberdine no problem. I did the change to add a `--context` argument. Regarding adding a `%{context}`, variable, it seems like a relatively safe breaking change but since we are close to releasing dune 2 we might as well do this change in dune 2.

**Comment by ejgallego** [comment]
TTBOMK this issue is fixed, `install` supports `--context` , and `%{context_name}` has been added to the list of variables.
