### ISSUE TITLE
brew: improve pkg-config paths

### ISSUE THREAD

**Issue by Chris00** [ocaml/dune#1978]
Given [failures](https://github.com/ocaml/opam-repository/pull/13706#issuecomment-475936419) [to](https://travis-ci.org/Chris00/ocaml-cairo/jobs/511009634#L1648) [run](https://github.com/ocaml/opam-repository/issues/13709) `pkg-config` on MacOS unless `PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig` is set, it is maybe worth that dune _configurator_ automatically adds this path internally.  A better solution would be a generic way to work around the idiosyncrasies of pkg-config under homebrew.

**Comment by rgrinberg** [comment]
I do not think this is a good idea. From the documentation of libffi:

```
==> Caveats
libffi is keg-only, which means it was not symlinked into /usr/local,
because some formulae require a newer version of libffi.

For compilers to find libffi you may need to set:
  set -gx LDFLAGS "-L/usr/local/opt/libffi/lib"

For pkg-config to find libffi you may need to set:
  set -gx PKG_CONFIG_PATH "/usr/local/opt/libffi/lib/pkgconfig"
```

If the homebrew packagers wanted it in pkg-config by default, they would have done so. Let's avoid adding homebrew specific hacks to dune.

**Comment by Chris00** [comment]
This suggestion was just to ease the live of homebrew users.  ATM, a post-message says to add [`PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig`](https://github.com/ocaml/opam-repository/pull/13706#issuecomment-476413113).

**Comment by rgrinberg** [comment]
I'm closing this issue as this is something that we've experimented before and found it to have negative side effects. No other build system will automatically detect packages that homebrew explicitly says should be made visible manually.

Feel free to come back with concrete proposals.
