### ISSUE TITLE
Travis thinks long tests timeout because of buffering

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#1991]
Hi,

When running tests for an OCaml package in Travis CI, [it will time out if no output is received for 10 minutes with an error message](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received).

This can cause problems with `dune runtest`, because it will buffer its output and print it only at the end. Some projects [call the binary manually](https://github.com/mirage/ocaml-qcow/commit/ebf6116d2320af0544f8d7c44e16f77e8a0e3974) to avoid that, which is painful and can be subtly wrong (for example the wrong profile is used).

There are some workarounds already:
- as stated in the travis docs, it could be possible to use `travis_wait`
- it's possible to use `--no-buffer`, but this will cause interleaving unless `-j 1` is passed

There's a couple ways we could improve this:
- do something similar to `travis_wait` by emitting a line every minute
- flush the output at regular intervals

**Comment by rgrinberg** [comment]
Good riddance with travis.
