### ISSUE TITLE
Fails witth `Sys_error("Permission denied"` when a parent doesn't have exec permission

### ISSUE THREAD

**Issue by AltGr** [ocaml/dune#2002]
As for the title. Other issues (#310, #1060) mention permission issues on descendants or siblings, but not directly on the parent directories, which can be the case on some restricted systems. Note that specifying `--root` works around the issue, but I think it would be best to stop looking without failing in this case.

**Comment by diml** [comment]
The proposed fix sounds reasonable to me.

**Comment by rgrinberg** [comment]
This is fixed in 1.9
