### ISSUE TITLE
Configurator.V1.C_define.import should gracefully handle C compilations errors

### ISSUE THREAD

**Issue by db4** [ocaml/dune#2005]
Currently  `jst-config` cannot be built on Windows as `C_define.import` does not tolerate missing include file "sys/resource.h":
```ocaml
    let rlimit_vars =
      C.C_define.import c ~includes:["sys/resource.h"]
        [ "RLIMIT_AS"  , Switch
        ; "RLIMIT_NICE", Switch
        ]
    in
```
@diml in https://github.com/janestreet/jst-config/issues/1#issuecomment-478933691 suggests it should be changed to use dummy values in case of compilation errors (if I got it right)

**Comment by diml** [comment]
Yes, also this behaviour should be optional as we can't know for sure whether it is acceptable for the header files to be missing. Thinking, about this again, we could simply rewrite this code as follow:


```ocaml
if C.c_test c "#include <sys/resource.h>" then
  C.C_define.import ...
else
  [ "RLIMIT_AS", Switch false
  ; "RLIMIT_NICE", Switch false
  ]
```

**Comment by diml** [comment]
In the end, it doesn't seem necessary to change configurator, so I'm closing this issue
