### ISSUE TITLE
odoc: page references aren't resolved

### ISSUE THREAD

**Issue by vphantom** [ocaml/dune#2007]
Hello. Sorry to pile onto an already busy list of issues, but it was suggested in https://github.com/ocaml/odoc/issues/346 that I report my finding here, as `odoc` per se is apparently not to blame.

Tested with Dune v1.8.2 and Odoc v1.4.0, the attached: [odoc-page-link-bug.tar.gz](https://github.com/ocaml/dune/files/3034077/odoc-page-link-bug.tar.gz) is a simple project with two `.mld` files.

Linking from `index.mld` to `otherpage.mld` with syntax `{{!page-otherpage}Test page}` yields "unresolved reference to 'otherpage'" in the resulting HTML generated with `dune build @doc`.  My understanding is that this should have resolved into a normal hyperlink.

**Comment by jonludlam** [comment]
Yes - using --verbose you can see odoc being invoked:

```
odoc html -o . ../_odoc/pkg/odoc_page_link_bug/page-index.odoc)
```

It needs an include path for the other package mld files added to the command line:

```
odoc html -o . -I ../_odoc/pkg/odoc_page_link_bug/ ../_odoc/pkg/odoc_page_link_bug/page-index.odoc
```

and then it correctly resolves the link

**Comment by vphantom** [comment]
I see!  Is this something I need to instruct Dune to do, or will this be perfected in Dune's invocation of odoc in the future?  I'm not sure if I'm culpable of a user error. :wink:

**Comment by jonludlam** [comment]
It's not a user error, just a bug in dune I think.

**Comment by rgrinberg** [comment]
The way I understood things, only .odoc files had to be in the include path when generating html. From your command, that seems to be what you meant. Is that right?

**Comment by jonludlam** [comment]
@rgrinberg yes, but I think the code currently only adds include paths for the libraries, not the package. I'll send a PR.
