### ISSUE TITLE
dune doesn't resolve symlinks and create wrong paths in .merlin files

### ISSUE THREAD

**Issue by Khady** [ocaml/dune#2025]
We have two projects p1 and p2. p2 is nested in p1 by using a
symlink. This specific example could be solved by using a dune
workspace containing the two projects, but this is not what I want to
illustrate.

```
.
├── p1
│   ├── _build
│   ├── dune
│   ├── dune-project
│   ├── main.ml
│   ├── .merlin
│   ├── p1.opam
│   └── p2 -> ../p2
└── p2
    ├── a.ml
    ├── dune
    ├── dune-project
    ├── .merlin
    └── p2.opam
```

My problem is that in this case, the .merlin file generated for p2 can be considered as incorrect. It contains a path that doesn't point to an existing _build directory.

```bash
$ cd p1
dune build main.exe
$ ../cat p2/.merlin
EXCLUDE_QUERY_DIR
B ../_build/default/p2/.p2.objs/byte
S .
FLG -open P2 -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs
```

It forces me to go to p2, compile p2 again and then use merlin in p2.

I created a repo to reproduce the problem https://github.com/Khady/dune-symlinks-problem

cc @jorisgio

**Comment by diml** [comment]
I'm not sure what the right behaviour is though. For instance, let's say you work on p1 in your editor, then jump to p1/p2/a.ml via merlin for instance. It that case the .merlin file currently generated is correct.

We have been talking with @trefis and @let-def about having dune and merlin communicate directly without going through the FS. That would effectively solve the issue as dune would always know what the current compilation root is.

Until then, I guess we could always generate absolute paths. Though IIRC, we were doing that in the past and it wasn't great for some other reason.

**Comment by jorisgio** [comment]
I didn't see this issue was opened. To be fair, i believe this is a minor problem and we made a mistake by using symlinks like this. 

The problem with absolute path is that then you cannot "move" your project, which afaik is possible currently.

**Comment by rgrinberg** [comment]
I'm closing this as it's not clear what the correct fix and the odds of anyone addressing this before the new merlin interface comes out are low.
