### ISSUE TITLE
MSVC <CR><LF> issues

### ISSUE THREAD

**Issue by db4** [ocaml/dune#2037]
When MSVC compiler reports warnings/errors, dune removes line breaks from its output:

```
dune build src/test_stubs.obj

      ocamlc src/test_stubs.obj
cl : Command line warning D9002 : ignoring unknown option '-g'
test_stubs.c
test_stubs.c(4): warning C4101: 'y': unreferenced local variabletest_stubs.c(3): warning C4101: 'x': unreferenced local variable
```
MSVC warnings
```
test_stubs.c(4): warning C4101: 'y': unreferenced local variable
test_stubs.c(3): warning C4101: 'x': unreferenced local variable
```
 are missing line breaks and merged into one big line.

**Comment by nojb** [comment]
Are you running the command under Cygwin or under cmd.exe ?

**Comment by db4** [comment]
Under `cmd.exe`. No Cygwin `bash` or `sh` at all.

**Comment by nojb** [comment]
This is a bug in the compiler, see https://github.com/ocaml/ocaml/pull/8875
