### ISSUE TITLE
dune exec does not pass arguments transparently

### ISSUE THREAD

**Issue by hbr** [ocaml/dune#2038]
According to the documentation

  dune exec prog.exe arg1 arg2 ...

should build the program and execute it with the arguments arg1 arg2. However if the arguments contain options of the form "-key value" dune obviously takes the options as own options and rejects it.

E.g. I have a project with a program alba.exe. If I issue

  dune exec ocaml/alba.exe compile -work-dir library/alba.base/

I get the error

  dune: unknown option `-o'.

Is this the intended behaviour or is it a bug? Is there a workaround?

Regards
Helmut

**Comment by ejgallego** [comment]
You need to issue `dune exec -- prog.exe args...` IMO the documentation seems correct.

**Comment by hbr** [comment]
You are right, it works as you said. The documentation is correct as this possibility is mentioned. However the synopsis `dune exec [OPTION]... PROG [ARGS]...` is a little bit missleading.

It should be changed to `dune exec [OPTION]... -- PROG [ARGS]...`

**Comment by ejgallego** [comment]
Oh indeed @hbr, maybe you could submit a pull request improving the synopsis? IMHO it is valid bug.

**Comment by Khady** [comment]
esy has a fork of cmdliner that would allow to skip the `--`: https://github.com/esy-ocaml/cmdliner/commits/feat/stop_on_pos

**Comment by diml** [comment]
That seems nice. Would it be possible to upstream this patch? I'd rather we stick to vendoring upstream projects unmodified.

**Comment by rgrinberg** [comment]
@Khady what happens when an argument is accepted both by dune and the program being executed?

**Comment by Khady** [comment]
From what I experienced with esy, it depends on the position of the argument. Every argument after the first positional will be given to the program being executed. All the arguments before the first positional argument are given to dune.

```
$ esy --help=pager ls | head
esy(1)                            Esy Manual                            esy(1)



NAME
       esy - package.json workflow for native development with Reason/OCaml

SYNOPSIS
       esy COMMAND ...

$ esy ls --help | head
Usage: /bin/ls [OPTION]... [FILE]...
List information about the FILEs (the current directory by default).
Sort entries alphabetically if none of -cftuvSUX nor --sort is specified.

Mandatory arguments to long options are mandatory for short options too.
  -a, --all                  do not ignore entries starting with .
  -A, --almost-all           do not list implied . and ..
      --author               with -l, print the author of each file
  -b, --escape               print C-style escapes for nongraphic characters
      --block-size=SIZE      scale sizes by SIZE before printing them; e.g.,
```

**Comment by diml** [comment]
FTR, I do find the esy behavior more intuitive. It's a pain to have to use `--` all the time.

**Comment by Khady** [comment]
I opened a pull request on cmdliner with the code of Andrey: https://github.com/dbuenzli/cmdliner/pull/108
