### ISSUE TITLE
Running executables from the project root

### ISSUE THREAD

**Issue by anton-trunov** [ocaml/dune#2045]
Hi, I have the following setup:

1. A bunch of installable executables in `MY_PACKAGE` package.
2. A test suite that runs those executables on some inputs
```
(test
 (name testsuite)
 (deps (package MY_PACKAGE)) 
 ...
```

My problem is that `dune` changes the working directory before running tests:
```shell
$ dune runtest
   testsuite alias tests/runtest
(cd _build/default/tests && ./testsuite.exe)
```
but `testsuite.exe` relies on being run at the project root, so I'd like `dune` to execute it like so `_build/default/tests/testsuite.exe`.

Is it possible to solve this? Or if it's the totally wrong approach with testing, feel free to tell me. I'd greatly appreciate any pointers! Thank you.

**Comment by ejgallego** [comment]
I guess the recommended solution is to use the `runtest` alias and do the chdir accordingly:
```
(action (chdir %{project_root} (run testsuite.exe))
```
you may need to use the env to put binaries into scope.

Beware with composed builds tho, it is usually better if you can tweak the test suite as to run in its own subdir.

**Comment by rgrinberg** [comment]
Emilio proposes the correct workaround. Note that instead of hard coding the exe name in the action, you could also do:

```
(action (chdir %{project_root} (run %{test})))
```

I also recommend to stick to dune's conventions and run all actions in the directory where they are defined.
