### ISSUE TITLE
Sys_error on directory rules

### ISSUE THREAD

**Issue by corwin-of-amber** [ocaml/dune#2070]
This dune file:
```
(rule
 (targets dir)
 (action (bash "mkdir %{targets}")))
```

Crashes Dune if a file named `dir` is present in the source tree.

```
Error: exception Sys_error("Is a directory")
Backtrace:
Raised at file "src/build_system.ml", line 1414, characters 9-14
Called from file "src/fiber/fiber.ml", line 79, characters 8-15
```

Additionally, if `(mode promote)` is set in the rule:
```
(rule
 (targets dir)
 (mode promote)
 (action (bash "mkdir %{targets}")))
```

Then, if `dir` is **not** present in the source tree, Dune creates an empty file (in the source tree), then the previous crash is triggered.

**Comment by rgrinberg** [comment]
Thanks for the report, yes there are currently some issues with directory targets. I will add your examples to the test suite.

**Comment by cpitclaudel** [comment]
(This also causes an issue when trying to promote a directory generated by a rule.)

**Comment by corwin-of-amber** [comment]
Are there any plans to support promoting directories? The same error persists.

**Comment by ejgallego** [comment]
> Are there any plans to support promoting directories? The same error persists.

AFAICT Dune devs would like to properly support this, but so far it seems it is not gonna happen soon, if I understand the development schedule correctly.

**Comment by emillon** [comment]
This seems to be fixed now:
- the error message is "multiple sources for ..." (and is correct since it's both in source tree and generated)
- (mode promote) works if the target is written as a directory target `(dir dir)`.
Thanks
