### ISSUE TITLE
dune clean leave install files

### ISSUE THREAD

**Issue by Pitometsu** [ocaml/dune#2074]
When I do `dune clean` there's still `*.install` files in project.

**Comment by Pitometsu** [comment]
```shell
$ dune --version
1.9.1
```

**Comment by diml** [comment]
I just gave it a try in dune and couldn't reproduce the issue:

```
$ dune build
$ ls dune.install
dune.install
$ dune clean
$ ls dune.install
ls: cannot access 'dune.install': No such file or directory
```

Could you provide a reproduction case?

**Comment by Pitometsu** [comment]
```
$ dune build
$ ls *.install
development.install  project.install
$ dune clean
$ ls *.install
development.install
```

**Comment by Pitometsu** [comment]
Well, I have two repository clones, on one it remove both install files, on other -- only project one.
And I remember previously it had skip both. Not sure, why so.

**Comment by Pitometsu** [comment]
dune `1.9.1` at both.

**Comment by diml** [comment]
What `<packages>.opam` files do you have? And are they at the root of in sub-directories?

**Comment by Pitometsu** [comment]
Two of them at root (except ones from `_buld` and `_opam`):
```
$ git ls-files '*.opam'                    
development.opam
mainnet.opam
```

**Comment by diml** [comment]
Ok, that does look like a bug. Could you point me to the repository in question?

**Comment by Pitometsu** [comment]
@diml sorry, it didn't open-sourced (yet). I'll try to create small demo to reproduce this in few days, thank you.

**Comment by rgrinberg** [comment]
@Pitometsu feel free to re-open once you have the small reproduction case. This would be highly appreciated as I don't think we can resolve this issue without it
