### ISSUE TITLE
When polling, clear screen on file change

### ISSUE THREAD

**Issue by ddickstein** [ocaml/dune#2080]
In polling mode it's difficult to differentiate between new and old errors. It would be helpful to clear the screen each time a file change is detected and errors are re-checked.

**Comment by diml** [comment]
Related to #2063

**Comment by TyOverby** [comment]
Oh wow, did switching time-zones actually give me the power to implement features before they're requested?  Maybe I should stay in Hong Kong...

**Comment by rgrinberg** [comment]
Dune clearly separates old and new builds now. Please re-open if you have other ideas to improve the output.
