### ISSUE TITLE
Odoc rules do not compute the package version correctly

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#2083]
Here is how it's done in the odoc ruiles:

https://github.com/avsm/dune/blob/9f6daf146d92e02da73c50b4c6b6ebb32a077f6f/src/odoc.ml#L241-L246

Here is how it's done in the install rules:

https://github.com/avsm/dune/blob/9f6daf146d92e02da73c50b4c6b6ebb32a077f6f/src/install_rules.ml#L71-L96

Odoc should reuse the method form install rules for consistency.

@jonludlam from now on, I'll assign odoc issues in bulk to you if you don't mind.

**Comment by emillon** [comment]
The difference has been removed in #2541. Now we use `pkg.Package.version` which sources from `(version)`, `(package (version))` or the VCS.
