### ISSUE TITLE
Unwrapped libraries and variant

### ISSUE THREAD

**Issue by Drup** [ocaml/dune#2092]
@rgrinberg affirmed that variant implementations should be allowed to add extra modules to unwrapped libraries. However, when I attempted it, I got:
```
Error: The following modules aren't part of the virtual library's interface:
- Tyre_regex
They must be marked as private using the (private_modules ..) field
```

The virtual lib's stanza is:
```
(library
 (name        tyrefun)
 (public_name tyre.fun)
 (wrapped false)
 (libraries result seq)
 (ocamlopt_flags :standard -O3)
 (virtual_modules tyrefun_regex)
)
```

and the variant impl stanza is:
```
(library
 (name tyre_mark)
 (public_name tyre.mark)
 (libraries re)
 (implements tyre.fun)
)
```

with two modules: `tyrefun_regex` and `tyre_regex`.

**Comment by smondet** [comment]
Indeed <https://dune.readthedocs.io/en/stable/variants.html#limitations> says:

> It is not possible for implementations to introduce new public modules. That
> is, modules that aren’t a part of the virtual library’s cmi. Consequently, a
> module in an implementation either implements a virtual module or is private.

Is it a temporary limitation? Or is there a fundamental reason for that?

**Comment by rgrinberg** [comment]
It would be very easy to lift this limitation for unwrapped libraries. For wrapped libraries, it would be tougher. One would need a way for the implementation to introduce a toplevel name where the new public modules could exist.

**Comment by smondet** [comment]
In @drup's example above, you mean those modules cannot live under `Tyre_mark.Extra_module`?

(even for unwrapped libraries only, this seems like a very useful feature for all the "base-compatibility-library" + "backends-with-various-extenstions" virtual-library/implementations combos)

**Comment by rgrinberg** [comment]
> In @Drup's example above, you mean those modules cannot live under Tyre_mark.Extra_module?

The name you proposed would be the natural one for extra modules. It would be somewhat unexpected that that `tyre.mark` introduce modules both under `Tyre_mark` and `Tyrefun`.

> (even for unwrapped libraries only, this seems like a very useful feature for all the "base-compatibility-library" + "backends-with-various-extenstions" virtual-library/implementations combos)

Very well, we'll consider the feature in the next dune meeting. If you have more arguments, use cases, or anything else you might want to say, those will be very handy for our discussion.

**Comment by smondet** [comment]
> (Obviously these are not fully fleshed-out ideas :) → )

The use-case/example that brought me here is trying to factor out code that has a “mutable thing that should work in a native or multicore or JSOO context, and that you may want to subscribe to”.

There could be a base-layer that provides the API of [Stdlib.Atomic](https://ocaml.org/api/Stdlib.Atomic.html) **plus** something like a `val signal: 'a t -> 'a signal` function.

Then depending on the context that API can be implemented with Incremental, React, Lwd, some stream library (Eio? Lwt?), or even combinations of those.

The extra modules would allow one to use the `'a signal` further (for instance as a `'a React.signal` or `'a Lwd.t` in a webapp).

(After, there would not be just a `'a ref` API but other mutable containers like arrays …)

**Comment by rgrinberg** [comment]
Today's discussion: nobody was against lifting this limitation and it seems useful to some people. Therefore this proposal is accepted.

**Comment by rgrinberg** [comment]
The limitation was lifted a while ago.
