### ISSUE TITLE
Variants, vocabulary and UI

### ISSUE THREAD

**Issue by Drup** [ocaml/dune#2094]
I found the vocabulary and UI surrounding variants quite poor. This is sort of a laundry-list of soft remarks. The goal is to encourage a discussion to unfold the whole thing.

The vocabulary surround variants is very confusing:
1. While the feature in general is called "variant", the actual variants are just tags. From all intent and purpose, they do not vary in anyway, they are more akin to compilation targets.
2. The thing that actually vary is called "virtual module". This is mostly fine, especially since this vocabulary is not really used in the OCaml module system (only in OO, and the meaning is the same).
3. The concrete version of a "virtual library" is called an "implementation" in the documentation. "Implementation" is fairly overloaded (...) but even worse: it means a specific thing in the ocaml module system, which is similar-but-not-the-same as variant implementations.

I do not have a definite answer,  but something along the lines of "variant library"/"variant tag"/"concrete library" would probably be a good start.

The UI make it seems that concrete libraries are actually normal libraries. However, in practice many fields are not usable, and others do not have the same semantics at all (naming, for instance). I wonder if concrete libraries shouldn't simply use a different stanza.

Finally, currently, having lot's of variants incur a fairly step cost: one directory per concrete library. In the case of libraries with only one virtual module, it's a bit painful.
For instance, if I have virtual module `A`. I would like to be able to have one directory with `A_foo`, `A_bar`, `A_baz` and a dune file describing 3 concrete libraries (with an appropriate module remapping, I suppose).

**Comment by diml** [comment]
We are putting library variants back in development mode (https://discuss.ocaml.org/t/dune-serious-bug-found-in-the-design-of-library-variants/3743), so renaming things is on the table. /cc @TheLortex @rgrinberg 

BTW, thanks for testing this feature and reporting your experience here!

**Comment by rgrinberg** [comment]
Given that variants were removed, this issue has been solved.
