### ISSUE TITLE
Cannot install dune 1.9.1 with opam.

### ISSUE THREAD

**Issue by chrism** [ocaml/dune#2111]
Hi, I’m having trouble installing `dune` using `opam`.

I’m trying to installing camomile with

```
opam install camomile
```

But as it depends on jbuilder, which in turn depends on dune, the installation fails.

Here is the log output

```
The following actions will be performed:
  ∗ install dune     1.9.1      [required by jbuilder]
  ∗ install jbuilder transition [required by camomile]
  ∗ install camomile 1.0.1
===== ∗ 3 =====

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[dune.1.9.1] downloaded from cache at https://opam.ocaml.org/cache
[camomile.1.0.1] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of dune failed at "/home/deployer/.opam/opam-init/hooks/sandbox.sh build ocaml bootstrap.ml".

#=== ERROR while compiling dune.1.9.1 =========================================#
# context              2.0.4 | linux/x86_64 | ocaml-system.4.02.3 | https://opam.ocaml.org#9fbe2b53
# path                 ~/.opam/default/.opam-switch/build/dune.1.9.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build ocaml bootstrap.ml
# exit-code            137
# env-file             ~/.opam/log/dune-32491-ad6566.env
# output-file          ~/.opam/log/dune-32491-ad6566.out
### output ###
# [...]
# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/stdune/caml/dune_caml.ml > boot-depends.txt
# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/dune_lang/dune_lang.ml src/dune_lang/atom.ml src/dune_lang/dune_lexer.ml src/dune_lang/escape.ml src/dune_lang/jbuild_lexer.boot.ml src/dune_lang/lexer.ml src/dune_lang/lexer_shared.ml src/dune_lang/syntax.ml src/dune_lang/template.ml src/dune_lang/types.ml > boot-depends.txt
# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/stdune/result/dune_result.ml src/stdune/result/result.ml src/stdune/result/result_compat.ml > boot-depends.txt
# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/fiber/fiber.ml > boot-depends.txt
# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' vendor/incremental-cycles/src/incremental_cycles.ml vendor/incremental-cycles/src/incremental_cycles_intf.ml > boot-depends.txt
# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/memo/memo.ml src/memo/implicit_output.ml > boot-depends.txt
# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/ocaml-config/ocaml_config.ml > boot-depends.txt
# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/stdune/stdune.ml src/stdune/ansi_color.ml src/stdune/appendable_list.ml src/stdune/array.ml src/stdune/bin.ml src/stdune/bool.ml src/stdune/bytes.ml src/stdune/char.ml src/stdune/common.ml src/stdune/comparable.ml src/stdune/digest.ml src/stdune/dyn.ml src/stdune/dyn0.ml src/stdune/either.ml src/stdune/env.ml src/stdune/escape.m[...]
# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/wp/wp.boot.ml > boot-depends.txt
# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/xdg/xdg.ml > boot-depends.txt
# /usr/bin/ocamlc.opt -g -w -40 -o boot.exe -pp './boot-pp.exe -dump-ast' -I +threads unix.cma threads.cma boot.ml
# Killed
```

Any help would be much appreciated. Thanks.

**Comment by diml** [comment]
What os are you building on? I wonder if the bootstrap hasn't exceed some resource limit again...

**Comment by chrism** [comment]
Hi,

I'm building a virtual machine with puppet from a 'ubuntu/trusty64' basebox.

It runs the updates from ubuntu 14.04.4

Is that enough info for you?

Thanks,

Chris

**Comment by diml** [comment]
Well, we can't do much on our side with just "Killed" in the log :) I was asking as we had similar reports on BSD in the past.

For now, you can try to increase the resource limits. There are things we can do in dune to mitigate this issue, but it will take some time to develop.

**Comment by chrism** [comment]
Hi @diml I guess that your reply answers my question about enough information then :)

I'm sorry, this isn't a subject I know about, I'm just trying to work through dependencies hoping to eventually get liquidsoap installed.

I will try to increase resource limits and see if that works.

Thanks for your help.

**Comment by avsm** [comment]
Exit code 137 is the process receiving a SIGKILL, which is likely the oomkiller.  What does the dmesg from the VM say?

**Comment by rgrinberg** [comment]
Yeah, unfortunately there's really not much that can be done on the dune side to fix this. I do wonder if this problems are going to become more severe in the future. The amount of code in dune will keep growing, perhaps it will not be possible to compile everything in a single command under a reasonable resource limit.

**Comment by diml** [comment]
One possibility would be to adapt `bootstrap.ml` to do separate compilation. It shouldn't be too difficult.

**Comment by loscil06** [comment]
I had this same very problem in which the process is killed, does your instance has swap space? Tried to install it without realizing I didn't have swap space allocated, once I allocated 1gb it allowed me to install.

**Comment by diml** [comment]
We have a new bootstrap process in the pipe that will solve this issue once and for all.

/cc @dra27

**Comment by diml** [comment]
The new bootstrap has been merged, so you should no longer observe such problems when building `dune`. If you still do, please open a new ticket.
