### ISSUE TITLE
Docs build fail with multiple virtual library implementations

### ISSUE THREAD

**Issue by jonludlam** [ocaml/dune#2138]
In master, trying to build odoc docs with dune fails with:

```
Error: Conflicting implementations for virtual library "dune._wp":
- "dune._wp.dune" in _build/default/src/wp/dune-impl
- "dune._wp.jbuilder" in _build/default/src/wp/jbuilder-impl
Multiple rules generated for _build/default/_doc/_html/dune/Wp/.dune-keep:
- <internal location>
- <internal location>
```

A reasonable approach for now might be never to build docs for _implementations_ of virtual libraries, since they all must share the same signature.

**Comment by avsm** [comment]
Given the restrictions going into dune 1.10 for virtual libraries (#2134), it might be possible to list the implementations available as part of the doc index generation step...

**Comment by jonludlam** [comment]
Yep, sounds like a good idea.

**Comment by rgrinberg** [comment]
> Given the restrictions going into dune 1.10 for virtual libraries (#2134), it might be possible to list the implementations available as part of the doc index generation step...

The restriction is only imposed on variants and not on virtual libraries. It will not be possible to list all implementations when building a virtual library.

Another option is to just include implementations in the generated index but link them to the virtual library with an appropriate note.
