### ISSUE TITLE
unbound module in custom toplevel

### ISSUE THREAD

**Issue by puitgfr** [ocaml/dune#2146]
I try to build a custom toplevel named `ocaml_inf201` with a library called `i201` (one module + one included module). `I201` defines one fonction named `f`.

Code can be found here: [puitgfr/ocaml_inf201](https://github.com/puitgfr/ocaml_inf201)

`dune build @install` doesn't complain, but when I launch the toplevel:

> $ ocaml_inf201
>        OCaml version 4.06.1
>
> \# I201.f ;;
> Error: Unbound module I201
> \#

Sorry for this beginner question, but I can't figure out my error.

**Comment by nojb** [comment]
You still need to make `i201.cmi` visible to the toplevel by passing `-I` flags, e.g.:
```
$ _build/install/default/bin/ocaml_inf201 -I _build/default/Lib/.i201.objs/byte
```

**Comment by puitgfr** [comment]
Thanks for your suggestion, that works perfectly (without `/byte`).
After installing the toplevel in my current switch, I've tried also the following, with equal success:
> $ ocaml_inf201
>  OCaml version 4.06.1
>
> \# #require "ocaml_inf201" ;;
> I201.f ;;
> \- : 'a -> 'a = \<fun\>

I was wondering if it's possible to avoid the `#require "ocaml_inf201"` step, maybe with some magic incantations in [ocaml_inf201.ml](https://github.com/puitgfr/ocaml_inf201/blob/master/Top/ocaml_inf201.ml) ?

**Comment by nojb** [comment]
> I was wondering if it's possible to avoid the `#require "ocaml_inf201"` step, maybe with some magic incantations in [ocaml_inf201.ml](https://github.com/puitgfr/ocaml_inf201/blob/master/Top/ocaml_inf201.ml) ?

`#require` is a [`Topfind`](http://projects.camlcity.org/projects/dl/findlib-1.7.1/doc/ref-html/lib/Topfind.html) command (from the `findlib` library), and you will need to use `Topfind.load` to do that in code. If `#load` is enough for your purposes, I believe you can do it by using one of the functions in [`Topdirs`](https://github.com/ocaml/ocaml/blob/trunk/toplevel/topdirs.mli).

**Comment by puitgfr** [comment]
Doesn't seem to work. I've tried to load my lib `ocaml_inf201` before entering the toplevel in [ocaml_inf201.ml](https://github.com/puitgfr/ocaml_inf201/blob/master/Top/ocaml_inf201.ml):
> let () =
> ` ` Topfind.load ["ocaml_inf201"] ;
> ` ` Topmain.main ()

but it has no effect: I get the same error when trying to access values from the I201 module: `Unbound module I201` (whereas this very same code works when entered directly in the toplevel). I guess `Topmain.main` erases its environment.

Same behavior when using `Topdirs`.

**Comment by diml** [comment]
You can look at how utop does it: https://github.com/ocaml-community/utop/blob/master/src/lib/uTop.ml#L796

**Comment by mroch** [comment]
> You can look at how utop does it: https://github.com/ocaml-community/utop/blob/master/src/lib/uTop.ml#L796

permalink: https://github.com/ocaml-community/utop/blob/7df33e500a19dbcec73a3856f6b498e021f7c125/src/lib/uTop.ml#L796

**Comment by emillon** [comment]
we now have `dune utop` and `dune ocaml top` which should do the right thing in that case, so I'm closing this bug report. thanks
