### ISSUE TITLE
[RFC] Third profile (for experiments)

### ISSUE THREAD

**Issue by ksromanov** [ocaml/dune#2157]
There are currently two profiles supported: `dev` and `release`. They serve
two situations:

1. `dev` - when developer wants to polish the code as much as possible,
but the code is not yet released. So, we have maximum strictness, lots of
checks, enforced `-warn-error`. Also we want reasonably small build time.

2. `release` - when code is released and the author has no control over it.
This means, that we do not care about build time, but we have to relax
`-warn-error`, because it is possible that program is compiled with
a newer compiler, which has new warnings.

I personally miss another profile - for experimental work, when I just make
a sketch of a new feature. This work style is close to repl:
I don't care about unused variables, about other warnings, which are
not acceptable in released code. Sometimes even errors are acceptable, if
they happen below the code I just wrote. But what I need is a fast build time
and just a single set of warnings.

Is it possible to introduce a third profile `experiment` or something like
that (may be `draft` or `sketch`), which has no `-warn-error` set, 
some reasonable warnings enabled,
and compilation with just bytecode or native compiler, whichever is faster?

So, the workflow will look like

1. Sketching - `--profile experiment`

2. Polishing/CI - `--profile dev`

3. Release - `--profile release`

**Comment by diml** [comment]
You can already do all this:
- you can define your own profile with custom compilation flags
- if you want to only build the bytecode, which is indeed much faster, you can request dune to build `prog.bc` or `lib.cma`

So I suggest that you play with these settings, and once you find the right ones that work well across all your projects, we can discuss adding a new standard experimentation profile.

**Comment by rgrinberg** [comment]
As mentioned above, users may define their own profiles quite easily. There's no need to make this built-in to dune unless there's strong demand.
