### ISSUE TITLE
Some modules not getting compiled into `.cmx*` in virtual library implementations.

### ISSUE THREAD

**Issue by jordwalke** [ocaml/dune#2166]
Suppose you have two virtual modules V1 and V2 (virtual module 1 and 2), which are implemented in a concrete implementation of a virtual library (their interfaces are supplied in the virtual library).

Suppose in the virtual library (not concrete implementation) there is also a module C1 (which is not virtual).
Now introduce a third virtual module V3 which lives alongside V1/2 in the concrete implementation and that is also declared as virtual in the virtual library.

Assume V3 depends on C1. That means we have:

- V1: No deps
- V2: No deps
- V3: Depends on C1.

Now, by changing what C1 depends on you can toggle the buggy behavior.
If C1 depends on V1, but doesn't depend on V2, then V1 won't get linked in, but V2 will get linked in.
Dune thinks that because the "abstract virtual library"(having module C1) depends on V1, it doesn't need to compile V1 into the concrete implementation (cmx*).

**Comment by jordwalke** [comment]
To confirm my theory, I made `V3` an empty module that doesn't depend on C1, and sure enough, both V1/V2 were correctly compiled into the cmx* of the concrete implementation library.

Then, I made V3 depend explicitly on V1 and V2 directly, without "hopping" through C1, and it continues to behave correctly. The bug happens when V3 depends on V1 or V2 indirectly by "hopping" through a module in the "base" virtual library.

The module you depend on indirectly through a "hop" through the virtual library is the one that doesn't get compiled into the cmx*.

**Comment by rgrinberg** [comment]
This issue is critical for 1.10 btw.

**Comment by jordwalke** [comment]
Initial test of your PR seems positive. But I'll keep testing to let you know if I see anything wrong.

**Comment by diml** [comment]
Could the bug description in this PR be turned into a test? That would help reviewing the fix

**Comment by rgrinberg** [comment]
We've tried doing that naively but it didn't work. What we need to do is to preserve the dep graph from jordan's example without leaking any sensitive information. Perhaps Jordan can take only the virtual library and implementation in question, copy all modules but erase all the sources. We only care about preserving the ocamldep structure, so perhaps we can do it by adding statements like `open Foo` to introduce a dependency on `Foo`. If this is done accurately for every module, this should give us a faithful reproduction case.

**Comment by diml** [comment]
I feel like a reproduction case would definitely help here. Especially given that the fix looks complex, we don't want to accidentally break things in the future!

**Comment by diml** [comment]
I'm reading this ticket again and I don't understand what the bug is. @jordwalke, what do you mean by "not getting compiled into `*.cmx`"? Do you mean that some .cmx files are missing in the `.cmxa` file of the concrete library?

**Comment by rgrinberg** [comment]
Some cmx files were indeed missing. Jordan showed me the full error log but it contained some sensitive information.

**Comment by diml** [comment]
Ok, but we need a public reproduction case for this.

**Comment by XVilka** [comment]
This one marked for 1.10 milestone, but it was already released. Probably should be moved then?

**Comment by rgrinberg** [comment]
Indeed. I adjusted it.

**Comment by rgrinberg** [comment]
@jordwalke would you mind confirming the status of this bug on master?

**Comment by rgrinberg** [comment]
I'm closing this bug until it's status is confirmed. It's likely to be fixed in master.
