### ISSUE TITLE
tar.gz version of source code doesn't have %%VERSION%% set

### ISSUE THREAD

**Issue by jfehrle** [ocaml/dune#2183]
After building and installing the tar.gz version of dune, `dune --version` prints `%%VERSION%%`, which is not too helpful.  The .tbz version appears to be correct.

These are the essential diffs between the tar.gz version and the .tbz version: (version 1.9.3 from https://github.com/ocaml/dune/releases):

```
diff -r dune-1.9.3/bin/main.ml /cygdrive/c/dune-1.9.3/bin/main.ml
156c156
<    Term.info "dune" ~doc ~version:"1.9.3"
---
>    Term.info "dune" ~doc ~version:"%%VERSION%%"
diff -r dune-1.9.3/bin/subst.ml /cygdrive/c/dune-1.9.3/bin/subst.ml
4c4
< (** A string that is "1.9.3" but not expanded by [dune subst] *)
---
> (** A string that is "%%VERSION%%" but not expanded by [dune subst] *)
diff -r dune-1.9.3/dune.opam /cygdrive/c/dune-1.9.3/dune.opam
1d0
< version: "1.9.3"
44c43
< """
\ No newline at end of file
---
> """
```

FWIW, I noticed this in https://github.com/ocaml/opam/issues/3843

**Comment by rgrinberg** [comment]
The tbz version is the one that the dune team officially prepares for releases. The tgz one is the one automatically generated by github. If I knew how, I would simply forbid the tgz from appearing at all.

Unfortunately, I'm not aware of how to fix this problem. Perhaps @avsm knows?

**Comment by NathanReb** [comment]
Indeed `dune-release` builds and uploads the `.tbz` ones but as it currently does not call `dune subst` when building the archive the `%%VAR%%` aren't properly replaced. This is on my todo list of things I'm gonna fix before releasing a new `dune-release` version, hopefully by the end of the week!

**Comment by Zimmi48** [comment]
>If I knew how, I would simply forbid the tgz from appearing at all.

AFAIK this is not possible ATM.

Have you considered contacting GitHub support to request that?

**Comment by NathanReb** [comment]
Hmm yeah nevermind `dune-release` still uses its own custom watermarking so indeed the `.tbz` should be correct. Still would like to replace that and use `dune subst` instead.

**Comment by avsm** [comment]
Did you manually download and run the tgz archive @Zimmi48?  All package managers should be using the tbz version.

**Comment by Zimmi48** [comment]
Why are you asking me? I am not the one who opened the issue, and I know that it is the tbz version that should be used. The OP (@jfehrle) was confused that it was not equivalent to use the .tar.gz / .zip vs the .tbz, and that's why he opened the issue. But there's not much that can be done beyond contacting GitHub and requesting a way of disabling the automatic generation of tarballs...

**Comment by Zimmi48** [comment]
FTR the OP is not a package manager, but a Windows user.

**Comment by jfehrle** [comment]
> The OP (@jfehrle) was confused that it was not equivalent to use the .tar.gz / .zip vs the .tbz, and that's why he opened the issue.

Not confused at all--it is a bug.  They darn well should have identical contents or the .tar.gz shouldn't be shown.  I submitted a request to GitHub support.

**Comment by ejgallego** [comment]
TTOMK this has been fixed by having dune use build-build-info.
