### ISSUE TITLE
mark an installed lib file as executable

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#2198]
While porting ppx_tools to dune, I had to come up with a bit of a hack to support the `ocamlfind ppx_tools/rewriter` functionality.  This depends on having an executable file installed in `lib/ppx_tools/rewriter` so that its not in the full bin namespace.

Installing it via `(install (section lib))` fails at runtime since the files are not executable when installed.  I worked around it with:

https://github.com/dune-universe/ppx_tools/blob/to-dune/dune#L41

```
(install
 (section bin)
 (files
  (ppx_metaquot.exe as ../lib/ppx_tools/ppx_metaquot)
  (rewriter.exe as ../lib/ppx_tools/rewriter)
  (dumpast.exe as ../lib/ppx_tools/dumpast)
  (genlifter.exe as ../lib/ppx_tools/genlifter)))
```

which works but is a bit ugly, so opening this bug for some better way to express that files in `lib` can be executable.

**Comment by rgrinberg** [comment]
What about using the `libexec` field?

**Comment by avsm** [comment]
Wouldn't that go into the `libexec/` directory though, and still require the `../lib/`?  My understanding is that ocamlfind only looks in `lib/<pkg>` for the executed binary (but I might be misunderstand how that works -- it seems odd to look in lib/ for executables)

**Comment by diml** [comment]
The policy is the same as opam: the `libexec` is the same as the `lib` section except that files get their executable bit set

**Comment by avsm** [comment]
Thanks for the clarification. I've submitted a doc PR to close this in https://github.com/ocaml/dune/pull/2237 as it wasn't very clear to me before.  I'd also never seen the `misc` section in opam before, which might violate sandboxing...

**Comment by diml** [comment]
Thanks. Yh, I've never used `misc` either, not sure what it's meant for :confused:
