### ISSUE TITLE
way to optionally turn jbuild files into a hard failure

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#2199]
Dune is currently advertising that support for jbuild files will disappear in July 2019.

In Dune 1.10, it would be nice if there were a way to turn the presence of jbuild files into a hard failure, so that we could run some bulk builds and eliminate the last pesky ones with some `dune upgrade`s.  Perhaps just an environment variable `DUNE_DEPRECATE_JBUILD=1` or similar to toggle the behaviour of the future dune that enforces it by default when support for jbuild is actually removed.

**Comment by rgrinberg** [comment]
This seems useful but I'm wondering if this is a bit too specialized. What's going to happen to this feature once jbuild files are no longer relevant?

Instead, how about we introduce `DUNE_STRICT_MIN=x.y`. Dune will now error out if it encounters any features below this version.

I'm not sure that we introduced the deprecation of jbuild files at a particular version but we can always add that information back in.

**Comment by avsm** [comment]
I was just assuming DUNE_DEPRECATE_JBUILD would just be ignored in future releases. I very slightly prefer mine since it lets the user isolate a particular feature rather than all the changes that are deprecated.  However, your proposal would be easier to maintain in CI, so it's probably the one to go for...

**Comment by rgrinberg** [comment]
Closing as I don't even remember the last time I've seen a jbuild file :)
