### ISSUE TITLE
dune still uses ocamlc when using (modes native)

### ISSUE THREAD

**Issue by rnd4222** [ocaml/dune#2204]
Given the following build config:

```
(executable
  (name my-exe)
  (ocamlopt_flags (-warn-error -a))
  (ocamlc_flags (-warn-error -a))
  (modes native)
  (libraries unix))
```

dune still invokes `ocamlc`, so I'm forced to use ocamlc_flags setting even if I don't need bytecode version.

**Comment by nojb** [comment]
You could use `(flags -warn-error -a)` if you want to set flags common to both the bytecode and native compilers.

**Comment by rnd4222** [comment]
@nojb thanks, it works!
However, why `ocamlc` needed to compile native executable?

**Comment by nojb** [comment]
I haven't checked but `ocamlc` is probably used to compile the `.cmi` interface even when compiling for native code. It is simpler to have a uniform rule to produce `.cmi` files that does not depend if the file is used for bytecode or for native.

**Comment by rnd4222** [comment]
OK, makes sense. Thank you, I'm closing the issue.
