### ISSUE TITLE
Generated opam has no doc field

### ISSUE THREAD

**Issue by NathanReb** [ocaml/dune#2205]
Currently the opam generation doesn't add a `doc` field to the opam files and that doesn't cope well with `dune-release`. I think this needs to be fixed on both ends as one might decide not to publish documentation, in which case `dune-release` should skip documentation publication and linting.

I'd suggest the addition of a `doc` field in the `dune-project` so that one can manually set it if they wish thus allowing them to publish their documentation to `gh-pages` using `dune-release` and opam generation.

We could eventually make it default to `https://user.github.io/repo/doc` if `source` is `(github user/repo)` but I don't know if that's a good idea.

I'm happy to provide a PR!

**Comment by avsm** [comment]
I think it does if you provide a `(documentation "https://dune.readthedocs.io/")` field in dune-project.

**Comment by NathanReb** [comment]
I'll try that and if it indeed works I'll add a mention to that field in the documentation as I believe there currently isn't any.

**Comment by NathanReb** [comment]
Ok nevermind it is also documented, I was looking at an outdated PR diff.

Closing this!

**Comment by avsm** [comment]
Sounds good -- see here for why its not inferred by default (in case we want a centralised docs.ocaml.org in the future) https://github.com/ocaml/dune/pull/2154
