### ISSUE TITLE
Running a single test via `dune build @runtest`

### ISSUE THREAD

**Issue by sinancepel** [ocaml/dune#2210]
Is it possible to run a single test in dune? I find myself wanting this feature when I edit a library in my codebase that invalidates most of the project's tests. Right now, I rely on the following magic to run a single test:

```
$ cd $TEST_DIRECTORY
$ export test_file=`realpath myTest.ml`
$ cat "/dev/null" | dune utop . -- -init "${test_file}" | sed -e 's/\\n/\n/g'
```

Is there a better way of doing this in dune today? If not, this issue is a feature request :)

**Comment by rgrinberg** [comment]
You may run a particular test with:

```
$ dune exec ./path/to/test.exe
```

If you organized your test suite with directories, you may also run all tests in a directory with:

```
$ dune runtest dir/where/tests/for/lib/live
```

**Comment by jberdine** [comment]
For inline tests, there is also some functionality to run single tests, but it's hard to get to:
```
$ dune build _build/dev/.../dir/.dir.inline-tests/run.exe
$ _build/dev/.../dir/.dir.inline-tests/run.exe inline-test-runner dir -only-test file.ml:42
```
This appears to run the test on line 42 of dir/file.ml, presuming everything else is set up for inline tests, etc.

Maybe someone who knows more about editor interop knows a way to hook into this to enable users to ask for "this test the cursor is on" to be run.

**Comment by sinancepel** [comment]
Thanks, that works! Closing the issue. @rgrinberg would you mind if I added this documentation to `tests.rst`?

**Comment by diml** [comment]
Inside Jane Street, we generate a `runtest.sh` script for inline tests. Then one can do: `./runtest.sh -only-test file.ml:42`. We could do something similar here.

**Comment by mimoo** [comment]
I think this should be reopened. There should be a way to do this in a single command in dune :o `dune test some/path/ -only-test some_test`

**Comment by OlivierNicole** [comment]
I confirm that thous would be useful pretty often for me.

**Comment by Alizter** [comment]
Actually, would it be sensible for us to add inline tests names to aliases like we do for cram? @rgrinberg

**Comment by rgrinberg** [comment]
It wouldn't work very well. Because doing `dune build @runtest` followed by `dune build @test-name` would still re-run the individual test.

I'd rather just hack the `runtest` command to have non-build semantics.
