### ISSUE TITLE
Explicitly document how to pass arguments with jbuilder exec

### ISSUE THREAD

**Issue by rdavison** [ocaml/dune#227]
Referencing issue: https://github.com/janestreet/jbuilder/issues/225

I was not able to find any documentation regarding this feature.  Essentially, we just need to state that arguments can be passed to the app being executed by `jbuilder exec` by separating them with a double hyphen `--`

Example:
`jbuilder exec app.exe -- arg1 -flag1 --flag2`

**Comment by rgrinberg** [comment]
`$ jbuilder exec --help` mentions this form briefly. But I suppose this convention isn't as popular as I thought  it was. `$ jbuilder utop` should be documented similarly.

**Comment by jfehrle** [comment]
This needs to be documented clearly.  I had to email other developers to discover this feature.

Furthermore, the man page displayed by `dune` doesn't mention the existence of `dune exec --help` anywhere.  The `dune` output mentions `dune help`--which only has some IMO less-important options while not mentioning `dune exec --help` at all.

Thinking it might be analogous to `git`, I tried "dune help exec" which is not accepted.  (And just now I discovered that git supports `git <CMD> --help`.)

**Comment by diml** [comment]
Yes, we need to improve our man pages here. Here is a list of things that can be done:

- make the man page displayed by `dune` mention that all commands accept `--help`
- make `dune help <what>` support all commands in addition to specific topics
- add a custom synopsis to the man page of `dune exec` to display:

  ```
  dune exec [OPTIONS]... -- PROG [ARGS]
  ```

  rather than:

  ```
  dune exec [OPTIONS]... PROG [ARGS]
  ```

**Comment by diml** [comment]
@dbuenzli pointed to this code for the second point: https://github.com/dbuenzli/topkg/blob/master/src-bin/help.ml#L334-L377

**Comment by rgrinberg** [comment]
What would be the difference between `$ dune help foo` and `$ dune foo --help`?

**Comment by dbuenzli** [comment]
@rgrinberg, none. Two different ways of accessing the same thing.

**Comment by emillon** [comment]
Excerpts from the man page:

```
DESCRIPTION
       dune exec -- COMMAND should behave in the same way as if you do:

         $ dune install
         $ COMMAND
```

```
EXAMPLES
       1.  Run the executable named `my_exec':

             dune exec my_exec

       2.  Run the executable defined in `foo.ml' with the argument `arg':

             dune exec -- ./foo.exe arg
```

The latter has been added in #3089. This seems good enough to close this issue. Thanks.
