### ISSUE TITLE
`dune build @doc` does nothing

### ISSUE THREAD

**Issue by TyOverby** [ocaml/dune#2284]
After installing odoc

```
$ opam install odoc
[.......]
$ eval $(opam env)
[.......]
$ odoc --version
1.4.0
```

I expected `dune build @doc` to do something, but it returns an exit code of `0` without having produced any documentation.  I tried running this command both at the project root (next to the `dune_project`) file, as well as at the library level (next to the `dune` file)

**Comment by ejgallego** [comment]
Do you have any public libraries? If not, you should use the `@doc-private` alias.

**Comment by TyOverby** [comment]
Hmm, I guess I thought my libraries were public but I guess they weren't.  Ah, looks like that's tied to opam?

**Comment by ejgallego** [comment]
> looks like that's tied to opam

A library is public if the stanza defining it has a `public_name` field.
