### ISSUE TITLE
opam does not list a local project installed by dune

### ISSUE THREAD

**Issue by nilsbecker** [ocaml/dune#2287]
i have a small local project which defines one public executable and no library. i can autogenerate an opam file for it using this `dune-project`:
```
(lang dune 1.10)
(generate_opam_files true)
	(package 
	 (name "extract_codes")
	 (synopsis "bla")
	 (description "bla bla")
	 (depends 
		(gen (> 0.5))
		(containers (>= 2.5 ))
		(yojson (>= 1.7.0))
		(csv (>= 2.2))))
```
i then do `dune build extract_codes.exe && dune install` which installs the executable in my opam switch. the autogenerated opam file is not copied to the opam switch; only a META file and a dune-package file exist there. `opam list` does not list my package, which i find odd. is this intended?

**Comment by rgrinberg** [comment]
Yes. You still need to check in and commit your opam generated file. Opam isn't yet ready to deal with auto-generated opam files.

**Comment by nilsbecker** [comment]
i'm not sure i understand fully. does `dune install` use git? it's true that my project is under git versioning, but i did not expect this to interact with dune

**Comment by nilsbecker** [comment]
(also, the autogenerated .opam file is indeed not checked into git)

**Comment by nilsbecker** [comment]
i tried it out. after checking the opam file into git, i did `dune clean && dune build extract_codes.exe && dune install`. i got asked to do `dune build @install instead`. i did that and then `dune install`. this copied an opam file into the opam switch (because of git?). 
anyway, `opam list` still did not list the package. the opam file in the opam switch is pretty minimal. it looks like this:
```
opam-version: "2.0"
build: [
  ["dune" "subst"] {pinned}
  ["dune" "build" "-p" name "-j" jobs]
  ["dune" "runtest" "-p" name "-j" jobs] {with-test}
  ["dune" "build" "-p" name "@doc"] {with-doc}
]
synopsis: "Polylox code parsing"
description:
  "A program that parses snapshot json files generated by Kappa for the Polylox system and outputs the number and letter-number-notation of the barcodes contained in the configuration"
depends: [
  "gen" {> "0.5"}
  "containers" {>= "2.5"}
  "yojson" {>= "1.7.0"}
  "csv" {>= "2.2"}
]
```

**Comment by nilsbecker** [comment]
i now tried a different route. instead of `dune install` i tried `opam pin add .` there i can understand that it depends on git, since opam adds the packages as `git+file` source. 

anyway, after adding a `maintainers` field, my dune-project is now this:
```
(lang dune 1.10)
(generate_opam_files true)

	(maintainers "nils@localhost")
	(package
	 (name "extract_codes")
	 (synopsis "bla")
	 (description "bla bla")
	 (depends
		(gen (> 0.5))
		(containers (>= 2.5 ))
		(yojson (>= 1.7.0))
		(csv (>= 2.2))))
```
however on opam installation, i get an error complaining that the project name is undefined. indeed the opam file in the source tree does not contain a name field although the dune-project does. i suspect there is an error in the opam file autogeneration?
```
# This file is generated by dune, edit dune-project instead
opam-version: "2.0"
build: [
  ["dune" "subst"] {pinned}
  ["dune" "build" "-p" name "-j" jobs]
  ["dune" "runtest" "-p" name "-j" jobs] {with-test}
  ["dune" "build" "-p" name "@doc"] {with-doc}
]
maintainer: ["nils@localhost"]
synopsis: "bla"
description: "bla bla"
depends: [
  "gen" {> "0.5"}
  "containers" {>= "2.5"}
  "yojson" {>= "1.7.0"}
  "csv" {>= "2.2"}
]
```
(this is the generated opam file)

**Comment by rgrinberg** [comment]
> however on opam installation, i get an error complaining that the project name is undefined. indeed the opam file in the source tree does not contain a name field although the dune-project does. i suspect there is an error in the opam file autogeneration?

The project name is something that only dune knows about. It seems like your dune-project file is missing a `name` field. You should probably add that.

Perhaps we should make it an error to turn on `(generated_opam_files true)` without such a `name` field however? Since the build instructions do rely on this.

**Comment by nilsbecker** [comment]
my dune-project file is exactly the one in my previous post. it contains a `name` field within the `package` field, just as described in the docs. i tried to add a `name` field outside of `package` but that is rejected.

**Comment by rgrinberg** [comment]
It should certainly not be rejected. A project name can be set with `(name ..)` in the toplevel. See dune's dune-project file for example.

**Comment by nilsbecker** [comment]
hmm. i'll check again -- i might have misremembered and actually something else was rejected. but i agree, it would be more foolproof to fail early if the generated opam file would be in some way broken/insufficient.

**Comment by nilsbecker** [comment]
ok, now i included a name field in dune-project. i deleted the old opam file. i then did `dune clean && dune install @build` which regenerated an opam file, but again without a name field. here are the files:

dune-project
```
(lang dune 1.10)
(generate_opam_files true)

	(name "extract_codes")
	(maintainers "nils@localhost")
	(package
	 (name "extract_codes")
	 (synopsis "bla")
	 (description "bla bla")
	 (depends
		(gen (> 0.5))
		(containers (>= 2.5 ))
		(yojson (>= 1.7.0))
		(csv (>= 2.2))))
```

opam file
```
# This file is generated by dune, edit dune-project instead
opam-version: "2.0"
build: [
  ["dune" "subst"] {pinned}
  ["dune" "build" "-p" name "-j" jobs]
  ["dune" "runtest" "-p" name "-j" jobs] {with-test}
  ["dune" "build" "-p" name "@doc"] {with-doc}
]
maintainer: ["nils@localhost"]
synopsis: "bla"
description: "bla bla"
depends: [
  "gen" {> "0.5"}
  "containers" {>= "2.5"}
  "yojson" {>= "1.7.0"}
  "csv" {>= "2.2"}
]
```

**Comment by rgrinberg** [comment]
Your project file still doesn't have a name field for the project.

**Comment by rgrinberg** [comment]
That looks right to me. There's no need for a name field in the opam file.

The name is inferred from the filename of the opam file.

**Comment by nilsbecker** [comment]
ah ok -- indeed it finally works now: 

`git commit -a`
`opam pin add `
installs a properly named package, which is also listed by `opam list`.

however, `dune install` does not do this -- it copies the executable to the opam switch, but opam is not aware of the existence of the package. i guess this is intended. however, i find it slightly confusing that `dune install` uses the opam directory structure but does not actually otherwise do things the opam way. i concede that this is explained in the dune docs -- but maybe it would make sense to issue a warning in the case `dune install` uses a prefix that is an opam switch, something like "warning: installing into opam switch without creating an opam package" ?

**Comment by ejgallego** [comment]
I think we can close this issue, indeed the current workflow could be improved but would require non-trivial integration.
