### ISSUE TITLE
opam file generation: dune constraint should fill in the version based on dune-project

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#2289]
Noticed this while porting some projects to dune 1.10. With a dune-project like:

```
(lang dune 1.10)

(package
 (name github-unix)
 (depends
  (ocaml (>= 4.03.0))
  dune
  <...>
```

The opam file generated has:

```
depends: [ "dune" ]
```

It should instead have:

```
depends: [ "dune" {>="1.10"} ]
```

based on the `lang 1.10` stanza in dune-project

**Comment by avsm** [comment]
Or thinking about it more, the `dune` entry should be mandatory and inserted by default. The user shouldn't need to have to specify the `dune` dependency in a `dune-project` at all...

**Comment by diml** [comment]
That's too good points
