### ISSUE TITLE
opam file generation: normalise resulting opam file

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#2290]
When generating opam files via dune-project, there's a big diff between the default order of opam fields generated by dune and those normalised by `opam lint <file> --normalise`

This is a minor hassle since the submitted version in dune-release could be run through `opam lint` before generating the release archive.  But if it's easy with the existing opam libraries vendored in dune, it would be nice to have the generated order match the opam linted field order.

**Comment by diml** [comment]
Let's just hard-code the right order. I suppose it's not changing very often.
