### ISSUE TITLE
Add name mangling to dune binaries

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#2292]
Any of the executable's compilation units might conflict with some compilation unit from a transitive dependency. This can cause unpredictable failures when some library used by the executable introduces a new dependency with the same name as one of the executable's modules.

This is quite easily fixed by applying a name mangling scheme to the executable's modules. The only downsides of doing this change is that it will make using gdb slightly harder.

This mode will become the default for 2.0

@diml how should we calculate the name mangling prefix? I think that just using the executable's name is suboptimal as it might be a common name. Should we calculate some digest perhaps?

**Comment by diml** [comment]
I suppose we could use the digest of the list of names. BTW, to be conservative, we should tie that fact to `(lang dune x.y)` and enable name mangling by default with lang dune >= 2.0

**Comment by rgrinberg** [comment]
We went for a much simpler mangling scheme. By the way, this feature can also be turned on/off explicitly per project with `(wrapped_exes ..)`.

**Comment by rgrinberg** [comment]
Fixed
