### ISSUE TITLE
[ci] Testing the build with OCaml `trunk`

### ISSUE THREAD

**Issue by ejgallego** [ocaml/dune#2298]
As discussed in #2296 it could be interesting to have a [soft, as in allowed to fail] CI job that tries to compile with Dune with OCaml's trunk.

It could be argued that this should be the responsibility of OCaml's CI itself, but for now we can add it here.

This kind of testing is not very stable but in Coq we have found it to be quite useful.

**Comment by diml** [comment]
Ideally you want both so that none of the compiler or dune can break each other's CI. In particular, if we had both we could safely make it a hard requirement on both.

Having it in Dune only as a soft failure seems like a good first step indeed.

**Comment by Alizter** [comment]
@rgrinberg Do you think this is still worth perusing? It doesn't seem very likely that OCaml upstream will break Dune.

**Comment by rgrinberg** [comment]
I think so.
