### ISSUE TITLE
Differentiating between mac and unix in dune files

### ISSUE THREAD

**Issue by leamingrad** [ocaml/dune#2310]
### Short Version

Is there a recommended way of differentiating between mac OSX and other unix OSs when using and `enabled_if` stanza in dune files?

### Details

For the testing of `terminal_size` I need to use an intercept library to modify the return value of a few C system calls. Unfortunately, the mechanism for doing so is different on OSX to other unix OSs. In particular, on OSX I need to compile my library using the `-dynamiclib` flag, which is mac-os specific.

I am trying to create two rules for the OSX intercept library - once that is used on mac and actually compiles it, and one that is used everywhere else and does nothing.

The full dune file is [here](https://github.com/cryptosense/terminal_size/blob/master/test/dune), but the key stanzas I have used are as follows:

```
(rule
  (targets libmock_ioctl.dylib)
  (enabled_if (= %{os_type} macosx))
  (action (run %{cc} -dynamiclib -o %{targets} %{dep:mock_ioctl_mac.c}))
)

(rule
  (targets libmock_ioctl.dylib)
  (enabled_if (<> %{os_type} macosx))
  (action (write-file %{targets} ""))
)
```

I also tried to use the `%{ocamlc-config:system}` macro, but that does not seem to be allowed in `enabled_if` stanzas.

Is there a recommended way of marking a target as only being compilable on OSX? Alternatively, is there a way to mark a target as optional so that dune will try and compile it but carry on if compilation fails?

### Version Information

I'm happy to provide more info here, but the basic details are as follows:

* `dune`: 1.10.0
* `ocaml`: 4.07.1
* OSX: Mohave 10.14.4

**Comment by rgrinberg** [comment]
There's no way to make a target optional. However, you can make dependencies optional. Would it be possible for you to always setup the target, but only use it conditionally?

**Comment by leamingrad** [comment]
Apologies if the following is wrong: I don't completely understand the difference between dependencies and targets.

The only place that the offending dll is used as a dependency is in the following test stanza action:

```
(test
  (name testsuite)
  ...
  (action
    (setenv LD_PRELOAD ./%{dep:dllmock_ioctl.so}
      (setenv DYLD_INSERT_LIBRARIES ./%{dep:libmock_ioctl.dylib}
        (run %{test})
      )
    )
  )
)
```

Since I don't care about setting `DYLD_INSERT_LIBRARIES` on platforms that are not osx, I would be more than happy to make that conditional - but I couldn't see a way to do that from the documentation. If I was somehow able to make it conditional, would the rule to generate it not be triggered?

**Comment by rgrinberg** [comment]
> Apologies if the following is wrong: I don't completely understand the difference between dependencies and targets.

Every rule has a set of dependencies and a set of targets. Dependencies must be produced and up to date before a rule is executed by dune to produce targets. Simple user rules are a good demonstration of this:

```
(rule
 (deps foo.exe) ;; the rule requires this binary
 (targets bar) ;; and produces this file
 (action (bash "%{deps) > %{targets}"))) ;; using the stdout
```

Dune usually infers dependencies & targets from the actions themselves. So specifying things so manually isn't necessary.

>  If I was somehow able to make it conditional, would the rule to generate it not be triggered?

Yes, rules are only executed when they are necessary to build targets

The simplest way I think is to push the logic for executing your tests into a custom script. But that doesn't help you with specifying your dependencies correctly. The power that is missing is the ability to add conditional dependencies to your test rule. This is something that is usable in dune internally, but isn't exposed to the user. We'll have to ask @diml what's the best way to proceed here.

**Comment by diml** [comment]
`system` seems like a safe variable to allow in `enabled_if` stanzas. We can add a variable `system` that is equal to `ocaml-config:system` and allow it in `enabled_if` stanzas

**Comment by rgrinberg** [comment]
Yeah, this should be safe. The only problematic variables should be ones that require us to build the compiler to generate. As we'd like to include the compiler itself in composable builds one day.

**Comment by rgrinberg** [comment]
I just had another look, and we already support `system` as a variable in `enabled_if`. What is missing is `os_type`.

**Comment by leamingrad** [comment]
I've probably missed something, but I think `os_type` is already available as I was able to use it. Changing to `system` also seems to work - although I need to check that it can correctly test for osx.

Are the available placeholders documented somewhere - if not, then I'm happy to add the documentation if someone can point me to the right place to add it.

**Comment by emillon** [comment]
It's been a few years, but given that `%{os_type}` and `%{system}` are supported in `enabled_if`, I don't think there's anything more to do here.
