### ISSUE TITLE
dune 2: set up formatting rules by default

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#2315]
Hi,

Currently formatting rules is opt-in and set up using an extension (`(using fmt)`). For `(lang 2.0)` I suggest that we:

- set up these aliases by default
- add a `(formatting)` stanza containing current options passed in `(using fmt)`, as well as future ones (paths to binaries, excludes...), and a way to opt out of autoformatting

**Comment by rgrinberg** [comment]
Fine by me. However, can we first turn this feature on for dune itself? This is something that we've done implicit transitive deps before promoting them to be the default.

**Comment by diml** [comment]
Fine by me as well

**Comment by emillon** [comment]
As described in #2315, once we have (formatting) we should have a way to override paths to formatting binaries. This might be a workspace option.

**Comment by rgrinberg** [comment]
This is done.
