### ISSUE TITLE
Relax quoting rule for atoms beginning /

### ISSUE THREAD

**Issue by dra27** [ocaml/dune#2321]
Context:

```
File "_build/default/src/cxxflags.sexp", line 1, characters 1-6:
1 | (/EHsc -DUSEGLPK)
     ^^^^^
Error: This atom must be quoted because it is the first element of a list and doesn't start with - or :
Command exited with code 1
```

In theory, is there any reason why `/`, as the flag prefix on Windows, couldn't be one of the allowed unquoted characters? In that particular case, it can be changed to `-`, but that's not universally true for Windows command line utils (in fact, in general, it's not the case)

**Comment by rgrinberg** [comment]
> , but that's not universally true for Windows command line utils (in fact, in general, it's not the case)

Quoting is still available however.

I don't immediately see any issues with making `/` an allowed character for atoms.

**Comment by diml** [comment]
Note that `Configurator.V1.Flags.write_sexp` uses quoted strings systematically to avoid this problem. I'd suggest to use this function to write the sexp file.

**Comment by dra27** [comment]
OK, though it could just as easily be written by hand in a `dune` file (it's a `cflags` field) - but I'll amend that particular case to use `write_sexp`, thanks!

**Comment by emillon** [comment]
I'll close this one as the right solution is to either follow the hint, or use `write_sexp`. Thanks!
