### ISSUE TITLE
dune utop fails with multiple virtual module implementations

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#2323]
In a similar vein to #2322, `dune utop` hits a conflict when there are multiple implementations of the same virtual module in a repository.  Perhaps the default_implementation could be used and the other virtual modules deselected from the toplevel?

```
$ dune utop
Error: Conflicting implementations for virtual library "io-page":
- "io-page-xen" in _build/default/lib/xen
- "io-page-unix" in _build/default/lib/unix
```

PR for io-page that shows this problem:
mirage/io-page#59

**Comment by rgrinberg** [comment]
Yes, this was one one of the motivations fort the default implementations fields. @TheLortex do you want to give this a stab?

**Comment by TheLortex** [comment]
https://github.com/ocaml/dune/blob/master/src/utop.ml#L65-L70
Indeed for now `dune utop` doesn't know anything about default implementations and just selects all libs in the workspace
