### ISSUE TITLE
opam pin dune fails as dune.install is not promoted

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#2329]
Since c691a79d4e559a0b2df15046418bc37ea22a3aa0 the `opam pin add dune --dev` fails since the build doesn't promote `_boot/dune.install` to the main source tree.

**Comment by rgrinberg** [comment]
When you install a pinned package, doesn't that use `-p`? If it does, the .install files should still be promoted. A little more investigation is needed here.

**Comment by rgrinberg** [comment]
Fixed now. The issue was the broken bootstrapped dune.
