### ISSUE TITLE
Aliases in the install directory no longer work

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#2337]
Being able to build aliases in the install directory is quite useful. For example: `$ dune build @_build/install/default/bin/all`.

@aalekseyev do you mind having a look at this?

**Comment by aalekseyev** [comment]
Ok, I'll have a look.

**Comment by aalekseyev** [comment]
Did it ever work though? I seem to track the ancestry of the check that's failing through to 2018-01: 

f3738e8b7370f941bfbf3fcc98e04fcc8cdb4aec
6f59380bf
2549ab09419c1ee069fc8c724053a62361b97edb
30db63ef7
25c34c222
9dd5ab74e

The error message explicitly says that there're no aliases in install directory.

**Comment by rgrinberg** [comment]
Yeah, I guess so. I suppose it would be nice to have, so let's just leave it as an enhancement.

**Comment by diml** [comment]
Indeed, it intentionally never worked. I missed the part about `_build/install` when I read the question on slack. I thought it was all aliases pointing to `_build/<context-name>` that were broken somehow.

For this particular subject, I don't think it's worth complexifying the system to add support for aliases in the install directory. Right now, it's nice that aliases are always attached to a source tree in one way or another.

However, we could certainly extend what is supported on the command line, for instance to allows things of the form:

```
$ dune build '(glob_files _build/install/lib/foo/*.cmx)'
```

That should gives the same benefit.
