### ISSUE TITLE
Remove the last remnants of Sexp

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#2338]
The last use case for the old `Sexp` module is integration with janestreet's internal release tooling. It would be nice to get rid of this and just use Dyn or Dune_lang for this.

**Comment by diml** [comment]
Indeed, we should be able to use `Dune_lang` directly. I'll have a look

**Comment by rgrinberg** [comment]
We now have a Csexp library. So sexps aren't going away after all.
