### ISSUE TITLE
Dune crashes because of erroneous hardcoded path

### ISSUE THREAD

**Issue by vsiles** [ocaml/dune#2359]
I build a dune binary in a sandbox, which lead to some hardcoded paths inside the binary that are no longer relevant at runtime. While this is a problem on my own, dune is crashing because of that, where it could (I think) use the current opam setup to recover. Here is the kind of error messages I get:
```
dune build @all
Error: exception Sys_error("/path/to/build/sandbox/dotopam/default/lib/ocaml/Makefile.config: No such file or directory")
Backtrace:
Raised by primitive operation at file "pervasives.ml", line 385, characters 28-54
Called from file "src/stdune/io.ml", line 74, characters 17-37
Called from file "src/stdune/io.ml" (inlined), line 96, characters 25-69
Called from file "src/ocaml-config/ocaml_config.ml", line 236, characters 16-37
Called from file "src/ocaml-config/ocaml_config.ml", line 411, characters 15-45
Called from file "src/context.ml", line 351, characters 27-49
Called from file "src/fiber/fiber.ml", line 201, characters 18-23
Called from file "src/fiber/fiber.ml", line 99, characters 6-13
 
I must not segfault.  Uncertainty is the mind-killer.  Exceptions are
the little-death that brings total obliteration.  I will fully express
my cases.  Execution will pass over me and through me.  And when it
has gone past, I will unwind the stack along its path.  Where the
cases are handled there will be nothing.  Only I will remain.```

**Comment by diml** [comment]
Dune doesn't hardcode this path, it obtains it by calling `ocamlc -config` and looking for the `standard_library` key in its output. The compiler however does hardcode this path, did you build the compiler as well in a sandbox?

**Comment by vsiles** [comment]
I'll trust you on that (`strings` returns some hardcoded path to the sandbox opam, but maybe they are not to blame here).  Yes, the compiler is built in the same sandbox (with the rest of the opam switch).

**Comment by diml** [comment]
> strings returns some hardcoded path to the sandbox opam, but maybe they are not to blame here

Normally, the only path we hardcode is the library directory when building with opam < 2 (as per the first line of the build instructions in `dune.opam`). Other paths pointing to the sandbox might be debug info or similar things that are not under Dune's control.

> Yes, the compiler is built in the same sandbox (with the rest of the opam switch).

That's the issue then. The OCaml compiler is currently not relocatable.

**Comment by vsiles** [comment]
Thanks for all the info. I'll close the issue since it's not directly dune related.
