### ISSUE TITLE
colored output for diff action

### ISSUE THREAD

**Issue by vogler** [ocaml/dune#2381]
Without `patdiff` installed, the output of diff actions is not colored.
Running tests with `dune runtest --diff-command='diff -u --color=always'` gives me colored output, where `--color=auto` (default) does not.
I guess making the default `--diff-command` include `--color=always` is not viable if the output should be processed further. What's the reason for `--color=auto` not working as expected?

Usage:
~~~
(alias
 (name runtest)
 (action
  (progn
    (diff %{dep:empty.c.expected} %{dep:empty.c.output})
    (diff %{dep:array.c.expected} %{dep:array.c.output}))))
~~~

~~~
❯ dune --version
1.10.0
~~~

**Comment by diml** [comment]
It is because `diff --color=auto` only outputs colors if the output is a tty and this is not the case here because dune redirects the output of commands it runs. It does so to avoid the output of commands run in parallel from being interleaved.

Since dune is able to understand colors in the ouptut of commands and strip if its own output is not a tty, it would be safe to systematically pass `--color=always` in Dune. However, do you know how portable this option is? Is at accepted by default on all systems (Linux, BSD, OSX, ...)?

**Comment by nojb** [comment]
Things may have changed, but if memory serves OS X's diff does not do `--color`.

A more portable alternative may be `git diff --no-index`.

**Comment by diml** [comment]
Ok, I guess we can do the following then:

- use patdiff if available
- otherwise use `git diff --no-index` if git is available
- otherwise use `diff -u`

**Comment by vogler** [comment]
> Things may have changed, but if memory serves OS X's diff does not do `--color`.
> 
> A more portable alternative may be `git diff --no-index`.

Can confirm:
~~~
❯ /usr/local/bin/diff --version    # has --color; via brew
diff (GNU diffutils) 3.7
❯ /usr/bin/diff --version          # no --color
diff (GNU diffutils) 2.8.1
~~~

Maybe check with `diff --help | grep 'color.*always'` if the option is available since it fails if it's not:
~~~
❯ /usr/bin/diff --color=always <(echo foo) <(echo bar)
/usr/bin/diff: unrecognized option `--color=always'
~~~

**Comment by diml** [comment]
Grepping the output of `diff --help` feels a bit overkill. Since `git diff --color=always --no-index` does the job in a portable way, let's go for that. @vogler or @nojb, does one of you want to give it a go? The code to modify is the local function `normal_diff` in `src/print_diff.ml`.

**Comment by vogler** [comment]
![image](https://user-images.githubusercontent.com/493741/60905277-0200f000-a275-11e9-9334-b41c692da3de.png)
Just using `git diff` with colors in `normal_diff` does not help.
Seems like the `Process.run` for `diff_command` uses a shell which makes the colors work.

**Comment by vogler** [comment]
> Seems like the Process.run for diff_command uses a shell which makes the colors work.

Just tried. That also doesn't make a difference.
