### ISSUE TITLE
install executable and library as part of a package?

### ISSUE THREAD

**Issue by houndofsound** [ocaml/dune#2386]
my package is a library with a ppx extension.
the docs say use public_name for each installable bit.
doing so gets a 'scope doesn't define ...' error
meaning it needs another .opam file.

the project has two pieces, it doesn't seem natural to
create two opam packages and make one dependent on the other.
is there another way to do this?

**Comment by diml** [comment]
You can put both piece in the same package. Simply add a `<package>.opam` file, or if you are using dune >= 1.10 you can also define the package via a `(package ...)` stanza in the `dune-project` file. Then you can add both pieces to this package. This is descibed in the (development version) of the documentation: https://dune.readthedocs.io/en/latest/installation.html

**Comment by houndofsound** [comment]
thanks.
is it correct to say the package stanza is not part of dune 1.9.3 ?
(I get an 'unknown field' error)

**Comment by diml** [comment]
Yep, that's correct
