### ISSUE TITLE
dune-project multiple packages?

### ISSUE THREAD

**Issue by houndofsound** [ocaml/dune#2387]
under the "dune files" part of the manual:

"The package name must be one of the packages that dune knows about, as determined by the dune-project files."

the docs on the dune-project file say nothing about this.

**Comment by diml** [comment]
In the development version of the manual, there is a new page about this: https://dune.readthedocs.io/en/latest/installation.html.

I'm closing this issue as I believe this page answers this question. Feel to re-open it if it's not clear
