### ISSUE TITLE
Future syntax?

### ISSUE THREAD

**Issue by houndofsound** [ocaml/dune#2388]
the section on this contains no information as to what, exactly,  can be specified.

**Comment by diml** [comment]
Indeed, the manual could be improved in this regard. At the moment, the only syntax is backported is the custom `let` operator syntax (`let+`, `and*`, ...). There is no plan to support more. However, starting from dune 2, `future_syntax` will be extracted from dune and maintained as a separate project. At this point, it will be able to evolve on its own and backport more things.
