### ISSUE TITLE
ppx extension built in bytecode?

### ISSUE THREAD

**Issue by houndofsound** [ocaml/dune#2393]
I tried adding
(modes byte)
to force a non-opt compilation (to speed things up)
but it still fails looking for .a and .cmxa of the extension.
any other to get a ppx executable built in bytecode?

**Comment by rgrinberg** [comment]
There's no way to instruct dune to build the ppx in bytecode mode. Is there a reason why you'd want this? It's unlikely to speed up your build as the ppx is going to preprocess your code slower in byte mode.

**Comment by houndofsound** [comment]
my system is a raspberry pi and waiting for the optimizing compiler is painful
in developing a trivial ppx extension. The preprocessing time is
unimportant during
development.
I think it's to do with core/base. I have previously had occasion to
cut dune out of the loop for compiling a small amount of ecaml code by
paring down the arguments to the
link stage, with good results.
and there's a big difference between byte and native.

**Comment by diml** [comment]
Note that if you don't have `ocamlopt` available, everything will be built in bytecode.

**Comment by progman1** [comment]
thanks, I'll try that.
