### ISSUE TITLE
dune exec ./hello_world.exe ?

### ISSUE THREAD

**Issue by houndofsound** [ocaml/dune#2400]
so unix convention is to prefix with ./  in order to get an executable in the current
directory to run as opposed to some random executable in the path.

does dune have this problem?
no
so what is the point of __requiring__ this?
if it wasn't for the quickstart of the manual I would still be randomly trying
various command lines to persuade dune to cooperate.

it's meaningless in the context of running the dune cmd and, worse still, counter-intuitive hence confusing/unguessable ... and not the first time it has happened in trying to get to grips with dune (yes, it is more difficult to work with than you probably realise!)

**Comment by houndofsound** [comment]
the confusion:
dune build hello_world.exe
as contrasted with
dune exec ./hello_world.exe

**Comment by rgrinberg** [comment]
Consider the case when there are two binaries in your project:

* foo.exe which is public
* foo.exe which is private but is in your project's root

which binary should `$ dune exec foo.exe` execute?

Dune should probably give a better error, as it can detect when `foo.exe` really means `./foo.exe`.
