### ISSUE TITLE
(modes native) but byte compiler invoked ?

### ISSUE THREAD

**Issue by progman1** [ocaml/dune#2405]
with the following stanza 
(executable
 (name test)
 (modules test)
 (modes native)
 (flags (-plugin dyn.cma))
 (libraries compiler-libs.common libdyn)
)

dune tries to compile with the byte compiler even though (modes native) is specified and the ocamlopt binary is available. the dependent library libdyn is also (modes native) but gets done with ocamlopt.

the error output is:
(cd _build/default && /home/dev/.opam/default/bin/ocamlc.opt -plugin dyn.cma -g -bin-annot -I .test.eobjs/byte -I /home/dev/.opam/default/lib/ocaml/compiler-libs -I .libdyn.objs/byte -I .libdyn.objs/native -I .dyn.objs/byte -I .dyn.objs/native -no-alias-deps -opaque -o .test.eobjs/byte/test.cmo -c -impl test.ml)

Fatal error: exception File "bytecomp/translobj.ml", line 114, characters 2-8: Assertion failed

and this assertion is related to flambda being configured! (no flambda here)

I'm avoiding byte compilation because it seems to not work for -plugin (another compiler assertion)

**Comment by progman1** [comment]
partially my bad!
at the beginning I had to set Clflags.native to true even though running a native compiler.
taking it out and things start moving again!
but....
using (flags (-plugin dyn.cma)) doesn't make dyn.cma a dependency and so when dune chooses to use
ocamlc.opt it doesn't know to build the dym.cmxs version.
is there a way to create this dependency in v1.9.3?

**Comment by nojb** [comment]
This would require special support from `dune`, and it is unlikely it will be added given that plugin support has been removed from the compiler starting in 4.09 (as has been mentioned in https://github.com/ocaml/ocaml/issues/8801).

**Comment by progman1** [comment]
relatedly, why does dune build a.cma only cause b.cmo to be produced and not b.cma?

(library
 (name a)
 (modules a)
 (libraries b)
)

(library
 (name b)
 (modules b)
)

**Comment by progman1** [comment]
removed?  that's tragic!!

**Comment by diml** [comment]
Because you don't need `b.cma` to build `a.cma`. You only need both if you link an executable. You might be interested in the `@all` alias that will build everything that's declared.

**Comment by progman1** [comment]
thanks again.
