### ISSUE TITLE
Warning 66 should be disabled

### ISSUE THREAD

**Issue by bcc32** [ocaml/dune#2410]
In 4.08.0, warning 66 alerts the user of unused `open!` statements.  It is disabled by default, but dune re-enables it because it uses `-w @a-...` syntax.  I think dune should disable this warning by default.

For reference, 4.08's default set of warnings is:

> The default setting is `-w +a-4-6-7-9-27-29-32..42-44-45-48-50-60`. It is displayed by `ocamlc -help`. Note that warnings 5 and 10 are not always triggered, depending on the internals of the type checker.

**Comment by rgrinberg** [comment]
Actually, we disabled this warning for projects using dune lang >= 1.11. But your comment made me realize that the way dune sets warning is a bit flawed. Ideally, we should use a stable set of warnings for every version of OCaml and for every version of the dune language. To do that, we can't really use `+a`. Let's see what @diml has to say.

**Comment by bcc32** [comment]
> dune lang >= 1.11

Ah, good to know.  Is there a quick reference of the changes between the dune lang versions?

**Comment by diml** [comment]
@rgrinberg indeed. Using `+a` is not really a good idea. I initially copy&pasted that from the Jane Street jenga rules. It made sense inside Jane Street at the time, but it's clearly not the right setting for Dune. Instead, we should have an explicit list of enabled warnings and this list should be tied to the dune language version.

To start with, we can look at what `+a` means in 4.07 and write this list explicitly in Dune, minus the ones we disable explicitly. I had a look in the OCaml source code and in 4.07, warnings go from 1 to 62, so the default setting should be: `@1@2@3@5@...@62`.

**Comment by diml** [comment]
> Ah, good to know. Is there a quick reference of the changes between the dune lang versions?

Currently it's only in the source code, but it seems like something that should be in the manual as well.

**Comment by rgrinberg** [comment]
@diml so just to confirm, we should really disable `-66` for all versions of dune. Since it should have never been enabled by accident.

**Comment by diml** [comment]
Yes

**Comment by hhugo** [comment]
Is this resolved in dune.1.11 ?

**Comment by rgrinberg** [comment]
Indeed it is.
