### ISSUE TITLE
[RFC] notation for compilation artifacts

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#2416]
Having a notation for compilation artifacts keeps coming up, but no suitable high-level design has been found yet.

I am thinking of a low-level approach that would serve this purpose, meant for "advanced" users:

```
- %{cmo:MOD}, %{cmx:MOD}, %{cmi:MOD}, %{cmt:MOD}, %{cmti:MOD}
- %{cmo:LIB:MOD}, %{cmx:LIB:MOD}, %{cmi:LIB:MOD}, %{cmt:LIB:MOD}, %{cmti:LIB:MOD}
- %{cma:LIB}, %{cmxa:LIB}
```
- `MOD` is a module name (not a file name, so without any potential prefix) and `LIB` is a library name.

- The `MOD` variables are scoped similarly to modules, i.e. one can only use them in a `dune` file where the modules is found.

- The `LIB:MOD` variables are scoped similarly to **public** modules and they can be used anywhere in the project scope. If the library is public they can also be used in the workspace scope.

- Similarly, the `LIB` variables can be used anywhere in the project scope. If the library is public they can be used in the workspace scope.

Finally the same mechanism can be used to implement virtual targets: doing `dune build MOD.EXT` would be equivalent to doing `dune build %{EXT:MOD}`, etc.

What do you think?

**Comment by diml** [comment]
That seems fine to me, I'm in favour of this proposal.

**Comment by rgrinberg** [comment]
That sounds fine to me, but I would suggest to use `MOD:EXT` for the command line. Then this proposal can be part of other higher level targets that we may add (that don't necessarily correspond to files).

**Comment by diml** [comment]
Your suggestion seems good to me. The `:` would indicate that we are doing something special, i.e. not just referencing a target directly. Pushing the idea a bit more, what about keeping the same order as inside the percent form? i.e. `dune build EXT:MOD`?

And thinking about this more, maybe we should start with just `dune build %{EXT:MOD}`. At least, it will be in line with what's available in dune files. This feature is supposed to be for advanced users anyway, so it doesn't seem to bad if it's a bit more verbose.

As a related noted, I was wondering about extending the command line to accept the same syntax as `deps` field. I.e. allow things like this: `dune build '(glob_files *.x)'`

**Comment by nojb** [comment]
Thanks for the feedback, happy to see consensus! I agree with using dune notation for virtual targets.

**Comment by rgrinberg** [comment]
> And thinking about this more, maybe we should start with just dune build %{EXT:MOD}. At least, it will be in line with what's available in dune files. This feature is supposed to be for advanced users anyway, so it doesn't seem to bad if it's a bit more verbose.

It's quite annoying to type curly braces in the shell however. They must be escaped in the fish shell for example.

**Comment by diml** [comment]
Yh that's true. However, it's not clear we'll need to do that very often. I expect that users generally want to build whole trees rather than individual modules or libraries.
