### ISSUE TITLE
executables: (optional) equivalent?

### ISSUE THREAD

**Issue by cfcs** [ocaml/dune#2433]
For the [`library` stanza](https://dune.readthedocs.io/en/stable/dune-files.html#library) there's a `<optional-field>` called `(optional)` which causes the library to only be built all of the required libraries are present.

Is there a way to achieve the same for executables?

In my project I'd like to have binaries for use with `afl-fuzz`, but I don't want to make `afl-persistent` a hard dependency for all users of the project.

**Comment by ejgallego** [comment]
see also #1690

**Comment by rgrinberg** [comment]
Is it possible for you to put those binaries in a separate package? This usually works much better in practice (if it's possible).

**Comment by cfcs** [comment]
@rgrinberg Yes, that's one option. The other option I guess is to pretend it's a library, then compile an executable from that based on a guarded `(run)` stanza. These are kind of hacky though, so I just wondered if there was a cleaner way to achieve this.

**Comment by diml** [comment]
At the moment it's not possible. The code that resolve binaries is quite simple: first look at public binaries in the workspace and then at binaries in the `PATH`. To support such a feature, we'd need to look at the library database as well when looking up binaries.
