### ISSUE TITLE
Dune reports warnings twice

### ISSUE THREAD

**Issue by copy** [ocaml/dune#2452]
For example:

```
% cat dune
(executable
 (name test)
 (flags :standard -warn-error -26))
% cat test.ml
let () = let y = 6 in ()
% dune build test.exe          
File "test.ml", line 1, characters 13-14:
Warning 26: unused variable y.
File "test.ml", line 1, characters 13-14:
Warning 26: unused variable y.
```

**Comment by nojb** [comment]
The reason is that test.ml does not have a .mli which causes test.ml to be compiled twice; once with ocamlc (to produce the .cmi) and once with ocamlopt (to produce the .cmx) needed for test.exe.

**Comment by nojb** [comment]
Closing as this behaviour is expected.

**Comment by copy** [comment]
That's unfortunate. Couldn't dune add `-w -a` to the invocation of ocamlc?

**Comment by diml** [comment]
This is a bit tedious, for instance if you only ask for the bytecode then we do need to display the warnings for the bytecode. Doing something different depending on what set of things are needed seems complicated to support and could hurt performance of incremental builds.

**Comment by diml** [comment]
The best is to always have a .mli file
