### ISSUE TITLE
Rule target inferrence doesn't work with write-file

### ISSUE THREAD

**Issue by NathanReb** [ocaml/dune#2469]
I personally prefer to be explicit about targets but I wanted to give a try to:
```
(rule (action (write-file file.ext "content")))
```
and it fails with:
```
File "dune", line 1, characters 0-47:
1 | (rule (action (write-file file.ext "content")))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: fields targets, target are all missing (exactly one is needed)
```

Is the rule target inferrence still working?
It seems like it's not, I just tried the example from https://dune.readthedocs.io/en/latest/dune-files.html#inferred-rules and I'm getting the same error.

I'm totally fine with this feature being removed but we should probably delete the doc section advertising it then!

**Comment by rgrinberg** [comment]
I just observed this bug as well and it's not related to `write-file`. I believe this bug is present with all actions for which the target is inferred. I haven't looked at this closely, but I think this bug was introduced when @aalekseyev added the target multiplicity feature.

In any case both the `deps` and `target{s,}` fields should be optional. @NathanReb would you mind creating some tests for this so that we don't forget about this?

**Comment by NathanReb** [comment]
Sure, I'll add that!

**Comment by aalekseyev** [comment]
Oh whoops, my bad. I could have sworn I've seen a test for this, but I guess not.
@NathanReb, thanks for volunteering.

**Comment by diml** [comment]
In any case, this should work: `(rule (write-file file.exe "content"))`, i.e. using the short form without any field.

**Comment by rgrinberg** [comment]
Yes, but the partial forms were convenient as well. I don't think we should break them. I'm surprised no one noticed this yet, I do think that we'll need a 1.11.1 for this fix.

**Comment by NathanReb** [comment]
I just wrote a couple basic blackbox tests for that and the bug isn't triggered for some reason. I'll dig deeper!

**Comment by NathanReb** [comment]
To clarify, the bug isn't triggered both from current master and from `1.11.0` so there's something weird going on.

**Comment by NathanReb** [comment]
Oh right, sry, I just realized the issue was coming from the use of the `action` field instead of using the short form. I'll add that test!
