### ISSUE TITLE
merlin cannot jump to generated ml files

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#2475]
Hi,

I'm working on a project where some ml and mli files are generated using an executable. However, merlin does not know about this, so when trying to jump to the definition of some values, I get the following error:

    'B' seems to originate from 'B' whose ML file could not be found

I think that we can tweak merlin file generation to add `S _build/default/dir` for every `dir` that has a rule that produces a `.ml` or `.mli` file in its list of targets.

Here's a project that shows the limitation:

### dune
```
(library
 (name l))

(rule
 (targets b.ml)
 (action
  (write-file %{targets} "let x = 2")))
```

### a.ml
```ocaml
let y = B.x + 1
```

(try to jump to `B.x` in `a.ml`)

**Comment by rgrinberg** [comment]
Merlin shouldn't really jump to generated code however. Is your generator emitting location directives?

**Comment by emillon** [comment]
The generator is a program that outputs an actual `.ml` file, not an AST. In the above example, when I'm manually adding the `S _build...` line, the result is what I'm expecting (it jumps to `let x = 2`).

**Comment by rgrinberg** [comment]
They can still output line directives. For example: https://caml.inria.fr/pub/docs/manual-ocaml/lex.html

This is how `copy_files#` works and merlin still jumps to the appropriate location.

**Comment by emillon** [comment]
In that case, there's not really any meaningful locations I can emit. The code generator reads some JSON files and uses them to generate some OCaml code.

Are you suggesting I should add `#line _build/default/generated.ml` in that case?

**Comment by rgrinberg** [comment]
Ah yeah I suppose the best you could do is jump to the generated source.

**Comment by diml** [comment]
Jumping to `_build` is not great though, especially if it is done transparently. In particular, if you open another file next to it you might end up editing files in `_build` without realising it.

**Comment by emillon** [comment]
In this case I adapted the code generator so that it prepends `#2 "./_build/default/path/to/file.ml"`, which does the trick for me. I think that `dune` could probably make things smoother but that can be done once we don't have `.merlin` files anymore. So I'm closing this, thanks!
