### ISSUE TITLE
[RFC] Better semantic of `diff?`

### ISSUE THREAD

**Issue by diml** [ocaml/dune#2482]
The semantic of `diff?` is a bit flaky. It has been a problem for users in the past (#2396) and it doesn't play well with sandboxing. We were discussing it with @aalekseyev this morning and are proposing the following changes:

- the first argument will always be a required dependency (as discussed in #2396)
- when the second argument exist, it will immediately be moved to a "promotion staging area" rather than be left where it was created

These two changes should make `diff?` better behaved, especially when sandboxing is enabled.

I'm putting this in the 2.0 milestone since it is a breaking change. We should have a quick at the dune-universe to check the impact of the first change. If as expected it is small, we should just make the change independently of the dune language version in use.

**Comment by nojb** [comment]
I believe this can be closed now that #2486 has been merged.
