### ISSUE TITLE
typpx-based PPX compatibility

### ISSUE THREAD

**Issue by Pitometsu** [ocaml/dune#2522]
How type-based PPX (see: https://bitbucket.org/camlspotter/typpx/src/default/) like https://bitbucket.org/camlspotter/ppx_implicits/src/default#readme could be used with the `dune`? AFAIK nor `(pps` nor `(staged_pps`, not even
```lisp
 (preprocess
  (action
    (system ppxfind ppx_implicits %{input-file})))
```

Current workaround:

```lisp
(rule
 (targets ppx_implicits.sexp)
 (action
  (with-stdout-to
   %{targets}
   (progn
    (system "echo \\(")
    (system "echo `ocamlfind printppx ppx_implicits`")
    (system "echo \\)")))))

(library
 (flags
  (:standard
   (:include ppx_implicits.sexp)))
```
And build like:
```shell
find _build/default/ -delete -name *.cmi > /dev/null 2>&1
nice dune build
```

**Comment by diml** [comment]
Dune expect ppx rewriters to be distributed as libraries and this is not the case for `ppx_implicits`. To make it work with `ppxfind`, we'd need to allow plain preprocessors to be used in staged mode.

TBH, it's probably simpler to port ppx_implicits to dune.

**Comment by Pitometsu** [comment]
Thank you for answer. Could you suggest also: is porting `ppx_implicits` to dune with appropriate ppx library kind would be enough, or any additional setup (e.g. from `ocaml-migrate-parsetree` integration side) required at sources yet?

**Comment by diml** [comment]
From what I can see, `TyPpx` is a ppx framework that already uses ocaml-migrate-parsetree` and `ppx_implicits` uses this framework, so porting `ppx_implicits` to dune should be enough.
