### ISSUE TITLE
How to handle program that generates files in multiple directories

### ISSUE THREAD

**Issue by hongchangwu** [ocaml/dune#2549]
Let's say that `gen` is an external program that will generate the following files:
- `src/a/foo.ml`
- `src/b/bar.ml`

And the project structure looks something like this (after `gen` is run):
```
├── dune-project
├── src
│   ├── a
│   │   ├── dune
│   │   └── foo.ml
│   └── b
│       ├── bar.ml
│       └── dune
```

Ideally I would want to have a `dune` file at `%{project_root}` that does this

```clojure
(rule
 (mode (promote (until-clean)))
 (targets
   src/a/foo.ml
   src/b/bar.ml)
 (action (run gen)))
```

However `dune` doesn't allow this:

```
File "dune", line 4, characters 3-15:
4 |    src/a/foo.ml
       ^^^^^^^^^^^^
Error: src/a/foo.ml does not denote a file in the current directory
```

Instead I have to do this separately in both sub-directories, e.g. in `src/a/dune`:

```clojure
(rule
 (mode (promote (until-clean)))
 (targets foo.ml)
 (action
  (chdir %{project_root} (run gen))))

(library
 (name a)
 (public_name test.a))
```

and in `src/b/dune`:

```clojure
(rule
 (mode (promote (until-clean)))
 (targets bar.ml)
 (action
  (chdir %{project_root} (run gen))))

(library
 (name b)
 (public_name test.b))
```

This works but looks very hacky, not to mention that it runs `gen` twice. Is there a better way to do this?

**Comment by diml** [comment]
Currently, there is no better support for such cases. We'll probably improve support for that one day, but in the meantime you can always generate the files in the main directory and then copy then in the sub-directories to avoid running the generation twice.

**Comment by hongchangwu** [comment]
@diml ok cool will try that.

**Comment by hongchangwu** [comment]
Hmm I got this exception:

```
Internal error, please report upstream including the contents of _build/log.
Description:
("dependency cycle that does not involve any files",
{frames =
   [("eval-pred",
    {dir = In_build_dir "default";
      predicate = {id = Glob "foo.ml"}});
   ("dir-contents-get0", ("default", "default/src/a"));
   ("install-entries", <opaque>); ("lazy-0", ()); ("lazy-1", ());
   ("lazy-5", ()); ("lazy-6", ()); ("load-dir", In_build_dir "default");
   ("eval-pred",
   {dir = In_build_dir "default";
     predicate = {id = Glob "foo.ml"}})]})
Backtrace:
Raised at file "src/stdune/code_error.ml", line 9, characters 2-29
Called from file "src/dep_path.ml", line 63, characters 12-17
Called from file "src/stdune/exn_with_backtrace.ml", line 23, characters 10-15
Called from file "src/stdune/exn_with_backtrace.ml" (inlined), line 25, characters 35-45
Called from file "src/build_system.ml", line 1783, characters 2-156
Called from file "src/fiber/fiber.ml", line 82, characters 8-15
```

The main `dune` file:

```clojure
(rule
 (mode (promote (until-clean)))
 (targets
   foo.ml
   bar.ml)
 (action
  (progn
   (run gen)
   (run mv src/a/foo.ml foo.ml)
   (run mv src/b/bar.ml bar.ml))))
```

`src/a/dune`:

```clojure
(copy_files %{project_root}/foo.ml)

(library
 (name a)
 (public_name test.a))
```

`src/b/dune`:

```clojure
(copy_files %{project_root}/bar.ml)

(library
 (name b)
 (public_name test.b))
```

Let me know if I did something wrong and misunderstood your suggestion. (I'm using dune 1.11.0)

**Comment by diml** [comment]
I think I see approximately what it could be. Could you try replacing the `(copy_files %{project_root}/xxx)` by `(rule (copy %{project_root}/xxx xxx))`? The latter is much simpler to interpret internally. Additionally, it would be better if `gen` would generate the files in the current directory rather than call `mv` afterwards.

**Comment by hongchangwu** [comment]
Thanks that works. In my case `gen` is an external program, but I can write a wrapper that make sure it generates files in the current directory.
