### ISSUE TITLE
is there a more generic command than dune utop for alternative toplevels?

### ISSUE THREAD

**Issue by hannesm** [ocaml/dune#2553]
so, I'd like to not execute `utop`, but instead `ocaml` or `ocamlnat` (esp. given the development of [down](https://erratique.ch/software/down)). is this possible with dune by now, or can be easily implemented?

thanks!

**Comment by rgrinberg** [comment]
It's not possible but we do have a plan to support things like down. The idea is to invert the relationship between dune and the toplevel. The user would launch the toplevel however they want and then run some directive to load the cmi's/cmo's for the dune project. This is all vaporware for now, so I wouldn't hold my breath for it in the near future.

**Comment by rgrinberg** [comment]
`$ dune top`
