### ISSUE TITLE
dune install ignores the `(vendor)` markers

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#2554]
`dune install` tries to install all the contents of packages marked as vendored. It should probably only install non-vendored things.

e.g.:
```
dune install
745Error: The following <package>.install are missing:
746- _build/default/duniverse/alcotest/alcotest.install
747- _build/default/duniverse/alcotest/alcotest-async.install
748- _build/default/duniverse/alcotest/alcotest-lwt.install
749- _build/default/duniverse/astring/astring.install
750- _build/default/duniverse/base/base.install
751- _build/default/duniverse/bigarray-compat/bigarray-compat.install
752- _build/default/duniverse/bos/bos.install
753- _build/default/duniverse/cmdliner/cmdliner.install
754- _build/default/duniverse/cppo/cppo.install
755- _build/default/duniverse/cppo/cppo_ocamlbuild.install
756- _build/default/duniverse/findlib/findlib.install
757- _build/default/duniverse/fmt/fmt.install
758- _build/default/duniverse/fpath/fpath.install
759- _build/default/duniverse/logs/logs.install
760- _build/default/duniverse/lwt/lwt.install
761- _build/default/duniverse/lwt/lwt_ppx.install
762- _build/default/duniverse/lwt/lwt_react.install
763- _build/default/duniverse/mmap/mmap.install
764- _build/default/duniverse/num/num.install
765- _build/default/duniverse/ocaml-compiler-libs/ocaml-compiler-libs.install
```

**Comment by rgrinberg** [comment]
For a library to be installed, its dependencies must also be installed. So this can't really work without some additional hackery.

In my vendoring proposal, I suggested to get around this by essentially marking all vendored libs as private and mangling all their names to make it safe for them to be installed.

**Comment by avsm** [comment]
installing via vendoring is primarily most useful for binaries.  Perhaps a `dune install --bin-only` would be useful here in the short term?  I definitely just want the binaries to go into the prefix

**Comment by rgrinberg** [comment]
A `--bin-only` flag sounds useful.

**Comment by diml** [comment]
A slightly more general proposal: `--sections <sections>`. For instance: `--sections bin,share`.

**Comment by avsm** [comment]
Yes, a sections one would be good.  Also, just specifying the targets would also work for me. E.g.

```
dune install bin/duniverse bin/duniverse-helper
```

**Comment by diml** [comment]
Anonymous arguments are already used for package names unfortunately
