### ISSUE TITLE
Feature request: CLI flag or env var to disable .merlin generation

### ISSUE THREAD

**Issue by fredemmott** [ocaml/dune#2568]
This has been raised a few times before (e.g #257) and it seems that it's been rejected due to better ways to solve the root problem in each case.

My root problem: outside of the ocaml community, it's fairly common to build outside of the source directory, and this should not modify the source directory at all; for example, this is the default expectation of debian's package building scripts

Example workflow:

```
$ cd $SOURCE_DIR
$ DUNE_NO_MERLIN=true DUNE_BUILD_DIR="$(mktemp -d)" dune build foo.exe
$ git status --ignored
Current behavior: lots of .merlin files added
Desired behavior: absolutely no changes to SOURCE_DIR, even ones ignored by source control system
$
```

People actively working on the project would presumably want the .merlin files, but packaging builds do not; this means that committing a change to the configuration files is not a suitable option.

**Comment by diml** [comment]
We could add an option to disable promotion of files from the build directory to the source tree entirely.

**Comment by rgrinberg** [comment]
Indeed. Should `-p` enable this automatically?

**Comment by diml** [comment]
Yes!

**Comment by rgrinberg** [comment]
Actually, what about .install files? Those are necessary to make the installation go through at least with opam.

@fredemmott are .install files a problem for you?

**Comment by fredemmott** [comment]
Those aren't showing up for me with `git status --ignored` or `find`; probably because this project (Hack+HHVM) is in a bunch of languages and tries to isolated opam/ocaml/rust/cargo/.... from anything on the user's system so people don't need to setup/clean/configure dev environments for <n> different languages, so we're running it in a bit of a weird way.

**Comment by rgrinberg** [comment]
I suppose that you're not using the `@install` alias and just building the executable with `$ dune build`.

@diml looks like we will not be able to make this the default for `-p`.

**Comment by fredemmott** [comment]
We're running `dune build src/foo.exe src/bar.exe`, but grep finds nothing for '@install' in the ocaml part of our source tree.

**Comment by rgrinberg** [comment]
Just a note that `$ dune build` and `$ dune build @install` are equivalent since `@install` is the default target in dune 1.x. In any case, it seems like just having a no promotion will work fine for you since you aren't using these .install files.

**Comment by diml** [comment]
> @diml looks like we will not be able to make this the default for -p.

Ah well, I guess in practice it doesn't matter that much.
