### ISSUE TITLE
Improve argument passing syntax in pps

### ISSUE THREAD

**Issue by aantron** [ocaml/dune#2573]
I suggest to replace the current syntax, which treats options as not belonging to any PPX, but being common to them all, by one which pairs each PPX with its own options:

```
(pps ppx1 (ppx2 --option1 --option2) ppx3)
```

The current syntax distinguishes options from PPX names by assuming that anything that begins with `-` is an option, and everything else is a PPX name. This doesn't work for option arguments, like `ppx2 --option1 value`, so Dune introduced `--` to work around this. As a result, if there are ever two PPXs with option arguments, the stanza in the current syntax becomes

```
(pps ppx1 ppx2 -- --option1 value1 --option2 value2)
```

We can make it into this instead:

```
(pps (ppx1 --option1 value1) (ppx2 --option2 value2))
```

We can maintain backward compatibility by still interpreting atoms beginning with `-` and atoms after `--` as options at the top level of the `pps` stanza.

The current choice of syntax seems to be based on the fact that current OMP combines all the options of registered PPXs into one command line, but that is itself a dubious decision. In any case, it shouldn't be exposed by Dune directly to the user, especially since OMP can parse the options correctly without needing `--`, but Dune cannot. We are already not able to simply expose the driver's syntax anyway.

I can make the change if this is approved.

**Comment by diml** [comment]
What is the motivation for this?  Merging ppx rewriters is the best way to get a good composition semantic and good performances, so I wouldn't call it dubious. On the contrary, not merging them is definitely dodgy. I've seen problems in the past due to not merging ppx rewriters.

Given that, it seems natural to expose the fact that ppx rewriter flags are common to all ppx rewriters. Making them per ppx would give the false impression that they are scoped and it is ok for two ppx rewriters to use the same name.

**Comment by aantron** [comment]
The issue isn't whether PPX writers are merged, I'm not proposing to change that. I'm proposing to change only the *syntax* expected by Dune in its `pps` stanza. The current syntax requires workarounds like `--`, but the syntax I am proposing would allow the binary, which has the arguments interpreter built into it, naturally interpret its own command line without the need for workarounds in Dune.

I'm not calling merging rewriters dubious, I'm calling merging their command lines blindly dubious.

> Given that, it seems natural to expose the fact that ppx rewriter flags are common to all ppx rewriters. Making them per ppx would give the false impression that they are scoped and it is ok for two ppx rewriters to use the same name.

That flags are currently common to all PPX rewriters is an accident of how OMP is currently implemented. We could imagine a future OMP adopting a syntax like `ppx.exe -- rewriter_name rewriter_flags -- rewriter2_name rewriter2_flags` or something, precisely to avoid the issue of flags conflict. But in any case, that is a detail of the interface between Dune and OMP. It's not actually natural for the flags to be common between all rewriters, that's arguably a mistake. And we are not exposing this to the right people. We are exposing this to users of Dune, not developers of PPXs, and not through other build systems. Furthermore, we are not *really* exposing the OMP command line in Dune, because we still parse it in order to implement `--`.

**Comment by aantron** [comment]
(and the only reason we even need `--` is because we can't parse the reset of the command line properly, like OMP can, because the OMP driver has all the arg specifications linked in, but Dune does not).

**Comment by aantron** [comment]
In other words, treating the command line this way is already hurting us in Dune, which is why we need `--` in the first place.

**Comment by diml** [comment]
How would you avoid `--` with the new syntax? For instance, how would you pass an argument of the driver itself such as `-reserve-namespace foo`?

**Comment by aantron** [comment]
We will leave the `--` for now for this purpose. If the syntax for PPXs with no arguments were to become `(ppx)`, it would disambiguate PPXs and anonymous arguments fully, and we could remove `--` in a far-future version of Dune.

**Comment by diml** [comment]
It is more common to not pass arguments to ppx rewriters than to pass some, so I'm not excited at the idea of requiring extra parentheses everywhere. Keeping `--` seems inevitable then.

Regarding the grouping of arguments, that seems fine to me in principle, but only if the underlying command accepts grouping as well. So this change should be accompanied with a convention for grouping arguments on the command line. Drivers should declare whether they support grouping via their [ppx.driver field](https://github.com/ocaml-ppx/ocaml-migrate-parsetree/blob/b7f1862433e598aa9f91f9b96a5639f1caa301e7/src/dune#L9) so that we get a proper error when grouping is not supported.

**Comment by aantron** [comment]
Another option would be to pass options to the driver in a separate stanza. Then, we could avoid parentheses for PPXs with no options.

Thanks for the discussion. Now, I see that there are several sets of constraints here, which don't quite fit together nicely. The current solution doesn't seem very neat, but it seems to be pretty good in context of the underlying constraints. So, I suggest to close this issue.

**Comment by diml** [comment]
> Another option would be to pass options to the driver in a separate stanza. Then, we could avoid parentheses for PPXs with no options.

Indeed, I hadn't thought about this option but it makes complete sense.

> Thanks for the discussion. Now, I see that there are several sets of constraints here, which don't quite fit together nicely. The current solution doesn't seem very neat, but it seems to be pretty good in context of the underlying constraints. So, I suggest to close this issue.

Yh, that's the idea. Ok, so I'm closing this for now then, but feel free to re-open it if you'd like to work towards it.
