### ISSUE TITLE
segfault with truncated marshalled value in dune 1.11.3

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#2598]
I think I had a bit of file corruption in the _build directory with an out of space error. After freeing up some space, dune segfaults due to marshalling failing:

```
Error: exception Failure("input_value: truncated object")
Backtrace:
Raised by primitive operation at file "src/persistent.ml", line 24, characters 18-41
Called from file "src/stdune/exn.ml", line 10, characters 8-11
Re-raised at file "src/stdune/exn.ml", line 12, characters 30-37
Called from file "src/build_system.ml", line 317, characters 10-21
Called from file "camlinternalLazy.ml", line 27, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 34, characters 4-11
Called from file "src/build_system.ml", line 1431, characters 21-55
Called from file "src/fiber/fiber.ml", line 112, characters 7-12
Re-raised at file "src/stdune/exn.ml" (inlined), line 39, characters 38-65
Called from file "src/stdune/exn_with_backtrace.ml", line 17, characters 2-40
Called from file "src/fiber/fiber.ml", line 82, characters 8-15
Re-raised at file "src/stdune/exn.ml" (inlined), line 39, characters 38-65
Called from file "src/stdune/exn_with_backtrace.ml", line 17, characters 2-40
Called from file "src/fiber/fiber.ml", line 82, characters 8-15
Re-raised at file "src/stdune/exn.ml" (inlined), line 39, characters 38-65
Called from file "src/stdune/exn_with_backtrace.ml", line 17, characters 2-40
Called from file "src/fiber/fiber.ml", line 82, characters 8-15
```

**Comment by diml** [comment]
Hmm, I suppose we could make sure writing such files is atomic to avoid such errors.

**Comment by rgrinberg** [comment]
@snowleopard what do you think about making all the writes to persistent db's atomic?

**Comment by snowleopard** [comment]
Sure, saving the file atomically sounds like the right thing to do.

(But also I vaguely remember writing some code to catch the exception, the crash from the first comment in this thread shouldn't happen.)

**Comment by rgrinberg** [comment]
Indeed. This error isn't possible now.

**Comment by rgrinberg** [comment]
I'm not sure writing the file atomically is worth it. We would do an extra syscall to avoid an error that we already handle correctly. Doesn't like a good trade-off.

**Comment by snowleopard** [comment]
Note that the code I wrote doesn't solve the problem that happens if we overwrite the old file somehow partially in a way that loading it succeeds.

Presumably writing this file is already slow (because it's large) so an extra syscall might not matter performance wise.

**Comment by rgrinberg** [comment]
> Note that the code I wrote doesn't solve the problem that happens if we overwrite the old file somehow partially in a way that loading it succeeds.

I'm not sure that's possible. Marshalling includes the length header first therefore any partial writes will give us this "truncated object" error.

**Comment by snowleopard** [comment]
I see. We are still losing the old database in this case though, so the next build is going to be slow.
