### ISSUE TITLE
Feature request: named signatures at separate files; functors files

### ISSUE THREAD

**Issue by Pitometsu** [ocaml/dune#2599]
Because signatures-modules relationship must be many-to-many in properly organized domain model, number of signatures even higher than modules. That's why it looks important to have ability to have named signatures as files. E.g. `(lib ... (named-signatures ...)` in similar way to interfaces-without-implementation.
***
Another useful abstraction would be `(lib ... (functor name (signatures...)` to have functor as file `name` and have listed named signatures as modules in functor. Behaviour similar to virtual-modules. It necessary because lots of dependency injection require functor hell (in case it depend on runtime configuration, it's not possible to use virtual libraries), so per-file functor creation would be very handy.

**Comment by diml** [comment]
What is the difference between a named signature and a .ml file containing only:

```ocaml
module type S = sig
 ...
end
```

**Comment by Pitometsu** [comment]
Necessity to:
1. write intermediate module
2. create explicit top-level module for library
3. include that intermediate module there
4. create  explicit top-level module signature for library
5. and hide that intermediate that module itself there from outside the library
6. but that intermediate module still be in scope for all the library. It could be avoided by wrapping it in nested library, but that would be even more boilerplate. Too much actions for simple thing.

**Comment by Pitometsu** [comment]
And also unclear naming, for sure

**Comment by diml** [comment]
I see. So the idea would be that a named signature `X` would give you a module type named `X` in the current library?

Unfortunately, dune cannot do that without support at the compiler level.

**Comment by Pitometsu** [comment]
AFAIK, dune just wrap all the library’s modules at top-level wrapper module. So compiler allow to do so (module types in the top level module). Dune need just to put files content with proper naming together to avoid necessity to list all the library's content by hand.

**Comment by diml** [comment]
But how would this work? FTR, Dune generate a wrapper module that looks like this:

```ocaml
module X = Foo__X
module Y = Foo__Y
```

what line would you generate for a named signature?

**Comment by Pitometsu** [comment]
E.g.

```ocaml
module X = Foo__X
module Y = Foo__Y
module type Z = module type of Foo__Z
```

**Comment by diml** [comment]
I dont think that would work as Z might references element from `Foo__Z` that require an implementation.

**Comment by Pitometsu** [comment]
@diml didn't get it. It's the module type, it suppose to require implementation. The same, as for interfaces-without-implementation. Any example with problem?
***
And functor a bit more complex:
```ocaml
module type A = module type of Foo__A
module type B = module type of Foo__B
module F (A : A) (B : B) = struct
  (* echo Foo__F body here *)
end
```

**Comment by diml** [comment]
I remember discussions about changing the semantic of `module type of` to match `module type of struct include ... end`. More precisely, if `z.mli` contains `exception X`, then currently `module type of Z` would return:

```ocaml
sig
  exception X
end
```

However, in the future in might  return:

```ocaml
sig
  exception X = Z.X
end
```

The equality `X = Z.X` means that when linking an executable, the compiler would require the module `Z` to have an implementation. This is hypothetical, but what `module type of` produces depends on the compiler internals, and IIRC it is already possible to get such equalities with the current `module type of`.

**Comment by Pitometsu** [comment]
Oh, I see, problem with module-loading-time evaluation
```ocaml
λ # module rec M = (M : sig type t val v : unit -> t end with type t = private int);;
module rec M : sig type t = private int val v : unit -> t end
λ # module type M = module type of M;;
module type M = sig type t = private int val v : unit -> t end
λ # module rec M = (M : sig type t val v : t end with type t = int);;
Error: Cannot safely evaluate the definition
       of the recursively-defined module M
```

**Comment by Pitometsu** [comment]
Maybe for named signatures just make echo as well:
```ocaml
module type Q = sig
  (* echo Foo__Q body here *)
end
```
Would it be hacky and fragile in some sense? Is there better options?

**Comment by diml** [comment]
It's a bit too hacky yeah. In particular, we end up diverging too much from the vanilla language. We generate alias files because we don't have much of a choice, but it is best to keep such implicit mechanisms as simple as possible.

**Comment by Pitometsu** [comment]
Yeah. Thank you for constructive critic. And ironically original language let define named signatures at top level module (but same file). Propose to keep issue here in case someone would propose an acceptable solution.

**Comment by Pitometsu** [comment]
Also is it possible to define that behaviour by rules currently in dune files for specific project (and inherit such rule for all libraries) to avoid boilerplate for this moment?

**Comment by Pitometsu** [comment]
Or maybe it should be a ppx...

**Comment by diml** [comment]
I haven't thought much about the question. It's probably possible to do something but TBH I don't recommend it. It will surely be more convenient for you to write the code, but then you'll basically end up writing code in a slightly different dialect that will be more difficult for others to understand because it is not standard.

My advice: either bear the pain of the more verbose but more explicit code, or try to get a proper feature merged in OCaml itself.

**Comment by rgrinberg** [comment]
I think we can reject this interesting proposal. We'd prefer to leave ambitious improvements like this to the compiler.
