### ISSUE TITLE
Linking with ppx libraries initializes Random

### ISSUE THREAD

**Issue by rdavison** [ocaml/dune#260]
I don't believe this is a bug with `jbuilder`, but I'm not really sure where to file this bug.  But I suspect the people who read this issue tracker might know better than me ;)

I'm trying to link with `ppx_inline_test` and some other ppx libraries (mostly from ppx_jane, and not directly... it seems this issue occurs with transitive dependencies as well).  But for some reason, the libraries appear to contain an initialization of the Random module with a nondeterministic seed.  This results in a bug where I cannot run the inline test runner.  I narrowed it as far down to several ppx libraries, but for this example, I am just focusing on two -- `ppx_let` and `ppx_optional`.

Using ppx_let will throw the error message: 
```
 test_runner alias runtest (exit 2)
(cd _build/default && ./test_runner.exe inline-test-runner foo)
Fatal error: exception (Failure
  "initializing Random with a nondeterministic seed is forbidden in inline tests")
Raised at file "pervasives.ml", line 32, characters 22-33
Called from file "src/random.ml", line 39, characters 4-50
```

But merely switching `ppx_let` with `ppx_optional` and reinvoking the runtest alias, the error simply goes away.

I'm attaching a gist which shows this minimal example.

https://gist.github.com/rdavison/02b53c5d5716430b32e5519e93de7a56

EDIT: One additional point, I am aware of `Random.self_init ~allow_in_tests:true ()`.  Yes, I did try it, no it did not work.

**Comment by diml** [comment]
There used to be an issue like this in ppx_core, but I though this had been fixed a while ago.

**Comment by dc-mak** [comment]
Still a problem, can reproduce it as follows
```
jbuild:
(jbuild_version 1)

(library (
    (name mwp)
    (flags (-linkall))
    (libraries (
         ppx_driver ppx_inline_test.runner.lib))
    (preprocess (pps (ppx_inline_test.runner.lib ppx_driver.runner)))
))
```
OCaml 4.06.0
ppx_inline_test v0.9.2
ppx_driver v0.9.2

**Comment by rdavison** [comment]
@dc-mak : The issue was in ppx_core.  After we upgraded to the latest version, we no longer had the problem.  The issue was here: https://github.com/janestreet-deprecated/ppx_core/blob/7b88da3a179e69a28e8dcc2c528168cbf284ee33/src/common.ml#L32 .  `gen_symbol` always chooses `gen_symbol_old`, but that doesn't prevent `gen_symbol_new` (which isn't a function) from initializing the random number generator.
