### ISSUE TITLE
How to cite Dune?

### ISSUE THREAD

**Issue by Zimmi48** [ocaml/dune#2602]
I see to recall that there was a paper about Dune but I cannot find it.
If there is a preferred method for citing Dune it should be mentioned somewhere, for instance in the FAQ.
Otherwise, I'll cite the manual, but note that another inconvenience is that there are only two versions of the manual that are provided "latest" and "stable", which are both moving targets. It would be nice to be able to cite the manual for a specific version of Dune.

**Comment by diml** [comment]
At the moment, there is no paper about Dune specifically, though we have been talking it on and off in the past. However, it was used as a case study in the [Selective Applicative Functors paper](https://www.staff.ncl.ac.uk/andrey.mokhov/selective-functors.pdf) presented at ICFP this year. It was also cited in the [Build system a la carte paper](https://www.microsoft.com/en-us/research/uploads/prod/2018/03/build-systems-final.pdf). 

For now, I'd that the best method is to point to the website: https://dune.build/

**Comment by Zimmi48** [comment]
I see thanks. I am leaving this open in case it is useful to you to track, but feel free to close it as well.

**Comment by rgrinberg** [comment]
Closing. Please re-open if you have more questions.
