### ISSUE TITLE
Need ability for c_flags in workspace file to be merged with library's own c_flags

### ISSUE THREAD

**Issue by timbertson** [ocaml/dune#2603]
My use case is building upstream reason-glfw with system dependencies (x11 mainly) provided by nix:

 - I can't modify the dune file, I only have control over env vars
 - I need to add extra cflags so that it can find all of its X11 dependencies (a long string of `-I/nix/store/xxxxxxxxxxxxxxxxx/include`)

I was hoping a custom workspace injected with DUNE_WORKSPACE would work, but I can't get it working. I figured out how to add c_flags, with:

dune-workspace:
```
(env (_
  (c_flags (-I/path/to/some/library))))
```

and it's builing with the following dune file, which has its own c_flags specified (from configurator):
https://github.com/revery-ui/reason-glfw/blob/c6a72a9a270864c5e461bb2a602454e9448ed8ea/src/dune

dune version: 1.11.3

Unfortunately my workspace c_flags are only used if the library has no c_flags specified, but I need both. I don't know about workspace overrides in general, but for c_flags I'd expect it makes more sense to merge the workspace and library flags, not simply act as a fallback if the library doesn't have any.

**Comment by rgrinberg** [comment]
Those libraries should use `:standard` in their flags to inherit whatever flags set by the workspace.
