### ISSUE TITLE
Fail to install Dune 1.11.3

### ISSUE THREAD

**Issue by Zhang-Liao** [ocaml/dune#2622]
I am trying to install dune 1.11.3 using 
**opam install dune**

But I get into trouble 
[WARNING] Running as root is not recommended
The following actions will be performed:
install dune 1.11.3
Gathering sources   
[dune.1.11.3] found in cache
Processing actions
[ERROR] The compilation of dune failed at
        "/Users/zhangliao/.opam/opam-init/hooks/sandbox.sh build ocaml
        bootstrap.ml".
=== ERROR while compiling dune.1.11.3 ======================================== 
2622  context     2.0.0 | macos/x86_64 | ocaml-base-compiler.4.07.1 | https://opam.ocaml.org#136fdfd4
path        ~/.opam/new_source/.opam-switch/build/dune.1.11.3
command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml bootstrap.ml
exit-code   2
env-file    ~/.opam/log/dune-6913-1872ec.env
output-file ~/.opam/log/dune-6913-1872ec.out

output
2622 cp src/ocaml-syntax-shims/pp.real.ml src/ocaml-syntax-shims/pp.ml
cp src/ocaml-syntax-shims/shims.406.ml src/ocaml-syntax-shims/shims.ml
/Users/zhangliao/.opam/new_source/bin/ocamllex.opt -q src/ocaml-syntax-shims/let_trail.mll
/Users/zhangliao/.opam/new_source/bin/ocamldep.opt -modules src/ocaml-syntax-shims/let_trail.mli src/ocaml-syntax-shims/let_trail.ml src/ocaml-syntax-shims/pp.ml src/ocaml-syntax-shims/shims.ml > boot-depends.txt
/Users/zhangliao/.opam/new_source/bin/ocamlopt.opt -g -w -40 -o boot-pp.exe -I +compiler-libs ocamlcommon.cmxa boot_pp.ml
clang: error: couldn't create cache file '/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/xcrun_db-ha4foCBM' (errno=Operation not permitted)
clang: error: unable to make temporary file: Operation not permitted
File "boot_pp.ml", line 1:
Error: Assembler error, input left in file /tmp/camlasmcc1e1b.s

Any help will be welcome.

**Comment by nojb** [comment]
At first sight this is not a dune error but rather a permission problem. Are you able to install opam packages?

**Comment by Zhang-Liao** [comment]
> At first sight this is not a dune error but rather a permission problem. Are you able to install opam packages?

**Comment by Zhang-Liao** [comment]
> > At first sight this is not a dune error but rather a permission problem. Are you able to install opam packages?

Yes I can. After I see you reply, I ran
**opam install coq.** 

The result is 

The following actions will be performed:
  ∗ install coq dev
<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  
[coq.dev] synchronised from git+https://github.com/coq/coq.git#master
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  
installed coq.dev
Done.

**Comment by Zhang-Liao** [comment]
> At first sight this is not a dune error but rather a permission problem. Are you able to install opam packages?

It seems I have solved this problem by a new ocaml switch. I am trying to figure out what causes this problem now.

**Comment by rgrinberg** [comment]
Please re-open if you can reproduce with a recent version of dune.
