### ISSUE TITLE
variables in targets/deps field

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#2626]
It should be possible to use "static" variables such as `%{exe}` in the `targets` (or `deps` for that matter) field of a `rule`.

**Comment by nojb** [comment]
@rgrinberg is this issue still relevant (maybe solved by your #3369, maybe already solved) ? [sorry, can't check at the moment]

**Comment by rgrinberg** [comment]
`%{exe:..}` is possible but the new artifact forms are still not supported. So I would say that this issue isn't addressed yet.

**Comment by rgrinberg** [comment]
@nojb this should be possible now.

**Comment by nojb** [comment]
> @nojb this should be possible now.

OK! I don't need this at the moment anymore, so I suggest we close it and reopen as needed. Thanks.
