### ISSUE TITLE
Register dependency on -args/-args0 argument

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#2627]
When passing flags to the compiler, it would be nice if the argument to `-args0` and `-args` were recognised by dune and registered as a dependency.

**Comment by diml** [comment]
If we do it for `-args0/-args`, it opens the door to doing it for other arguments as well. In the end, dune might need to know the exact grammar of the compiler command line, which feels like opening a can of worms.

That said, I've been wondering about a standard format for commands to describe their command line. That would be easy to generate with cmdliner for instance.

**Comment by nojb** [comment]
OK, fair point.
