### ISSUE TITLE
Glob parsed as two arguments

### ISSUE THREAD

**Issue by Julow** [ocaml/dune#2630]
Hi,

```
(copy_files ../../unix/common.{ml,mli})
(copy_files ../../unix/common.ml{,i})
```

The first line give the following error, while the second works as expected.

```
5 | (copy_files {../../unix/common.{ml, mli}})
                                        ^^^^^
Error: Too many argument for copy_files
```

**Comment by diml** [comment]
The excerpt in the error message doesn't match the code you quoted. Are you sure you are looking at the right `dune` file?

**Comment by Julow** [comment]
Yes. That's what happened, I was testing with the extra space.
Sorry for the inconvenience.
