### ISSUE TITLE
(preprocessor_deps) are ignored when there is no preprocessing

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#2642]
Hi,

I was trying to use `(preprocessor_deps)` as a way to pull files (required at runtime) into `_build/`, and noticed the following behaviour.

When there is no `(preprocess)` field, `(preprocessor_deps)` is completely ignored.

For example, the following `dune` file does not trigger any error or warning (but uncommenting the `(preprocess)` field triggers an error if the file does not exist of course).

```scheme
(executable
 (name e)
 ;(preprocess (pps ppx_deriving.std))
 (preprocessor_deps does-not-exist.txt))
```

I think that we could detect the problem a bit more eagerly, for example by issuing an error or a warning when `(preprocess_deps)` is set but `(preprocess)` is not.

What do you think?

**Comment by diml** [comment]
That seems good to me! It should be a warning with lang dune<2.0 and an error with lang dune>=2.0
