### ISSUE TITLE
Unable to build using `make`

### ISSUE THREAD

**Issue by vyorkin** [ocaml/dune#2651]
I'm trying to build the `dune` [as described in the README](https://github.com/ocaml/dune#installation).

Running `make` command for me results in the following error:
```
File "src/dune_action_plugin/dune_action_plugin.ml", line 16, characters 57-65:
Error: Unbound module Result
```

Some details about my environment:
```
$ ocaml --version                                                                                        The OCaml toplevel, version 4.06.1
```

Darwin vasiliys-mbp 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

**Comment by diml** [comment]
I think this will be fixed by #2646 as this PR removes dune_action_plugin from the bootstrap path entirely
