### ISSUE TITLE
cover name clashes between system libraries and ocaml libraries

### ISSUE THREAD

**Issue by olafhering** [ocaml/dune#2684]
oasis was able to build `ocaml-libvirt` and its examples, but dune fails to provide the same functionality. The reason is simple: the system library is named `libvirt.so`, the ocaml library is also called `libvirt`. When linking the examples, "dune" tries to link to "-lvirt", which maps to either `libvirt.so` or `libvirt.a` in the system linker. Since the `_build` directory comes first in the `-L` search paths, the linker finds the ocaml `libvirt.a` file first, and will not consider the real `/usr/lib64/libvirt.so` anymore. The only way to get around this is  `(flags -ccopt -Wl,/usr/lib64/libvirt.so)` for the example executables. Other ocaml applications that use ocaml-libvirt will most likely have the same issue.

This is the `_oasis` file:
````
Library mllibvirt
 Path: libvirt
 Modules: Libvirt, Libvirt_version
 FindlibName: libvirt
 BuildDepends: unix
 CSources: libvirt_c.c
 CCOpt: ${libvirt_cflags}
 CCLib: ${libvirt_libs}

Executable "myfoo"
 Path: examples
 MainIs: foo.ml
 BuildDepends: libvirt
````
This will create the findlib name `libvirt`,  `mllibvirt.a|cma|cmxa` and `libvirt.mli|cmx`.

So far I was unable to separate the findlib name, the `*.a` name and the `*.ml` name with dune.

Does dune support such case?

**Comment by olafhering** [comment]
It seems `name` in dune is like `Library` in oasis, `public_name` is like `FindlibName:`, and `modules` is like `Modules:`. At least with these settings the files in `_build` are similar.

However, the `executable` does not find the `Libvirt` module with `libraries == public_name`.

**Comment by olafhering** [comment]
I think the issue is that `mllibvirt.cmi` is created by dune, instead of `libvirt.cmi` as in oasis.

**Comment by diml** [comment]
> It seems name in dune is like Library in oasis, public_name is like FindlibName:, and modules is like Modules:. At least with these settings the files in _build are similar.

That seems correct to me.

Could you try adding `(wrapped false)`? By default Dune puts all the modules under a single toplevel module named after the library name (the `name` field). `(wrapped false)` disables this behavior

**Comment by olafhering** [comment]
Indeed, thanks. Adding `(wrapped false)` fixes it for me.,
