### ISSUE TITLE
implicit_transitive_deps for workspace only

### ISSUE THREAD

**Issue by Pitometsu** [ocaml/dune#2685]
Is it possible to disable `implicit_transitive_deps` for current workspace-related libraries only to make development dependencies more clear, but not for findlib's (installed from opam) ones?

**Comment by diml** [comment]
Could you give an example of what you have in mind?

**Comment by Pitometsu** [comment]
It would be convenient to have control over libraries scopes. E.g. if in my project library A use library B and C, and library B use C, I can miss it during refactoring planning. I would prefer to have both B and C to be required at A's dune file. On other hand it's inconvenient to require same from third-party libraries (like ppx_sexp_conv or core) which may implicitly depend on some "internal" (but not private) libraries (like sexplib0 or core_kernel in that case).

Not sure: can I use dune's projects for that?

**Comment by diml** [comment]
Oh, I see. Yeah, this is unfortunate. We have a plan to sort out this case. More precisely, we'd like to add support for "hidden" include paths in the compiler. This would mean that when you use `core` with `(implicit_transitive_deps false)`, then the compiler would still be able to see `sexplib0` files. However, you still wouldn't be allowed to write `Sexplib0.x` in your code.

Given that we have a plan to sort this out properly, I'd prefer to not add a partial solution in the meantime.

**Comment by rgrinberg** [comment]
I'll officially reject this. Thanks for the interesting proposal
