### ISSUE TITLE
Several project per workspace

### ISSUE THREAD

**Issue by Pitometsu** [ocaml/dune#2686]
It's not clear from documentation: can several dune projects be created under same dune workspace, and how they should be related to opam packages?

**Comment by diml** [comment]
Yes. Simply drop a `dune-project` file anywhere to define a new project. Project names don't relate to opam packages, however a project can define one or more opam packages via the `(package ...)` stanza.

Note that each project defines a scope, i.e. private libraries and executables are only visible inside the project they are defined in.

**Comment by Pitometsu** [comment]
Thank you. Also got that `dune-project` could have several opam's `package`s. Maybe all this worth be placed at documentation.

**Comment by Pitometsu** [comment]
Oh, one more question: could be one of `dune-project` "orphan" (not related to any opam's package) to be used as a scope in other projects of same workspace?

**Comment by diml** [comment]
Yes, however you won't be able to declare any public element in it as public elements must be attached to a package name.
