### ISSUE TITLE
dune fails to create an empty .cmxa library under Windows

### ISSUE THREAD

**Issue by db4** [ocaml/dune#2687]
I stumbled on that trying to build stdlib_shims:
```
File "_build/.dune/default/src/dune", line 2, characters 0-75:
2 | (library
3 |  (wrapped false)
4 |  (name stdlib_shims)
5 |  (public_name stdlib-shims))
Error: Rule failed to generate the following targets:
- src/stdlib_shims.lib
```
For more detail see https://github.com/ocaml/stdlib-shims/issues/11
@diml suggested it should be fixed on dune's side.

**Comment by rgrinberg** [comment]
This should be fixed in master. Thanks for the report.
