### ISSUE TITLE
Allow dune exec underneath perf rather than having to specify a target from _build.

### ISSUE THREAD

**Issue by gs0510** [ocaml/dune#2691]
Currently the perf runs on dune exec rather than the binary, it would be nice to have dune allowing a perf with dune exec rather than having to specify the target from _build.

**Comment by avsm** [comment]
Would you be able to paste the command line that you currently use to run `perf` with a dune-built library?

**Comment by gs0510** [comment]
I currently run:
```
 perf record --call-graph dwarf _build/default/bench/main.exe -g
```

**Comment by avsm** [comment]
Thanks! So what we're looking for here is some dune mechanism to prefix a `dune exec` with another command. This might also help with running `valgrind` under a dune exec as well.

**Comment by diml** [comment]
What about `dune exec perf record --call-graph dwarf _build/default/bench/main.exe -g`?

**Comment by gs0510** [comment]
@diml ``` dune exec perf record --call-graph dwarf _build/default/bench/main.exe -g ``` doesn't work because:
1. dune doesn't have the --call-graph or the -g flags.
2. dune exec after perf record has already ran so dune errors out.

**Comment by diml** [comment]
Ah yes, there is a missing `--`. What about: `dune exec -- perf record --call-graph dwarf _build/default/bench/main.exe -g`?

**Comment by gs0510** [comment]
This works perfectly! I wonder if there's any use of dune exec -- here though since the remainder gives the same result?

**Comment by diml** [comment]
ah yes, that's true actually. BTW, one other option is to add a `(promote (until-clean))` field to your executable stanza. Dune will then copy it to the source directory

**Comment by gs0510** [comment]
perf works perfectly with binary in the source directory with ```(promote (until-clean))```. 

IMO what would be desirable is a way for running perf with `dune exec` or suffixing any such command with `dune exec`
