### ISSUE TITLE
dir stanza does not work in include stanza

### ISSUE THREAD

**Issue by bschommer** [ocaml/dune#2711]
I tried to use the `dirs` stanza in a file which is included in a `dune` file via the `include` stanza and got the error:
```
Error: Unknown constructor dirs
```

**Comment by diml** [comment]
That's a similar situation to #2938

**Comment by anmonteiro** [comment]
I couldn't repro this on Dune 2.7

**Comment by rgrinberg** [comment]
I can confirm that this has been fixed.

**Comment by nojb** [comment]
Was this fixed as a side-effect of #3676 ? If yes, note that we did not version this change in behaviour.

**Comment by rgrinberg** [comment]
Yes indeed. If this ends up being a problem, we can version it retroactively.
