### ISSUE TITLE
Selecting library_flags based on OS type

### ISSUE THREAD

**Issue by anton-trunov** [ocaml/dune#2718]
Is there an easy way to set `library_flags` when building on macOS but not doing that otherwise?
E.g. I'd like to express something like this
```
(library_flags
 (if (= %{os_type} macosx)
  (-cclib -Wl,-keep_dwarf_unwind)))
```

Thank you in advance.

**Comment by nojb** [comment]
You should be able to use `(:include <filename>)` (where `<filename>` can be generated by another rule), see https://jbuilder.readthedocs.io/en/latest/concepts.html#id2

**Comment by diml** [comment]
We should probably add the `(if ...)` form though. Included files are a bit heavy for such cases

**Comment by anton-trunov** [comment]
Yes, please! I noticed that Dune has [boolean constructors](https://dune.readthedocs.io/en/stable/dune-files.html#boolean-language), but not boolean eliminators (at least not general ones).

**Comment by emillon** [comment]
To summarize this issue, "selecting library_flags based on OS type" is possible through `:include`. The `(if)` form is a separate issue, #924. So I'm closing this. Thanks!
