### ISSUE TITLE
Per-package documentation

### ISSUE THREAD

**Issue by mmottl** [ocaml/dune#2736]
Package specifications in `dune-project` do not currently have an entry for `documentation`.  This field is only available project-wide.  I am not sure whether this is by design, but it certainly does not map neatly to OPAM files.

OPAM-files currently have a `homepage` and `doc` entry.  The way I have been using these fields until now was to have `homepage` point to the `github.io` page of the project (not the repository) whereas the `doc` field was set to the API-documentation of that package.

I think it would help to clarify how documentation should be specified.  Here is a suggestion on what might work well:

  * Rename the project-wide `documentation` field `doc` to make it more obviously related to the OPAM field of the same name.
  * Introduce a `homepage` field.
  * If no  project-wide`homepage` is provided, its default should be the `source` (e.g. GitHub) repository.
  * If no project-wide `doc` field is provided, it should point to whatever `homepage` is.
  * Each package in the project also has a `homepage` and `doc` field.  If a package `homepage` is not provided, it should be the same as the project-wide `homepage`.  If a package `doc` page is not provided, it should be the same as the project-wide `doc` page if it was explicitly specified.  If the project-wide `doc` was inferred from the project-wide `homepage` and if a package `homepage` was provided, the package `homepage` should be used instead.

The advantage of the above approach is that most projects  do not have to specify anything if their GitHub page contains all information, thus keeping project specifications clean and compact.  But users can easily define these entries for the whole project and override them on a per-package basis as needed.

**Comment by mmottl** [comment]
It seems that there is already a global `homepage` field that is handled the way I had suggested.  Maybe it's ok not to fill in the `doc` OPAM field if none is provided in the specification, which is the current behavior.

The only thing I believe might still be useful is being able to override `doc` (`documentation` if you want to keep the name) for each package.  Maybe even the `homepage`, though it's much less likely that it will differ on a per-package basis.

**Comment by rgrinberg** [comment]
> Rename the project-wide documentation field doc to make it more obviously related to the OPAM field of the same name.

I am responsible for calling it `documentation` rather than `doc`. My reasoning was as follows:

`doc` is consistent with the all other fields because it is abbreviated. I never liked that opam's naming convention. Additionally, the long term goal for dune is to grow beyond opam and to be just as useful when used with other package managers. Given this, I decided it was more important to use consistent names rather than align with opam.

> If no project-wide doc field is provided, it should point to whatever homepage is.

We also considered that. One reason I don't like this is that there's now no way to signal that in fact there is no doc page. This is not uncommon for new packages for example. I don't feel too strongly about this so you could change my mind here.

Another suggestion would be to add a `(documentation (inherited))` option to allow dune to choose the location.

> The only thing I believe might still be useful is being able to override doc (documentation if you want to keep the name) for each package. Maybe even the homepage, though it's much less likely that it will differ on a per-package basis.

That's an indeed an omission on our part. I'll fix it.

**Comment by mmottl** [comment]
Fair enough if not even better in the long term.  I'd certainly prefer a consistent and integrated way of specifying projects / packages for both building and distributing.  If supplanting rather than mirroring OPAM specifications is your goal, a new naming convention seems fine.

I usually thought of the OPAM `doc` field as pointing to API-documentation.  Command-line tools can then easily open it in a browser.  Developers likely prefer a uniform, project-independent way of doing that.  The raison d'etre of a `homepage` (or GitHub project page) is general documentation (links to manuals, tutorials, etc.) about a project anyway.  `homepage` seems sufficient to capture all of that.

So maybe `documentation`, if seen as API documentation, should not even be a project-wide field but only per-package and optional?  And `homepage` would only remain a project-wide field (possibly inferred from the GitHub repository).  I guess if you needed a different homepage for individual packages, maybe they should become their own project anyway.
