### ISSUE TITLE
Delete `(no_keep_locs)`

### ISSUE THREAD

**Issue by diml** [ocaml/dune#2747]
The doc says it will be deleted in 2.0.0

**Comment by rgrinberg** [comment]
To clarify, this means that we'll never use `-no-keep-locs` then?

**Comment by diml** [comment]
Nope, it just that the `(no_keep_locs)` field was added to support *manual* virtual libraries. It's no longer needed since we have virtual libraries. Given that it was a temporary hack, we stated in the doc that this field was temporary, so we can just delete it.

**Comment by rgrinberg** [comment]
Fixed.
