### ISSUE TITLE
Internal path <module name> is dangling when including stdlib module

### ISSUE THREAD

**Issue by alinpopa** [ocaml/dune#275]
Having the following scenario:
- given a module `lib/bytes.ml`
- as the very first line `include Bytes`
- build using `jbuilder build @install`
- getting the following error:
```
File "lib/bytes.ml", line 1, characters 8-13:
Error: Internal path Hello__Bytes is dangling.
       The compiled interface for module Hello__Bytes was not found.
```
Here's the hello world project that is able to show this issue: https://github.com/alinpopa/jbuilder_hello_modules_clash

```
jbuilder build @install
```
Is this the expected behaviour when doing something like this?
I'm asking that because if not using jbuilder, and going straight to `utop`, I can do a similar thing without any issue:
```
module Bytes = struct include Bytes let concat x y = cat x y end;;
```
```
> Bytes.concat Bytes.empty Bytes.empty;;
- : string = ""
>
```
But if instead of using `include Bytes`, I'm doing `include Core.Caml.Bytes`, everything is fine.

**Comment by rgrinberg** [comment]
I don't think this has anything to do with bytes. Rename your module to `foo.ml` and you will have the same problem. In any case, there doesn't seem anything that we can fix here. Qualifying your module path seems like a good idea and should be more easily done with the new `Stdlib` module.
