### ISSUE TITLE
Custom memoziation data structure

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#2753]
> One thing that could be useful though is to allow to specify a custom dictionary data-structure in Memo, so that for some memoized function we use something better than a hash-table.

From https://github.com/ocaml/dune/pull/2706#discussion_r334912366

**Comment by rgrinberg** [comment]
@diml I assume this would still require the user to provide some sort of a cache like interface:

```ocaml
module Cache : sig
  type ('key, 'a) t
  val create : unit -> (_, _) t
  val set : ('key, 'a) -> 'key -> 'a -> unit
  val get : ('key, 'a) -> 'key -> 'a option
end
```

**Comment by diml** [comment]
Yep. Except I wouldn't call it cache, it's not supposed top drop entries or anything. Maybe just `Store`.

**Comment by rgrinberg** [comment]
One possible issue with this feature is that we know need to store a module along with the `Store.t` itself. Since `Memo` needs to know how to access this store. Are we ok with this small penalty?

**Comment by diml** [comment]
Isn't it what `Table` does already?
