### ISSUE TITLE
Use direct cache filesystem access for tests and Opam sandbox.

### ISSUE THREAD

**Issue by mefyl** [ocaml/dune#2754]

**Comment by mefyl** [comment]
I'm not sure it is a good idea for tests, we probably want to test interaction with the daemon too as it is a significant portion of the code. Actually we should probably run the tests twice, in each mode.

**Comment by diml** [comment]
That makes sense yeah. If we can setup things so that it's easy to run all tests in both modes, then we might as well. I expect that it will be easier to debug problems in the "direct" mode.

**Comment by mefyl** [comment]
I did duplicate the tests in https://github.com/ocaml/dune/pull/2785 to run them both in direct and daemon mode. That PR provides everything that is needed to not use the daemon, (i.e. `DUNE_CACHE_MODE=direct`). I suppose it's on OPAM to use the correct options and we can close this now ?

**Comment by diml** [comment]
yep, sounds good
