### ISSUE TITLE
[Sandbox] Linking foreign archives fails in bytecode

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#2765]
If I run the tests in sandbox mode, I get this failure:

```
----------------------------------------------------------------------------------
* Multiple (foreign_library ...) declarations.
* Mixing C and C++ foreign library archives.
* Passing flags via (flags ...) field.
* Interaction with (foreign_archives ...) stanza.

  $ cat >lib/config.cpp <<EOF
  > #include <caml/mlvalues.h>
  > extern "C" value config(value unit) { return Val_int(CONFIG_VALUE); }
  > EOF

  $ cat >lib/calc.ml <<EOF
  > external add : int -> int -> int = "add"
  > external mul : int -> int -> int = "mul"
  > external config : unit -> int = "config"
  > let calc x y z = add (mul (add x y) z) (config ())
  > EOF

  $ cat >lib/calc.mli <<EOF
  > val calc : int -> int -> int -> int
  > EOF

  $ cat >dune <<EOF
  > (executable
  >  (name main)
  >  (libraries calc)
  >  (modules main))
  > EOF

  $ cat >main.ml <<EOF
  > let () = Printf.printf "%d" (Calc.calc 1 2 3)
  > EOF

  $ rm -rf _build
  $ dune build
        ocamlc main.bc (exit 2)
  (cd _build/.sandbox/0be14d8137f47f3e01f174cec1f7c9d7/default && /Users/rgrinberg/.opam/4.08.0/bin/ocamlc.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -o main.bc -I lib lib/calc.cma .main.eobjs/byte/dune__exe__Main.cmo)
  File "_none_", line 1:
  Error: Error on dynamically loaded library: dllconfig$ext_dll: dlopen(dllconfig$ext_dll, 10): image not found
  [1]
```

It seems like our rule is missing a dependency on the `.so` file.

@aalekseyev @snowleopard Is this a mac only issue perhaps? can one of you confirm with `DUNE_SANDBOX=symlink $ make test`.

**Comment by snowleopard** [comment]
@rgrinberg I just tried `DUNE_SANDBOX=symlink & make test` on my Linux machine and it worked. 

This does seem like a missing dependency, so I should be able to trigger this in a different way.

**Comment by snowleopard** [comment]
@rgrinberg Managed to reproduce.

Lots of other tests appear to be broken with `DUNE_SANDBOX=symlink`. We better add this to CI.

**Comment by rgrinberg** [comment]
> Lots of other tests appear to be broken with DUNE_SANDBOX=symlink. We better add this to CI.

Yeah but unfortunately some tests kind of rely on running in non-sandbox mode. In particular, they rely on predictable paths which sandboxing doesn't allow for.

I would suggest that we start setting the sandboxing property explicitly for tests. We should try to make all rules work with sandboxing and just make exceptions for some rules that don't.

**Comment by aalekseyev** [comment]
One thing we should remember going forward is that the sandboxing mode of dune under test can be potentially different from sandboxing mode of dune that runs the tests.

What makes it more confusing is that the outer DUNE_SANDBOX setting controls both.
