### ISSUE TITLE
single make target to build a release with libaries

### ISSUE THREAD

**Issue by olafhering** [ocaml/dune#2788]
With dune 1.x a single `make release` would build dune itself and also libraries such as `dune.configurator`.

With dune 2.0 a single `make release` would only build dune itself.

I wonder if there is a less hacky way than this to achieve a full build:

````diff
--- a/Makefile
+++ b/Makefile
@@ -21,6 +22,12 @@ install:
 uninstall:
        $(BIN) uninstall $(INSTALL_ARGS) dune --build-dir _boot
 
+release-with-libraries: release
+       $(BIN) build @install $(INSTALL_ARGS) --for-release-of-packages='dune,dune-action-plugin,dune-build-info,dune-configurator,dune-glob,dune-private-libs' --build-dir _olh
+
+install-with-libraries:
+       $(BIN) install $(INSTALL_ARGS) dune dune-action-plugin dune-build-info dune-configurator dune-glob dune-private-libs --build-dir _olh
+
 reinstall: uninstall install
 
 test:

````

**Comment by diml** [comment]
That seems like a valid request to me, though I'm not a fan of having to maintain an additional list by hand in the Makefile.

**Comment by rgrinberg** [comment]
If we’re checking in some generated stuff for bootstrap, perhaps we can just generate a part of the makefile as well?

Although a less hacky way would certainly be preferable

**Comment by emillon** [comment]
@olafhering is this request still relevant? FYI, I think that `--release` is equivalent to `-p <list of all packages>` now.

**Comment by olafhering** [comment]
The build system changed in the past two years. I do not tweak the Makefile anymore.
