### ISSUE TITLE
Pseudo-namespaced library modules are not hidden from the caller

### ISSUE THREAD

**Issue by hakuch** [ocaml/dune#279]
I would expect "inner" modules of libraries compiled by `jbuilder` (like `Library__.Inner_module`) to be relatively well-hidden from clients, but the obfuscated names are popping up in lots of contexts.

# Environment:

`opam`: `1.2`
`ocaml`: `4.05.0+flamba`
`jbuilder`: `1.0+beta13`

# Example

## Goal

- The `example` library has a top-level `Example` module.
- `Example.TYPE` is a module type.
- `Example.Foo` is a module with `Example.Foo.Make : functor (K : Example.TYPE) -> Example.TYPE`

`example/example.opam` is empty.

`example/lib/jbuild`:
```
(jbuild_version 1)

(library
 ((name example)
  (public_name example)))
```

`example/lib/types.ml`:
```ocaml
module type TYPE = sig
  type t
end
```
`example/lib/foo.ml`:
```ocaml
open Types

module Make (K : TYPE) () = struct
  type t = K.t * K.t

  let x k =
    (k, k)
end
```

`example/lib/foo.mli`:
```ocaml
open Types

module Make :
  functor (K : TYPE) () -> TYPE
```

`example/lib/example.ml` (top-level module):
```ocaml
include Types

module Foo = Foo
```

## Outcome

```
$ jbuilder build
$ jbuilder utop example/lib
# open Example ;;
# show Foo ;;
module Foo = Example__.Foo
module Foo = Example__Foo
module Foo :
  sig
    module Make : functor (K : Example__.Types.TYPE) () -> Example__.Types.TYPE
  end

# module M = Foo.Make (struct type t = int end) ;;
# show M ;;
module M : functor () -> Example__.Types.TYPE
```

Building documentation with `odoc` (`jbuilder build @doc`) yields similar references to all the `Example__` names.

**Comment by rgrinberg** [comment]
As unfortunate as this is, I don't know how much can be done in jbuilder to fix this - the compilation scheme for aliases is fixed. I wonder if odoc can do better with the names though.

Here's an example of the bad docs: http://docs.mirage.io/base/index.html

**Comment by lpw25** [comment]
That example of `__` appearing in types is a deficiency in OCaml's `-short-paths` implementation. I wrote a better implementation of short paths which would avoid it, and is already used in `merlin`, but I haven't yet upstreamed it into the compiler.

> Here's an example of the bad docs

That page isn't generated by odoc. Odoc already does quite a bit of work to hide these names, although it's not perfect yet.

**Comment by lpw25** [comment]
Odoc's output would probably improve if you used:

```ocaml
module Types = Types

include Types

module Foo = Foo
```

since it is trying to rewrite `Example__.Types` to `Example.Types` but `Example.Types` doesn't exist.

**Comment by hakuch** [comment]
This is indeed unfortunate, though I appreciate the advice and input.

@lpw25, your advice about aliasing `Types` does reduce the `__` names, but it still doesn't help me achieve the goal of having the module types being defined as part of the top-level module.

I know that defining a top-level `.mli` file (`example.mli`) would allow me to precisely specify everything (as @dbuenzli often does), except it comes with the disadvantage, AFAICT, of either duplicating the interface declarations of all inner modules or not constraining any modules inside the implementation of the library (yuck!).

**Comment by hcarty** [comment]
@hakuch You can have something like the following, which will expose `Mylib.A` and `Mylib.B`, each constrained by their corresponding mli files.
```
src/
  mylib.ml
  mylib.mli
  a.ml
  a.mli
  b.ml
  b.mli
  jbuild
```
mylib.ml
```ocaml
module A = A
module B = B
let f x = x + 1
```
mylib.mli
```ocaml
module A = A
module B = B
val f : int -> int -> int
```

**Comment by hakuch** [comment]
@hcarty That works well for inner modules (thanks!) but I believe that top-level module types (my `Example.TYPE`) cannot be included in the same way without duplicating their definition.

**Comment by hcarty** [comment]
@hakuch I'm so sorry - I'm not sure how I managed to do it, but I completely skipped over your example in the original post!

**Comment by lpw25** [comment]
> but it still doesn't help me achieve the goal of having the module types being defined as part of the top-level module.

I don't follow you here. Note that my example still had `include Types` in `example.ml`.

**Comment by rgrinberg** [comment]
We've added the ability to hide modules using the `(private_modules ..)` field. I'm not sure if this is good enough, but hiding cmi's is the best dune can do to help out with this without more compiler support.
