### ISSUE TITLE
The cinaps stanza adding actions to @runtest isn't very flexible

### ISSUE THREAD

**Issue by NathanReb** [ocaml/dune#2801]
Currently the cinaps stanza adds all cinaps actions to the `runtest` alias. This has several drawbacks which I believe could be fixed by attaching those to a separate `cinaps` stanza:
1. If you're using cinaps to generate non-test code, and in particular main library code that your tests depend upon, it induces a dependency cycle between library and runtest alias. While you can still run `dune runtest --auto-promote || dune runtest`, you still potentially have to go through a failing `dune runtest` if the cinaps-generated code is dramatically out of sync or has not yet been generated.
2. Cinaps-generated code could potentially differ from released code, for instance if it contains `%%VERSION%%` or any other such placeholder, meaning that if you use the `cinaps` stanza, you can't test released code through opam as the cinaps actions will fail.

Moving cinaps actions to a separate alias would allow to solve both by:
1. specifying a clear set of dependencies `runtest` -> `build` -> `cinaps --auto-promote` and therefore a succeeding sequence of operation to build and test my project
2. allowing to choose whether I want to attach the `cinaps` stanza to my build or test commands/alias.

**Comment by NathanReb** [comment]
I'm happy to add a `1.1` version of the cinaps feature where the actions are attached to a `cinaps` alias.

We could also eventually add an optional field to the stanza where users can specify the name of the alias for the cinaps actions, defaulting to runtest.

**Comment by diml** [comment]
What dependency cycle are you thinking about? There should be none as we rely on the diff/promotion mechanism to break the cycle.

2 seems fishy to me. Cinaps tests should definitely pass in released code.

Attaching cinaps validation to the runtest alias has the advantage that it ensures the cinaps generated code is as up to date as the tests, which are often tested in the CI.

In any case, changing the implicit default in a minor release doesn't seem right, it would have to be a 2.0. I suggest to start by making the alias to which cinaps validation is attached configurable.

**Comment by NathanReb** [comment]
There's no actual dependency cycle but from a user perspective it feels like one. As an example here's what can happen:
1. I update the cinaps code
2. I run `dune build` and it fails because the generated code wasn't updated and I was relying on changes there from some other places in the code.
3. I run `dune runtest --auto-promote` to update the generated code. That part will work but the outcome of the command will still be a failure because I can't build my test since they depend on my currently broken library.
4. Only now can I hope to successfully run `dune build` or `dune runtest`

While there are workarounds to that like running `dune runtest --auto-promote lib/` or another more specific command I feel like it still is a little bit weird to have to go through that much effort not to get inappropriate errors during my dev cycle.

I agree `2` is probably a little bit fishy and if we rule it out it make sense to check that the generated code is up to date. What troubles me is that, as a developper, I want this to be checked before I even start building my library so I'd like the cinaps actions to be a dependency of my library. I feel like the only reason why we attach it to `runtest` is so that the `cinaps` package is a test and not a build dependency, which also makes sense!

I'm not sure what's best here.

**Comment by diml** [comment]
I see. Initially this was thought for a setup where you run dune in watch mode and the cinaps code just gets updated as you edit.

What about attaching the cinaps validation to both the `runtest` and `cinaps` aliases?

**Comment by NathanReb** [comment]
Yes that sounds good!

**Comment by diml** [comment]
That's settled then. We can do this change without thinking too much about versioning. If users already have an alias stanza, it's likely used for cinaps validation already.
