### ISSUE TITLE
Missing cmt files for some modules

### ISSUE THREAD

**Issue by smondet** [ocaml/dune#2805]
I am having the same issue as here: 
https://stackoverflow.com/questions/51206132/how-to-jump-to-function-definition-in-ml-not-mli-in-emacs-merlin-mode
(`merlin-locate` bringing me to an `.mli` even with the `'ml` preference set)

It seems it is because dune 1.11.3 does not build all the required `cmt` files.

This is the code: https://gitlab.com/tezos/flextesa/tree/sm@qol-improvements

The generated `.merlin` has this line:

```
B ../../_build/default/src/lib/.flextesa.objs/byte
```

and in this directory, all the modules have `.cmi` and `cmti` files but only some of them have their `cmt`

I haven't figured out what makes the one that have `cmt` files special, it looks random so far.

**Comment by smondet** [comment]
If I run `dune utop src/lib` then all the `cmt`s get created.

**Comment by rgrinberg** [comment]
> It seems it is because dune 1.11.3 does not build all the required cmt files.

What target were you using before? If `$ dune build @check` doesn't build some `.cmt` file I would say that's a bug with dune.

**Comment by smondet** [comment]
The build command is `dune build src/test/main.exe src/app/main.exe` 

I didn't know about `@check` (in my case it seems to try to build a bunch of useless stuff need to tweak the data-only-dirs I guess), but indeed all the `cmt`s seem to be there
( https://dune.readthedocs.io/en/stable/usage.html#built-in-aliases )

**Comment by rgrinberg** [comment]
If your .exe target is native then indeed the cmt’s might not be generated as we only do that on the bytecode targets. Try to see if you can incorporate @check into your workflow. If that isn’t sufficient then let us know

**Comment by rgrinberg** [comment]
Closing this issue as what is described in this issue is expected behavior. We have a separate target for guaranteeing cmt's and cmti's are built. Feel free to let us if there are some issues with the recommended workflow.
