### ISSUE TITLE
[ocamlformat] pre-commit hook

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#2813]
As discussed in the meeting, having a pre-commit hook would be useful to make sure that devs don't forget to format their code. It's even more important to do it on every commit as it cannot always be applied retroactively through rebasing.

**Comment by zjhmale** [comment]
I think https://pre-commit.com/ may help

**Comment by rgrinberg** [comment]
We've incorporated an ocamlformat check in CI to make sure submit patches are well formatted.
