### ISSUE TITLE
OPAM semantic tags not auto-generated

### ISSUE THREAD

**Issue by mmottl** [ocaml/dune#2817]
It seems that package tags in `dune-project` files, e.g. `(tags (clib:sqlite3 clib:pthread))` are not added to auto-generated OPAM files.  This can be worked around by creating a `[pkg_name].opam.template` file, though this is obviously inconvenient.

The issue is present in `dune` version `1.11.41`.

**Comment by emillon** [comment]
Hi!

These tags are only added when `(lang dune 2.0)` is used (see #2504), but until dune 2 is released (very soon) you have to use a template file, indeed.

Thanks!
