### ISSUE TITLE
'Variables for artifacts' working in dune 1.10?

### ISSUE THREAD

**Issue by houndofsound** [ocaml/dune#2837]
the docs say:
'These variables can appear wherever a Dependency specification'

is it actually more limited in context than that?

in a rule:
 (deps %{cma:test})

I get:
Error: unknown macro %{cma:....}

I tried using it in other contexts with the same result.

I would like to obtain the directory of a particular .cmi file  for making a (flag (-I ... )) expression
- I cannot specify a library dep as it would cause a rebuild.
%{project_root} and %{workspace_root} expand to ../.. like paths so cannot build a path that way.
is there a work-around?
thanks!

**Comment by nojb** [comment]
I think this is a dune 2.0-only feature, so it would not work with dune 1.10. And even in dune 2.0 there are some limitation as to the contexts where these forms can be used. On the other hand, have you tried using the form `%{lib:<public-library-name>:<filename>}` which can be used to access the path of a file `<filename>` installed by the public library `<public-library-name>`?

Having said that, all of these forms imply a dependence on the corresponding file, so it may not be what you are looking for.

It is hard to know if there is a work-around without knowing what you are really trying to accomplish.

**Comment by houndofsound** [comment]
my need is to build a library that depends on a single cmi file from another library.
or better said, the build would succeed if it could specify a directory include for the other library's artefacts.
I specifically do not want to depend on that other library via a (library ...) line and thus potentially cause it to re-build and change the .cmi I am interested in (as it was first created).
I am building stanzas via the ocaml syntax dune files and it would be convenient to do it there,
_if_ I could get hold of project/target directories to get the same relative path the compilers are using:
ie. -I %{target - project}/.test.objs/byte    -I %{target - project}/.test.objs/native

I can't get any hackier unfortunately!

**Comment by houndofsound** [comment]
%{lib:<public-library-name>:<filename>}  worked and got me the cmi which I can put somewhere known: %{project_root}  then added a flag of '-I .' for the compiler to pick it up.
so done within a rule.
thanks!

**Comment by nojb** [comment]
Great!

**Comment by houndofsound** [comment]
... but that has made it apparent what my true, subconscious objective was!
ideally I would like to target an individual cmo/cmx and have it compile in the same environment (ocaml flag, preprocessor clauses, kind, libraries  ... ) as it would have done if incorporated in a library or executable stanza.
Rules don't seem to  allow the same specification though I imagine (preprocessor ...) clauses translate 
ultimately into such. 
And it seems that a target of %{cmo:...} is Dune 2.0 only, as well.

the only work around I can come up with is to wrap that one target file in a library stanza, invoke it, then extract the cmo/cmi artefacts from its build area with the aforementioned special syntax.
I'd love to hear there is a better way?!

**Comment by nojb** [comment]
Indeed, what you describe seems to be exactly the use-case for the "variables for artifacts", but you will have to wait for dune 2.0 for that (it should be coming out really soon now :)).
