### ISSUE TITLE
Dune-based Coq projects FTBFS since coq/coq#8642

### ISSUE THREAD

**Issue by erikmd** [ocaml/dune#2842]
**Kind:** bug

Since https://github.com/coq/coq/pull/8642, `coqdep` outputs another line involving `.vos` files:

```
$ cat _build/default/BigN/BigN.v.d
BigN/BigN.vo BigN/BigN.glob BigN/BigN.v.beautified BigN/BigN.required_vo: BigN/BigN.v SpecViaZ/NSig.vo SpecViaZ/NSigNAxioms.vo BigN/NMake.vo
BigN/BigN.vio: BigN/BigN.v SpecViaZ/NSig.vio SpecViaZ/NSigNAxioms.vio BigN/NMake.vio
BigN/BigN.vos BigN/BigN.vok BigN/BigN.required_vos: BigN/BigN.v SpecViaZ/NSig.vos SpecViaZ/NSigNAxioms.vos BigN/NMake.vos
```

As [Dune's `(using coq 0.1)`](https://dune.readthedocs.io/en/stable/dune-files.html#coq-theory) is not aware of these `.vos` files, building any Dune-based Coq project (e.g. [coq-bignums](https://github.com/coq/bignums/issues/26)) with a recent `coq.dev` will now fail [here](https://github.com/ocaml/dune/blob/ea54f43a2ccf7d96d6ce91b7126f8b867be4c467/src/dune/coq_rules.ml#L42)…

Cc @ejgallego @charguer FYI

**Comment by charguer** [comment]
Correct me if I'm wrong, but I suspect that Dune's `coq_rules` ought to be version dependent somehow, else there is no way it can deal with evolution of the `coqdep` tool. Doesn't this qualify as a Dune bug?

**Comment by ejgallego** [comment]
I think we should:
- make Dune's `coqdep` parsing more resilient.
- restore old coqdep behavior, so it only produces the rules when the `.vos` mode is enabled.

**Comment by SkySkimmer** [comment]
>restore old coqdep behavior, so it only produces the rules when the .vos mode is enabled, this will allow dune 1.x to work with Coq's 8.11

This is now done (https://github.com/coq/coq/pull/11074)

**Comment by ejgallego** [comment]
This should be fixed indeed.
