### ISSUE TITLE
Mixing coq and ml files in the same directory

### ISSUE THREAD

**Issue by cpitclaudel** [ocaml/dune#2857]
Hi there,

Is there a way to mix a Coq library with `(include_subdirs qualified)` and an OCaml library in the same folder?

Some context: I have `x.v` that extracts `x.ml`, and then I'd like to compile `x.ml`; but since my dune file contains `(include_subdirs qualified)`, dune complains that `Error: (include_subdirs qualified) is not supported yet`.

Thanks again for the hard work.

**Comment by ejgallego** [comment]
Unfortunately there is no way to do that yet; a solution is to extract files to a subdir, then use in that subdir `(include_subdirs no)`

**Comment by ejgallego** [comment]
Note that fixing https://github.com/ocaml/dune/issues/3314 will fix this issue too [almost a duplicate but the linked one is more general than this one]

**Comment by Alizter** [comment]
This is now possible from 3.7 onwards as support for (include_subdirs qualified) was added for OCaml. Whether or not you want to pick the behaviour separately is a different issue however.
