### ISSUE TITLE
Allow to definitely set the root of a project

### ISSUE THREAD

**Issue by grayswandyr** [ocaml/dune#2869]
Hi,
thanks on the good work on dune.

I'd like to set the root of my project in a way that definitely prevents dune to look in ancestor directories of the said root. This is already possible with the `--root` option but I'd like this to be deduced by dune itself just by looking at a dune/dune-project/dune-workspace (whichever you prefer) instruction. 

Use case: I could not compile anymore a working project and got tens of lines listing dune errors. It took me looong while to figure out I had an old dune-workspace file hanging in my home directory, which was then taken as the root of all my projects. The said projects were tens of student projects producing tons of error message :-) so much I could not see dune printing it had chosen my home as the root... 

Using a command-line option doesn't seem enough to me, as by definition, I could not know a problematic file was hanging in an ancestor directory. In fact, I find it quite disturbing that the semantics of `dune build` varies depending on what there is *outside* (morally) of your project.

**Comment by diml** [comment]
The only way to prevent that would be to make dune stop at the first `dune-project` or `dune-workspace` file. However, that would break the composability aspect of dune.

This problem with the home directory has come up a few times. I propose the following: if `dune` detects that the root is set to the home directory or any higher-level directory, it errors out immediately. Then we could add an option to allow the root to be such a directory for special cases.

**Comment by grayswandyr** [comment]
I only use dune for small projects so I don't grasp the full picture, but I was thinking only `dune` files were indeed made for various source directories to be composable.

Perhaps my question is stupid but are we sure composability-by-default is the most needed workflow by dune users (apart form that of the above nature, that of plain `dune` files)? Or should *this* rather be an option? Is there a way to know how many public projects using dune rely on this composabiity? 

If indeed this is the most needed workflow, I think the problem is not really that of the HOME or a higher-level directory, it's rather that -at least as far as I'm concerned- I think the expected behavior would be to be able to "tag" a directory as a *root*, forbidding to explore higher levels (unless I use a command-line option as the one you propose). 

It's a bit far-fetched but suppose some other project (not even related to OCaml) relies on files named "dune", and then you git checkout this project in another part of the user hierarchy, and suddenly you can't compile your OCaml projects anymore... From my -certainly limited- perspective, it seems sensible to just be able to work in user-defined "closed world".

**Comment by diml** [comment]
Just to add a bit of context, when looking for the root, `dune` only looks for `dune-project` and `dune-workspace` files. It ignores `dune` files. A `dune-project` file marks the root of a project while `dune-workspace` marks the root of a workspace. A workspace can be composed of several projects, that's why it's important for `dune-workspace` files to have precedence over `dune-project` files.

If we stopped at the first `dune-workspace`/`dune-project` file, it means that if we were in a big workspace and changed the directory to a sub-directory, we'd be in a sub-world with its own `_build` directory etc. But maybe that's acceptable. There has been situation in which I wished I had this behaviour.

Regarding what should be the most needed workflow, I feel like we need a bit more feedback. Maybe you could ask on discuss to see what other users think?

**Comment by grayswandyr** [comment]
I will; but first to make things clear: is there another reason for walking upwards (until finding the highest `dune-workspace`) than just the fact that a user may run `dune build` (say) in a given sub-directory while she would like the build to start at a higher level? (If this is the only reason, I personnally  don't find it very compelling.)

**Comment by diml** [comment]
If you use the same higher-level root, then the build artifact will be shared. For instance, if you start by building everything from the root and then go to a sub-project, you'll be able to do things such as `dune build`, `dune utop`, etc... without rebuilding from scratch.

Sharing the root also mean sharing the libraries. For instance, let's assume that you have the following workspace:

```
dune-workspace
a/dune-project
a/dune <- defines library a
b/dune-project
b/dune <- defines library b that uses library a
```

If you run `dune` from `b`, currently it will resolve the library dependency `a` to the one in `../a`. If the detected root was instead `b` when run from `b`, then `a` would resolve to a library `a` that is already installed on the system. And if no library `a` is installed, compilation would fail.

Sharing the same root also ensure that we use the same workspace configuration. For instance, a user might setup several build contexts via the `dune-workspace` file. If we were stopping at the first `dune-project` file, we wouldn't see the `dune-workspace` file and would instead use the default workspace configuration, ignoring the user specified one.

**Comment by grayswandyr** [comment]
Right, so -from my perspective- I'd advocate for what you say above: the first `dune-workspace` met (incl. the current directory) when walking upwards would be a good candidate to mark the root. I'll switch to [Discuss now](https://discuss.ocaml.org/t/finding-the-root-of-a-dune-project-request-for-comments/4676), thanks for the time spent explaining!
