### ISSUE TITLE
memory leak in `dune build -w`

### ISSUE THREAD

**Issue by c-cube** [ocaml/dune#2870]
somehow, if I leave `dune build @all -w` in a project that I heavily modify with lots of errors all the time (writing new modules, and saving every few seconds, etc.) dune takes more and more RAM.

Here's a screenshot of it taking 4GB (before I kill it).

![2019-11-07-142351_737x145_scrot](https://user-images.githubusercontent.com/1274291/68484433-dbdb6480-0202-11ea-9c55-7c896862c3d8.png)

**Comment by diml** [comment]
Alright, there must be a memory leak somewhere. Thanks for the report!

**Comment by rgrinberg** [comment]
@c-cube please re-open if you can still observe this leak
