### ISSUE TITLE
Raise an error when building a defined but empty package

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/dune#2882]
From a beginner point of vu, it seems a bit odd to not get any errors when building a project that doesn't install anything due to a lack of `(public_name ...)` or other things.

For instance, see the PR of someone who made the mistake and would have been unnoticed if I hadn't looked at the project more in details: https://github.com/ocaml/opam-repository/pull/15262

For example, if you define a project as such:
```
$ echo '(library (name some_package))' > dune
$ touch some_package.opam
```
`dune build -p some_package` doesn't do build anything but produces `some_package.install` which doesn't install anything (except an empty `META` file). This is prone to mistake from beginners trying to release their first package in opam and I think dune should raise an error to avoid this type of mistake.

**Comment by diml** [comment]
Agreed. For special cases where one would really want an empty project, we could add a special `(may_be_empty)` field to the `package` stanza.

**Comment by kit-ty-kate** [comment]
Can this issue be addressed? Other packages that I thought was good to merge in opam-repository did not install anything besides succeeding to build. See https://github.com/ocaml/opam-repository/pull/16151

**Comment by rgrinberg** [comment]
We can give you some pointers if you want to take a stab at this.

**Comment by kit-ty-kate** [comment]
> We can give you some pointers if you want to take a stab at this.

sure

**Comment by rgrinberg** [comment]
Actually, I'm not sure how this feature works with `enabled_if`. Suppose we have a package with a single file attached conditionally:

```
(install
 (files ..)
 (section ..)
 (enabled_if ..)
 (package ..))
```

Now the package is empty only if the `enabled_if` evaluated to `false`. How would this check work in this case?

**Comment by kit-ty-kate** [comment]
From my point of vue, the check would do something like:
1) for each packages, check what they would install
2) ignore `enable_if` in this check
3) if one is empty, raise an error if `(lang dune >= whichever version this feature gets added in)`, unless tagged with `(may_be_empty)`.
4) with previous versions of `(lang dune ...)` only display a warning if dune build is called explicitly for the empty package (e.i. `build -p empty_pkg @install`)

If a package may be empty, regardless of whether it as `(enable_if ..)` or not, a warning should appear unless the package is tagged as `(may_be_empty)`. I suspect packages with just `(enable_if ...)` sections are almost inexistent anyway.
