### ISSUE TITLE
Feature request: shell autocomplete for dune commands

### ISSUE THREAD

**Issue by raphael-proust** [ocaml/dune#2897]
There are multiple subcommands for dune (`dune build`, `dune format-dune-file`, `dune promote`, etc.) some of them take potentially long options and additional targets. It'd be useful to have autocompletion in the shell for dune commands.

**Comment by diml** [comment]
(requested in #126)

Agreed. Would you be happy to help with this?

**Comment by raphael-proust** [comment]
(ah damn, I search autocomplete and autocompletion but forgot to drop the "auto". I'll close in favour of #126.)

I don't have a lot of bandwidth, but I'll have a look at cmdliner anyway and see if I can do something.
