### ISSUE TITLE
Strange foreign_archives name resolution

### ISSUE THREAD

**Issue by debugnik** [ocaml/dune#2914]
I was following the [foreign build sandboxing](https://dune.readthedocs.io/en/stable/foreign-code.html#foreign-build-sandboxing) guide on 2.0, when I found out that `(foreign_archives foo/foo)` resolves as `libfoo/foo.a`, instead of `foo/libfoo.a`.

**Comment by debugnik** [comment]
As an aside, the `targets` declaration in the docs won't work either: `(targets libfoo.a)` declares that `libfoo.a` will be generated in the current directory, and `foo/libfoo.a` is not allowed as a target.

Am I missing something? I'd rather not put a dune file inside a vendored source tree. Maybe paths should be allowed for targets inside `data_only_dirs`?

For now, I'm copying the archive to the parent directory. That's not what the docs seem to indicate though.

**Comment by snowleopard** [comment]
@debugnik Thanks for the report! This does look like a bug; I'm looking into it.

**Comment by snowleopard** [comment]
@debugnik I've implemented support for relative foreign archives in the `library` stanza in #2920.

Note that to make the example work, it will still be necessary to either copy the foreign archive (as you currently do) or add a `dune` file into the `foo` directory. Allowing `foo/libfoo.a` in `targets` seems complicated, so I will just fix the example in the documentation.

**Comment by snowleopard** [comment]
#2920 has been merged, so I think this issue is resolved:
* `(foreign_archives x/y) is now correctly resolved to `x/liby.a` and then correctly located during linking.
* The documentation now includes the previously missing copying step.
