### ISSUE TITLE
'library not found' false negative

### ISSUE THREAD

**Issue by houndofsound** [ocaml/dune#2919]
I have a library in the directory of a project and it has been automatically
seen and used as expected.
and now, without any modification to it or its dune file,
the project build is claiming that it cannot find the library ( (libraries   xxx) specified )
I have changed nothing relating to this library.
and it builds fine with [dune build mylib/xxx.cma]

I can only imagine a hidden disqualification within dune that has been inadvertently triggered.
are there any?
(using dune 2 from sources pre-release)

**Comment by houndofsound** [comment]
oddly, if I [cp -a] the library directory and rerun dune, it compains the library is defined
twice!

**Comment by rgrinberg** [comment]
Could you give us a reproducible example?

**Comment by houndofsound** [comment]
sure. what's your shipping address?!
I thought I'd ask what dune's disqualification criteria might be before doing a brute force search of  taking out directories or trawling the dune code base.

**Comment by houndofsound** [comment]
that's disqualification criteria in the presence of schizophrenically finding no library at the same time as finding two of the same name.

**Comment by houndofsound** [comment]
the problem turned out to be initiating a [dune exec ...] from within a [dune exec ...]
which created, as an unintended side-effect,  a dune-project file in an inner directory thereby making it appear as a separate workspace/project.
is this to do with the INSIDE_DUNE env variable?

**Comment by diml** [comment]
Yes, when `INSIDE_DUNE` is set `dune`  uses the current directory as the workspace root. Among other things, this is to avoid the inner and outter dune sharing the same build directory, which wouldn't work.

**Comment by houndofsound** [comment]
ok, thank you
