### ISSUE TITLE
[windows] dune clean fails with Error: unlink: _build\log: Permission denied

### ISSUE THREAD

**Issue by ejgallego** [ocaml/dune#2921]
When updating our windows workers to Dune 2.0.0 `dune clean` has started to fail with:
```
Error: unlink: _build\log: Permission denied
```

@nojb has also seen it so this seems worth reporting.

**Comment by ejgallego** [comment]
Note that this is a regression in 2.0

**Comment by diml** [comment]
My guess is that this has to do with the cache daemon (/cc @mefyl)
