### ISSUE TITLE
Dune dependency logic for installed libraries

### ISSUE THREAD

**Issue by prahlada** [ocaml/dune#2922]
hi,

  I have a very basic question regarding the dependency calculation logic of dune. It appears that dependency on installed libraries are not taken into account for rebuilding source code.

The situation I have is as follows (I am attaching a tgz file of the code):
- library 'b' depends on library 'a' (library 'a' is installed in site-lib)
- Library 'a' changes
- running 'dune build' on library 'b' does not detect change in library 'a'.

Concrete example:
> tar xvfz example.tgz
> cd moda; dune build; dune install
> cd modb; dune build; dune runtest
>>> Edit moda/moduleA.ml and change 42 to 41
> cd moda; dune build; dune install
> cd modb; dune build; dune runtest <<<<< At this point I expect the test to fail!!

Please let me know if I am making some incorrect assumptions.

Prahlad
[example.tar.gz](https://github.com/ocaml/dune/files/3890877/example.tar.gz)

**Comment by diml** [comment]
I just gave this a try and I couldn't reproduce this issue. On my machine, changing and reinstalling moda causes `runtest` in modb to fail.

**Comment by prahlada** [comment]
I am using Dune 1.06. I will check with the latest version.

**Comment by prahlada** [comment]
Works as expected in Dune 2.0.0
