### ISSUE TITLE
Adding menhir/ocamlyacc flags to env

### ISSUE THREAD

**Issue by bschommer** [ocaml/dune#2924]
In a project with multiple invocations of menhir or ocamlyacc it would be useful if one could specify the common menhir/ocamlyacc flags like the ones for the ocaml compiler.

**Comment by nojb** [comment]
As a workaround you can use `(:include ...)`.

**Comment by bschommer** [comment]
That would work, however I think for some of the stanzas it would be nice if their flags could be defined globally like for the ocaml compiler. If there is interest from the developer side I would try to make a PR implementing this.

**Comment by diml** [comment]
That seems acceptable to me

**Comment by bschommer** [comment]
The menhir version is available, I don't really need one for ocamlyacc, however if wanted I could give it a try.
