### ISSUE TITLE
dune build @all should not build rules attached to @runtest alias

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#2926]
This is by analogy with the pre-2.0 aliases with actions attached to `runtest`.

**Comment by diml** [comment]
Is it specific to `runtest`?

**Comment by nojb** [comment]
To me it would be reasonable to apply the same criteria for all rules : they are triggered by `@all` if and only if they are not themselves attached to a specific alias themselves.

**Comment by diml** [comment]
I agree for rules without targets, but I'm not 100% for rules with targets. My mental model is that `@all` means "all the files that can be built"
