### ISSUE TITLE
`tests` stanza seems to ignore `deps` since dune 2.0

### ISSUE THREAD

**Issue by MattWindsor91** [ocaml/dune#2935]
I recently upgraded a project that was using dune 1.11 to dune 2, and updated the language version at the the same time.  It seems that a `test` stanza with `deps` that previously seemed to work now fails to copy over any dependencies:

```scheme
(tests
 (names config config_failures delitmus dump_header explain fuzz_replays
   fuzz_action_list herd_observations litmus_observations litmusify)
 (preprocess
  (pps ppx_jane))
 (libraries result yojson sexplib0 base.caml core_kernel core stdio fmt
   common_cmd fpath ppx_yojson_conv.runtime-lib travesty travesty.base_exts
   plumbing act.asm act.backend act.backend_herd act.backend_litmus
   act.c_mini act.common act.config act.delitmus act.fuzz act.litmus
   act.sanitiser act.state act.utils)
 (action
  (run %{test} input))
 (deps
  "input/asm/x86/att/spec.json"
  (glob_files "input/fuzz/replays/*.litmus")
  (glob_files "input/fuzz/replays/*.trace")
  (glob_files "input/config/valid/*.conf")
  (glob_files "input/config/failures/*.conf")
  (glob_files "input/litmus/*.litmus")
  (glob_files "input/asm/x86/att/*.s")
  (glob_files "input/observations/herd/*.txt")
  (glob_files "input/observations/litmus/*.txt")))
```

All of the `deps` are local to the directory in which the `dune` file is located, and exist to put the various test inputs into the `_build` directory tree so that the test actions can work.

Dune is definitely parsing the `deps` stanza, but no dependencies appear to be copied (and so the commands fail to read the various files in `input`, and changing the dependencies to point to files that don't exist doesn't trigger any errors from Dune.

On the other hand, this form seems to work fine, but seems comparatively tedious/low-level:

```scheme
(executables
 (names config config_failures delitmus dump_header explain fuzz_replays
   fuzz_action_list herd_observations litmus_observations litmusify)
 (preprocess
  (pps ppx_jane))
 (libraries result yojson ppx_yojson_conv_lib sexplib0 base.caml core_kernel
   core stdio fmt common_cmd fpath travesty travesty.base_exts plumbing
   act.asm act.backend act.backend_herd act.backend_litmus act.c_mini
   act.common act.config act.delitmus act.fuzz act.litmus act.sanitiser
   act.state act.utils))

(rule
  (deps (glob_files "input/config/failures/*.conf"))
  (action (with-stdout-to config_failures.output (run ./config_failures.exe input))))

(rule
  (alias runtest)
  (action (diff config_failures.expected config_failures.output)))
```

Am happy to give more information/try various things.

**Comment by diml** [comment]
I tried writing a reproduction case but couldn't: 1a12fca749ac4b3e905f95e03ac3f64dd0bc4631

In my case, the files are copied correctly. Do you have a case I could try to reproduce?

**Comment by MattWindsor91** [comment]
@diml ah, interesting.

I don't have a MWE at present (as the above got yanked directly out of an existing codebase), but I'll try get around to experimenting with one.  I also need to check whether it's happening with language version 1.11 on dune 2.0, as I changed both language version _and_ dune version at the same time.

**Comment by rgrinberg** [comment]
Closing for staleness. Don't hesitate to re-open if you manage to reproduce this.
