### ISSUE TITLE
documentation error on globbing?

### ISSUE THREAD

**Issue by houndofsound** [ocaml/dune#2939]
the manual (latest) says to put multiple glob patterns between {..} but:
```
1 | (copy_files {yy, xx} )
                                ^^
Error: Too many argument for copy_files
```
and 
```
1 | (copy_files {xx}  )
                         ^^^^
Error: invalid glob: :'}' without opening '{'
```

**Comment by houndofsound** [comment]
the manual (latest) says to put multiple glob patterns between {..} but:
```
1 | (copy_files {../tt.ml, xx} )
                           ^^^
```
and
```
Error: Too many argument for copy_files
1 | (copy_files {../tt.ml} )
                ^^^^^^^^^^
Error: invalid glob: :'}' without opening '{'
```

**Comment by houndofsound** [comment]
the manual (latest) says to put multiple glob patterns between {..} but:
```
1 | (copy_files {../tt.ml, xx} )
                           ^^^
Error: Too many argument for copy_files
```
and
```
1 | (copy_files {../tt.ml} )
                ^^^^^^^^^^
Error: invalid glob: :'}' without opening '{'
```

**Comment by aalekseyev** [comment]
Have you tried without a space (`{../tt.ml,xx}`), or in quotes (`"{../tt.ml,xx}"`)? I wouldn't expect the first example to work as written.

(The "without opening '{' error seems very confusing in either case)

**Comment by aalekseyev** [comment]
(neither of my suggestions work, something seems to be wrong)

**Comment by aalekseyev** [comment]
Oh, I know what it is. :-(

We first split on the slash to separate the directory from the glob.
We obtain something like `{ dir = "{.."; glob = "tt.ml,xx}" }`
We then parse the glob and that fails with this inscrutable error message.

Actually I think the documentation is pretty clear that this is how it works (even though I forgot about it). Not sure how we can improve the documentation, we should instead try to improve the error message.

**Comment by houndofsound** [comment]
so how should multiple files be specified?! 
I agree the documentation was clear but it also led me to believe the example given was
correctly specified.

**Comment by aalekseyev** [comment]
One glob in dune can't refer to files coming from multiple directories.
You'd have to write multiple `copy_files` stanzas:
```
(copy_files ../tt.ml)
(copy_files xx)
```

**Comment by houndofsound** [comment]
sorry, shortcutted example.
how about (copy_files {../x, ../y})
that's how the docs say to write it but it doesn't work.

**Comment by aalekseyev** [comment]
Where in the doc does it say this?

**Comment by houndofsound** [comment]
copy_files section says (copy_files <glob>),
and in the Glob section:
{<glob1>,<glob2>,...,<globn>} matches any string that is matched by one of <glob1>, <glob2>, …

the {..} are highlighted in red along with the rest, as is the case with [<set>] syntax for characters.
are {..} and [..] meta-characters as <set> is meta for ... a set?!
if so I am lost in Meta World.
without those characters:
```
1 | (copy_files ../tt.cmi,../tt.cmo)
                ^^^^^^^^^^^^^^^^^^^
Error: Cannot find directory: tt.cmi,..
```

**Comment by houndofsound** [comment]
copy_files section says (copy_files <glob>),
and in the Glob section:
```
{<glob1>,<glob2>,...,<globn>} matches any string that is matched by one of <glob1>, <glob2>, …
```
the {..} are highlighted in red along with the rest, as is the case with [<set>] syntax for characters.
are {..} and [..] meta-characters as <set> is meta for ... a set?!
if so I am lost in Meta World.
without those characters:
```
1 | (copy_files ../tt.cmi,../tt.cmo)
                ^^^^^^^^^^^^^^^^^^^
Error: Cannot find directory: tt.cmi,..
```

**Comment by aalekseyev** [comment]
I thought I explained this, but I guess it didn't work. At the beginning the doc says:

> - anything before the last / is taken as a literal path
> - anything after the last /, or everything if the glob contains no /, is interpreted using the glob syntax

So what you wrote is interpreted as `{ dir = "../tt.cmi,.."; glob = "../tt.cmo" }`.

It will work if you write `../{tt.cmi,tt.cmo}` instead.

**Comment by houndofsound** [comment]
the documentation could be improved with your one-liner:
> It will work if you write ../{tt.cmi,tt.cmo} instead.

an example is worth a tangle of words.
thanks.
