### ISSUE TITLE
Extensions should check for the lowest version of dune they are available in

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/dune#2957]
Looking at some failure logs, I came across this one:
```
#=== ERROR while compiling ppxlib.0.10.0 ======================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.04.2 | file:///home/opam/opam-repository
# path                 ~/.opam/4.04.2/.opam-switch/build/ppxlib.0.10.0
# command              ~/.opam/4.04.2/bin/dune build -p ppxlib -j 71
# exit-code            1
# env-file             ~/.opam/log/ppxlib-6-f9b82b.env
# output-file          ~/.opam/log/ppxlib-6-f9b82b.out
### output ###
# File "dune-project", line 4, characters 7-13:
# 4 | (using cinaps 1.0)
#            ^^^^^^
# Error: Unknown extension "cinaps".
```
The problem is that dune 1.6 is installed but `cinaps` is only available in dune 1.11 and above.
However the `dune-project` file is as follow:
```
(lang dune 1.0)
(name ppxlib)
(using cinaps 1.0)
```
In my opinion dune should be able to raise an error if such `dune-project` gets detected. In that case an error should be raised if `(lang dune ...)` is below 1.11.

**Comment by diml** [comment]
Agreed. So we could do this right now with some ad-hoc code, but to make things smoother moving forward I'd rather we come up with a general solution right from the start. I haven't put much thought into it, but I guess it involves declaring dependencies between extension versions and the main language version.
