### ISSUE TITLE
mylib.ml ignored, how do disable compilation of library with -pack?

### ISSUE THREAD

**Issue by aryx** [ocaml/dune#2969]
I have a library called mylib under lib/ containing many .ml files.
I would like to use code from this library in a separate bin/ directory, but right now
dune force me to prefix all calls to this library with Mylib. (the library is compiled
with -pack I guess). The documentation says that if mylib.ml is present, then
the library will not be compile with -pack, but this does not seem to work.

How do I disable the compilation of libraries with -pack?

**Comment by nojb** [comment]
`dune` does not use `-pack`; but it does "wrap" the libraries using module aliases. You can disable this by putting `(wrapped false)` in the definition of your library. You could also just add `open MyLib` at the top of any module using the library.
