### ISSUE TITLE
build problems with js_of_ocaml

### ISSUE THREAD

**Issue by hbr** [ocaml/dune#2970]
I have a project with various libraries which I compile using dune. One of the executable is a javascript executable (executable under nodejs).

For the javascript executable I encounter the following problem:

- If I build with ‘—profile release’ everything works fine, except that I get a warning that some primitives are missing. But the program works fine i.e. the missing primitives are obviously not used.

There are some missing primitives
Dummy implementations (raising 'Failure' exception) will be used if they are not available at runtime.
You can prevent the generation of dummy implementations with the commandline option '--disable genprim'
Missing primitives provided by +dynlink.js:
  caml_add_debug_info
  caml_dynlink_add_primitive
  caml_dynlink_get_current_libs
  caml_dynlink_lookup_symbol
  caml_dynlink_open_lib
  caml_register_code_fragment
Missing primitives provided by +toplevel.js:
  caml_get_section_table
  caml_realloc_global
  caml_reify_bytecode
  caml_static_alloc

- If I build with the default profile (i.e. — profile dev), then starting the program I get the error message

/Users/helmut/myprogs/alba/program/_build/default/ocaml/alba-node/alba_node.bc.js:51209
    runtime.ml_setup_bridges(0);
            ^

TypeError: runtime.ml_setup_bridges is not a function
    at /Users/helmut/myprogs/alba/program/_build/default/ocaml/alba-node/alba_node.bc.js:51209:13
    at Object.<anonymous> (/Users/helmut/myprogs/alba/program/_build/default/ocaml/alba-node/alba_node.bc.js:51243:3)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)

I assume that there is something missing to load the libraries.

Using the release profile is no principal problem, but compile times are much longer than compiling with the development profile.

Does anybody have an idea how to get the build with development profile working?

Thanks for any hints.
Helmut

**Comment by hhugo** [comment]
The difference between the release and the dev profile is the following:

1. with the release profile, one will first build a bytecode executable with ocamlc and call the js_of_ocaml compiler on the result. In that case, unless you use `-linkall`, ocamlc will only link modules that are explicitly referenced.
2. with the dev profile, libraries (*.cma) and modules  (*.cmo) will be compiled to JavaScript individually and linked at the end. In that case, every single module of you dependencies will be included unconditionally.

In your case, your program has a dependency on ocaml-linenoise. This library rely on c stubs [1] that have not been implemented in JavaScript (`ml_setup_bridges`).
With (1.), I believe ocamlc is able to figure out that the module `lNoise` (that rely `ml_setup_bridges`) is not required to build your program.
With (2.), `lNoise` will be included and will fail at runtime trying to call `ml_setup_bridges`.

Two solutions:
- remove ocaml-linenoise from the dependencies of the program you want to compile to javascript.
- implement JavaScript stubs needed by ocaml-linenoise.

[1] https://github.com/ocaml-community/ocaml-linenoise/blob/f7aa780c1f13c579612ce8191f5cfaaba432e4e4/src/lNoise.ml#L16

**Comment by hbr** [comment]
Thanks for the explanation. 

Since I do not use lNoise in the executable I compile to javascript, I just removed it from the dependencies. Now the profile 'dev' works fine.
