### ISSUE TITLE
Missing "-I stdlib" when building OCaml compiler tree

### ISSUE THREAD

**Issue by mshinwell** [ocaml/dune#2974]
As discussed with @diml there appears to be a regression from dune 2.0.0 to 2.1.0 seen when building the OCaml compiler.  It looks like "`-I stdlib`" is now omitted from the command line, leading to an error about `std_exit.cmx` being missing.

Using 2.1.0 (note missing "`-I stdlib`"):
```
$ (cd _build/default && <path>/ocamlopt.opt -w
@1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats
-short-paths -keep-locs -w +a-4-9-40-41-42-44-45-48 -principal -nostdlib -g -o
tools/make_opcodes.exe stdlib/stdlib.cmxa runtime/runtimeopt.cmxa -I runtime
tools/.make_opcodes.eobjs/native/dune__exe.cmx
tools/.make_opcodes.eobjs/native/dune__exe__Make_opcodes.cmx)
```
This fails with:
```
File "_none_", line 1:
Error: Cannot find file std_exit.cmx 
```

Using 2.0.0:
```
(cd _build/default && <path>/ocamlopt.opt -w
@1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats
-short-paths -keep-locs -w +a-4-9-40-41-42-44-45-48 -principal -nostdlib -g -o
tools/make_opcodes.exe -I runtime -I stdlib stdlib/stdlib.cmxa
runtime/runtimeopt.cmxa tools/.make_opcodes.eobjs/native/dune__exe.cmx
tools/.make_opcodes.eobjs/native/dune__exe__Make_opcodes.cmx)
```

**Comment by diml** [comment]
And I'm likely the one who broke this BTW

**Comment by lthls** [comment]
Ping ? The flambda 2.0 CI has to fallback to 2.0.1 because of this.

**Comment by diml** [comment]
I started working on this there: https://github.com/ocaml/dune/pull/3038

**Comment by diml** [comment]
@mshinwell or @lthls, could you give a try to #3038 to confirm that it fixes the issue? I tried on trunk, compilation goes further and then fails for another reason which doesn't seem dune-related (something about `caml_register_code_fragment`)

**Comment by lthls** [comment]
I've tried it, and we can build flambda 2.0 with it, so the issue seems to be fixed.

**Comment by mshinwell** [comment]
When will this make it into a released version of dune?

**Comment by diml** [comment]
@lthls thanks for testing!

@mshinwell I can backport it to 2.1.x once it's merged and release it today.

**Comment by mshinwell** [comment]
Very good, thanks.

**Comment by diml** [comment]
Here it is: https://github.com/ocaml/opam-repository/pull/15679
