### ISSUE TITLE
Building project with incorrectly specified library dependencies succeeds, blows at runtime

### ISSUE THREAD

**Issue by dboris** [ocaml/dune#2975]
I am referring here the following issue from "dbuenzli/logs":
https://github.com/dbuenzli/logs/issues/30#issuecomment-565952820
In summary, I was able to build a project which does not specify correctly its library dependencies. The project builds without errors or warnings in the default profile, and blows at runtime. The issue becomes apparent when building the release profile.

**Comment by diml** [comment]
Not sure we can do much about that in Dune. It seems to me that the simplest solution would be to install the various `logs.xxx` libraries in sub-directories. i.e `logs.lwt` would go in `<libdir>/logs/lwt`, `logs.browser` would go in `<libdir>/logs/browser` and so on.

**Comment by Alizter** [comment]
@rgrinberg I guess this issue can be closed since it is possible to write user defined install stanzas?

**Comment by rgrinberg** [comment]
It can be closed because the fix can be done upstream in logs.
