### ISSUE TITLE
Add github issue template

### ISSUE THREAD

**Issue by shonfeder** [ocaml/dune#2978]
This issue proposes adding a github issue template to help instruct users on filing bug reports, as per discussion with @diml at https://github.com/ocaml/dune/issues/2927#issuecomment-559503309 

I thought this could be achieved via a PR, but github now advises using their new issue template workflow. See the following for instructions on adding the template: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#creating-issue-templates

Here's a rough proposal for the basic issue template, just to get things going. Please change as you see fit. (The following is elaborated from [stevemao's github-issue-templates repo](https://github.com/stevemao/github-issue-templates/blob/master/simple/ISSUE_TEMPLATE.md)).

```markdown
<!-- Thank you for filing an issue to help us improve Dune! -->
## Expected Behavior


## Actual Behavior


## Reproduction

<!-- If possible, please open a PR with a test that reproduces the problem.
      Adding tests is easy, see  https://github.com/ocaml/dune/blob/master/HACKING.md#tests -->

- PR with a reproducing test: 

<!-- Otherwise, please detail how to the behavior can be reproduced -->

1.
1.
1.

## Specifications

- Version (output of `dune --version`):
- Operating system (distribution and version):

<!-- remove the following if not used -->
## Additional information 

- Link to gist with verbose output (run with `--verbose` flag): 
```

**Comment by shonfeder** [comment]
Just a quick update: configuration of the issue templates seem to require access to the repo configuration settings (as per https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#creating-issue-templates), but I don't have this level of access.

**Comment by diml** [comment]
Alright, I increased your access rights. You should now be able to configure the issue template.

**Comment by shonfeder** [comment]
I'm afraid I still don't have access. According to https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level, only admin's have access to "Change a repository's settings".

Assuming I'm not a great candidate for admin access at this point (the fewer the better in any case, and with "great power etc..."), someone else may need to run through the few configuration steps.

**Comment by diml** [comment]
Hmm, I thought I did gave you admin rights.I tried again. If you prefer not to have them, I can do it myself. I'm just thinking that the template might need a few adjustments after it's setup and it'll be easier if you can do them yourself.

**Comment by shonfeder** [comment]
I can see the settings now! Thank you and happy to be help with whatever level of permission is useful for the team. Thanks, @diml!
