### ISSUE TITLE
Rules cannot have optional file dependencies

### ISSUE THREAD

**Issue by timbertson** [ocaml/dune#298]
jbuilder doesn't appear to have a way to specify "depend on this file, if it exists" - all dependencies are treated as mandatory, and the build will fail if a dependency cannot be built. That makes sense in most cases, but it can be useful to have an optional variant which allows the file to be missing (in which case it would be considered "changed" if it later gets created).

I discussed a use case for this in https://github.com/janestreet/jbuilder/issues/255, essentially I want a rule (for `version.ml`) to depend on `.git/HEAD`, but I also want the rule to be buildable when there is no .git directory (e.g. when building from a plain tarball).

**Comment by rgrinberg** [comment]
@diml do optional dependencies make sense for dune? Does jenga support such dependencies?

**Comment by diml** [comment]
Dune already supports optional dependencies. If you use `(glob_files x)` in a rule, it will only depend on `x` if `x` exists or is buildable. However, this doesn't help for the use case in this PR because directories starting with `.` are completely ignored by dune. #880 should solve this common use case.

**Comment by rgrinberg** [comment]
So now it is possible to depend on `.git/HEAD` since the `dirs` stanza was introduced. However, this isn't really a good solution as we don't want to be scanning all of `.git` just for a single file.

**Comment by diml** [comment]
I'm expecting that #1930 will cover all the cases where one wants to depend on `.git/HEAD`, so we can close this PR
