### ISSUE TITLE
Put a summary of the common basic commands at the top of the inline help

### ISSUE THREAD

**Issue by shonfeder** [ocaml/dune#3007]
This proposal for the inline CLI documentation proposal is inspired by [chrisnevers's remark on
discuss](https://discuss.ocaml.org/t/mkocaml-release-project-generator/4949/3?u=shonfeder):

> I just want to know the bare minimum commands to build/run/publish my project.

I think this is how a lot of users feel about their build tools, and in the
spirit of well designed, deep API's, this is all most users should need to
know.

Currently, the output of `dune`/`dune --help` is its manual page: the
first substantial piece of information are two paragraphs about the design
philosophy and lineage of `dune`, which is followed by an alphabetical listing
of the commands. This is great for a manual page, but not helpful for quick
guidance on general usage.

I propose foregrounding the few commands that all users need to know at the top
of the inline help. 

These are the three options I've thought of so far:

1. Follow `cargo`'s example and provide a list the commands with a synopsis of what they do. E.g.,
    ```
    Common dune commands (run *dune CMD --help* for more on the CMD):
      build    Build the given targets, or all installable targets if none are given.
      test     Run all tests in the current project
      exec     Build and execute a command or executable component in an environment as if it were installed
      init     Initialize a new project or component
    ```
    And the full list of commands could be given further down, as it is currently.
2. Demonstrate common usage by example at the top, E.g.,
    ```sh
    USAGE
      # Initialize a new project named my_project with executable and library components
      dune init proj my_project && cd my_project 
      dune build            # Build all targets
      dune test             # Run all tests
      dune exec my_project  # Run the executable named myproject
      dune install          # Install packages defined in the project
      dune clean            # Clean up all build artifacts
    ```
3. Follow `pacman`'s example, and list the synopsis of the most used commands. E.g.,
    ```
    Common operations:
      dune build [OPTION]... [TARGET]...
      dune runtest [OPTION]... [DIR]...
      dune exec [OPTION]... PROG [ARGS]...
      dune install [OPTION]... [PACKAGE]...
      dune clean [OPTION]...
      dune init [OPTION]... INIT_KIND NAME [PATH]
    ```

(1) has the benefit of providing a succinct summary of the commands. (2) Is more
verbose, and less general, but has the benefit of providing a mini tutorial on
a basic workflow. (3) Splits the differences, and could be augmented with some
commentary. 

If it is agreed that this is a good change to make, here are some things to do
moving forward:

- Consider other sources of inspiration or suggestions on how to approach this.
- Determine which commands are the most frequently used and/or most important
  for beginners to use.
- Pick a scheme.
- Make needed alterations to the cmdliner configuration

**Comment by diml** [comment]
As mentioned yesterday during the meeting, that seems like a great idea to me! I don't have a particular opinion on the format. Just By looking around, I can see that `git` and `cargo` seems to be using format 1 for `--help` and 3 for the man pages.

At this point, I'd suggest to just try and see what looks best.

**Comment by shonfeder** [comment]
Reopened since, as the issue that triggered closure notes, it only "partially resolves" this one. I think the full resolution will come will separating out the inline help from the manpage, so that the immediate inline help gives the kind of useful synopsis described in this issue.

**Comment by shonfeder** [comment]
I think tat the inline help provided by `--help` can (and should) serve a different purpose than the more exhaustive documentation provided by a man page (most seem to agree, judging by the CLI tools I use). However, Cmdliner has taken a [principled stand in rejecting this](https://github.com/dbuenzli/cmdliner/pull/26). So, as to implementation, our options are

1. Patch/overlay our vendored Cmdliner to make to make `--help` provide a brief inline help page.
2. As a hack, add some quick reference command to provide the kind of help we want (e.g. `dune ref[erence]`)
3. Just stick the desired stuff in the `SYNOPSIS` section, since we can override this, and current (automatically generated) synopsis content is useless (`dune COMMAND ...`).

(3) is the easiest to implement (I'd argue the others are not worth the effort) and the cleanest approach (IMO). It is also consistent with the [man-pages(7) guidance](http://man7.org/linux/man-pages/man7/man-pages.7.html) on the usage of the `SYNOPSIS` section: 

> A brief summary of the command or function's interface.
>
> For commands, this shows the syntax of the command and
> its arguments (including options);

I'll draft up something today or tomorrow, and we can see how we like the output I'll include the PR.

**Comment by diml** [comment]
It doesn't worth departing from the standard provided by cmdliner here but I'm curious to see what (3) looks like.
