### ISSUE TITLE
Feature request: shared object rules

### ISSUE THREAD

**Issue by bcc32** [ocaml/dune#301]
OCaml has the ability to produced standalone shared libraries using the `-output-complete-obj` compiler flag. These libraries can then be dynamically loaded into other programs (for example, when writing native plugins for Emacs).

It would be nice to be able to build `*.so` files directly in jbuilder (equivalently, `*.dylib`, `*.dll` depending on platform).

I'm currently using the following workaround, which takes advantage of the `Mach-O` executable format being basically the same as the shared object one:

```
(executables
 ((names     (libsomething))
  (libraries ())))

(rule (copy libsomething.exe libsomething.so))
```

**Comment by rgrinberg** [comment]
Will #23 address this @bobot ?

**Comment by diml** [comment]
This feature has now been added to jbuilder. You can use the following jbuild file:

```scheme
(executables
 ((names     (libsomething))
  (modes (shared_object))
  (libraries ())))
```
