### ISSUE TITLE
dune upgrade for lang 2.0

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#3011]
Hello,

I opened [a PR on ocamlformat so that it uses `lang dune 2.0`](https://github.com/ocaml-ppx/ocamlformat/pull/1196).

The result is nice (in particular the new actions completely replaces our uses of `(system)`!), but the upgrade process was fairly manual.

As discussed elsewhere yesterday it would be nice to automate this process by reusing the `dune upgrade` command. This is fairly involved, so it should be useful to spec this out a bit first. I added some suggestions to start from somewhere but I'm happy to discuss all the points.

It seems to me that there are several aspects to consider:

## Dealing with several kinds of upgrades

Dune upgrade has been designed for the jbuilder -> dune ("0 -> 1") transition.
Extending this to support dune 1.x -> dune 2.0 ("1 -> 2") raises some questions:

- should we keep the ability to run 0 -> 1 migrations?
- how to select which migration to run?
- should there be a way to run both migrations back to back?
- how to select which projects to migrate?

### :bulb: Suggestion

There's a `--to` option that selects the migration to run. Valid values are `--to=dune1` or `--to=dune2`.

We collect the projects in the current workspace as well as their version.
All migratable projects are migrated (meaning: when `dune upgrade --to dune2` runs, only dune 1.x projects are migrated).

If `--to` is not passed, the oldest no-op migration is selected. That is to say:

- if there's a jbuilder project in the workspace, run as `--to dune1`
- if there's a dune 1.x project in the workspace, run as `--to dune2`
- otherwise, do nothing

## What we need to upgrade 

We'll need to list what things to convert. Off the top of my head:

- edit `(lang dune 1.x)` in `dune-project`
- remove `(using fmt x)`, and convert configuration to `(formatting x)`
- convert `(alias (name x) (action y))` to `(rule (alias x) (action y))`

And then we can iterate using existing projects from opam (and of course, reading the 2.0.0 changelog).

Note that since defaults change, there are two ways we can perform the update:

- preserve the 1.x behavior when possible
- use the new default

In the case of a 1.x project with no `(using fmt x)` stanza, the first strategy corresponds to adding an explicit `(formatting disabled)`.
The second strategy corresponds to not adding this, ie set up the rules.

### :bulb: Suggestion

Let's go with the second strategy, otherwise the corresponding dune projects will need many overrides for `(explicit_js_mode)`, etc.
We can display a message pointing to a documentation page that lists the new defaults.

## Can we do better?

Version 2.0 of the dune language also comes with some new features that can simplify existing dune files.
One such example is long-form target inference: in dune 2 it is possible to simplify:

    (rule
     (targets out.ml)
     (deps (source_tree dir))
     (action
      (with-stdout-to
       %{targets}
       (run ./generator.exe))))
       
to:

    (rule
     (deps (source_tree dir))
     (action
      (with-stdout-to
       out.ml
       (run ./generator.exe))))
       
I think it would be neat to have a way to detect these cases and have a way to promote them in place, but this is not strictly an upgrade.

### :bulb: Suggestion

There's probably room for a new command like `dune fixup` for this kind of suggestions, but it's not needed for migrations, and we'll probably need an AST for this (and in turn, switching to using an
applicative to parse s-expressions). So we can revisit that later.

I'll help @voodoos implement this once the details have been sorted out. This should be a nice and useful feature!

Let me know what you think.

**Comment by diml** [comment]
Thanks for the nice writeup @emillon !

Regarding support for 0->1 migrations, yh let's keep it until Dune 3.0.0. Personally, I would systematically upgrade to the latest version and drop the `--to`. So for instance, running `dune upgrade` in a `jbuilder` project would upgrade it to Dune 2. In particular, this would have the nice property of making `dune upgrade` idempotent. I have no objection to `--to` though if you guys think it's worth it.

> The second strategy corresponds to not adding this, ie set up the rules.

Does that mean that a project could fail to build after an upgrade? That seems worse to me than explicitly keeping the old defaults.

> There's probably room for a new command like dune fixup for this kind of suggestions, but it's not needed for migrations, and we'll probably need an AST for this (and in turn, switching to using an
applicative to parse s-expressions). So we can revisit that later.

Having it has a separate command seems sensible to me as well. Some people might prefer the first style and it's better if `dune upgrade` preserve as much as possible the original style.

**Comment by voodoos** [comment]
> Does that mean that a project could fail to build after an upgrade? 

Having a working project after "upgrading" to 2.0 is a much more involved endeavour than just automating some of the tedious changes required for the upgrade.

I started reading the changelog: some breaking changes can be locally corrected by parsing and editing the config files but others need an analysis of the project source files such as:

> `mli` only modules must now be explicitly declared. 
> This was previously a warning and is now an error. (#2442, @rgrinberg)

The simpler "provide a mean to automate some of the translation" project, while being a first step toward full upgrade, should already be a great help.

An in-between solution would be to translate the easy and pervasive things and list the other changes needed at the end of the process ?

**Comment by NathanReb** [comment]
I agree with @diml that from a user perspective, `dune upgrade` should upgrade all the way to the latest version by default.

Having a `--to` option to prevent it from upgrading all the way up might be useful but since I imagine we want to encourage people to upgrade to `2.0` I guess it makes for it not to be the default.

**Comment by diml** [comment]
> An in-between solution would be to translate the easy and pervasive things and list the other changes that may be needed at the end of the process ?

That seems reasonable yes. The most important is that user never get stuck with no idea how to make progress. If they get a build failure because of a mli only module, then it's not too bad because the error message tells the user exactly what to do. One the other hand, `dune runtest` suddenly failing with a formatting diff could be confusing, especially if you never looked into the auto-formatting business. But if `dune upgrade` mentions that, that seems fine.

**Comment by emillon** [comment]
Regarding `--to`, I agree: let's go with an idempotent, all the way up command. This means that in the case of a jbuilder project, it will have to go through both migrations.

Let's go also with explicit opt-outs. The litmus test that the user should always have a way to make progress is a good test. Changing behaviour goes against that. The "how to port to the new defaults" would still be useful of course.

I think we have enough consensus to start a first prototype and then we'll see how to iterate based on the public projects available on opam.

**Comment by diml** [comment]
BTW, https://github.com/dune-universe/dune-universe can come in handy to test the upgrader

**Comment by emillon** [comment]
Good point! An alternative is to set up an ocurrent pipeline (similar to ocaml-ci) but dune-universe can get us very far.

**Comment by hhugo** [comment]
Is anyone working on that yet ?

**Comment by rgrinberg** [comment]
> Is anyone working on that yet ?

Nope. But that's because it's already done in master :)

If you could test it out, that would be great.

**Comment by seantalts** [comment]
> Nope. But that's because it's already done in master :)

Could you say more about what the command is? I can't find it.
