### ISSUE TITLE
Extend what (with-accepted-exit-codes) supports

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#3014]
Hi,

I noticed that when you want to run a command with certain accepted codes and a redirection, only one order is possible. Meaning that:

    (with-stdout-to out.txt
     (with-accepted-exit-codes
      1
      (run cmd)))

is accepted, but this is not:

    (with-accepted-exit-codes
     1
     (with-stdout-to out.txt
      (run cmd)))

It seems to me that all modifiers like `(chdir)`, `(setenv)`, and redirections should have no impact on interpreting the exit code.

What do you think about lifting a bit the restriction that the action in `(with-accepted-exit-codes)` should be `(system)`, `(sh)` or `(bash)`. We should be careful not trying to give failure semantics to `(progn)` or pipes (if supported one day), but redirections and other manipulations of a process environment seem fair game.

**Comment by diml** [comment]
That seems good to me!

**Comment by nojb** [comment]
I guess we could be a bit more flexible. See the discussion in #2742 for background.

**Comment by emillon** [comment]
All right, let's do this!
