### ISSUE TITLE
Copy file as binary to prevent corruption under windows

### ISSUE THREAD

**Issue by let-def** [ocaml/dune#3032]
@Armael reported that the copy operation produced corrupted files under windows.
I think it is due to this line
https://github.com/ocaml/dune/blob/44d3a17f6b360f8308e2341cdabafb5219c36e81/src/stdune/io.ml#L178
```ocaml
-    let ic = open_in src in 
+    let ic = open_in_bin src in 
```

The file being read as a text file, line ending characters will be translated. (However it is correctly written as a binary file, so the incorrect translation is done only once).

**Comment by diml** [comment]
This `open_in` function is defined earlier in the file, and it open files in binary mode by default. The corruption must come from somewhere else. Do you have a reproduction case?

**Comment by Armael** [comment]
Aha, then that's just my bad. I copy-pasted the copy code, but not the custom `open_in` function.

**Comment by Armael** [comment]
@let-def this issue can be closed. Sorry for the noise everyone!

**Comment by diml** [comment]
No worries. That makes me wonder if we shouldn't make these `binary` arguments required rather than optional. To force the caller to think about it.

**Comment by let-def** [comment]
Sorry for the noise indeed.
To prevent mistake like I and @Armael did, maybe we should instead redefine:
```
let open_in = `Use_open_in_bin_instead
```
Are there any use case for text files?

**Comment by diml** [comment]
There are a few `~binary:false` in the tree, mostly when we create or edit configuration files. We could    add and remove the `\r` manually I suppose, but that's a bit tedious.
