### ISSUE TITLE
Unable to use ppx_deriving after #3039

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/dune#3057]
Using dune master after the merge of #3039 (https://github.com/ocaml/dune/commit/63298a53b76e66b2e536da54011d434c1cc36165), I'm now unable to compile projects using `ppx_deriving`.

For example, the following test-case fails to compile:
```
$ cat dune
(library
 (name test)
 (preprocess (pps ppx_deriving.std)))
$ touch test.ml
$ dune build test.a
File "dune", line 3, characters 18-34:
3 |  (preprocess (pps ppx_deriving.std)))
                      ^^^^^^^^^^^^^^^^
Error: Ppx dependency on a non-ppx library "ppx_deriving.std". If
"ppx_deriving.std" is in fact a ppx rewriter library, it should have (kind
ppx_rewriter) in its dune file.
```

cc @snowleopard @diml

**Comment by rgrinberg** [comment]
For a bit of background, `ppx_deriving.std` is a "pseudo library" used to group the standard set of derivers provided by `ppx_deriving`: `ppx_deriving.show`, `ppx_deriving.compare`, etc.

I suppose we could require that such libraries have the correct kind as well.

**Comment by snowleopard** [comment]
@kit-ty-kate Thanks for letting us know!

A general way to avoid getting builds broken by new versions of Dune is to fix a version of the Dune language in a `dune-project` file. For example, in this case one could add `(lang dune 2.1)`, hence suppressing the new dependency check.

To make `ppx_deriving.std` usable with the latest version of Dune, I will open a PR adding the `kind` declaration to the appropriate `dune` file.

**Comment by snowleopard** [comment]
Oh, that's strange. `ppx_deriving.std` does have the right declaration:

https://github.com/ocaml-ppx/ppx_deriving/blob/59fed039092304ec54234541201930fbbb45aebc/src_plugins/std/dune#L15

**Comment by snowleopard** [comment]
Aha, `ppx_deriving` is using META files, so we need to adjust Dune to generate the `kind` information. I'll take care of this.

**Comment by snowleopard** [comment]
@kit-ty-kate This has been fixed in #3060 and your example now works. Thanks again for the report.

**Comment by joprice** [comment]
I'm seeing the same error using nix, which has recent versions of dune and ppx_deriving. Any other nix users hit this?

**Comment by snowleopard** [comment]
@joprice Presumably, it should be possible to reproduce your issue without nix. I'm happy to look at it, but I need a way to reproduce it myself. (I'm not a nix user.)

**Comment by joprice** [comment]
No problem. Let me try to reproduce in isolation first.

**Comment by joprice** [comment]
Here's the repo https://github.com/joprice/ocaml-scratch. I tried building it with opam, and it worked with both versions 5.2 and 4.5 of ppx_deriving. With that new piece of information, I compared the META files of opam and nix and found a discrepancy: The META file installed at /nix/store/8fm09alxiqa28wfkxxvzv41snjyik66k-ocaml4.10.0-ppx_deriving-4.5/lib/ocaml/4.10.0/site-lib/ppx_deriving/META is in fact missing the line `library_kind = "ppx_deriver"`, whereas the opam installed META file at `.opam/default/lib/ppx_deriving/META` has it. Is there maybe some post-processing that needs to be run to generate that line?

**Comment by joprice** [comment]
I found a workaround: I added `useDune2 = true;` here https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/ppx_deriving/default.nix#L5, which makes the package build with dune 2.x: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/ocaml/dune.nix#L5. That generated the correct META file. It makes sense if this feature was added in dune 2.x.

**Comment by snowleopard** [comment]
@joprice Cool, thanks for sharing the workaround!
