### ISSUE TITLE
make doesn't trigger a rebuild

### ISSUE THREAD

**Issue by ejgallego** [ocaml/dune#3078]
Since the bootstrap was reworked doing `make` does not correctly re-build dune. Example:

```
# start with a clear checkout of master
$ make     # => dune is built
$ git checkout my-branch
$ make     # => nothing happens
```

**Comment by diml** [comment]
Agreed. The default `make` target is good for release builds, which I assume is what non-dune developers would expect when they just type `make`. I'm thinking of distribution packagers for instance. But I agree it's not ideal.

BTW, note that you can write a `Makefile.dev` file at the root to override the default target. For instance you can set the default to `./dune.exe runtest` or `./dune build @bin/all`.

**Comment by ejgallego** [comment]
Maybe `Makefile.dev` could be used when some conditions are met? What would be a good way to detect that?
