### ISSUE TITLE
Warning on unused attributes

### ISSUE THREAD

**Issue by ddickstein** [ocaml/dune#3091]
Does dune support warnings on unused attributes? For example, if I write [@compare.ignor] accidentally, I don't want the build to be reported as successful.

**Comment by diml** [comment]
Dune doesn't know about attributes so it cannot warn about unused attributes.

Ppx rewriters based on ppxlib do these checks. IIRC, they are not enabled by default and you need to enable them by passing `-check` to the ppx rewriter. You can do that by writing:

```scheme
(library
 ...
 (preprocess (pps ppx_jane -check)))
```

However, note that this will only work if all the ppx rewriters you are using are based on [ppxlib](https://github.com/ocaml-ppx/ppxlib).
