### ISSUE TITLE
How does target resolution work w.r.t. subfolders and contexts?

### ISSUE THREAD

**Issue by artempyanykh** [ocaml/dune#3123]
This is not exactly a feature request, I'm rather hoping that someone could help me clarify a couple things about dune's CLI.

This is the directory structure:
```
src/dune-workspace
   /functional/dune
               annot.ml
```

In the workspace we have 3 contexts defined:
```
(context (opam (switch ocaml-variants.4.08.1+flambda) (name default) (merlin)))
(context (opam (switch ocaml-variants.4.08.1+flambda) (name opt)))
(context (opam (switch ocaml-variants.4.08.1+flambda) (name test)))
```

`src/functional/dune` has the following contents
```
(tests
  (names annot)
  (libraries alcotest))
```

and `src/functional/annot.ml` is a small exe with unit tests:
```ocaml
let test_lowercase () =
  Alcotest.(check string) "same string" "hello!" "hello!"

let () =
  Alcotest.run "Annot"
    [
      ( "string-case",
        [
          Alcotest.test_case "Lower case" `Quick test_lowercase;
        ] )
    ]
```

Now when I run things from workspace root, I get this:
```
src$ dune build @functional/runtest -f # (a) runs tests in 3 defined contexts
src$ dune exec functional/annot.exe -f # (b) runs tests in 1 (default) context
src$ dune exec _build/default/functional/annot.exe # (c) fails with 'not found'
src$ dune build @_build/default/functional/runtest -f # (d) runs tests in 1 (specified default) context
```
Two things here are confusing:
- mismatch between (a) and (b) in terms of context (although I can see how it follows from 'when a target on the command line doesn't start with _build, dune will expand it to the corresponding target in all the build contexts').
- is there a way to exec a binary under a particular context (c)?

Then from `functional` subfolder:
```
src/functional$ dune build @runtest -f # (a) runs tests in 3 contexts, expected
src/functional$ dune exec annot.exe -f # (b) fails with 'not found'
src/functional$ dune exec functional/annot.exe -f # (c) fails with 'not found'
src/functional$ dune exec ../functional/annot.exe -f # (d) runs tests in 1 (default) context
src/functional$ dune build @_build/default/runtest -f # (e) fails with "don't know about directory"
src/functional$ dune build @_build/default/functional/runtest -f # (f) fails with "don't know about directory"
src/functional$ dune build @../_build/default/functional/runtest -f # (g) fails with 'path ouside the workspace'
```

Here pretty much everything is confusing:
- Why do I need to use (d) to exec a binary while other options (b, c) don't work?
- How do I run `runtest` in a particular context from a subfolder?

Any help building a proper mental model for how dune resolves targets would be much appreciated!

**Comment by diml** [comment]
> mismatch between (a) and (b) in terms of context (although I can see how it follows from 'when a target on the command line doesn't start with _build, dune will expand it to the corresponding target in all the build contexts').

How could they match?

> is there a way to exec a binary under a particular context (c)?

You can pass `--context <name>`

> Why do I need to use (d) to exec a binary while other options (b, c) don't work?

The binary name is relative to the current directory

> How do I run runtest in a particular context from a subfolder?

It doesn't seem to be supported at the moment. I suppose we could generalise the `--context` option. And in fact, we could deprecate the special parsing of `_build/<context-name>`, it's just confusing

**Comment by artempyanykh** [comment]
Thanks for replying @diml !

> How could they match?

I understand there is a difference between `dune build` and `dune exec`. What I tried to say is that it's confusing that if you run `dune runtest` you get tests run 3 times because it invokes `build` which runs a rule in all 3 contexts. While a regular `dune exec functional/annot.exe` only runs tests once in default context.

This behaviour is confusing for me as someone new to dune, so I wonder what I'm missing. What's the point of `runtest` by default being run in all contexts (it doesn't seem like what I'd want most of the time)? Maybe I misunderstand the purpose of contexts? Is it advised to have just 1 context defined in workspace for regular development and have another workspace file with additional contexts for testing on CI?

> The binary name is relative to the current directory

Then why option (b) `src/functional$ dune exec annot.exe` doesn't work? It seems somewhat non-intuitive that I need to do this weird roundtrip `../functional` from `functional` subfolder to make dune find an executable. What are the exact rules of how the targets get expanded?

**Comment by diml** [comment]
> This behaviour is confusing for me as someone new to dune, so I wonder what I'm missing. What's the point of runtest by default being run in all contexts (it doesn't seem like what I'd want most of the time)? Maybe I misunderstand the purpose of contexts? Is it advised to have just 1 context defined in workspace for regular development and have another workspace file with additional contexts for testing on CI?

The purpose is to test against multiple configuration simultaneously. For instance, you might want to build and test your code against several versions of the compiler at once. In this case, it is very convenient that dune run the tests in all contexts simultaneously.

> Then why option (b) src/functional$ dune exec annot.exe doesn't work? It seems somewhat non-intuitive that I need to do this weird roundtrip ../functional from functional subfolder to make dune find an executable. What are the exact rules of how the targets get expanded?

The binary name is interpreted the same way as in the shell. So you need to write `./annot.exe` indeed. I agree that this is a bit confusing, however this has been fixed in master and dune now produces a helpful error message if you write `dune exec annot.exe`. In particular, it hints you to add the `./`

**Comment by artempyanykh** [comment]
> The purpose is to test against multiple configuration simultaneously. For instance, you might want to build and test your code against several versions of the compiler at once. In this case, it is very convenient that dune run the tests in all contexts simultaneously.

Ok, good. I can see value in that.

> So you need to write ./annot.exe indeed

All right, this makes sense now!

Thanks for helping @diml ! I think I have a better understanding of how I want to structure my build now. Closing the issue.
