### ISSUE TITLE
Imprecise hint when using "and" in opam file generation

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#3129]
Hi,

With opam file generation, when a dependency has both a stage and a constraint, the hint is not exact:

```
File "dune-project", line 19, characters 11-12:
19 |   (yojson (& (>= "1.6.0") :with-test ))
                ^
Error: Unknown constructor &
Hint: did you mean !=, =, >=, <=, >, <, <> or or?
```

The actual syntax is `(yojson (and (>= "1.6.0") :with-test ))`, but the `and` constructor does not appear in the hint.

That seems to be located around here. I thought that the fixpoint combinator could make things harder for the hint, but `"or"` comes from there and it's picked in the hint, so I'm puzzled.

https://github.com/ocaml/dune/blob/ad0764c44dac4d7644d4832a0124a059c40ae655/src/dune/package.ml#L163-L171

**Comment by diml** [comment]
The list of choices presented in the hint is produced by `User_message.did_you_mean`, which filters the list of possibilities using the levenshtein distance. Maybe it's filtering out the `and` because it's too long compared to `&`.

**Comment by emillon** [comment]
Ah, that's definitely it. I didn't realize there was some filtering. Not much we can do here then, I'm closing this. Thanks!

**Comment by emillon** [comment]
(confirmed by bumping the distance from 3 to 4, which adds some unwanted suggestions in other places such as c_names -> name)
