### ISSUE TITLE
Create alias "fmt" for "build @fmt --auto-promote"

### ISSUE THREAD

**Issue by ryanslade** [ocaml/dune#3170]
## Desired Behavior

Similar to the recently added `test` alias, would it be possible to add a `fmt` alias that is a shorthand for `dune build @fmt --auto-promote`?

**Comment by diml** [comment]
That seems reasonable to me.

**Comment by rgrinberg** [comment]
Would be nice this command hid the diff as well.

**Comment by ian-barnes** [comment]
And in both cases (i.e. `dune fmt` and  `dune build @fmt --auto-promote`) if the return code was 0 rather than 1 even if the diff was non-empty. This should only return an error code if there was some sort of failure, not if it successfully reformatted everything.

**Comment by rgrinberg** [comment]
`dune fmt` exists. Please create concrete issues for how to improve it.

**Comment by ryanslade** [comment]
Thanks!
