### ISSUE TITLE
Interning names & Watch Mode

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#3175]
I've noticed a bad interaction between the following two features:

* Interning of function names in the Memo library
* The generation of fresh Id's when creating Memo.Lazy values

The fresh Id's are represented using the function name type which means that we will constantly allocate these Id's.

As discussed internally, we should either:

* Drop the Id's on lazy values
* Do not intern them

**Comment by diml** [comment]
I have been wondering about removing interning altogether. It often makes things more complex to reason about, i.e. you have to remember that when you go from a string to a `.t` you have to pay a hash table lookup. It's also clearly not great for reproducibility. And in the end, we don't intern that much anymore.

**Comment by rgrinberg** [comment]
As discussed in the meeting, let's experiment with getting rid of interning everywhere. We no longer intern anything worthwhile anyway.

However, it would still be nice to omit names for some dep nodes in Memo. It's better than creating meaningless `lazy-<n>` names.

**Comment by snowleopard** [comment]
I've removed interning of names in memoization framework in #3196. I also dropped autogenerated names of lazy nodes altogether.

**Comment by rgrinberg** [comment]
Fixed in master.
