### ISSUE TITLE
Can't promote target to data-only dir

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#3179]
It seems it is not currently possible to promote something to a directory that is marked as "data-only" (the error is `Error: directory "foo" does not exist`). Is this by design? (this is using `(mode (promote (into ...)))`).

**Comment by rgrinberg** [comment]
Indeed, that seems a bit excessive. @aalekseyev is there a reason for this restriction?

**Comment by aalekseyev** [comment]
I can't think of any reason. For what it's worth, from the error message it doesn't sound like the restriction is deliberate. (that said, I'm not very familiar with how "promote into" is supposed to work so I might well be wrong)

**Comment by diml** [comment]
This restriction can be lifted. Initially, we added the promote into feature for merlin, where they have one directory per compiler version.

**Comment by nojb** [comment]
This appears to have been fixed.
