### ISSUE TITLE
dune utop fails with optional packages

### ISSUE THREAD

**Issue by hannesm** [ocaml/dune#3188]
## Expected Behavior

I expect `dune utop` to work

## Actual Behavior

bigstringaf# dune utop
File "lib/xen/dune", line 5, characters 30-46:
5 |  (libraries   bigarray-compat mirage-xen-posix)
                                  ^^^^^^^^^^^^^^^^
Error: Library "mirage-xen-posix" not found.
Hint: try: dune external-lib-deps --missing .utop/utop.exe

## Reproduction

get bigstringaf  from https://github.com/inhabitedtype/bigstringaf
run `dune utop`

the `xen` (and `freestanding`) subpackages contain `optional` parts.

## Specifications

- Version of `dune` (output of `dune --version`): 2.1.3
- Version of `ocaml` (output of `ocamlc --version`) 4.09.0
- Operating system (distribution and version): N/A

**Comment by diml** [comment]
We should indeed filter out non-available optional dependencies.

**Comment by anuragsoni** [comment]
This was fixed as part of https://github.com/ocaml/dune/pull/3612

**Comment by jeremiedimino** [comment]
Great, closing this. Thanks @anuragsoni for the fix!
