### ISSUE TITLE
Watch mode (with runtest) seems to be broken in 2.3.0

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#3189]
Hi,

It seems that watch mode does not work at all in dune 2.3.0 :cry: 

I run `dune runtest -w`, it displays a success; I edit a file and it does not rebuild anything.

It works fine with 2.2.0.

Let me know if I can help debugging this.

**Comment by diml** [comment]
Might be related to #3162? i.e. prefering fswatch on linux.

**Comment by emillon** [comment]
It's fixed at least in 2.7.0 so let's close this
