### ISSUE TITLE
Dune segfaults if the codebase contains some UTF-8 chars in (Coq) filenames

### ISSUE THREAD

**Issue by erikmd** [ocaml/dune#3219]
Cc @ejgallego @Zimmi48 FYI, I tested the [`dune subst`](https://dune.readthedocs.io/en/latest/usage.html#dune-subst) command (which allows one to automatically add a `version: _` line in `*.opam` files (following the discussion initiated in https://github.com/coq/coq/pull/11038 ))

## Expected Behavior

The command `dune subst` returns normally.

## Actual Behavior

stdout+stderr:

```
Error: exception Sys_error("\"test-suite/misc/deps/\\316\\261\\316\\262/\\316\\263\\316\\264.v\": No such file or directory")
Backtrace:
Raised by primitive operation at file "pervasives.ml", line 385, characters 28-54
Called from file "src/stdune/io.ml", line 87, characters 17-37
Called from file "src/stdune/io.ml" (inlined), line 107, characters 29-64
Called from file "src/watermarks.ml", line 155, characters 10-27
Called from file "list.ml", line 85, characters 12-15
Called from file "src/fiber/fiber.ml", line 201, characters 18-23
Called from file "src/fiber/fiber.ml", line 99, characters 6-13

I must not segfault.  Uncertainty is the mind-killer.  Exceptions are
the little-death that brings total obliteration.  I will fully express
my cases.  Execution will pass over me and through me.  And when it
has gone past, I will unwind the stack along its path.  Where the
cases are handled there will be nothing.  Only I will remain.
```

## Reproduction

1. `git clone https://github.com/coq/coq.git`
1. `cd coq`
1. `dune subst`

## Specifications

- Version of `dune` (output of `dune --version`): 1.11.3
- Version of `ocaml` (output of `ocamlc --version`): 4.05.0
- Operating system (distribution and version): GNU/Linux Debian

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag): N/A

- Regular Coq file that triggers that error: [test-suite/misc/deps/αβ/γδ.v](https://github.com/coq/coq/blob/master/test-suite/misc/deps/%CE%B1%CE%B2/%CE%B3%CE%B4.v)

**Comment by ejgallego** [comment]
It doesn't segfault now but still returns "no such file or directory"; actually this seems like a blocker for Coq.

**Comment by ejgallego** [comment]
This seems strange:
```
$ dune --debug-backtraces subst
dune: too many arguments, don't know what to do with `subst'
Usage: dune COMMAND ...
Try `dune --help' for more information.
```

**Comment by nojb** [comment]
> Error: exception Sys_error("\"test-suite/misc/deps/\\316\\261\\316\\262/\\316\\263\\316\\264.v\": No such file or directory")

Looking at the error message I am a bit puzzled since the file name seems to have been escaped (look at the embedded double quotes and the double backslashes). Perhaps this is the problem rather than an encoding issue.

**Comment by ejgallego** [comment]
Ok, the problem is that `git ls-files`, which Dune subst calls returns:
```
"test-suite/misc/deps/\316\261\316\262/\316\263\316\264.v"
"test-suite/misc/deps/\316\261\316\262/\316\265\316\266.v"
```
let me investigate more.
