### ISSUE TITLE
hacking guidance request

### ISSUE THREAD

**Issue by progman1** [ocaml/dune#3221]
hi
when dune decides on a DAG for re-compilations stemming from a changed .ml file 
(amongst a set with no .mli interfaces)

hypothetical question: is there any provision for detecting when one of the dependent re-compilations generates exactly the same cmi  as previously?
because I imagine, if found, that would be reason enough to terminate further re-compilations along a particular chain of dependencies.
but this cannot happen of course because of the propagation of new CRC digests.

however, if this were a possibility what in particular in [src/dune/build_system.ml]
should I look at in order to have it notice unchanged build artefacts?
I would really appreciate some guidance as I'm stuck!

**Comment by diml** [comment]
Do you still need help with this?
