### ISSUE TITLE
foreign_stubs rule fails when shared libraries are disabled in the compiler

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#3222]
##  Expected Behavior

- build an ocaml compiler with --disable-shared and install dune
- build a dune library like configurator and have it build ok

## Actual Behavior

```
File "duniverse/dune-configurator.2.3.1/src/stdune/dune", line 1, characters 0-214:
1 | (library
2 |  (name stdune)
3 |  (public_name dune-private-libs.stdune)
4 |  (synopsis "[Internal] Standard library of Dune")
5 |  (preprocess future_syntax)
6 |  (libraries unix)
7 |  (foreign_stubs
8 |   (language c)
9 |   (names fcntl_stubs)))
Error: Rule failed to generate the following targets:
- duniverse/dune-configurator.2.3.1/src/stdune/dllstdune_stubs.so
```

Looks like the dllstubs.so target needs to be conditional on whether the compiler will output shared libraries or not.

**Comment by let-def** [comment]
The "dual" situation, a .so and no .a, would be very convenient for [Qt/cuite](https://github.com/let-def/cuite). The objects produced are really big and working with .a is not really an option so the current build is designed around .so only. Unfortunately that breaks foreign_archives.
(Qt will be distributed as shared objects anyway, so we care only about this case for now).

**Comment by diml** [comment]
@let-def indeed. Note however that it'd be difficult to provide full support, or at least difficult in the short term. More precisely, if you were building a binary using `cuite` and running it as part of the build, for instance for testing purposes then Dune wouldn't know that this binary would load the `.so` at runtime. In order for this to work without hassle, we'd need to introduce a notion of "runtime dependencies". This is something we'd like to do one day, but the infrastructure is not there yet.

**Comment by let-def** [comment]
@diml I understand that this does not compose well (there are already issues with respect to runtime linking path, the `LD_LIBRARY_PATH` variable). Do you have any workaround to suggest in the meantime?

**Comment by diml** [comment]
No good one unfortunately. As a first approximation, for such rules you can depend on `(package xxx)` and you'll get the `.so` installed at the right place and recorded as a dependency. However, we don't set `LD_LIBRARY_PATH` in Dune. We could do that and add the local directory in `_build/install`.

More generally, support for C libraries and C compilation in Dune is quite limited and heavily relies on the ocaml tools. It'd be nice to change that though.
