### ISSUE TITLE
hacking help request:  terminating rule execution...

### ISSUE THREAD

**Issue by progman1** [ocaml/dune#3224]
hi
when dune decides on a DAG for re-compilations stemming from a changed .ml file
(amongst a set with no .mli interfaces)
(hypothetical question) is there any provision for detecting when one
of the dependent re-compilations generates exactly the same cmi as
previously?
because I imagine, if found, that would be reason enough to terminate
further re-compilations along a particular chain of dependencies.
but this cannot happen of course because of the propagation of new CRC digests.

however, if this were a possibility (I'm working on an alternative to
the CRC digest regime and hacking in [src/dune/build_system.ml] to
switch off hygiene to allow the compiler to determine whether a
re-compilation is really needed at all) what in particular might I
look at in order to have Dune notice unchanged build artefacts and
deciding on whether to continue with a sequence of rule execution?
my hope was that the code is only trivially far away from being able
to implement this,
but I'm having difficulty following the it.
I would really appreciate some guidance as I'm stuck!

**Comment by rgrinberg** [comment]
> is there any provision for detecting when one
of the dependent re-compilations generates exactly the same cmi as
previously?

There's a provision like this for all rules. If the dependencies of rules do not change, then they will not be re-run.

> what in particular might I
look at in order to have Dune notice unchanged build artefacts and
deciding on whether to continue with a sequence of rule execution?
my hope was that the code is only trivially far away from being able
to implement this,

Fortunately for you, there's no need to change dune at all to do this. If you hack the compiler to produce the same cmi's, extra recompilation will automatically cease.

**Comment by progman1** [comment]
that's strange because I expected that but observation of the commands run demonstrated otherwise.
perhaps by disabling the removal of old targets I have inadvertently interfered somehow with this process? The invoked compiler leaves cmo/cmx/cmi artefacts untouched when it decides no re-compilation needed and I expected no more commands to follow it but they do. 
Can you suggest anything?

**Comment by progman1** [comment]
I'm using the 2.0.0 source...

**Comment by rgrinberg** [comment]
> The invoked compiler leaves cmo/cmx/cmi artefacts untouched when it decides no re-compilation needed and I expected no more commands to follow it but they do.

Did you confirm that this is the case? Dune compiles cmi's with `-keep-locs` so even innocuous changes will produce different artifacts.

**Comment by progman1** [comment]
I'm being dumb - it was what I mentioned, the CRC of a changed file propagating upwards where there is type leakage. fixed that and the termination happened :)
thanks for your help.

**Comment by progman1** [comment]
at the risk of being dumb again, I note that when t3 depends on t2 depends on t1
(with no mli's involved) that t3.cmi contains the CRC digest for t1.cmi even though there is
no type connection between the two, which appears to be an unnecessary dependency to me.  do you know why there might be a justification for it?

**Comment by progman1** [comment]
putting aside that somewhat unrelated question I'd like to revisit the termination issue.
I made a mistake in stating that I was able to get the early termination.
so despite an invoked compilation command returning without having altered the existing build artefacts, the next action is invoked regardless.
I have a suspicion that you had in mind, before I mentioned the t1/t2/t3 setup,
that early termination would happen if t1.cmi proved unchanged.
however, in my scheme, recompilation of t1.ml does indeed change the cmi,
a re-compilation command is then invoked on t2.ml but the compiler decides it unnecessary and returns without altering previously generated artefacts, and I would wish for re-compilation of t3.ml not to even be attempted. 
since it is attempted I would posit that the difference between those two scenarios is
the former has a computed set of actions to undertake which wouldn't be computed unless t1.ml had changed, while the latter has already initiated those actions and isn't looking for any conditions for early termination - it is now committed to an execution plan.
so perhaps that is why the recompile of attempted t3.ml happens regardless.
if so then I hope it's clearer that I'm looking to introduce a way for an already underway sequence of actions to terminate on seeing the post-condition of unchanged artefacts.

**Comment by diml** [comment]
If ocamldep tells us that t3 depends on t2 and t2 depends on t1, then it is possible that the compiler will decide to read t1.cmi when compiling t3. Dune has no way of knowing whether the compiler will do that or not so it has to assume it will.

FTR, in early versions of Dune we didn't record such transitive dependencies between OCaml modules and has a result incremental compilation was sometimes broken.

One thing that could happen to improve the world is:
- the compiler would tell Dune what files it read when compiling t3
- Dune would use that information to narrow the dependencies of t3 after the fact and do less recompilation

This would require work on both the compiler and Dune. It would also require Dune to save more information on disk. Indeed, for the purpose of recompilation Dune doesn't remember that t3 depends on t2 and/or t1 between runs of Dune. Instead, it recomputes this information on every run. If it was provided by the compiler after the fact, then Dune would need to remember it in the persistent DB it saves in `_build/`. This DB would become bigger and it would take longer to save it and load it.

So, it's not entirely clear that all of this is worth it. However, it would be fun to experiment with these ideas to see how they perform in practice. If you are interested in exploring all this, we are happy to give you some pointers.

**Comment by progman1** [comment]
ah yes, I see now. there are the src dependencies but then there are the consistency
digests, that if present, must be maintained - t3.cmo cannot be allowed to carry other than the newest t1 digest even though the t3 implementation does not access t1's 
directly.
it appears a module's import list grows ever-more without the use of interfaces.
the compiler should probably make a distinction between inherited imports and
those arising from the modules (compiled units) accessed in the code.
while all should remain consistent, only the digests of directly used modules should 
make it into the outer import list.
is it the case that the build failures you mentioned in the early days of dune were 
consistency check errors?

I would very much like a pointer to where that transitive dependency decision is happening. Changing the behaviour in favour of source-only dependency will eliminate 
the un-needed recompilation invocations (my hacked compiler declines them anyway, where inconsistent digests are not an issue)..
Thanks to working with a relatively resource constrained machine (a Pi !) I'm very much interested in efficiency measures :)

**Comment by diml** [comment]
> is it the case that the build failures you mentioned in the early days of dune were
consistency check errors?

Yes

> I would very much like a pointer to where that transitive dependency decision is happening. Changing the behaviour in favour of source-only dependency will eliminate
the un-needed recompilation invocations (my hacked compiler declines them anyway, where inconsistent digests are not an issue)..

That'd be awesome, but probably quite difficult. This happens in the compiler, and it's probably not super explicit either, i.e. hidden in the internal implementation details of the OCaml typer. You could start by looking at the `typing/env.mli` module. That's where names written in source files are resolved.

> Thanks to working with a relatively resource constrained machine (a Pi !) I'm very much interested in efficiency measures :)

Working on a Pi? Bold! :)

**Comment by progman1** [comment]
I meant location in the Dune source not the compiler :) 
?

**Comment by diml** [comment]
Ah, so it's in `src/dune/ocamldep.ml`. Look for `Merge_file_into (sources, ...)` and replace `sources` by `[]`. That should do the trick. The code is not very straightforward because of the API we work with (we should be able to improve it in the future), but if you want to understand it reading the discussion of the original PR (#666) should help.

**Comment by progman1** [comment]
the very thing itself, thanks!
PR#666?  my knees are beginning to shake...

**Comment by diml** [comment]
:laughing:
