### ISSUE TITLE
PPX context handling

### ISSUE THREAD

**Issue by progman1** [ocaml/dune#3248]
## Expected Behavior
that the ppx.context inserted by the compiler into the AST before passing to the
program given by -ppx is actually made available to that program.

## Actual Behavior
it appears when using the ppxlib infrastructure of dune that the generated ppx.exe 
is used directly on the implementation file (to give xxx.pp.ml), so bypassing the
expected relay of info via a compiler invocation.

## Reproduction

- PR with a reproducing test: 

1.
1.
1.

## Specifications

- Version of `dune` (output of `dune --version`): 2.3.0
- Version of `ocaml` (output of `ocamlc --version`) 4.07.1
- Operating system (distribution and version): raspbian

## Additional information 
the particular information passed via the ppx.context that was wanted in this case:
include_dirs and load_path.

perhaps not strictly a bug but user expectation can only be that the ppx is a pipelined 
processor (via -ppx) as that's the guarantee that only ocaml syntax is permissible.
dune is in effect allowing ppxlib to define the front end of the compiler.

- Link to gist with verbose output (run `dune` with the `--verbose` flag):

**Comment by diml** [comment]
Are you trying to call the typer in a ppx? Passing `include_dirs` and `load_path` won't be enough. Dune needs to know that the ppx is going to read the cmi files.

However, you can use `staged_pps` instead of `pps`. That will cause dune to rely on the `-ppx` option of the compiler. Compilation will be slower, but on the other you will be able to call the typer from the ppx.

**Comment by progman1** [comment]
no typer, just wanted the locations where the compiler will be looking for cmi's.
so I can use staged-pps then.  that would mean using a different ppx api, right?

**Comment by diml** [comment]
Nope, it's all the same. Basically instead of using the following pipeline:

- build ppx.exe
- `ppx.exe file.ml > file.pp.ml`
- `ocamldep file.pp.ml`
- build deps
- `ocaml{c,opt} -c file.pp.ml`

dune uses the following pipeline:

- build ppx.exe
- `ocamldep -ppx "ppx.exe --as-ppx" file.pp.ml`
- build deps
- `ocaml{c,opt} -ppx "ppx.exe --as-ppx" -c file.pp.ml`

**Comment by diml** [comment]
Why do you want the locations where the compiler will be looking for cmi's BTW?

**Comment by progman1** [comment]
thanks for that.
I wrote a debug printing facility a while back (genprint, re-using the compiler's toplevel/genprintval.ml facility) a version of which lives outside the compiler.
but to do so imposed an ugly environment variable hack to be able to locate the cmt files (I mistakenly said cmi's above! what I really want is the 'outputprefix' the compiler would use)

I recently came across the parsetree embedded ppx context and saw that such info could be captured in one's ppx automatically (at least a cmi include path could be chopped and a recursive search would find a ./byte/X.cmt or ./native/X.cmt)

so that's a small improvement that I can make thanks to your clarification/distinction.
it's still of limited use because the cmt records the typedtree with the signature constraint applied (rather than reserving that for the cmti) and the type declarations are duly abstracted.... so print-out of things of interest at the global level will often be littered with "<abstr>" :(

**Comment by diml** [comment]
Ok. This looks like an experiment I did once: https://github.com/diml/ppx_show

Basically, what you want to do is ask the compiler to type the AST, then you can a typedtree that you can process and finally you can convert the typedtree back to an AST. I wouldn't recommended putting this in production as this is using stuff that's very unstable, but it's nice for debugging indeed.

**Comment by progman1** [comment]
thanks for that - very interesting but I find it too tempting to have
an already available
typedtree available. I will enquire on general board why the cmt seems
hobbled.
