### ISSUE TITLE
preprocessor_deps should be mentionned on the preprocessing-specification page

### ISSUE THREAD

**Issue by zapashcanon** [ocaml/dune#3254]
Hi,

Just a note about the documentation. I think it would be nice to have [this page](https://dune.readthedocs.io/en/stable/concepts.html#preprocessing-specification) to mention the `preprocessor_deps` optional field of the library stanza. I didn't found it when grepping the first one and only found it "by chance" later...

**Comment by diml** [comment]
Indeed. Could you submit a PR? :)
