### ISSUE TITLE
Flag disable_dynamically_linked_foreign_archives seems to default to "true", in switches

### ISSUE THREAD

**Issue by corwin-of-amber** [ocaml/dune#3262]
## Expected Behavior

Bytecode executables that depend on foreign libraries should use dynamic loading by default.

## Actual Behavior

When defining a context in `dune-workspace`, Dune falls back to linking with `-custom`. Adding `(disable_dynamically_linked_foreign_archives false)` reproduces the normal behavior (as it was in Dune 2.3.1).

## Reproduction

Extract this tarball and run `dune build --verbose a.bc`.
[dune-custom-bug.tar.gz](https://github.com/ocaml/dune/files/4332745/dune-custom-bug.tar.gz)

## Specifications

- Version of `dune` (output of `dune --version`): 2.4.0
- Version of `ocaml` (output of `ocamlc --version`): 4.08.1
- Operating system (distribution and version): macOS 10.15

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag):
https://gist.github.com/corwin-of-amber/d8f4b9e811c77e1a4cbc5d7e32548977

**Comment by corwin-of-amber** [comment]
May be relevant: https://github.com/ocaml/dune/commit/038564b873c52a83941d2ef9e5788f9deeea45e8

**Comment by diml** [comment]
Ah indeed, the meaning was reversed but not the default value.
