### ISSUE TITLE
Ability to pass profile-dependent flags to ppx rewriters

### ISSUE THREAD

**Issue by jberdine** [ocaml/dune#3278]
## Desired Behavior

It would help if there was a way to specify flags to pass to ppx rewriters in a profile-dependent way. As far as I know, these flags need to be included in the `preprocess` field and there is no way to set something in an `env` stanza that ends up in that field. To work around this, I've changed my ppx rewriter to also accept environment variables, and set them in the `env` stanza. For example:
```
(env
 (dbg
  (flags
   (-w +a-4-9-18-40-42-44-48@50-66 -strict-formats -strict-sequence
     -short-paths -bin-annot -keep-locs -keep-docs))
  (env-vars
   (PPX_TRACE_ENABLED 1))
  (inline_tests enabled))
 (_
  (flags
   (-w -a -noassert -unboxed-types))
  (ocamlopt_flags (-O3))
  (env-vars
   (PPX_TRACE_ENABLED 0))
  (inline_tests disabled)))
```

This is suboptimal for a couple reasons:
1. flags are clearer, easier to trace, etc. as they appear in the build log, error messages, etc.
2. flags are recorded in the generated .merlin files, while env-vars are not (I don't know of any workaround for this, other than to change the defaults to whatever the `(merlin)` context's profile happens to set).

First, is there a way to do this that I have overlooked?
Second, if not, does such a feature seem reasonable?

**Comment by diml** [comment]
Have you looked at cookies?

In the definition of your ppx rewriter, you can have:

```
(library
 ...
 (kind (ppx_rewriter (cookies (ppx_trace_enabled %{env:PPX_TRACE_ENABLED}))))
```

and that will translate to `--cookie ppx_trace_enabled={0|1}` on the command line of the ppx. From the ppx rewriter itself, you can retreive the value via the usual cookie API.

**Comment by jberdine** [comment]
Thanks, I'll look. I don't know about cookies, other than something to reject on the internet.

**Comment by diml** [comment]
Haha, wait don't you use cookies at FB? :stuck_out_tongue_closed_eyes:

**Comment by jberdine** [comment]
Uh, you may be right, I should crawl back under my rock...

**Comment by jberdine** [comment]
Using a cookie seems to work, thanks! But note that as far as I can see, expanding environment variables is not documented [here](https://dune.readthedocs.io/en/latest/concepts.html#variables). Am I blind? Also, maybe there is some documentation I missed, but just as a data point, I basically had to just guess what pattern and expression forms to use with the Driver.Cookie api.

I have to admit that this approach still seems somewhat suboptimal and roundabout. In particular, it seems over-complicated and overkill to set an environment variable in the profile, to only read it when expanding a variable in dune file. It seems to suggest some notion of generic identifier in the dune world whose scope can span files, instead of going with the "nuclear" option of setting an env var just to pass a flag from one dune file to another. Maybe I'm overly hard on env vars, but they are a real pain when trying to make builds reproducible.

**Comment by diml** [comment]
No indeed, it is not documented. We should fix that. I'll open an issue.
