### ISSUE TITLE
Ignore dependencies from other executables

### ISSUE THREAD

**Issue by ghost** [ocaml/dune#328]
When I try to build only one of my executables with `jbuild build src/logarion_cli.exe`, using [this jbuild](https://gitlab.com/orbifx/logarion/blob/1fff19a18c4d8f25cf77022079983b9321ddceb7/src/jbuild) it failed because I'm missing dependencies for `logarion_webserver`. I can't currently install `opium` but I wish to make `logarion_cli` which doesn't depend on opium.

**Comment by rgrinberg** [comment]
Does it work when you put the executables in different directories and write separate jbuild files?

**Comment by orbifx** [comment]
I suppose it will, because there are other jbuild files and those don't require dependencies from other jbuild files.
