### ISSUE TITLE
misplaced documentation comments revealed by ocamlformat

### ISSUE THREAD

**Issue by Strikeskids** [ocaml/dune#3291]
The commit that applied ocamlformat to dune (b1ab9a1a4dcf284582d157410f7c52a4bc80696a) revealed some misplaced comments. Now, these comments refer to the wrong thing. For example, see the documentation of `Promote.Lifetime.t` and `Mode.t` in [src/dune/rule.mli](https://github.com/ocaml/dune/blob/2.4.0/src/dune/rule.mli)

**Comment by diml** [comment]
Indeed, could you submit a PR to fix these please? :)
