### ISSUE TITLE
native mode being used for arch that has no ocamlopt

### ISSUE THREAD

**Issue by andyli** [ocaml/dune#330]
When invoking `jbuilder build @install` in byte-code-only architectures (armel, mips, and others that do not have ocamlopt), it still try to build native code, and fails.

Looks like it is already done for executables (at least according to https://github.com/janestreet/jbuilder/blob/master/doc/jbuild.rst), but not yet for library stanza.

Re: https://lists.debian.org/debian-ocaml-maint/2017/11/msg00057.html

**Comment by andyli** [comment]
Any update on this?
I can see that there are more and more libs switching to dune. This issue will affect updating them in the Debian archive since Debian builds for many byte-code-only architectures.

**Comment by diml** [comment]
Sorry for the late reply, this is supposed to be working but there is a bug in the code. We'll add a test for bytecode only architectures and fix the code.

**Comment by diml** [comment]
It's now fixed in master
