### ISSUE TITLE
Output of custom code generation not detected by dune

### ISSUE THREAD

**Issue by pat227** [ocaml/dune#3301]
## Expected Behavior
Custom code generation should output files into a sub-directory (call it FOO) of the source tree (rooted at BAR) as per an alias defined in a dune file in that sub-directory (within FOO). Dune should copy these custom generated source files to a corresponding location under _build off the root of the entire project before proceeding to compile all source code. This presumes use of "(include_subdirs unqualified)" in the dune file within BAR, which also holds other manually created source files. The dune file within BAR also includes: "(preprocessor_deps (alias FOO/alias_name) (source_tree src/lib/FOO))" to invoke the alias defined therein by that name and to include them for compilation of the project.

## Actual Behavior
Source code is copied to corresponding locations under _build at some point before the the alias has a chance to custom generate required source files. Custom code generation otherwise works ok. The custom code generator actually outputs source files in FOO under BAR in the source tree, but within _build, they are missing from FOO under BAR. A second invocation of dune build (if using (mode fallback) for the alias) completes successfully since the second time around the files are already present from the very start of the build attempt.

Creating two aliases also provides a work-around: if the custom code generator outputs to both FOO locations, first under the source tree and second within the corresponding location under _build, then compilation also proceeds normally on the first attempt. Am I misunderstanding how to use custom code generators in combination with an alias?

## Specifications

- Version of `dune`: 2.0 and 2.01
- Version of `ocaml`: 4.06.1 and 4.06.1+afl
- Operating system : Debian 9, Debian 10.3 and Devuan ascii

Thank you.

**Comment by rgrinberg** [comment]
Do you have a small reproducible test case of what you have in mind? It would make it easier for us to understand the issue.

**Comment by pat227** [comment]
Not immediately. Perhaps I can create one. But the code generator depends
on access to a live database with at least one table. Which makes things a
bit awkward.

**Comment by pat227** [comment]
If I could set up a temporary environment that could demonstrate the issue
and give you ssh credentials to access it, would that work? And is there a
private address to which I could send you those credentials?

**Comment by diml** [comment]
That seems like a lot of hassle on our side. @pat227 could you craft a minimal reproduction case please?

**Comment by rgrinberg** [comment]
Please re-open if you have an example we can use to reproduce.

**Comment by pat227** [comment]
Thank you for reminding me about this. It's been a long time and like I said, there is no way for me to provide an example. You can however create an example if you create for yourself a project, and a local live database with at least one table with a bunch of fields. If you then use the project below as a build-time dependency, in the manner intended, you will see the problem. See the README file. At this point I don't see any other way to provide an example.<br>
Here is the relevant portion of that README file:<br>

>USAGE WITH DUNE:
The overall goal is to create a rule and an alias that invokes the a command line dependency that is this project after installation using opam.<br>
>Within your source code directory, create a dune file, within which you use the "(include_subdirs unqualified)" directive.
Use an alias to create the modules based on tables before compile-time.
Include the following statement, or something similar, to direct dune to execute an alias:<br>
(preprocessor_deps (alias tables/tables_alias) (source_tree src/lib/tables))<br>
> Within your source code subdirectory, create another subdirectory named "tables" and within that create another dune file in   which to define the alias that creates the modules like so:<br>
 (rule
 (alias tables_alias)
 (targets table_name_one.ml table_name_one.mli table_name_two.ml table_name_two.mli table_name_three.ml table_name_three.mli tables.ml)
 (deps (:gen /home/<userhome>/.opam/<version>/bin/ocaml_mysql_model))
 (action (run %{gen} -host <ip_of_db> -user <username> -password <password> -db <dbname> -table-list table_name_one,table_name_two,table_name_three -comparable-tables table_name_one,table_name_two,table_name_three -fields2ignore ts -ppx-decorators fields,eq,make,ord,sexp,show,yojson -destination <path_to_project>/_build/default/src/lib/tables/))
 (mode fallback)
)<br>
>Create a second identical rule and alias within the same dune file that outputs to your "tables" subdirectory within your source code tree, such as <path_to_project>/src/lib/tables. Presently it appears dune copies source code over to the _build tree for compilation from the source code tree, and while our rule generates files within the source code tree, apparently that doesn't happen in time before dune copies source code from the source tree to the build tree. Use of dune locks doesn't seem to help. If anyone knows how to do this with just one rule instead of two with dune, please let me know.

I'm sure it's just my misunderstanding of dune internals or stanzas, but despite reading the dune docs and trying a lot, I could never get dune to incorporate, ie, compile, ocaml modules created on the fly at build time by this little project program I wrote. The modules would only show up in the source code tree, but not in the _build tree. So I had to use a work-around in all projects that depended on the one below. The README file, quoted above, describes the intended use and work-around, which is a pair of rules instead of one rule, one of which outputs to _build. Only then would projects dependent on this command line tool compile ok.
<br>The project below was just an attempt to provide a rudimentary object-relational-mapper. I needed to reduce the time I spent typing boiler-plate describing tables in certain projects that were heavy on database interaction, reading records, writing records, comparing records. The project just writes modules that each describe a table. Nothing else. No checking of sql for validity, etc.<br>
https://github.com/pat227/ocaml-db-model.git
