### ISSUE TITLE
Documentation has a typo

### ISSUE THREAD

**Issue by JasonGross** [ocaml/dune#3304]
I'm not sure if this is the right repo to be reporting this in, but https://dune.readthedocs.io/en/stable/concepts.html#diffing-and-promotion says:
> when `<file1>` and `<file2>` are equal, it doesn’t nothing

"it doesn't nothing" isn't valid English, I assume that it should be either "it does nothing" or "it doesn't do anything"

**Comment by JasonGross** [comment]
Also in "Note that `(cmp a b)` does no end of lines normalization", "end of lines" should be replaced by "end-of-line".

**Comment by JasonGross** [comment]
And in "on Windows, both `(diff a b)` and `(diff? a b)` normalize the end of lines before comparing the files", "end of lines" should be "ends of lines" or "end-of-line characters".

**Comment by diml** [comment]
That's the right repo indeed. Could you open a PR to fix these please?

The files are in the doc/ directory.
