### ISSUE TITLE
Copying a file from outside of a projects causes an internal error

### ISSUE THREAD

**Issue by hcarty** [ocaml/dune#3306]
## Expected Behavior
`dune build` should warn that a file was accessed outside of the context of a project.

## Actual Behavior
`I must not segfault...`

## Reproduction

- PR with a reproducing test: #3307

Until then, given:
`dune-project`
```
(lang dune 2.0)
```
`dune`
```
(executable
 (name main))

(rule
 (targets lib.ml)
 (deps ../libraries/lib.ml)
 (action
  (chdir
   %{workspace_root}
   (copy# %{deps} %{targets}))))
```
`main.ml`
```
let () = Lib.run ()
```
and no `lib.ml` anywhere then `dune build main.exe` will fail with a long backtrace.

## Specifications

- Version of `dune` (output of `dune --version`): Tested with 2.3.0 and 2.4.0
- Version of `ocaml` (output of `ocamlc --version`): 4.08.1
- Operating system (distribution and version): macOS 10.15.4

**Comment by hcarty** [comment]
What's the right way to add a blackbox test?  Following the instructions linked from the issue template:
https://github.com/ocaml/dune/blob/master/HACKING.md#tests
I

**Comment by rgrinberg** [comment]
> dune build should warn that a file was accessed outside of the context of a project.

So you expect that the build rule in your example shouldn't work? As far as I understand, your goal is to copy sources from outside the source directory.

**Comment by diml** [comment]
@hcarty regarding adding a blackbox test, unfortunately this part is a bit flaky. The rules for blackbox tests are generated but the dependencies of the generator are not well specified. If the rule is not generated, try cleaning and running `make test` twice.

**Comment by rgrinberg** [comment]
I believe this was fixed. I don't remember when, but please re-open if there are still issues.
