### ISSUE TITLE
Jbuilder hangs in AppVeyor

### ISSUE THREAD

**Issue by aantron** [ocaml/dune#332]
Here is an example: https://ci.appveyor.com/project/aantron/lwt/build/808/job/x10wi3b2r07mkhdk#L630

I've seen this occur both in MinGW and Cygwin rows.

The build is terminated after running for one hour.

**Comment by dra27** [comment]
I assume it's not consistent, but does this happen frequently enough that you could trigger some builds with remote desktop enabled to see what its frozen at?

**Comment by aantron** [comment]
What would I be looking for? It doesn't look like Jbuilder has compiled a file or run the tester, given the lack of output. I suppose I could poke around the build directory and try to guess the state things are frozen in. I assume it's not just an error with output, though I suppose it could be. Could a hang in test cases prevent Jbuilder from flushing and printing progress output?

**Comment by rgrinberg** [comment]
Is it possible to attach gdb to the running process and get a backtrace perhaps? That's what I'd do on Linux, not sure what the possibilities on Linux are.

**Comment by rgrinberg** [comment]
Please re-open if this is still a problem
