### ISSUE TITLE
dune build %{bin:foo} returns an error

### ISSUE THREAD

**Issue by dra27** [ocaml/dune#3324]
`dune build %{bin:foo}` should ensure that `foo` is built and installed, but instead returns:

```
C:\Users\DRA\Documents\Signup\Payroll>dune build %{bin:MOSS_ESQL.cmxs}
File "command line", line 1, characters 2-21:
Error: %{bin:..} isn't allowed in this position
```

(same behaviour on Linux; Dune 2.4.0)

**Comment by rgrinberg** [comment]
I believe @nojb implemented this. Please re-open if this doesn't work.

**Comment by Alizter** [comment]
This appears to still be broken for different reasons. Currently `build-bin.t` demonstrates this issue. We do an install staging area expansion which ends up with a nonsense path like:
```
  $ dune build %{bin:public}
  Error: File unavailable:
  $TESTCASE_ROOT/../install/default/bin/public
  [1]
```
