### ISSUE TITLE
New external project: 'dune-deps'

### ISSUE THREAD

**Issue by mjambon** [ocaml/dune#3333]
I'm [about to release](https://github.com/ocaml/opam-repository/pull/16144) this command-line tool I made called [dune-deps](https://github.com/mjambon/dune-deps). Please let me know if this would introduce any friction or confusion, like the name for example.

**Comment by diml** [comment]
That seems perfectly fine to me. It's nice to see the dune ecosystem developing :)

**Comment by avsm** [comment]
@mjambon this looks great, thank you! The only feedback I have (apart from appreciation) is that you might want to parse `dune describe` output to generate the dot graph. That will save you having to parse dune files.

**Comment by mjambon** [comment]
Thanks @avsm ! I briefly looked into `dune describe` as @diml also suggested and I didn't see what I was looking for right away. Will have to try harder at some point.

**Comment by diml** [comment]
Yh, this command is still experimental. If you need more things, we can add them.
