### ISSUE TITLE
Adding a library in `jbuild` causes `FLG -ppx` to not be generated

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/dune#334]
I was wondering why Merlin sometimes does not pick up the `js_of_ocaml` PPX. It is due to the `FLG -ppx` line missing in the generated `.merlin` file in some cases.

To reproduce: https://gist.github.com/Leonidas-from-XIV/ffbf7a8afba9c18a02e02f4f5e42e068

Basically, when you have the `library` declaration in `jbuild` it does not generate the `FLG -ppx` line. If you comment it out (in my example the library is just empty), then the `.merlin` file contains the `FLG -ppx` line with the proper path to the built `ppx.exe`.

Building the artifacts themselves (both native code as well as `.bc.js`) is completely unaffected.

**Comment by Leonidas-from-XIV** [comment]
It looks like this is related to #230 where there are multiple configurations and `jbuilder` does not merge the `executable` and `library` configurations regarding PPXes correctly.

**Comment by Leonidas-from-XIV** [comment]
In particular it is the `No_preprocess` that probably triggers the lack of the flag: https://github.com/janestreet/jbuilder/blob/619d64d1016794062f8f9c3f8bfd7ceca8c038bc/src/merlin.ml#L100

Is there any particular reason why it gives up merging different preprocessing options? I could try to give it a shot to produce a better result.

**Comment by rgrinberg** [comment]
I'm closing this as we're waiting for the obsoletion of .merlin files. It's highly unlikely that will work on this.
