### ISSUE TITLE
Cannot run inline tests with multiple modes (e.g. native and js)

### ISSUE THREAD

**Issue by hhugo** [ocaml/dune#3347]
## Expected Behavior
I would like to be able to run inline tests with multiple modes (e.g. native and js)
with just `dune runtest` 

## Actual Behavior
```
Error: Multiple rules generated for
_build/.aliases/default/compiler/tests-jsoo/runtest-35bbbc336be45723611745d39daa46eb:
- compiler/tests-jsoo/dune:5
- compiler/tests-jsoo/dune:5
```

## Reproduction
Set multiple modes in the inline_tests stanza. 
```
(library
 (name tests)
 (libraries)
 (inline_tests
  (flags -allow-output-patterns)
  (modes js native))
 (preprocess (pps ppx_expect)))
```

## Specifications

- Version of `dune` (output of `dune --version`): `2.4.0`

**Comment by diml** [comment]
That's indeed a bug

**Comment by hhugo** [comment]
Thanks
