### ISSUE TITLE
Make dune-cram a public binary

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#3351]
Either by moving it into its own package or just my making it public in dune-private libs.

This binary is required to run configurator's tests.

**Comment by diml** [comment]
We should apply the policy we discussed on slack, i.e. we extract it into a separate public repository. 

There is one last thing to do before we can do that: right now there is still a bit of dune-specific behaviour in it. It's the part that rewrite extensions. For this, one idea we discussed in the past is to have a "portable output" mode for dune, that would be enabled by default when running dune inside dune. Once that's done we can extract it and make it public.

**Comment by rgrinberg** [comment]
We've decided against this in the end. Instead, we'll have a cram stanza.
