### ISSUE TITLE
Question: dune toplevel-init-file not working

### ISSUE THREAD

**Issue by smabie** [ocaml/dune#3364]
Hi, I'm trying to load my modules in to rtop so I can use them. According to https://github.com/stephanieyou/dune/blob/master/doc/toplevel-integration.rst I should be able to run `dune toplevel-init-file` to get the right includes to paste into rtop. It seems like the command isn't defined though. Any help would be appreciated!

**Comment by diml** [comment]
Indeed, it was renamed `dune top`. I'm going to update the doc.

**Comment by diml** [comment]
Done in #3373
