### ISSUE TITLE
Coq theories install path is wrong

### ISSUE THREAD

**Issue by lthms** [ocaml/dune#3380]
So I have created a minimal dune project that should highlights what my issue is better than any English rationale I may come up with: https://github.com/lthms/dune-coq-install-issue

That being said, I will try to explain myself nonetheless. Bear with me!

## Expected Behavior

Using dune 2.5.0 with the new Coq theories composition feature, I expect a theories `.vo` files defined using the following stanza:

```
(coq.theory
  (name Foo.bar)
  (package some-package))
```
to be installed in `user-contrib/Foo/bar`.

## Actual Behavior

Instead, they are installed in `user-contrib/Foo.bar`.

## Reproduction

You can reproduce by cloning the following repo: https://github.com/lthms/dune-coq-install-issue

Then, as suggested by the README, just `dune build; dune install` to see by yourself. (:

## Specifications

- Version of `dune` (output of `dune --version`): `2.5.0`
- Version of `ocaml` (output of `ocamlc --version`): `4.08.0`
- Operating system (distribution and version): up-to-date Archlinux

I am actually skimming dune source file to try to come up with a patch myself. If you happen to know how to fix this, feel free to share! I can do the hard-work if required, but I am not that fluant in OCaml so. (:

I hope this issue describes the problem well enough. And thanks for all the work you put in dune, this tool is really enjoyable to use!

**Comment by lthms** [comment]
Okay, so I have dug into that issue, found the issue, fix the issue… then rebased against `master` only to see that it has already been taken care of. Sorry about that. x)

**Comment by ejgallego** [comment]
Sorry @lthms about this embarrassing bug, and thanks for testing; indeed it was fixed by #3358 ; @rgrinberg we found no more bugs so far from the Coq side 2.5.1 would be OK.

This bug is not super serious but annoying for those that find it.

**Comment by lthms** [comment]
No worries, it was an interesting dive into `dune` codebase (whose quality I can only emphasize here!) at the very least.
