### ISSUE TITLE
[coq] Install .v files along with .vo

### ISSUE THREAD

**Issue by lthms** [ocaml/dune#3383]
## Desired Behavior

Currently, `dune` only installs `.vo` files of a Coq theory. It would be a good idea to also install `.v` files too (just like `coq_makefile`). It would make possible for tools such as ProofGeneral/company-coq to leverage them.

**Comment by ejgallego** [comment]
Thanks for the report @lthms , indeed that was an oversight, I think we should install `.v` files too; the change should be straighforward.
