### ISSUE TITLE
Coq libraries match several files in path

### ISSUE THREAD

**Issue by Tuplanolla** [ocaml/dune#3389]
## Reproduction

Let us set up a project in the following way.

```
$ cat dune-project
(lang dune 2.5)
(name counterexample)
(version 0.0.0)
(using coq 0.2)
(package
  (name counterexample))

$ cat dune
(coq.theory
  (name Counterexample))
(include_subdirs qualified)

$ cat A/M.v
Definition x : nat := 2.

$ cat B/M.v
Definition y : nat := 3.

$ cat C/M.v
From Counterexample Require Import A.M.
From Counterexample.B Require Import M.
Definition z : nat := x * y.
Compute z.
```

## Expected behavior

When we use `coq_makefile` to compile the project,
everything goes smoothly.

```
$ coq_makefile -Q . Counterexample -o _CoqMakefile A/M.v B/M.v C/M.v
$ make -f _CoqMakefile
COQDEP VFILES
COQC A/M.v
COQC B/M.v
COQC C/M.v
     = 6
     : nat
$ make -f _CoqMakefile cleanall
```

## Actual behavior

However, when we use `dune` to compile the project,
the compiler get confused with unambiguous imports.

```
$ dune build
      coqdep C/M.v.d
*** Warning: in file C/M.v,
    required library M matches several files in path
    (found M.v in B, A and C; used the latter)
        coqc C/M.vo
     = 6
     : nat
$ dune clean
```

## Specifications

Here are some version numbers.

```
$ dune --version
2.5.0

$ ocamlc --version
4.09.0

$ coqc --version
The Coq Proof Assistant, version 8.11.1 (April 2020)
compiled on Apr 18 2020 16:20:00 with OCaml 4.09.0

$ opam --version
2.0.6

$ cc --version
cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ uname -a
Linux z370 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

## Additional information

This may be related to #2585.

**Comment by ejgallego** [comment]
Hi @Tuplanolla ; almost for sure this is a Coq bug, a variation of https://github.com/coq/coq/issues/11631 and https://github.com/coq/coq/issues/9080

The reason that Coq makefile works better here is that it generates a single `v.d` file for all `.v` files in the project which somehow avoids this bug in coqdep.

I have a fix in the queue for 8.12 ; I'll see what can be done for older Coq versions.

**Comment by Tuplanolla** [comment]
Jolly good!

**Comment by ejgallego** [comment]
Note that I still plan to mitigate this for Coq versions < 8.12 in dune itself [by actually running coqdep once per lib as opposed as once per file as it is now, due to coqdep scanning the tree Dune builds have a bit of slowdown due to so many coqdep calls]

**Comment by Tuplanolla** [comment]
The problem persists with Coq 8.12.0 and Dune 2.6.2.
Some of the fixes must have stalled,
which is unfortunate but understandable.

**Comment by Blaisorblade** [comment]
I notice that coq_makefile uses -Q rather than -R, and https://github.com/coq/coq/issues/11631 points out using -Q avoids the problem.
Meanwhile, https://github.com/coq/coq/issues/11631#issuecomment-588290220 points out that `-R` has problematic semantics.

**Comment by ejgallego** [comment]
I think there are two problems here, one is a bug in coqdep, that hopefully will be solved when we make the code handling loadpaths common across all tools, and problems with `-R` / `From` that make the above code more complicated and prone to bugs.

So indeed we are more or less aware upstream, but we just didn't get the cycles to work on it a lot pending other work that is required [for example recently untangled the loadpath code, but stuff such as https://github.com/coq/coq/pull/13418 should also be concluded as to be able to properly have the common logic.
