### ISSUE TITLE
dune 2.5.0: permission denied leads to stack trace

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#3390]
See https://github.com/realworldocaml/book/issues/3301

@yminsky is on dune 2.5.0. The .merlin file being read-only is probably a throwback to #3026, but the stack backtrace probably shouldn't happen on latest dune.

**Comment by diml** [comment]
We don't print backtraces for `Unix.Unix_error`, we should probably treat `Sys_error` the same.

**Comment by rgrinberg** [comment]
This is fixed in master.
