### ISSUE TITLE
Generate install files at root regardless of opam file location ?

### ISSUE THREAD

**Issue by pirbo** [ocaml/dune#3405]
In tezos/tezos gitlab repository (and the archived generated from it), the ~90 opam files defined there are not at the root. Instead, all files related to library `tezos-foo` are in folder `src/lib_foo/.

In this configuration, doing `dune build -p tezos-foo` at the root works to the limit that it generates `src/lib_foo/tezos-foo.install` that opam "doesn't see". For this reason, a `["mv" "src/lib_foo/%{name}%.install" "./"]` has to be added to the build stage of all packages.

Note that support at the opam level for this setting will be added in opam 2.1. Quoting @hnrgrgr:
> The next version of opam should add better support for non-toplevel .opam. See: ocaml/opam#3499 Basically, it allows to add a field subpath in the package description, meaning: this package only requires this fragment of the .tar.gz (or the repository) in order to build. So opam only extracts (or fetch) the required subpath and build directly in the subdirectory. So, from the dune perspective, both.opam and .install are at toplevel.

but as @avsm replied, we may not want to wait for the availability of opam.2.1 in all stable releases of distrib to handle it nicely.

_Originally posted by @avsm in https://github.com/ocaml/opam-repository/pull/16215_

**Comment by diml** [comment]
In the meantime, is the `mv` workaround not good enough?

**Comment by pirbo** [comment]
I'm fine with it. Anil seems not.

**Comment by diml** [comment]
@asvm, what is the problem with the workaround? If we have a good perspective that we won't need all that in the future, I'd rather keep Dune simple and not commit to maintain one more feature that in the end is only going to be used temporarily.

**Comment by jeremiedimino** [comment]
Alright, given that we have a good perspective that eventually none of this will be necessary, let's not over-optimise for the present.

**Comment by avsm** [comment]
It's a blocker for switching tezos to do opam file generation from dune-project. But that can be a separate issue indeed.

I also wanted to check that tezos would continue to build as a duniverse, which it does. So all is good!
