### ISSUE TITLE
Message for missing extensions is not correct

### ISSUE THREAD

**Issue by diml** [ocaml/dune#3412]
## Expected Behavior

When we use an experimental extension without declaring it, the suggestion should be correct:

```
$ dune build
Info: Creating file dune-project with this contents:
| (lang dune 2.5)
File "dune", line 3, characters 1-12:
3 |  (variant x))
     ^^^^^^^^^^^
Error: 'variant' is only available since version 0.1 of the experimental
library variants feature.. Please update your dune-project file to have
(using library_variants 0.1), but please note that this extension is
experimental and we might drop support for it in the future.
```

## Actual Behavior

```
$ dune build
Info: Creating file dune-project with this contents:
| (lang dune 2.5)
File "dune", line 3, characters 1-12:
3 |  (variant x))
     ^^^^^^^^^^^
Error: 'variant' is only available since version 0.1 of the experimental
library variants feature.. Please update your dune-project file to have (lang
0.1).
```

## Reproduction

```
$ cat > dune <<EOF
(library
 (name toto)
 (variant x))
EOF
$ dune build
```

## Specifications

- Version of `dune` (output of `dune --version`): 2.5.0
- Version of `ocaml` (output of `ocamlc --version`): 4.09.0
- Operating system (distribution and version): Ubuntu 19.10

**Comment by voodoos** [comment]
In fact, the expected behaviour should be the automatic addition of the correct field in the `dune-project` file. For example, is one tries to use the menhir extension without declaring it, the following message appears:

```
Info: Appending this line to dune-project: (using menhir 2.1)
```

**Comment by diml** [comment]
Yeah, but that's only for non-experimental extensions. For experimental ones, we want the user to explicitly add it so that they are aware they are doing something dodgy.
