### ISSUE TITLE
`subdir` doesn't work in included files

### ISSUE THREAD

**Issue by samoht** [ocaml/dune#3419]
Using `(subdir foo <action>)` in `dune.inc` and then doing `(include dune.inc)` in `dune` results in:

```
File "dune.inc", line 3, characters 1-7:
1 | (subdir fooo
     ^^^^^^
Error: Unknown constructor subdir
```

(using dune 2.5.0)

**Comment by rgrinberg** [comment]
Yes, that's quite annoying. It's also impossible to use `subdir` in dune syntax files either. This will require a little longer to fix.
