### ISSUE TITLE
a -C option might be nice (a la make)

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/dune#342]
specification: 
Change to directory dir before doing anything else.

**Comment by UnixJunkie** [comment]
where is the entry point of jbuilder?
The 'main ()' function with the first parsing of the command line args.

**Comment by diml** [comment]
It's in [bin/main.ml](https://github.com/janestreet/jbuilder/blob/master/bin/main.ml#L1086).

BTW, jbuilder has a `--root` option. Isn't it the same?

**Comment by UnixJunkie** [comment]
probably.
