### ISSUE TITLE
dune build @fmt should use the current executable instead of looking for it in PATH

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#3420]
Currently, when using `dune build @fmt` to format `dune` files, we look in the `PATH` to find a `dune` executable. There are two issues with this:

1) `dune` may not be in the `PATH`
2) if a directory in the `PATH` happens to contain any *file* named `dune`, then this file will be taken to be the `dune` executable

It seems to me a better way could be to simply use the currently executing `dune` binary instead of looking for it in the `PATH`.

**Comment by jeremiedimino** [comment]
In fact, any reason why we don't just do this in-process? `dune` files are small and the formatting is unlikely to take any time.

/cc @emillon who worked on this.
