### ISSUE TITLE
Improve management of temporary files

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml/dune#3432]
In `src/dune/process.ml`, we have a `Temp` sub-module for dealing with temporary files. This module ensures that all temporary files are systematically deleted on exit. It would be nice to extract and generalise this module. We could also go a bit further and:

- create a single temporary directory to store all temporary files
- systematically delete this directory when dune exists, normally or abnormally
- set the `TEMP` environment variable to point to this directory so that commands started by dune put their temporary files there
- clear the contents of this directory at the end of each run in polling mode, so that if some commands don't properly clean up their temporary files we don't leak them

We actually do something quite similar in Jenga.

**Comment by rgrinberg** [comment]
@NathanReb are you still working on this issue?

**Comment by NathanReb** [comment]
Not really at the moment, I only extracted the `Process.Temp` module but haven't had the chance to work on this ever since!

**Comment by rgrinberg** [comment]
I gave this a stab in #3691. I'd like to see this in 2.7
