### ISSUE TITLE
ERROR `dune rules -o` fails (option "output to stdout")

### ISSUE THREAD

**Issue by MdeLv** [ocaml/dune#3440]
## Expected Behavior
```
$ dune rules <path-to-dune-file> -m -o Makefile
$ ls
Makefile ...
```

## Actual Behavior
```
$ dune rules <path-to-dune-file> -m -o Makefile
Internal error, please report upstream including the contents of _build/log.
Description:
  ("Fdecl.get: not set", {})
Description:
  ("Fdecl.get: not set", {})
Description:
  ("Fdecl.get: not set", {})
Raised at file "src/stdune/code_error.ml", line 9, characters 30-62
Called from file "src/stdune/fdecl.ml" (inlined), line 29, characters 13-53
Called from file "src/stdune/path.ml", line 833, characters 26-60
Called from file "src/stdune/option.ml", line 9, characters 21-26
Called from file "src/stdune/option.ml" (inlined), line 21, characters 15-28
Called from file "bin/print_rules.ml", line 110, characters 12-44
Called from file "vendor/cmdliner/src/cmdliner_term.ml", line 25, characters
  19-24
Called from file "vendor/cmdliner/src/cmdliner.ml", line 146, characters 9-16
Called from file "vendor/cmdliner/src/cmdliner.ml", line 176, characters
  18-36
Called from file "vendor/cmdliner/src/cmdliner.ml", line 312, characters
  20-46
Called from file "bin/main.ml", line 261, characters 10-51

```
Same error without the `-m` option.
I also tried `-o=Makefile` `-o="Makefile"` `-o='Makefile'`... which fail.

 While this works with the output redirection symbol:
```
$ dune rules <path-to-dune-file> -m > Makefile
$ ls
Makefile ...
```

- Version of `dune` : 2.5.1
- Version of `ocaml` : 4.07.1
- Operating system : debian buster

**Comment by MdeLv** [comment]
Thanks. 
It has been merged to master 12 days ago.
When is it supposed to be available on opam? (without needing to pin this repo)

Do you have an overview on the ongoing opam-repository publishing process? (for me it's a blackbox; where can I have a look at what is going on? publishing requested/approved/published on opam-repository...)

**Comment by rgrinberg** [comment]
We’d like to release 2.6 in the next week or two. There’s still some changes pending before we can release.

This bug doesn’t seem to be critical enough to warrant a bug fix release
