### ISSUE TITLE
append/prepend to PATH-like variables in dune-workspace

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#3441]
It would be useful to be able to prepend/append to PATH in `dune-workspace` files, which currently support:

```
(paths (<var1> <val1>) .. (<varN> <valN>))
```

This can be used to introduce a local OCaml compiler and associated tools to a dune build seamlessly, without interfering with the main dune build graph.

Discussed with @rgrinberg offline.

**Comment by jeremiedimino** [comment]
Doesn't `(paths (PATH <path> :standard))` already works?

/cc @nojb who added this feature IIRC

**Comment by nojb** [comment]
Indeed it should work I think. It was added in #2426. Did you try it @avsm?

**Comment by avsm** [comment]
It works, and allows a `dune build` to proceed without an OCaml or opam installation on the system. This is how the duniverse bootstrap will work shortly. Thanks!

```
(lang dune 2.5)
(context (default (paths (PATH _ocaml/bin :standard))))
```
