### ISSUE TITLE
What's the behavior of dune runtest ?

### ISSUE THREAD

**Issue by Ninjapouet** [ocaml/dune#3442]
I'm quite puzzled with the way dune runtest works. I don't know if it's a bug or what so let me explain the issue. I have a simple OCaml project whose layout is something like that:
```
.
├── bin
│   ├── dune
│   └── server.ml
└── test
    ├── data
    │   ├── hello.txt
    ├── dune
    ├── test.ml
    └── test.expected
```
The target bin/server.exe is a simple HTTP server I want do test with some curl commands. 

The test/dune is like that :
 ```
 (test
   (name test)
   (modules test)
   (deps
     (:server ../bin/server.exe)
     (:data (source_tree data)))
   (libraries ...)
   (preprocess (pps ...))
)
```
The test itself is quite simple: it runs the bin/server.exe in background, runs the curl commands, checks the results and kill the server. After a dune clean, if I run dune runtest, the tests go completely wrong with curl saying it can't connect to the server for the latter isn't launched. If I retry dune runtest, it obviously doesn't runs the test (for the test do sleep a bit and the result is immediate) and prints the same diff. I understand that automatic caching is interesting but I don't find if we can deactivate it (i tried -f or --cache disabled with no results).

Here is the strange thing to me: if I simply add an empty line to test/test.ml so the test binary should be **exactly** the same but it forces its recompilation and running dune runtest again gives a correct result: all is correctly launched and works fine.

dune clean && dune runtest makes the whole thing go wrong again. What I understand of all of it is that dune runtest somehow runs the test before its dependencies are ready and the caching mechanism prevents the test to be reran correctly.

Can someone confirm or not my understanding ? And maybe give me a hint to avoid such situation ?

**Comment by Ninjapouet** [comment]
I forgot to say i'm using dune 2.5.0 with OCaml 4.08.1. If my story looks like a real bug i'll post more details to reproduce the issue.

**Comment by jeremiedimino** [comment]
Dune will definitely not run the test before the dependencies are ready. If you have a minimal example that demonstrate this behaviour, then it would point to a bug in dune.

If your tests has dependencies that are too difficult to specify, you can depend on `(universe)` to force the test to be re-executed everytime.

**Comment by Ninjapouet** [comment]
The project was rewritten using dune 2.7 with cram and the dependency issue disappeared. I strongly suspect that dependencies between binaries weren't specified correctly. I close this issue for now until the problem shows again (if ever).
