### ISSUE TITLE
dune init exec foo src --lib=lwt.unix fails

### ISSUE THREAD

**Issue by bikallem** [ocaml/dune#3443]
## Expected Behavior
```dune init exec foo src --lib=lwt.unix``` to succeed and create a ```dune``` file and ```src``` folder. 

## Actual Behavior
Error below.
```
dune: option `--libs': invalid element in list (`lwt.unix'): invalid
      component name `lwt.unix'
      Library names must be non-empty and composed only of the
      following
      characters: 'A'..'Z', 'a'..'z', '_' or '0'..'9'.
Usage: dune init [OPTION]... INIT_KIND NAME [PATH]
Try `dune init --help' or `dune --help' for more information.
```

## Reproduction
Any lib name with that has characters other than 'A - Z', 'a - z', '_', '0-9'.

```dune init exec foo src --lib=lwt.unix```

## Specifications

- Version of `dune` (output of `dune --version`): 2.5.0
- Version of `ocaml` (output of `ocamlc --version`): 4.10.0
- Operating system (distribution and version): red hat linux 8.2

**Comment by bikallem** [comment]
Also it seems the ```dune exec init ``` accepts both options ```--lib``` and ```--libs```. ```--lib``` is not documented so shouldn't it fail?? PR #3444 just fixes the first part of the bug. Should we remove ```--lib``` from being accepted?

**Comment by shonfeder** [comment]
@bikallem thanks for reporting this and fixing it! :)

The latter is not a bug in implementation, it's just [part of how cmdliner works](https://erratique.ch/software/cmdliner/doc/Cmdliner):

>  Long names can be specified by any non ambiguous prefix

So `dune exec init foo src --li foo` will also work! We could add this to the inline documentation somewhere, so we could at least point to that for future bug reports?

**Comment by jeremiedimino** [comment]
Documenting it seems good, but we should make it clear that this is not something we encourage users doing, or at least not in scripts given that it is not future proof.
