### ISSUE TITLE
Bug in PR #3410

### ISSUE THREAD

**Issue by reubenrowe** [ocaml/dune#3461]
I think the merge of PR #3410 has introduced a bug.

I am not sure of the exact nature of the bug, but one effect is that the `containers` library now no longer compiles.

## Expected Behavior

Containers library (v2.8.1) should compile.

## Actual Behavior

Library does not compile.

```
dune build   @install
     mkshims src/core/CCShimsArrayLabels_.ml,src/core/CCShimsArray_.ml,src/core/CCShimsFormat_.ml,src/core/CCShimsFun_.{ml,mli},src/core/CCShimsList_.ml,src/core/CCShimsMkLet_.ml,src/core/CCShims_.ml (exit 2)
(cd _build/default/src/core && ./mkshims.exe)
Fatal error: exception File
"/tmp/containers.2.8.1/_build/default/.dune/configurator",
line
1,
characters
1-52:
Error: Atom expected

     mkflags src/flambda.flags (exit 2)
(cd _build/default/src && ./mkflags.exe)
Fatal error: exception File
"/tmp/containers.2.8.1/_build/default/.dune/configurator",
line
1,
characters
1-52:
Error: Atom expected

     mkshims src/monomorphic/CCMonomorphicShims_.ml (exit 2)
(cd _build/default/src/monomorphic && ./mkshims.exe) > _build/default/src/monomorphic/CCMonomorphicShims_.ml
Fatal error: exception File
"/tmp/containers.2.8.1/_build/default/.dune/configurator",
line
1,
characters
1-52:
Error: Atom expected

Makefile:7: recipe for target 'build' failed
make: *** [build] Error 1
```

## Reproduction

    > opam source containers
    > cd containers.2.8.1
    > make

## Specifications

- Version of `dune` (output of `dune --version`): commit 1ce1cea
- Version of `ocaml` (output of `ocamlc --version`): 4.09.0
- Operating system (distribution and version): Ubuntu 16.04

**Comment by jeremiedimino** [comment]
Hmm, it's because #3410 changes the format to `csexp`. You need to pin `dune-configurator` to the development version until we do the next release.

**Comment by jeremiedimino** [comment]
We just had a chat about this with @rgrinberg. Basically #3410 changes the format of a file generated by dune and read by `dune-configurator`. We are going to change things so that the new dune generates both the old and new format for a while. This will make the change of format a bit smoothter.

**Comment by reubenrowe** [comment]
Thanks for the feedback. If you are going to release a new version of `dune-configurator` at the same time as the new version of `dune`, and have the new version of `dune` depend on it, then that would be fine. You and Rudi will know best though.

**Comment by rgrinberg** [comment]
The PR me and Jeremie had in mind: https://github.com/ocaml/dune/pull/3470
