### ISSUE TITLE
Dune + Bisect integration runs tests twice

### ISSUE THREAD

**Issue by aantron** [ocaml/dune#3472]
## Expected Behavior

After setting up coverage, `dune runtest` should still run tests only once.

## Actual Behavior

Tests are run twice, the second time in the coverage context.

```
$ dune runtest
        test alias test/runtest
.................................................................................
Ran: 81 tests in: 0.32 seconds.
OK
        test alias test/runtest [coverage]
.................................................................................
Ran: 81 tests in: 0.24 seconds.
OK
```

## Reproduction

1. `git clone https://github.com/aantron/lambdasoup.git`
1. `cd lambdasoup`
1. `git checkout dune+bisect`
1. `dune runtest`

The branch is [here](https://github.com/aantron/lambdasoup/tree/dune%2Bbisect) and its diff to `master` is [here](https://github.com/aantron/lambdasoup/commit/166999b57cc8b8d909d22b58199785ddd97319a1).

## Specifications

- Version of `dune` (output of `dune --version`): 2.5.1-99-gf6ef0be5
- Version of `ocaml` (output of `ocamlc --version`): 4.08.0
- Operating system (distribution and version): WSL

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag): https://gist.github.com/aantron/170b63ab614935440c42b76b56b9eb8e

**Comment by jeremiedimino** [comment]
Do you have two build context defined? Dune can't really guess where you want to run the test, so it just run them everywhere.

I have been thinking that we should allow to mark certain contexts as "auxiliary". Targets and aliases passed on the command line would ignore auxiliary contexts.

**Comment by jeremiedimino** [comment]
We could also support `--context`, so that you could do `dune runtest --context coverage`

**Comment by aantron** [comment]
Yes. As I understand it, it's necessary to define a context to use Bisect_ppx conditionally with the current integration.

**Comment by aantron** [comment]
> We could also support `--context`, so that you could do `dune runtest --context coverage`

Without auxiliary contexts, or some other approach, this would still be invasive on normal builds, requiring adding `--context default` to preserve "ordinary" behavior.

**Comment by jeremiedimino** [comment]
Indeed. The other option would be to allow to set `(bisect_enabled true)` via the command line. Though it feels a bit odd to add command line arguments related to third-party tools. The language is versioned so we could easily migrate to a more decentralised model in the future, but the CLI is not so any command line argument we add will virtually exist forever.

**Comment by aantron** [comment]
I previously suggested not to use contexts for coverage (eventually), as it pervasively affects any custom scripts a user might have that run as part of testing, whether by requiring them to add `--context foo`, or by requiring them to change `_build/default` to `_build/coverage`. This means such scripts will need to adapt depending on whether they are running with or without coverage enabled, which IMO is impractical to require. The current Dune [instructions](https://github.com/aantron/bisect_ppx#Dune) cause Dune to rebuild with/without coverage in-place in `_build/default`, which makes coverage a true "aspect," in the sense that testing works the same with and without coverage enabled (except for the side-effect of coverage output being generated).

I hope Dune will switch to something like this in the future. If we release the current setup, and it is temporary, we should not add something as permanent as a command-line argument.

**Comment by jeremiedimino** [comment]
How would that work?

**Comment by aantron** [comment]
The instructions already work, you can try them. Are you asking about the interface?

**Comment by jeremiedimino** [comment]
Yes, what interface do you have in mind?

**Comment by aantron** [comment]
I would prefer a profile-based interface or similar. I'm not sure how to expose an interface for a special-cased feature without making the interface also be a special case in say, the command line.

**Comment by jeremiedimino** [comment]
Alright, well let see what feedback we get from users. It's all versioned, so we can always introduce another mechanism if the current one is not good enough.

**Comment by aantron** [comment]
This no longer happens with the new integration added in Dune 2.7.0, so I think the issue can be closed.

**Comment by nojb** [comment]
Thanks for the update, closing.
