### ISSUE TITLE
Crash with (bisect_ppx) and (lang dune 2.5)

### ISSUE THREAD

**Issue by aantron** [ocaml/dune#3473]
## Expected Behavior

If one accidentally does not use `(lang dune 2.6)`, Dune should print a neat error message that `(bisect_ppx)` requires 2.6.

## Actual Behavior

`Internal error, please report upstream including the contents of _build/log.`

## Reproduction

1. `git clone https://github.com/aantron/lambdasoup.git`
1. `cd lambdasoup`
1. `git checkout dune+bisect`
1. Edit `dune-project` to have `(lang dune 2.5)`
1. `dune runtest`

## Specifications

- Version of `dune` (output of `dune --version`): 2.5.1-99-gf6ef0be5
- Version of `ocaml` (output of `ocamlc --version`): 4.08.0
- Operating system (distribution and version): WSL

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag): https://gist.github.com/aantron/8d8c13ddde1e6b7f70f33d3d7536c14a

**Comment by jeremiedimino** [comment]
Agreed

**Comment by jeremiedimino** [comment]
Adding to the 2.6 milestone because that should be easy to fix and it seems like something we should fix before releasing support for bisect_ppx.
