### ISSUE TITLE
Dune doesn't run tests after rebuild from dependent change.

### ISSUE THREAD

**Issue by d3zd3z** [ocaml/dune#3475]
## Expected Behavior
`dune runtest` runs the test suite.
Edit a string constant in `src/hashindex.ml`.
Expect `dune runtest` to run the test suite again, as code being tested has changed.

## Actual Behavior
Instead, `dune runtest` rebuilds `_build/default/test/test.exe` but does not run it.

## Reproduction
Unfortunately, I have not been able to reproduce this with a simpler case. I am able to see the failure on this repo: https://github.com/d3zd3z/oborg/commit/626b71c692be2a55a55436ad534bb923b21a278f

## Specifications

- Version of `dune` (output of `dune --version`): Tested with 2.4.0, as well as 2.5.1-138-g73a70c02
- Version of `ocaml` (output of `ocamlc --version`): 4.10.0
- Operating system (distribution and version): Fedora f31

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag): https://gist.github.com/d3zd3z/ce38984ed28b7a6bf9d19b947c76fd13

**Comment by rgrinberg** [comment]
I'm unable to run the tests because I don't have a borg binary. Where do I obtain the binary? Or is there a way to replace this binary with something else perhaps?

**Comment by d3zd3z** [comment]
Let me see if I can reduce some of the dependencies in the test.

**Comment by d3zd3z** [comment]
After digging around to reduce dependencies, I figured out what was wrong, and it isn't a Dune issue. Turns out that my tests indeed were not running the code that I was modifying. I'll go ahead and close this issue.
