### ISSUE TITLE
Make jbuilder log workspace root to stdout (or stderr) in case it's different than cwd

### ISSUE THREAD

**Issue by andreypopp** [ocaml/dune#348]
I understand that jbuilder already logs workspace root into `_build/log` but in some setups with filesystem sandboxing jbuilder can't even create `_build/log` file (seen some such failures and they were hard to debug remotely).

Even besides that it would be useful and informative to have workspace root printed on stdout when it's different than pwd.

cc @rgrinberg

**Comment by rgrinberg** [comment]
> but in some setups with filesystem sandboxing jbuilder can't even create _build/log file (seen some such failures and they were hard to debug remotely).

I think this is orthogonal. I think we should improve the error handling for this situation. But I'm not really convinced that we need this extra logging. The situation is common enough that this would simply intrusive.

**Comment by rgrinberg** [comment]
I'm inclined to reject this. To repeat, pwd <> workspace root is quite a common use case. Whenever `_build/log` fails to create, dune seems to just crash btw. But I think the ideal behavior would be for dune to warn about this and log to stderr instead.
