### ISSUE TITLE
Drop support for library variants

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml/dune#3483]
Following #3417 

- make the `default_implementation` part of the vanilla language
- drop the `library_variants` experimental extension and all the code associated with it

**Comment by jeremiedimino** [comment]
@rgrinberg do you want to do the honours?

**Comment by rgrinberg** [comment]
I would like to introduce another restriction:

default implementations for a virtual library must be defined in the same package as the virtual library? @jeremiedimino wdyt?

**Comment by jeremiedimino** [comment]
That seems like a good restriction to me!
