### ISSUE TITLE
[RFC] Distributed store artifact transfer protocol

### ISSUE THREAD

**Issue by mefyl** [ocaml/dune#3498]
# Rationale

The distributed cache needs a protocol to sync local artifact with a central repository. This protocol should be fixed so the clients and the server implementation can be changed without impacting the other side.

A first prototype has been created with WebDAV. WebDAV  is extremly simple when it comes to basic operations : fetching a file is a simple HTTP Get, uploading a file is a simle HTTP Put, etc. It quickly becomes hairy beyond that point though, with something as simple has handling file permissions - in our case whether the executable bit is set - requiring extension HTTP methods (eg PROPFIND) to get file metadata, separate requests, and handling XML responses as pretty as 
```
  <D:prop xml:lang="en" xmlns:D="DAV:">
    <x:author xmlns:x='http://example.com/ns'>
      <x:name>Jane Doe</x:name>
      <!-- Jane's contact info -->
      <x:uri type='email' 
             added='2005-11-26'>mailto:jane.doe@example.com</x:uri>
      <x:uri type='web' 
             added='2005-11-27'>http://www.example.com</x:uri>
      <x:notes xmlns:h='http://www.w3.org/1999/xhtml'>
        Jane has been working way <h:em>too</h:em> long on the  
        long-awaited revision of <![CDATA[<RFC2518>]]>.
      </x:notes>
    </x:author>
  </D:prop> 
```

Many file synchronization software exist, but no real widespread protocol that I know of. Since the matter can be handled rather simply for our use case, it does not seem unreasonable to describe a small protocol.

We propose here a very simple protocol, on top of HTTP, to synchronize files. HTTP seems like a good pick has it is widely used and available, separates transport (compression etc) and security (encryption, authentication, etc) from the protocol, and should yield good performances with connection keep-alive and requests pipelining.

# Protocol

## Path

Once rooted at an endpoint - say `https://some.host/some/root/`, all subsequent paths map directly to filesystem paths.

## Data retrieval.

Retrieving a file is a simple GET on that path, the body response being the verbatim file. The file not existing can be reported with a 404.

## Data upload.

Sending a file is a simple PUT on that path, with the file verbatim in the request body. Parent directories are created if needed. Illegal operations, such as replacing a directory with a file, can be handled with `415 Unsupported Media Type` for instance.

## Data removal.

Removing a file is a simple DELETE on that path.

## Deduplication

The `Etag` header can easily be used to avoid transfering files already present on the peer back and forth. When checking a metadata file, the client can include a hash of that file and the server can respond with a 304 Not Modifed. Likewise when uploading a file, the server can indicate it already has it and short-circuit the actual upload. This is all done in one request.

See https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/ETag.

## Metadata

We can easily get and set metadata on files using header extension. For instance, the executable bit could be read and set with an `X-executable: true | false` header.

## Range retrieval

If for any reason, some massive file is to be split in chunks to be streamed in several requests, this can be handled with the `Range` HTTP headers. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests.

# Execution

I think such a prototype could be implemented fairly quickly in a few hundreds line of Caml. 95 % of the work is already done thanks to the completeness  of the HTTP protocol and the large ecosystem that already exists in caml, both server and client side. Finally, in terms of production, a vast set of tool exist to proxy, load balance, authenticate, ... any kind of HTTP payload.

As a nice to have, the centralized store can even be interacted with using a web browser of http CLI tools, both to read and write, making it trivial to debug or script upon.

**Comment by snowleopard** [comment]
The current description seems to treat files as opaque objects, in particular there is no distinction between artifacts and metadata files -- they are all just files which we can upload and download. 

If the protocol makes no distinction between the type of files, couldn't we use something like the [Network File System](https://en.wikipedia.org/wiki/Network_File_System) protocol?
