### ISSUE TITLE
Dune doesn't cause Merlin to flag use of deprecated calls.

### ISSUE THREAD

**Issue by yminsky** [ocaml/dune#3508]
## Expected Behavior

Consider the following snippet:

```ocaml
open Base
let x = sqrt 3.
```

will fail, with this error:

```
dune build @all
Entering directory '/home/yminsky/Documents/code/siggy'
File "bin/main.ml", line 3, characters 8-12:
3 | let x = sqrt 3.
            ^^^^
Error (alert deprecated): Base.sqrt
[2016-09] this element comes from the stdlib distributed with OCaml.
Use [Float.sqrt] instead.
```
I would expect Merlin to highlight this error in the buffer, since it's going to cause the compilation to fail.

## Actual Behavior

It is not flagged by Merlin.

## Reproduction

The example file given above is enough to replicate it, under the name main.ml.  Just save that file, and do a dune build.   You need a dune file like this:

```
(executable
 (libraries base)
 (name main))
```

You can just use Merlin in the ordinary way to see the problem. I've replicated the issue on emacs and vscode.

## Specifications

- Version of `dune`: 2.5.1
- Version of `ocaml`: 4.10.0
- Operating system: Fedora 31

**Comment by yminsky** [comment]
In case this is helpful, here's the state of the generated .merlin file:

```
EXCLUDE_QUERY_DIR
B /home/yminsky/.opam/4.10.0/lib/base
B /home/yminsky/.opam/4.10.0/lib/base/base_internalhash_types
B /home/yminsky/.opam/4.10.0/lib/base/caml
B /home/yminsky/.opam/4.10.0/lib/base/shadow_stdlib
B /home/yminsky/.opam/4.10.0/lib/sexplib0
B ../_build/default/bin/.main.eobjs/byte
S /home/yminsky/.opam/4.10.0/lib/base
S /home/yminsky/.opam/4.10.0/lib/base/base_internalhash_types
S /home/yminsky/.opam/4.10.0/lib/base/caml
S /home/yminsky/.opam/4.10.0/lib/base/shadow_stdlib
S /home/yminsky/.opam/4.10.0/lib/sexplib0
S .
FLG -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs
```

**Comment by voodoos** [comment]
It is a Merlin issue for OCaml >= 4.08 due to the new alert system.
I have a patch for it for OCaml >= 4.08 but we need to ensure compatibility with older versions.

Once this is done it will also require an update of `ocaml-lsp-server` for the change to be visible in vscode using Ocaml Platform. (because ocamllsp vendors Merlin)

**Comment by yminsky** [comment]
I guess the Merlin patch hasn't been released yet? Because I see the same issue when I use Merlin directly from emacs, with just the regular installed version.  That's why I thought this was a dune-level issue.

**Comment by voodoos** [comment]
> I guess the Merlin patch hasn't been released yet? Because I see the same issue when I use Merlin directly from emacs, with just the regular installed version. That's why I thought this was a dune-level issue.

No it has not been released yet, it will probably happen next week.

**Comment by voodoos** [comment]
I close this issue because the Merlin fix has now been released. However `ocaml-lsp-server` vendors Merlin and has not been updated yet. Thus the fix is not yet available for users of the vscode `OCaml Platform` extension.
