### ISSUE TITLE
Support for linters

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#351]
This will need a way to specify the linter (`lint` already exists) and a way to run these linters. Likely by building `@lint` target. This will be useful to add support for `[@@deriving_inline]` users.

cc @trefis 

@diml I assume this comment is no longer relevant then:

https://github.com/rgrinberg/jbuilder/blob/jbuilder-exec-b/src/jbuild.ml#L457-L459

**Comment by diml** [comment]
@rgrinberg yh, basically the lint field is the same as the preprocess field. When you run the ppx driver, you just need to pass `-null`.

**Comment by rgrinberg** [comment]
OK this is implemented. @diml is there anything left to do here to make it work better with promotion?

**Comment by diml** [comment]
Nope, this should work well now
