### ISSUE TITLE
jbuilder.transition against dune.2.5.1

### ISSUE THREAD

**Issue by MdeLv** [ocaml/dune#3514]
When doing opam update && opam upgrade (ocaml.4.10.0 and opam.2.0.7), I get this message (since today):
```
The following packages are not being upgraded because the new versions conflict with 
other installed packages:                                                                                           
  - jbuilder.transition                                                                             
    ∗ dune.2.5.1 is installed and conflicts with jbuilder = transition                              
However, you may "opam upgrade" these packages explicitly, which will ask permission 
to downgrade or uninstall the conflicting packages.                                                                 
```
As jbuilder and dune are related, have you a suggestion to fix that?
When (in which conditions) is jbuilder supposed to totally disappear from our radar?
Thanks.

**Comment by jeremiedimino** [comment]
What version of `jbuilder` do you have installed?

The situation is as follow:

- Dune 1.x installs a `jbuilder` binary and can only be co-installed with `jbuilder.transition` which is a dummy package that depends on Dune < 2.0
-  Dune 2.x doesn't install a `jbuilder` binary and cab be co-installed with any of the proper versions of Jbuilder, i.e. any that is not `transition`

I suggest to try the following: `opam remove jbuilder`. If it only removes `jbuilder`, then nothing on your system is using `jbuilder` and removing it entirely is the right way to go. If it tries to remove some other stuff, then you still have packages in your opam installation that use `jbuilder`. Jbuilder has been deprecated for quite a while now, so the way forward is to port the last packages still using it to dune, which can be done easily with `dune upgrade`.

**Comment by MdeLv** [comment]
> What version of `jbuilder` do you have installed?

jbuilder.1.0+beta20.2 (ocaml.4.10.0)
dune.2.5.1
I didn't install jbuilder. Some packages have installed it for their needs.

There are still a few packages depending on jbuilder on the considered machine:
```
$ opam remove jbuilder
The following actions will be performed:
  ⊘ remove irmin-unix    2.1.0        [uses irmin-watcher]
  ⊘ remove ocsigen-start 2.18.0       [uses safepass]
  ⊘ remove irmin-watcher 0.3.0        [uses jbuilder]
  ⊘ remove safepass      3.0          [uses jbuilder]
  ⊘ remove jbuilder      1.0+beta20.2
```
It's surprising that irmin-unix still depends on jbuilder.

> the way forward is to port the last packages still using it to dune, which can be done easily with `dune upgrade`

I understand that it's package maintainer's role&reponsibility to do `dune upgrade`? (and not an action that a user shoud do).
Is it correct?

As packages' maintainers may forget to update the opam file or to get rid of some old dependencies,    do you think that opam-repository could be the best checkpoint for that?

**Comment by jeremiedimino** [comment]
Actually, recent versions of `irmin-unix` and `irmin-watcher` use Dune to build. It is `safepass` that doesn't have a version that uses Dune. @darioteixeira, do you think you could switch `safepass` to Dune? It is better if all packages switch to Dune as Jbuilder is deprecated and is no longer receiving support.

> I understand that it's package maintainer's role&reponsibility to do dune upgrade? (and not an action that a user shoud do).
Is it correct?

Yes, that's correct.

> As packages' maintainers may forget to update the opam file or to get rid of some old dependencies, do you think that opam-repository could be the best checkpoint for that?

I suppose, yes.

**Comment by MdeLv** [comment]
Thanks.

**Comment by rgrinberg** [comment]
This doesn't seem like a bug. Feel free to ask more questions however.
