### ISSUE TITLE
Odd dune__exe__ prefix in error message

### ISSUE THREAD

**Issue by yminsky** [ocaml/dune#3518]
## Expected Behavior

When building a simple example from RWO with a signature mismatch on a compilation unit, the error message comes back with a surprising dune__exe__ prefix.

Here's the error message, scraped from RWO:

```
$ dune build freq.exe
File "counter.ml", line 1:
Error: The implementation counter.ml
       does not match the interface .freq.eobjs/byte/dune__exe__Counter.cmi:
       Values do not match:
         val touch :
           ('a, int, 'b) Base.Map.t -> 'a -> ('a, int, 'b) Base.Map.t
       is not included in
         val touch : string -> t -> t
       File "counter.mli", line 16, characters 0-28: Expected declaration
       File "counter.ml", line 9, characters 4-9: Actual declaration
[1]
```

This showed up when bumping the version of Dune in the dune-project file from 1.0 to 2.4.  Here's the PR where it happened: https://github.com/realworldocaml/book/pull/3321

If you look in the comments, you'll see where counter.cmi gets replaced with dune__exe__Counter.cmi.

## Reproduction

This is easy to reproduce by grabbing the files [here](https://github.com/realworldocaml/book/tree/master/book/files-modules-and-programs/examples/erroneous/freq-with-sig-mismatch) and running `dune build`.

## Specifications

- Version of `dune`: 2.5.1
- Version of `ocaml`: 4.10
- Operating system: Fedora 32

**Comment by nojb** [comment]
This is due to `dune` building "wrapped executables" by default since 2.0. You can disable this by setting `(wrapped_executables false)` in your `dune-project`, see https://dune.readthedocs.io/en/stable/dune-files.html#wrapped-executables.

**Comment by yminsky** [comment]
I don't quite understand why this is necessary, but I don't want to make Real World OCaml use non-standard features.  Given that it doesn't sound like it's a mistake, so I think I'll just close this issue.

**Comment by rgrinberg** [comment]
@yminsky if your executable transitively depended on some library `counter` that introduced a top-level module `Counter`, then you wouldn't be able to link your executable without this name mangling. It's a bit unfortunate that it leaks to the user, but it seems like the lesser evil which is why we enabled it by default in 2.0.

**Comment by jeremiedimino** [comment]
FTR, we do the same in Jenga.

**Comment by yminsky** [comment]
Hah! Well, that doesn't give me much of a position to complain...
