### ISSUE TITLE
`dune build -p ''`  crashes

### ISSUE THREAD

**Issue by camlspotter** [ocaml/dune#3530]
## Expected Behavior

`dune build -p ''` should properly report the problem, instead of crashing due to an internal error.

## Actual Behavior and Reproduction

At any project directory

```
$ dune build -p ''
Internal error, please report upstream including the contents of _build/log.
Description:
  ("Invalid Package.Name.t", { s = "" })
Raised at file "src/stdune/code_error.ml", line 9, characters 30-62
Called from file "list.ml", line 103, characters 22-25
Called from file "src/stdune/list.ml" (inlined), line 5, characters 19-33
...
```

## Specifications

- Version of `dune` (output of `dune --version`): 2.5.1
- Version of `ocaml` (output of `ocamlc --version`): 4.09.1
- Operating system (distribution and version):  OS X but should not be specific

## Additional note

This `-p ''` was triggered by OPAM, when a package not in the current repository scope is to be recompiled.  It seems a bug which fails to get the proper package name for `dune build -p xxx`.

**Comment by jeremiedimino** [comment]
Indeed. Are you happy to write a fix for this?
