### ISSUE TITLE
Need to manually add -lstdc++ for C++ compilation

### ISSUE THREAD

**Issue by toots** [ocaml/dune#3533]
I just finished converting `ocaml-taglib` to `dune` and I was surprised to discover that I have to manually add `-lstdc++` to the linker flags here: https://github.com/savonet/ocaml-taglib/blob/master/src/config/discover.ml#L31 otherwise, the flag isn't registered with the library which prevents linking binaries using it.

Is that intended? Shouldn't `dune` be doing some of the lifting since it is aware that it's dealing with C++ linked code?

**Comment by jeremiedimino** [comment]
That's indeed a known issue: https://github.com/ocaml/dune/issues/3528

**Comment by toots** [comment]
Oh good, sorry I didn't check. It would be nice if that could be documented somewhere, specially the `-x c++` parameter, which I've had to use in the discovery binary as well. Thanks for all the work on `dune`, tho, it's a great tool.

**Comment by jeremiedimino** [comment]
No problem, we should schedule this work in a few weeks. So I expect the fix to be part of 2.7 or 2.8, so hopefully not too long to wait.
