### ISSUE TITLE
Ability to mark rules as non-reproducible.

### ISSUE THREAD

**Issue by Zimmi48** [ocaml/dune#3538]
## Desired Behavior

I have a dune `(rule ...)` which runs a command to download a file from the internet and promotes it in my repository. This file is known to evolve: to be specific, it is the GitHub GraphQL schema, it is a dependency of my build, through [`graphql_ppx`](https://opam.ocaml.org/packages/graphql_ppx/), and I appreciate that building my project will automatically update to the latest version of the schema (and thus check compatibility with it), while if running with option `--ignore-promoted-rules` or `-p` will allow users to build the project without requiring an HTTP call.

Now that I'm also using Dune cache, I discover that the two do not play well together because Dune assumes that build rules are reproducible (and has even an option to check for this).

I'd love an option `non-reproducible` or `(cache disabled)` that I could pass to `rule` to automatically disable the cache for this rule specifically, that I know is not reproducible. Ideally, Dune would then check the checksum of the target of the rule, and if it hasn't changed, it would use the cache to skip whatever can be.

## Example

```
(rule
 (targets random)
 (action (with-stdout-to random (bash "echo $(($RANDOM%2))")))
 (cache disabled))
(rule
 (deps random)
 (targets random_bis)
 (action
  (with-stdout-to random_bis
   (progn
    (cat random)
    (cat random)))))
```

The output of the first rule is never cached. The output of the second rule is cached, thus if the checksum of the output of the first rule (`random`) has not changed, then the second rule is not run again.

**Comment by ejgallego** [comment]
@Zimmi48 , does `(deps universe)` help with this case?

**Comment by ejgallego** [comment]
See https://dune.readthedocs.io/en/stable/concepts.html#dependency-specification

**Comment by Zimmi48** [comment]
Thanks. It is actually `(deps (universe))`. It seems to be exactly what I was looking for. IMHO, it should be mentioned in https://dune.readthedocs.io/en/stable/caching.html.

**Comment by ejgallego** [comment]
> IMHO, it should be mentioned in https://dune.readthedocs.io/en/stable/caching.html.

I'm not very familiar with caching but if you think it makes sense it would be great to submit a PR to improve the docs then.

**Comment by ejgallego** [comment]
Indeed, regarding documentation there has been some discussion on how discoverable some features are; a bit in the sense of the typical trade-off between reference vs guides. For example the Coq documentation is now sparse, so we may try to reintroduce a Coq section that presents all the features available to Coq users.
