### ISSUE TITLE
make dev-switch fails

### ISSUE THREAD

**Issue by gares** [ocaml/dune#3545]
I'm trying to work on #3486 and following `HACKING.md` I tried to set up a development switch.
```
gares@ollypat:~/work-area/dune$ make dev-switch
opam switch create -y . --deps-only --with-test
[ERROR] Could not resolve set of base packages:
        Your request can't be satisfied:
          - No available version of ocaml-base-compiler satisfies the
        constraints


Switch initialisation failed: clean up? ('n' will leave the switch partially
installed) [Y/n] y
Makefile:47: recipe for target 'dev-switch' failed
make: *** [dev-switch] Error 20
gares@ollypat:~/work-area/dune$ opam --version
2.0.7
```

**Comment by jeremiedimino** [comment]
hmm, it seems to work on my machine. Not really sure what's happening. But TBH I develop on Dune using my global opam installation and it works just fine. You just need a recent enough version of the compiler and if you want to run the test suite you'll need to install a bunch of packages: `ppx_expect`, `utop`, `odoc` and maybe a couple of other ones

**Comment by gares** [comment]
This is what I've ended up doing, and it works for me as well.

**Comment by avsm** [comment]
Need to specify a compiler for that to be reliable, due to the more complex formula that dune has (with a secondary compiler).  Try

```
opam switch create . 4.10.0 --deps-only --with-test
```

Should fix that in the `dev-switch` target too, I think.

**Comment by rgrinberg** [comment]
I fixed the dev-switch target with Anil's advice.
