### ISSUE TITLE
Coq extraction sometimes leaves extracted modules in source tree

### ISSUE THREAD

**Issue by anton-trunov** [ocaml/dune#3550]
## Expected Behavior

Extracted OCaml modules and their signatures stay in `_build` directory outside of the source tree.

## Actual Behavior

Dune leaves extracted OCaml modules in the source tree alongside with the corresponding Coq files. For the example below this is what I get in the source tree (untracked by git):
```
	Ascii.ml
	Ascii.mli
	Datatypes.ml
	Datatypes.mli
	String.ml
	String.mli
	Top.ml
	Top.mli
	stlc.ml
	stlc.mli
```

And this causes compilation errors the next time I run `dune build`:

```shell
$ dune build
Error: Multiple rules generated for _build/default/src/stlc/Datatypes.ml:
- file present in source tree
- <internal location>
Hint: rm -f src/stlc/Datatypes.ml
```

## Reproduction

Looks like it's non-deterministic, because I cannot always reproduce it, but
it was also reproduced by another person using the same Dune version.

I'd provide a minimal example if I could always reproduce it, but here are my files that caused the issue.

The Dune file:
```
(coq.extraction
 (prelude stlc)
 (extracted_modules Datatypes Stlc))
```
 
The Coq file (`stlc.v`):
```
From Coq Require Import String.

Definition var := string.

Inductive ty : Type :=
| Nat : ty
| Arr : ty -> ty -> ty.

Inductive term : Type :=
| Num : nat -> term
| Var : var -> term
| Abs : var -> ty -> term -> term
| App : term -> term -> term.

From Coq Require Extraction.

Extract Inductive string => "string"
[
(* EmptyString *)
"(* If this appears, you're using String internals. Please don't *)
  """"
"
(* String *)
"(* If this appears, you're using String internals. Please don't *)
  (fun (c, s) -> String.make 1 c ^ s)
"
]
"(* If this appears, you're using String internals. Please don't *)
 (fun f0 f1 s ->
    let l = String.length s in
    if l = 0 then f0 else f1 (String.get s 0) (String.sub s 1 (l-1)))
".

Extraction Language OCaml.
Separate Extraction term.
```

## Specifications

- Version of `dune` (output of `dune --version`): 2.5.1-223-g9b88e9466 and 2.5.1
- Version of `ocaml` (output of `ocamlc --version`): 4.09.1 and 4.08.0
- Operating system (distribution and version): macOS 10.15.4 "Catalina"

## Additional information 

My Coq version:
```shell
coqc --version
The Coq Proof Assistant, version 8.11.2 (June 2020)
compiled on Jun 9 2020 11:54:54 with OCaml 4.09.1
```

Also was reproduced with Coq 8.10.2

**Comment by ejgallego** [comment]
That may be due to running Proof General on the extraction prelude?

**Comment by anton-trunov** [comment]
@ejgallego I almost sure that I cleaned up everything before building, but you made me doubt that. Ok, let me close this issue for now. I'll reopen if the problem reappears. Thanks for you quick response.

**Comment by ejgallego** [comment]
Feel free to keep this issue open / reopen. Indeed if you can identify the problem is proof general, there is already an issue there.

Indeed how to integrate stuff like this with PG is kinda trikcy?

**Comment by anton-trunov** [comment]
I'm wondering if configuring PG to use Dune's `_build` directory would be a good enough first approximation to the solution of this problem. E.g. introducing a new Elisp variable (and some kind of setting for CoqIDE/VSCoq). Or even moving this to the level of `_CoqProject` file. I guess this would be better discussed elsewhere.

**Comment by ejgallego** [comment]
Main issue is https://github.com/ProofGeneral/PG/issues/477

Usually there is no need to do a lot of special stuff, but indeed if you run extraction commands from PG that becomes a bit complex, as I don't think you want to set `current-dir` to `_build` in general when editing a file.

Likely this will have to be solved with a better API for objects in the Coq side, so the DM has some control over it.

**Comment by anton-trunov** [comment]
Ah, I see, makes sense. Thanks for the link.
