### ISSUE TITLE
How to copy generated files to source folder

### ISSUE THREAD

**Issue by robz** [ocaml/dune#3552]
I have a program `foo.re` that I use to generate a file `bar`. I'd like to keep `bar` checked in the folder where `foo.re` is, or an adjacent folder if that's not possible. When I build, I'd like to regenerate `bar` if `foo.re` has changed. 

Suppose `foo.re` looks like this:

```
print_endline("Hello");
```

So I want the stdout of `foo.re` to be dumped into `bar`. I tried this:

```
(executable (name foo))
(rule (with-stdout-to bar (run ./foo.exe)))
```

But `bar` is generated into the _build/default/ folder, not the folder where foo.re is in. I tried making a dummy rule to copy it ("bar-placeholder"):

```
(rule
  (deps bar)
  (targets bar-placeholder)
  (action
    (bash "
      cp ./bar ../../bar &&
      echo done > bar-placeholder
    ")))
```

Running "dune build bar-placeholder" seems to work the first time. But I receive this error the second time:

```
bash-3.2$ dune build bar-placeholder
File "dune", line 3, characters 0-45:
3 | (rule
4 |   (with-stdout-to bar (run ./foo.exe)))
Warning: File bar is both generated by a rule and present in the source tree.
As a result, the rule is currently ignored, however this will become an error in the future.
To keep the current behavior and get rid of this warning, add a field (fallback) to the rule.
```

It seems I can solve this by making a special folder `bar-dir` and stick `bar` into it:

```
(rule
  (deps bar)
  (targets bar-placeholder)
  (action
    (bash "
      mkdir -p ../../bar-dir
      cp ./bar ../../bar-dir/ &&
      echo done > bar-placeholder
    ")))
```

This approach feels hacky, since I have to rely on the paths of the package. Also creating this this dummy file bar-placeholder and copying it as side effect feels wrong. Reading the documentation, maybe I should be using the install stanza. "copying freshly built artifacts from the workspace to the system" is exactly what I want to do. 

I tried replacing bar-placeholder rule with an install stanza:

```
(install
  (files bar)
  (section share)
  (package mypackage))
```

After `touch mypackage.install` and `dune build @install`, running `dune install` seems to copy `bar` into my home directory:

```
bash-3.2$ dune install
Done: 0/0 (jobs: 1)Installing /Users/username/.opam/4.06.1/lib/mypackage/META
Installing /Users/username/.opam/4.06.1/lib/mypackage/opam
Installing /Users/username/.opam/4.06.1/share/mypackage/bar
```

The docs (https://dune.readthedocs.io/en/stable/dune-files.html?highlight=install#install) have a `<prefix>` thing in front of all the directories that it lists. Is there some way to change `<prefix>` to the directory where the original source code for `bar.re` is in?

Or is there another way to do what I'm trying to do here?

Thanks!!

**Comment by nojb** [comment]
Copying files built by dune to the source directory is the objective of the "promotion" machinery. For example, you could do:
```
(rule
 (mode promote)
 (action (with-stdout-to bar (run ./foo.exe))))
```
See https://dune.readthedocs.io/en/stable/dune-files.html#modes for more.

**Comment by robz** [comment]
Awesome, that's works great. Thanks!

**Comment by nojb** [comment]
No problem. Cheers!
