### ISSUE TITLE
Be able to update META file even if we use virtual_modules

### ISSUE THREAD

**Issue by dinosaure** [ocaml/dune#3557]
Currently, [`digestif`](https://github.com/mirage/digestif) and [`checkseum`](https://github.com/mirage/checkseum) use some tricks to be able to _patch_ the produced `META` file to be compatible with MirageOS 3 where `dune` disallows `META.package.template` when we use `virtual_modules`.

It will be very pleasant to unlock the ability to update the `META` file and still continue to use `virtual_modules`.

**Comment by avsm** [comment]
Could you link to the tricks please? Also see https://github.com/mirage/checkseum/issues/46 for a regression caused by this workaround

**Comment by dinosaure** [comment]
So currently, such a script:
https://github.com/mirage/checkseum/blob/master/install/install.ml
is needed to append some fields into the `META` file. These fields are needed by MirageOS 3 to be able to link with the right C library according the requested target by the user.

OPAM executes it when it wants to build `checkseum`:
https://github.com/mirage/checkseum/blob/master/checkseum.opam#L21

And a test exists to check the existence of _runes_  needed by MirageOS:
https://github.com/mirage/checkseum/blob/master/test/test_runes.ml

So when we "test" (eg. `opam install -t checkseum`) the package, we simulate an installation and we check if we can get static C libraries as MirageOS does.

An other example to respect the layout required by MirageOS 3 is `bigstringaf`:
https://github.com/inhabitedtype/bigstringaf/blob/master/META.bigstringaf.template
which is able to modify the `META` file (because it does not use `virtual_modules`). It will help us if `digestif` and `checkseum` can have the same layout than `bigstringaf`/`mirage-crypto`/etc.

**Comment by jeremiedimino** [comment]
/cc @rgrinberg, do you remember why we disable META templates for virtual libraries?

IIRC, it's because the `META` file produced for libraries with virtual modules simply don't work. i.e. such libraries cannot be used without Dune at the moment.

**Comment by rgrinberg** [comment]
It’s because virtual libraries rely on dune-package file information to be used. For example, we use the dune-package file to specify which module is virtual. This is necessary when we implement a virtual library that is installed.

**Comment by jeremiedimino** [comment]
Ah yes, I remember now. When there is a custom META file, we just write `Use_meta` in the `dune-package` file, but obviously that wouldn't work for virtual libraries.

In any case, given that the `META` files for virtual libraries currently don't work, @dinosaure would adding support `META` template for virtual libraries be of any use right now?

**Comment by dinosaure** [comment]
> In any case, given that the META files for virtual libraries currently don't work, @dinosaure would adding support META template for virtual libraries be of any use right now?

Yes, as I said, `digestif` and `checkseum` come with some extra and non-conventional operations which are not very portable. It should help me a lot if I can have the `META.template` with virtual modules :+1: .

**Comment by jeremiedimino** [comment]
The thing I don't understand is: if `digestif` and `checkseum` are using virtual libraries, who are the consumers of their `META` files? I'm assuming that one currently cannot link and executable using `digestif` with `ocamlfind` because they use virtual libraries.

**Comment by dinosaure** [comment]
> if digestif and checkseum are using virtual libraries, who are the consumers of their META files?

It's MirageOS with a bit dirty hack with `ocamlfind`, you can see the invocation of `ocamlfind` by tests [here](https://github.com/mirage/checkseum/blob/master/test/test_runes.ml#L132) and this is what MirageOS 3 currently does.

**Comment by jeremiedimino** [comment]
I see. Technically I don't see a problem with taking into account the `META` template. it just means that if people do complex transformations of the `META` file, clients using Dune to build won't such adjustments as Dune will ignore the `META` file.

@rgrinberg WDYT?

**Comment by rgrinberg** [comment]
There are some cases where users users write META files and expect dune to read them. The most common use case is when they create public library aliases, and refer to them in dune files. This is mostly obsolete by our deprecated library stanza, but I think that altering this would still be a breaking change. 

To make this a non breaking change, we need a way to tell dune to ignore the generated META file.

**Comment by jeremiedimino** [comment]
Alternatively, what about we add a field `(additional-META-fields ..)` to the library stanza?

**Comment by rgrinberg** [comment]
That seems like a lesser evil to me. Let me have a closer look at what digestif is doing however. I'd like to see if there's a less adhoc solution to this.

**Comment by rgrinberg** [comment]
Don't think anyone cares much anymore and I doubt there's much interest in META files remaining.
