### ISSUE TITLE
Problem recompiling/cleaning project

### ISSUE THREAD

**Issue by thepalbi** [ocaml/dune#3563]
Hi! I'm working with https://github.com/facebook/infer, following a lab of them. I found some issues when trying to re-compile/clean the project.

**NOTE: ** This is my first time working with OCaml, so I might be missing something on how to use the toolchain.

## Expected Behavior

Project recompiles correctly

## Actual Behavior

```bash
➜  infer git:(master) ✗ make -j 4
[09:57:38][77291] Generating source dependencies...
[      1s][77291] SUCCESS Generating source dependencies
[09:57:39][77369] Building native(opt) Infer...
[*ERROR**][77369] *** ERROR 'Building native(opt) Infer'
[*ERROR**][77369] *** command: ' /Library/Developer/CommandLineTools/usr/bin/make INTERACTIVE=1 -C /Users/thepalbi/infer/infer/src infer'
[*ERROR**][77369] *** CWD: '/Users/thepalbi/infer'
[*ERROR**][77369] *** stdout:
[*ERROR**][77369] *** stderr:
[*ERROR**][77369] Entering directory '/Users/thepalbi/infer/infer'
[*ERROR**][77369] Error: Error: unlink: _build/default/.dune/.dune-keep: Permission denied
[*ERROR**][77369] make[1]: *** [/Users/thepalbi/infer/infer/bin/infer.exe] Error 1
make: *** [src_build] Error 2
```

It's also possible to reproduce this when running `make clean`:

```bash
[09:59:09][77567] Cleaning infer OCaml build...
[*ERROR**][77567] *** ERROR 'Cleaning infer OCaml build'
[*ERROR**][77567] *** command: ' /Library/Developer/CommandLineTools/usr/bin/make INTERACTIVE=1 -C /Users/thepalbi/infer/infer/src clean'
[*ERROR**][77567] *** CWD: '/Users/thepalbi/infer'
[*ERROR**][77567] *** stdout:
[*ERROR**][77567] /Library/Developer/CommandLineTools/usr/bin/make INTERACTIVE=1 -C deadcode clean
[*ERROR**][77567] rm -f .depend *.ml *.mli all_ml_files all_mli_files all_ml_files_copied \
[*ERROR**][77567] 	  all_mli_files_copied dune
[*ERROR**][77567] rm -f
[*ERROR**][77567] rm -f toplevel.mlpack
[*ERROR**][77567] rm -f /Users/thepalbi/infer/infer/etc/clang_ast.dict
[*ERROR**][77567] rm -f dune.common ../dune-workspace base/Version.ml
[*ERROR**][77567] rm -f dune al/dune clang/dune integration/dune java/dune opensource/dune unit/dune
[*ERROR**][77567] rm -f base/Version.ml.tmp.* dune.tmp.* dune-workspace.tmp.*
[*ERROR**][77567] rm -f /Users/thepalbi/infer/infer/bin/infer /Users/thepalbi/infer/infer/bin/infer-analyze /Users/thepalbi/infer/infer/bin/infer-capture /Users/thepalbi/infer/infer/bin/infer-compile /Users/thepalbi/infer/infer/bin/infer-explore /Users/thepalbi/infer/infer/bin/infer-help /Users/thepalbi/infer/infer/bin/infer-report /Users/thepalbi/infer/infer/bin/infer-reportdiff /Users/thepalbi/infer/infer/bin/infer-run /Users/thepalbi/infer/infer/bin/InferCreateTraceViewLinks
[*ERROR**][77567] rm -f /Users/thepalbi/infer/infer/bin/llvm_sil
[*ERROR**][77567] rm -f atd/*_{j,t,v}.ml{,i} atd/clang_ast_*
[*ERROR**][77567] rm -f mod_dep.dot
[*ERROR**][77567] rm -f mod_dep.pdf
[*ERROR**][77567] cd .. && dune clean
[*ERROR**][77567] *** stderr:
[*ERROR**][77567] Error: Error: unlink: _build/default/.dune/.dune-keep: Permission denied
[*ERROR**][77567] make[1]: *** [clean] Error 1
make: *** [ocaml_clean] Error 2
```

## Reproduction

- PR with a reproducing test: 

1- Compile the project. Infer's team made a Makefile, but it ends up using Dune.
2- Try some things.
3- Make some changes.
4- Run `make` again

## Specifications

- Version of `dune` (output of `dune --version`): 2.5.1
- Version of `ocaml` (output of `ocamlc --version`): 4.09.1
- Operating system (distribution and version): macOS 10.15.4

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag):

**Comment by jeremiedimino** [comment]
Could you try with dune 2.6.0?

I remember that we had issues related to the shared cache and files put in read-only, so maybe this issue has already been fixed.

**Comment by rgrinberg** [comment]
Does building infer enabled the cache? That seems unlikely.

Maybe @jberdine  knows

**Comment by jberdine** [comment]
Some people working on infer use the cache, but it is enabled manually on each developer's machine via `~/.config/dune/config` (correct me if I'm wrong @artempyanykh).

Just to check, was there any chance that part of the build was done under `sudo`?

I don't know what else to guess without a more concrete repro. It is not an issue that I'm aware of anyone hitting before though.

**Comment by rgrinberg** [comment]
Please re-open if you're still running into this issue.
