### ISSUE TITLE
dune -w (--watch) observes ignored directories and fails with "upper limit on inotify watches reached "

### ISSUE THREAD

**Issue by vog** [ocaml/dune#3579]
## Expected Behavior

"dune -w" should only watch files and directories actually relevant for dune. For example, when a "(dirs src)" stanza is in place, "dune -w" should run inotifywait like this:

    /usr/bin/inotifywait -r src --exclude /_build|/_opam|/_esy|/\..+|~$|/#[^#]*#$|4913 ...

## Actual Behavior

"dune -w" always executes "inotifywait" recursively for all of the current directory, and merely excludes some standard build directories:

    /usr/bin/inotifywait -r . --exclude /_build|/_opam|/_esy|/\..+|~$|/#[^#]*#$|4913 ...

Hence, if there are too many files in the sibling directories, dune (more precisely, inotifywait) fails with:

    Success, waiting for filesystem changes...Failed to watch .; upper limit on inotify watches reached!

Moreover, `dune -w` now hangs, rather than aborting because of the failed `inotifywait` call.

## Reproduction

1. Create a project whose dune file contains `(dirs src)`
1. Put in some code in `src/`, or not (doesn't really matter).
1. Create directory `ignored/` containing tons of empty files (~9000 should be sufficient, on Linux the actual limit on your system can be checked via `sysctl fs.inotify.max_user_watches`.)
1. run `dune -w`

## Specifications

- Version of `dune` (output of `dune --version`): 1.11.4
- Version of `ocaml` (output of `ocamlc --version`): 4.08.1
- Operating system (distribution and version): Debian 10

## Additional information 

Since the error message is generated by `inotifywait`, the output of `dune --verbose` contains no information about this issue.

**Comment by vog** [comment]
One more question:

I wonder why setting up `inotifywait` for each individual file is really needed. Wouldn't it be sufficient to just watch all directories and subdirectories, as those change whenever files change as well?

For example:

    find src lib -type d -print0 | xargs -0 -- inotifywait -e modify,attrib,move,create,delete

or, assuming a `(dirs src1 src2)` stanza:

    find src1 src2 -type d -print0 | xargs -0 -- inotifywait -e modify,attrib,move,create,delete

**Comment by rgrinberg** [comment]
Could you try using fswatch instead of inotifywait? Does it suffer from this problem as well?

> I wonder why setting up inotifywait for each individual file is really needed. Wouldn't it be sufficient to just watch all directories and subdirectories, as those change whenever files change as well?

Sounds like that's worth trying. We could dump the list of directories dune sees and then feed them to `inotifywait`. @jeremiedimino wdyt?

> For example:

Launching this many extra processes doesn't seem good.

**Comment by jeremiedimino** [comment]
How do we updated this list dynamically though? For instance if the user edit a `dune` file and changes the list of ignored directories

**Comment by rgrinberg** [comment]
> How do we updated this list dynamically though? For instance if the user edit a dune file and changes the list of ignored directories

At that point we reload `File_tree` anyways. We can simply regenerate this file again.

**Comment by jeremiedimino** [comment]
So concretely, how would that work? Would it be something like: at the start of each build:

- kill the current inotifywait process
- gather the list of ignored directories
- start a new inotifywait process with the new list

This might be pretty costly. Ideally, what we want is to be able to dynamically add and remove directories to watch.

**Comment by rgrinberg** [comment]
> So concretely, how would that work? Would it be something like: at the start of each build:

That's the idea, except that

> gather the list of ignored directories

This step is essentially free as we already walk over the entire file tree to find the dune files.

> This might be pretty costly. Ideally, what we want is to be able to dynamically add and remove directories to watch.

Indeed, but neither fswatch or inotifywait are powerful enough for this. Perhaps we should just bite the bullet and wrap the inotify API ourselves.

**Comment by vog** [comment]
I'd propose to restart `inotifywait` only if the list of directories actually changed.

More precisely, I believe the list of source directories needs to be recursively expanded with all subdirectories (e.g. "src/ src2/" -> "src/ src/a/ src/b/ src/b/x/ src2/"), and that list should be compared before/after.

**Comment by jeremiedimino** [comment]
> Indeed, but neither fswatch or inotifywait are powerful enough for this. Perhaps we should just bite the bullet and wrap the inotify API ourselves.

The problem is that inotify is Linux only. If we go this way, we are going to have to bind all sorts of OS-specific APIs. A more promising way might be to rely on a portable service such as watchman.

> I'd propose to restart inotifywait only if the list of directories actually changed.

That would help yes. It is still not perfect though. For instance, if a large subtree of the workspace is in "data only mode", we might only want to watch the part of this subtree that are used for the build.

**Comment by rgrinberg** [comment]
We no longer watch ignored directories
