### ISSUE TITLE
[ocaml] Restore compatibility with OCaml 4.12

### ISSUE THREAD

**Issue by ejgallego** [ocaml/dune#3583]
OCaml 4.12 has introduced a new field in the `Gc.stats` record,
`forced_major_collections`. This makes compilation of Dune fail due to
`src/catapult/catapult.ml:fake_gc_stat`

There could be several solutions to this, such as calling
`Gc.quick_stats` and then overriding the set of safe fields, but OMMV.

cc: #2298

**Comment by emillon** [comment]
They're just used in the expect tests for catapult. Since we don't emit a counter event for this field, `Gc.quick_stat` + overridding should work.
