### ISSUE TITLE
New name: Dune

### ISSUE THREAD

**Issue by diml** [ocaml/dune#360]
It appears that for legal reasons we do need to change the jbuilder name. Feel to suggest new names here.

**Comment by cfcs** [comment]
It was originally a confusing for me that the `jbuilder` tool did a lot more than build things (including running tests, cleaning up, installing stuff, uninstalling stuff). Kind of like `make`. I also still keep typing `jbuild` instead of `jbuilder`.
The `j-` prefix is contaminated by both JavaScript and Java, so if you are bent on including your company name in the name of the tool, maybe something like `janemake`?

**Comment by reynir** [comment]
I propose `jbyg`. Byg is imperative of 'bygge' ('to build') in Danish. It also means barley, and barley is used in beer brewing, and I like beer. Finally, it's *super* short and doesn't seem to conflict with anything.

**Comment by dra27** [comment]
As it happens, the J in jbuilder does not come from the J in Jane Street. The only potential reason for wishing to keep a name beginning with J is that we could logically keep having files called `jbuild`

**Comment by xclerc** [comment]
I don't speak Swahili, but https://translate.google.com can help
finding variations around "jenga" (build in Swahili), e.g.:
  - building (noun) -> jengo;
  - building (verb) -> kujenga;
  - builder -> mjenzi.

**Comment by lpw25** [comment]
As previously suggested, I think `obuilder` will involve the least amount of confusion/churn.

**Comment by cfcs** [comment]
Oh, shit, naming things - "the hardest problem in computer science."
I'll be out of this thread and leave you to it. :-)

@lpw25 you don't think `obuilder` will be confused with `obuild`, `omake` or `ocamlbuild`? To me they all seem very similar (and the latter three are all existing software distributed through `opam`).

@dra27 just out of curiosity, what *does* the `J` in `jbuilder` stand for?

**Comment by ivg** [comment]
My five cents:

* `caravan` for the camel theme, and it also plays nice with the commands, e.g., `caravan build`
* `oproject` for the OCaml Project, since `jbuilder` is about the project managing
* `oat` as a fancy acronym for OCaml Automation Tool.

**Comment by diml** [comment]
@cfcs the `J` comes from  [jenga](https://github.com/janestreet/jenga), which is another build system developed at Jane Street which inspired jbuilder. Jbuilder is now a community project and will soon move out of the janestreet github organization, so there is no reason to keep a link to Jane Street in the name.

**Comment by bluddy** [comment]
Presumably, if we change the name, we also have to change the name of the configuration file from jbuild?

**Comment by jnavila** [comment]
Retaining the "j" would avoid some questions about migrating all the "jbuild" names that are already there.

My proposition is "jamal" which seems to be the arab word for camel.

**Comment by diml** [comment]
No constraint on keeping the `j`. Once we have a new name, we'll decide if we need to rename configuration or not. If we do, there'll be a migration plan and both old and new names will be supported for a while.

**Comment by bluddy** [comment]
As mentioned above, I've also had an issue with writing jbuild when I meant jbuilder. It's confusing to have the 2 IMO. I think a better approach is similar to what Rust does: the tool is cargo, and the file is cargo.toml.

I also like the idea of continuing with desert-related names. Caravan is good but a bit long. How about `nomad`? The idea being that the nomad takes everything needed along, and rebuilds it where needed. We would then have something like a `nomad.sexp` or `nomad.conf` file as our configuration file name.

**Comment by mars0i** [comment]
A build tool helps with digesting code and turning it into something productive, so I started thinking about camel digestion.  I don't know anything about that topic, but did some superficial web investigation.  Camels are "pseudoruminants" with three-chambered stomachs, differing from ruminants which have four-chambered stomachs.  It's not clear that "pseudoruminate" is a word, although there seems to be a term "pseudorumination".   Both of these are too long, and "pseudorumination" seems to refer to a rabbit behavior that sounds kind of disgusting.   

However, camels do chew their cud, i.e. "ruminate", as part of their digestive process.  "Ruminate" more commonly refers to thinking deeply over a period of time.  

So I suggest "ruminate" as a possibility.

("Rumination" is apparently also a term for a concept associated with depression in psychology.   However, I'd never heard of that until I searched on "ruminate".  The "thinking deeply" sense seems pretty common.)

On the other hand, it could be nice to have a name that's unusual enough that web searches always bring it to the top.

**Comment by Chris00** [comment]
For desert things, how about [mesa](https://en.wikipedia.org/wiki/Mesa)?
![mesa-landform-drawing-wallpaper-1](https://user-images.githubusercontent.com/1255665/33844867-f088f522-dea1-11e7-9fb2-ebbdf4477e6d.jpg)

**Comment by Chris00** [comment]
Another one: _coyote_ :-)

**Comment by bluddy** [comment]
> For desert things, how about mesa?

To be honest, I had no idea what a mesa was until I clicked. And I used to live right by a place called Costa Mesa!

**Comment by hcarty** [comment]
I like `mesa` a lot.  It's a short name, it stands over the surrounding terrain.  It has the downside of name-clashing with the [graphics stack] of the same name.

`obuilder` is a minimal name change which is helpful.  It's very similar to other existing tools as @cfcs pointed out.  The name will cause problems when using tab completion on the command line if a project using `obuild` is also installed, even if someone isn't using both tools explicitly.

`caravan` looks and sounds good.  I like `oat` as well, but maybe that should be saved as a potential name for the `bob` project.

[graphics stack]: https://en.wikipedia.org/wiki/Mesa_(computer_graphics)

**Comment by mars0i** [comment]
Is it OK to use names associated mainly with deserts in North American, where camels are not native?

More on ruminate:  If that name is too long, maybe `rumin` could be the command name.  Then to build a project would be to "ruminate" it.  

(jbuild files could be renamed to "cud" files.   
Or maybe not.  Not sure that the build files should named after partially digested food.)

**Comment by mars0i** [comment]
Camel herder or shepherd?
Google translate give "راعي", or "raei" for "herder".  
I wouldn't use something like this without advice from a native speaker, though.

Or maybe just use English call the tool "herder" with command name "herd". 
Then you can say that you are herding your project when you build it.  Which kind of makes sense.

**Comment by cfcs** [comment]
FWIW `caravan -- A framework for testing arbitrary systems, in OCaml.` is also the name of an existing opam package.

**Comment by rdavison** [comment]
So far, I like:
- `obuilder`, but I don't like the name clash with `obuild`
- `mesa`
- `nomad`
- `shepherd`, because jbuilder is more than just a make clone

Some of my own thoughts
- `obt` - ocaml build tool
- `boo` - build_of_ocaml
- `rakuda` - camel in japanese
- `mehariste` - camel cavalry in french

**Comment by shonfeder** [comment]
In praise of `nomad`

- Very nice phonetic feel in my mouth.
- Sounds cool and adventurous.
- Short and memorable.
- Not taken by existing package on opam.
- Has been in English language since at least the 16th century, so I don't have any concerns about cultural appropriation in using it (which, btw, I don't presume to project on y'all. Just a statement about my own feelings).

However, due to the niceness of that name, there are plenty of projects that have used itL https://github.com/search?utf8=%E2%9C%93&q=nomad&type=

It's still my favorite suggestion so far, tho.

**Comment by rdavison** [comment]
We could end all the bike shedding by just calling it `shed`
`shed build @install` sounds kinda cool

**Comment by hcarty** [comment]
`obt` - (O)Caml (b)uild (t)ool

**Comment by AntonioGaspar** [comment]
Orix

**Comment by yminsky** [comment]
nomad is my favorite name thus far. And +1 to @shonfeder's points.

I also like bina or binya, which I think is "build" in Arabic. (though maybe someone who actually knows the language can comment on whether that's right.)

But nomad is still my favorite.

**Comment by hcarty** [comment]
I like nomad a lot as well.  It has at least a few commercial products which share the name: https://en.wikipedia.org/wiki/Nomad_(disambiguation)  Would there be an issue with those project names, similar to what is causing the change from jbuilder now?

**Comment by yminsky** [comment]
It doesn't seem like any of those are in the same space as jbuilder (either one!), so that doesn't seem too worrying.

**Comment by paurkedal** [comment]
Not sure about legal matters, clash of the command name with https://github.com/hashicorp/nomad would be an issue for those using it.

**Comment by mars0i** [comment]
I don't have strong feelings about it--or really, even weak feelings about it--but I want to point out that a nomad is a wanderer, which kind of sounds antithetical to building and constructing.  Or maybe compiled OCaml programs take you on a journey, and `nomad` lets you organize your stuff for the journey.  Not important.  I would support any name, and my vote shouldn't matter anyway.

**Comment by bluddy** [comment]
Another suggestion would be `dune`. It was awesome as a book name, and it still works as an executable. It also pulls in a whole lot of neighboring associated words, such as buggy, sand, and spice (from the book), which could be useful for related tools/files.

There's a dune library for distributed numeric computation, but it's only a library -- not an executable.

**Comment by yawaramin** [comment]
If we're suggesting Arabic-themed names, how about 'jamal'? It's a male name meaning 'beauty'.

- Preserves the 'j' (which I know is not an issue, but anyway)
- No tech project name clashes, at least not on Google
- Easy to type

**Comment by mars0i** [comment]
> If we're suggesting Arabic-themed names, how about 'jamal'? It's a male name meaning 'beauty'.

**Comment by hcarty** [comment]
Is jbuild an option?

**Comment by shonfeder** [comment]
I want to like `caravan`, but it feels plodding and somehow clumsy to me. Moreover, I cannot shake the association with https://en.wikipedia.org/wiki/Dodge_Caravan :(

**Comment by yawaramin** [comment]
I see @jnavila has already suggested 'jamal' which means 'camel', I just want to disambiguate it from 'Jamal' which is a male name meaning 'beauty'. They are pronounced differently:

- jamal is pronounced 'JUM-ul'
- Jamal is pronounced 'jum-ALL' (more or less)

**Comment by darioteixeira** [comment]
+1 for `nomad`.

Another possibility is to pick the name of a desert, like `sahara` or `gobi`. Purists will prefer a desert where bactrian camels actually roam -- which favours `gobi` over `sahara` -- though frankly no one will notice.

**Comment by rdavison** [comment]
I know I already posted in here, but as time goes on, I just want to update my votes:

`nomad` sounds too much like `monad` to me :)
`sahara` or `gobi` sound really really really cool
`obt` I like the no-frills simplicity of this

**Comment by paurkedal** [comment]
I like `gobi`, it's short, it hints at "go build", and contains at least two obviously usable letters for backronyming.

**Comment by Freyr666** [comment]
gobi sounds really appropriate.

**Comment by jnavila** [comment]
`gobi` sound to `go` for me. Not really the intended reference.

**Comment by paurkedal** [comment]
Oh snap!  This is my fault.  I deconstructed the word, and now what everyone sees is "go".  I'll try to reconstruct it as the "Global OCaml Build Infrastructure", where "global" refers to the workspace feature. But I also like some other names mentioned including `dune`, `caravan`, `jamal`, `binya`.  And I was pondering on how amusing it would be to type `unclean` to build a project, but then maybe not.

**Comment by mars0i** [comment]
Why not French?  Is there a term for a build process when one isn't using the English word?  `bâtir`?  `construire`?  Something else?  Maybe not the infinitive but some other form?  I am not fluent in French.

**Comment by ubsan** [comment]
Against mesa - meson is a build system already. I'd rather not use something so close :)

**Comment by IanConnolly** [comment]
Definitely against `nomad` due to the name clash -- I think avoiding executable name clashes should be a priority.

**Comment by hellopatrick** [comment]
`orbs` -- OCaml Robust Build System
`oud` -- [The musical instrument](https://en.wikipedia.org/wiki/Oud).

**Comment by mars0i** [comment]
I love `oud`.  Beautiful instrument.  OCaml Utility for Development?

**Comment by ubsan** [comment]
I like `oud` - it's quite fun to say `oud build`!

**Comment by jnavila** [comment]
Apart from exotic bactrian puns, `obt` makes much sense, just like `sbt` for Scala. To bad there's a clash with this [obt](https://github.com/Financial-Times/origami-build-tools)

**Comment by xclerc** [comment]
There was once a project named `oud` in the OCaml ecosystem,
developed by @zoggy.

**Comment by zoggy** [comment]
That was `oug`: http://oug.forge.ocamlcore.org/
But it's not maintained anymore.

**Comment by xclerc** [comment]
Sorry for the confusion - I knew "oud" had already
been used in the context of OCaml, but it was indeed
the name of the workshop at ICFP a few years ago.

**Comment by igarnier** [comment]
Another desert (and engineering)-themed proposal: `qanat`, which are [underground irrigation systems](https://en.wikipedia.org/wiki/Qanat)

**Comment by Kakadu** [comment]
mameluke?

![from Age of Empires](https://vignette2.wikia.nocookie.net/ageofempires/images/5/54/Theodore_mameluke.jpg/revision/latest?cb=20130223073653)

**Comment by rizo** [comment]
In my opinion it would be nice if we could add sub-command(s) to opam to build
the project. From my experience people get confused by the amount of separeate
tools they need to use to manage the project lifecycle (_e.g._ ocamlfind,
ocamlbuild, opam, odoc/odig, utop, merlin, ocp-indent, topkg, _etc_).

`jbuilder` could be renamed into `opam-build` and could be run as `opam build`.

Another option is to add the `opam project` sub-command as a namespace for all
`jbuilder` commands.

**Comment by leviroth** [comment]
Sticking with the camel/desert/etc. theme and relating to building, perhaps something to do with pyramids would be appropriate. E.g. the word `pyramid` itself, `hemiunu` (architect of the Great Pyramid of Giza), `khufu` (the pharaoh for whom it was built).

**Comment by diml** [comment]
I like the pyramid idea. To me it evokes how we create these big pyramids of projects with jbuilder. Plus pyramids are impressive buildings

**Comment by orbifx** [comment]
Folk, I made a poll to get some aggregation of the overall opinions.

https://poll.disroot.org/jbuilder-rename

The names are loosely in the order I saw from here and in the forum, omitting ones that didn't seem to get any favour.

If I've missed your favourite one, mention me with the name.

**Comment by olafhering** [comment]
@rizo "jbuilder" has to build binaries, and install them into a subtree. After jbuilder has done its work, opam or rpm or apt or whatever grabs that tree and turns it into a package of some sort.

**Comment by pmaddams** [comment]
`omakase`

https://en.m.wikipedia.org/wiki/Omakase

**Comment by hsk** [comment]
`cob` camel o builder.
cob means the hump of a camel in Japanese and Kobu,Konbu is Japanese Laminariaceae.

**Comment by ubsan** [comment]
@hsk that makes me think of COBOL - the COBOL file extension is `.cob`.

**Comment by ibnfirnas** [comment]
How about `emmet`, for [Emmet Brickowski](https://en.wikipedia.org/wiki/List_of_The_Lego_Movie_characters#Emmet_Brickowski) from The Lego Movie (he initially struggles with building, but eventually develops his skills to become a Master Builder).

Other, original, Master Builders may be worth considering:
- `lucy`, for Lucy "Wyldstyle"
- `vitruvius`, for Vitruvius

"Vitruvius" seems pretty original, so I can imagine some legal conflict there, but "Emmet" and "Lucy" are generic enough that they would be unreasonable to claim rights to.

"Emmet" also sounds like "emit", which invokes (in me) somewhat magical associations - just picture Gerald Sussman in his wizard robes, waving a wand and proclaiming "Emit the executable!" :)

**Comment by yawaramin** [comment]
@ibnfirnas there's some kind of editor tooling called Emmet, I think that would be confusing.

**Comment by ibnfirnas** [comment]
@ivg Author of `caravan` here... It is, indeed, neglected, as my priorities changed, but it is not abandoned, since the idea of organizing trees of sequentially-dependent system tests is something I regularly need, just did not get a chance to do it in OCaml in a few years, but I do hope to return to it soonish... 

There, "Caravan" was meant to evoke an image of camels following one behind another in line (possibly several, parallel lines). What would be the mental association for a build tool? Perhaps some guy who's job it is to organize caravans would be a better choice? I can't easily find any such job titles, but Wikipedia says that caravans were commonly organized by Han and Hui firms. `opam search han` matches (though not exactly) a lot of packages, while `opam search hui` returns none.

`hui build`
`hui install`

Kind of has a ring to it, no? To make it more-specific, we could even try `ohui` or `camelhui`... Thoughts?

Oh, and since I mentioned Sussman, how about a very non-revolutionary change from `jbuild` to `jaybuild`?

**Comment by ibnfirnas** [comment]
`brickie` seems decent too: https://en.wikipedia.org/wiki/Bricklayer

**Comment by diml** [comment]
We discussed with the other developers and we settled on `dune`.

Thanks to everyone for helping in finding a new name for Jbuilder! I personally loved the dune books and I'm looking forward to this rename, I think it's a great choice for Jbuilder.

We'll start the renaming work at the beginning of next year, you can follow the advancement on #362.

**Comment by UnixJunkie** [comment]
My (too late) proposition: ocamlb.
Rational: I never liked oamlbuild, so I am very happy to see something eradicating it from the ocaml ecosystem.
Plus, we already have names such as ocamlc, ocamlopt,  etc.
But, of course, having settled on the name of some of the finest science fiction ever written is also cool.
