### ISSUE TITLE
Incorrect linking with `tests/executables` stanza

### ISSUE THREAD

**Issue by Cjen1** [ocaml/dune#3615]
## Expected Behavior
`dune exec test/bar.exe` runs only `test/bar.ml`

## Actual Behavior
`dune exec test/bar.exe` links not only `lib/foo.ml` but also `test/foo.ml`.

## Reproduction
What I think is occurring is that dune isn't respecting `open Lib` and thus is bringing in both `Lib.Log` and `Log` into the executable.

File structure:
```
dune-project
lib
| - dune
| - foo.ml
test
| - dune
| - foo.ml
| - bar.ml
```
`lib/dune` = `(library (name lib))`
`lib/foo.ml` = `let main = print_endline "lib/foo.ml"`
`test/dune` = `(executable (names foo bar) (libraries lib))`
`test/foo.ml` = `let () = print_endline "test/foo.ml"
`test/bar.ml` = 
```
open Lib
let () =
  print_endline "test/bar.ml"; 
  Foo.main ()
```

`dune exec test/bar.exe` would logically only output: 
```
test/bar.ml
lib/foo.ml
```

however outputs:
```
test/foo.ml
test/bar.ml
lib/foo.ml
```

If we change `test/bar.ml` to 
```
let () = 
  print_endline "test/bar.ml";
  Lib.Foo.main ()
```
We only get:
```
test/bar.ml
lib/foo.ml
```

Thus what I think is occurring is that the `test/foo.ml` is getting linked in the first case because a `Foo` module is used without the open being respected.

I expect that this may be a hard thing to fix, though at the very least a "This can occur" would be good to exist somewhere.

This was observed in a situation using Alcotest where only the `test/foo.ml` would end up running.

## Specifications

- Version of `dune` (output of `dune --version`):
2.6.0
- Version of `ocaml` (output of `ocamlc --version`)
4.10.0
- Operating system (distribution and version):
Arch Linux

## Additional information 
Output of `dune exec test/bar.exe --verbose`
incorrect output: https://gist.github.com/Cjen1/733a44b1a143304ade7a11adf053b0b4
corrected output: https://gist.github.com/Cjen1/e87298d81dfd2f8049422351f93b9c97

**Comment by jeremiedimino** [comment]
Your analysis is correct. Dune relies on the `ocamldep` tool to compute cross-module dependencies, and `ocamldep` only understands the syntactic layer. It doesn't know that `Lib` contains a module `Foo`. So Dune can only assume that `bar.ml` refers to the module `Foo` in the same directory.

If you refer to `Foo` several times in `bar.ml`, a workaround is to explicitly write this at the beginning:

```ocaml
module Foo = Lib.Foo
```

Mentioning this in the manual seems reasonable. There is also the idea of [explicit imports](https://github.com/ocaml/dune/issues/1753) if you are interested.

**Comment by Cjen1** [comment]
Ah the explicit imports rfc is quite interesting! But yes I have it working now, it was just a rather difficult thing to debug last week. Shall I close this issue, or would it be useful to keep open?

**Comment by jeremiedimino** [comment]
Let's keep it open for future references. I have labelled it with "wontfix" to make it clear we don't plan to do anything about it for the time being

**Comment by rgrinberg** [comment]
I closed it but it should still be searchable.
