### ISSUE TITLE
env-vars ignored under exec

### ISSUE THREAD

**Issue by progman1** [ocaml/dune#3632]
## Expected Behavior
be taken account of per documentation

## Actual Behavior
ignored

## Reproduction
(env
 (_
  (env-vars (XXX 1)
))

- PR with a reproducing test: 

1.
1.
1.

## Specifications

- Version of `dune` (output of `dune --version`): 2.5.1
- Version of `ocaml` (output of `ocamlc --version`) 4.07.1
- Operating system (distribution and version): ubuntu x86_64

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag):

**Comment by jeremiedimino** [comment]
There is not enough information for us to understand the problem. Please open a new ticket with more details. In particular, please provide commands we can execute to reproduce and observe the issue.

**Comment by progman1** [comment]
dune exec ....   for a program that examines the env and anything set with env-vars is not set, contrary to the docs which says it covers both build and exec.
