### ISSUE TITLE
Why is the name of plugin still `Jbuild_plugin.V1`?

### ISSUE THREAD

**Issue by sangwoo-joh** [ocaml/dune#3633]
Hi. Thanks for the great tool.
I have a question about the module name.
As the title said, why is the name of plugin still `Jbuild_plugin.V1`?
Since I'm using dune version 2.6, I thought that the name of plugin should be `Dune_plugin.V2`, but the error message said `Did you forgot to call [Jbuild_plugin.V*.send]?`.

Is this because there is some plan to deprecate the support for the plugin?
Thank you.!

**Comment by jeremiedimino** [comment]
Hi Sangwoo,

We'd like to replace it by a more principled system. The current mechanism is pretty ad-hoc and only exists as an escape hatch for cases that are not currently covered by Dune. But it doesn't feel like the right long term solution. So it doesn't feel worth changing things now.

**Comment by sangwoo-joh** [comment]
@jeremiedimino 
Thank you for your answer.
I just worried about being deprecated someday, because of not being updated.

Look forward to the principled system!

**Comment by jeremiedimino** [comment]
No problem.  Regarding your concern, we take backward compatibility very seriously, that's [one of our design goal](https://dune.readthedocs.io/en/stable/goals.html#have-excellent-backward-compatibility-properties). So when we deprecate this mechanism, we'll first introduce the new one and wait a reasonable amount of time before deleting the old one. And we'll make sure to announce it in time to give people plenty of time to upgrade their project.
