### ISSUE TITLE
Including a generated file with the sources

### ISSUE THREAD

**Issue by tari3x** [ocaml/dune#3654]
I made a package that automatically generates an API. So in my dune file I have:
```
(rule
 (targets raw.ml raw.mli)
 (deps    WebGPU.webidl)
 (action  (run jsoo-webidl WebGPU.webidl -errors-file errors.out -output-module raw)))
```

For documentation purposes it would be really nice if raw.ml and raw.mli could be part of my source tree, so that people could see them on github without having to download and compile the package and then search around in _build. Perhaps a solution already exists?

**Comment by nojb** [comment]
You can do this by committing the files in question, and adding `(mode promote)` to your `rule` stanza. This has the effect that each time that the files are generated, they will be copied back to your source tree, where you will get a diff (if they have changed), which you will then be able to commit in turn.

See https://dune.readthedocs.io/en/stable/dune-files.html#modes to learn more about `(mode ...)`.

**Comment by tari3x** [comment]
This is exactly what I wanted, thank you so much!
