### ISSUE TITLE
Support :include for foreign_archives 

### ISSUE THREAD

**Issue by db4** [ocaml/dune#3656]
I have an OCaml library that needs some C libraries from an external package manager. So generating `c_libraries.sexp` and then using `(foreign_archives (:include c_libraries.sexp))` seems to be logical. Unfortunately, it does not work:
```
16 |   (foreign_archives (:include c_libraries.sexp))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Atom or quoted string expected
```

**Comment by nojb** [comment]
One of the basic assumptions in `dune` is that dependencies should be known statically (without having to execute any rule). So what you are proposing is not currently supported, not in `(foreign_archives ...)` or in any other field where dependencies are specified (eg `(modules ...)`, `(libraries ...)`, etc.).

However, some form of this may be supported in the future...

**Comment by nojb** [comment]
Coming back to your example, note that `(foreign_archives ...)` is typically used for libraries built by `dune`. If you libraries are available outside of `dune` (ie installed by a package manager), then you could pass the necessary linker flags in `(link_flags ...)`, and this field *does* support `(:include ...)`.

**Comment by db4** [comment]
> Coming back to your example, note that `(foreign_archives ...)` is typically used for libraries built by `dune`. If you libraries are available outside of `dune` (ie installed by a package manager), then you could pass the necessary linker flags in `(link_flags ...)`, and this field _does_ support `(:include ...)`.

Ok, this sounds reasonable. Thank you for the hint!
