### ISSUE TITLE
On Windows, generated .merlin ppx path incorrectly uses backslashes

### ISSUE THREAD

**Issue by leviroth** [ocaml/dune#366]
I have a `jbuild`:

```lisp
(jbuild_version 1)

(executables
 ((names        (example))
  (flags (:standard -short-paths))
  (preprocess (pps (ppx_jane)))))
```

with `example.ml`:

```ocaml
open Base

let f = [%compare.equal: int]
```

This builds just fine. However, the generated .merlin has the following line:

    FLG -ppx "C:\Users\levim\src\ppx-example\_build/default/.ppx/ppx_jane/ppx.exe --as-ppx"

This results in merlin trying and failing to find the ppx at:

    C:.\\Userslevimsrcppx-example_build\\default\\.ppx\\ppx_jane\\ppx.exe

This apparently can be fixed by manually modifying the `\` in the generated .merlin either to `/` or `\\`.

Related to #201.

**Comment by rgrinberg** [comment]
cc @dra27

**Comment by leviroth** [comment]
Or, maybe merlin itself should be responsible for reading the `\` correctly, without escaping?

**Comment by rgrinberg** [comment]
Maybe :) Let's cc @let-def as well.

**Comment by rgrinberg** [comment]
@diml @dra27 Can we change the generation to use `/` on win32 as well?

**Comment by diml** [comment]
I let @dra27 comment on whether it's preferable to use `/` or `\\`, but yh we should make sure we generate something merlin can understand

**Comment by diml** [comment]
I suppose we should add `Path.quote_for_shell` that would take care of all this

**Comment by diml** [comment]
@dra27 do you have time to look at this issue? I believe that we'll need to sort that out for #193 given that the ppx rewriter will be passed to the compiler via `-ppx` which takes a string that is then passed to `Sys.command`.

**Comment by nojb** [comment]
Not sure that `dune` is the right place to fix this. The code that reads this option in `merlin` unconditionally interprets `\ ` to mean "unquote next char", which is wrong on Windows. See
https://github.com/ocaml/merlin/blob/13210bd5638a59f915b854d838a07f0344c713ff/src/utils/std.ml#L677-L733

**Comment by diml** [comment]
Do you mean dune *isn't* the right place to fix this?

**Comment by nojb** [comment]
> Do you mean dune _isn't_ the right place to fix this?

Yes, that's my understand.

**Comment by diml** [comment]
Ok. Is there a ticket on merlin about this BTW?

**Comment by mlasson** [comment]
On merlin sides, it seems that a correct way to implement this side would be to have some kind of external program that prints its arguments (something like "let () = Array.iter print_endline Sys.argv") and call this program with "Sys.command" for each "FLG " lines in the .merlin in order to split the arguments like the "host shell". But that would be an overkill, no ?

In the mean time, in dune, we could either replace the backslash in the executable_name by forward slashes which would be consistent anyway with the rest of the path from the root.

**Comment by diml** [comment]
> In the mean time, in dune, we could either replace the backslash in the executable_name by forward slashes which would be consistent anyway with the rest of the path from the root.

That seems fine to me
