### ISSUE TITLE
Dune cache causing `dune exec` process to die

### ISSUE THREAD

**Issue by tzemanovic** [ocaml/dune#3663]
Enabling dune cache seems to affect `dune exec` command. When the executable needs to be rebuilt, dune cache causes the process to die on the first run. The process runs fine on a subsequent run.

## Reproduction

1. enable dune cache with `~/.config/dune/config` containing:
```
(lang dune 2.6.2)
(cache enabled)
```
1. run `dune exec x.exe` and exit
1. make a change in ocaml source code to force compilation
1. run `dune exec x.exe` again, the executable dies immediately with status code `137`
1. if we run `dune exec x.exe` again, it runs fine

## Specifications

- Version of `dune` (output of `dune --version`): `2.6.2`
- Version of `ocaml` (output of `ocamlc --version`): `4.09.1`
- Operating system (distribution and version): `Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64`

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag): The output of the command when the executable dies: https://gist.github.com/tzemanovic/c50f1846b883bad34280982254f1ff9c

**Comment by mefyl** [comment]
I can't reproduce with a minimal test:

```
$ dune --version
2.6.2
$ cat dune-project 
(lang dune 2.6)
$ cat
$ cat dune 
(executable
 (name main))
$ cat main.ml
let () =
  print_endline "1"
$ DUNE_CACHE=enabled dune exec ./main.exe
1                    
$ sed -i s/1/2/ main.ml 
$ DUNE_CACHE=enabled dune exec ./main.exe
2                    
```

Can you please check I didn't miss something from your instructions ? If not, is there any way to get the actual setup that exhibits the issue ?

**Comment by rgrinberg** [comment]
@tzemanovic please re-open if you're still able to repro.
