### ISSUE TITLE
(subdir ...) stanzas do not work in included `dune` files

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#3668]
To reproduce:
```
$ cat >dune-project <<EOF
> (lang dune 2.5)
> EOF
$ cat >dune <<EOF
> (include dune.inc)
> EOF
$ cat >dune.inc <<EOF
> (subdir a (rule (alias foo) (action (echo Hello))))
> EOF
$ mkdir -p a
$ dune build @foo
File "dune.inc", line 1, characters 2-8:
1 |  (subdir a (rule (alias foo) (action (echo Hello))))
      ^^^^^^
Error: Unknown constructor subdir
```

**Comment by nojb** [comment]
Looking at how `subdir` is implemented, I understand that allowing this would complicate matters, since the `subdir` stanzas are interpreted before evaluating any rule.

On the other hand, this feature is useful in generated `dune` files specifically, so it would nice to support this if not too difficult.

**Comment by nojb** [comment]
One way to do it could be to process `(include ...)` stanzas before processing `(subdir ...)`.

**Comment by jeremiedimino** [comment]
That seems reasonable

**Comment by rgrinberg** [comment]
It works now.

**Comment by vsiles** [comment]
@rgrinberg FYI it doesn't work easier with tuareg mode files like https://github.com/facebook/hhvm/blob/master/hphp/hack/src/hhi/dune
