### ISSUE TITLE
[doc] Issue with provided code for .ocamlinit.

### ISSUE THREAD

**Issue by Zimmi48** [ocaml/dune#3669]
In the new documentation page https://dune.readthedocs.io/en/stable/toplevel-integration.html, some code is provided to paste in `.ocamlinit` to get access to the feature with OCaml < 4.11. I just tried to do this and got:

```
        OCaml version 4.10.0

File "/home/theo/.ocamlinit", line 18, characters 21-37:
18 |       | 0 -> ignore (Toploop.use_file Format.std_formatter fn : bool)
                          ^^^^^^^^^^^^^^^^
Error: Unbound module Toploop
```

I'm reporting this but not investigating it further since nothing prevents me from upgrading to OCaml 4.11.

**Comment by jeremiedimino** [comment]
Ah yes, one needs to do `#directory "+compiler-libs"` to be able to use Toploop. I'm adding this to the doc.
