### ISSUE TITLE
User actions are connected to dune's stdin

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#3672]
When a cram test attempts to read stdin, it will read from dune's stdin. I think it should be closed instead.

A simple way to reproduce this is to run this block in a cram test (e.g. in `otherlibs/cram/test/run.t`):

    $ cat

Then, `dune runtest` hangs. If some input is fed to dune, such as typing "hello" followed by Ctrl-D, the test suggests a promotion:

     $ cat
    +hello

This happens on master as of 4c79d968fc2cef5ec5bf689b6ee1c18bb8a43772.

(cc @rgrinberg, I found this while testing the cram stanza but this is not related)

Thanks!

**Comment by rgrinberg** [comment]
Thanks for the report. Does this also happen in my cram stanza branch?

**Comment by rgrinberg** [comment]
#3677 should fix this in my cram stanza branch

**Comment by emillon** [comment]
Yes, it happens in both master and your branch. I suppose this has always been the case.

**Comment by rgrinberg** [comment]
I renamed the issue because it's actually more general. cram is just a `run` action, and all user actions suffered from this unintended effect.

**Comment by emillon** [comment]
Sure, that makes sense. Probably everything that applies to cram tests would apply to actions. For example, it was probably possible to break reproducibility using things like `cat file | dune build` with an action like `(with-stdout-to file.txt (run cat))`.

**Comment by aalekseyev** [comment]
Indeed. We should add that as a test to #3677.
