### ISSUE TITLE
Cram: error messages when redirecting IO

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#3673]
Hi,

When there is an error with redirecting input or output, the message leaks some info about the temporary shell script:

```diff
 Input:
 
   $ <doesnotexist cat
+  /tmp/dune.cram.ee5255run.t/main.sh: 1: /tmp/dune.cram.ee5255run.t/14.sh: cannot open doesnotexist: No such file
+  [2]
 
 Output:
 
   $ echo > does/not/exist
+  /tmp/dune.cram.ee5255run.t/main.sh: 1: /tmp/dune.cram.ee5255run.t/16.sh: cannot create does/not/exist: Directory nonexistent
+  [2]
```

I'm not sure what the expected behavior is. Maybe just rewrite the beginning so that it reads "Internal dune-cram error: cannot open doesnotexist: No such file" ?

(cc @rgrinberg ; I found this while testing the cram stanza)

Thanks!

**Comment by rgrinberg** [comment]
@jeremiedimino perhaps we should rewrite `TMPDIR` by default? Although we'd still have the random file names leaking.

**Comment by jeremiedimino** [comment]
Rewriting tmpdir seems like a clear improvement. Dune also know all the filenames involved here: `TMPDIR/main.sh` and `TMPDIR/14.sh`, so we could rewrite them as well.

And rewriting the whole thing seems fine as well. Especially since dune knows all the filenames, we can have a precise regexp that has low-risk of rewriting other things.

@emillon I'd just drop the prefix entirely BTW, i.e. rewrite it to:

```
  $ <doesnotexist cat
  cannot open doesnotexist: No such file
```

**Comment by emillon** [comment]
yes, dropping the prefix seems fine as well.

**Comment by rgrinberg** [comment]
>  Dune also know all the filenames involved here: TMPDIR/main.sh and TMPDIR/14.sh, so we could rewrite them as well.

What would be a better name than `TMPDIR/main.sh` or `TMPDIR/14.sh`? I'm working on this, but don't really see the point to be honest.

I still think we should rewrite the error messages however.

**Comment by jeremiedimino** [comment]
Rewriting the error message seems enough indeed. Rewrite the internal temporary files is nitpicking.
