### ISSUE TITLE
Dune looks for OCaml's C headers in the wrong place

### ISSUE THREAD

**Issue by anton-trunov** [ocaml/dune#3681]
When building libraries with `foreign_stubs`, I see output as follows

```
/usr/bin/cc ... -I /Users/anton/.opam/4.10/lib/ocaml ... -o foo.o -c foo.cpp
```

But according to [Chapter 20](https://ocaml.org/releases/4.10/htmlman/intfc.html#ss:c-prim-impl) of the OCaml manual, 

> To write C code that operates on OCaml values, the following include files are provided:
> `caml/mlvalues.h`, `caml/alloc.h`, ...

Please correct me if I wrong, but this looks like Dune should append `/caml` to `ctx.stdlib_dir` when combining it with `-I` switch at least [here](https://github.com/ocaml/dune/blob/48406c09fc7d8d9b91ad2daf8d2d4568fe0d4c41/src/dune/foreign_rules.ml#L110).

## Expected Behavior

```
/usr/bin/cc ... -I /Users/anton/.opam/4.10/lib/ocaml/caml ... -o foo.o -c foo.cpp
```

## Actual Behavior

```
/usr/bin/cc ... -I /Users/anton/.opam/4.10/lib/ocaml ... -o foo.o -c foo.cpp
```

## Reproduction

The following `dune` file should compile without errors (it refers to OCaml's `mlvalues.h` file).
```
(rule
 (with-stdout-to foo.cpp
  (echo "#include <mlvalues.h>\nvoid foo() {}")))

(library
 (name caml)
 (foreign_stubs
  (language cxx)
  (names foo)))
```
## Specifications

- Version of `dune` (output of `dune --version`): 2.6.1
- Version of `ocaml` (output of `ocamlc --version`): 4.10.0
- Operating system (distribution and version): macOS 10.15.5 "Catalina"

## Additional information 

I tried a quick-and-dirty fix: https://github.com/anton-trunov/dune/blob/include-caml/src/dune/foreign_rules.ml#L110. Looks like it works, but I don't know what I'm doing :)

The way I arrived at this issue is somewhat funny, so let me share it to someone who might stumble upon this in the future. After upgrading C++'s Boost library to v1.73, the project I'm working on stopped building on macOS (Linux builds are fine). This happens because Boost started using `#include <version>` in some headers we are using, but there is also `$HOME/.opam/4.10/lib/ocaml/VERSION` file which gets included instead of something like `/usr/local/include/boost/version.hpp` because of macOS's case-insensitive file paths and because apparently some C++ compilers don't care about file extensions. Long story short, appending `/caml` saves the day and seems to adhere to the OCaml manual :)

**Comment by bschommer** [comment]
> When building libraries with `foreign_stubs`, I see output as follows
> 
> ```
> /usr/bin/cc ... -I /Users/anton/.opam/4.10/lib/ocaml ... -o foo.o -c foo.cpp
> ```
> 
> But according to [Chapter 20](https://ocaml.org/releases/4.10/htmlman/intfc.html#ss:c-prim-impl) of the OCaml manual,
> 
> > To write C code that operates on OCaml values, the following include files are provided:
> > `caml/mlvalues.h`, `caml/alloc.h`, ...
> 
> Please correct me if I wrong, but this looks like Dune should append `/caml` to `ctx.stdlib_dir` when combining it with `-I` switch at least [here](https://github.com/ocaml/dune/blob/48406c09fc7d8d9b91ad2daf8d2d4568fe0d4c41/src/dune/foreign_rules.ml#L110).
> 
> ## Expected Behavior
> ```
> /usr/bin/cc ... -I /Users/anton/.opam/4.10/lib/ocaml/caml ... -o foo.o -c foo.cpp
> ```
> 
> ## Actual Behavior
> ```
> /usr/bin/cc ... -I /Users/anton/.opam/4.10/lib/ocaml ... -o foo.o -c foo.cpp
> ```
> 
> ## Reproduction
> The following `dune` file should compile without errors (it refers to OCaml's `mlvalues.h` file).
> 
> ```
> (rule
>  (with-stdout-to foo.cpp
>   (echo "#include <mlvalues.h>\nvoid foo() {}")))
> 
> (library
>  (name caml)
>  (foreign_stubs
>   (language cxx)
>   (names foo)))
> ```
> 
> ## Specifications
> * Version of `dune` (output of `dune --version`): 2.6.1
> * Version of `ocaml` (output of `ocamlc --version`): 4.10.0
> * Operating system (distribution and version): macOS 10.15.5 "Catalina"
> 
> ## Additional information
> I tried a quick-and-dirty fix: https://github.com/anton-trunov/dune/blob/include-caml/src/dune/foreign_rules.ml#L110. Looks like it works, but I don't know what I'm doing :)
> 
> The way I arrived at this issue is somewhat funny, so let me share it to someone who might stumble upon this in the future. After upgrading C++'s Boost library to v1.73, the project I'm working on stopped building on macOS (Linux builds are fine). This happens because Boost started using `#include <version>` in some headers we are using, but there is also `$HOME/.opam/4.10/lib/ocaml/VERSION` file which gets included instead of something like `/usr/local/include/boost/version.hpp` because of macOS's case-insensitive file paths and because apparently some C++ compilers don't care about file extensions. Long story short, appending `/caml` saves the day and seems to adhere to the OCaml manual :)

The clash with `VERSION` is a known problem, see https://github.com/ocaml/ocaml/issues/9523 . I don't think adding the `/caml` to the include path would help, but in contrast would produce more problems since then the OCaml header are visible in your search path and might clash with real headers. The easiest way to solve this is just to remove the `VERSION` file from your OCaml installation.

**Comment by anton-trunov** [comment]
@bschommer Oh, I see. Thanks a lot. Then my take on this is totally wrong. Sorry for the noise.
