### ISSUE TITLE
Dune build inconsistencies if library is missing a dependency

### ISSUE THREAD

**Issue by Zimmi48** [ocaml/dune#3694]
## Expected Behavior

If I forget to specify a dependency of a `library`, I should always get a build failure.

## Actual Behavior

I've observed that I can remove some dependencies from the `(libraries ...)` stanza without making the build fail, while building in a `nix-shell`. The behavior is different when building with dependencies installed in an opam switch. I have no idea what could be causing this discrepancy.

## Reproduction

- PR with a reproducing test: 

1. Build https://github.com/coq/bot/tree/0f703bfd86941ee1a46f87d3c0846c476fb10344 with dependencies installed through `opam` (as documented). Cf. the failing build here: https://github.com/coq/bot/runs/973017634#step:3:361
1. Build the same commit under a `nix-shell` (using the `default.nix` provided in the repository): it passes!
1. Adding the missing dependency (`eqaf`) is sufficient to fix the build when using opam (cf. https://github.com/coq/bot/tree/72f166d613822139cf8389e9a923dff85e71af03).

## Specifications

- Version of `dune` (output of `dune --version`): 2.6.2
- Version of `ocaml` (output of `ocamlc --version`): 4.10
- Operating system (distribution and version): NixOS vs Ubuntu

## Additional information 

I also observed that I can remove the `hex` dependency without triggering a failure under `nix-shell`.

**Comment by avsm** [comment]
Have you tried dune sandboxing to see if you can get the build to fail?

`DUNE_SANDBOX=copy dune build` in nix-shell.

https://dune.readthedocs.io/en/stable/concepts.html#global-sandboxing-configuration <https://dune.readthedocs.io/en/stable/concepts.html#global-sandboxing-configuration>

**Comment by Zimmi48** [comment]
I just tried this but no, this does not make the build fail.

**Comment by rgrinberg** [comment]
What command are you using the build the project under nix-shell? Are you still invoking opam? Or is it a dune command?

**Comment by Zimmi48** [comment]
It is `dune build` or `dune build --ignore-promoted-rules`.

**Comment by rgrinberg** [comment]
I suppose that's the reason for the distinction. Opam builds dune pacakges with the `-p` flag to filter out stanzas that don't belong to the same package (among other things required for a release build).

**Comment by Zimmi48** [comment]
Maybe I misunderstood something, but I just tried with `dune build -p bot-components` and it still didn't give me any error inside my `nix-shell`...

**Comment by rgrinberg** [comment]
Hmm, then I'm not sure what's causing the issue. I thought it was the lack of `-p` in nix.

**Comment by Zimmi48** [comment]
I've reduced my reproducing test to:

`default.nix`:
```nix
{ pkgs ? import (fetchTarball {
  name = "nixpkgs-master-2020-08-05";
  url =
    "https://github.com/NixOS/nixpkgs/archive/143626989245c751505049316ae408737248309d.tar.gz";
  sha256 = "0r2pizvwm7skr6zdwan355ffsb439knk6kb2m0z9xmps67lkjy18";
}) { } }:

with pkgs;
let ocamlPackages = ocaml-ng.ocamlPackages_4_10;
in stdenv.mkDerivation rec {
  name = "test";
  src = null;
  buildInputs = with ocamlPackages; [ # Compiler and dev tools
    ocaml
    findlib
    dune_2
    hex
    eqaf
    cohttp-lwt-unix
  ];
}
```

`dune-project`:
```
(lang dune 2.6)
```

`dune`:
```
(library
 (name test)
 (libraries cohttp-lwt-unix))
```

`main.ml`:
```ocaml
let test signature body =
  let expected =
    body |> Hex.of_cstruct |> Hex.show
  in
  Eqaf.equal signature expected
```

The presence of `cohttp-lwt-unix` in the Dune file makes `dune build` succeed without having to specify `hex` nor `eqaf` as explicit dependencies. However, if I remove `cohttp-lwt-unix` from the Dune file, then I have to explicitly list the two packages to make `dune build` succeed.

**Comment by ejgallego** [comment]
Maybe you want to set `(implicit_transitive_deps false)` ?

**Comment by Zimmi48** [comment]
Thanks, this is it, but does building with `opam` automatically sets this setting to `false`?

**Comment by ejgallego** [comment]
> Thanks, this is it, but does building with `opam` automatically sets this setting to `false`?

Opam is not involved here, that's a flag that controls what Dune will put into scope.

Thus I'm not very sure if this bug should be closed, as far as I understand the behavior you are experienced is expected.

**Comment by Zimmi48** [comment]
> Opam is not involved here, that's a flag that controls what Dune will put into scope.

The question was: why does this fail to build when the dependencies are installed with opam (instead of Nix) even if I didn't specify `(implicit_transitive_deps false)`?

This is the discrepancy that caused me trouble. That being said, this is not a very important issue to me, so feel free to close.

**Comment by ejgallego** [comment]
To debug more we should know the exact command line passed to ocamlc in both nix and opam setups, that can be extracted from `_build/log`

**Comment by Zimmi48** [comment]
I won't have time to provide additional debugging info for this issue (not important to me anymore since I know about `implicit_transitive_deps`), so closing.
