### ISSUE TITLE
`(dirs @starts_with_at_sign)` doesn't work

### ISSUE THREAD

**Issue by anmonteiro** [ocaml/dune#3716]
## Expected Behavior
the directory starting with `@` would be visible to dune

## Actual Behavior
it isn't

## Reproduction

```shell
$ mkdir -p foo/@bar

$ echo '(rule (alias heh) (action (progn (echo hi) (run touch x))))' > foo/@bar/dune

$ echo '(dirs foo/@bar)' > dune

$ dune build foo/@bar/heh
Error: Don't know how to build foo/@bar/heh

```

## Specifications

- Version of `dune` (output of `dune --version`): 2.7.0
- Version of `ocaml` (output of `ocamlc --version`): 4.10.0
- Operating system (distribution and version): NixOS 20.03

**Comment by anmonteiro** [comment]
the repro case is wrong given:

> Currently dune only supports globbing files in a single directory

I had missed that in the docs at first, so this is not a bug.

That does, however, raise a question: it seems like it's not possible to build a rule in a directory that starts with `@`, because dune will always interpret it as an alias. Is that a known limitation, and is there a workaround?

**Comment by rgrinberg** [comment]
> because dune will always interpret it as an alias. Is that a known limitation, and is there a workaround?

it's a known limitation. The simplest workaround is to an alias for this target and build that:
```
(alias
 (name foo)
 (deps @foo))
```

then `$ dune build @foo` should work.

@aalekseyev is there a workaround for this issue in jenga?

**Comment by aalekseyev** [comment]
Nope, only the same workaround as in dune.
