### ISSUE TITLE
Dune 2.6.2 fails to ignore restricted directory in `(data_only_dirs)` stanza

### ISSUE THREAD

**Issue by XVilka** [ocaml/dune#3717]
## Expected Behavior

`dune clean && dune build` cleans and builds directory just fine

## Actual Behavior

I have a symlink to `/sys/debug` in `./tests/bla/foo/debug` which gives "Permission denied " for the normal user. The `./tests` directory is marked as `(data_only_dirs "tests")`.

## Reproduction

1.  Add `(data_only_dirs "tests")` stanza in Dune file
2.  Create a symlink to the directory that is denied access for the user with `ln -s`
3. Run `dune clean` or `dune build`

## Specifications

- Version of `dune` (output of `dune --version`): 2.6.2
- Version of `ocaml` (output of `ocamlc --version`): 4.10.0
- Operating system (distribution and version): Fedora 32 x86_64

**Comment by rgrinberg** [comment]
`data_only_dirs` is only for ignoring rules inside a directory. You can make dune completely ignore `tests/blah/foo/debug` by excluding it from `dirs`.

**Comment by XVilka** [comment]
Yes, it did help. Closing then. Sorry for the noise.
