### ISSUE TITLE
checking dune's cache

### ISSUE THREAD

**Issue by DieracDelta** [ocaml/dune#3719]
Suppose I have a library built with dune. I run `dune build`, then I change a file. I know that dune is able to recognize that most of the project is cached, but one or more files have been changed and dune cannot use its cache for those files. Is there a way to query dune to see if dune thinks there has been changes to a project without rebuilding the project?

**Comment by rgrinberg** [comment]
There's no way to check this at the moment. I suppose we could add a command that would tell you if a target is up to date without building. But note that even this process might require you to build *something*. I'm closing this as we're unlikely to implement such a feature without motivation. But definitely re-open if you have a good use case for this.
