### ISSUE TITLE
dune build of ocaml-ssl fails with Fatal error: exception Failure("Map.of_list_exn: duplicate key")

### ISSUE THREAD

**Issue by rwmjones** [ocaml/dune#3736]
## Expected Behavior
Not failing I guess.

## Actual Behavior
Check out https://github.com/savonet/ocaml-ssl and try to build it using dune 2.7.0.  For me it fails with:

```
run: gcc -O2 -fno-strict-aliasing -fwrapv -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I /usr/lib64/ocaml -o /tmp/ocaml-configuratorefa7ef/c-test-3/test.o -c /tmp/ocaml-configuratorefa7ef/c-test-3/test.c
-> process exited with code 0
-> stdout:
-> stderr:
Fatal error: exception Failure("Map.of_list_exn: duplicate key")
```

## Reproduction

See above.

## Specifications

- Version of `dune` (output of `dune --version`):

This also seems broken:
```
$ dune --version
n/a
```
- Version of `ocaml` (output of `ocamlc --version`)

4.11.0 just released version

- Operating system (distribution and version):

Fedora Linux

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag):

https://gist.github.com/rwmjones/d4aee7db5637941bd9a52ce172cd9bc0

**Comment by rgrinberg** [comment]
Fixed with the nasty workaround. Let us know if this is broken in other situations.
