### ISSUE TITLE
Missing newline after build

### ISSUE THREAD

**Issue by mmottl** [ocaml/dune#3737]
## Expected Behavior

```
Entering directory '...'
Done: 914/915 (jobs: 1)
13:45:36 user@mach$
```

## Actual Behavior

```
Entering directory '...'
Done: 914/915 (jobs: 1)13:45:36 user@mach$
```

## Reproduction

Any `dune build foo.exe` should do.  It seems the problem was only introduced very recently.

## Specifications

- Version of `dune`: 2.7.0
- Version of `ocaml`: 4.11.0
- Operating system (distribution and version): Mac OS X 10.15.6

**Comment by emillon** [comment]
I think I bisected that to 5c133a06f8c5f252abe2b7a855834530fd57d5cb (#3607, @jeremiedimino), so I don't think I'll be able to debug this further :sweat_smile:

**Comment by voodoos** [comment]
Another example, when building a workspace with multiple switches:
```
dune build --always-show-command-line --workspace=dune-workspace.test
Done: 12498/12503 (jobs: 1)dune runtest --workspace=dune-workspace.test
Done: 15893/15897 (jobs: 1)%
```

**Comment by rgrinberg** [comment]
I'll assign this to Jeremie since I'm also puzzled by this.

**Comment by dosaylazy** [comment]
I also noticed that after updating to 2.7.0, when the job counter (e.g. `Done: 194/196 (jobs: 1)`) progresses, it never finishes, and always stops at a few jobs left. Could this change be related to the missing newline?

**Comment by dosaylazy** [comment]
@emillon [This change](https://github.com/ocaml/dune/commit/5c133a06f8c5f252abe2b7a855834530fd57d5cb#diff-ff131fdd19a5b21cb26449420ec47aa7L688) from the commit that you bisected looks suspicious... However, I'm having trouble building Dune following the instructions in HACKING.md, so I can't test what happens if I put back that line.

**Comment by dosaylazy** [comment]
I've made a PR that fixes this: https://github.com/ocaml/dune/pull/3767
