### ISSUE TITLE
Have an option between display short and progress 

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#3741]
## Desired Behavior

I would like to use `--display short` and `--display progress` at the same time.

## Example

It should look something like this:

```
        coqc theories/Colimits/MappingCylinder.vo
        coqc theories/Pointed/pMap.vo
        coqc theories/Colimits/SpanPushout.vo
        coqc theories/Categories/Functor/Dual.vo
        coqc theories/Categories/FunctorCategory/Morphisms.vo
        coqc theories/Categories/HomFunctor.vo
        coqc theories/Categories/SetCategory/Morphisms.vo
Done: 1801/2513 (jobs: 2)
```

Also on a related note, there is a little too much whitespace in `--display short` so having an option to configure that would be great as well.

**Comment by rgrinberg** [comment]
Sound reasonable but I doubt this is something that will be high enough on the priority list. Contributions welcome.

**Comment by Alizter** [comment]
Seems that this is the case now with --display=short.
