### ISSUE TITLE
The cram test for errors is flaky due to difference in shell behavior 

### ISSUE THREAD

**Issue by shonfeder** [ocaml/dune#3744]
## Expected Behavior

`test/blackbox-tests/test-cases/cram/error.t` should succeed or fail reliably
 
## Actual Behavior

Different shells on different machines handle the error case differently (even when both are using distro standard shells executed from `/usr/bin/sh`).

E.g.,

```
------ test/blackbox-tests/test-cases/cram/error.t
++++++ test/blackbox-tests/test-cases/cram/error.t.corrected
File "test/blackbox-tests/test-cases/cram/error.t", line 3, characters 0-1:
 |Error messages are neat and don't leak out generated file names.
 |  $  <doesnotexist cat
-|  cannot open doesnotexist: No such file
-|  [2]
+|  doesnotexist: No such file or directory
+|  [1]
```

## Specifications

- Version of `dune` (output of `dune --version`): `2.7.0`
- Version of `ocaml` (output of `ocamlc --version`): `4.10.0`
- Operating system (distribution and version): `Linux comp 5.4.58-1-MANJARO #1 SMP PREEMPT Tue Aug 11 15:46:30 UTC 2020 x86_64 GNU/Linux`

Shell:

```
$ /usr/bin/sh --version
GNU bash, version 5.0.18(1)-release (x86_64-pc-linux-gnu)
```

**Comment by rgrinberg** [comment]
This test was disabled.
