### ISSUE TITLE
Implicit empty `.mli` files for executable modules

### ISSUE THREAD

**Issue by CraigFe** [ocaml/dune#3745]
When creating an executable, it's a fairly common pattern to create a corresponding `.mli` file, to ensure that any unused values in the implementation are caught by the compiler. (See this example inside [Dune itself](https://github.com/ocaml/dune/blob/master/bin/main.mli)).

It seems worthwhile for Dune to assume the existence of such files by default, avoiding bugs & dead code for users that don't know about the empty `.mli` trick and saving more experienced users time and effort in setting them up. I suspect that is almost always a win, but users could get around it by disabling warning 32 or perhaps using an opt-out mechanism provided by Dune.

**Comment by rgrinberg** [comment]
Seems like this proposal improves the default behavior. I'm for it, but I'd like to see what other maintainers think.

**Comment by nojb** [comment]
Cannot see anything problematic with the proposal.

**Comment by copy** [comment]
This would also fix https://github.com/ocaml/dune/issues/2452 (at least for executables)

**Comment by rgrinberg** [comment]
@craigfe want to give this a try?

**Comment by CraigFe** [comment]
@rgrinberg: Yep, I'll come up with something. Do you have a feel for where this would best sit in the codebase?

**Comment by aalekseyev** [comment]
I think this idea is great.

**Comment by rgrinberg** [comment]
@CraigFe `Exe_rules` seems like the right module.
