### ISSUE TITLE
dune install fails to install directories

### ISSUE THREAD

**Issue by samoht** [ocaml/dune#3752]
`dune build @install` works well for target directories but `dune install` fails.

See for instance this small repro:

```
(rule
  (target foo)
  (package p)
  (action (progn
    (run mkdir foo)
    (run touch foo/bar))))

(install (package p) (section lib) (files foo))
```

and

```
$ dune build @install
$ echo $?
0
$ dune install
Installing /Users/thomas/.opam/system/lib/p/META
Installing /Users/thomas/.opam/system/lib/p/dune-package
Installing /Users/thomas/.opam/system/lib/p/foo
Error: Is a directory
```

**Comment by voodoos** [comment]
@rgrinberg, what are your thoughts on this issue ?

I understood that it would be a useful fix for the Mirage team and I would like your feedback before diving-in.

**Comment by rgrinberg** [comment]
It would be a  good feature to have. How do you plan on expressing a dependency on a target directory though?

By the way, perhaps it would make sense to allow glob patterns inside install stanzas first? That might be enough for your use case.

**Comment by MisterDA** [comment]
> By the way, perhaps it would make sense to allow glob patterns inside install stanzas first? That might be enough for your use case.

It's exactly what I would have needed right now!
My use-case is that my project embeds a webserver with a bunch of static files `static/{img/*.png,css/*.css,js/*.js}`. I'd like so install all these files without having to list each of them, and preserve the directory structure.
