### ISSUE TITLE
dune-cram: ignores everything after a "cram" error

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#3754]
When there's an error due to cram itself (see #3690), the generated script exits and the rest of the test is ignored.

This behavior can be observed by adding a `  $ echo test` line to `test/blackbox-tests/test-cases/cram/error.t`. It then gets ignored.

**Comment by rgrinberg** [comment]
Yeah, that's a shame. Unfortunately there's no way to catch sourcing errors in sh and continue the execution. At least now dune will mark the remaining commands as "ureachable" so the user can see which command caused the issue. I think that's the best we can do.
