### ISSUE TITLE
%{project_root}'s expansion does not take linker's current working directory into account

### ISSUE THREAD

**Issue by anton-trunov** [ocaml/dune#3786]
## Expected Behavior

Build succeeds because `ocamlmklib` is called with the correct path to a vendored C library:

```
ocamlmklib ... -L./deps/libff/install/lib -lff
```

## Actual Behavior

Build fails with the following error:

```
ocamlmklib src/base/cpp/dllscilla_crypto_stubs.so,src/base/cpp/libscilla_crypto_stubs.a (exit 2)
(cd _build/default && /Users/anton/.opam/4.10/bin/ocamlmklib.opt -g -o src/base/cpp/scilla_crypto_stubs src/base/cpp/BIGNUMSerialize.o src/base/cpp/DataConversion.o src/base/cpp/ECPOINTSerialize.o src/base/cpp/PrivKey.o src/base/cpp/PubKey.o src/base/cpp/Schnorr.o src/base/cpp/Signature.o src/base/cpp/Snark.o src/base/cpp/c_schnorr.o src/base/cpp/c_snark.o src/base/cpp/generate_dsa_nonce.o -lstdc++ -L/usr/local/Cellar/openssl@1.1/1.1.1g/lib -lssl -lcrypto -L../../../deps/libff/install/lib -lff)
ld: warning: directory not found for option '-L../../../deps/libff/install/lib'
ld: library not found for -lff
```

This came up when I was trying to remove some hardcoded paths in the build system. We have `libff` as a vendored C dependency in `deps` directory at the project root, which I express as follows.

```
 (c_library_flags
  -L%{project_root}/deps/libff/install/lib -lff)
```

I would expect `-L%{project_root}/deps/libff/install/lib -lff` to expand into `-L%./deps/libff/install/lib -lff` for the linker, because the linker is called from `_build/default` directory.

Please see this commit for the full diff: https://github.com/Zilliqa/scilla/commit/82f416bbcd9011ebbc42054b8c4682657a966461 (before this commit the project builds just fine).

By the way, `%{project_root}` is correctly expanded when building the project's foreign stubs, i.e. this works as expected

```
 (foreign_stubs
 ...
  (include_dirs %{project_root}/deps/libff/install/include))
```

## Reproduction

1. `opam pin add scilla.dev git+https://github.com/Zilliqa/scilla\#libff-unhardcode-paths --no-action`
1. `opam depext scilla --yes`
1. `opam install scilla`

## Specifications

- Version of `dune` (output of `dune --version`): 2.7.1
- Version of `ocaml` (output of `ocamlc --version`): 4.10.0
- Operating system (distribution and version): macOS 10.15.6 Catalina

**Comment by rgrinberg** [comment]
Why do we call `ocamlmklib` from `_build/default` anyway? Perhaps @aalekseyev knows.

An even bigger problem is that you don't seem to be depending on the files in that directory. Or am I missing something?

**Comment by anton-trunov** [comment]
@rgrinberg Excellent point! Dune somehow decides to copy the whole `deps/` directory into `_build/default`, so everything is there, including `deps/libff/install/lib` directory and `libff.a` in it. Coming to think of it, I have no idea how to specify this dependency, given that it lives at the project root and not nested inside the `src/base/cpp` directory. 

It should probably be made a foreign archive, but we need not only the `.a` file, but also a lot of C++ header files (`.hpp`), which I don't know how to make Dune copy to the relevant places. I may be mistaken, but there is no support for `.hpp` and no support for recursive copying all the headers from a given directory.

**Comment by nojb** [comment]
Have you tried using `(foreign_archive deps/libff/install/lib/ff)` to link `libff.a` ?

**Comment by anton-trunov** [comment]
@nojs `foreign_archives` was the first option I tried, but I couldn't make it work. That time I couldn't make Dune find the header files `libff` installs alongside the `.a` file.

If I add `(foreign_archive deps/libff/install/lib/ff)`, then Dune looks for `deps/libff/install/lib/libff.a` w.r.t to `src/base/cpp/` directory, not w.r.t the project root. Here is the directory structure of the project I'm working on:
```
src
├── base
│   ├── cpp
│       ├── dune
deps
└── libff
        ├── include
        │   └── libff
        └── lib
            └── libff.a
```
I guess one solution could be to move `deps/libff` inside `src/base/cpp`, but it feels kind of strange to move vendored code deep into the project.

**Comment by nojb** [comment]
> If I add `(foreign_archive deps/libff/install/lib/ff)`, then Dune looks for `deps/libff/install/lib/libff.a` w.r.t to `src/base/cpp/` directory, not w.r.t the project root.

In that case, you should use `(foreign_archive %{project_root}/deps/libff/install/lib/ff)`.

**Comment by anton-trunov** [comment]
@nojb Sorry, I should have mentioned that I tried it. I get the following message:

```
File "src/base/cpp/dune", line 24, characters 19-60:
24 |  (foreign_archives %{project_root}/deps/libff/install/lib/ff)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Atom or quoted string expected
```

**Comment by nojb** [comment]
> @nojb Sorry, I should have mentioned that I tried it. I get the following message:
> 
> ```
> File "src/base/cpp/dune", line 24, characters 19-60:
> 24 |  (foreign_archives %{project_root}/deps/libff/install/lib/ff)
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Error: Atom or quoted string expected
> ```

I think you should still be able to use a relative path:
```
(foreign_archives ../../deps/libff/install/lib/ff)
```

**Comment by anton-trunov** [comment]
That worked! Thank you so much!

**Comment by jeremiedimino** [comment]
Looks like this issue was resolved so I'm closing it.

**Comment by rgrinberg** [comment]
The concrete issue is fixed, but I'm wondering if there's a deeper issue underneath here.

Anton's original attempt seems to demonstrate an issue with our expansion mechanism:

```
 (c_library_flags
  -L%{project_root}/deps/libff/install/lib -lff)
```

We expanded `%{project_root}` as a path relative to where the rule is defined eagerly, but did not take into account the fact that we run this action (ocamlmklib) in the context's root. @jeremiedimino  It seems like the fundamental issue is that we've interpreted the paths too eagerly?

**Comment by jeremiedimino** [comment]
Seems like it yes. The expansion should be relative to where the command is being executed. That being said, using `-L` manually with a path inside the workspace seems like a recipe for troubles. Using `foreign_archives` is the way to go.
