### ISSUE TITLE
wrong location reported when using copy_files

### ISSUE THREAD

**Issue by zapashcanon** [ocaml/dune#3821]
Hi,

In a folder `src` I have a dune file containing: `(copy_files syntax/*.ml)`. In the `syntax` folder there's a `ast.ml` file.

When I (fail to) build, I get something like: `File "src/types.ml", line 38, characters 2-15: ...`.

Which is not the original location of the file. (It's in `src/syntax/` not just in `src/`) The thing is that I have many folders in `src` and it's not very nice to have to find myself which one is it.

I kinda guess why it is that way but it would be nice if this could be fixed. :)

Cheers!

**Comment by nojb** [comment]
You should use `(copy_files# ...)` instead of `(copy_files ...)`.

**Comment by zapashcanon** [comment]
Oh indeed. I read `(copy# <src> <dst>) to copy a file and add a line directive at the beginning` and didn't understood what that was. Reading the doc further, I see there's a note about it. Thanks !
