### ISSUE TITLE
What folder does dune ignore by default?

### ISSUE THREAD

**Issue by rlepigre** [ocaml/dune#3833]
I have been looking in the doc for information about what subfolders of a dune project are ignored (when searching for dune files), but I could not find anything on that. For instance it seems that folders whose name starts with an underscore (e.g., `_opam`) are ignored. Are there others? Could you please clarify this? Thanks!

**Comment by nojb** [comment]
By default, `dune` ignores subdirectories starting with `.` and `_`.

**Comment by rlepigre** [comment]
Do you know if this is documented anywhere?

**Comment by nojb** [comment]
> Do you know if this is documented anywhere?

It is not very clear, but it is mentioned in passing at https://dune.readthedocs.io/en/stable/dune-files.html#dirs-since-1-6

**Comment by rlepigre** [comment]
I see, thanks. I missed it when searching the doc.
That is good enough for me.
