### ISSUE TITLE
Typo in `configure -help` output

### ISSUE THREAD

**Issue by wildptr** [ocaml/dune#3835]
## Expected Behavior
Expected output of `configure -help`:
```
Usage: ocaml configure.ml [OPTIONS]
Options are:
...
```
## Actual Behavior
```
Usage: ocaml configure.ml [OPTRIONS]]
Options are:
...
```
Note the misspelled "OPTRIONS" and the superfluous "]" at the end of the message. The message is located at configure.ml, line 46.

## Reproduction
run `./configure -help` in dune's source directory

## Specifications

- Version of `dune` (output of `dune --version`):
2.7.1

**Comment by rgrinberg** [comment]
Thanks. Fixed.
