### ISSUE TITLE
cram: a mechanism to skip some lines of the output

### ISSUE THREAD

**Issue by anton-trunov** [ocaml/dune#3858]
## Desired Behavior

E.g. [mdx](https://github.com/realworldocaml/mdx) supports using ellipsis `...` in the output which lets the user to skip zero, one or multiple lines of output.
This is useful when the output of a binary is too chatty or contains some environment or dynamic information (like time stamps).

## Example

```shell
  $ cmd
  ...
  The part of output we care about
  ...
```

The example above would work if a program `cmd` outputs something like this:

```shell
Time: Friday, October 9, 2020, 4:54 PM
The part of output we care about
Have a nice day!
```

**Comment by jeremiedimino** [comment]
While I sympathise with this request, it is unfortunately an anti-pattern when it comes to expectation tests. Indeed, if you use `...` in the expectation and the real output doesn't match, you will get a diff against the fully expanded output. And after promotion, you will have to manually edit the expectation again to delete some lines and replace them by `...`.

We actually have experience with this at Jane Street. We implemented this kind of loose matching in ppx_expect and regretted it pretty much immediately.

One solution we found works better in practice is to post-process the output. In your example, you could for instance do `$ cmd | grep ...` to focus on the part of the output you care about. Using this method works well with the expect test workflow.

For these reasons, I'm closing this request.

**Comment by anton-trunov** [comment]
Right, promotion is far from trivial in this case, thank you for a quick response!
