### ISSUE TITLE
Times reported in trace file aren't correct

### ISSUE THREAD

**Issue by Khady** [ocaml/dune#3861]
I observed that the durations that are stored in the trace file when the --trace-file option is given are not correct. It seems that the bigger the project to compile is, the longer the durations are. Even when the commands executed actually are pretty fast. It is pretty obvious on ocamldep. On a big project I have a trace in which almost all the calls to ocamldep are reported to take over 1.5s. If I run the same command by hand it is much much faster.

```
_build/default$ time ocamldep.opt -modules -impl api/src/core/request/keKeywordsOverviewByPageExport.pp.ml
api/src/core/request/keKeywordsOverviewByPageExport.pp.ml: 11 modules here
real    0m0.005s
user    0m0.005s
sys    0m0.000s
```

![image](https://user-images.githubusercontent.com/974142/95648647-8a6ee000-0b0b-11eb-9e65-2023d606d527.png)

## Expected Behavior

When compiling with `--trace-file=trace.json`, the duration reported in trace.json must be the actual duration taken by the measured commands.

## Actual Behavior

The durations reported get bigger and bigger when the bigger the project compiled is.

## Reproduction

I can't release out big repo to show the problem. But it is already possible to see a different in duration for ocamldep on a tiny repo like https://github.com/khady/diffwhat and a small repo like https://github.com/khady/ocaml-junit. For the first repo, I get a trace with a duration of 5ms for a call to ocamldep. In the second repo, ocamldep is reported to take 47ms. When in both case if I run ocamldep by hand it takes about 5ms.

```
git clone git@github.com/khady/diffwhat
cd diffwhat
DUNE_CACHE=disabled dune build --trace-file=trace.json
```

## Specifications

- Version of `dune` (output of `dune --version`): 2.7.1
- Version of `ocaml` (output of `ocamlc --version`): can reproduce on at least 4.09.0 and 4.11.1
- Operating system (distribution and version): debian 10.3

https://discordapp.com/channels/436568060288172042/469167238268715021/764085737817505792

**Comment by Khady** [comment]
On the [mlang repo](https://gitlab.inria.fr/verifisc/mlang), ocamldep calls are reported to take about 100ms.

```
$ git clone https://gitlab.inria.fr/verifisc/mlang.git
$ cd mlang
$ opam sw create . 4.09.1
$ opam install cmdliner parmap menhir
$ DUNE_CACHE=disabled dune build --trace-file=trace.json
$ cd _build/default
$ time ocamldep -modules -impl "src/mlang/m_ir/mir_dependency_graph.pp.ml"
src/mlang/m_ir/mir_dependency_graph.pp.ml: Cli Format Graph List Mir Pos String Unix

real	0m0.006s
user	0m0.001s
sys	0m0.005s
```

![image](https://user-images.githubusercontent.com/974142/95652273-7682a880-0b22-11eb-9f80-4cad27d7ed50.png)

**Comment by aalekseyev** [comment]
What level of concurrency did dune run to produce this log? That is, how many CPU cores does the machine you ran this on have?

**Comment by aalekseyev** [comment]
Looks like in your case dune was trying to run around 40 commands in parallel, which could explain some of the slow-down.
However, I was able to reproduce that the poor precision of measurement even if that is taken out of consideration.
A patch in this branch:

https://github.com/aalekseyev/dune/tree/precise-command-measurement

makes dune measure more precisely and also store the "overhead" numbers on each event that indicate the difference between the more precise and the less precise ways of measurement.

I'm yet to understand exactly why the precision is so much worse when done in a fiber (likely reason: dune has a lot of internal computation to do and some of that contributes to the measurement overhead).

**Comment by Khady** [comment]
Yes it happened on a 40 cores machine. If there is a lot of overhead in the fiber, does it mean that running on a bigger machine (with 200+ cores) would make things worse?

**Comment by aalekseyev** [comment]
I do expect that running with more cores will make dune internal computation a bottleneck because they are not parallelized.

And indeed, since that internal computation is competing for time with collection of process results, I expect the measurement precision to become even worse then. Even the "more precise" way I implemented in that branch suffers from this problem, to a lesser degree, because it still needs to obtain the OCaml runtime lock before it can collect the results.

**Comment by rgrinberg** [comment]
We now use wait3 when available to report accurate times.
