### ISSUE TITLE
"dune describe": allow to describe specific libraries and directories

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#3893]
It would be nice to be able to restrict the output of `dune describe` to specific libraries (in this case it would print information about a library and all of its dependencies) and/or directories (in which case it would print information about all the libraries in that directory and their dependencies).

And, as in #3892, this should also ideally be extended to support executables as well.

**Comment by rgrinberg** [comment]
Should be quite easy to add now. The directory argument is most natural and fits with the rest of dune.

cc @esope

**Comment by esope** [comment]
I'm not sure about which interface should be given to the user, if we want to support directory filtering, library filtering and executables filtering, as the command could be ambiguous.
For example, a user could write `dune describe foo` : should it refer to the directory `foo` ? to the library/executable `foo` (which can be located in a directory that is not named `foo`) ?
Should we make this explicit, like: `dune describe lib:foo dir:bar exe:baz` ?

**Comment by rgrinberg** [comment]
I would say that `describe foo` should refer to directory `foo`. This is the convention we have with every other command.

**Comment by esope** [comment]
Implemented in PR #6107.
