### ISSUE TITLE
Improve error message on js compilation

### ISSUE THREAD

**Issue by oteku** [ocaml/dune#3896]
## Desired Behavior

When you set `(modes js)` in `dune` file with a `public_name` stanza you get the following error 

```sh
Error: No installable mode found for this executable.
One of the following modes is required:
- exe
- native
- byte
```

It may be usefull to have a more explicit message for newcomers in js compilation.

## Example

Something like 

```sh
Error: No installable mode found for this executable.
When public_name is set, one of the following modes is required:
- exe
- native
- byte
```

or maybe update the doc for `public_name` stanza

**Comment by nojb** [comment]
Sounds good! Would you like to make a PR? It should be enough to amend the message at:
https://github.com/ocaml/dune/blob/76c161dda2a6152c90ea68a9d41e02dd119ee44e/src/dune_rules/dune_file.ml#L1394
