### ISSUE TITLE
Change in file descriptors for dune-run processes since 2.7

### ISSUE THREAD

**Issue by psafont** [ocaml/dune#3902]
The PR https://github.com/ocaml/dune/pull/3677 changed how file descriptors are opened for processes run dune, both using `runtest` and `exec`. 

While easy to workaround whith the cause being known, it broke the tests for [forkexecd](https://github.com/xapi-project/forkexecd/pull/45/commits/1dbfb24a54fa6aaf0a71aa2da47d4294e1f9c7d5)

Here's a binary that replicates the change in behaviour from the tests:

```ocaml
let print_fds () =
  let pid = Unix.getpid () in
  let path = Printf.sprintf "/proc/%d/fd" pid in
  let filtered_fds =
    List.filter (* get rid of the fd used to read the directory *)
      (fun x ->
        try
          ignore (Unix.readlink (Filename.concat path x));
          true
        with _ -> false)
      (Array.to_list (Sys.readdir path))
    |> List.map (fun x -> (x, Unix.readlink (Filename.concat path x)))
    |> (* Filter any of stdin,stdout,stderr which have been mapped to /dev/null *)
    List.filter (fun x ->
        not
          (List.mem x
             [ ("0", "/dev/null"); ("1", "/dev/null"); ("2", "/dev/null") ]))
  in
  let pp fds =
    List.map (fun (x, y) -> Printf.sprintf "%s -> %s" x y) fds
    |> String.concat "; "
  in
  Printf.printf "Expected 3 fds; process has %d: %s"
         (List.length filtered_fds) (pp filtered_fds)

let () = print_fds ()
```

Before the change there's a consistent behaviour:

```
$ dune runtest
       fds alias runtest
Expected 3 fds; process has 3: 0 -> /dev/pts/1; 1 -> /tmp/dune91267f.output; 2 -> /tmp/dune91267f.output
$ dune exec ./fds.exe
Expected 3 fds; process has 3: 0 -> /dev/pts/1; 1 -> /dev/pts/1; 2 -> /dev/pts/1
$ _build/default/fds.exe 
Expected 3 fds; process has 3: 0 -> /dev/pts/1; 1 -> /dev/pts/1; 2 -> /dev/pts/1
```

After the change:

```
$ dune runtest
       fds alias runtest
Expected 3 fds; process has 2: 1 -> /tmp/dunec1d3bc.output; 2 -> /tmp/dunec1d3bc.output
Done: 8/10 (jobs: 1)⏎ 
$ dune exec ./fds.exe
Expected 3 fds; process has 4: 0 -> /dev/pts/1; 1 -> /dev/pts/1; 2 -> /dev/pts/1; 6 -> /dev/null
$ _build/default/fds.exe 
Expected 3 fds; process has 3: 0 -> /dev/pts/1; 1 -> /dev/pts/1; 2 -> /dev/pts/1
```

Current behaviour is awkward if file descriptor behaviour has to be tested.
Consider adding a way to override the current redirection when it's needed, also the behaviour around `dune exec` is not clear to me, is that a bug?

**Comment by rgrinberg** [comment]
Thanks for the detailed report, but I don't think this is a bug. The fd's that a dune action opens is an implementation detail.

> Consider adding a way to override the current redirection when it's needed

Sure, but were you trying to read from stdin? If you weren't, then it seems safer to keep it closed?

>  also the behaviour around dune exec is not clear to me, is that a bug?

is it a bug because stdin is open? `$ foo | dune exec -- foo.exe` should work I think.

**Comment by psafont** [comment]
If you think the behaviour is all expected and documented then it's fine with me, after all what was being tested and how is very particular and a workaround was very small in any case.

> Sure, but were you trying to read from stdin? If you weren't, then it seems safer to keep it closed?
In these tests reading from stin was not needed, it's how file descriptors are being counted due to a design in the RPC of how are stdin, stout and stderr reported.
