### ISSUE TITLE
Problem with installing re2 on 4.06

### ISSUE THREAD

**Issue by yminsky** [ocaml/dune#392]
Apparently, this issue is due to a jbuilder bug: https://github.com/janestreet/re2/issues/22

This seems like a better place to track it.

**Comment by rgrinberg** [comment]
The issue seems to be caused by a 4.06.0 switch having arguments in the `c_compiler` option. @yminsky 's config:

```
c_compiler: cc -O2 -pipe
ocamlc_cflags: -O2 -fno-strict-aliasing -fwrapv
ocamlopt_cflags: -O2 -fno-strict-aliasing -fwrapv
```

While jbuilder assumes that `c_compiler` is just a binary and doesn't contain any flags.

**Comment by rgrinberg** [comment]
This is fixed. @yminsky try this out again in the upcoming beta 17 (sorry for the delays...)

**Comment by yminsky** [comment]
It does seem to work for me now. Thanks!
