### ISSUE TITLE
[Coq] Use the flag -q by default

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [ocaml/dune#3924]
If I write a standard dune file to compile some coq developments, Coq is invoked without the `-q` argument, causing it to load a `coqrc` file. This reduces the reproducibility of the build since I don't know what users might have stored there. Note that `coq_makefile` also includes `-q` by default. Currently, I can use `(flags -q)` to get this behavior, but I think it would be good for `-q` to be an overridable default. Basically every Coq package would benefit from setting this option.

**Comment by ejgallego** [comment]
Thanks for the report, I was not aware that coq_makefile used `-q`, so indeed let's add this to the default flags.

Yeah, maybe we should go towards a way to deprecate loading `coqrc` in coqc, and leave it as an option file for interactive use only upstream?

**Comment by LasseBlaauwbroek** [comment]
> Yeah, maybe we should go towards a way to deprecate loading `coqrc` in coqc, and leave it as an option file for interactive use only upstream?

I am not opposed to this, but I also don't think it is super important if the build systems take care of it. It might surprise casual users if a file that works in `coqtop` does not work in `coqc` because `coqrc` is not loaded.
