### ISSUE TITLE
Invalid DUNE_WORKSPACE causes an untraceable error

### ISSUE THREAD

**Issue by corwin-of-amber** [ocaml/dune#3948]
## Actual Behavior
If `DUNE_WORKSPACE` is set to some value that is not a valid filename, the resulting error is a bit obscure making it hard to find the cause. E.g., I had an empty string assigned to `DUNE_WORKSPACE` by accident, and the error message from `dune build` was:
```
Error: Is a directory
```

## Expected Behavior

For the special case of `DUNE_WORKSPACE == ""`, probably ignoring the env var would be best. For other cases, the error should include some indication that the erroneous file access was caused by `DUNE_WORKSPACE`.

## Reproduction

```
% export DUNE_WORKSPACE=
% dune build
```

## Specifications

- Version of `dune` (output of `dune --version`): 2.7.1
- Version of `ocaml` (output of `ocamlc --version`): 4.08.1
- Operating system (distribution and version): macOS Catalina 10.15.7

**Comment by corwin-of-amber** [comment]
As an aside, if `DUNE_WORKSPACE` is set in your environment and you try to `opam install` something that uses Dune during its build process, all manners of havoc can occur. I was bitten by this a couple of times. I don't know what can be done on the Dune side, though.

**Comment by nojb** [comment]
Make sense. For the second issue it looks like something that should be reported to the `opam` maintainers, they may be able to do something about it.

**Comment by nojb** [comment]
I believe this is fixed. The current error for an empty `DUNE_WORKSPACE` is
```
Error: Workspace file /home/nojebar/t/ does not exist
```
(here `/home/nojebar/t` is the current working directory).
