### ISSUE TITLE
(wrapped false) support for executables

### ISSUE THREAD

**Issue by mshinwell** [ocaml/dune#3952]
I am working on improved support for building the OCaml compiler with dune.  A problem that has cropped up a few times is that there is no way of disabling the "dune exe" prefix for "main executable" .ml files that have the same name as the executable being declared in the current stanza.  I would like an option to disable this, which seems analogous to setting `(wrapped false)` for a library, so that .cmx files that get installed have the correct names.

Apart from this specific use case, it seems correct to me that users should have control over this prefixing, since it is not something with semantics defined by the standard OCaml distribution; and is user visible (for example in a debugger, where module symbols do not currently have the expected name).

**Comment by nojb** [comment]
You can disable it by putting `(wrapped_executables false)` in your `dune-project` file.

**Comment by mshinwell** [comment]
@nojb Thanks.  A famous Dune developer told me it wasn't possible!
