### ISSUE TITLE
create namespace in honor of directory structure

### ISSUE THREAD

**Issue by Nymphium** [ocaml/dune#3964]
The below project seems to have namespaces with directories:
```
lib/
  data/
    data.ml
    foo/
      foo.ml
      foo_pat.ml
    bar/
      bar.ml
    biz/
      foo/
       ...
src/
  command_line.ml
  main.ml
```
however, dune supports only "flat" namespace.

In the above example, I must create a dune file like:
```
(library (name foo))
```
and `Foo` module can be referred anywhere.

When I rename `foo` to `foo__` , although dune generates `Foo__` module and data.ml can only refer the module, I cannot name `foo__` to lib/data/biz/foo due to conflict with the flat namesmace. 

## Desired Behavior
I want dune to create modules with respect to the directory structure.
For example. the above project may contain "bundled" modules for each directories such as:

```
module Foo = struct
  module Foo (* or `include Foo` *)
  module Foo_pat
end
...
module Biz = struct
  module Biz
end
```

Or I can create such modules via `generate_module` in dune 2.8 ?
(* However, I wish I can get these modules without any settings ;) *)

**Comment by rgrinberg** [comment]
This is a duplicate of #1084. It's definitely something we'd like, but not the main priority.

**Comment by Nymphium** [comment]
Okay, thank you!
