### ISSUE TITLE
`dune subst` requires that there is a package with the same name as the project

### ISSUE THREAD

**Issue by leviroth** [ocaml/dune#3965]
## Expected Behavior

`dune subst` does not require there to be a package with the same name as the project.

It's possible there's some deep reason it can't work this way. However, the current behavior is surprising. It's perfectly legal to have (for *n* > 1) *n* packages defined in a dune-project, *n* - 1 of which will by necessity have different names from the project. So if the other packages can work independently of the project name, it's counterintuitive that there would need to be a package that does match the project name.

Alternatively, if the current behavior is necessary, I don't think it's currently documented.

## Actual Behavior

In a dune-project with `(name reddit_api)` and packages `reddit_api_kernel` and `reddit_api_async`:

```
$ dune subst
File "dune-project", line 3, characters 6-16:
3 | (name reddit_api)
          ^^^^^^^^^^
Error: Package reddit_api doesn't exist. Please add a (package (name
reddit_api) ...) stanza to your dune-project file.
```

## Reproduction

There's a commit that shows this behavior [here](https://github.com/leviroth/ocaml-reddit-api/tree/25a468a764ebdef01c7b3d14026613ba4d7d05ff).

## Specifications

- Version of `dune` (output of `dune --version`): 2.7.1
- Version of `ocaml` (output of `ocamlc --version`): 4.11.1
- Operating system (distribution and version): Ubuntu 20.04.1 LTS (on WSL)

**Comment by rgrinberg** [comment]
We're aware, and we're trying to improve the behavior for 2.8 https://github.com/ocaml/dune/pull/3851

**Comment by leviroth** [comment]
I believe #3851 fixed this. Thanks!
