### ISSUE TITLE
(optional) not respected in (executable) and (library) stanza

### ISSUE THREAD

**Issue by fangyi-zhou** [ocaml/dune#3970]
## Expected Behavior

1. Run `$ dune build`
2. main.exe is compiled, main_lwt.exe is not compiled because it's optional and `lwt` is not installed.

## Actual Behavior

Failed with missing `lwt`

## Reproduction
https://github.com/fangyi-zhou/dune-optional-repro

## Specifications

- Version of `dune` (output of `dune --version`): 2.7.1
- Version of `ocaml` (output of `ocamlc --version`) 4.11.0
- Operating system (distribution and version): macos 10.15.7
- Link to gist with verbose output (run `dune` with the `--verbose` flag):
https://gist.github.com/fangyi-zhou/b41bfe07f77abd3219e1fdd09d408198

**Comment by nojb** [comment]
Hello, unless I missed something, there doesn't seem to be any `(optional)` annotation in your reproduction sample.

**Comment by fangyi-zhou** [comment]
Sorry, something was lost in creating the repro, but the behaviour is the same
https://github.com/fangyi-zhou/dune-optional-repro/blob/master/bin/dune#L1

**Comment by fangyi-zhou** [comment]
https://github.com/ocaml/dune/blob/master/test/blackbox-tests/test-cases/optional-executable.t/run.t
https://github.com/ocaml/dune/blob/master/test/blackbox-tests/test-cases/optional.t/run.t
It seems that the behaviour of (optional) is correct, but `dune build` decides to build all stanza regardless of optional. Am I doing it wrong?

**Comment by nojb** [comment]
I was able to reproduce. Indeed it is puzzling. I am investigating.

**Comment by nojb** [comment]
... and actually I think this is the expected behaviour. Indeed, this feature is meant to avoid adding hard-dependencies to OPAM packages, so you will get the desired behaviour only if you build the `@install` target. Other targets will still try to build the `(optional)` stanzas.

It would be great if you can confirm that you see the same behaviour.

**Comment by fangyi-zhou** [comment]
Thanks for the reply. I noticed that building `@install` omits the optional target.

I guess I can close this issue now.
