### ISSUE TITLE
Is it possible to specify dependencies for an instrumenter?

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#3983]
Is it possible to specify dependencies for an instrumenter? For example, in Bisect, we previously recommended using `(preprocessor_deps ...)` to give the filename of the exclusions file, i.e.

```
(preprocess (pps bisect_ppx --exclusions bisect.exclude))
(preprocessor_deps (file bisect.exclude))
```

Doing this now with

```
(instrumentation (backend bisect_ppx --exclusions bisect.exclude))
(preprocessor_deps (file bisect.exclude))
```

results in

```
5 |  (preprocessor_deps (file bisect.exclude))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This preprocessor_deps field will be ignored because no preprocessor
that might use them is configured.
```

_Originally posted by @aantron in https://github.com/ocaml/dune/issues/3932#issuecomment-734738991_

**Comment by nojb** [comment]
This is not currently supported; since instrumentations could in the future be specified by other means than ppx preprocessors, I guess we would like a dedicated field, eg
```
(instrumentation
 (backend bisect_ppx --exclusions bisect.exclude)
 (deps bisect.exclude))
```
I haven't looked to the details, but this looks reasonable to me. cc @jeremiedimino

**Comment by jeremiedimino** [comment]
Me too. A `deps` field in the `instrumentation` one also look more natural to me than a `preprocessor_deps` field on the side of an `instrumentation` one. It makes the intent clearer.

**Comment by aantron** [comment]
Bisect still needs this. It's not practical to use Bisect with the new integration with complicated projects that need files excluded, because exclusion files cannot be found by Bisect when they are not copied into the build directory.

**Comment by nojb** [comment]
> Bisect still needs this. It's not practical to use Bisect with the new integration with complicated projects that need files excluded, because exclusion files cannot be found by Bisect when they are not copied into the build directory.

Ack. Sorry, this slipped through the cracks. I will try to get around to it soon.
