### ISSUE TITLE
`make dev-switch` fails

### ISSUE THREAD

**Issue by fpottier** [ocaml/dune#3996]
## Expected Behavior

The file `HACKING.md` says the very first step is `make dev-switch`.

## Actual Behavior

However, for me, this command seems to fail:

```
The following dependencies couldn't be met:
  - dune-action-plugin → dune >= 2.8
      no matching version
```

Of course I don't have dune 2.8; it does not even exist.
Am I doing something wrong, or should `HACKING.md` be clarified?

**Comment by rgrinberg** [comment]
@dra27 we use the following command:
```
		opam switch create -y --no-install . 4.10.0 --deps-only --with-test
```

Do you know how to make satisfy `dune-action-plugin` constraint using the packages in the repo?

**Comment by rgrinberg** [comment]
As a workaround, you can just do:

```
$ opam switch create -y --no-install . 4.10.0 --deps-only --with-test
$ make dev-deps
```
