### ISSUE TITLE
Context spec in workspace doesn't match documentation

### ISSUE THREAD

**Issue by rleonid** [ocaml/dune#403]
```
$ cat jbuild-workspace
(context (opam (switch 4.05.0)))
$ jbuilder build
File "jbuild-workspace", line 1, characters 10-14:
Error: S-expression of the form (_ _) expected
$ jbuilder --version
1.0+beta16
```

I'm just starting out, going through docs, so I could be misunderstanding something.

**Comment by rleonid** [comment]
It is also super awkward that these files don't require or accept `(jbuild_version 1)`

**Comment by rgrinberg** [comment]
We just changed the format of workspaces and haven't made a release yet so things are a bit out of sync.

**Comment by rleonid** [comment]
Figures, hopefully this issue can be a reminder to get the documentation in sync.

**Comment by rgrinberg** [comment]
It's actually a slightly different issue, the documentation is a bit too up to date for its own good. To get the documentation for the latest stable version of dune you should go here: http://jbuilder.readthedocs.io/en/stable/

**Comment by rleonid** [comment]
Can I, please, make a recommendation that the stable link be the default link in the README.
