### ISSUE TITLE
Output produced by `dune` in `release` profile is much larger than the output produced by `ocamlfind + js_of_ocaml` 

### ISSUE THREAD

**Issue by jayesh-bhoot** [ocaml/dune#4030]
## Expected Behavior

The following commands:

```
ocamlfind ocamlc -package js_of_ocaml,js_of_ocaml-ppx,promise_jsoo -linkpkg -o bg.byte bg.ml

js_of_ocaml +promise_jsoo/indirect_promise.js bg.byte
```

produces a `bg.js` with size of 41K.

dune with the following command

```
dune build --profile release bg.bc.js   
```

produces a `bg.bc.js` with size of 2.2M.

`dune` file:

```
(executable
 (name bg)
 (modes js)
 (libraries js_of_ocaml promise_jsoo)
 (preprocess (pps js_of_ocaml-ppx)))
```

## Actual Behavior

dune should produce an output of size similar to that of `ocamlfind+js_of_ocaml` (~41K).

## Specifications

- Version of `dune` (output of `dune --version`): 2.7.1
- Version of `ocaml` (output of `ocamlc --version`):  4.11.1
- Operating system (distribution and version): openSUSE Leap 15.2

- Link to gist with verbose output (run `dune` with the `--verbose` flag):
https://gist.github.com/jayesh-bhoot/89a932b938ee0e2d003e45de74bf4d81

## Additional Info

Note the use of `promise_jsoo`, which `js_of_ocaml command` links with the `+promise_jsoo/indirect_promise.js`.

I tried a few `dune` config options from the docs, but couldn't make anything work.

The problem looked similar to https://github.com/ocaml/dune/issues/3815, but the resolution seems different.

This discussion https://github.com/ocsigen/js_of_ocaml/issues/1073 might give a few hints.

**Comment by nojb** [comment]
Is the size difference due to the sourcemap, as suggested in ocsigen/js_of_ocaml#1073 ?

**Comment by jayesh-bhoot** [comment]
That's not the case. The last line is not a sourcemap comment in `bg.bc.js` file.

That inspired me to try another command:

```
ocamlfind ocamlc -g -package js_of_ocaml,js_of_ocaml-ppx,promise_jsoo -linkpkg -o bg.byte bg.ml

js_of_ocaml --source-map-inline +promise_jsoo/indirect_promise.js bg.byte
```

With `--source-map-inline`, `js_of_ocaml` adds a sourcemap comment starting with `//# sourceMappingURL=data:application/json;base64,....`, and so produces a larger file, but only with a size of 544K (still smaller than dune's 2.2M).

**Comment by nojb** [comment]
Out of curiosity, can you post the stanza that builds the bytecode executable?

**Comment by jayesh-bhoot** [comment]
> Out of curiosity, can you post the stanza that builds the bytecode executable?

I realized now I didn't post the `dune` file content. Sorry about that. I have added it to the first post for sake of posterity

**Comment by nojb** [comment]
Could it be related to the debugging info? Try adding `(ocamlc_flags :standard \ -g)` to the stanza.

**Comment by jayesh-bhoot** [comment]
```
(executable
 (name bg)
 (modes js)
 (libraries js_of_ocaml promise_jsoo)
 (preprocess (pps js_of_ocaml-ppx))
 (ocamlc_flags :standard \ -g))
```

didn't do anything. Still at 2.2M.

**Comment by nojb** [comment]
Is the project publicly accessible?

**Comment by jayesh-bhoot** [comment]
Sure. Let me clean it up a bit.

**Comment by jayesh-bhoot** [comment]
@nojb Here it is: https://github.com/jayesh-bhoot/ff-webext-jsoo

**Comment by nojb** [comment]
I think it is the fault of `promise_jsoo`, it is linking the whole `ppx` stack: https://github.com/mnxn/promise_jsoo/blob/trunk/dune#L6

**Comment by nojb** [comment]
Removing `gen_js_api-ppx` from the `libraries` field of `promise_jsoo` results in `bg.bc.js` of size 44K which seems about right.

**Comment by jayesh-bhoot** [comment]
> I think it is the fault of promise_jsoo, it is linking the whole ppx stack: https://github.com/mnxn/promise_jsoo/blob/trunk/dune#L6

Yep. I had a look at that earlier. What I am wondering is whether dune can do whatever `ocamlfind + js_of_ocaml` is doing here. Somehow the latter has still managed to bring down the size. If I understand correctly (from my 2 weekends of experience of OCaml), dune should be passing the actual compilation work to the latter. Am I wrong here?

**Comment by nojb** [comment]
Yes, I'm wondering if there is something we could improve here, but am not very famiilar with the PPX internals.

@rgrinberg you mentioned in #3815 that a recent version of the dune language should make linking against a ppx rewriter should result an error or a warning, but that does not seem to be the case here: https://github.com/mnxn/promise_jsoo has `2.7` as project version. Any insights?

**Comment by nojb** [comment]
The issue at hand has been resolved, so closing.
