### ISSUE TITLE
a way of introducing files without specifying exactly what in advance?

### ISSUE THREAD

**Issue by progman1** [ocaml/dune#4059]
I would like to copy source files out of an opam build directory and apply a patch to them (the patch matching the particular version and going to succeed) for dune to compile as one part of a larger opam installation.
I find however no way to evade specifying to dune exactly what those files will be.
I'd prefer not to have to prepare the dune directory via Make/shell and then invoke dune.

is there something for this already or a workaround?

**Comment by progman1** [comment]
I'll try copy_files!

**Comment by rgrinberg** [comment]
copy_files now likes absolute paths.
