### ISSUE TITLE
%{ocaml_version} when ocaml is an alpha release isn't very useful -- maybe need a different var?

### ISSUE THREAD

**Issue by chetmurthy** [ocaml/dune#4060]
## Desired Behavior

It would be helpful, I suspect, if either there were a new "base_ocaml_version", or "ocaml_version" itself gave "4.12.0" when the ocaml version is "4.12.0~alpha3" (as it is right now).  

## Example

For instance, ppx_deriving depends on this for CPPO, and that breaks ppxlib.  That is, if the current ocaml is "4.12.0~alpha3", then dune ends up setting ocaml_version to "4.12.0~alpha3", and this is passed as an argument in the dunefile for ppx_deriving, to cppo.  CPPO barfs at this version-string, and in any case, I would expect that it wouldn't be very useful to conditionalize compilation on the alpha-release-level.  Or at least, it should be possible to conditionalize on the -base- of the release-string, and not on the full string.

I'm not a dune user, but noticed this when trying to build some packages (including pppx_derivingpxlib) that are built with dune

**Comment by nojb** [comment]
This is an issue with `cppo` which does not understand https://github.com/ocaml/ocaml/pull/9712, but this seems to have been fixed in master https://github.com/ocaml-community/cppo/commit/df86865182ae24355cb534475fbf4df589b6dce0

**Comment by nojb** [comment]
Closing as this doesn't look like a `dune` issue.
