### ISSUE TITLE
Better definition and implementation of the jbuild syntax

### ISSUE THREAD

**Issue by diml** [ocaml/dune#407]
I described a standalone project for an AST+parser generator for S-expressions [here](https://github.com/janestreet/usexp/issues/1).

I'd like to eventually use something like this in jbuilder. i.e. Instead of going directly from `Usexp.Ast.t` to `Jbuild.Stanza.t`, we would pass by an intermediate `Jbuild_ast.Stanza.t` type. `Jbuild_ast` would contain the exact AST of the language, without any desugaring. This would have several advantages:

- it's likely to make things quite faster. It's one more pass, but the current code creates a ton of closures
- the AST could be reused for refactoring/analysis tools
- the same mechanism could be reused for most plugins. In particular, for plugins that would want to generate more S-expressions rather than low-level rules, it would be nicer to use the AST datatype rather than directly `Usexp.Ast.t`
- some processing would be easier on the intermediate AST, such as variable expansion

This project is not a priority at all. The hardest part is to implement the generator in usexp, but since it's a completely standalone project, it could be done as an intern project for instance.

**Comment by rgrinberg** [comment]
@diml is this still relevant?

**Comment by diml** [comment]
No, we went in another direction in the end
