### ISSUE TITLE
dune clean does not clean generated opam and .merlin files

### ISSUE THREAD

**Issue by josch** [ocaml/dune#4087]
Hi,

I'm using dune 2.7.1 from Debian unstable. The following dune-project file:

```
(lang dune 2.7)
(name test)
(generate_opam_files true)

(package (name test))
```

After running `dune build` I get:

```
drwxr-xr-x   3 josch josch  120 Jan  6 18:59 .
drwxrwxrwt 239 root  root  7.1K Jan  6 18:59 ..
drwxr-xr-x   5 josch josch  180 Jan  6 18:59 _build
-rw-r--r--   1 josch josch   78 Jan  6 18:52 dune-project
-rw-r--r--   1 josch josch  165 Jan  2 00:58 .merlin
-rw-r--r--   1 josch josch  300 Jan  6 18:59 test.opam
```

When I then run `dune clean` I get:

```
drwxr-xr-x   2 josch josch  100 Jan  6 18:59 .
drwxrwxrwt 239 root  root  7.1K Jan  6 18:59 ..
-rw-r--r--   1 josch josch   78 Jan  6 18:52 dune-project
-rw-r--r--   1 josch josch  165 Jan  2 00:58 .merlin
-rw-r--r--   1 josch josch  300 Jan  6 18:59 test.opam
```

When I run `man dune-clean` I read:

> Removes files added by dune such as _build, <package>.install, and .merlin

Why is the `.merlin` file still there?

While we can maybe argue that the `.merlin` file is hidden, so we don't care, the `test.opam` is also still leftover.

Please consider to either/or:

 - update the documentation to say that the `.merlin` is not removed and neither is any generated `foo.dune` file
 - change the current behavior to remove the `.merlin` and/or a generated `foo.dune` file
 - add a CLI switch to `dune clean` which allows one to remove both

**Comment by rgrinberg** [comment]
The opam file is supposed to be committed to the repository. I wouldn't expect `$ dune clean` to touch it.

As for .merlin files, we'll actually stop generating them in 2.8 so this issue will be solved.

**Comment by josch** [comment]
That's odd. Why would I add an auto-generated file to git? That means that I'm tracking duplicate information. If I  have my dune file in git, I might as well remove the duplicate information from dune-project, no?

**Comment by rgrinberg** [comment]
It's a little odd indeed. The gist of it is it needs to be checked in for `$ opam pin git+https://github.com/foo/bar.git` to work. There's no way to make opam generate the `.opam` file on the fly when pinning.

**Comment by josch** [comment]
Oooh okay, that was the missing piece. Awesome, thanks for your input! Then I'll commit the opam file and put your explanation into the git commit message. Thanks! :+1:
