### ISSUE TITLE
With dune 2.4: Error: Rule failed to generate _doc/_html/highlight.pack.js and _doc/_html/odoc.css

### ISSUE THREAD

**Issue by josch** [ocaml/dune#4126]
Hi,

so this problem might be Debian-specific but the odoc maintainer in Debian also doesn't understand why this is happening so we definitely need your help. Steps to reproduce:

```
mkdir test
cd test
echo "(library (name test) (public_name test))" > dune
printf "(lang dune 2.4)\n(name test)" > dune-project
touch test.opam
dune build @doc
```

One will then get the following error message:

```
File "_doc/_html/_unknown_", line 1, characters 0-0:
Error: Rule failed to generate the following targets:
- _doc/_html/highlight.pack.js
- _doc/_html/odoc.css
Done: 11/15 (jobs: 1)
```

A workaround is to replace `dune 2.4` in dune-project above by `dune 2.3`. Then no error will be raised. We verified that bumping the dune version beyond 2.3 also makes this error happen for real packages. Here the build log of compiling ocamlgraph on the Debian gitlab CI:

https://salsa.debian.org/ocaml-team/ocamlgraph/-/jobs/1347468

When running above commands with `--debug-backtraces` I'm getting:

```
File "_doc/_html/_unknown_", line 1, characters 0-0:
Error: Rule failed to generate the following targets:
- _doc/_html/highlight.pack.js
- _doc/_html/odoc.css
Raised at Stdune__user_error.raise in file "src/stdune/user_error.ml", line
  9, characters 35-74
Called from Dune_engine__build_system.Exported.execute_rule_impl in file
  "src/dune_engine/build_system.ml", line 1525, characters 12-70
Called from Fiber.O.(>>|).(fun) in file "src/fiber/fiber.ml", line 218,
  characters 36-41
Called from Fiber.Execution_context.safe_run_k in file "src/fiber/fiber.ml",
  line 127, characters 18-21
Re-raised at Stdune__exn.raise_with_backtrace in file "src/stdune/exn.ml"
  (inlined), line 36, characters 27-56
Called from Stdune__exn_with_backtrace.reraise in file
  "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from Fiber.Execution_context.forward_error.loop in file
  "src/fiber/fiber.ml", line 135, characters 12-19
Re-raised at Stdune__exn.raise_with_backtrace in file "src/stdune/exn.ml"
  (inlined), line 36, characters 27-56
Called from Stdune__exn_with_backtrace.reraise in file
  "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from Fiber.Execution_context.forward_error.loop in file
  "src/fiber/fiber.ml", line 135, characters 12-19
Re-raised at Stdune__exn.raise_with_backtrace in file "src/stdune/exn.ml"
  (inlined), line 36, characters 27-56
Called from Stdune__exn_with_backtrace.reraise in file
  "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from Fiber.Execution_context.forward_error.loop in file
  "src/fiber/fiber.ml", line 135, characters 12-19
Re-raised at Stdune__exn.raise_with_backtrace in file "src/stdune/exn.ml"
  (inlined), line 36, characters 27-56
Called from Stdune__exn_with_backtrace.reraise in file
  "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from Fiber.Execution_context.forward_error.loop in file
  "src/fiber/fiber.ml", line 135, characters 12-19
Done: 11/15 (jobs: 1)%
```

This is on Debian unstable with dune 2.7.1 and odoc 1.5.2.

Maybe relevant: odoc in Debian patches out the vendored file `highlight.pack.js` in favour of the one shipped by a different package: https://sources.debian.org/src/ocaml-odoc/1.5.2+dfsg-1/debian/patches/no-vendored-js-highlight/ But if that was the problem then why is also `odoc.css` affected?

We think this might be a dune problem, because a workaround is to change the dune version in `dune-project`. Can you reproduce the problem? Any idea why this is happening?

**Comment by josch** [comment]
Hi, I had a hunch and indeed I can confirm that the problem is, that we patched ocaml-odoc in Debian so that it creates symlinks instead of regular files and this seems to confuse dune starting with 2.4. I already modified the patch we use in Debian so that it creates regular files but in the long term it would be great if dune could fix this problem and allows symlinks as well.

**Comment by ejgallego** [comment]
Cannot reproduce on dune 2.8.5 , so likely got fixed.
