### ISSUE TITLE
Allow compilation with foreign object files

### ISSUE THREAD

**Issue by zbaylin** [ocaml/dune#4129]
## Desired Behavior
Per my discussion with @rgrinberg on Discord earlier, as of now in order to include an object file in compilation, it first needs to be embedded in a `.a` file with `ar`.

My thought was to add a `(foreign_objects <foreign-objects-list>)` field that behaves the same way as `(foreign_archives <foreign-archives-list>)`, except with `.o` files.

## Example
`dune`:
```
(library
 (name mylib)
 (foreign_objects myobject.o))

(rule
 (targets myobject.o)
 (action ...))
```

**Comment by rgrinberg** [comment]
`foreign_objects` is the name that I would prefer, but in this field is actually more similar to `foreign_stubs`. It's essentially the same as having `(foreign_stubs (language custom) (names myobject))`, and then manually setting up the `(rule ..)` as you did.

Such a `custom` language wouldn't setup any rules in `Foreign_rules.build_o_files`, but would still return the object file.

The name `foreign_objects` is still preferred though.

To implement this feature, start by reading our [hacking docs](https://dune.readthedocs.io/en/stable/hacking.html). If there's anything unclear, I'm happy to expand them.

You should familiarize yourself with the modules `Foreign`, `Foreign_rules`, and parts of `Dune_file`.
