### ISSUE TITLE
Memory blowup when at least one compilation error has a "global" scope

### ISSUE THREAD

**Issue by bbc2** [ocaml/dune#4134]
The issue appears when there is a compilation error not hidden behind an interface, so an error with a standalone `.ml` file or in a `.mli` file, exposed in the global scope. Apparently, it doesn't seem to be specific to any kind of error.  It can be a syntax error, or a type error, for instance.

## Expected Behavior

```
> dune build @check
...
Error: Syntax error
```

## Actual Behavior

```
> dune build @check
...
```
:boom:  Dune uses at least 10 GB of memory.  I haven't let it go further.

## Reproduction

Unfortunately, I have only been able to reproduce this on our main private repository (about 100k lines of OCaml) so far.

## Specifications

- Version of `dune` (output of `dune --version`): 2.8.1
- Version of `ocaml` (output of `ocamlc --version`): 4.10.0
- Operating system (distribution and version): Arch Linux

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag): https://gist.github.com/bbc2/a1e9986364d32a088e1f2e4aa1b0ce64
- I think this might be related to #4097.
- The problem appeared in version 2.8.0.  It isn't present in 2.7.1.

**Comment by jeremiedimino** [comment]
Thanks for the report. Could you check if #4122 fixes the issue for you?

**Comment by bbc2** [comment]
Yes, no problem. Unfortunately, this doesn't seem to fix it.

```
> dune --version
039c8c1ef
```

```
> dune build @check
Done: 7708/9478 (jobs: 8)^C^C

**************************************************************
* Press Control+C again quickly to perform an emergency exit *
**************************************************************


^C
```

Still the same kind of memory blowup.

**Comment by rgrinberg** [comment]
Thanks for the report. I'll try and reproduce a minimal example.

**Comment by jeremiedimino** [comment]
@bbc2 I believe #4144 fixes this issue. Could you give it a try?

**Comment by bbc2** [comment]
Yes, this one does it, it fixes my issue.  :+1:

**Comment by jeremiedimino** [comment]
Excellent, thanks for testing!

**Comment by jeremiedimino** [comment]
Great, thanks for testing!
