### ISSUE TITLE
Executable built with dune killed by zsh on macOS

### ISSUE THREAD

**Issue by htzh** [ocaml/dune#4135]
## Expected Behavior
Executable should run the same way as command line build.

## Actual Behavior
Command line build with the same options runs fine but executable built with dune is killed by zsh on macOS. To match command line build I have to manually do `codesign -s - test.exe` on the executable.

## Reproduction

- PR with a reproducing test: 

I can compile the following simple test.ml:

    let () =
      at_exit (fun () -> print_endline "Exiting.") ;
      let _ = Sys.(signal sigint (Signal_handle (fun _ -> print_endline "Received SIGINT." ; exit 100))) in
      Unix.sleep 100

by hand on the command line with the same options used by dune:

`ocamlopt -o test -strict-sequence -strict-formats -short-paths -keep-locs -g ~/.opam/default/lib/ocaml/unix.cmxa test.ml`

and it worked as expected. After keying `ctrl-c`:

    ocaml % ./test    
    ^CReceived SIGINT.
    Exiting.

However if I build with dune using the following minimal `dune` file the executable is immediately killed by zsh:

    (executable
     (name test)
     (promote (until-clean))
     (libraries unix))

The problem with dune built exe:

    ocaml % ./test.exe
    zsh: killed     ./test.exe

Note the killing by zsh is immediate (so something is wrong) and there is no keyboard input.

## Specifications

- Version of `dune` (output of `dune --version`): 2.8.1
- Version of `ocaml` (output of `ocamlc --version`) 4.10.2
- Operating system (distribution and version): macOS 11.1 ARM64

## Additional information 

And weirdly enough there seems to be some hysteresis in the behavior related to dune build. Starting with the above example and after building an executable that is always killed, the killing persists even if I hand edit the code to only contain `print_endline "Hello world"`. This "Hello world" from editing only works correctly after I do a `dune clean`. However if I `cp` or `mv` the same code from another existing file then it works right away without need to `dune clean`. Does dune decide on how/when to build certain artifacts based on more than just time stamps?

Originally I had this problem with a much larger code base so I had variously thought it is a problem with Lwt or Unix module. And it is very sensitive to certain code change (like adding a Sys.signal call or adding print_endline to an at_exit function would cause the exe to be killed but otherwise it worked). However after some sleuthing it now appears to be related to how dune builds the artifacts. But all my opam installed code appeared to be working fine so that would be weird too.

**Comment by htzh** [comment]
After posting to the Ocaml forum and following suggestion by `zbaylin` it appears this issue relates to Apple code signing. More specifically, after a fresh `dune build` if I run `codesign -s - test.exe` the executable runs correctly.

**Comment by jeremiedimino** [comment]
What happens if you run `./_build/default/test.exe` instead of `./test.exe`?

**Comment by htzh** [comment]
`./_build/default/test.exe` appears to work even when `./test.exe` does not.

**Comment by htzh** [comment]
`cp`ing `./_build/default/test.exe` to other directories also work. How is `./test.exe` created?

**Comment by jeremiedimino** [comment]
It is copied from `./_build/default/test.exe`. The copy is done inside dune

**Comment by zbaylin** [comment]
> After posting to the Ocaml forum and following [the suggestion](https://discuss.ocaml.org/t/dune-built-executable-killed-by-zsh-on-macos/7113/10?u=zhtprog) by `zbaylin` it appears this issue is related to Apple code signing. More specifically, after a fresh `dune build` if I run `codesign -s - test.exe` the executable runs correctly.

For what it's worth, @ManasJayanth was able to fix this in `esy` by adding in codesigning functionality here: https://github.com/esy/esy/pull/1242

**Comment by jeremiedimino** [comment]
IIUC, Dune would need to call `codesign -s - test.exe` on every executables after copying them?

**Comment by htzh** [comment]
Does Dune use shell `cp` to do the copying? When I do that in the shell it seems to work fine. It is not clear to me what exactly breaks the chain of trust so it is hard to give a prescriptive answer.

**Comment by htzh** [comment]
Symbolic links also work. So now instead of using dune promote stanza I just create a symbolic link once and so far so good.

**Comment by ManasJayanth** [comment]
@jeremiedimino A bug in the codesigning tool (at the time the PR was raised) needs a inode-related work around. I have documented what we do at esy overe here - https://github.com/esy/esy/pull/1242/files#diff-4dea82c8ecf3b5fe56b6fb4881faa5e0de5668e90f921a0aa41e2ab5c905f37a

**Comment by jeremiedimino** [comment]
Does anyone understand why binaries produced by `cp` can be executed but not the one produced by Dune?

@htzh Dune doesn't use `cp` and implements its own copy. If the executable depends on `dune-build-info`, it might even be rewritten during promotion (to replace a placeholder by version information from git).

@ManasJayanth thanks for the pointer.

**Comment by zbaylin** [comment]
> Does anyone understand why binaries produced by `cp` can be executed but not the one produced by Dune?

@jeremiedimino any modifications to the binary (i.e. the `dune-build-info` one you mentioned IIUC) would invalidate the initial codesignature of the file, causing the kernel to refuse to execute it. Since all `cp` does is make a 1:1 copy, the signature doesn't change.

It’s a pain, as `esy` was also modifying the binaries, but the alternative is asking users to disable SIP on their machines 😕.

**Comment by jeremiedimino** [comment]
Ack. However, in the example given in this ticket `dune-build-info` is not involved. In this case, Dune also does a `1:1` copy. So I'm concluding that doing a 1:1 copy is not enough to preserve the signature.

Maybe `cp` is doing something special on OSX, or the system marks `cp` as trusted for creating binaries. Or it is something else.

**Comment by jeremiedimino** [comment]
That said, it would be good to confirm this. @htzh could you compare `_build/default/test.exe` and the `test.exe` promoted by Dune? To make sure they are bit-by-bit equal.

**Comment by htzh** [comment]
@jeremiedimino I can confirm that there is no difference between the two binaries, that is, the promoted copy is identical to the one in the `_build` directory.

As of this moment I could no longer reproduce the `killed by zsh` behavior reported earlier. I don't know what changed on my system causing this to go away. I think it is probably safe to mark this as an Apple issue rather than dune specific. If anyone still has a problem with this behavior the easy work-around is to use symbolic links instead of promotions.

Thanks for everyone's help and feel free to close the issue.

**Comment by jeremiedimino** [comment]
Ack, happy to consider this an Apple issue. Closing then.

**Comment by jeremiedimino** [comment]
Agreed
