### ISSUE TITLE
Dune preventing Unix timer from working properly

### ISSUE THREAD

**Issue by nik312123** [ocaml/dune#4151]
## Expected Behavior
When the timer set by `Unix.setitimer` finishes, it calls the signal handler immediately

## Actual Behavior
Dune seems to cause one of two things to happen: It prevents the timer set by `Unix.setitimer` from giving the `SIGALRM` signal until the current function finishes executing, or it prevents the signal handler itself from being called until the current function finishes executing

## Reproduction

**Showing that the issue occurs when using `dune`**
1. Download this archive to any desired location and extract it: [test.zip](https://github.com/ocaml/dune/files/5861754/test.zip)
2. `cd` into the extracted folder.
3. Run `dune build`
4. Run `dune test` (This may take some time but will finish)
5. Run `dune clean` when done

This clearly takes longer than 1 second to run, and the timer unfortunately does not interrupt it with the `Alarm` exception until the computation of `fib 50` is complete. This is far different from the expected behavior present when using `ocamlbuild` or `utop` as shown below:

**Showing that the issue does not occur when using `ocamlbuild`**
1. Repeat steps 1 – 2 in "Showing the issue when using `dune`" if not already done
2. Run `ocamlbuild -lib unix test.byte`
3. Run `./test.byte`
4. Run `ocamlbuild -clean` when done

**Showing that the issue does not occur when using `utop`**
1. Repeat steps 1 – 2 in "Showing the issue when using `dune`" if not already done
2. Run `utop`
3. In `utop`, run `#use "test.ml";;`
4. In `utop`, run `#quit;;` when done

## Specifications

- Version of `dune` (output of `dune --version`): 2.7.1
- Version of `ocaml` (output of `ocamlc --version`): 4.08.1
- Operating system (distribution and version): macOS Catalina 10.15.7

## Additional information 

The below gist links refer to the output for the "Showing that the issue occurs when using `dune`" section for my machine:

- Link to gist with verbose output for build (run `dune build` with the `--verbose` flag): https://gist.github.com/nik312123/64c069a547ddcf5b9008ec3ac90bd8e8
- Link to gist with verbose output for test (run `dune test` with the `--verbose` flag): https://gist.github.com/nik312123/99af039c8932f4d32f5ca92e2d2e4db1

**Comment by rgrinberg** [comment]
Your dune example is compiling to native code, while your ocamlbuild (and utop) example are using bytecode. Could that explain the difference you're observing?

**Comment by nik312123** [comment]
@rgrinberg You hit the nail on the head! Doing the same exact thing for `ocamlbuild` using `test.native` instead of `test.byte` reproduced the issue I was having in Dune. Adding `(modes byte)` to the dune file fixes the issue.
