### ISSUE TITLE
[merlin] Upgrading to Dune 2.8 confuses Merlin with left-over config files

### ISSUE THREAD

**Issue by voodoos** [ocaml/dune#4168]
Starting Dune 2.8 `.merlin` files are not promoted in the source tree any more.
In absence of `.merlin` files Merlin will ask Dune for its configuration using the `dune ocaml-merlin` command.

However, when upgrading from a previous version of Dune, some `.merlin` files may already be in the source-tree and these won't be removed without a call to `dune clean`. These left-over `.merlin` files will be used by Merlin but they won't be updated by Dune any more and thus Merlin will get out-of-sync if the project configuration change. 

This can be confusing for users.

One way to answer that issue would be to raise a warning when such leftover promoted `.merlin` files are found in the subtree, asking users to perform a `dune clean`.

@rgrinberg does that feel like a reasonable solution to you ? 

Also for maximum impact this patch would need to be released as soon as possible.

**Comment by rgrinberg** [comment]
Seems alright to do this. At this point, the effect is probably going to be minimal as we've let the genie out of the box, but feel free to do so. Let's make sure that this check isn't too costly performance wise though.

**Comment by voodoos** [comment]
What would be the best way to do it in your opinion ?
Maybe we can check when the system is being initialized so it happens only once ?
In very large project that could already be costly...

Also can Dune distinguish promoted files from user-created ones ?
(we don't wan't to warn/delete about custom configs users could have created)

**Comment by voodoos** [comment]
After discussing this subject by @jeremiedimino we decided that the best way to solve that issue would be to tackle a problem a bit more general: Dune could, when scanning the file tree, delete files that were promoted in `Until_clean` mode by rules before but are not any more because the rules changed.

This could be done by comparing the set [source_files_to_ignore](https://github.com/ocaml/dune/blob/main/src/dune_engine/build_system.ml#L925-L927) in `Build_system.load_dir` with the set of promoted files to delete `Promoted_to_delete.load ()`. If a file is in the second one but not the first one it should be removed (this should include leftover `.merlin` files from Dune 2.7).

However this would introduce a mismatch between files known by `File_tree` and `Build_system.targets_of`...

@aalekseyev: do you have advice on how we should tackle that problem ?

**Comment by aalekseyev** [comment]
I think we should try to avoid a general deletion of files from source directory based on a database.
The database can get out of date easily, for example when a file turns from a promoted file into a normal committed source file.

I think it's OK to do this for .merlin files specifically, though. One way to think about this is a promotion of "absence" (aka "whiteout") of .merlin file. After all, if we want merlin to pay attention, then we want to remove the .merlin file regardless of if dune generated it in the past or not.

**Comment by rand00** [comment]
It would have been really useful with some warning printed by dune for this; I was pretty lucky that I found @voodoos comment on (after an hour of debugging): https://discuss.ocaml.org/t/ann-dune-2-8-0/7090/2 

I had some .merlin file hidden i my file hierarchy, and even though I thought I could try to remove it, this isn't obvious at all...
