### ISSUE TITLE
[question] how to tell in the dune file that building the library depends on the previously describbed executable

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/dune#4181]
Hello,

In this example dune file:
```
;; the preprocessor necessary to build all the rest of this project
(executable
  (name prefilter)
  (modules prefilter)
  (libraries str)
  (modes byte))

;; e.g. it is a requirement that it is built and installed to build the following
(library
  (name batList)
  (public_name batList)
;;  (preprocessor_deps prefilter)
  (preprocess
    (action
      (system "./prefilter.bc %{input-file}")))
  (modules batList batEnum batInterfaces batInnerIO batConcurrent
  batOrd batInnerWeaktbl batBytesCompat batRef batSet batSeq batInnerShuffle
  batPrintf batBuffer batString batInt batNumber batInt32 batInt64 batNativeint
  batIO batUnix batFloat batChar))
```

How can I tell dune that the executable must be built (and installed?) prior to building the library?

Currently, I build and install the preprocessor by hand, which is kind of stupid because
I am pretty sure dune could handle this.

Thanks a lot,
F.

**Comment by nojb** [comment]
> How can I tell dune that the executable must be built (and installed?) prior to building the library?

It should be enough to change `(system "./prefilter.bc %{input-file}")` by `(run ./prefilter.exe %{input-file})`.

**Comment by nojb** [comment]
(you should also probably remove `(modes byte)` from the `prefilter` stanza unless you have a good reason to do that)

**Comment by UnixJunkie** [comment]
Ok, I can remove the 'modes byte' thing.
However, if I use '(run ./prefilter.exe %{input-file})':
I get many errros like:
```
File "src/dune", line 13, characters 6-41:
13 |       (run "prefilter.exe %{input-file}")))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: No rule found for "prefilter.exe src/batBuffer.ml"
```
Maybe I should specify somehow that src/bat*.ml{i} need to be preprocessed?
prefilter.exe has been build though.

**Comment by nojb** [comment]
> Ok, I can remove the 'modes byte' thing.
> However, if I use '(run ./prefilter.exe %{input-file})':
> I get many errros like:
> 
> ```
> File "src/dune", line 13, characters 6-41:
> 13 |       (run "prefilter.exe %{input-file}")))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Error: No rule found for "prefilter.exe src/batBuffer.ml"
> ```

You should remove the double quotes and use `./prefilter.exe` instead of just `prefilter.exe`.

**Comment by UnixJunkie** [comment]
Ok, thanks a lot for the help.
So, the final working dune file is:
```
(executable
  (name prefilter)
  (modules prefilter)
  (libraries str))

(library
  (name batList)
  (public_name batList)
  (preprocess
    (action
      (run ./src/prefilter.exe "%{input-file}")))
  (modules batList batEnum batInterfaces batInnerIO batConcurrent
  batOrd batInnerWeaktbl batBytesCompat batRef batSet batSeq batInnerShuffle
  batPrintf batBuffer batString batInt batNumber batInt32 batInt64 batNativeint
  batIO batUnix batFloat batChar))
```

**Comment by nojb** [comment]
Looks good -- if you wanted to be minimal I believe you can remove the double quotes around `%{input-file}`, but that's just splitting hairs.
