### ISSUE TITLE
[merlin] Merlin and Dune disagree on a project's path when symlinks are involved 

### ISSUE THREAD

**Issue by voodoos** [ocaml/dune#4189]
The issue arise when a Dune workspace is accessed from a symlink.

1.  Dune,  when discovering the root of the project uses a path where all symlinks resolved
2. Merlin asks dune for configuration using paths with the symlink not resolved
3. Dune answers that the path is not in the project because it does not recognize the root's path as a prefix of the path given by Merlin

**Comment by voodoos** [comment]
We discussed this offline with @emillon : 

The simple tweak that would consist in having Merlin resolving all the symlinks in the path before sending it to Dune would probably solve the issue for symlinks *outside* of the project root but would break projects with symlinks *inside*of the workspace.

We think the safest solution is for Merlin to give `dune ocaml-merlin` paths that are relative to the directory in which it (`dune`) was started. Then Dune can determine the workspace root, complete the path to reach CWD and use the relative path given by Merlin from here.

**Comment by voodoos** [comment]
Should be fixed with #4221

**Comment by rgrinberg** [comment]
@voodoos can we close this?
