### ISSUE TITLE
Dune doesn't set up subpackages in a way that allows Merlin to work properly

### ISSUE THREAD

**Issue by yminsky** [ocaml/dune#4236]
It's worth saying: I'm not 100% sure if this is a Merlin or Dune bug. I tried this out in both emacs and vscode, and got the same behavior in both places.

## Expected Behavior

Adding a subpackage via Dune (.e.g, core_kernel.pairing_heap) should cause Merlin to work properly and be able to, say, auto-complete on the Pairing_heap module.

## Actual Behavior

Merlin acts as if it doesn't know about the module at all.

The dune file I used is as follows:

```
(library
 (name foo)
 (preprocess
  (pps ppx_jane))
 (inline_tests)
 (libraries core bignum expect_test_helpers_core core_kernel.pairing_heap))
```

but, despite the inclusion of core_kernel.pairing_heap in the libraries declaration, the generated .merlin file includes no mention of pairing_heap.

## Reproduction

If you install core_kernel, and then include core_kernel.pairing_heap in the libraries stanza, you'll see that autocompletion and the like don't work properly in Merlin.

## Specifications

- Version of `dune` (output of `dune --version`): 2.8.2
- Version of `ocaml` (output of `ocamlc --version`) 4.11.1
- Operating system (distribution and version): Fedora release 33

**Comment by ejgallego** [comment]
dune doesn't generate `.merlin` files anymore since 2.8 , what is your merlin version?

**Comment by voodoos** [comment]
Dune topped generating visible `.merlin` files in 2.8 but leftovers are not removed until the next `dune clean`.
Can you try cleaning and rebuilding your project and see if that make a difference ?

After this change you can query the generated configuration by running `dune ocaml-merlin --dump-config="$(pwd)"` from your source folder.

**Comment by rgrinberg** [comment]
Please re-open if the issue still stands. As mentioned by the other posters, you should have no .merlin files in the project.
