### ISSUE TITLE
Why is patdiff instructed to show unrefined diffs?

### ISSUE THREAD

**Issue by hakuch** [ocaml/dune#4254]
## Desired Behavior

When it's installed, Dune uses the `patdiff` utility to show diffs as part of, for example, expectation tests.

My understanding is that the value proposition of `patdiff` is that it shows more refined diffs than whole-line changes.

For example, a diff produced by `patdiff` could identify clearly a single integer being different on a line that's otherwise the same.

## Current behavior

While there's an explicit check for `patdiff` being present [here](https://github.com/ocaml/dune/blob/main/src/dune_engine/print_diff.ml#L96), the `-unrefined` flag is being passed to `patdiff`, which is counter-intuitive to me.

Is the reason for this performance? If so, I'd personally prefer that the default was to omit `-unrefined` and to make its inclusion an option exposed somehow in Dune.

**Comment by jeremiedimino** [comment]
That's a good question... I dig into the history and this argument was passed since the beginning. Seems like I just copy&pasted at the beginning from the way we were calling patdiff in `ppx_expect`.  We should probably remove it.

**Comment by hakuch** [comment]
It's always a pleasure to know I asked a helpful question! :smiley:

Could I take a stab at fixing this with a PR? It might be a nice way to learn a little more about Dune development.

**Comment by jeremiedimino** [comment]
Definitely, thanks for asking and making a PR :)
