### ISSUE TITLE
Better isolation of .cm* files and support of private modules

### ISSUE THREAD

**Issue by diml** [ocaml/dune#427]
Currently we always wait for all the rules of a directory to be loaded before executing any rule from this directory. Technically, we could start executing rules that don't depend on globs from this directory before all the rules are known. That might be useful when we add support for dynamic rules for instance. Indeed, it seems quite natural to write something like this for instance:

```scheme
(executable ((name foo) (module (foo))))

(rule (with-stdout-to jbuild.inc (run ./foo.exe)))

(include jbuild.inc)
```

There is however one issue with such approach: because the compiler uses include directories, the compilation of any .ml/.mli file implicitly depend on `*.cmi`. In fact, there is already an issue currently when there are several independent libraries in the same directories, since they can see each others modules. Though, the problem gets worse if we start building before we have loaded all the rules: because we can only delete stale artefacts when all the rules are known, we might end up leaving stale .cmi files and the compiler could end up reading them.

## Solution

The idea is to put the .cm* files in sub-directories. For instance we could put the .cm* files for a library `foo` in a sub-directory `.foo.objs`. All the rules for this sub-directory would always be all generated at once, so we wouldn't have the issue describe before.

## Private modules

This should provide a simpler way to support private modules: the .cm* files for private modules of libraries could be stored in `.foo.objs/private`. This way we could easily control who can see them by passing or not the relevant `-I .../private` option.

## Work

There should be only three things to change:
1. the path to the various .cm* files
2. the include paths passed to the various tools
3. merlin files

We could proceed as follow:
- change the functions `Module.cm*_file` to take an `obj_dir` argument rather than a `dir` one, as well as various functions in `gen_rules.ml` returning other OCaml object files
- define `obj_dir` in `library_rules` and `executables_rules` appropriately and fold these values everywhere needed
- adapt `Lib.include_flags`, `Lib.link_flags`, ...
- adapt `merlin.ml`

**Comment by nojb** [comment]
Regarding private modules: this is a feature we use heavily in our codebase in order to restrict visibility of certain modules for different clients of the libraries, and so it would be important for us to be able to define different "views" (set of private modules) on the same library.

I haven't followed the details of the proposed implementation, but do you think that you would be able to support this use-case? Thanks!

**Comment by rgrinberg** [comment]
@nojb we have no such plans but are willing to consider it if the feature sounds compelling enough. A couple of questions to start with:

* How does one define different "views" on a library?
* How does one select a different view when depending on a library?

**Comment by nojb** [comment]
@rgrinberg Thanks for the quick reply!

As a first approximation, I think a "view" on a library could be defined by a subset of its module names, corresponding to those modules which are visible (i.e. `.cmi` is exposed).

So, for example, given a library `foo` with three modules `A`, `B` and `C`. One could define a view on `foo`, say `foo-public`, in which only `B` and `C` are visible (i.e. `a.cmi` is hidden). As far as the user is concerned, `foo-public` is handled like any other library. So an "internal" library that needs access to the details of `A` would depend on `foo`, but an "external" library would depend on `foo-public`, so that it would only get a restricted view of `foo` where some types are abstract, etc.

(also cc @alainfrisch as he may have more suggestions, use-cases, etc.)

**Comment by diml** [comment]
In practice do you have more than 2 views? I.e. a *public* one and a *private* one. Having exactly these 2 views was what I had in mind for Dune

**Comment by nojb** [comment]
Right now I can only think of examples with two views; but: does it really make it simpler to impose this restriction?

**Comment by diml** [comment]
Maybe not, but if there is no use for it, I think sticking to the simpler concept is best. private/public is intuitive, views a bit less.

**Comment by diml** [comment]
Note that "scope only" is not straightforward to implement as the various libraries might be installed as part of different packages.

What would be the benefit over just using a naming convention to make it clear some modules are not for users? For instance putting the scope only modules in `Cohttp.Cohttp_private`? This is what we do inside Jane Street; it works well, it's simple to understand and it's one less thing to learn for users.

**Comment by nojb** [comment]
The downside of using a naming convention alone is that you nothing guarantees that the "client" of the "public" part can be compiled *only* using the public interface.

**Comment by diml** [comment]
The thing is hiding cmi files is just not enough. It's often the case that private functions of a module need to be exposed just for testing purposes or internal use. For these there is no choice but to use a naming convention.

Another idea would be to have an attribute `[@@private <scope>]` similar to `[@@deprecated]`, that we could use to control who can use what.

**Comment by paurkedal** [comment]
I have a couple of use cases for the simplest kind of private modules:  Hiding ocamlyacc and ocamllex generated interface, which I don't have much control over, and hiding modules containing only helper functions for the library or other items which are re-exported in other modules. Accessing them in a test suite might be useful, but I think testing the public API is usually sufficient in such cases.

How about merely excluding the `*.cmi` files of private modules from the `*.install` files? Wouldn't that still make the modules available internally?

**Comment by rgrinberg** [comment]
It's not enough unfortunately. In dune, we make sure that libraries are
equivalent whether they're accessed via findlib or available as local
sources. Implementing this feature only via install files will break this
principle

**Comment by diml** [comment]
@rgrinberg I imagine that supporting only the simplest version, i.e. where private modules are visible only to the library itself would be easier, since we only need to pass the `-I .../private` when compiling the library itself. Maybe we could start like this.

Additionally, one way to make the private view easier to understand and implement would be to always install the private cmi files in a `.private` sub-directory, and allow to give the private view to anyone who wants it, for instance by writing something special in the jbuild file:

```scheme
(library
  ((name ...)
   (libraries (foo (private bar) ...))))
```

**Comment by paurkedal** [comment]
In a slightly different scheme,
```
(library
  ((name foo)
   (public_name foo)
   (modules (...))
   (private_modules (...))))
```
would produce two libraries `foo` and `foo_private`, except the latter would only contain the private interface files of and a dependency on `foo`.  To the user, it would appear as if `private_modules` was replaced by an additional
```
(library
 ((name foo_private)
  (public_name foo.private) ; maybe
  (modules (...))
  (libraries (foo))))
```
That should make the semantics clear and, I believe, honour the equivalence of findlib-linking and workspace-scope linking.

**Comment by paurkedal** [comment]
You may be right, and I don't mind your solution either if it's simpler. The need to `-I .private` across projects should be rare, anyway.
