### ISSUE TITLE
Input redirection and pipes

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml/dune#428]
## Description

We should add the following forms to the action language:
- `(with-stdin-from <file> <action>)`
- `(pipe-stdout <action1> <action2> ...)`
- `(pipe-stderr <action1> <action2> ...)`
- `(pipe-outputs <action1> <action2> ...)`

Pipes should be implemented with temporary files, to make things simpler and more portable.

## Implementation

The action language is defined in `src/action_intf`. One should add the new actions and then follow compilation errors to implement them.

The `Future.run*` functions will need to be adapted to support stdin redirection.

**Comment by rgrinberg** [comment]
@NathanReb would you like to address this issue first? I believe it might be useful for your work on composing preprocessors and formatters. The only difference is that we will not be memoizing the result of intermediate preprocessors. However, that doesn't seem so bad to me as it's quite likely not to result in any additional incrementality.

**Comment by NathanReb** [comment]
Yeah that sounds like a good feature, I'd be happy to work on it! That should indeed make my life easier for the preprocessors composition feature and will also ensure that it will benefit any improvement we might make to pipe actions in the future.

Thanks for pointing me to it!
