### ISSUE TITLE
Cram like tests

### ISSUE THREAD

**Issue by diml** [ocaml/dune#429]
I think the way we do blackbox tests is nice and could be packaged so that it can be reused in other projects. We should make it a bit more convenient and portable.

## Details

When a directory is named `foo.dunet`, dune would assume that it contains a file `run` and would do the following:
- it wouldn't scan this directory (same as putting `foo.dunet` in `jbuild-ignore`)
- it would setup the alias `foo.dunet/runtest` to execute the `run` file. The test would depend on `(files_recursively_in foo.dunet)`

## Test syntax

Same as what we have now but using the action language rather than sh:

```
  $ (run echo toto)
  toto
  $ (chdir src)
  $ (run false)
  [1]
```

In particular, dune would scan the action to guess dependencies in the same way that it scan actions in jbuild files.

**Comment by avsm** [comment]
This feature would be useful for RWO to let us build our expect-tests for shell scripts easily.  Some comments:

- The extension `.dunet` reads oddly.  Why not simply `.test`?
- Can there be multiple test scripts in the directory that share state (e.g. one to build and one to run).  Perhaps `run1` `run2` `run3` etc in lexical order?

**Comment by diml** [comment]
Changing the extension seems fine. Multiple tests as well, thought performance wise this might be the same as one big test, i'm not sure.

We might also want to allow tests to state the dependency on a package directly, so that the test is executed in an environment where it looks like the package has been fully built and installed.

**Comment by diml** [comment]
Another thought about this: it would be nice to have an easy way for users to create such self-contained tests for Dune itself.

The idea being that you could accompany tickets with a reproduction case that we could immediately import in Dune. That would save us time.

**Comment by diml** [comment]
I wrote a more concrete proposal in #622
