### ISSUE TITLE
poor error message when odoc is not installed for `dune build @doc`

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#4295]
With odoc not installed:

```
$ dune build @doc                                                                                                                               
        odoc .uring.objs/byte/uring__.odoc (exit 1)                                                                                                                               
(cd _build/default/.uring.objs/byte && /home/avsm/.opam/4.11.1/bin/odoc compile -I . -I ../../_doc/_odoc/pkg/uring --pkg uring -o uring__.odoc uring__.cmt)                       
ERROR: File "uring__.cmt":                                                                                                                                                        
not an implementation               
```

With odoc installed, it builds fine. It's not clear from the dune error message that odoc wasn't installed, though.

**Comment by rgrinberg** [comment]
If odoc isn't installed, why does dune find an odoc binary in your error message? Is `/home/avsm/.opam/4.11.1/bin/odoc` not a valid odoc binary?

**Comment by lubegasimon** [comment]
I couldn’t reproduce @avsm’s issue.
```
simon@Lubegas-MacBook-Pro alcotest % dune build @doc
Error: Program odoc not found in the tree or in PATH
 (context: default)
Hint: opam install odoc
Done: 0/0 (jobs: 0)%       
```

**Comment by avsm** [comment]
This is strange indeed -- it's picking up an odoc from another opam switch. It appears that `opam switch` isn't entirely idempotent, so `opam switch a; opam switch b; opam switch a` will not result in the same environment as just `opam switch a`. 

I'm tracking this down, but it's not a dune bug indeed -- more of an opam quirk. Sorry for the noise here :-)
