### ISSUE TITLE
Spurious RPC test failure

### ISSUE THREAD

**Issue by snowleopard** [ocaml/dune#4296]
## Expected Behavior

Building `main.exe` in the main branch, and then running `main.exe build @runtest` should work, i.e. all tests should pass.

## Actual Behavior

When doing the above, I'm occasionally seeing this failure in the RPC tests:

```
-test/blackbox-tests/test-cases/rpc.t
+test/blackbox-tests/test-cases/rpc.t.corrected
File "test/blackbox-tests/test-cases/rpc.t", line 3, characters 0-1:
 Rpc connection fails when dune isn't running
   $ dune rpc init
-  Error: rpc server not running
+  Error: connect: : No such file or directory
   [1]
 
```

## Reproduction

I couldn't reproduce this reliably.

/cc @rgrinberg

**Comment by snowleopard** [comment]
I noticed that running the testsuite with `-f` flag clears the issue. After that I can get back to using `-w`.

**Comment by rgrinberg** [comment]
The flaky test was removed.

**Comment by rgrinberg** [comment]
> This issue doesn't seem to be fixed for me. I just checked on main and get the same error.

The test mentioned by this issue has been deleted. Perhaps you're seeing the issue in another test? In which case, more details would be appreciated.

> Error: _build/default/test/blackbox-tests/test-cases/github4429.t: Is a
directory

Try doing a clean build. If you encounter this error again, try to do it with a backtrace (`--debug-backtrace`). This seems like a bug

**Comment by snowleopard** [comment]
> The test mentioned by this issue has been deleted. Perhaps you're seeing the issue in another test? 

Ah, sorry, that must be it. I just tried to reproduce but running `_build/default/bin/main.exe build @runtest -w` seems to just hang for me right now, showing `Done: 2/2 (jobs: 0)` permanently. No idea what's going on: running it with `-f` still works fine.

> Try doing a clean build. 

Yep, that helped. Will try to figure out what's on with cram next time.

**Comment by rgrinberg** [comment]
Can this issue be closed then?

**Comment by snowleopard** [comment]
Sure, I'll reopen if it reappears.
