### ISSUE TITLE
How to specify doc output directory?

### ISSUE THREAD

**Issue by SteveBronder** [ocaml/dune#4337]
## Desired Behavior

When compiling documentation with `dune` the default @doc or @doc-private writes them to `_build/default/_doc/`, but is there a way for me to specify what directory I'd like to put the docs in? I'd like to be able to use github pages to generate docs for a project and can't seem to find how to do it.

I tried to look at the code in dune and the most I could get down to is that [`doc`](https://github.com/ocaml/dune/blob/154272b779fe8943a9ce1b4afabb30150ab94ba6/src/dune_engine/alias.ml#L173) is made as a standard alias but it's not clear where they are actually defined at. Could you point me to what exactly `@doc` and `@doc-private` call? If I could see what doc and doc private where doing I think it would be easy at least to write an alias to call odoc but with some extra flags.

## Example

This would be nice!

```bash
dune build --doc-output=./man @doc
```

**Comment by ejgallego** [comment]
Hi @SteveBronder , I'm afraid the output directory is fixed to be `$context/_doc`, see:
https://github.com/ocaml/dune/blob/f56833bb8bcb12a18ea4d44c6863a4d8c6fa5bac/src/dune_rules/odoc.ml#L69-L70

so you will need some extra logic as to move those to a suitable place. If you can use `dune-release`, it already takes care of github pages in its workflow.

**Comment by SteveBronder** [comment]
Thanks! Would the github pages contrain the docs for the private modules as well or only the public module?

**Comment by ejgallego** [comment]
I'm not sure, I guess the best is to try.

**Comment by SteveBronder** [comment]
Alrighty!

**Comment by ejgallego** [comment]
Note that it could make sense for the output dir to be configurable, just mentioning, I know that there are plans for a better doc workflows but I am not fully up to date.

**Comment by SteveBronder** [comment]
It would be nice! I could probably do some clever sed and move everything to another folder but it would be nice to be able to specify it. I'll check if we use dune-release for our nightly builds to see if it's possible to generate a github page with private docs as well that way
