### ISSUE TITLE
Dune 2.8.4 fails to ignore directory. Improper glob?

### ISSUE THREAD

**Issue by mbardwell** [ocaml/dune#4338]
## Reproduction

Take this `src` dir
```
dune # contains (dirs :standard \ a b/c)
a/
b/
  c/
d/
```

If I `dune clean && dune build --build-dir=_build`, I expect **a** and **c** to be ignored, but only **a** is ignored

The [predicate language docs](https://dune.readthedocs.io/en/stable/concepts.html#predicate-lang) say "The exact meaning of :standard and the nature of 'element' depends on the context. For example, in the case of the dirs (since 1.6), an 'element' corresponds to file glob patterns". And [the glob docs](https://dune.readthedocs.io/en/stable/concepts.html?patterns#glob) indicate paths are permitted; also @rgrinberg 's comment [here](https://github.com/ocaml/dune/issues/3717#issuecomment-675307629) indicates that as well.

In my specific case, "**c**" is a python venv, which gets unwillingly copied into `_build`

## Specifications

- Version of `dune` (output of `dune --version`): 2.8.4
- Version of `ocaml` (output of `ocamlc --version`): 4.11.1
- Operating system (distribution and version): Ubuntu 18.04.5 LTS

**Comment by nojb** [comment]
Hello,

The `dirs` stanza only specifies which *immediate* subdirectories should be "seen" by `dune`. So `:standard` refers to the list of immediate subdirectories (minus those starting with `.` or `_`), and so removing `b/c` from it doesn't really do anything :)

You can either put an extra `dirs` stanza in a `dune` file inside `b` or you can also use a `subdir` stanza in the `dune` file you are using right now, as follows: `(subdir b (dirs :standard \ c))`.
