### ISSUE TITLE
cache is not trimmed completely

### ISSUE THREAD

**Issue by copy** [ocaml/dune#4353]
## Expected Behavior

`.cache/dune` should not grow much bigger than 10GB

## Actual Behavior

`.cache/dune` grew to 62 GB after several months of use. Running `dune cache trim --size=10G` only shrunk it down to 31 GB.

## Reproduction

Difficult, since it's most likely leftovers from older versions of dune. After running `dune cache trim --size=10G`, the contents of the `~/.cache/dune` are as follows:

- `db/v2`: 13 GB
- `db/files/v3`: 1 GB  
- `db/files/v4`: 16 GB  

There are also ~13k empty promoting.xxxxx directories in `~/.cache/dune/db`. They don't take much space, but potentially slow down accesses to the cache (on some filesystems).

## Specifications

- Version of `dune` (output of `dune --version`): 2.8.2
- `.config/dune/config`:
```
(lang dune 2.3.0)
(cache enabled)
```

**Comment by Khady** [comment]
Similar problem here. Different settings, but despite a 50GB limit I get over 80GB of cache. That's with `v4` files only.

```
(lang dune 2.5)
(cache enabled)
(cache-trim-size 50GB)
(cache-trim-period 10m)
```

I've recently wiped the cache and tried to reduce the max size to 10GB to pinpoint the problem and got this result.

```
$ du -h -d 1 ~/.cache/dune/db/files
16G	/home/louis.roche/.cache/dune/db/files/v4
16G	/home/louis.roche/.cache/dune/db/files
```

**Comment by nojb** [comment]
Note that cache trimming only considers "cache overhead" (i.e. files not currently hard-linked in a build directory), as removing files currently used would not free any disk space.

Did you try doing `dune clean` in your build directory (or directories) and re-running the trim?

**Comment by Khady** [comment]
After running `dune clean` it goes bellow 10GB indeed

**Comment by copy** [comment]
> Note that cache trimming only considers "cache overhead" (i.e. files not currently hard-linked in a build directory), as removing files currently used would not free any disk space.
> 
> Did you try doing dune clean in your build directory (or directories) and re-running the trim?

Thanks, that clarifies it. The v4 directory is below 10 GB now, however, the v2 directory still takes an additional 13 GB and the thousands of empty promoting.xxxxx directories are still present.

**Comment by nojb** [comment]
> however, the v2 directory still takes an additional 13 GB and the thousands of empty promoting.xxxxx directories are still present.

I'm not familiar with the inner working of the cache. Maybe @snowleopard will be able to chime in.

**Comment by snowleopard** [comment]
I checked the code and found that the trimmer doesn't have any support for trimming `v2` entries. It's not too difficult to add such support but I'm not sure it's worth the extra complexity.

It's safe to delete the `v2` directory manually. Assuming you are not using old versions of Dune, it should never reappear.

**Comment by nojb** [comment]
I am closing this as the situation has been explained and as far as I can see there isn't anything to fix.
