### ISSUE TITLE
Make `dune init proj` create the `dune-project` file 

### ISSUE THREAD

**Issue by shonfeder** [ocaml/dune#4367]
Followup to #4239

It should also populate the `dune-project` file with useful stanzas following our recommended best practices, such as:

- Current lang version
- Enable opam file generation
- Minimal package definition

This has also come up on the discourse: https://discuss.ocaml.org/t/defining-standard-ocaml-development-lifecycle-processes/7486/22

**Comment by jeremiedimino** [comment]
That sounds good. In today's meeting, we also discussed the fact that just `dune init` should create a simple `dune-project` file (cf https://github.com/ocaml/dune/issues/4459).

**Comment by shonfeder** [comment]
@jeremiedimino Would you be ok with an implementation that introduced a function `Dune_project.to_dune_lang : Dune_project.t -> Dune_lang.t`? This seems like the most principled way, as opposed to coding up an adhoc set of `Dune_lang.t` stanzas, that might get out of sync with the `Dune_project`.

**Comment by jeremiedimino** [comment]
That seems fine to me. We generally call such functions `encode` BTW.
