### ISSUE TITLE
Virtual library: nested modules and virtual modules not present

### ISSUE THREAD

**Issue by dannywillems** [ocaml/dune#4372]
## Expected Behavior

`MyLib.M1` should be accessible

## Actual Behavior

`Unbound module MyLib`

## Reproduction

See repository: https://gitlab.com/dannywillems/hello-world-dune-opam.

3 packages are defined: `hello-world` (virtual), `hello-world-unix` (implementation for `hello-world`) and `hello-world-normal`.

All of them have the same structure: two nested modules `M1` and `M2` with a simple `print` function.
I want to call `Hello_world.M1.print` and `Hello_world.M2.print`.
The dune files are the following (*note there is no `hello_world.mli`):
```
; normal package
(library
 (public_name hello-world-normal)
 (name hello_world_normal)
 (modules m1 m2)
)
```
```
; UNIX package
(library
  (public_name hello-world-unix)
  (name hello_world_unix)
  (modules m1 m2)
  (implements hello_world)
)
```
```
; virtual package
(library
  (public_name hello-world)
  (name hello_world)
  (virtual_modules m1 m2)
)
```

There are test files in `test`.
As expected, the `dune exec ./test/test_normal.exe` works fine.
However:
1. when executing `dune exec ./test/test_virtual.exe`, it is fine.
2. when copying the test directory outside of the dune project (copy in tmp for instance), we get `Unbound module Hello_world`

## Specifications

- Version of `dune` (output of `dune --version`): 2.8.4
- Version of `ocaml` (output of `ocamlc --version`): 4.11.0
- Operating system (distribution and version): MacOS + Ubuntu

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag):
When outside of the dune project:
```
Running[2]: (cd _build/default && /Users/dannywillems/.opam/4.11.0/bin/ocamlc.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I .test_virtual.eobjs/byte -I /Users/dannywillems/.opam/4.11.0/lib/hello-world-unix -no-alias-deps -opaque -o .test_virtual.eobjs/byte/dune__exe__Test_virtual.cmo -c -impl test_virtual.ml)
Command [2] exited with code 2:
$ (cd _build/default && /Users/dannywillems/.opam/4.11.0/bin/ocamlc.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I .test_virtual.eobjs/byte -I /Users/dannywillems/.opam/4.11.0/lib/hello-world-unix -no-alias-deps -opaque -o .test_virtual.eobjs/byte/dune__exe__Test_virtual.cmo -c -impl test_virtual.ml)
```

**Comment by kit-ty-kate** [comment]
Replacing `(implements hello_world)` by `(implements hello-world)` (its public name) works fine.

Discrepancies between public names and private ones seem to be a common mistake in dune's usage, I remember seeing several such issues in opam repository's CI

**Comment by rgrinberg** [comment]
> when copying the test directory outside of the dune project (copy in tmp for instance), we get Unbound module Hello_world

I'm not sure I understood this step.  I cloned the repository and moved the test directory into a separate project. The test executables still seem to build.

**Comment by rgrinberg** [comment]
> Discrepancies between public names and private ones seem to be a common mistake in dune's usage, I remember seeing several such issues in opam repository's CI

While that is true, the private name is expected to be hidden in this particular case. Since the test is being copied outside the project. Private names are only usable from within a project.

Closing as invalid until further information is given.
