### ISSUE TITLE
target to generate an inferred interface

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#443]
One of the last uses of ocamlbuild in RWO is for the `.inferred.mli` target 

```
$ corebuild -pkg ctypes.foreign ncurses.inferred.mli
$ cp _build/ncurses.inferred.mli .
```

Is there an equivalent command to generate the default inferred interface? It might be neat to make an optional promotion rule that copies it into the place of an .mli if one doesnt already exist in the source tree.

**Comment by rgrinberg** [comment]
The tendency in https://github.com/ocaml/dune/issues/150 was that this is better supported in the editor.

**Comment by bendiken** [comment]
Not everyone uses an editor with Merlin support, so that's a not wholly satisfactory answer to this missing feature. That said, [cmitomli](https://opam.ocaml.org/packages/cmitomli/) works for me, though the workflow perhaps can't be said to be particularly user friendly:

    $ find _build -name '*.cmi'
    $ cmitomli ./_build/default/src/.cli.objs/cli__Lexer.cmi

**Comment by diml** [comment]
I'm always a bit nervous about adding extra rules for every file as we don't know yet what's the impact in terms of performance.

We need to do a bit more work on the jbuilder internals to partition things at a finer level than the directory level, then adding support for this shouldn't be an issue.
