### ISSUE TITLE
Digests are calculated for files that are not part of any rule

### ISSUE THREAD

**Issue by jchavarri** [ocaml/dune#4438]
## Expected Behavior

When building a project, md5 digests should only be calculated for files that are part of a rule (either input or target I assume).

## Actual Behavior

Digests are calculated for files that are not part of any rule.

## Reproduction

1. Create a new project with `dune init project test && cd test`
2. Check build time with `time dune build @all`:
    ```
    real	0m0.368s
    user	0m0.316s
    sys	0m0.218s
    ```
1. Create a very large file `fallocate -l 10G elephant.img`
2. Run build again with `time dune build @all`:
    ```
    real	0m45.851s
    user	0m35.427s
    sys	0m10.402s
    ```

By adding some logging I could check that it creates digests twice, for both `test/elephant.img` and `_build/default/elephant.img`.

## Specifications

- Version of `dune` (output of `dune --version`): main branch (d75bd885262b98075299e9145a2aa3bd1a54a35d), can reproduce as well with v 2.8.5 published in opam
- Version of `ocaml` (output of `ocamlc --version`): 4.12.0
- Operating system (distribution and version): Debian 10

**Comment by nojb** [comment]
While this may be surprising, I believe this is the expected behaviour. In fact, the `@all` alias depends on *every* file in the source directory, and doing `dune build` or `dune build @all` will copy *every* file in the source tree to the `_build` directory, and so each file will be hashed.

You can change this behaviour by marking some directories as "data only". In that case, their contents will be copied to `_build` only if they are dependencies of some rule.

(Personally I still wonder if there isn't something to improve here...)

cc @jeremiedimino

**Comment by rgrinberg** [comment]
To optimize `@all`, it's conceivable to exclude targets which have a corresponding file in the source tree. I believe `$ dune build dir/` has this problem as well. It will build all targets in `dir/` and this will include targets which just copy sources.

**Comment by nojb** [comment]
> To optimize `@all`, it's conceivable to exclude targets which have a corresponding file in the source tree. I believe `$ dune build dir/` has this problem as well. It will build all targets in `dir/` and this will include targets which just copy sources.

I think this is worth exploring. Right now, if you happen to have big files lying around in your tree that aren't used in the build, you get affected by this issue and: 1) the source of the slowdown is not immediately evident, and 2) the solution (move the big files to ignored or data-only dirs) can be inconvenient.

I added a note for the next dev meeting.

**Comment by jeremiedimino** [comment]
> By adding some logging I could check that it creates digests twice, for both test/elephant.img and _build/default/elephant.img.

FTR, this particular aspect could be optimised. I.e. copy/symlinks rules could be treated specifically so that the file is not hashed twice.
