### ISSUE TITLE
List commands available in a group

### ISSUE THREAD

**Issue by snowleopard** [ocaml/dune#4467]
## Expected Behavior

Run `dune ocaml --help` (or some other command that's part of a group) and see a list of available subcommands.

## Actual Behavior

The current output is not very helpful:

```bash
$ dune ocaml --help

DUNE-OCAML(1)                     Dune Manual                    DUNE-OCAML(1)



NAME
       dune-ocaml

SYNOPSIS
       dune ocaml [OPTION]...

OPTIONS
       --help[=FMT] (default=auto)
           Show this help in format FMT. The value FMT must be one of `auto',
           `pager', `groff' or `plain'. With `auto', the format is `pager` or
           `plain' whenever the TERM env var is `dumb' or undefined.

       --version
           Show version information.



Dune n/a                                                         DUNE-OCAML(1)
```

## Reproduction

Run `dune ocaml --help`.

## Specifications

This is on the main branch. ~We should fix it for Dune 3.~

/cc @rgrinberg @jeremiedimino

**Comment by snowleopard** [comment]
@rgrinberg Thanks for self-assigning. I'd like to also discuss one feature.

For the `dune cache` command, in addition to `dune cache trim`, I'd like to have `dune cache start` and `dune cache stop` that are deprecated. What that means is that I don't want them to show up in the help for `dune cache`, but if the user calls any of these commands, I want a custom deprecation error message to be printed (instead of a generic "command not found").

Will it be difficult to support this?

**Comment by rgrinberg** [comment]
> Will it be difficult to support this?

Probably not. However, our changes to cmdliner (The libray we use for the CLI) are supposed to be upstreamed one day. So it would be good to first agree with [upstream](https://github.com/dbuenzli/cmdliner/pull/123) one such a feature.

**Comment by snowleopard** [comment]
@rgrinberg Yep, I've just added a comment to the corresponding issue.

**Comment by Alizter** [comment]
@emillon Do we consider this resolved now?

**Comment by emillon** [comment]
yes, `dune CMD` will open a manpage that lists subcommands and their synopsis.
