### ISSUE TITLE
[Cache] dune cache corrupts git submodules

### ISSUE THREAD

**Issue by smorimoto** [ocaml/dune#4496]
```
#=== ERROR while compiling luv.0.5.7 ==========================================#
# context     2.1.0~beta4 | linux/x86_64 | ocaml-base-compiler.4.12.0 | git+https://github.com/ocaml/opam-repository.git
# path        ~/src/github.com/ocsigen/lwt/_opam/.opam-switch/build/luv.0.5.7
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p luv -j 47
# exit-code   1
# env-file    ~/.opam/log/luv-12180-058f67.env
# output-file ~/.opam/log/luv-12180-058f67.out
### output ###
#          git (internal) (exit 128)
# (cd src/c/vendor/libuv && /usr/sbin/git rev-parse HEAD) > /tmp/dune5885d5.output
# fatal: not a git repository: /home/smorimoto/src/github.com/ocsigen/lwt/_opam/.opam-switch/build/luv.0.5.7/src/c/vendor/libuv/../../../../.git/modules/src/c/vendor/libuv
```

**Comment by jeremiedimino** [comment]
Why will git related things be corrupted?

**Comment by smorimoto** [comment]
I have no idea, but this seems to only happen if the dune cache is enabled:
https://github.com/smorimoto/ocaml-dune-repro-4496/runs/2381711087?check_suite_focus=true#step:3:637

**Comment by smorimoto** [comment]
It seems to be submodule related, not git related. (I'm not sure if this choice of "corrupted" is precise, but my vocabulary was not as large as I thought.)

**Comment by jeremiedimino** [comment]
Do you expect Dune to call git in this build?

**Comment by smorimoto** [comment]
No, the submodule should have been properly unpacked to the preset path when opam resolved and retrieved the package. If so, we can assume that for some reason the files are not being handled through the dune cache.

**Comment by smorimoto** [comment]
@mefyl Do you have any idea?

**Comment by jeremiedimino** [comment]
Might be worth passing `--debug-dependency-path --debug-backtrace` to Dune, to try and understand why Dune is trying to call git.

**Comment by smorimoto** [comment]
It seems that it cannot find the vendorized folder. Of course, if you install `conf-libuv`, it builds as expected.
https://github.com/smorimoto/ocaml-dune-repro-4496/runs/2382649662?check_suite_focus=true#step:6:15

**Comment by smorimoto** [comment]
Here is an example that works (On Windows, it fails with an irrelevant error, so we can ignore Windows builds.):
https://github.com/smorimoto/ocaml-dune-repro-4496/runs/2382692628?check_suite_focus=true

**Comment by jeremiedimino** [comment]
I'm not too sure what to make of these errors. Could you provide a minimal reproduction case that we could work with?

**Comment by smorimoto** [comment]
Try building a luv repository with dune cache enabled. That should reproduce this problem.

**Comment by jeremiedimino** [comment]
First, could you try with the tip of Dune? There was some work done on the shared cache, so the problem might be fixed already.

**Comment by smorimoto** [comment]
Oops, it seems to be fixed in the latest master!

**Comment by smorimoto** [comment]
Close this because I've confirmed that it has been fixed in the latest master.
