### ISSUE TITLE
`target` field in a `rule` stanza is optional

### ISSUE THREAD

**Issue by arbipher** [ocaml/dune#4526]
`rule` stanza in dune doc(https://dune.readthedocs.io/en/stable/dune-files.html#rule) doesn't list `target` as an optional field. It matches the description there _generate a specific set of files_ . 

However, `alias` stanza (https://dune.readthedocs.io/en/stable/dune-files.html#alias) has a sample of `rule` with no `target`. 

```
(rule
 (alias   runtest)
 (action (run %{exe:my-test-program.exe} blah)))
```

The description and syntax in the `rule` stanza section are not accurate.

**Comment by jeremiedimino** [comment]
Indeed, the doc should be updated.
