### ISSUE TITLE
promote deletes the corrected file without updating the target file

### ISSUE THREAD

**Issue by yminsky** [ocaml/dune#455]
I've been using promote for RWO in the tip of jbuilder, and it mostly works, but not 100%. In particular, if I do a jbuilder build as one step, I'll get a new corrected file as expected. But when I run `jbuilder promote`, that file just disappears, without updating the target.

Note, however, that --auto-promote seems to work without issues.

**Comment by diml** [comment]
Hmm, the tests for `jbuilder promote` are passing currently, can you provide a reproducible example?

**Comment by yminsky** [comment]
It's happening on the RWO repo, but I'll try to give you a more precise recreation some time this weekend.

**Comment by yminsky** [comment]
I'm going to close for now. My naive attempt to replicate has not succeeded. If I see it again, I'll reopen the feature with a clearer account of the issue.

**Comment by diml** [comment]
It's possible that the problem you observed was due to [this](https://github.com/ocaml/dune/issues/456#issuecomment-361281415). It's fixed by #460
