### ISSUE TITLE
problem with dependencies that use `files_recursively_in`

### ISSUE THREAD

**Issue by c-cube** [ocaml/dune#457]
if I have a rule with `(deps ((files_recursively_in ../src)))` (for a test generation tool), I get a failure because dune considers both the files normally in `../src/` (source files) and the files it produced itself (.merlin) for which there's no build rule.

So in practice, with this and #412, it seems I have no way of having my `run_qtest.ml` target be re-generated every time a source file changes 😞

**Comment by rgrinberg** [comment]
Hmm, are you sure? We were talking about renaming `files_recursively_in` for the exact reason that it _only_ considers the sources.

https://github.com/ocaml/dune/issues/362#issuecomment-356939766

**Comment by c-cube** [comment]
I get a `No rule found for _build/default/src/core/.merlin` that I don't get without the dependency.

**Comment by rgrinberg** [comment]
Do you have a branch where I can try this out? I can't reproduce this with a simple example locally.

**Comment by c-cube** [comment]
https://github.com/c-cube/ocaml-containers/tree/wip-qtest-dune

**Comment by rgrinberg** [comment]
I can't reproduce. The tests seem to run fine for me. There's a weird failure when qtest is absent though.

Also, why do you have the `(fallback)` there? I don't think you need it here, and if you want to check in the generate the qtests file, then you should wait for promotion (in beta 17).

**Comment by c-cube** [comment]
I don't want to check in the file, rather I'd like to re-generate it every time.

On my computer with 4.05.0+flambda and 1.0+beta16, on a clean clone of containers on this branch, I get the same failure with `make` (the lib compiles fine, but then the test generation fails).

**Comment by c-cube** [comment]
@rgrinberg have you tried on a switch where merlin is installed?

I get:

```
opam sw create 4.05.0 --switch=foo
eval `opam env`
opam install merlin sequence gen qtest qcheck result
make
```
and that leads to failure (I suppose it needs merlin to be installed to generate the .merlin files)

**Comment by Gbury** [comment]
I can also reproduce on my machine (see https://pastebin.com/nEKXd2zZ).

**Comment by rgrinberg** [comment]
> and that leads to failure (I suppose it needs merlin to be installed to generate the .merlin files)

.merlin files are generated regardless of the presence of merlin

Sorry, I still can't reproduce (this time I tried on different switches). Which version of jbuilder are you using?

Btw the tests do fail for me:

```
   run_qtest alias qtest/runtest (exit 1)
(cd _build/default/qtest && ./run_qtest.exe)
random seed: 337674958
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
Failure: >>../src/unix/CCUnix.ml:248

expected: 10000 but got: 9691
///////////////////////////////////////////////////////////////////////////////
Ran: 1042 tests in: 16.60 seconds.
FAILURE
```

**Comment by c-cube** [comment]
This was on beta16, on linux 64 bits.

**Comment by rgrinberg** [comment]
Would you mind trying out beta17?

**Comment by c-cube** [comment]
Seems to be fixed, indeed.

What's your OS and cpu, btw? The test failing is strange, it never happens on my computer…

**Comment by rgrinberg** [comment]
I'm on osx. Ok glad to hear it's working. Can we close?

**Comment by c-cube** [comment]
It's closed! 😄 
I suppose the test comes from a difference in `F_LOCK` between linux and os X, but that's worrying, because I have no simple way of testing on that platform…
