### ISSUE TITLE
Dune doesn't enforce that library used is in the dune file's libraries field

### ISSUE THREAD

**Issue by mimoo** [ocaml/dune#4582]
## Desired Behavior

So I discovered that I could use some module/library A because it was imported by some direct dependency B.
Yet the library A is not defined in the `dune` file (under `libraries`).
This really tripped me, and it was really hard to figure out where that library came from.
Is there a way to have dune enforce that any library called in my code MUST be included in the libraries field of my dune file?

**Comment by mimoo** [comment]
Looks like this does the trick: https://dune.readthedocs.io/en/stable/dune-files.html#implicit-transitive-deps 

but any reason why this is not the default behavior?

**Comment by mimoo** [comment]
It looks like I'm running into unexpected behavior using this. For example, when using `(preprocess (pps (ppx_sexp_conv ...` in the `dune` file I get:

```
Error: The module Ppx_sexp_conv_lib.Sexp is an alias for module Sexplib0.Sexp, which is missing
```

which seems to be a transitive dependency issue, not a direct dependency issue.

**Comment by voodoos** [comment]
Hi @mimoo, I am closing this issue since your problem looks solved. 
Please re-open it if you need more support.
