### ISSUE TITLE
Unique ID's for Errors reported by RPC

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#4635]
This is something that I discussed earlier with @cwong-ocaml and we agreed to address it eventually.
It would be helpful if build errors reported came with a unique ID. This would be useful for the clients to maintain a table keyed by such a ID to efficiently handle incoming add/remove events.

One simple idea would be for dune to generate a GUID for every error. Slightly more efficient would be to generate a GUID for a session and then append an incrementing integer to every error.

cc @jeremiedimino

**Comment by jeremiedimino** [comment]
That makes sense to me. Just note that right now, the systems sends a stream of "add" during the build and them clear all errors at once when the next build starts. So doing something clever at this level might not pay off right now.

/cc @aalekseyev who has been looking at error reporting from `Memo`
