### ISSUE TITLE
[RFC] Mode-specific foreign stubs

### ISSUE THREAD

**Issue by voodoos** [ocaml/dune#4639]
Some projects like the OCaml compiler need to use different C-stubs implementations depending on wheter the target is `byte` or `native`. This can be done by passing different C-flags (like preprocessor flags) depending on the mode or by using different source files.

Dune already allows multiple `foreign_stubs` definitions in the same executable or library stanza:

```lisp
(executable
 (name stubs_exe)
  (foreign_stubs
    (language c)
    (names c_stubs))      ; c_stubs.c
  (foreign_stubs
    (language c)
    (names c_stubs_2)))   ; c_stubs_2.c
```

which is equivalent to using `(names c_stubs c_stubs_2)` if no other field (such as the flags field) differ.

However, as expected, using twice the same source file is forbidden:
```lisp
(executable
 (name stubs_exe)
  (foreign_stubs
    (language c)
    (names c_stubs))
  (foreign_stubs
    (language c)
    (names c_stubs)))
```
```
dune exec ./stubs_exe.exe
File "dune", line 5, characters 11-19:
5 |     (names c_stubs))
               ^^^^^^^^
Error: Multiple sources map to the same object name "c_stubs":
- c_stubs.c
- c_stubs.c
```

We propose to add a field `mode` to the `foreign_stubs` field that would act as a *filter* defaulting to all modes.

- This *optional* field would accept a *single* value: `byte` or `native`
- A `foreign_stubs` field with a mode specified will be ignored ("filtered-out") if the current build mode does not match the one specified in its `mode` field. Thus two different `foreign_stubs` fields for the same source can coexist if they specify different modes.
- Absence of the field means both `byte` and `native`. That makes this proposal backward compatible. That also means that a `foreign_stubs` field without a `mode` field will never be silently filtered-out in favor of another `foreign_stubs` with an explicit `mode` field.

For example, one could feed different flags to the compiler depending on the mode:
```lisp
(executable
 (name stubs_exe)
  (foreign_stubs
    (language c)
    (mode byte)
    (names c_stubs))
  (foreign_stubs
    (language c)
    (mode native)
    (flags :standard -DNATIVE_CODE)
    (names c_stubs)))
```

Or use different sources depending on the mode:
```lisp
(executable
 (name stubs_exe)
  (foreign_stubs
    (language c)
    (mode byte)
    (names c_stubs_byte))
  (foreign_stubs
    (language c)
    (mode native)
    (names c_stubs_native)))
```

Part of this proposal has already been implemented in a [fork of Dune](https://github.com/ocaml-flambda/dune/commits/special_dune) used to compile the flambda backend. Our plan is too carefully upstream and complete these changes.

**Comment by snowleopard** [comment]
@voodoos Good to see this work being cleaned up and upstreamed, thanks for doing this! 

The PR #3935 which implemented the first draft of this idea has a few comments, which you might want to look at. A couple of alternatives were mentioned there, although the design with `(mode byte)` and `(mode native)` described in this RFC still seems best to me.

**Comment by hongchangwu** [comment]
Would love to see this proposal upstreamed in some form. We have a use case where we only want to include stubs in `native` mode. Currently there is no clean way to do this.

**Comment by voodoos** [comment]
We just had a talk with @snowleopard about this RFC.

The implementation introduces a fair amount of complexity and noise in the build directory because for public libraries we systematically need to build targets for object and archive files in both `_byte` and `_native` versions. This is because when a library is built we don't know in advance what link mode will be used when building an executable that depends on it. 

This also means that we will have useless computation happening  when both these targets are actually the same (which happens most of the time when the stubs are not mode-dependent). One way to deal with that and share the computation would be to use symlinks so that object files are not compiled twice when unnecessary. 

Finally the new naming of targets also means that some error messages might refer to awkward name like `my_stubs_byte.o` which could confuse users who do not use the feature.

It feels unreasonable to introduce the target-noise and potential issues with the symlinking to every project using Dune for a feature that probably has a very limited set of concrete use-cases outside of the compiler codebase (according to the number of answers that this RFC received). So we decided that we should hide this feature behind a project-wide option which would be off by default.

@rgrinberg do you have an opinion about these changes ?

**Comment by voodoos** [comment]
I like the idea of having a new category of C sources, that way there is no need for having a on-off configuration switch everywhere to tweak the behaviour of the existing `forein_stubs` field.

But it also feels a bit off to have two fields with very close names that almost do the same thing. Maybe calling it `mode_specific_stub` and making the `mode` subfield non-optional would be clearer.

**Comment by nojb** [comment]
> But it also feels a bit off to have two fields with very close names that almost do the same thing. Maybe calling it `mode_specific_stub` and making the `mode` subfield non-optional would be clearer.

Either that or we could have four different "modes" : `byte` (builds `foo.b.o` from `foo.c`, used for bytecode only) `native` (builds `foo.n.o` from `foo.c`, used for native only) `byte_and_native` (as today, builds `foo.o` from `foo.c`, used both for bytecode and native) and `byte_and_native_separate` (builds `foo.b.o` for bytecode and `foo.n.o` for native from `foo.c`). Of course, better names should be found :)

**Comment by voodoos** [comment]
Or maybe we could specify that in the lib's metadata ?

**Comment by nojb** [comment]
> Or maybe we could specify that in the lib's metadata ?

I hadn't thought about the details, but vaguely I thought this would be recorded somewhere in the Dune meta-data (like `dune-package`).

**Comment by nojb** [comment]
> I don't think it would solve the main issue

Taking a step back, I wonder if this would really solve the motivating use-case at all: in the compiler the runtime is built not only in byte and native versions, but also an "instrumented" and "debug" versions. Is Dune supposed to be able to reproduce all this? If yes, then perhaps we need a more general version of "mode" instead of focusing on just "byte" and "native"...

**Comment by voodoos** [comment]
> Taking a step back, I wonder if this would really solve the motivating use-case at all: in the compiler the runtime is built not only in byte and native versions, but also an "instrumented" and "debug" versions. Is Dune supposed to be able to reproduce all this? If yes, then perhaps we need a more general version of "mode" instead of focusing on just "byte" and "native"...

When we specified it it appeared to be enough for the needs of flambda-backend which might be more restrictive than a full compiler build, @snowleopard can you confirm ?

Also I think in any case the flexibility added to handle both `byte` and `native` modes can be easily extended afterward.

**Comment by snowleopard** [comment]
> When we specified it it appeared to be enough for the needs of flambda-backend which might be more restrictive than a full compiler build, @snowleopard can you confirm ?

My understanding is that two modes were sufficient for building the compiler but it's best to confirm this with the with compiler developers.

@mshinwell Are `byte` and `native` modes sufficient, or do you also need `instrumented` and `debug`?

**Comment by mshinwell** [comment]
For the moment we only need `byte` and `native`.  I would suggest starting with just those.

**Comment by mshinwell** [comment]
(Also I'm not sure it would be correct to conflate `byte`, `native`, `instrumented` and `debug`.  The instrumented and debug runtimes exist in both bytecode and native code versions.)

**Comment by voodoos** [comment]
We decided at the Dune meeting that this should be an experimental feature at first.
