### ISSUE TITLE
Building documentation is broken in some workspaces

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#464]
E.g. in my workspace of janestreet packages:

```
% jbuilder build @doc
Error: External library "core_kernel_test" not found.
-> required by "core/test/src/jbuild (context default)"
Hint: try: jbuilder external-lib-deps --missing @doc
```

While, beta16 generates the documentation as expected. We suspect this is because scopes aren't being taken into account.

**Comment by rgrinberg** [comment]
Actually this is just an issue with the janestreet workspace that uses private dependencies that cross scope lines. E.g. `core_kernel_test` is defined in `core_kernel` but is used within `core`.

**Comment by trefis** [comment]
There's still a problem though: how's one supposed to generate documentation in that situation?

**Comment by rgrinberg** [comment]
A quick fix would be to delete all opam files to share the scopes. Another way would be for us to have an option to only build docs for public libs.

**Comment by trefis** [comment]
Option 2 seems like a must have regardless :)

**Comment by trefis** [comment]
Also, w.r.t option 1:
```
File "async/src/jbuild", line 3, characters 2-21:
Error: You cannot declare items to be installed without adding a <package>.opam file at the root of your project.
To declare elements to be installed as part of package "async", add a "async.opam" file at the root of your project.
```

**Comment by diml** [comment]
I suggest that the `@doc` alias only means the doc for public libraries, and we add `@doc-private` for private libs

**Comment by rgrinberg** [comment]
Jérémie Dimino <notifications@github.com> writes:

> I suggest that the `@doc` alias only means the doc for public libraries, and we add `@doc-private` for private libs

Agreed. This command is also used by people in their opam files to build
the documentation in their package. This change in behavior will make it
work more inline with what they expect.
