### ISSUE TITLE
merlin does not work when a copy rule is involved

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#4642]
Hi,

When using the new merlin-dune protocol, merlin does not work when file copy is involved.

In that case I'm using dune 2.8.5 and merlin 4.2-411.

```
; dune
(rule (copy# m_orig.ml m_copy.ml))

(library
 (modules m_copy)
 (name l)
 (libraries base))
```

If I create `m_orig.ml`, `Ba` does not complete to `Base`.

On the other hand, it works with the following setup without copy:

```
(library
 (modules m_orig)
 (name l)
 (libraries base))
```

cc @voodoos

**Comment by voodoos** [comment]
We do not handle the copy rule in the general case but there is some flexibility in the way Merlin configuration are matched:
If a file is named `module.something.something.ml` only the name before the first dot is taken in consideration. So you could rename `m_orig.ml` to `m_copy.orig.ml` and it should work.

This mechanism is described [here](https://dune.readthedocs.io/en/stable/usage.html?highlight=merlin#non-standard-filenames) in the docs.

**Comment by emillon** [comment]
Thanks for the pointer. If that works for your use case @MisterDA I think we can close this issue.

**Comment by MisterDA** [comment]
It works, thanks.

For reference:
```
(rule
 (targets sandbox.ml)
 (enabled_if
  (= %{os_type} Win32))
 (action
  (copy sandbox.docker.ml sandbox.ml)))
```

This is also somewhat the naming scheme expected by the `select` stanza, yay for consistency!
```
(select winsvc_wrapper.ml from
 (winsvc -> winsvc_wrapper.winsvc.ml)
 (       -> winsvc_wrapper..ml))
 ```

**Comment by voodoos** [comment]
Glad it worked for you. I should add a hint to this behavior in the copy stanza documentation. It would be more useful than where it is right now. Please don't close until I do that :-)
