### ISSUE TITLE
Dune rpc: connection to persistent client stuck indefinitely

### ISSUE THREAD

**Issue by aalekseyev** [ocaml/dune#4658]
We saw some issues with dune rpc getting stuck at startup.
At the very least:

- if there is a stale socket remaining in `_build/rpc/clients/$something/s`, then the code in `external/dune/src/dune_rpc_impl/run.ml`, in function `waiting_clients`, chokes on `Csexp_rpc.Client.connect client` and things get stuck for some reason. Two problems with that:
    - We should accept new clients in parallel with connecting to old ones
    - We should handle errors correctly (seems more important in that case); for that matter, the errors from `accept` seem to be silently ignored, which seems bad
- There's something that causes the stale socket to be often left around even when I'm not doing anything particularly weird, but I couldn't figure out what it is. It could be the way we integrate dune, which is causing it.
I think at least once the client created such a socket even when the server was already started. I don't know if that's deliberate.

cc @cwong-ocaml @rgrinberg

**Comment by rgrinberg** [comment]
The first point should be addressed in #4661.

I've noticed the issue with stale sockets lingering as well, but haven't got the bottom of it yet. I have have an `at_exit` hook to do the cleanup, so I don't know why the socket isn't cleaned up.

**Comment by rgrinberg** [comment]
> We should handle errors correctly (seems more important in that case); for that matter, the errors from accept seem to be silently ignored, which seems bad

Do  you think we should retry on `accept` failures (and log them) then?

**Comment by aalekseyev** [comment]
> Do you think we should retry on `accept` failures (and log them) then?

I don't know if retrying is useful. From the quick look at the man page, the only errors perhaps worth retrying on are EINTR|EAGAIN, but we don't expect to get them since (presumably) our sockets are blocking and because we block the signals.

Logging this error seems important to me, though, because otherwise you just have a stuck process with no explanation.

**Comment by rgrinberg** [comment]
@aalekseyev I believe this now is fixed.
