### ISSUE TITLE
ctypes-foreign not found while installed

### ISSUE THREAD

**Issue by peter-jerry-ye** [ocaml/dune#4796]
## Expected Behavior
Project compiles

## Actual Behavior
> Error: The following libraries are missing in the default context:
> - ctypes-foreign
> Hint: try:
>   opam install ctypes-foreign

## Reproduction

1. `opam install dune ctypes ctypes-foreign`
2. Create files `dune` `ncurses.ml` `hello.ml` according to [Section Example: A Terminal Interface](https://github.com/ocaml/dune/blob/master/HACKING.md#tests)
3. Run `dune build hello.exe`

## Specifications

- Version of `dune` (output of `dune --version`): 2.9.0
- Version of `ocaml` (output of `ocamlc --version`): 4.12.0
- Operating system (distribution and version): Manjaro 21.0.7

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag): [gist](https://gist.github.com/peter-jerry-ye/c22af6207190e0f8493ca6aed019ae19)
- Link to opam list: [gits](https://gist.github.com/peter-jerry-ye/c2e6117d9f86d807224ed95ef30c4de8)

**Comment by jeremiedimino** [comment]
That's expected. `ctypes-foreign` is a virtual package and it installs no library. You can check this as follow:

```
$ opam install ctypes-foreign
[...] # success
$ ls -d $OPAM_SWITCH_PREFIX/lib/ctypes*
/home/dim/.opam/4.12.0/lib/ctypes/
```

As can be seen, there is no `ctypes-foreign` directory in the opam library directory.

**Comment by peter-jerry-ye** [comment]
I modified the library dependency from `ctypes-foreign` to `ctypes` and `ctypes.foreign` and it somehow worked. But I still think the error message is somehow confusing.

**Comment by jeremiedimino** [comment]
Agreed. However there is nothing we can do on the Dune side given that the `ctypes-foreign` package installs nothing. You'd have to follow this up with ctypes developers.
