### ISSUE TITLE
Dune unnecessarily calls git

### ISSUE THREAD

**Issue by Mbodin** [ocaml/dune#4819]
I’m using `esy` as a package manager.
As a consequence, when compiling a dependency, the sources are not compiled within a git repository: only the sources are present.
Dune deals fine with it for the compilation part.
However `dune install` calls `/usr/bin/git describe --always --dirty`, which fails, as the sources are not present within a git repository.

## Expected Behavior
There are no `%%VERSION%%` watermark in the sources, so I would expect dune not calling git during installation.

Alternatively, I would appreciate to have an option to disable the call to git, for instance a way to explicitly specify the value of `%%VERSION%%` to avoid calling git if given (and/or to synchronise esy’s versioning with dune’s).

## Actual Behavior
Dune calls git, which fails as it is not called from a git repository, making the installation of the dependency failing.
From what I understood, the only reason dune would call `git describe` would be to replace `%%VERSION%%` watermarks, but they are not present in the sources).

## Reproduction

- PR with a reproducing test: unfortunately, to reproduce this test, one needs to be outside a git repository, so minimalistic PR are difficult to produce.

Here is a (non-minimal, sorry) way to reproduce the issue:
1. Install esy (for instance `npm install --global esy@latest`)
2. Create a new folder with the following file `package.json`:
```json
{
	"name": "test",
	"esy": {
		"build": "make"
	},
	"dependencies": {
		"@opam/ocamlfind": "1.8.1",
		"coq-prelude": "github:Mbodin/coq-prelude#64788390864332be9f058932cce78699c6924732"
	}
}
```
3. Run `esy` in the folder.

Warning: this will compile Coq and thus take some time.
Once Coq is compiled, the compilation of `coq-prelude` will start.
Compilation works fine (some notation warnings, but that’s all).
Then esy will call `dune install --prefix=<some folder>`, and dune will call git, falling.
Note that dune is called from a esy-specific folder, not from the current folder: adding a local git repository would not change the issue.

## Specifications

- Version of `dune`:  2.9.0
- Version of `ocaml`: 4.9.0
- Operating system: Ubuntu 18.04.1

## Additional information 

- Link to gist with verbose output: https://gist.github.com/Mbodin/135f76890b30412b1e14636a104ab04f (there are some esy outputs in the middle, but most is from dune)
- This issue is not present in `dune` 2.4.

**Comment by rgrinberg** [comment]
> Then esy will call dune install --prefix=<some folder>, and dune will call git, falling.

Why is esy calling dune install anyway? I thought esy reads the .install files generated by dune directly.

**Comment by ejgallego** [comment]
Does that happen if you do `dune subst` before calling `dune install` ? But indeed, this may be a problem in other contexts such as Debian.

**Comment by Mbodin** [comment]
> Does that happen if you do `dune subst` before calling `dune install` ?

The same error happens at the `dune subst` step.

> Why is esy calling dune install anyway? I thought esy reads the .install files generated by dune directly.

Sorry, that’s my fault: I didn’t know that esy was able to do this, so I added the `dune install` command in the installation process. This may solve the issue on my specific usage.
