### ISSUE TITLE
Generalize the *short syntax*

### ISSUE THREAD

**Issue by diml** [ocaml/dune#482]
A few stanzas accept two forms, a long one and a short one. For instance:

```scheme
(rule (copy a b))

(rule
 ((action (copy a b))
  (targets (b))
  (deps    (a))))

(ocamllex (a))

(ocamllex
 ((modules (a))
  (mode promote)))
```

I suggest to generalize it as follow: each stanza can mark a field as **most significant field**. For instance:
- the most significant field of `rule` is `action`
- the most significant field of `ocamllex` is `modules`

then the two following syntax are always accepted:

```scheme
(foo
  (<fields>))

(foo <most-significant-field-value>
 <other-fields>)
```

So that we could write:

```scheme

(rule (copy a b)
 (mode promote))
```

this would avoid having to switch back and forth between the two syntaxes. We could also use that for other stanzas. For instance the most significant field of `library` could be `name`, so that we could write:

```scheme
(library foo
 (public_name blah.foo)
 (modules (a b c)))
```

which is a bit shorted, and I believe as clear.

**Comment by rgrinberg** [comment]
What I don't like about this is that it complicates work for people who would like to write external tools that work with jbuild files. For example, it's no longer so easy extract the `name` field out of a library stanza. It's still a win for things like `(rule ...)` which are just far nicer in the short form, but the other examples aren't as convincing.

Anyway, I'm ambivalent about this so I'd like to see some support from the other maintainers. @dra27 @bobot @Chris00, or @lpw25

**Comment by lpw25** [comment]
This a restricted form of combining named and positional arguments. Such combinations tend to suffer from ambiguities, and this is no exception. For example,
```
(foo (bar baz))
```
is this a `foo` with `(bar baz)` as a value for the most-significant field or a `foo` with a `baz` value for its `bar` field. What if it is the first and then we add a new `baz` field to the `foo` construct?

Of course these ambiguities can be tolerated, but its definitely a trade off.

**Comment by diml** [comment]
> `(foo (bar baz))`

Actually this one is not ambiguous as we have an extra pair of parentheses for the long syntax. But this one is indeed ambiguous:

```scheme
  (foo ((bar baz)))
```

I was thinking to just forbid the short syntax when the value can start with `((`. 

> What I don't like about this is that it complicates work for people who would like to write external tools that work with jbuild files. For example, it's no longer so easy extract the name field out of a library stanza.

That's true. Although we could provide a library for parsing jbuild files, or have a sub-command to expand all short forms into long ones so that you could look at the output.

> It's still a win for things like (rule ...) which are just far nicer in the short form, but the other examples aren't as convincing.

OK, it seems fine to only use this when it's a win, i.e. `rule`, `ocamllex` and `ocamlyacc`.

**Comment by diml** [comment]
We could also imagine changing the syntax for records:

```ocaml
(library
  :name      foo
  :libraries (a b c)
)
```

(inspired by elisp)

**Comment by rgrinberg** [comment]
There seems to be enough controversy here that I don't think we should proceed here. We've already simplified the syntax a bunch by removing parens. Let's wait for more demand from users before doing anything (waiting on @trefis to switch to emacs. Or at least learn elisp)
