### ISSUE TITLE
Grammar: "Creating file dune-project with this contents:"

### ISSUE THREAD

**Issue by aantron** [ocaml/dune#4845]
## Expected Behavior

`dune build` on a project without Dune should print grammatically correct sentences such as

> Creating file dune-project with these contents:

or 

> Creating file dune-project with this content:

## Actual Behavior

```
$ dune runtest --instrument-with bisect_ppx --force    # mostly red herrings on this line, of course
Info: Creating file dune-project with this contents:
| (lang dune 2.9)
```

## Specifications

- Version of `dune` (output of `dune --version`): 2.9.0

**Comment by rgrinberg** [comment]
This is fixed in master because we actually got rid of the automatic dune-project generation completely.
