### ISSUE TITLE
(locks ) in (cram ) seems ignored

### ISSUE THREAD

**Issue by zoggy** [ocaml/dune#4869]
## Expected Behavior

According to https://dune.readthedocs.io/en/stable/tests.html#test-options , using `(locks)` in a `(cram)` stanza is supposed to prevent running two tests using the same lock. In my case:

```
(cram
  (locks /tcp-ports/9999)
)
```

## Actual Behavior

The locks specified in `(locks)` seem ignored, all tests are run in parallel. Or am I missing something ?

## Specifications

- Version of `dune` : 2.9.0
- Version of `ocaml` : 4.12.0
- Operating system (distribution and version): Linux ubuntu 18.04

**Comment by rgrinberg** [comment]
Could you show your project? I'd like to see how the tests are organized.

**Comment by zoggy** [comment]
Here: https://framagit.org/zoggy/ocaml-ldp in the `tests/` directory, each test in one `.t` directory.

**Comment by rgrinberg** [comment]
Seems correct to me. Does adding `(applies_to :whole_subtree)` fix it?

**Comment by rgrinberg** [comment]
Another thing to try: a relative path such as `(locks tcp-ports.9999)`

**Comment by zoggy** [comment]
> Seems correct to me. Does adding `(applies_to :whole_subtree)` fix it?

No.

> Another thing to try: a relative path such as (locks tcp-ports.9999)

Neither.

**Comment by voodoos** [comment]
I will have a look. We were able to fix Merlin tests issue with the new locks feature. However we used [the same stanza to defined all the locked tests](https://github.com/ocaml/merlin/tree/master/tests/test-dirs/server-tests/typer-cache).

Could you try moving the `(locks ...)` fields to a new `cram`stanza in your `tests/` folder's `dune` file ?

```
(cram
  (applies_to :whole_subtree)
  (locks /tcp-ports/9999)
)
```

This might be a workaround while we work on fixing the issue.

**Comment by voodoos** [comment]
After some testing I think this is not an issue with the implementation of cram locks as I am unable to reproduce on simple projects.

@zoggy Looking at your project I think I now understand your error: you put `dune` files **inside** your tests directories `*.t`. This means that these `dune` files are considered as *part of the tests*  and not the host project. Therefore they have no impact on their execution. Test configuration should be outside the `.t` folders which only contain test data and the `run.t` file, as stated in [the documentation](https://dune.readthedocs.io/en/stable/tests.html#directory-tests):

> The name of the test directory must end with .t and must include a run.t as the test script. Everything else in that directory is treated as raw data for the test. It’s not possible to define rules using dune files in such a directory.

**Comment by cwong-ocaml** [comment]
I didn't follow the conversation super closely, but from reading the resolution it strikes me that this sounds like a pretty easy mistake to make. The documentation on this front could be better, but I'm not sure precisely how, or if there's something else we can do.
