### ISSUE TITLE
add `-safe-string` to default flags

### ISSUE THREAD

**Issue by c-cube** [ocaml/dune#487]
With 4.06 out, it's reasonable to have this as a default flag.

**Comment by diml** [comment]
This would only change the behaviour for OCaml < 4.06, is that correct?

**Comment by jpdeplaix** [comment]
Yes, and for ```4.06.x+default-unsafe-string```. For this case I would consider checking for the value of ```default_safe_string``` via ```ocamlc -config``` first.

**Comment by diml** [comment]
Changing the default is likely to break a lot of stuff

**Comment by jpdeplaix** [comment]
So will dune 1.0 :)

**Comment by diml** [comment]
With dune, ocaml support will be a plugin (a builtin one, #461 ). So I guess for such changes, we'll simply bump the plugin version.

**Comment by c-cube** [comment]
People could still add `unsafe-string` to their list of flags, but I'd argue that a package that is not safe-string compliant in 2018 is somewhat broken anyway 😏

**Comment by diml** [comment]
Yh, I agree that it should become the default, but we can't change it silently or it will break a lot of released packages in opam. It seems fine to change the default during the migration to Dune though

**Comment by emillon** [comment]
I suppose we could tie that to `(lang dune 4.0)`, but the overlap between projects supporting ocaml < 4.06 and requiring dune >= 4 (when it's out) is probably very small (and it's possible to set an env node that does this). So I'm closing this one. Thanks!
