### ISSUE TITLE
Looks like `dune exec` does not work on Windows

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#4886]
```
$ echo '(executable (name a))' >dune
$ echo 'let () = print_endline "Hola!"' >a.ml
$ dune exec -- ./a.exe
```
No output is visible and the exit code is 2 (not sure what that means).

@dra27 any ideas by chance?

**Comment by ejgallego** [comment]
Does adding a flush fix this ?

**Comment by nojb** [comment]
False alarm. This was due to a local patch on `Unix.create_process` that was interfering with `dune exec`. Sorry for the noise!
