### ISSUE TITLE
[RPC] Connection Handling

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#4887]
This is a summary of the RPC/LSP/Editor issues discussed in today's meeting.

## Problem

The client (lsp server in this case) is given a set of workspace folders. Each one of these folders can possibly be connected to a live instance of dune. It's not feasible to discover the set of all dune server instances that correspond to these folders because it requires polling every single parent of these folders recursively.

## Solution - Dune Process Registry

This solution is inspired by how things operate inside janestreet (according to @cwong-ocaml @jeremiedimino). The editor is able to query the system for all live instances of dune via the process table. Except that isn't cross platform, so we'll fake the process table with a directory (e.g `$XDG/dune`). Each dune server will be responsible for registering and removing itself in that directory. Editors will now be able to poll this directory and see the list of active dunes and which directories they are managing.

**Comment by jeremiedimino** [comment]
For the directory, I believe it should be `$XDG_RUNTIME_DIR/dune`
