### ISSUE TITLE
`dune subst` output depends on `git` version

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#4911]
Not sure this is something that should be fixed by `dune`, but am opening the issue just to put it out: `dune subst` calls `git describe`, but the number of digits used in the "short hash" depends on the version of `git` as far as I can see. Recently I was bitten by this where the same commit built under Unix (Ubuntu 18.04) and Windows (Cygwin) ended up with different strings substituted.

`git describe` accepts a `--abbrev=<n>` argument to specify how many digits to use in the short hash, but it is not clear that using this is the right thing to do.

**Comment by jberdine** [comment]
Is this covered by https://github.com/ocaml/dune/pull/4857 or does subst use a different path than build-info?

**Comment by nojb** [comment]
> Is this covered by #4857 or does subst use a different path than build-info?

From a quick glance it looks like it is. Thanks for the pointer!
