### ISSUE TITLE
Circular dependency problem with OPAM on Travis

### ISSUE THREAD

**Issue by xguerin** [ocaml/dune#492]
Hello !

I ran into a bit of a problem yesterday while CI'ing a project on Travis. See: https://github.com/ocaml/opam/issues/3213. OPAM is failing on the last installable step complaining about a circular dependency between OMP and jbuilder.

Interestingly I could not reproduce the problem locally. Did you guys run into something similar ?

I've cross-posted that issue on OMP https://github.com/ocaml-ppx/ocaml-migrate-parsetree/issues/38 for good measure.

x

**Comment by Chris00** [comment]
See https://github.com/ocaml/dune/issues/483

**Comment by rgrinberg** [comment]
The workaround is posted in opam-repository and in dune so the problem should be addressed shortly. Sorry for the inconvenience.
