### ISSUE TITLE
%{ext_dll} is .so on macos

### ISSUE THREAD

**Issue by hcarty** [ocaml/dune#4948]
## Expected Behavior

`%{ext_dll}` would expand to `.dylib` on macos as that is the extension for dynamically libraries on the OS.

## Actual Behavior

`%{ext_dll}` expands to `.so` on macos.

## Specifications

- Version of `dune` (output of `dune --version`): 2.9.1
- Version of `ocaml` (output of `ocamlc --version`): 4.13.0
- Operating system (distribution and version): macos 11.6

**Comment by nojb** [comment]
`dune` just inherits this extension from the compiler, so there is not much we can do on our side. For a discussion on the compiler side see the thread starting at https://github.com/ocaml/ocaml/pull/988#issuecomment-269288136

**Comment by hcarty** [comment]
Ah, that's unfortunate. Looks like the `so` vs `dylib` change was left open at the end of that conversation.

Should I close this issue in that case? I can use hard-coded workarounds for now. Unfortunately, as far as I understand that means I need to copy+paste every rule which needs to refer to a dynamic library and include an `enabled_if` stanza.

**Comment by nojb** [comment]
> I can use hard-coded workarounds for now. Unfortunately, as far as I understand that means I need to copy+paste every rule which needs to refer to a dynamic library and include an `enabled_if` stanza.

What kind of rule are you writing? If you need to link with a dynamic library you should be able to use a `-l<name>` flag which doesn't need the extension. But yes, otherwise I think that is pretty much the situation right now...

**Comment by hcarty** [comment]
> What kind of rule are you writing? If you need to link with a dynamic library you should be able to use a -l<name> flag which doesn't need the extension.

You are completely correct, and to compile an executable I do that. However, on macos the C library I'm working with, a game engine called orx, has its install/search path set as `@executable_path/liborx.dylib`. If you're not familiar with `@executable_path` - I just learned about it recently - it means that an executable linked against that dynamic library should search at runtime for the library in the same directory as the executable.

Linking an executable against `liborx.dylib` works as expected by setting `-L` and `-l` appropriately. In order the run the executable, though, the library needs to be copied to sit alongside the executable. Or, after linking, use macos's `install_name_tool` to change the library search path.

**Comment by hcarty** [comment]
Thanks @nojb!
