### ISSUE TITLE
ignore ppx runtime dependencies when implicit transitive deps = false

### ISSUE THREAD

**Issue by c-cube** [ocaml/dune#4963]
## Desired Behavior

When `(implicit_transitive_deps false)` is specified, it would be good if dependencies required by ppx rewriters were excluded from it. For example, `ppx_deriving.runtime` should be left implicit even in this case, because in all likelihood it's only depended upon by automatically generated code, for which the dependency is already explicit in `(pps …)`.

related: #2733

**Comment by rgrinberg** [comment]
Could you explain the problem a little more? Why should code generators rely on transitive dependencies. Why can't they specify the full list of deps they intend to use in `ppx_runtime_deps`?
