### ISSUE TITLE
Consider global configuration file when ran by opam

### ISSUE THREAD

**Issue by Lupus** [ocaml/dune#4979]
It takes a lot of time if CI pipeline is creating local switch for the build step, typical approach for improving the situation is caching. One can just .tar.gz whole _opam dir and extract it later as one way of doing this. As some work is happening on distributed cache support (#4850) it would be really beneficial to be able to leverage distributed dune cache during opam switch builds. According to discussion in #4851 currently dune ignores configuration file thus preventing the user from enabling dune cache for opam switch builds.

**Comment by rgrinberg** [comment]
I question the main request of this ticket:

> Consider global configuration file when ran by opam

I think it's fundamentally a bad idea to have released packages depend on some local configuration a user has.

See this issue https://github.com/ocaml/opam-repository/issues/19150 for a plan to enable the cache for switches in a saner way. As a workaround for now, you can set the environment for your local switch to enable the cache and then recompile everything.

**Comment by jeremiedimino** [comment]
When invoked by opam, Dune has to adopt a fully reproducible mode. Some options are safe to set in this mode and some are not. Enabling the shared cache is a safe option. Currently the global config file allows to set both kinds of options, that's the reason we don't read it when run from opam.
