### ISSUE TITLE
Unsuccessful tests run invocation.

### ISSUE THREAD

**Issue by lubegasimon** [ocaml/dune#4983]
## Expected Behavior
Tests run should successful complete.

## Actual Behavior
Tests fail — https://gist.github.com/lubegasimon/8c1973e12c9522ae1ff06b0824ef6f99

## Reproduction
Run `make test` on `Dune`’s main branch

## Specifications

- Version of `dune` (output of `dune --version`): 2.8.5
- Version of `ocaml` (output of `ocamlc --version`): 4.10.0, as a result of `make dev-switch` [command](https://github.com/ocaml/dune/blob/main/HACKING.md#create-an-opam-switch-with-the-required-dependencies)
- Operating system (distribution and version): macOS Big Sur, version 11.6

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag): https://gist.github.com/lubegasimon/62688ccc7e46862d92e2d56990925337

**Comment by voodoos** [comment]
Does this still happen at the tip of the `main` branch ?

**Comment by ejgallego** [comment]
Coq failures due to the need to use Coq >= 8.14 for the `main` branch, sorry for that.

**Comment by rgrinberg** [comment]
Should be fixed. Please re-open if it's not.
