### ISSUE TITLE
unhelpful error message when mixing executable & library stanzas with same-named library.ml file

### ISSUE THREAD

**Issue by rntz** [ocaml/dune#501]
In a fresh, empty directory, do the following:

```
$ touch helloworld.ml
$ touch mylib.ml
$ echo '(jbuild_version 1)' > jbuild
$ echo '(executable ((name helloworld)))` >> jbuild
$ echo '(library ((name mylib)))' >> jbuild
$ jbuilder build
Multiple rules generated for _build/default/mylib.o:
- <internal location>
- <internal location>
```

I don't understand why this causes an error. If there is a good reason, the error message should explain what the reason is.

This example is minimal, but I ran into this bug while trying to set up a project to use Jbuilder and attempting to follow the quickstart instructions.

**Comment by rgrinberg** [comment]
If you define a library and executable stanza in the same directory, you will need to dune which source files belong to which stanza. You can do that by providing the `(modules (..))` field both stanzas. So for example `(modules (helloworld))` would go in your `executable` stanza while `(modules (mylib))` would go into your library stanza.

We are aware of the bad error message in this situation and we'd like to fix it.

**Comment by diml** [comment]
the error message has been improved in beta19
