### ISSUE TITLE
Installation of internal libraries with the same name isn't handled correctly

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#502]
The case where libraries with the same internal name and a different public name doesn't seem to be handled correctly. Even when they exist in different scopes. I have a real test case, but the bug should be evident from reading this bit of code

https://github.com/ocaml/dune/blob/master/src/lib_db.ml#L260-L264

It's not possible to have a map from private names to installable libraries that includes *all* installable libraries.

**Comment by diml** [comment]
Ah indeed. I think the keys are never used, so we can probably use whatever unique key we want.
