### ISSUE TITLE
Error from `ar` when compiling unwrapped library in empty directory

### ISSUE THREAD

**Issue by MiloDavis** [ocaml/dune#504]
I hit the following error when I deleted the last file in a library:

```
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
File "_none_", line 1:
Error: Error while creating the library bug_report.a
```

The jbuild file contains:
```
(jbuild_version 1)

(library
 ((name bug_report)
  (wrapped false)))
```

Self contained code to reproduce:
```
mkdir report
cd report
cat >jbuild << EOL
(jbuild_version 1)

(library
 ((name bug_report)
  (wrapped false)))
EOL
jbuilder build bug_report.a
```

**Comment by rgrinberg** [comment]
Which version of OCaml are you using?

**Comment by MiloDavis** [comment]
OCaml 4.04.2 with Dune/Jbuilder 1.0+beta17

**Comment by rgrinberg** [comment]
This is on OSX, right?

**Comment by MiloDavis** [comment]
Yes.

**Comment by rgrinberg** [comment]
I recall this was an issue with OSX ar. But I also think that there wa a
workaround for it in 4.03.0 so I'm surprised you're running into this
issue. For now, you can just add an empty file to workaround this, and
see if you can reproduce this with a later version of OCaml. Perhaps
we'll need some sort of OSX workaround in dune as well.

**Comment by diml** [comment]
What about just making this a Dune error? I.e.:

```
File ...
Error: this library is unwrapped and has no module. This is not supported.
```

**Comment by rgrinberg** [comment]
Jérémie Dimino <notifications@github.com> writes:

> What about just making this a Dune error? I.e.:
>
> ```
> File ...
> Error: this library is unwrapped and has no module. This is not supported.
> ```

It's acceptable if we don't break anyone's code. Compiling such an empty
library does work in 4.05.0 for me for example.

**Comment by MiloDavis** [comment]
I'd be fine with a standard error. It was definitely a mistake for me, it was just that I wasn't expecting the error to come from `ar`, rather from inside of dune.
