### ISSUE TITLE
Install directories

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#5059]
Since @snowleopard added directory targets, it would be cool if they were truly first class and available as install targets. So for example:

```
(install
 (section ..)
 (directories foo))
```

This would also require traversing the contents of `foo` and including it in the `.install` file.

**Comment by rgrinberg** [comment]
@snowleopard if I'm doing this right, implementing this feature will require a new action. That's because we need the rule that generates `package.install` to read the contents of the directory.

**Comment by snowleopard** [comment]
> That's because we need the rule that generates `package.install` to read the contents of the directory.

@rgrinberg I don't understand. Why can't that rule depend on the directory? Then it would be able to traverse it and do whatever it likes with the contents.

**Comment by snowleopard** [comment]
Oh, maybe by "new action" you mean a new action in the Dune action language?

**Comment by rgrinberg** [comment]
Yes, that's what I meant. I'll put up my PR that should make it easier to discuss this.
