### ISSUE TITLE
optional compilation

### ISSUE THREAD

**Issue by vbmithr** [ocaml/dune#51]
```
[vb@haramis ~/code/ocaml-websocket]% jbuilder external-lib-deps --missing @install
Error: The following required libraries are missing in the default context:
- cryptokit (optional)
```

I am using the following stanza:

```
(library
 ((name rng_cryptokit)
  (public_name websocket.rng_cryptokit)
  (modules (rng_cryptokit))
  (optional)
  (libraries (rng cryptokit))))
```

Why jbuilder insists on building this if it is flagged optional and that cryptokit is not installed?

**Comment by diml** [comment]
Maybe it's required by a non-optional library or an executable that is to be installed?

**Comment by vbmithr** [comment]
No, not that I can see.
Maybe you can have a look and try to compile : https://github.com/vbmithr/ocaml-websocket/tree/jbuilder

**Comment by diml** [comment]
Can you try putting the optional libraries in separate directories? It might have to do with the merging of the .merlin

**Comment by vbmithr** [comment]
This works. But still a bug.

**Comment by diml** [comment]
Indeed, I documented it. I'd say it's low-priority

**Comment by diml** [comment]
I head that merlin should eventually read flags from .cmt[i] files directly, which will solve this issue, so it's probably best to just wait for now
