### ISSUE TITLE
Dune is watching _build/install/default/bin

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml/dune#5153]
While debugging some inotify issue, I noticed that Dune is currently watching `_build/install/default/bin`. Dune shouldn't be watching the build directory given that user are not supposed to modify things there.

**Comment by rgrinberg** [comment]
@snowleopard isn't this impossible? We have a check that makes sure that no build dirs are watched.

**Comment by snowleopard** [comment]
We do have a check in `Fs_memo` but I suppose it's possible to set up a watch without using `Fs_memo`'s API.
