### ISSUE TITLE
Dune watch keeps rebuilding project when using main branch

### ISSUE THREAD

**Issue by voodoos** [ocaml/dune#5170]
## Actual Behavior

Dune keeps restarting the build in watch mode even with no obvious file change.

![Screen Recording 2021-11-15 at 10 58 33](https://user-images.githubusercontent.com/5031221/141795016-2b6c5c2d-a827-4780-8276-8b33fe842cb6.gif)

I have a [log here](https://pastebin.com/gbyby2FQ) with a few loops.

## Reproduction

- Pull dune `main` (701b5de1ae0299a8634e464746c1d173534e4151)
- Run `make dev` 
- Run `./dune.exe build -w`

On my machine this will start an endless loop of restarting builds.

## Specifications

- Version of `dune` (output of `dune --version`): 701b5de1ae0299a8634e464746c1d173534e4151
- Version of `ocaml` (output of `ocamlc --version`):  4.12.0
- Operating system (distribution and version): MacOS Monterey (x86_64)

**Comment by snowleopard** [comment]
I believe #5203 should fix this issue.

**Comment by snowleopard** [comment]
@voodoos Could you check if the issue is fixed for you?

**Comment by voodoos** [comment]
> @voodoos Could you check if the issue is fixed for you in `main`?

It is ! What an amazing feeling to be able to use watch-mode again, thanks 🙂

**Comment by snowleopard** [comment]
Awesome! :tada:
