### ISSUE TITLE
define inline tests dependencies

### ISSUE THREAD

**Issue by JoAllg** [ocaml/dune#5183]
I am writing inline expectation tests that need to read test-files located in a subdirectory. I specified this dependency in the dune file:
````
(library
 (name test)
 (libraries ...)
 (inline_tests (deps (universe))) ; or (deps glob_files ./test-files/) 
 (preprocess (pps ppx_jane))
) 
````

Now I just noticed, that both `(universe)` and `(deps glob_files ...)` do not seem to work. as I need to run `dune build` before `dune runtest`, in order for the test-files to be recognized. ("No such file or directory" exception otherwise).

How do I properly define the dependencies in order for dune to include them with `dune runtest` and also updating them when modified?

**Comment by jeremiedimino** [comment]
That should definitely work. Could you give us a reproduction case? Or even better, submit a PR with a cram test as described [here](https://github.com/ocaml/dune/blob/main/HACKING.md#tests). Thanks

**Comment by JoAllg** [comment]
Yes, please have a look at https://github.com/JoAllg/dune_runtest_deps

The specific error I get is:
````
inline_test_runner_test alias runtest (exit 2)
(cd _build/default && .test.inline-tests/inline_test_runner_test.exe inline-test-runner test -source-tree-root . -diff-cmd -)
Fatal error: exception (Sys_error "./sub/file.txt: No such file or directory")
Raised by primitive operation at Stdlib.open_in_gen in file "stdlib.ml", line 405, characters 28-54
Called from Stdlib.open_in in file "stdlib.ml" (inlined), line 410, characters 2-45
Called from Test in file "test.ml", line 2, characters 18-42
````
Expected:
````
inline_test_runner_test alias runtest
Hello World
````

(there is also a first try on a cram test in the folder `inline-test-deps`. I couldn't get the `make dev-switch` work on my system yet and didnt want to push a cram test of that I do not know if it works)

**Comment by jeremiedimino** [comment]
> (there is also a first try on a cram test in the folder inline-test-deps. I couldn't get the make dev-switch work on my system yet and didnt want to push a cram test of that I do not know if it works)

You can run a particular cram test by typing `dune build @<name-of-the-test>`. For instance, if the test was in a file `foo.t`, you could type `dune build @foo`. Then you wouldn't need all of the things `make dev-switch` installs. You would only need what is required by your test, which might already have installed.

Do you mind giving that another try? A cram test would make the issue a lot easier for us to understand and debug, as this is what we work with on a daily basis.

**Comment by rgrinberg** [comment]
The dependency `(universe)` is wrong here because it is not enough to tell dune that `sub/` must be copied to the build directory.

The dependency `(glob_files sub/)` is wrong because it omits the part that must match the filename. It should be `(glob_files sub/*)` or event `(glob_files sub/*.txt)`.
