### ISSUE TITLE
convention for the toplevel module of a library

### ISSUE THREAD

**Issue by c-cube** [ocaml/dune#520]
I really like the way dune makes it easy to "pack" modules together in a library `foo` using module aliases in `Foo` to expose or hide them. However, whenever I want to rename a libray (or worse, a whole package with many sublibraries) I have to update the `jbuild` files (understandable) but also these main module files.

Would it make sense to imitate other languages (python, rust) and have a convention for the entry point of a library to be `lib.ml` or `__lib__.ml` or something like that? It would be renamed during the build anyway.

**Comment by diml** [comment]
I think we could start with this as a plugin to get a bit more experience and feedback. I'd rather not add too many rules like this eagerly.

BTW, if you want to play with the idea, adding the following should be enough:

```scheme
(rule (copy# __init__.ml foo.ml))
```

One problem is that Dune might still pick up `__init__.ml` as a module of the library, however we can make Dune ignore this file given that the filename is not a valid module name.

**Comment by UnixJunkie** [comment]
I would like that dune only needs a jbuild file and that an ocaml project has not to be cluttered with specific other files so that it compiles with dune.
Having an _optional_ toplevel lib.ml seems fine.
I don't understand why it should be named specifically with a strange naming convention that might break the build for other tools.

**Comment by c-cube** [comment]
It's already optional to have a `foo.ml` module in library `foo`. An a dune project will already not build with another tool without intervention (because of all the hidden renamings and `-open`magic).

**Comment by rgrinberg** [comment]
One deficiency of this __init__.ml convention is that it will not work for multiple libraries defined in the same directory. So we'll still need the old convention for those libs. That seems inadequate.

**Comment by c-cube** [comment]
Oh, you can have multiple libs in one directory? But you can't have one lib in multiple nested directories? I find this kind of surprising. Anyway, this looks like a bad fit for dune, closing.

**Comment by rgrinberg** [comment]
You can have the latter as well with `copy_files`.
