### ISSUE TITLE
Test programs cannot have the same name

### ISSUE THREAD

**Issue by camlspotter** [ocaml/dune#525]
I have put many software packages built by dune.  Many of them have test programs named `test`, compiled from `test.ml`.  For example,

```
(executable
 ((name test)
  (libraries (camlimages.core camlimages.gif camlimages.jpeg camlimages.png camlimages.tiff camlimages.xpm camlimages.graphics camlimages.freetype))))
```

Once they are put under one `jbuild-workspace`, it seems to me that dune does not like to have more than one executable with the same name:

```shell
$ jbuilder build
Entering directory '/home/myhome'
Multiple rules generated for _build/default/camlimages/test/test.o
```

I guess this is because there is another test program named `test` in another project.

Since these test binaries are not to be installed, they should be able to be compiled even if they share the same name.  Or is there a special stanza for test programs other than `executable` nor `executables`?

**Comment by rgrinberg** [comment]
Could you post the full jbuild file in camlimages/test? Dune indeed lets you define non-installed executables with the same name as long as they are in different directories.

**Comment by camlspotter** [comment]
It turned out that the error was caused by multiple `executable` rules in one directory, and it does not relate with an executable of the same name in another directory:

```
 (executable
  ((name test)
   (libraries (camlimages.core camlimages.gif camlimages.jpeg camlimages.png camlimages.tiff camlimages.xpm camlimages.graphics camlimages.freetype))))
 
(executable
 ((name test2)
  (libraries (camlimages.core camlimages.gif camlimages.jpeg camlimages.png camlimages.tiff camlimages.xpm camlimages.graphics))))

; BTW, I cannot use executable*s* here since the used libraries are slightly different.
```

The error was gone once I have added `(modules (test))` and `(modules (test2))` to the rules.

I now understand that without `(modules ..)`, all the modules found in the directory are used to build an executable for `(executable ..)` but it is only stated at the explanation of `(modules ..)` of `(library ..)`.  To me, it would be great if this behaviour would be explained in `(executable ..)` explicitly, since the behaviour is different from `(executable*s* ..)`.
