### ISSUE TITLE
jbuilder --display is hard to figure out

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#526]
The command line doesnt tell you what the options are:

```
$ jbuilder --display
jbuilder: option `--display' needs an argument
Usage: jbuilder COMMAND ...
Try `jbuilder --help' for more information.
```

But then `--help` points to a non-existent manual page:

```
       --display=MODE
           Control the display mode of Jbuilder. See dune-config(5) for more
           details.
```

**Comment by diml** [comment]
The man page exist for me:

```
$ man -w dune-config
/usr/local/home/jdimino/opam-root/4.05.0/man/man5/dune-config.5
```

You can also do `jbuilder help config`, would it be clearer to point to that instead?

**Comment by diml** [comment]
I think we can also improve the error message. Though it seems that Cmdliner would be the right place to do this, since we are giving all the possible values to cmdliner.
