### ISSUE TITLE
[3.0 opam failures] Library "result" not found

### ISSUE THREAD

**Issue by voodoos** [ocaml/dune#5263]
Log from `rpclib.8.1.1` run:

```
#=== ERROR while compiling rpclib.8.1.1 =======================================#
# context              2.1.0 | linux/x86_64 | ocaml-base-compiler.4.12.1 | file:///home/opam/opam-repository
# path                 ~/.opam/4.12+dune3/.opam-switch/build/rpclib.8.1.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p rpclib -j 31
# exit-code            1
# env-file             ~/.opam/log/rpclib-19-e1a553.env
# output-file          ~/.opam/log/rpclib-19-e1a553.out
### output ###
# File "src/lib/dune", line 11, characters 12-18:
# 11 |  (libraries result base64 rresult)
#                  ^^^^^^
# Error: Library "result" not found.
# -> required by library "rpclib.core" in _build/default/src/lib
# -> required by _build/default/META.rpclib
# -> required by _build/install/default/lib/rpclib/META
# -> required by _build/default/rpclib.install
# -> required by alias install

- File "src/lib/dune", line 11, characters 12-18:
- 11 |  (libraries result base64 rresult)
-                  ^^^^^^
- Error: Library "result" not found.
- -> required by library "rpclib.core" in _build/default/src/lib
- -> required by _build/default/META.rpclib
- -> required by _build/install/default/lib/rpclib/META
- -> required by _build/default/rpclib.install
- -> required by alias install
```

Impacted packages: 
- [rpclib.8.1.1 and ppx_deriving_rpc.8.1.1](https://github.com/mirage/ocaml-rpc) [(log)](http://check.ocamllabs.io:8083/log/1638379752-2572516bdd86475ad6b1d39a03efd52eee94f81f/4.12+dune3/bad/rpclib.8.1.1)
- [dispatch.0.5.0](https://github.com/inhabitedtype/ocaml-dispatch) [(log)](http://check.ocamllabs.io:8083/log/1638379752-2572516bdd86475ad6b1d39a03efd52eee94f81f/4.12+dune3/bad/dispatch.0.5.0)
- [lsp.1.9.1](https://github.com/ocaml/ocaml-lsp) [(log)](http://check.ocamllabs.io:8083/log/1638379752-2572516bdd86475ad6b1d39a03efd52eee94f81f/4.12+dune3/bad/lsp.1.9.1)

[Full report.](http://check.ocamllabs.io:8083/?comp=4.12&comp=4.12%2Bdune3&available=4.12&available=4.12%2Bdune3&show-failures-only=true&show-diff-only=true&show-latest-only=true&sort-by-revdeps=true&maintainers=&logsearch=&logsearch_comp=4.12)

Parent issue: #5257

**Comment by nojb** [comment]
xref https://github.com/ocaml/dune/pull/4946#issuecomment-928031670

**Comment by emillon** [comment]
Done in https://github.com/ocaml/opam-repository/pull/20443
