### ISSUE TITLE
[3.0 opam failures] gcc: ubpf.h: No such file or directory

### ISSUE THREAD

**Issue by voodoos** [ocaml/dune#5266]
Impacted package: [ubpf.0.1](https://github.com/ahrefs/ocaml-ubpf)

```
#=== ERROR while compiling ubpf.0.1 ===========================================#
# context              2.1.0 | linux/x86_64 | ocaml-base-compiler.4.12.1 | file:///home/opam/opam-repository
# path                 ~/.opam/4.12+dune3/.opam-switch/build/ubpf.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ubpf -j 31
# exit-code            1
# env-file             ~/.opam/log/ubpf-18-b908b6.env
# output-file          ~/.opam/log/ubpf-18-b908b6.out
### output ###
# File "src/dune", line 6, characters 24-27:
# 6 |   (cxx_names ubpf_stubs bpf)
#                             ^^^
# (cd _build/default/src && /usr/bin/gcc -O2 -fno-strict-aliasing -fwrapv -fPIC -std=c++11 -Iubpf_c/ubpf/vm/inc -g -I /home/opam/.opam/4.12+dune3/lib/ocaml -I ubpf_c -o bpf.o -c bpf.cpp)
# bpf.cpp:7:10: fatal error: ubpf.h: No such file or directory
#     7 | #include "ubpf.h"
#       |          ^~~~~~~~
# compilation terminated.
# (cd _build/default/src/ubpf_c/ubpf/vm && /usr/bin/make)
# cc -Wall -Werror -Iinc -O2 -g -fPIC   -c -o ubpf_vm.o ubpf_vm.c
# cc -Wall -Werror -Iinc -O2 -g -fPIC   -c -o ubpf_jit_x86_64.o ubpf_jit_x86_64.c
# cc -Wall -Werror -Iinc -O2 -g -fPIC   -c -o ubpf_loader.o ubpf_loader.c
# ar rc libubpf.a ubpf_vm.o ubpf_jit_x86_64.o ubpf_loader.o
# gcc -shared ubpf_vm.o ubpf_jit_x86_64.o ubpf_loader.o -o dllubpf.so
# cc -Wall -Werror -Iinc -O2 -g -fPIC   -c -o test.o test.c
# cc   test.o libubpf.a  -lm -o test
```

[Full log](http://check.ocamllabs.io:8083/log/1638379752-2572516bdd86475ad6b1d39a03efd52eee94f81f/4.12+dune3/bad/ubpf.0.1)

Parent issue: #5257

**Comment by jeremiedimino** [comment]
We looked into it with @kit-ty-kate. The breakage seems to be due a different execution order of the rules. With the <3.0 order, the ubpf.h files happened to be there because a rule that depended on it happened to have been fired before. This was a bit fragile and it seems better to properly declare the dependency on the header files, which can be done with `foreign_stubs`.

It's a single project, so let's not change Dune. Instead, let's make a PR to the upstream project to switch to `foreign_stubs` and properly declare the dependency on the header files.

**Comment by jeremiedimino** [comment]
Todo to unlock 3.0.0: notify upstream. To fix upstream: switch to using foreign_stubs

**Comment by snowleopard** [comment]
I'll try to have a look and put together a PR if it's not too difficult.

**Comment by rgrinberg** [comment]
@snowleopard I ended up doing this

https://github.com/ahrefs/ocaml-ubpf/pull/1

**Comment by snowleopard** [comment]
@rgrinberg Awesome, thank you!
