### ISSUE TITLE
`jbuilder exec ./ls` executes `/bin/ls`

### ISSUE THREAD

**Issue by camlspotter** [ocaml/dune#527]
It's a small thing, but with 1.0+beta16,

```
$ jbuilder exec ./ls
```

executes `/bin/ls` in the jbuilder root directory.  I guess this is not intended behaviour of `jbuilder exec`.

**Comment by diml** [comment]
I just tried this with master and I can't reproduce the error:

```
$ jbuilder exec ./ls
Error: Program "./ls" not found!
```

I think this problem was fixed at some point since beta16
