### ISSUE TITLE
Exception for invalid module name uncaught

### ISSUE THREAD

**Issue by yannl35133** [ocaml/dune#5273]
### Expected Behavior
Not crashing

### Actual Behavior
```
Internal error, please report upstream including the contents of _build/log.
Description:
  ("Invalid Module_name.t", { s = "03" })
Raised at Stdune__code_error.raise in file "src/stdune/code_error.ml", line
  9, characters 30-62
[...]
Called from Fiber.Execution_context.safe_run_k in file "src/fiber/fiber.ml",
  line 130, characters 8-11

I must not crash.  Uncertainty is the mind-killer. Exceptions are the
little-death that brings total obliteration.  I will fully express my cases. 
Execution will pass over me and through me.  And when it has gone past, I
will unwind the stack along its path.  Where the cases are handled there will
be nothing.  Only I will remain.
```

### Reproduction
```bash
mkdir test
dune init library 03
dune build
```

- PR with a reproducing test: #5274
### Specifications

- Version of `dune` (output of `dune --version`): 2.9.1
- Version of `ocaml` (output of `ocamlc --version`): (doubts this has an influence) 4.13.1
- Operating system (distribution and version): Manjaro Linux

**Comment by voodoos** [comment]
Thank you for your report. I was able to reproduce the issue with both Dune 2.9.1 and dev version.
Your test was correct, it is just that you did not promote the complete error message.

**Comment by emillon** [comment]
Hi,
Here's the output today (dune 3.3.1):

```
+|  File "dune", line 2, characters 7-9:
+|  2 |  (name 03))
+|             ^^
+|  Error: "03" is an invalid module name.
+|  Module names must be non-empty and composed only of the following characters:
+|  'A'..'Z', 'a'..'z', '_', ''' or '0'..'9'.
+|  Hint: 03 would be a correct module name
+|  [1]
```

That's better (technically this issue can be closed) but the hint is wrong. I'll open a PR for it.
