### ISSUE TITLE
`jbuilder utop` has a confusing error message if no jbuild file is present in the current directory

### ISSUE THREAD

**Issue by samoht** [ocaml/dune#528]
For instance, from the root of project:

```
$ jbuilder utop .
Don't know how to build .utop/utop.exe
```

But `jbuilder utop src/` will work fine (when `src/jbuild` exists).

**Comment by ELLIOTTCABLE** [comment]
Ah, this just bit me too — came here to report, but looks like I got beat to it.

It'd be best if we could *specify* which things to load, or have it load everything in child directories by default?

**Comment by rgrinberg** [comment]
@ELLIOTTCABLE that's how it works now. Therefore, this issue can be closed.
