### ISSUE TITLE
dune-private-libs downgrade build error on arith_status.cmi

### ISSUE THREAD

**Issue by sim642** [ocaml/dune#5280]
I've set up a lower-bounds like CI job (on GitHub Actions) for my own project using 0install and by now I've noticed it multiple times (although seemingly randomly) failing while downgrading dune-private-libs from 2.9.1 to 2.8.0:
```
#=== ERROR while compiling dune-private-libs.2.8.0 ============================#
# context     2.1.1 | macos/x86_64 | ocaml-base-compiler.4.12.0 | git+https://github.com/ocaml/opam-repository.git
# path        ~/work/analyzer/analyzer/_opam/.opam-switch/build/dune-private-libs.2.8.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p dune-private-libs -j 3 @install
# exit-code   1
# env-file    ~/.opam/log/dune-private-libs-32075-2c04dc.env
# output-file ~/.opam/log/dune-private-libs-32075-2c04dc.out
### output ###
# Error: stat:
# /Users/runner/work/analyzer/analyzer/_opam/lib/ocaml/arith_status.cmi: No
# such file or directory
```
CI log: https://github.com/goblint/analyzer/runs/4452001137?check_suite_focus=true#step:8:5438.
Copy of log file: [2_lower-bounds (macos-latest, 4.12.0, downgrade).txt](https://github.com/ocaml/dune/files/7674875/2_lower-bounds.macos-latest.4.12.0.downgrade.txt).

I could probably fix my random CI failures by adding a dune-site lower bound of 2.9.1 to my dependencies (I already have a dune lower bound of 2.9.1 to fix various problems with dune-site) but I wanted to open this issue in case there's something deeper going on, because I couldn't find note of any changes or issues addressing anything similar.

Weirdly, the `arith_status.cmi` file it's failing on isn't even part of dune but num (which in the same downgrade attempt was downgraded from 1.4 to 1.0, but its changes also don't seem to mention anything related), so I'm confused why it's showing up during dune-private-libs build.

I saw that dune-site depends on the exact corresponding version of dune-private-libs, but their versions constraints are independent of dune itself, so the downgrade process is allowing to downgrade the former two to 2.8.0 while keeping dune itself at 2.9.1. Is this intended or should the versions of dune-site and dune-private-libs be coupled to dune itself as well? Seems a bit suspicious that the version constraints allow dune-site 2.8.0 to be used with dune 2.9.1, which contains dune-site related fixes.

## Specifications

- Version of `dune` (output of `dune --version`): 2.9.1
- Version of `ocaml` (output of `ocamlc --version`): 4.12.0
- Operating system (distribution and version): MacOS

**Comment by sim642** [comment]
I've now seen other very similar failures the dune-private-libs downgrade does work, but then dune-site fails to:
```
#=== ERROR while compiling dune-site.2.8.0 ====================================#
# context     2.1.2 | macos/x86_64 | ocaml-base-compiler.4.12.0 | git+https://github.com/ocaml/opam-repository.git
# path        ~/work/analyzer/analyzer/_opam/.opam-switch/build/dune-site.2.8.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p dune-site -j 3 @install
# exit-code   1
# env-file    ~/.opam/log/dune-site-32483-25bbc9.env
# output-file ~/.opam/log/dune-site-32483-25bbc9.out
### output ###
# Error: stat:
# /Users/runner/work/analyzer/analyzer/_opam/lib/ocaml/arith_flags.cmx: No such
# file or directory
```
(https://github.com/goblint/analyzer/runs/4490566773?check_suite_focus=true#step:8:5470)

**Comment by rgrinberg** [comment]
@nojb @bobot any idea what this could be?

**Comment by nojb** [comment]
No idea, sorry.

**Comment by emillon** [comment]
I had a look at this and I confirm what @bobot said above.
That seems to be due to how opam executes the build plan. When downgrading there's a "remove" step, but instead of doing "remove old", "build new", "install new", opam actually does "build new" first and waits until the last moment to "remove old" and "install new" (see https://github.com/ocaml/opam/pull/2593). So in that case I think we're seeing the build step of `dune-private-libs` being executed in parallel with the remove or install step of `num`.
