### ISSUE TITLE
Error should say to use `include_dirs` instead of `include_subdirs`

### ISSUE THREAD

**Issue by KeenWill** [ocaml/dune#5293]
Hi,

I was trying to include some C code from an `include` directory in dune.

Here was my code:

```
...
(foreign_stubs 
    (language cxx)
    (names include/host)  
...
```

I then got this error:

```
File "lib/dune", line 7, characters 11-23:
7 |     (names include/host)
               ^^^^^^^^^^^^
Error: Relative part of stub is not necessary and should be removed. To
include sources in subdirectories, use the (include_subdirs ...) stanza.
```

Based off of [these docs](https://dune.readthedocs.io/en/stable/concepts.html#foreign-stubs), I think this is supposed to be `include_dirs` instead of `include_subdirs`.

## Specifications

- Version of `dune` (output of `dune --version`): 2.9.1
- Version of `ocaml` (output of `ocamlc --version`): 4.12.0
- Operating system (distribution and version): MacOS Monterey 12.1 Beta

**Comment by recoules** [comment]
Hi @KeenWill,

From my understanding, this is not a bug: `include_dirs` is for tracking header dependencies (it is barely equivalent to `-I` of C compilers) while `include_subdirs` is used to *view* all the files in sub-directories as if they were alongside the `dune` file (*flattening*).

At the end, what you have to do depends on the structure of your project.
If the structure is quite simple, for instance, you only have one sub-directory `include` and no file with duplicate names, you can use the stanza `(include_subdirs unqualified)` at the top of your `dune` file.
```
(include_subdirs unqualified)

(library
...
(foreign_stubs
  (language cxx)
  (names host)
...
```

However, if you do not want to "*flatten*" the repository structure, you can create a `dune` file in `include` and create a `foreign_library`:
```
(foreign_library
 (archive_name my_host_lib)
 (language cxx)
 (names host))
```
And use it in your dune file:
```
(library
...
(foreign_archives include/my_host_lib)
...
```

Note that if you do not want to modify the `include` directory (e.g. if it is a git sub-module), you can use the `subdir` stanza that acts as if the stanzas where in a `dune` file in the sub-directory. 
```
(subdir include
  (foreign_library
   (archive_name my_host_lib)
   (language cxx)
   (names host)))

(library
...
(foreign_archives include/my_host_lib)
...
```

**Comment by voodoos** [comment]
As @recoules said this is not an error. The `include_subdirs` stanza is one way to interact with stubs in subdirectories.
