### ISSUE TITLE
`js_of_ocaml`: ability to specify `link` step flags

### ISSUE THREAD

**Issue by zbaylin** [ocaml/dune#5296]
## Desired Behavior
Currently when using `--profile=debug`, dune uses separate compilation steps for `js_of_ocaml`<sup>[1](https://ocsigen.org/js_of_ocaml/3.5.1/manual/separate-compilation)</sup>. One of these steps is `js_of_ocaml link`. In the dune 2.9 spec, one can change the flags sent to the "main" JSOO build step using `(js_of_ocaml (flags ...))`, but as far as I can tell<sup>[2](https://discuss.ocaml.org/t/dune-changing-js-of-ocaml-link-flags/8995/4)</sup> there is no equivalent for the `link` step.

I think it would be useful to provide add `link_flags` to the JSOO configuration, which behaves the same as `flags`.

Let me know if this is something that I could submit a PR for.

## Example
`dune`:
```
(executable xyz
 ...
 (js_of_ocaml
  (link_flags (--source-map-root=/abc/))))
```

**Comment by hhugo** [comment]
This has been implemented as part of https://github.com/ocaml/dune/pull/5049

**Comment by zbaylin** [comment]
Ah, thanks @hhugo! I assume this will land as part of dune 3?

**Comment by hhugo** [comment]
I guess so
