### ISSUE TITLE
Question: how to run tests in specified directory ?

### ISSUE THREAD

**Issue by Kakadu** [ocaml/dune#5298]
I have the source tree that contains tests (see below). I can successfully run all tests using `dune runtest --force` or  "typed" tests via `dune runtest --force tests/typed`.   But I can't run tests by specifying single directory, i.e. `dune runtest tests/typed/Ignore.t --force` does nothing. Current workaround is either run too many tests at once (`dune runtest tests/typed`) or put tests into one more level of directory tree (as I did for `ifbool`, see below). 

Questions:
1) Could you make dune to tests from the file `asdf/run.t` if the command `dune test asdf --force` is being executed?
2) Could you patch manpages for `test` and `runtest`? They mention positional `[DIR]` argument but don't provide any explanations.

dune 2.9.1

````
✗ tree tests/ -P '*.t'
tests/
├── typed
│   ├── ast.t
│   │   └── run.t
│   ├── Equality.t
│   │   └── run.t
│   ├── ExcTry.t
│   │   └── run.t
│   ├── failwith.t
│   │   └── run.t
│   ├── function.t
│   │   └── run.t
│   ├── hashtables.t
│   │   └── run.t
│   ├── ifbool
│   │   └── t.t
│   │       └── run.t
│   ├── Ignore.t
│   │   └── run.t
│   ├── ListFusion.t
│   │   └── run.t
│   ├── list_len.t
│   │   └── run.t
│   ├── Record1.t
│   │   └── run.t
│   └── StringConcat.t
│       └── run.t
└── untyped.t
    ├── lib3
    └── run.t
````

**Comment by nojb** [comment]
If I'm not wrong, CRAM tests define aliases named the same way as the test minus the `.t` suffix, ie `dune build @Ignore` in your case.

**Comment by Kakadu** [comment]
@nojb many thanks! It looks like an opportunity to path documentation

**Comment by rgrinberg** [comment]
It's in the manual already. https://dune.readthedocs.io/en/stable/tests.html#test-options
