### ISSUE TITLE
Evaluation order for rule deps is generating "subdir doesn't exist" warnings (1.0+beta17)

### ISSUE THREAD

**Issue by gersonmoraes** [ocaml/dune#534]
Since v1.0+beta17, I'm getting these warnings whenever I define an executable in a subdirectory where the main file is generated by a rule.

```
Warning: Directory _build/default/subdir doesn't exist.
```

To reproduce the problem sufice to add this file to a subdir and trying runnig it with `jbuilder exec path/to/main.exe`:

```
(executable
 ((name main)
))

(rule
 ((targets (main.ml))
  ;; problematic line:
  (deps ( (glob_files optional.ml) (glob_files *optional.ml) ))
  (action  (with-stdout-to ${@} (run echo "let () = print_endline \"Hello World\""
  )))))
```

Apparently it's related with the evaluation order for `deps` in the rule. If removed, the warnings disappear.  It's seams jbuilder/dune is checking dependencies before creating the subdirectory under `_build/default`.

**Comment by diml** [comment]
Thanks, I added your example as a reproduction case and fixed  in #536
