### ISSUE TITLE
dune promote queries

### ISSUE THREAD

**Issue by raphael-proust** [ocaml/dune#5368]
## Desired Behavior

I would like to be able to query the state of dune file promotion. I.e., determine what will be the result of `dune promote` without actually promoting the files.

Currently, I use a workaround where I rely on `git`: I do promote, and then inspect the applied promotion, and then `git restore`. However this requires some care in keeping the git repo clean which isn't really possible during rebases.

## Example

I would like the following options to query the current state of the files to be promoted.

```
$ dune promote --diff
<same output as `git diff` after a `dune promote`>
```

```
$ dune promote --diff --name-only
<same output as `git diff --name-only` after a `dune promote`>
```

**Comment by rgrinberg** [comment]
The idea is sound, but I don't like proposed command line. Flags shouldn't modify a command to be completely different, we should add additional commands for this. For example:

```
$ dune promotion list
$ dune promotion diff
```

I'm using the subcommand `promotion` since unfortunately `promote` is already taken.

**Comment by raphael-proust** [comment]
Using subcommands of `promotion` seems a sound proposal.

For `diff` we could also have `dune promotion diff path/to/directory` to restrict the set of file diffs shown (as in `git diff`). Maybe with `--` before the path list.

This can later be extended with additional subcommands at a later point:

- to promote, possibly with some file-or-directory paths (`dune promotion promote -- test/`)
- to remove the promotion (`dune promotion forget -- lib/`)

**Comment by raphael-proust** [comment]
Thanks @emillon !
