### ISSUE TITLE
How to hide a module in a library?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/dune#540]
Hi,

The sources are:
src/svm.ml
src/utls.ml

Excerpt from the src/jbuild:

    (library
     ((name        orsvm_e1071)
      (public_name orsvm_e1071)
      (modules (svm utls))
      (libraries (dolog))))

If I don't put utls in modules, it won't compile.
However, I want this module to be hidden when installing the library (not exposed to potential users).

How to do so?

**Comment by rgrinberg** [comment]
> If I don't put utls in modules, it won't compile.

What do you mean? Unless you have other stanzas in your jbuild, then the modules field is completely optional.

> However, I want this module to be hidden when installing the library (not exposed to potential users).

You cannot control what gets installed/not installed (yet). But you can hide `Svm.Utls` as a name in `svm.ml`. By not adding an `module Utls = Utls` line.

**Comment by UnixJunkie** [comment]
Ok, I got it. I will create this orsvm_e1071.ml file.
Thanks! Great support!

**Comment by UnixJunkie** [comment]
Are there good project examples out there that use a toplevel .ml file to list what they want to export?
I kind of failed in there: https://github.com/UnixJunkie/orsvm-e1071
So I finally inlined the Utls module inside of the Svm module.
I would have preferred it to be in a separate file but...
In the dirty hackish way of doing, I could #include the implementation into svm.ml but...

**Comment by diml** [comment]
A lot of Jane Street packages do that, such as src/base.ml in Base or src/parsexp.mli in parsexp.

Why didn't it work in your case?

**Comment by UnixJunkie** [comment]
Let's say I want to create library toto.
I have a.ml and b.ml.
a.ml uses b.ml.
Let's say there are no mli files, to keep things simple.
What should be the minimalist content of the jbuild file (and eventually the especially crafted because of jbuilder needs toto.ml file) so that only the A module is visible after installation of the library as Toto.A?

**Comment by rgrinberg** [comment]
Francois BERENGER <notifications@github.com> writes:

> Let's say I want to create library toto.
> I have a.ml and b.ml.
> a.ml uses b.ml.
> Let's say there are no mli files, to keep things simple.
> What should be the minimalist content of the jbuild file (and eventually the especially crafted because of jbuilder needs toto.ml file) so that only the A module is visible after installation of the library as Toto.A?

Again, there is no way control visibility across installation. The best
that you can do today is:

$ ls toto
jbuild a.ml b.ml toto.ml

$ cat jbuild
(library ((name toto)))

$ cat toto.ml
module A = A

In this scheme, only Toto.A is visible to users of the library toto
(whether it's installed or used as part of a bigger jbuilder workspace)

Note that Toto__B is still available to all users. But users should be
aware that modules that are only accessible this way are private.

**Comment by UnixJunkie** [comment]
No: the best I can do today is #include b.ml inside of a.ml:

    module B = struct
      #include "b.ml"
    end

Which implies not having to provide a toto.ml file and not having a Toto__B module installed.

**Comment by rgrinberg** [comment]
Yup, preprocessor tricks should work as well. Just remember to add `(modules (:standard \ b))` so that `Toto.B` will not exist.

**Comment by UnixJunkie** [comment]
or just

    (modules (a))

**Comment by UnixJunkie** [comment]
And here comes the next question:
https://github.com/ocaml/dune/issues/544
