### ISSUE TITLE
this project doesn't compile, I think it should

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/dune#543]
https://github.com/UnixJunkie/jbuilder_test_00

**Comment by rgrinberg** [comment]
What error are you getting?

**Comment by UnixJunkie** [comment]
# jbuilder build @install
        ocamldep src/toto.depends.ocamldep-output
          ocamlc src/toto.{cmi,cmo,cmt}
          ocamlc src/toto__A.{cmi,cmo,cmt} (exit 2)
    (cd _build/default && /home/berenger/.opam/4.05.0/bin/ocamlc.opt -w -40 -g -bin-annot -no-alias-deps         -I src -open Toto -o src/toto__A.cmo -c -impl src/a.ml)
    File "src/a.ml", line 4, characters 2-41:
    Error: Unbound module B

**Comment by rgrinberg** [comment]
module `B` is indeed unavailable to your library because your `modules` field only includes module `A`. This is expected.
