### ISSUE TITLE
how to preprocess a file with cppo?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/dune#544]
a.ml needs to go through cppo in order to be compilable.
I don't want a a.ml.needs_preprocessing file in order to generate a.ml.
I would like plain old C style preprocessing.

**Comment by UnixJunkie** [comment]
can't I pass '-pp cppo' in some way?

**Comment by rgrinberg** [comment]
Yes, simply set this as your preprocessor `(preprocess (action (run ${bin:cppo} ${<})))`.

Also, don't be shy about reading the manual: http://dune.readthedocs.io/en/latest/search.html?q=cppo&check_keywords=yes&area=default

Finally, may I suggest that you ask questions on discuss.ocaml.org? There's a far bigger audience for answering questions there. This place is more focused on discussing dune bugs.

**Comment by UnixJunkie** [comment]
I did looked into the manual and did a fair amount of trial before posting here.
While the manual is filled with grammar rules, simple working examples would be welcome.

**Comment by UnixJunkie** [comment]
Thanks a lot for the help, really.
The final solution looks like this:

      (preprocessor_deps (utls.ml))
      (preprocess (per_module ((action (run ${bin:cppo} ${<})) (svm))))

**Comment by rgrinberg** [comment]
That looks good. It's best to avoid preprocessing modules that don't need
it.
