### ISSUE TITLE
warning 70 is enabled by default

### ISSUE THREAD

**Issue by c-cube** [ocaml/dune#5464]
## Expected Behavior

Dune would let me choose whether or not I want to write .mli files

## Actual Behavior

Dune enables warning 70 ("missing mli") by default

## Specifications

- Version of `dune` (output of `dune --version`): 2.9.3
- Version of `ocaml` (output of `ocamlc --version`): 4.13.1
- Operating system (distribution and version): arch

**Comment by rgrinberg** [comment]
As much as I would love to force you all to use mli's, this warning wasn't intentional. I think the culprit is this piece of code in dune:

```
  (* New warnings should be introduced here *)
  let all =
    Int.Set.diff
      (Int.Set.of_list (List.init 62 ~f:succ))
      (Int.Set.of_list [ 4; 29; 40; 41; 42; 44; 45; 48; 58; 59; 60 ])
  in
```

Which assumes 62 warnings should be enough for everyone.

However, I'm actually curious as to why you don't like the warning. You can easily write `[@@@warning "-70"]` to silence it and otherwise it's a useful reminder.

**Comment by c-cube** [comment]
I don't want to make my custom warning list even longer :slightly_smiling_face: . I just think this should be opt-in, it doesn't warn of any potential defect and is purely a matter of taste.

My use case, if you're curious: sometimes I find it cleaner to have a large `.ml` file with a lot of submodules of the shape
```ocaml
module Foo : sig
  …
end = struct
  …
end```

and perhaps a few toplevel values and shared module aliases, etc. It's as safe as each module having its own `.ml` and `.mli` and can be less verbose overall, and more namespaced.

**Comment by rgrinberg** [comment]
Do you think this is worth fixing for 2.9.4 as well?

**Comment by c-cube** [comment]
if it's not a warn-error, probably not :)

**Comment by Octachron** [comment]
> You can easily write [@@@warning "-70"] to silence it and otherwise it's a useful reminder.

Just for information's sake, `[@@@warning "-70"] ` will not work currently (the scope of floating attributes is not large enough). I will fix this issue at some point but not before 5.1 .
