### ISSUE TITLE
grouping of processes in chrome trace files changed with dune 3

### ISSUE THREAD

**Issue by Khady** [ocaml/dune#5469]
Between dune 2 and 3 the chrome trace files have changed slightly. I don't know it is this a bug or an expected difference.

With dune 2, every call of one process is living in its own "group". When using chrome://tracing or https://ui.perfetto.dev/v21.0-c4eb91619/assets/catapult_trace_viewer.html all the calls for ocamlc.opt are under one foldable list. There are no other processes in the same group
![image](https://user-images.githubusercontent.com/974142/154953045-eb88442a-b701-48f5-bcc2-6c73e7404b79.png)

Since dune 3, some calls are grouped like before, but most of the calls end up in an anonymous group that contains calls to many different binaries (the one bellow `refmt` in the screenshot)
![image](https://user-images.githubusercontent.com/974142/154953454-7e430aa0-6be1-4355-ad3e-6134a89c763e.png)

## Specifications

- Version of `dune` (output of `dune --version`): 3.0.2 and 2.9.1
- Version of `ocaml` (output of `ocamlc --version`): 4.12.1
- Operating system (distribution and version): debian 10

**Comment by rgrinberg** [comment]
> all the calls for ocamlc.opt are under one foldable list. There are no other processes in the same group

Would it fix things if we put all the ocamlc, ocamldep, ocamlopt calls in their individual categories?

**Comment by Khady** [comment]
to me the main problem is that calls to a single tool (let's say ocamlc) are divided between different groups with no apparent logic. I feel that the way it is done with dune 2 was more readable. But having everything in the anonymous group could work too. It's mainly the mix of both that is weird.
