### ISSUE TITLE
[RPC] Outstanding long-poll requests are not returned on subscription cancel

### ISSUE THREAD

**Issue by cwong-ocaml** [ocaml/dune#5479]
## Expected Behavior

When a long-polling subscription is cancelled from the client side, any outstanding polling requests should immediately receive a `None` (no more values).

## Actual Behavior

Dune does not immediately respond to outstanding long-poll requests when the subscription is cancelled from the client side, but instead only when the request *would* have received some data if it were not cancelled.

## Reproduction

I struggled to express this with the existing framework, but a test along the lines of this:

```ocaml
    let%expect_test "long polling - client side termination with outstanding request" =
      let client client =
        let* poller = Client.poll client sub_decl in
        let poller =
          match poller with
          | Ok p -> p
          | Error e -> raise (Version_error.E e)
        in
        let req () =
          let+ res = Client.Stream.next poller in
          match res with
          | None -> printfn "client: no more values"
          | Some a -> printfn "client: received %d" a
        in
        let* () = req () in
        (* Imagine that this immediately kicks off the job. *)
        let outstanding = Client.Stream.next poller in
        let* () = Client.Stream.cancel poller in
        let+ res = outstanding in
        match res with
        | None -> printfn "client: no more values"
        | Some a -> printfn "client: received %d" a
      in
      let handler =
        let state = ref 0 in
        server (fun _poller ->
            incr state;
            Fiber.return (Some !state))
      in
      test ~init ~client ~handler ~private_menu:[ Poll sub_proc ] ();
      (* Actual output: client hangs when binding on [outstanding] *)
      [%expect
        {|
    client: received 1
    client: no more values
    server: polling cancelled
    server: finished. |}]
```

**Comment by cwong-ocaml** [comment]
The issue is in `make_on_poll` [here](https://github.com/ocaml/dune/blob/main/src/dune_rpc_server/dune_rpc_server.ml#L494).

Notice that `send` binds on `Fiber.Svar.wait svar ~until` before producing any actual data. In fact, if I'm understanding correctly, this implementation *never* informs clients that an outstanding long poll request has had its subscription cancelled, so such requests may be blocked indefinitely.

Done properly, I think the right thing to do is to update the svar to distinguish between "server produced new values" and "client canceled".

**Comment by rgrinberg** [comment]
> Notice that send binds on Fiber.Svar.wait svar ~until before producing any actual data. In fact, if I'm understanding correctly, this implementation never informs clients that an outstanding long poll request has had its subscription cancelled, so such requests may be blocked indefinitely.

Yes, but that does not necessarily mean that we cannot have cancellation working. In fact, all we have to do is just to fill the appropriate ivar that corresponds to answering this request.

**Comment by rgrinberg** [comment]
Refer to Jeremie's comment over here: https://github.com/ocaml/dune/pull/5276#issuecomment-989287625

**Comment by cwong-ocaml** [comment]
If I'm understanding that comment correctly, does this mean that leaving the pending requests open indefinitely is intended? I think this is pretty unintuitive (and it seems that this behaves differently than Jeremie's suggestion anyway, the in-flight request actually can get answered eventually).

**Comment by cwong-ocaml** [comment]
> Could you clarify this? I think this contradicts:

With the current implementation, pending requests get answered "normally" regardless of whether the subscription is cancelled. That is, if the chain of events is

- (Client) Send request
- (Client) Cancel request
- (Server) Request is ready

the client will actually get a response on that request. I think this contradicts Jeremie's suggestion, which would have the client's request hang forever.
