### ISSUE TITLE
 num fails to build with dune 3.0

### ISSUE THREAD

**Issue by olafhering** [ocaml/dune#5490]
As reported in ocaml/num#26, dune 2.x can build num.git, but dune 3.0 fails.

Nothing in CHANGES.md indicates what change in dune caused this regression.

**Comment by rgrinberg** [comment]
The dependencies in num weren't specified correctly. Dune reservers the right to run the rules in whatever order as long as it respects dependency order. I sent a PR to fix issue upstream.
