### ISSUE TITLE
Changlog feedback, missing docs (re: action-stdout-on-success)

### ISSUE THREAD

**Issue by jberdine** [ocaml/dune#5493]
I think it would be helpful to users is it were easier to go from a changelog entry for a new feature to documentation to use it. This is motivated by a recent experience I had seeing the following entry in the 3.0 changelog:

> Add options to control how Dune should handle stdout and stderr of actions when then succeed. It is now possible to ask Dune to ignore the stdout of actions when they succeed or to request that the stderr of actions must be empty. This allows to reduce the noise of large builds (#4422, #4515, @jeremiedimino)

It would have helped if the changelog entry had mentioned the specific option, to enable searching for docs, etc. Barring that, having the option name in the PR description would have helped. In the end I figured out that I could add `(action_stdout_on_success swallow)` to the workspace file, but it took reading the source code of several PRs to find the `--action-stdout-on-success` option name and to then figure out that the workspace file entry needed to use underscores instead of hyphens. Finally, searching the latest version at readthedocs for "on-success" does not turn anything up.

**Comment by nojb** [comment]
See #6392
