### ISSUE TITLE
Dune-configurator does not find csexp

### ISSUE THREAD

**Issue by roptat** [ocaml/dune#5497]
Hi!

I'm trying to build dune in Guix, a package manager similar to Nix. We split the build into multiple phases. First, we build a first dune with `./configure` and `make release`. Then, starting from fresh sources, we try to run it with `dune build @install -p dune-configurator`, which fails with:

```
File "otherlibs/configurator/src/dune", line 7, characters 17-22:
7 |  (libraries unix csexp)
                     ^^^^^
Error: Library "csexp" not found.
-> required by library "dune-configurator" in
   _build/default/otherlibs/configurator/src
-> required by _build/default/META.dune-configurator
-> required by _build/install/default/lib/dune-configurator/META
-> required by _build/default/dune-configurator.install
-> required by alias install
```

even though csexp is available in `OCAMLPATH`. It used to work with 2.9.3. I tried to look at the nix packages you have in this repo, but they also seem to be stuck at 2.9.3.

**Comment by anmonteiro** [comment]
FWIW it's working just fine here: https://github.com/anmonteiro/nix-overlays/blob/8bc4e7e5f4d7579d5875ec1c11f5f20bb632b1fc/ocaml/dune/configurator.nix

**Comment by roptat** [comment]
Thanks! Removing the vendored dependencies did the trick. It looks like, after building bootstrap, there's a step to remove them, but since I'm building the bootstrap and configurator as separate packages, I start the build of dune-configurator with the vendor directories. Closing, since the issue is with packaging in Guix, not in dune.
