### ISSUE TITLE
Cannot run tests in bytecode mode

### ISSUE THREAD

**Issue by dariusf** [ocaml/dune#5515]
This is a follow-up to janestreet/ppx_inline_test#19, which I found after separately encountering this issue. I'd be happy to submit a PR and add tests, if someone could point me in the right direction.

## Expected Behavior

Inline tests should be able to run in bytecode mode, for use with ocamldebug, etc.

## Actual Behavior

```
$ dune test
File "dune", line 4, characters 1-28:
4 |  (inline_tests (modes byte))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
inline_test_runner_test alias runtest (exit 1)
You are doing something unexpected with the tests. No tests have
been run. You should use the inline_tests_runner script to run
tests.
make: *** [all] Error 1
```

## Reproduction

https://gist.github.com/dariusf/78e40f07c62e04e2781d45c4cb6065e3

This is for ppx_expect, and the linked issue finds it in ppx_inline_test. I'm not sure how to reproduce using `generate_runner`, which is used in existing tests.

## Specifications

- Version of `dune` (output of `dune --version`): 3.0.2
- Version of `ocaml` (output of `ocamlc --version`): 4.13.1
- Operating system (distribution and version): macOS Monterey 12.2.1

**Comment by rgrinberg** [comment]
To start, submit a PR with the reproduction test case in cram style.

> This is for ppx_expect, and the linked issue finds it in ppx_inline_test. I'm not sure how to reproduce using generate_runner, which is used in existing tests.

That's OK, you can use ppx_inline_test. Since we already depend on it in the test suite anyway.

**Comment by dariusf** [comment]
Are there any docs on how inline tests work beyond what's in the manual? I had a look at inline_tests.ml but I don't really know the workflow implemented by the rules it generates. Would appreciate any other pointers.

**Comment by rgrinberg** [comment]
I had a look and I think the issue is either in ppx_expect or ppx_inline_test. Perhaps @hhugo knows?

**Comment by dariusf** [comment]
Never mind, I figured out the issue after reading janestreet/ppx_inline_test#19 more closely. The problem is ppx_inline_test contains C stubs which should be linked in bytecode mode, and dune doesn't build the test runner with 1. `-output-complete-exe`, 2. paths to stubs using `-I`. With these added manually, the test works.

There's a tentative fix in the linked PR. Is changing the extension of the executable okay? Since `Exe.Linkage.custom` produces an `.exe`.
