### ISSUE TITLE
Generating private documentation

### ISSUE THREAD

**Issue by wieczyk** [ocaml/dune#552]
My project contains application and a couple of private libraries.

After executing `jbuilder build @doc` I see that documentation for each library has been generated (I see html files) but the main `index.html` files does not have link to ANY generated documentation.

I guess that links are generated only to libraries with `public_name`. I think it would be nice options to generate documentation also for developers which contains whole documentation.

**Comment by rgrinberg** [comment]
I don't think the index page ever contained links to private libraries. However, we do have an alias for building the private docs as well `@doc-private`.

**Comment by rgrinberg** [comment]
`@doc-private` is now available. Note that in the next version of jbuilder, private libraries will not be added in the main listing of packages (but their html will still be generated using this alias).
