### ISSUE TITLE
Exit code for `dune build @doc` not useful enough

### ISSUE THREAD

**Issue by raphael-proust** [ocaml/dune#5524]
## Expected Behavior

When I run `dune build @doc` and there are syntax errors reported by `odoc`, I would expect `dune` to exit with a non-zero code.

## Actual Behavior

`dune build @doc` exits with code `0` even when there are errors.

This makes it unnecessarily difficult to check whether there are doc syntax issues programmatically.

## Reproduction

From within the `dune`'s `main` branch:

1. `dune build @doc`
1. see a lot of warnings and errors
1. `echo $?`
1. it's `0`

## Specifications

- Version of `dune` (output of `dune --version`): tested on 3.0.2 and 2.9.3
- Version of `ocaml` (output of `ocamlc --version`): tested on 4.13.1 and 4.12.1
- Operating system (distribution and version): archlinux

## Additional information 

- odoc version: tested on  2.1.0 and 1.5.3

**Comment by raphael-proust** [comment]
Workaround: `ODOC_WARN_ERROR=true dune build @doc`.

Is there a way to set the env variable from the dune file? Or pass the `--warn-error` flag from the dune file?

**Comment by rgrinberg** [comment]
I think @Julow worked on something related to this.

**Comment by Julow** [comment]
This is intended, sorry for the confusion.

The "Couldn't find the following modules" is special because it doesn't come from the input but from the way the documentation is built by Dune.
Odoc is trying to lookup the intermediate `.odoc` files of the external dependencies (for example the stdlib), which aren't built by Dune and aren't stored in Opam.
I think Dune is doing that on purpose and it's a supported use case in Odoc: build the documentation for a specific package that don't have links to external modules.

**Comment by emillon** [comment]
To summarize:
- most warnings can be enabled with the env stanza above
- we planned to make the warnings fatal by default in dev mode in dune 3, but forgot
- the "couldn't find the following modules" warning is being tracked as #5229 

So I'm closing this issue. Thanks!

**Comment by zapashcanon** [comment]
Sorry for resurrecting this but is there a way to make these kind of errors fatal: `Warning: Failed to resolve reference unresolvedroot(Owi).Value Couldn't find "Value"` ?

I'm using both `ODOC_WARN_ERROR=true dune build @doc` and `(env (_ (odoc (warnings fatal))))` but I'm still getting a 0 exit code.

**Comment by emillon** [comment]
Hi.
Can you post the odoc command that outputs this warning? you can get that with `--display verbose`.

You're probably in the case that's described in this comment:

https://github.com/ocaml/dune/blob/3.13.0/src/dune_rules/odoc.ml#L243

**Comment by emillon** [comment]
For future reference:

```
Running[281]: (cd _build/default/_doc/_html && /home/zapashcanon/.config/opam/5.1.0/bin/odoc link -I ../_odoc/pkg/owi -I ../../src/.owi.objs/byte -o ../_odocls/owi/page-index.odocl ../_odoc/pkg/owi/page-index.odoc)
Output[281]:
File "../../../../doc/index.mld", line 9, character 0 to line 22, character 1:
Warning: Failed to resolve reference unresolvedroot(Owi).Value Couldn't find "Value"
File "../../../../doc/index.mld", line 9, character 0 to line 22, character 1:
Warning: Failed to resolve reference unresolvedroot(Owi).Pp Couldn't find "Pp"
File "../../../../doc/index.mld", line 9, character 0 to line 22, character 1:
Warning: Failed to resolve reference unresolvedroot(Owi).Simplify Couldn't find "Simplify"
```

I'll have a look if its an issue with odoc.

**Comment by emillon** [comment]
The quick answer if that the `(env)` stanza needs to be above the package you're building for the flags to apply. So I think that if you move [this](https://github.com/OCamlPro/owi/blob/8afe136be9c315bc1e3622d0e27749707b1432d8/doc/dune#L5) to the top-level `dune` file, you should be good.

(Debugging notes):
- `--warn-error` is not present in that command, so it's expected that the warning is not fatal
- this flag is not present in any of the `odoc` command lines, so something might be wrong with the setup

**Comment by zapashcanon** [comment]
FYI this comes from the fact that I'm referencing a module that does not exist anymore from a `.mld` file.
