### ISSUE TITLE
dune prints filename as _unknown_ on failing Coq compilation

### ISSUE THREAD

**Issue by MackieLoeffel** [ocaml/dune#5532]
## Expected Behavior

Consider the following Coq file `test.v`:
```
Lemma x : True.
Proof. idtac "A". Qed.
```
When I compile `test.v` with dune, I expect the output to use the file name `test.v`, not `_unknown_`. 

## Actual Behavior

```
dune build --display short
```
in a dune project that contains the Coq file above results in the following error:
```
File "theories/_unknown_", line 1, characters 0-0:
        coqc theories/.test.aux,theories/test.{glob,vo} (exit 1)
A
File "./theories/test.v", line 4, characters 18-22:
Error:  (in proof x): Attempt to save an incomplete proof
```
The first line of this output does not seem useful and it contains `_unknown_` instead of the correct file name.

## Reproduction

Create a dune project with the file `test.v` with the following contents:
```
Lemma x : True.
Proof. idtac "A". Qed.
```
Then run 
```
dune build --display short
```

The error only occurs with the `idtac "A"`.

## Specifications

```
$ dune --version            
3.0.2
$ coqc --version     
The Coq Proof Assistant, version 8.14.0
compiled with OCaml 4.07.1
```
on Debian

**Comment by ejgallego** [comment]
Tried dune 2.9.2 and Coq 8.13 and I could not reproduce. Trying your Coq + Dune combination now.

**Comment by MackieLoeffel** [comment]
I also way not able to reproduce this with dune 2.9.2.

**Comment by rlepigre** [comment]
I was thinking of giving this issue a go, but the commit that introduces the problem is large, and the problem is not obvious to me. Anyway, I bisected the issue, and here is the result.
```
6e25cddf803d8bb76ac6af607f0a892217617187 is the first bad commit
commit 6e25cddf803d8bb76ac6af607f0a892217617187
Author: Jérémie Dimino <jeremie@dimino.org>
Date:   Thu May 13 13:12:12 2021 +0100

    Replace Dep_path by a more principled mechanism (#4605)
    
    Signed-off-by: Jeremie Dimino <jeremie@dimino.org>
```
Perhaps @jeremiedimino will know where the problem might come from?

Here is the reproducing test case I used (should probably be put in `test/blackbox-tests/test-cases/coq/github5532.t/run.t` by whoever proposes a fix):
```
Reproducing test case for #5532.

  $ cat >foo.v <<EOF
  > Lemma dummy : True.
  > Proof. idtac "A". Qed.
  > EOF
  $ cat >dune-project <<EOF
  > (lang dune 2.8)
  > (using coq 0.3)
  > EOF
  $ cat >dune <<EOF
  > (coq.theory
  >  (name basic))
  > EOF
  $ dune build --display short
  XXX
```
