### ISSUE TITLE
Dune errors when trying to remove non-empty man directory

### ISSUE THREAD

**Issue by Gbury** [ocaml/dune#5542]
## Expected Behavior

When uninstalling a package containing man pages, dune should accept that the manpage directories can be non-empty after removing the manpages from the project being uninstalled.

## Actual Behavior

When uninstalling a package containing man pages, dune sometimes errors out, with a message stating that some directories, such as `<prefix>/man/man1`, are non-empty and that the user should manually delete it. This is a problem since such directories are shared by all tools being installed in a prefix, and thus there are perfectly good reasons for such directories to not be empty (even if during installation dune had to create some of these directories).

## Reproduction

- PR with a reproducing test: #5541 

## Specifications

- Version of `dune` (output of `dune --version`): 3.0.3
- Version of `ocaml` (output of `ocamlc --version`): 4.13.1
- Operating system (distribution and version): Archlinux

## Additional information 

This issue makes the CI of alt-ergo fail (see e.g. https://github.com/OCamlPro/alt-ergo/runs/5816456115?check_suite_focus=true ).

**Comment by nojb** [comment]
Makes sense.
