### ISSUE TITLE
dune passes jsoo compile flags as link flags

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/dune#5563]
## Expected Behavior

A jsoo project compiles with `(js_of_ocaml (flags --pretty))`

## Actual Behavior

One gets an error 

```
File "src/_unknown_", line 1, characters 0-0:
js_of_ocaml: unknown option '--pretty'.
Usage: js_of_ocaml link [OPTION]… [JS_FILES]…
Try 'js_of_ocaml link --help' or 'js_of_ocaml --help' for more information.
```

## Reproduction

Try compiling a jsoo project with `(js_of_ocaml (flags --pretty)`

## Specifications

- Version of `dune` (output of `dune --version`): 3.0.3
- Version of `ocaml` (output of `ocamlc --version`): 4.14.0
- Operating system (distribution and version): macOS Monterey 12.2.1 (21D62)
- Js_of_ocaml 4.0.0

## Additional information 

The documentation says that `(flags ...)` is passed to `js_of_ocaml compile` but actually it is passed to `js_of_ocaml link` as well. See this [line](https://github.com/ocaml/dune/blob/cff55b104a0bb7ebf688570ebdeb3833371f1462/src/dune_rules/js_of_ocaml.ml#L93-L94)

Thanks,
Ulugbek

**Comment by hhugo** [comment]
This is because your are using `dune lang 2.*`. You should update to `dune lang 3.0`

**Comment by ulugbekna** [comment]
Indeed, thanks! :-)
