### ISSUE TITLE
Multiple licenses

### ISSUE THREAD

**Issue by liyishuai** [ocaml/dune#5575]
## Desired Behavior
Allow `license` field to take multiple arguments.

## Example
`(license MIT LGPL-2.1-only)`

**Comment by rgrinberg** [comment]
How does this get translated to generated .opam files?

**Comment by liyishuai** [comment]
`license: ["MIT" "LGPL-2.1-only"]`

https://opam.ocaml.org/doc/Manual.html#opamfield-license

**Comment by rgrinberg** [comment]
Sounds reasonable. Do you want to send a PR?

**Comment by liyishuai** [comment]
I'll try to make one. Still navigating through the codebase.
