### ISSUE TITLE
Select stanza broken (when using -only-packages)

### ISSUE THREAD

**Issue by hhugo** [ocaml/dune#5603]
## Broken Behavior
I have  git repo that contains multiple opam packages.
I have a library `A` with an optional (`select` stanza) dependency on a library `B` that is also part of the repo but marked as vendor-ed.
After installing A with opam pin (B is not installed), I see B in the `requires` section of the `A`'s   lib/A/dune-package.
Trying to install a third package C result in the following error.

```
# File ".opam/....../lib/A/dune-package", line .., characters ...:
# 87 |   B)
#        ^^^^^^^^^^^^^^^^^^
# Error: Library "B" not found.
```

If I remove B from the repo and reinstall A. Everything works fine

## Specifications

- Version of `dune` 2.9
- Version of `ocaml` 4.12
- Version of `opam` 2.1.0

**Comment by rgrinberg** [comment]
Is this a bug in 3.1.x as well? If so, could you add a reproduction test case to the repo?

**Comment by hhugo** [comment]
I confirm that this affects dune.3.1.x as well

**Comment by hhugo** [comment]
There was one missing aspect in my initial report. The issue only triggers when the optional library in marked as vendor-ed.

**Comment by hhugo** [comment]
could be related to https://github.com/ocaml/dune/issues/4962

**Comment by rgrinberg** [comment]
Replaced by 7197
