### ISSUE TITLE
In --display=short / verbose, reprint any error-messages after completion of the build

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml/dune#5605]
## Desired Behavior

Often, when a build of our monorepo fails due to the error, the actual error-message is buried halfway through pages-and-pages of `(display short)` output-lines.

This leads to a workflow where I often do `dune build`, followed by *another* `dune build` if the build failed, because the second time it only prints the errors.

I'd like a mode, something like `--summarize=errors` (and possibly `--summarize=warnings`?) that causes dune to re-print all error-messages (resp. warning messages) after the build has fully failed.

Some thoughts on making this the most user-friendly:

1. I'd posit that this should be turned on by default;
2. when connected to an interactive terminal, it should probably only re-print errors if there were more than `$LINES` of output overall — i.e. if there was output that scrolled off-screen.

## Example

… forgive the absurdly-long examples; I wanted to get across how helpful it would be to have this implemented.

(First time I've ever seen GitHub's "body is too long (maximum is 65536 characters)." error, ahhah.)

https://gist.github.com/ELLIOTTCABLE/6348c25da90a8aba8b052ef9c04a959e

**Comment by rgrinberg** [comment]
Why do you run your builds with display=short in the first place?

**Comment by ELLIOTTCABLE** [comment]
@rgrinberg it's super-helpful to see what's going on — it helps keep a visceral awareness of which sections of the codebase are consuming the most build-time.

(Was actually about to open an issue asking that timing information for "long" entries be added to the log; but ran out of time for today … maybe tomorrow?)

**Comment by rgrinberg** [comment]
It's a bit of a weakness in dune that the normal watch mode doesn't display what it's doing, but we aren't going to solve this problem by making `--display=short` weird. We should instead add better live information to the normal display for watch mode.

> Was actually about to open an issue asking that timing information for "long" entries be added to the log; but ran out of time for today … maybe tomorrow?

I'm neither for or against this, but if someone else on the team likes this, I suppose it can be done.

**Comment by ELLIOTTCABLE** [comment]
I've realized this is just a matter of personal taste, so it's appropriate to close this issue if it's a WONTFIX.

In particular, right before writing this, this 'bug'(?) ended up forcing me to disable `--display=short` in my personal config — a meaningful warning, lost somewhere in the pages of `short` scrollback (and not reprinted at the end) made it thru into CI, for which I caught a little flack. Ugh.

FWIW, though, I have to imagine I'm not the only one who much prefers `--display=short` on large projects. I wish I could more delicately articulate the *why*, as I suspect doing so might help `--display=short` get improved to the point where it's not dangerous, but I can also relate to maintaining a feature that gets misused or that you regret adding, so … `¯\_(ツ)_/¯` such is life!

**Comment by rgrinberg** [comment]
> FWIW, though, I have to imagine I'm not the only one who much prefers --display=short on large projects. I wish I could more delicately articulate the why, as I suspect doing so might help --display=short get improved to the point where it's not dangerous, but I can also relate to maintaining a feature that gets misused or that you regret adding, so … ¯\_(ツ)_/¯ such is life!

It would be very useful feedback for us if you could explain what is lacking from the default display mode. We'll be spending our efforts improving the default display mode, so it will be very useful for us to know what can be done to improve things for the few remaining users on `--display=short`.
