### ISSUE TITLE
Unable to find libraries with some findlib installation scheme 

### ISSUE THREAD

**Issue by terencode** [ocaml/dune#5616]
## Expected Behavior

When installing the llvm bindings and adding a target lib (llvm_X86 for example) to the libraries stanza, running `dune build ` should pull it in and terminate with no error.

## Actual Behavior

dune can't find the library : `Error: Library "llvm_X86" not found.`

## Reproduction

1. create a new opam switch
2. install dune and llvm
3. execute `dune exec ocamlfind list` and confirm the library is present
4. add llvm_X86 to the libraries stanza in bin/dune
5. run `dune build` and notice the following error : `Library "llvm_X86" not found.`
6. inside the _opam/lib folder, create new directory called llvm_X86 and copy inside the META.llvm_X86 file renamed to META and the `llvm` folder.
7. run `dune build` again and notice the previous error is gone

## Specifications

- Version of `dune` (output of `dune --version`): 3.1.1
- Version of `ocaml` (output of `ocamlc --version`): 4.13.1
- Operating system (distribution and version): Archlinux, linux 5.17.2

**Comment by nojb** [comment]
The problem seems to be that Dune assumes that if `META.foo` exists then the package `foo` is found in a directory `foo`, and does not try to read the `directory` variable inside the META file which can modify the package directory (as in this case).

**Comment by nojb** [comment]
Possible fix in #5619

**Comment by terencode** [comment]
I can confirm this fixes the issue when using your branch, thank you very much for the fast response and solution !
