### ISSUE TITLE
Any way to specify dependencies for `optional` instead of `libraries`?

### ISSUE THREAD

**Issue by camlspotter** [ocaml/dune#563]
I want to control the build of an optional library based on whether some file exists or not:

```
(library
  ((name mylibrary)
   (public_name mylibrary)
   (optional)
   (libraries (notmylibrary))
   (???)  ; build only happens when some file exists
  ))
```

But I cannot find a way to add such a dependency to `library` stanza.  Is there a way for it or any workaround?

**Comment by camlspotter** [comment]
More specifically speaking I need this to workaround a build failure of camlimages in the environments where `graphics.cm*` are not really installed.  Currently, the package graphics always exists even if `graphics.cm*` are not installed.  Therefore the following library build is not skipped and failed in such environments:

```
(library
 ((name camlimages_graphics)
  (public_name camlimages.graphics)
  (optional)
  (wrapped false)
  (libraries ( graphics camlimages.core ))  ;; graphics always exists, even when graphics.cm* do not
  ))
```

I think this is a bug of findlib (https://gitlab.camlcity.org/gerd/lib-findlib/merge_requests/11) and want to have a workaround.

This specific problem can be solved when the installation of `META` file for graphics becomes optional in findlib, but I think it may be still useful to have an easy way to control optional building of libraries other than by library dependencies.

**Comment by camlspotter** [comment]
> you could express that the library only exists if a file is present, but this file couldn't be a generated file.

Could you tell me how to do this?  There is a declaration other than ’libraries’ to inject dependency to control the optional build of a library?

**Comment by diml** [comment]
I was thinking out loud about how to implement such a feature. It's not straightforward basically. For now, the answer is no, you can only control the build of optional libraries via the `libraries` field.

Given that the fix in findlib is trivial, I don't believe we need a workaround in Dune.

**Comment by hhugo** [comment]
js_of_ocaml work around this issue using jbuild's ocaml syntax.
See https://github.com/ocsigen/js_of_ocaml/blob/master/lib/lwt/graphics/jbuild

**Comment by camlspotter** [comment]
@hhugo, thanks!  I will try that direction!

**Comment by camlspotter** [comment]
@diml, thanks for the info!

**Comment by diml** [comment]
Actually I thought of a simple workaround: #574
