### ISSUE TITLE
include stanza doesn't work with OCaml syntax

### ISSUE THREAD

**Issue by dra27** [ocaml/dune#564]
Easiest repro is to alter the `include-loop` blackbox test `jbuild` file to:

```
(* -*- tuareg -*- *)

let () = Printf.ksprintf Jbuild_plugin.V1.send {|
(jbuild_version 1)
(include a.inc)
|}
```
which gives:
```
File "_build/.jbuilds/default/jbuild", line 3, characters 0-15:
Error: File _build/.jbuilds/default/a.inc doesn't exist.
```
This may be related (or even the underlying cause?) to #431.

**Comment by dra27** [comment]
(I'm just recording this failure - I've actually hit it while in the process of using the include stanza to eliminate OCaml syntax for a jbuild file!)

**Comment by rgrinberg** [comment]
This problem as is acknowledged, but we have no plans to improve the OCaml syntax of dune files.
