### ISSUE TITLE
Nested variables do not work

### ISSUE THREAD

**Issue by samoht** [ocaml/dune#566]
I am trying to do something like:

```
${exe:${ROOT}/foo/bar.exe}
```

But this doesn't seem to work. I am doing this because I am trying to run a private binary in some rule. Is there a better way to do this?

**Comment by diml** [comment]
At some point I was wondering about allowing to give a name to a binary that would be available in all the current scope.

**Comment by diml** [comment]
For this I suggest the following syntax: `%{exe:%root/foo/bar.exe}`. It avoids the nesting of `{` and it would be hard to support all forms nested anyway. One thing we need to do as part of the syntax adjustments we are doing for 1.0.0 is make sure that literal `%` characters must be escaped as `%%` inside the payload of such forms.

**Comment by rgrinberg** [comment]
So we wouldn't support double nesting like: `%{read-lines:%{ocaml-config:foo}}`?

**Comment by diml** [comment]
I suppose we could add it latter if we needed it, it wouldn't be a breaking change. Personally I find the lighter syntax nicer.

**Comment by diml** [comment]
We discussing this more, nested variables complicate things a bit and it's not clear it is the right solution to this problem. For this problem it would be better to have the ability to give a name to a private executable that is available in the current project, so that we can use like a public executable even though it is not installed.

**Comment by samoht** [comment]
>  it would be better to have the ability to give a name to a private executable that is available in the current project, so that we can use like a public executable even though it is not installed.

sounds good to me

**Comment by rgrinberg** [comment]
I'm closing this issue until new arguments are brought up in favor of this feature. Feel free to bring up more use cases where this is needed.

**Comment by samoht** [comment]
Is it now possible to give a name to private executable? How does it work?

**Comment by diml** [comment]
@samoht it's not possible yet. Could you open a separate issue for that?
