### ISSUE TITLE
runtest aliases create unintended dependency on internal libary

### ISSUE THREAD

**Issue by paurkedal** [ocaml/dune#568]
While trying to fix  ocaml/opam-repository#11495 I hit what I think is a bug in dune (or rather, still jbuilder 1.0+beta18).  The attached file is a simplified source directory to reproduce the problem.  It contains two independent libraries `lib1` and `lib2` each with their own tests `test1` and `test2`, respectively.  All `.ml` files are empty and there are now cross dependencies.  I get the following error when running tests for either of them, say lib1:
```
$ jbuilder runtest -p lib1 --debug-dependency-path
File "jbuild", line 33, characters 1-56:
Error: Library "lib2" not found.

Hint: try: jbuilder external-lib-deps --missing -p lib1 @runtest
Dependency path:
    alias runtest
--> alias runtest
--> test1.exe
--> .merlin-exists
--> .merlin
```
If I interpret this right, the `.merlin` file gets a dependency on both libraries.

The issue can be avoided by putting the libraries and tests in separate directories.  Some solutions I can think of:
* Omit the `.merlin` file if `-p` is specified, if the option is mainly meant for opam builds and pre-release testing.
* Only build the part of the `.merlin` file requested by the `-p` option.
* Require that separate packages are built in separate directories, preferably adding a check to dune to enforce it, or at least document it.

[dune-cross-deps.tar.gz](https://github.com/ocaml/dune/files/1772833/dune-cross-deps.tar.gz)

**Comment by diml** [comment]
Thanks for the reproduction case. This is indeed a bug, I changed things so that errors occurring during the generation of the .merlin file are ignored.

**Comment by paurkedal** [comment]
Nice!
