### ISSUE TITLE
Preview `jbuilder promote` changes

### ISSUE THREAD

**Issue by samoht** [ocaml/dune#571]
Currently the only way (that I found) to preview the changes done by `promote` is to do something like: `jbuilder promote && git diff` which is not really optimal (especially if I am not really sure if I want to promote these changes).

Instead, it would be great to have something like `jbuilder promote --preview` which will run the diff program between the `.corrected` files.

**Comment by rgrinberg** [comment]
Sounds like a good idea. However, this should really be its own command as its not actually promoting anything.

**Comment by emillon** [comment]
Duplicate of #5368

**Comment by rgrinberg** [comment]
Let's continue the discussion in #5638 as it's a little fuller.
