### ISSUE TITLE
Select compilation asset based on `alias`

### ISSUE THREAD

**Issue by toots** [ocaml/dune#5764]
## Desired Behavior

It would be great to be able to pick specific compilation assets based on the alias being ran.

## Example

As we prepare on switching to `dune` for liquidsoap, we would like to be able to build with or without using `dune-site`. For `windows`, for instance, we need a standalone binary where those paths are expected locally instead of as defined by `opam`/`dune`.

The current solution is to use an `env` variable:
```dune
(rule
 (target liquidsoap_paths.ml)
 (action
  (copy liquidsoap_paths.%{env:LIQUIDSOAP_BUILD_TARGET=default}.ml %{target})))
```

It would be great, however, to be able to generate this file based on the alias being ran, for instance something like this:
```dune
(alias
 (name standalone)
 (deps (alias_rec install)))

(rule
 (target liquidsoap_paths.ml)
 (action
  (copy liquidsoap_paths.%{alias_name}.ml %{target})))
```

**Comment by emillon** [comment]
Hi,
I don't think that this is possible, because a given rule might be firing because of different aliases.
What you're after is a sort of dynamically-bound variable and the environment is a good way to emulate them.
Thanks
