### ISSUE TITLE
(3.2.0 bug?) failed to create directory in rule

### ISSUE THREAD

**Issue by Nymphium** [ocaml/dune#5788]
dune file is:

```lisp
...
(rule
 (alias runtest)
 (target node_modules)
 (deps
  (:tgz node_modules.tgz))
 (action
  (bash "tar xf %{tgz}")))
```

and when I upgrade dune from 3.1.1 to 3.2.0 then get an error

## Expected Behavior
Unpack `node_modules`

## Actual Behavior

```
File "test/dune", line 10, characters 0-112:
10 | (rule
11 |  (alias runtest)
12 |  (target node_modules)
13 |  (deps
14 |   (:tgz node_modules.tgz))
15 |  (action
16 |   (run tar xf %{tgz})))
Error: Error trying to read targets after a rule was run:
- test/node_modules: Unexpected file kind "S_DIR" (directory)
```

## Reproduction

- PR with a reproducing test: 

1. `mkdir node_modules && tar cf node_modules.tar.gz node_modules`
1. copy-and-paste above dune
1. run `dune test`

## Specifications

- Version of `dune` (output of `dune --version`): 3.2.0
- Version of `ocaml` (output of `ocamlc --version`): 4.13.1
- Operating system (distribution and version): ArchLinux

## Additional information 
However, when I run action `(run mkdir node_modules)` I get no error. It is inconsistent behavior 🤔

**Comment by Alizter** [comment]
On main I get this error:
```
File "dune", line 2, characters 0-115:
2 | (rule
3 |  (alias runtest)
4 |  (target node_modules)
5 |  (deps
6 |   (:tgz node_modules.tgz))
7 |  (action
8 |   (bash "tar xf %{tgz}")))
Error: This rule defines a target "node_modules" whose name conflicts with a
source directory in the same directory.
Hint: If you want Dune to generate and replace "node_modules", add (mode
promote) to the rule stanza. Alternatively, you can delete "node_modules"
from the source tree or change the rule to generate a different target.
```

**Comment by Alizter** [comment]
Ah wait, you want to create a directory with your rule right? Then you need to use directory targets.
