### ISSUE TITLE
Support a file list in `cat` user action

### ISSUE THREAD

**Issue by MisterDA** [ocaml/dune#5795]
## Desired Behavior

The `cat` user action could support a list of files to concatenate, instead of currently a single file. This would allow to concatenate all the dependencies without having to list them by hand (as a combination of `with-stdout-to`, `prog`, and `cat` could achieve).

## Example

(this is perhaps not a valid cram test but I hope you'll get the idea)

```
  $ echo '(dune lang 3.2)(name test)' >dune-project
  $ echo hello >hello; echo world >world
  $ cat >dune <<EOF
  > (rule
  >  (targets file)
  >  (deps hello world)
  >  (action (with-stdout-to %{targets} (cat %{deps}))))
  > EOF
  $ dune build @all
  $ [ "helloworld" == "$(cat file)" ]
```

**Comment by nojb** [comment]
Sounds reasonable.
