### ISSUE TITLE
[minor] XDG default values do not seem right under Windows

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#5808]
In `Xdg`:

- `XDG_CACHE_HOME` --> `%HOME%/Local Settings/Cache`
- `XDG_CONFIG_HOME` --> `%HOME%/Local Settings`
- `XDG_DATA_HOME` --> `%APPDATA%`

This does not seem very good as the `HOME` environment variable is not typically defined on Windows (it is under Cygwin, but that is an "accident").

Instead, suggest the following correspondence:

- `XDG_CACHE_HOME` --> `%TEMP%`
- `XDG_CONFIG_HOME` --> `%LOCALAPPDATA%`
- `XDG_DATA_HOME` --> `%LOCALAPPDATA%`

This coincides eg with what is done in Racket https://docs.racket-lang.org/basedir/index.html

**Comment by jonahbeckford** [comment]
I'll mention that Opam also equates `XDG_CONFIG_HOME` with `%LOCALAPPDATA%`. See https://github.com/ocaml/opam/pull/4815#issuecomment-910137754 . That is great!

Only thing I would add is that `XDG_CACHE_HOME` is probably better as [FOLDERID_InternetCache](https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid) like is used in [GLib on Windows](https://docs.gtk.org/glib/func.get_user_cache_dir.html). The problem with `%TEMP%` is that Windows does not delete the files in it; you (the developer) are expected to clean up after yourself. The Internet Cache folder is a much more managed cache and is the first thing that Windows suggests to delete when the system drive is running out of space; it can also be deleted from the Control Panel.

The only annoying thing with the cache folder is that its value should be looked up with a Windows API (there is a C code sample in the FOLDERID_InternetCache link above) or with `cygpath --folder 32 --absolute --windows`.
