### ISSUE TITLE
Declare explicit dependencies of libraries/executables

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#582]
I have the following situation: I define a `library` that links in a C static library `libfoo.a`. There is a `rule` to produce `libfoo.a` using an external script. The `library` stanza contains `(c_library_flags (libfoo.a))` but there does not seem to be a way to declare that the `library` depends on `libfoo.a`.

Is there a way to declare this dependency? If not, it seems a good idea to be able to declare "extra" dependencies of the `library` apart from the ones implicitly deduced from the listed `(modules ...)`, `(c_names ...)`, `(libraries ...)`, etc.

**Comment by diml** [comment]
I think this is a case where you need to use `self_build_stubs_archive`. You can check [re2](https://github.com/janestreet/re2/blob/master/src/re2_c/jbuild) for an example of use

**Comment by nojb** [comment]
Thanks - I will give it a try.

**Comment by nojb** [comment]
Solved the issue in some other way, thanks.
