### ISSUE TITLE
--verbose should not output `$` since this confuses cram tests

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#5828]
When doing a cram test with `--auto-promote`, you might want to pass `--verbose` to dune. Unfortunately, since command line arguments are printed with `$` this causes the cram test to loop. We should replace `$` with something else.

**Comment by emillon** [comment]
a minimal change is to emit a couple spaces before `$`.

**Comment by Alizter** [comment]
FTR I tried https://github.com/ocaml/dune/pull/6345 for the similar issue with the log, but it was decided not to make the log weird for this niche case. I guess we probably won't do anything for this either.
