### ISSUE TITLE
I do not understand this warning : Module "XXX" is used in several stanzas

### ISSUE THREAD

**Issue by ttamttam** [ocaml/dune#583]
Hello,

I do not understand this warning:
```
File "comrt/jbuild", line 1, characters 0-0:
Warning: Module "Comnirt_t" is used in several stanzas:
- comrt/jbuild:8
- comrt/jbuild:3
This will become an error in the future.
```

emitted by jbuilder 1.0+beta18 with the following `jbuild` file.

Isn't it correct?

```
(jbuild_version 1)

(executable(
  (name comrt)
  (libraries (threads atdgen netclient))
))

(library(
  (name comnirt)
  (modules (comnirt_j comnirt_t))
  (libraries (atdgen))
))

(rule(
  (targets (comnirt_j.ml comnirt_j.mli))
  (deps (comnirt.atd))
  (action (run atdgen -j -j-std ${<}))
))

(rule(
  (targets (comnirt_t.ml comnirt_t.mli))
  (deps (comnirt.atd))
  (action (run atdgen -t ${<}))
))
```

**Comment by rgrinberg** [comment]
Yes, the error is a bit confusing. The point here is that if you need to rely on a `modules` field, then you need to use it in all stanzas.

**Comment by diml** [comment]
BTW, why in theory we could support including a module in two different libraries, this would be a nightmare for pretty much all the tools. Assuming that a given .ml file is part of at most one library/executable is a much simpler model.

If you want to use the same .ml file in two different libraries, the best is to put this .ml file in its own library.

**Comment by ttamttam** [comment]
Oh! Stupid me! Thanks for the explanation.

It goes better after I separated comrt executable and comnirt in two directories.
