### ISSUE TITLE
`(public_name -)` different behaviour between `executable` and `executables`

### ISSUE THREAD

**Issue by maiste** [ocaml/dune#5852]
## Expected Behavior

Hi, dear dune maintainers,
While working with `executable` and `executables` I noticed a difference in behaviour with the stanza `(public_name -)` and `(public_names - -)`.
As described in the documentation, they should work the same way:
> The executables stanza is the same as the executable stanza except that it’s used to describe several executables sharing the same configuration, so the plural executables stanza is used to represent more than one executable.

## Actual Behavior

IIUC, the two executables descriptions should work the same way as one is just a contraction of the other one:

1.
```lisp
 (executable
   (public_name -)
   (name example_1)
   (modules example_1)
   (package dune-example))

 (executable
   (public_name -)
   (name example_2)
   (modules example_2)
   (package dune-example))
```

2.
```lisp
 (executables
   (public_names - -)
   (names example_1 example_2)
   (package dune-example))
```

Whereas `2.` works without any issue and the  `-` name is taken as _ignored this field_, `1.` raised the following error:
```
Error: Multiple rules generated for _build/install/default/bin/-:
- examples/dune:3
- examples/dune:9
-> required by _build/default/dune-example.install
-> required by alias all
-> required by alias default
```

## Reproduction

The reproduction steps are:
```
git clone https://github.com/maiste/dune-example.git
cd dune-example
dune build .
```

## Specifications

- Version of `dune` (output of `dune --version`): 3.2.0
- Version of `ocaml` (output of `ocamlc --version`): 4.14.0
- Operating system (distribution and version): Ubuntu 20.04 / EndeavourOS Linux

**Comment by nojb** [comment]
> one is just a contraction of the other one

Orthogonal to the issue described here, but note that this is not actually correct: `executables` allow _sharing_ modules between the different executables, while this is not possible if you replace it by multiple `executable` stanzas. Probably a good idea to fix the documentation to point this out.

> raised the following error:

This is probaly because using `-` in a single-executable stanza doesn't make a lot of sense: you may as well just supress the `public_name` field altogether. On the other hand, it may be a good idea to implement the same behaviour as for `executables` just for the sake of uniformity.

**Comment by maiste** [comment]
> Orthogonal to the issue described here, but note that this is not actually correct: `executables` allow _sharing_ modules between the different executables, while this is not possible if you replace it by multiple `executable` stanzas. Probably a good idea to fix the documentation to point this out.

Apart from the possibility of sharing modules between executables, are they acting in the same way or is there other difference?

> This is probably because using `-` in a single-executable stanza doesn't make a lot of sense: you may as well just supress the `public_name` field altogether. On the other hand, it may be a good idea to implement the same behaviour as for `executables` just for the sake of uniformity.

I agree that we should be able to remove this `(public_name -). However, it needed to be used in case of some examples... This is the only hack I found to bypass the problem mentioned in [ocaml/dune#5621](https://github.com/ocaml/dune/issues/5621). 
By the same behaviour, do you that if `(public_names - - -)` look like this, it should raise an error?

**Comment by nojb** [comment]
> By the same behaviour, do you that if `(public_names - - -)` look like this, it should raise an error?

No, I mean that any `-` in the public name fields (either in `executable` or `executables` stanzas) should be ignored.

**Comment by Alizter** [comment]
@emillon It seems to me like executable and executables have their public_name's validated differently.

**Comment by maiste** [comment]
There was indeed two issues in this issue:
- The problem with the documentation which was fixed in the PR you mentioned.
- The inconsistent behaviour of `-` which is still an issue.

**Comment by maiste** [comment]
Yes, I agree with this proposition :+1:
