### ISSUE TITLE
dune build fails with devcontainer

### ISSUE THREAD

**Issue by fortierq** [ocaml/dune#5871]
Hello,
I am using a .devcontainer folder with Visual Code (for containerized development) but it causes the following error with `dune build`:
```
dune build
File "a.devcontainer", line 1, characters 0-0:
Error: File unavailable: .devcontainer
Broken symbolic link
```
How to deal with this? Everything works fine without the devcontainer but I want to keep using it.

**Comment by emillon** [comment]
Hi.
Can you post the output of `ls -l .devcontainer` ?

**Comment by fortierq** [comment]
As the error message suggests, it was a broken symbolic link inside the image. Sorry for the inconvenience.
