### ISSUE TITLE
Dune does not generate .cmt files for modules in non-public libraries

### ISSUE THREAD

**Issue by reubenrowe** [ocaml/dune#5885]
Dune does not appear to generate `.cmt` files for modules within libraries that are not public (i.e. do not have a `(public_name ...)` field in the library stanza). I note that it does produce the `.cmti` files in this case, though.

I accept that this is not a "bug" as such, but for those developing tools that use `.cmt` files (in my case, `rotor`), this may be a problem. If this is not considered a bug, then I think it should be considered as a feature request.

**Comment by nojb** [comment]
Dune will build normally build `.cmt` for all libraries, not just public ones. Which command-line did you use?

**Comment by reubenrowe** [comment]
Ah, yes I see.

I was just running `dune build`, so building the default target (i.e. only installable things).

If I run `dune build @check` or `dune build @all`, then I get the `.cmt`s I am expecting.

Thanks!

**Comment by ejgallego** [comment]
Maybe https://github.com/ocaml/dune/issues/4892 is related?
