### ISSUE TITLE
Non-deterministic reporting of errors

### ISSUE THREAD

**Issue by rdavison** [ocaml/dune#589]
When we have errors arising in multiple files, it is annoying that multiple invocations of dune will often report the errors in a different order.  I propose that we should collect the error messages into a list and sort the list based on the path to the file reported by the error message.

**Comment by rdavison** [comment]
Certainly, I'd be glad to

**Comment by diml** [comment]
Ok, so all the errors are reported by `src/report_error.ml` using a single `print_to_console` call. You can update this code to store the error in a table instead and add a function in this module to actually print the error. The key should be the `hash` variable. We hash errors to be sure the same error is not reported twice.

The configuration file is handled by the `Config` module. You can add an option for this there.

The command line parsing should go in `let common =` in `bin/main.ml`. We also need a global variable in `src/clflags.mli` for this, that should be set by `set_common` in `bin/main.ml`.

**Comment by emillon** [comment]
Fixed in #4634 - you can pass `--error-reporting=deterministic` to get this behavior.
