### ISSUE TITLE
Overlapping library names aren't allowed

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#591]
For example:

```
(library ((name foo) (public_name abc)))
(library ((name bar) (public_name foo)))
```

This will say that `foo` and `bar` have conflicting names. Shouldn't this be technically allowed?

**Comment by diml** [comment]
What would `foo` refer to?

**Comment by rgrinberg** [comment]
Well, I don't need to use foo. I just keep using `abc` and `bar` to refer to the libraries properly.

**Comment by diml** [comment]
Do you have a use case for this?

**Comment by rgrinberg** [comment]
Yup. I would like to refactor camomile so that the `Camomile` module becomes the toplevel module. Unfortunately, I cannot assign the `camomile` findlib name to this module because it's already taken by camomile itself. So what I'd like to do is something like:

```
(library ((name camomile) (public_name camomile.lib)))
(library ((name camomileLibrary) (public_name camomile) (libraries (camomile.lib))))
```

I realize this is all a bit of a hack, but I don't see another way of maintaining backwards compatibility as jbuilder doesn't allow me to have more than 1 toplevel name for a wrapped lib.

**Comment by diml** [comment]
What about keeping the main `camomile` library unwrapped exposing both modules `Camomile` and `CamomileLibrary`?

**Comment by rgrinberg** [comment]
Yeah, I can do that. But then I can't use module aliases which I'd prefer to. I suppose there's no sane way to make this work.

**Comment by rgrinberg** [comment]
Actually, this doesn't really work for me as `Camomile` is basically a pack of all the constituents modules `UChar`, `ISet`, etc. I'd hate to be manually packing that stuff like I am with cppo.

What I can do for now is to forego the `Camomile` name and just use `CamomileLibrary` for the main pack. I suppose I can transition to `Camomile` later.

**Comment by diml** [comment]
what about this:

```scheme
(library
  ((name camomileLibrary)
   (public_name camomile.lib)))

(library
 ((name camomile)
  (public_name camomile)))
```

with this in `camomile.ml`:

```ocaml
include CamomileLibrary
```
