### ISSUE TITLE
Allow (run name.exe) to run executable in the current directory

### ISSUE THREAD

**Issue by Chris00** [ocaml/dune#592]
Currently, `(run ${<})` runs the executable pointed by `${<}` because the latter is a path but will says it does not find the program with `(run "${<}")` or with `(run name.exe)` where `name.exe` is the executable name.  The workaround is to write `(run "./${<}")` or `(run ./name.exe)`.  Note that the error message
```
Error: Program name.exe not found in the tree or in PATH (context: default) 
```
is not helpful because `name.exe` **is** in the tree.

**Comment by dra27** [comment]
Doesn't `(run ${path:name.exe})` also do this?

**Comment by Chris00** [comment]
Indeed, it seems to work too.  The error message should definitely suggest this.

**Comment by dra27** [comment]
Although it might be better for `(run ...)` to do more "clever" things with the first parameter anyway. The `${path:...}` trick is worth more mention, as it's also a nice way of annotating some actions to create inferred rules.

**Comment by rgrinberg** [comment]
Just an FYI, you probably want `${bin:...}` or `${exe:...}` in this case and not `${path:..}`.

**Comment by rgrinberg** [comment]
Note that it's on purpose that `./foo.exe` and `foo.exe` aren't the same. I suppose we can improve the error message to suggest the local path when the global one doesn't exist.

**Comment by rgrinberg** [comment]
I'm inclined to close this as we are really not going to change the semantic here. Adding a better error message is nice, but it would be wrong to do it just for this special case. We should have mechanism to suggest proper target names in any position where a user might mistype them.
