### ISSUE TITLE
Disable tests depending on utop/odoc/migrate-parsetree if these libraries aren't present instead of failing

### ISSUE THREAD

**Issue by TC01** [ocaml/dune#593]
Would it be possible for these sorts of tests to not fail but simply not be ran when these applications aren't installed?

For example, currently the test "test/blackbox-tests/test-cases/utop" will fail if utop is not installed, and jbuilder/dune will print out:

```
+  Error: Library "utop" not found.
+  
+  Hint: try: jbuilder external-lib-deps --missing --root . forutop/.utop/utop.exe
```

I run the tests from inside Fedora's buildsystem when building the jbuilder package (currently just using "make test"). It is not practical to have the package pull in utop (or odoc, or migrate-parsetree) at build time, as utop and a bunch of its dependencies require jbuilder to build. And we also cannot install the test libraries from inside the build process using opam, as Fedora builds must be ran with no network access. 

But I'd like to run the rest of the tests, if possible, so I don't want to disable the entire test suite.

Alternatively, is there an easy way to turn off specific tests? For beta 17, I wrote a patch that deleted the relevant stanzas from [this jbuild file](https://github.com/ocaml/dune/blob/master/test/blackbox-tests/jbuild), but now the patch doesn't cleanly apply against beta18, so rebasing it for every release is going to become frustrating.

**Comment by rgrinberg** [comment]
We could add a target to collect all tests that don't have external dependencies.

**Comment by TC01** [comment]
This would be really useful. :)

**Comment by TC01** [comment]
Sorry to nag, but any chance of an update / fix for this soon?

For the moment, I am resorting to disabling all the blackbox tests (but still running the unit tests). It would be nice if this was not necessary.

**Comment by rgrinberg** [comment]
Feel free to nag away. As a matter of a fact we do have a possibly working solution to this. The `runtest-no-deps` alias tracks tests which do not have external dependencies. Give it a try and see if it's good enough.

**Comment by TC01** [comment]
Oops, sorry for not getting back sooner.

I built dune 1.0.1 with the runtest-no-deps alias and it worked very well! There looked to still be tests which wanted ocaml-migrate-parsetree, which is a bit unfortunate because migrate-parsetree is built with dune... but it's still better than before.

**Comment by rgrinberg** [comment]
I see. Okay, I suppose we should really mark any tests that use ppx as having external dependencies.

**Comment by TC01** [comment]
Great, with the patch from #1113 things seem to be good now. Thanks!
