### ISSUE TITLE
[RFC] Link time code generation

### ISSUE THREAD

**Issue by diml** [ocaml/dune#594]
It'd be nice to support special libraries whose implementation would be generated at link time. Here are several uses cases:

## Build info

```ocaml
module Dune_build_info : sig
  (** If inside git, this is the output of [git describe ...] *)
  val vcs_head : string option

  (** Project version *)
  val version : string

  (** For things that dynamically load libraries *)
  val linked_in_libraries : string list
end
```

## Ocaml config

This could be used for all configurator scripts:

```ocaml
module Dune_ocaml_config : sig
  val version : int * int * int
  val standard_library : string
  ...
end
```

all you'd have to do is add `dune.ocaml_config` in the `libraries` field and we'd get this library with the values instantiated with the current build context configuration.

**Comment by rgrinberg** [comment]
Will there be a way for a user to add their own variables? I'm thinking of the configurator use case where a user wants to pass custom arguments. We could add either add a function to fetch such arguments into the module. Or just generate a binding for every argument.

I'm also for the feature btw. I'm also wondering if we could implement this feature in terms of variants as well. I'm thinking of generating a single library for the link time library, and a variant implementation for every context.

**Comment by diml** [comment]
That seems fine, however the .mli would have to be static, so generating arbitrary bindings wouldn't work.

**Comment by rgrinberg** [comment]
I believe this has been addressed.
