### ISSUE TITLE
`dune build` and `dune build -p name` rebuild each other

### ISSUE THREAD

**Issue by QinshiWang** [ocaml/dune#5944]
This is a bug report or a question.
## Expected Behavior
On an older version of dune (~2.6), `dune build` and `dune build -p name` are the same (when there is only one project called `name`).

## Actual Behavior
Now on dune 3.3.1, `dune build` after `dune build -p name` or `dune build -p name` after `dune build` cause dune to rebuild everything.

I am working on a Coq project. Both `dune build` and `dune build -p name` generate object files in `_build/default/...vo`. But the generated files (for the same Coq source code) are slightly different and incompatible (if replacing one with another then Coq will detect incompatibility).

## Reproduction
This should be reproducable on any Coq project.

## Specifications

- Version of `dune` (output of `dune --version`): 3.3.1
- Version of `ocaml` (output of `ocamlc --version`): 4.10.0
- Operating system (distribution and version): WSL1 Ubuntu on Windows 10

**Comment by ejgallego** [comment]
Do you have a pointer to a project that showcases this problem? If you have a plugin in your workspace, this could be expected.

If you can't really share the project, we'd need `_build/log` from a clean tree for both cases.

Note that `dune build` and `dune build -p name` do actually build files in different profiles (as documented), so depending on your project, the rebuild could be indeed the right choice for dune to make.

You can use Dune cache tho to alleviate this workflow if you happen to do that often.

**Comment by rgrinberg** [comment]
The real question is, why are you using `dune build -p name` in the first place? In almost all situations, you're you're looking for `dune build name.install`.

**Comment by QinshiWang** [comment]
I put an example here. https://gist.github.com/QinshiWang/20bc2508bcc95d510710506ce11cae69
The log shows the difference. When building with `dune build`, the script is
```
$ (cd _build/default && /home/s-quark/.opam/coq-8.15.2/bin/coqc -q -w -deprecated-native-compiler-option -w -native-compiler-disabled -native-compiler ondemand -R . ProD3 A.v)
$ (cd _build/default && /home/s-quark/.opam/coq-8.15.2/bin/coqc -q -w -deprecated-native-compiler-option -w -native-compiler-disabled -native-compiler ondemand -R . ProD3 B.v)
```
When building with `dune build -p name`, the script is
```
$ (cd _build/default && /home/s-quark/.opam/coq-8.15.2/bin/coqc -q -R . ProD3 A.v)
$ (cd _build/default && /home/s-quark/.opam/coq-8.15.2/bin/coqc -q -R . ProD3 B.v)
```

**Comment by QinshiWang** [comment]
@rgrinberg I have no idea why I should or shouldn't use `dune build -p name`. I didn't find any friendly documentation. I just copied from another project.

**Comment by Blaisorblade** [comment]
The symptoms match https://github.com/ocaml/dune/issues/4553; IIRC, you can fix it by replacing
`(lang dune 2.7) (using coq 0.2)` with `(lang dune 2.8) (using coq 0.3)` like in https://github.com/bedrocksystems/BRiCk/commit/605c56df55177f0ccb8ed8818b8b83f8d13d5311.

**Comment by QinshiWang** [comment]
Yes. This works for me. I think we should close this issue.
