### ISSUE TITLE
Directory targets that contain symlinks

### ISSUE THREAD

**Issue by corwin-of-amber** [ocaml/dune#5945]
## Expected Behavior
If a rule make a directory, and that directory happens to be populated with symbolic links, I expect the symlinks to be present in the compiled tree.

## Actual Behavior

Dune stops processing rules and issues this error:
```
Error: Rule produced a file with unrecognised kind "S_LNK"
```

## Reproduction
E.g. I am using a rule to make `node_modules` by running `npm install`.
My rule is this:
```
(rule
 (targets (dir node_modules))
 (deps
   (sandbox always)
   package.json
   package-lock.json)
 (action
  (progn
   (run chmod +w package-lock.json)
   (run npm install))))
```

(an unrelated wrinkle is that NPM requires write access to `package-lock.json`, but that's NPM's problem IMHO)

- PR with a reproducing test: 

1. Make a directory that contains a `package.json` file, e.g. [this one](https://github.com/nodejs/examples/blob/main/package.json).
1. Add a `dune` file with the rule above (remove the references to `package-lock.json` if you don't want to have one).
1. Run `dune build`.

## Specifications

- Version of `dune` (output of `dune --version`): 3.3.1
- Version of `ocaml` (output of `ocamlc --version`): 4.12.0
- Operating system (distribution and version): macOS Monterey 12.4

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag):

**Comment by ejgallego** [comment]
This is still an issue, on today's main:
```
File "dune", line 19, characters 0-152:  
19 | (rule
20 |  (targets (dir node_modules))
21 |  (deps
22 |    (sandbox always)
23 |    package.json
24 |    package-lock.json)
25 |  (action
26 |   (progn
27 |    (run npm install --no-save))))
Error: Rule produced a file with unrecognised kind "S_LNK"
```

**Comment by ejgallego** [comment]
Ups wait, I think I've messed up.

**Comment by ejgallego** [comment]
What I get now is a different kind of error:
```
found 0 vulnerabilities
File "dune", line 1, characters 0-131:
1 | (rule
2 |  (targets (dir node_modules))
3 |  (deps
4 |    (sandbox always)
5 |    package.json)
6 |  (action
7 |   (progn
8 |    (run npm install --no-save))))
Error: This rule defines a directory target "node_modules" that matches the
requested path "node_modules" but the rule's action didn't produce it
```
That's with a simple rule for node_modules. Will open a new bug.
