### ISSUE TITLE
For conflicting Coq theories, both conflicting theories should be reported

### ISSUE THREAD

**Issue by Blaisorblade** [ocaml/dune#5947]
## Expected Behavior

If my tree has two conflicting `dune` files with the same logical path, I need the report to mention both files.

## Actual Behavior

```
File "fmdeps/cpp2v/theories/dune", line 3, characters 7-14:
3 |  (name bedrock)                ; This will determine the toplevel
           ^^^^^^^
Error: Duplicate theory name: bedrock
make: *** [cpp2v-dune] Error 1
```

To diagnose this, I need to inspect all my `dune` files, but that's painful in my setup:
```
$ find . -name _build -prune -false -o -name dune|wc -l
     199
```

## Reproduction

- PR with a reproducing test: 

1.
1.
1.

## Specifications

- Version of `dune` (output of `dune --version`): `3.1.1`
- Version of `ocaml` (output of `ocamlc --version`): `4.14.0`
- Operating system (distribution and version): MacOS 12.3.1

**Comment by Alizter** [comment]
We have access to both names when we print the message. I guess we could go about printing both.

**Comment by Alizter** [comment]
@Blaisorblade I've patched it so that the error will now list both locations. #5948
