### ISSUE TITLE
Problem using several preprocesses together

### ISSUE THREAD

**Issue by bFrem** [ocaml/dune#5974]
## Desired Behavior
Hello, 
I have some working code with one preprocess 
`   (preprocess (action (run %{bin:cppo} %{input-file})))`
and would like to add another preprocess 
`((pps ppx_let) tVisitorParser)`

 These two preprocesses work separately but I would like to have both and without using `per_module`

I tried to use `pipe-outputs` without sucess.

I'm using :
dune               version 3.3.1
ocaml              version 4.11.1

Any indication would be greatly appreciated.
Regards.

**Comment by bFrem** [comment]
Thank you for the suggestion. 
However it won't work as cppo's `#include` and ppx_optcomp's `[%%import]` are not equivalent and import only works on optcomp directives.

**Comment by emillon** [comment]
Duplicate of #171
