### ISSUE TITLE
manual: list stanzas in alphabetic order

### ISSUE THREAD

**Issue by gasche** [ocaml/dune#6037]
The "stanza reference" pages of the Dune manual ([dune-project](https://dune.readthedocs.io/en/latest/dune-files.html#dune-project-1), [dune](https://dune.readthedocs.io/en/latest/dune-files.html#dune), [dune-workspace](https://dune.readthedocs.io/en/latest/dune-files.html#dune-workspace-1)) shoud be listed in alphabetical order.

Note: this request was a sub-request of [another issue](https://github.com/ocaml/dune/issues/4202) I created back in February 2021, but it was not acted upon yet, possibly because it was not an issue of its own.

**Comment by rgrinberg** [comment]
Resolved by @esope

**Comment by gasche** [comment]
Great, thanks!
