### ISSUE TITLE
Apply `no-buffer` to an alias within jbuild file

### ISSUE THREAD

**Issue by SaswatPadhi** [ocaml/dune#613]
This is related to #107.

I use an alias to generate a file that's used during the build. And I want this process to always run, never be buffered.

It would be nice if we could ask jbuilder to never buffer certain aliases. Just like `(no_dynlink)` for executable, a `(no_buffer)` for aliases would be nice.

**Comment by SaswatPadhi** [comment]
On a second thought, it makes sense to control this from the command line rather than `jbuild`. In my case, it's just awkward to type it every time but it's fine since it's only during development, not in production.

Closing this issue.

**Comment by rgrinberg** [comment]
We could this add as an option in the configuration file. Also, it's also a candidate to be an option for profiles.

**Comment by dra27** [comment]
You should be able to set this kind of behaviour up with #603, I think? The file will be saved, but it will also be regenerated on each run.

**Comment by SaswatPadhi** [comment]
Thanks @dra27 :)

That'd be perfect! I can get rid of the `-f` flag that I was also typing every time, once this feature is pushed to the next beta.

**Comment by diml** [comment]
BTW, one thing to keep in mind is that no buffering is only expected to work well with `-j 1`. If we allow this in jbuild files, it's likely that we would need to make sure such actions don't run concurrently with other actions and that would decrease parallelism.
