### ISSUE TITLE
specify using alternative compiler...

### ISSUE THREAD

**Issue by progman1** [ocaml/dune#6143]
Having tried
```
(binaries (x as ocamlc))
```
in an 'env' stanza and failing to get the desired behaviour of dune
using this alternative compiler, is there in fact a way to do this yet?

**Comment by nojb** [comment]
You closed your issue right away, but note that it is possible to specify the compiler in a Dune build by using
```
(context (default (paths (PATH <path to ocamlc>))))
```
in your `dune-workspace` file.
