### ISSUE TITLE
dune init: port to the cmdliner Cmd API

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#6161]
`bin/init.ml` mentions "when cmdliner supports group, update it". This is a thing now!

_Originally posted by @emillon in https://github.com/ocaml/dune/pull/6038#discussion_r937800738_

**Comment by emillon** [comment]
cc @shonfeder

**Comment by shonfeder** [comment]
I should be able to pick this up. Thanks for spotting the todo and flagging for follow :)
