### ISSUE TITLE
disappearing build artefacts

### ISSUE THREAD

**Issue by progman1** [ocaml/dune#6166]
I've noticed a bug report I made some time ago must have been addressed (after upgrading to 3.4.1)  but the issue is still open (#3638)

In light of this potential for reports to fall by the wayside, I'm necro bumping another report I made that seems to
be unrecognised as a bug:
#5491 

The issue is not that stale artefacts are being deleted prior to rebuilding, which is completely understandable, it is that they don't exist AFTER a rebuild when they ought to.

**Comment by emillon** [comment]
Hi,
These are still open, you can post to them to ask for updates. Please do not open duplicate issues for the same thing.
Thanks
