### ISSUE TITLE
Strange error with directory targets

### ISSUE THREAD

**Issue by ejgallego** [ocaml/dune#6168]
Hi folks, using this simple dune file:

```
(rule
 (targets (dir node_modules))
 (deps package.json)
 (action (run npm install --no-save)))

(alias
 (name node)
 (deps node_modules))
```

`dune build @node` fails with
```
File "dune", line 1, characters 0-95:
1 | (rule
2 |  (targets (dir node_modules))
3 |  (deps package.json)
4 |  (action (run npm install --no-save)))
Error: This rule defines a directory target "node_modules" that matches the
requested path "node_modules" but the rule's action didn't produce it
-> required by alias node in dune:6
```
however `npm install` generates the directory just fine; this is in today's main. Adding sandboxing doesn't alter the result.

**Comment by Alizter** [comment]
Do you have directory targets enabled?

**Comment by ejgallego** [comment]
Yup dune-project is:
```
(lang dune 3.4)
(using directory-targets 0.1)
```

**Comment by emillon** [comment]
to confirm, the action ran in `_build/default` and created `_build/default/node_modules/`?

**Comment by ejgallego** [comment]
Yes @emillon (it is very easy to reproduce, so if someone can confirm it'd be great)

**Comment by ejgallego** [comment]
I'm adding this to the milestone as it could be understood as a regression.

**Comment by ejgallego** [comment]
Yes (tho 3.3 didn't like the symlinks inside node, but we just clean them up and that works)

**Comment by ejgallego** [comment]
@rgrinberg if that serves as a clue, it seems still related to links somehow, the following action still works fine on `main`:
```
 (action
  (progn
   (run npm install --no-save)
   (run find node_modules -type l -exec rm {} ";"))))
```

**Comment by Alizter** [comment]
Repro case here https://github.com/ocaml/dune/pull/6189

**Comment by ejgallego** [comment]
Thanks a lot @Alizter ! This was a tricky one actually

**Comment by Alizter** [comment]
The digest computation for directory targets is broken because when it recuses on the subdirectory it forgets that symlinks are allowed and fails instead.

**Comment by emillon** [comment]
As this is related to directory targets which are experimental, we said that it would be fine to release 3.5 without a fix to this.

**Comment by rgrinberg** [comment]
Bumping this back to 3.5.0 as I have a fix ready.
