### ISSUE TITLE
Add support for Dune action runners

### ISSUE THREAD

**Issue by snowleopard** [ocaml/dune#6199]
A **Dune action runner** is a process that Dune can communicate with via Dune RPC to execute build actions.

It is useful to separate action runners from the main Dune process for more precise action isolation and information flow control. For example, in the context of a big monorepo (like the one we have at Jane Street), we might want to restrict some actions from seeing the whole source tree in order to provide some information flow guarantees, e.g., to prevent information leakage from the private parts of the monorepo to the public ones. To achieve that, we can wrap multiple Dune action runners in different `bwrap` instances (or use some other process isolation mechanism). We expect that we won't need more than a handful of separate runners: each responsible for running actions for a relatively large part of the source tree.

More generally, we usually put more trust in Dune itself compared to the user-written actions that Dune is running, which is why it's useful to run Dune and build actions in differently setup environments.

For the first version, we should assume that action runners run on the same file system as Dune, as otherwise there will be quite a lot of copying of action dependencies. In future, we can consider more advanced configurations, e.g. to execute long running tests remotely by communicating to action runners on other machines.

@rgrinberg I'm assigning this to you, as agreed. Please expand the above spec with more details as needed.

**Comment by snowleopard** [comment]
cc @dkalinichenko-js who is also going to work on this feature.

**Comment by snowleopard** [comment]
Yes, it's fine to assume that the action runner and Dune are the same binary. We might change that in future but no need to overcomplicate things for now.

**Comment by rgrinberg** [comment]
After my discussion with @dkalinichenko-js, we split the work into the following parts:

## Forking Workers

A worker is a dune command started with bubble wrap (after configuring a policy). A forker should know how to connect to the main server. Essentially, we'll be doing something like:

```
$ DUNE_RPC=domain/socket/rpc sandbox.sh -- dune forker start
```

All of this should be done before initializing the build system itself.

The RPC protocol is currently unidirectional in the sense that only the client can make requests to the server. We'll need to make it bidirectional for the server to send requests to the client as well.

## Distribution of Actions

For every action that dune wants to execute, it needs to determine if it needs to be run by a forker. This decision is made by looking at the directory in which the rule that introduced the action.

## Action Output

When a forker executes an action, it will swallow the output for successes and return failures after the output has been post processed. Diana mentioned that actions that are successful are going to be swallowed, but I'm not sure how this will work for anonymous actions that capture their output. Such actions need the stdout to be recorded in the stamp file (`./actions/...`).
