### ISSUE TITLE
`(lint ...)` field is undocumented

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#6201]
I've just noticed that the Buildable.t stanzas all take a `(lint ...)` field however this seems to be undocumented.

What does it do and how should we document it it?

**Comment by emillon** [comment]
Duplicate of #5021

**Comment by emillon** [comment]
to answer the question in a short form: it's sort of similar to `(preprocess)` and attaches results of this preprocessing to the builtin `@lint` alias. ppxlib has builtin support to write ppxes that support this.
