### ISSUE TITLE
Dependency on whole packages

### ISSUE THREAD

**Issue by diml** [ocaml/dune#621]
The idea is to allow to declare a dependeny on all the files in `_build/install` that belong to a package. As a result an action could for instance execute a script that would use all the binaries installed by the package or even call `ocamlfind`.

Syntax:

```scheme
(rule
 ((action (run ocamlfind ...))
  (deps   ((package foo)))))
```

## Implementation

A prerequisite of this feature is to change Dune so that all actions are executed in the same environment as `jbuilder exec`. We can simply change `Context.env` to be the same as `Context.env_for_exec` and remove the latter.

To interpret `(package X)`, we can simply setup an alias that depends on all the relevant file at the same time as setting up the rules for the symlinks in `_build/install`.

**Comment by rgrinberg** [comment]
@diml this is complete I believe.
