### ISSUE TITLE
Initial support for Melange

### ISSUE THREAD

**Issue by jchavarri** [ocaml/dune#6230]
[Melange](https://github.com/melange-re/melange) is a fork of the [ReScript compiler](https://github.com/rescript-lang/rescript-compiler/) with the focus of integrating with the OCaml ecosystem. This is a proposal to add some minimal support for Melange in Dune, specifically as part of the `library` stanza.

## Current status

At the moment, Melange is leveraging Dune as the build system, as a replacement for the original system used in ReScript ([Ninja](https://github.com/rescript-lang/rescript-compiler/tree/02ff4c907ec67c2e31c1e01e24310673e391d1a6/ninja)). However, the integration remains superficial: Melange uses Dune as a rule executing engine, and this process involves Melange writing dune rules in some intermediate file, so `dune` command can read them up and execute them. Dune has no understanding of Melange sources.

This has a few disadvantages:
- For large projects, this 2-step process (dump rules in file, read them up) has a performance cost
- Users of Melange don't have full access to the expressiveness of the Dune language
- Defining builds in codebases with shared OCaml and Melange sources can become challenging

## Proposal

Adding a new mode `melange` to the `modes` field in the `library` stanza, so that Melange users can use it like this:

```dune
(library
 (name my_lib)
 (modes melange))
```

Behind the scenes, when the new mode is selected for a library, Dune would automatically generate rules from `ml*` and `re*` files in the same way it currently does for `byte` and `native` modes. The main differences with `byte` and `native` modes is:

- `melc` is called to generate artifacts, rather than `ocamlc/opt`
- A new object folder `melange` would contain the new mode artifacts (e.g. `_build/default/my_lib/.my_lib.objs/melange` in the example above)
- Specific rules are created for artifacts that are required in Melange (`js` files), and existing rules would be adapted to support Melange case.

Then, users can trigger builds of specific modules targeting the `.js` file inside a given library, e.g.

```bash
dune build my_lib/.my_lib.objs/melange/main.js
```

In terms of generated artifacts from each module, here is the comparison between Melange and the OCaml compiler artifacts:

| Artifact      | OCaml | Melange |
| ----------- | ----------- | ----------- |
| `cmi`      | ✔️        | ✔️  |
| `cmo`      | ✔️        | ✖️  (replaced by `cmj`) |
| `cmx`      | ✔️ (native)      | ✖️ |
| `cmt*`      | ✔️       | ✔️ |
| `js`   |    ✖️   | ✔️ | 

## Limited scope

Melange and Dune are both complex projects. For the sanity of everyone involved 😄 the scope is kept as limited as possible during this first integration. There are a lot of features that could be added over time, but the first step will not include any of them. This is a non-exhaustive list of potential future additions:
- installation of libraries
- es6 / commonjs modules in JavaScript output
- private modules
- virtual libraries
- ReScript syntax
- `executable` stanzas

One priority though is to make sure that the OCaml [VSCode extension](https://github.com/ocamllabs/vscode-ocaml-platform) can work with this deeper Dune-Melange integration. Hopefully, if the scope defined in this issue makes sense, it would be enough to start integrating on the editor side as well.

## Previous work / references

- https://github.com/ocaml/dune/issues/140. Side note: this is still [the most upvoted issue](https://github.com/ocaml/dune/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc) in Dune repo ever with 24 votes 🙂 
- https://github.com/melange-re/melange/pull/200, an RFC that explored this integration
- https://github.com/ocaml/dune/pull/60, the first PR that tackled js_of_ocaml and Dune integration

**Comment by Kakadu** [comment]
Adding support of melange would be very great. I hope a positive construction movement would be a result of this discussion.
Many thanks, @jchavarri for your work

**Comment by rgrinberg** [comment]
Initial prototype is slated for 3.6. Let's track additional features in separate tickets.
