### ISSUE TITLE
I'm seeing a Windows failure when trying to build current Dune master (with this PR).

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#6241]
I'm seeing a Windows failure when trying to build current Dune master (with this PR). 

Here's a GHA run: https://github.com/melange-re/melange/actions/runs/3256688824/jobs/5347432767

And relevant output:

```
      (cd _build/default/otherlibs/xdg && C:\npm\prefix\node_modules\esy\node_modules\esy-bash\.cygwin\bin\x86_64-w64-mingw32-gcc.exe -O2 -fno-strict-aliasing -fwrapv -mms-bitfields -g -I C:/Users/runneradmin/.esy/3__________________________________________________________/i/ocaml-4.14.0-cd77a8d9/lib/ocaml -o xdg_stubs.o -c xdg_stubs.c)
  
      xdg_stubs.c: In function 'dune_xdg__get_known_folder_path':
  
      xdg_stubs.c:35:9: warning: implicit declaration of function 'SHGetKnownFolderPath'; did you mean 'SHGetFolderPath'? [-Wimplicit-function-declaration]
  
         res = SHGetKnownFolderPath(rfid, 0, NULL, &wcp);
  
               ^~~~~~~~~~~~~~~~~~~~
  
               SHGetFolderPath
  
      xdg_stubs.c:41:38: error: 'WC_ERR_INVALID_CHARS' undeclared (first use in this function); did you mean 'MB_ERR_INVALID_CHARS'?
  
         len = WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, wcp, wlen, NULL, 0, NULL, NULL);
  
                                            ^~~~~~~~~~~~~~~~~~~~
  
                                            MB_ERR_INVALID_CHARS
  
      xdg_stubs.c:41:38: note: each undeclared identifier is reported only once for each function it appears in
  
      error: command failed: "dune" "build" "-p" "xdg" "-j" "4" "@install" (exited with 1)
  
 ```

_Originally posted by @anmonteiro in https://github.com/ocaml/dune/issues/5943#issuecomment-1279806620_

**Comment by nojb** [comment]
Isn't this failure rather coming from the build of the `xdg` library (version 3.4.1)?

![image](https://user-images.githubusercontent.com/113560/196003549-39b235d5-2b8b-4b97-a83e-d42a5c365470.png)

(which would be coherent with teh fact that the fix in #6109 is not included in 3.4.1).

**Comment by phated** [comment]
I think @nojb is correct, I needed to add extra resolutions for xdg since the dune monorepo makes both deps depend on similar code

**Comment by phated** [comment]
Fwiw, I wish this fix would have been released as 3.4.2 so we didn't need to wait months for it to be fixed in 3.5

**Comment by anmonteiro** [comment]
@nojb is obviously correct. Sorry for the noise here.

**Comment by emillon** [comment]
@phated right, we expected dune 3.5 to be released earlier. I agree that this could have made it into a point release.
