### ISSUE TITLE
Unwanted module linked if name overlaps 

### ISSUE THREAD

**Issue by bartoszmodelski** [ocaml/dune#6254]
## Expected Behavior
In the following code, I expect only `Queue` from `Lib` to be linked. 
```
open Lib

let () = 
  let () = Sys.opaque_identity (Queue.create ()) in
  Printf.printf "bar"
```
## Actual Behavior

If there's a `Queue` module in the same directory as above file, it also gets linked. 

## Reproduction

Build https://github.com/bartoszmodelski/odd-modules and run `a/test.ml`, `a/test2.ml`. 

## Specifications
```
Dune: 3.4.1
Ocaml: 5.0.0+dev6-2022-07-21
System: Ubuntu 22.04.1 LTS
```
## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag):
https://raw.githubusercontent.com/bartoszmodelski/odd-modules/main/build-verbose.txt

**Comment by nojb** [comment]
This is a known limitation of `ocamldep` (that it performs a purely syntactic analysis), and there aren't any simple solutions to this issue. If you want to avoid mislinking module in question, you can specify the list of modules explicitly in the `executable` stanza by adding a `(modules ...)` field.

**Comment by rgrinberg** [comment]
You can also add `module Queue = struct end` in the beginning of the module to trick ocamldep not to link.

**Comment by bartoszmodelski** [comment]
Thanks!
