### ISSUE TITLE
Support for `or` in opam dependencies generation

### ISSUE THREAD

**Issue by toots** [ocaml/dune#6284]
Reading from the doc, it looks like the `dune-project` support for generating `opam` files does not support top-level `or` (`|` in opam) combinators for dependencies:
```
"depends": [
  "foo" | "bla"
]
```
The template file is not really useful for this either.

**Comment by emillon** [comment]
duplicate of #5815

**Comment by toots** [comment]
Sorry about that!

**Comment by emillon** [comment]
Sorry, "duplicate of XXX" is a bit of an unfriendly message but I don't think there's another way to set this piece of metadata :)

**Comment by toots** [comment]
No pb!
