### ISSUE TITLE
Corner case: executing dune build & dune utop at the same time fails

### ISSUE THREAD

**Issue by rbjorklin** [ocaml/dune#6286]
## Errors
```
❯ dune utop
File ".ppx/bcab0be011c28261c514e69f4fe141f8/_ppx.ml-gen", line 1:
Error: I/O error: .ppx/bcab0be011c28261c514e69f4fe141f8/dune__exe___ppx.cmi: No such file or directory
```
```
❯ dune build @install
Error: near line 303: database is locked
Error: near line 304: database is locked
Error: near line 305: database is locked
```

## Expected Behavior
Both commands succeed.

## Actual Behavior
Executing `dune build @install` and `dune utop` in parallel causes both to fail.

## Reproduction
* `cd <any project>`
* Use tmux/screen and split into two panes
* Type `dune build @install` in one pane, do not press enter
* Type `dune utop` in the other pane, do not press enter
* Enable tmux synchronized panes `:set synchronize-panes`
* Press enter

## Specifications

- Version of `dune` (output of `dune --version`): 3.5.0
- Version of `ocaml` (output of `ocamlc --version`): 5.0.0~beta1
- Operating system (distribution and version): Fedora 36

## Additional information
I'm not sure this is even supposed to work. I just stumbled over this while trying to set up a vim session that starts both in parallel when starting up. I would not be the least bit upset if you decide this is not worth fixing.

**Comment by rgrinberg** [comment]
#6360 will forbid this.

**Comment by emillon** [comment]
Does #6360 fix this, in the end?

**Comment by rgrinberg** [comment]
Indeed it does.
