### ISSUE TITLE
Merlin complainng about expect tests in Beta 19

### ISSUE THREAD

**Issue by yminsky** [ocaml/dune#633]
I'm not sure if this is a replicable issue, and I don't know if this is a Merlin issue. In any case, I'm running with opam2 and with opam fully up to date, installing core, async and the various inline test libraries, along with beta19 of jbuilder. I've attached the list of installed packages.

I can now build an expect test with jbuilder and promote the output, which is great; but Merlin is still unhappy about the state of affairs, responding with this error in emacs:

```
ppx_expect: extension is disabled because the tests would be ignored 
(the build system didn't pass -inline-test-lib) [2 times]
```
I've attached the jbuild file I'm using, as well as the generated dot-merlin file.

[dot-merlin.txt](https://github.com/ocaml/dune/files/1823315/dot-merlin.txt)
[jbuild.txt](https://github.com/ocaml/dune/files/1823317/jbuild.txt)
[opam-list.txt](https://github.com/ocaml/dune/files/1823310/opam-list.txt)

I described this to @diml, who had no obvious ideas what was wrong. I've done a lot of rebooting my emacs and blowing away the dot-merlin file and regenerating, so I don't think there's an issue of some weird old caching. But I'm open to any suggestions here. I'm also wondering if anyone else has seen this issue.

**Comment by mbarbin** [comment]
I have tried to run expect tests as well with 1.0+beta19 but I get this error:
```
File "src/jbuild", line 5, characters 2-16:
Error: No inline tests backend found.
```
In my jbuild I listed ppx_expect explicitly (though I believe it is probably not necessary since it is part of ppx_jane.
```
(jbuild_version 1)

(library
 ((name mylib)
  (inline_tests)
  (libraries
   (core stdio))
  (preprocess (pps (ppx_jane ppx_expect)))))
```
What am I missing?  Did you have to add another step to make it work?

**Comment by diml** [comment]
@mbarbin you need ppx_inline_test v0.10.1 and ppx_expect v0.10.1

**Comment by diml** [comment]
@yminsky I think I found the issue. Could you try pinning `ocaml-migrate-parsetree` to the `fix-global-cookies` branch and `ppx_driver` to the `v0.10` branch?

**Comment by yminsky** [comment]
I'm already using the 0.10 branch of ppx_driver, and flipping to the stated branch of ocaml-migrate-parsetree resolves my issue.

**Comment by rgrinberg** [comment]
@yminsky Seems like this is resolved. Please re-open if there's more issues.
