### ISSUE TITLE
Clash between expect_test and warning 18: record disambiguation not principal

### ISSUE THREAD

**Issue by mbarbin** [ocaml/dune#634]
If your program contains an empty expect section:
```
[%expect{||}]
```
Compiling with warning 18 activated (for example `(flags (:standard -principal))`) will trigger:
```
Warning 18: this type-based record disambiguation is not principal.
```
Has anyone run into it also?

**Comment by xclerc** [comment]
From (very limited) testing, it looks like we just need to change
the `ppx_expect` lifter to add a module prefix to a record label,
*e.g.* generate:
```
{ Expect_test_common.Std.Expectation.tag = ... }
```
rather than:
```
{ tag = ... }
```

**Comment by rgrinberg** [comment]
This seems like an issue with the ppx's rather than dune.
