### ISSUE TITLE
`dune describe workspace` returns an incorrect root

### ISSUE THREAD

**Issue by esope** [ocaml/dune#6379]
## Expected Behavior

`dune describe workspace` should return a (relative or absolute) path to the project's root.

## Actual Behavior

`dune describe workspace` always returns `.` as the workspace root.

## Reproduction

Assume the following setup:

```
foo/
|-- dune-project
|-- a/
    |-- dune
    |-- a.ml
```

where:

- `dune-project` contains `(lang dune 3.5.0)`
- `a/dune` contains `(library (name a))`
- `a/a.ml` is an empty file

When run from `foo/a/`, the command `dune describe workspace` returns `.` as the project's root.
Instead, it should return `..` or an absolute path to `foo/`.

This cannot be tested using cram tests, because paths are sanitized (using the ``--sanitize-for-tests`` flag) so that paths are reproducible (i.e. do not depend on where the test directory is located on the machine where tests are run).

## Specifications

- Version of `dune` (output of `dune --version`): 3.5.0
- Version of `ocaml` (output of `ocamlc --version`): 4.14.0
- Operating system (distribution and version): linux, LinuxMint 21

**Comment by esope** [comment]
Fixed by PR #6380

**Comment by reubenrowe** [comment]
Hi @esope

Yes, this does indeed implement what we wanted. I had actually spotted this bug recently, but not got around to addressing it.

Thanks!
