### ISSUE TITLE
Empty missing dependencies while a (test) package is missing

### ISSUE THREAD

**Issue by xclerc** [ocaml/dune#644]
If one tries to set up inline tests with a `jbuild` file akin to the one below
while the `inline_test` package is not installed, the following message is
output:
```
Error: Library "ppx_inline_test" not found.
Hint: try: jbuilder external-lib-deps --missing @runtest
```

However, the execution of the suggested command line prints nothing.

---
```
(library
 ((name lib)
  (inline_tests)
  (preprocess (pps (ppx_inline_test)))))
```

**Comment by trefis** [comment]
I'm a bit surprised that this issue popped up again (cf #485 ).
Is there no way to add a regression test for this?

**Comment by diml** [comment]
There is a test but it's only testing the `libraries` field, there might be another issue for the `preprocess` field.

**Comment by diml** [comment]
I found the issue. It's a bit annoying to fix and the code that implement `external-lib-deps` already requires to be careful when writing the rules. I have an idea to catch external library dependencies more systematically without having to think about it while the rules, I'm going to try that.
