### ISSUE TITLE
Support for inline tests/benchmarks

### ISSUE THREAD

**Issue by diml** [ocaml/dune#65]
Some thoughts on how to add automatic support for inline tests/benchmarks in jbuilder.

Currently [Jane Street jenga rules](https://github.com/janestreet/jenga-rules) support linking inline test and/or benchmark runners as soon as ones uses ppx_inline_test and/or ppx_bench. Additionally they automatically run the tests in parallel as part of the `runtest` alias.

This is a really useful feature for development and it would be great to add this to jbuilder. The rules are not very complicated to setup, however I'd like to support this without hardcoding the knowledge of the various libraries and their layout (ppx_bench, ppx_inline_tests, ppx_expect, ...) inside jbuilder. This is for two reason:
- to avoid having to update jbuilder whenever the details of these subsystems change. They don't change very often but do change from now and then
- to allow other people to reuse the same mechanism for their own test/benchmark systems

### The runners

For any given library Jbuilder systematically setups rules for building `<lib>-test-runner.exe` and `<lib>-bench-runner.exe` executables. These executables link all of library `<lib>` and are used for running tests and benchmarks respectively.

### Additional runner libraries

The various runners require additional libraries, essentially to report the results at the end. We need two things: a way to specify these additional libraries and a way to specify the code to run at the end of the runner. Currently the jenga rules hardcode this information and know what .cmx/.cmo to link last fo each runner.

#### Specifying additional libraries

We can simply add them in the jbuild of the ppx:

```scheme
(library
 ((name ppx_inline_test)
  ...
  (ppx_runner_library (test ppx_inline_test.runner))))
```

and Jbuilder will know to link `ppx_inline_test.runner` in the test runner of any libraries using this ppx.

#### Specifying the reporter

To make things simple, we provide a small `libmain` library allowing one to set the entry point:

```ocaml
(** Set the main entry point of the program *)
val set_main : (unit -> unit) -> unit

(** Execute the registered entry point. Never returns *)
val run_main : unit -> _

(** Are we linked as part of a library test/benchmark runner or a normal executable? *)
val is_library_runner : unit -> bool
```

and jbuilder will add a module that calls `run_main` as the last .cmx/.cmo on the command line to link the runner.

### running tests in parallel

We formalise the convention of ppx_inline_test for running tests in parallel: `foo-runner.exe --list-partitions` returns a list of partitions and `... --partition blah` selects tests from partition `blah`.

### Runtime test dependencies

Sometime inline tests require extra dependencies when running. For instance when they read a file. The jenga rules support this by looking for an `(inline_tests ...)` field in `(library ...)` stanzas:

```scheme
(library
 ((name foo)
  ...
  (inline_tests ((deps (blah))))))
```

We can do the same in jbuilder.

### helper scripts

The jenga rules generate helper shell scripts allowing one to run the tests/benchmarks manually. Instead, ppx_inline_test can provide an executable to call the generated runner appropriately. Alternatively we could extend `jbuilder exec` so that one can do:

```
$ jbuilder exec ./foo-test-runner.exe ...
```

**Comment by jyc** [comment]
This would definitely be a super useful feature! I could try to implement it, if you don't think it'd be too hard/subtle for someone new to the codebase.

**Comment by diml** [comment]
That would be really cool! It is quite a bit of work, some of it is straightforward and some of it is more complicated. This will also require modifications to ppx_inline_test and ppx_inline_bench. Happy to point you to the right places if you want to give it a try.

I updated the description as the original proposal merged tests and benchmarks and @sliquister pointed that this wasn't a good idea given that for instance ppx_bench links quite a lot of stuff that we don't want for just running tests.

**Comment by rgrinberg** [comment]
Since, I'd like to use this feature myself so I'd love to help out. @jyc take this on and I can help out with the parts that you're less comfortable with.

**Comment by jyc** [comment]
Thanks diml and rgrinberg! Very neat, thanks so much for the offer of help too @rgrinberg! I can set aside time to start on this next weekend--so if you'd like to begin work on it sooner, I could step aside and try to help out where needed.

**Comment by rgrinberg** [comment]
@jyc go right ahead, I'm not in a rush. I think increasing the number of contributors to jbuilder is extremely important so I welcome your initiative.

**Comment by diml** [comment]
So the first part of the work should be pretty straightforward. Essentially `ppx_runner_library` works almost the same as `ppx_runtime_libraries`, so most of the infrastructure is already in place.

The overall plan is as follow:

1. extend the syntax of `library` stanza to support `(ppx_runner_library (test <libname>))` and `(ppx_runner_library (bench <libname>))`. You need to modify `src/jbuild.ml` for that
2. choose how this information will be encoded in META files, for instance it could be encoded as `ppx_runtime_deps(test-runner)` and `ppx_runtime_deps(bench-runner)`
3. add the two necessary fields to `Findlib.package` and extend the parsing of META files in `src/findlib.ml`
4. extend the generation of META files to include the new information, you can basically copy&paste what `ppx_runtime_deps` does
5. setup how the transitive closure of runtime dependency is computed. You can basically copy&paste the following functions: `Super_context.Libs.load_runtime_deps` and `Super_context.Libs.setup_runtime_deps`. `setup_runtime_deps` is called once in `gen_rules.ml`. You'll need to call the two new `setup...` functions there as well
6. write the `libmain` library. To implement `is_library_runner` we might need something like #136, but in the meantime we could use a trick using weak symbols
7. Setup the rules to build the runners. They need to be added in the function `library_rules` in `src/gen_rules`, and you can use the `build_exe` function to generate the rule to build the executable
8. Update ppx_inline_test to work with the new conventions and test it

There are a few points that will need more details. I can help and provide more explanation as you make progress.

**Comment by jyc** [comment]
Thanks! Sorry–ended up swamped with work this weekend. I can start on Tuesday, but I don't want to end up getting this issue stuck in a loop where it isn't clear who is working on it, so if I don't start at by then (or even if someone else would like to take this right now), someone else should just pick it up. Sorry again for the delay, would be very exciting to have this feature instead of the hacky thing I have right now.

**Comment by diml** [comment]
No problem, there is no rush. Feel free to open a PR when you start working on this

**Comment by basus** [comment]
Has there been any progress on this? If not, is there a non-automatic way to use `ppx_inline_test` with `jbuilder` currently? I've tried adding both `ppx_driver.runner` and `ppx_inline_test` to the `preprocess` section, but I get errors saying:

```
Error: ppx_inline_test: extension is disabled because the tests would be ignored (the build system didn't pass -inline-test-lib)
```

**Comment by jyc** [comment]
Hi @basus, I haven't had time to make any progress on this, sorry (deadlines at work), though, like I mentioned earlier, this sounds like it's something that'd be very useful so I think someone else should pick it up if they can! I think diml would know more about whether others have made progress.

**Comment by rgrinberg** [comment]
I'll tackle this as soon as I wrap up `jbuilder utop` (which just needs some UI tweaks + docs). I will tentatively assign this to myself but I welcome collaboration from anyone who wants to work on this. There's plenty of work here, and I'm always happy to encourage more contributors to jbuilder.

**Comment by diml** [comment]
@basus what version of jbuilder and ppx_inline_test are you using? It should work with the latest versions

**Comment by basus** [comment]
According to OPAM, I'm running version `1.0+beta10` for jbuilder and `0.9.1` for ppx_inline_test. It's possible that I'm just not using the correct incantation as part of my `jbuild` file. Is there a working example I could look at?

**Comment by diml** [comment]
Most Jane Street code is preprocessed with ppx_inline_test, so you could look at core for instance. You can also look at [this repository](https://github.com/diml/memory-access-bench). It uses ppx_bench but it works the same way as ppx_inline_test

**Comment by rgrinberg** [comment]
@diml will ppx_inline_test preprocess the libraries unconditionally? I see that janestreet's repos today all use ppx_inline_test  (through ppx_jane) but this might not be acceptable for regular users who are used to making their test dependencies optional.

**Comment by diml** [comment]
Well, if the syntax uses extension points, there is not much choice: the extension points have to be dropped otherwise the compiler will choke on them

**Comment by rgrinberg** [comment]
This has been addressed and released.
