### ISSUE TITLE
wrong include directories when calling odoc

### ISSUE THREAD

**Issue by trefis** [ocaml/dune#651]
When I look at the log for base after having called `jbuilder build @doc` I see the following:
```
$ (cd _build/default/_doc/base &&
   odoc compile -I ../../src/ -I <opam switch>/lib/sexplib0
     -I ../../compiler-stdlib/src/.caml.objs
     -I ../../shadow-stdlib/src/.shadow-stdlib/src/.shadow_stdlib.objs
     --pkg base -o base.odoc ../../src/.base.objs/base.cmt
  )
...
$ (cd _build/default/src &&
   odoc html -I ../_doc/base -I <opam switch>/lib/sexplib0
     -I ../compiler-stdlib/src/.caml.objs -I ../shadow-stdlib/src/.shadow_stdlib.objs
     -o ../_doc ../_doc/base/base.odoc
  )
```

This is wrong. It gives the (OCaml) compilation include directories, whereas it should pass directories where to find .odoc files; e.g. `_build/default/_doc/base` and such (and nothing for installed dependencies / dependencies not part of the workspace).
This is true for both the `compile` and `html` steps.

---
As a side remark: I find it surprising that the html step doesn't happen from the `_doc/pkg` directory.

**Comment by trefis** [comment]
Note: that was with beta19.1, I'll try to reproduce with master just to make sure.

**Comment by trefis** [comment]
With master the `html` step seems correct but the `compile` one is still wrong.

**Comment by rgrinberg** [comment]
Btw, I'm going back a few versions and I always see the `-I` flags that are being passed are from `Lib.include_flags`. Did it ever work right?

**Comment by trefis** [comment]
Not sure what you mean by "works".
Just like the compiler, `odoc` doesn't mind if there is nothing to be found in its load path, it won't error, but you won't have many links.

If I look at the generated doc for base though, it's pretty clear that "it doesn't work".

**Comment by trefis** [comment]
I know that beta16 was OK, anything after that I have no idea.

**Comment by rgrinberg** [comment]
Isn't this line the problem: https://github.com/ocaml/dune/blob/1.0%2Bbeta16/src/odoc.ml#L139

Seems like beta16 was passing the library include flags just the same.

**Comment by trefis** [comment]
I guess that beta16 was also storing the .odoc along the .cmt / .cmti files.
Which isn't the case anymore.

**Comment by rgrinberg** [comment]
This is fixed in master.

**Comment by stevebleazard** [comment]
The fix seems to have resolved the dangling link issue I reported as an odoc issue ([ocaml/odoc#113](https://github.com/ocaml/odoc/issues/113)), but results in a document structure that does not seem right - see the odoc issue for details
