### ISSUE TITLE
Regression: auto-generated entry-point modules are being marked as deprecated

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/dune#6545]
## Expected Behavior

When a module is autogenerated as exposing all modules as library, it should be possible to access all submodules without issues.

An example of this is opam-monorepo which declares `Duniverse_lib`, but doesn't have a `duniverse_lib.ml`, so dune generates one which contains references to all modules in the library. This works fine until dune-lang 3.5, but past that the auto-generated `duniverse_lib.ml` is marked as deprecated, thus leading to build failures if deprecation warnings are configured to be errors.

## Actual Behavior

Since #6126 in dune-lang 3.5+ modules that are not meant to be accessed are marked as deprecated. This is nice, but unfortunately it also affects packages which don't have a main entry-point module, thus any access to the library causes deprecation warnings.

## Reproduction

- PR with a reproducing test: #6544

## Specifications

- Version of `dune` (output of `dune --version`): 3.6, anything that supports dune-lang 3.5+
- Version of `ocaml` (output of `ocamlc --version`) 4.14
- Operating system (distribution and version): Fedora Linux

**Comment by emillon** [comment]
I agree that this is a regression. We should be doing this only when the module is `Foo__`, not `Foo` (I'm not sure how it translates in the code)

**Comment by Leonidas-from-XIV** [comment]
Ok, after investigating I realized this has little to do with the deprecation. I've been fixing a codebase affected by it and the issue seems to be

```ocaml
open Mylib

(* some code here or whatever *)
let () = Mylib.Foo.main ()
```

This used to be valid before 3.5, it would just access the `Mylib` module. But starting in 3.5 it generates `module Mylib = struct end`, so the generated file shadowns `Mylib`, thus `Mylib.Foo.main` is not accessible anymore.

While I agree that code like this is admittedly _confusing_ and would better be rewritten, the `open Mylib` shadowing itself is rather unexpected, since normally opening a module doesn't seemingly remove the module from the scope.
