### ISSUE TITLE
Bad default interaction with Syntastic when PPXes are used

### ISSUE THREAD

**Issue by mavant** [ocaml/dune#655]
Something that came up this morning during the intro-to-ocaml workshop: One vim-user noted the editor was reporting errors on save at let%test declarations (something like 'module expected after let') in a project that was compiling correctly with jbuilder and had its .merlin file in the correct place.

It turns out that he was missing the
````viml
let g:syntastic_ocaml_checkers = ['merlin']
````
declaration in his vimrc, which resulted in some default checker being used that didn't know about ppx_inline_test (https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/ocaml/camlp4o.vim, I'm guessing, but I don't know).

I'm not sure of the best way to fix this, since it exists in a sort of weird intersection between dune, merlin, and syntastic; maybe the best answer is just to note in the readme that if you want error checking in the editor, you need to be sure to set up merlin.

(cc @kshitijl)

**Comment by rgrinberg** [comment]
The only way this could be related to dune is if we're generating an incorrect `.merlin` file. Which is the  config used by merlin to lint the file for syntastic. So unless you have a buggy .merlin file, this isn't really dune issue.

You should try reproducing the issue on master btw, there have been some fixes with respect to ppx + .merlin generation and they could work for your situation.

**Comment by rgrinberg** [comment]
Closing. beta 20 should hopefully help with things. Otherwise, there's not much we can do.
