### ISSUE TITLE
.merlin has no ppx when several libraries are defined

### ISSUE THREAD

**Issue by jvillard** [ocaml/dune#657]
This is only when the libraries define `(preprocess (pps ...))` directives, but happens even when they have the *same* directives, unlike #230.

I think this is because [`Jbuild.Preprocess.pps`](https://github.com/ocaml/dune/blob/bc2286215bea7e954151be0a43bef400d7549280/src/jbuild.ml#L279) includes location information (since 138c920069bc559c36f4e4f7803c457de8c5bf0b) and [`Merlin.merge_two`](https://github.com/ocaml/dune/blob/bc2286215bea7e954151be0a43bef400d7549280/src/merlin.ml#L129) compares these objects for equality using `=`. This comparison will almost always be false because two directives will have different source locations in the jbuild file.

**Comment by diml** [comment]
Indeed, thanks for finding the cause of the bug. I added a test case and a fix in #658.
