### ISSUE TITLE
inconsistent assumptions when using module aliases

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#660]
Hi!

I am building an executable that uses module aliases. Building works fine, but when the aliased module is modified, I get a "Files X and Y make inconsistent assumptions over interface I" error.

More precisely, here is a way to reproduce the problem:

### jbuild
```
(jbuild_version 1)

(alias
 ((name runtest)
  (deps (main.exe))
  (action (run ${<}))))

(executable ((name main)))
```

### main.ml
```ocaml
let () = print_endline Lib.Sub.hello
```

### lib.ml
```ocaml
module Sub = Lib_sub
```

### lib_sub.ml
```ocaml
let hello = "hello"
```

And when running the following script, an error happens:

```sh
#!/bin/sh
set -ex
jbuilder clean
jbuilder runtest
echo 'let x = 1' >> lib_sub.ml
jbuilder runtest
```

Output:
```
+ jbuilder clean
+ jbuilder runtest
        main alias runtest
hello
+ echo let x = 1     
+ jbuilder runtest
    ocamlopt main.exe (exit 2)
(cd _build/default && /home/etienne/.opam/4.06.1/bin/ocamlopt.opt -w -40 -g -o main.exe .main.eobjs/lib_sub.cmx .main.eobjs/lib.cmx .main.eobjs/main.cmx)
File "_none_", line 1:
Error: Files .main.eobjs/main.cmx and .main.eobjs/lib_sub.cmx
       make inconsistent assumptions over interface Lib_sub
```

I'm using OCaml 4.06.1, and jbuilder 1.0+beta19.1 (but the problem happens on master as well).

I'm happy to help with a PR, but I am absolutely not familiar with `dune` internals.

Thanks!

**Comment by diml** [comment]
Thanks for the short reproduction case. I can reproduce the error as well, including when using `-j1`. Things seems to be built in the right order, I suspect this is an issue with the fact that the files don't have mlis

**Comment by diml** [comment]
Hmm, I think i found the issue: lib.cmi is unchanged since it just contain aliases and main.ml only depends on Lib, so jbuilder doesn't rebuild it

**Comment by jberdine** [comment]
Is this related to https://caml.inria.fr/mantis/view.php?id=5624 I wonder? (We recently ran into this issue in a non-dune context where ocamldep was being used to trim excessive deps in manually specified build configs.)

**Comment by diml** [comment]
Yh that looks like the same issue. Inlining all or part of the cmi files as suggested wouldn't work well with module aliases though.

I talked with @sliquister about this, in theory by doing clever things we could avoid some recompilation when using `-no-alias-deps` everywhere, but we don't do these things in Dune at the moment, so it seems fine to me to start by removing some of the `-no-alias-deps` flags.

> I'm happy to help with a PR, but I am absolutely not familiar with dune internals.

@emillon I'm happy to guide you through what there is to do. Do you want to give it a try?

**Comment by diml** [comment]
Actually @sliquister pointed out to me that not using `-no-alias-deps` will cause more things to be linked into executables. For instance linking with Base would cause all of Base to be linked as the aliases in base.ml would be considered as implementation dependencies. This is a strong argument for keeping `-no-alias-deps` everywhere.

So I guess we'll have to compute the transitive dependencies of modules.

**Comment by emillon** [comment]
> Do you want to give it a try?

Sure! Shall I open an empty PR or do you prefer to discuss this here?

**Comment by diml** [comment]
You can open an empty PR, that way we can keep the discussion in one PR
