### ISSUE TITLE
dune -w (--watch) watches ignored directories if they're not top-level

### ISSUE THREAD

**Issue by emchristiansen** [ocaml/dune#6639]
## Expected Behavior

Assuming a root-level `dune` file containing:

```
(dirs :standard \ foo/bar/)
```

If you run the command `dune build --watch` we'd expect dune to build while excluding `foo/bar/` from the set of watched files.

## Actual Behavior

Changes within `foo/bar/` do cause dune to detect a change and restart.

## Specifications

Tested with `ocamlc 4.14.0` and `dune 3.5.0` on Ubuntu 22.04.

**Comment by rgrinberg** [comment]
It should be:

```
(subdir foo (dirs :standard \ bar))
```

**Comment by Alizter** [comment]
Dune should error when a user puts a non-strict subdirs in the dirs stanza. I have submitted a PR fixing this: https://github.com/ocaml/dune/pull/6640

**Comment by Alizter** [comment]
Closing this since the issue was resolved. The feature request that came out of it is reported here https://github.com/ocaml/dune/issues/7644
