### ISSUE TITLE
(:include ...) stanza in c_names field

### ISSUE THREAD

**Issue by ryanrhymes** [ocaml/dune#669]
Hi, 

I am wondering whether it is possible to support `(:include ...)` stanza in `c_names` field in future. The reason is that there are quite some c stubs in Owl lib, saving the list in another file(s) makes the jbuild file much cleaner, [[see this file]](https://github.com/owlbarn/owl/blob/00422f733829c15b563724fe9ba2d4621c479954/src/owl/jbuild#L27).

If my understanding is correct, this is not supported, right? Or is there any technical reason behind?

Many thanks.

**Comment by rgrinberg** [comment]
Having the list of stubs generated by a rule is something that we might not be able to support today, but I don't see it as the right way to fix this issue either. What about treating the `c_names` field the way we treat our `modules` field - using the ordered set language. I'm curious as to why @diml chose not to implement things this way. Unfortunately, to preserve backwards compat `:standard` (the default value) would have to be the empty list. But perhaps we can add something like `:all` to load all of them?

**Comment by diml** [comment]
It's only for historical reasons, I copied what we had inside Jane Street. I'm assuming this was like this in our jenga rules as we never have that many C files. Supporting `:all` seems fine to me.

**Comment by ryanrhymes** [comment]
Cool, `:all` also seems fine by me, thank you very much.

**Comment by rgrinberg** [comment]
The solution here is actually to use globs and the predicate language. I'll add a proper ticket for that feature.
