### ISSUE TITLE
Missing newline in "dune exec"

### ISSUE THREAD

**Issue by talex5** [ocaml/dune#6700]
## Expected Behavior

`dune exec` should show the program's output starting on a new line, but instead it appears after the build status. It used to work correctly in dune 3.5.0.

## Reproduction

```
$ dune init project test
$ cd test
$ dune exec -- ./bin/main.exe
Done: 92% (12/13, 1 left) (jobs: 1)Hello, World!
```

## Specifications

```
$ dune --version
3.6.1

$ ocamlc --version
5.0.0~rc1

$ cat /etc/debian_version
11.5
```

**Comment by rgrinberg** [comment]
Already fixed in the main branch. Will add a CHANGES entry.

**Comment by Alizter** [comment]
Seems to be an issue again.l

**Comment by rgrinberg** [comment]
It's already open as #7142.
