### ISSUE TITLE
Allow `(source (gitlab org/project/repo))` in dune-project

### ISSUE THREAD

**Issue by dannywillems** [ocaml/dune#6723]
## Expected Behavior

`(source (gitlab org/project/repo))` should be a valid source.

## Actual Behavior

```
6 | (source (gitlab nomadic-labs/cryptography/ocaml-chia-vdf))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Gitlab repository must be of form user/repo
```

## Reproduction

Update the dune-project here: https://gitlab.com/nomadic-labs/cryptography/ocaml-chia-vdf.

## Specifications

- Version of `dune` (output of `dune --version`):
3.6.1
- Version of `ocaml` (output of `ocamlc --version`)
4.14
- Operating system (distribution and version):
Ubuntu 22.04

**Comment by rgrinberg** [comment]
Seems like a simple issue. Would you like to try and fix it? The fix is relatively self contained to changing `dune_engine/package.ml`. The only thing to keep in mind is that we need to guard `x/y/z` sources behind 3.7.

**Comment by dannywillems** [comment]
Sure, let me give a shot

**Comment by rgrinberg** [comment]
ping @dannywillems seems like you have a WIP

**Comment by dannywillems** [comment]
Sorry but I gave a shot quickly after my message but I didn't have time to finish it and I am not sure I will have time to finish it in the new few weeks. I tried and struggled to write tests because I am not familiar with inline tests and the codebase.
