### ISSUE TITLE
Configurator Release Check List

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#674]
IMHO, the main blocker from having a supported configurator release was that configurator was basically untested. I'd be very uncomfortable releasing and supporting in that state. But now that @diml's seriously improve our blackbox testing situation, this is no longer a limitation. So I'd like that we make more progress on this issue.

* The main issue to solve seem to be be having a convenient way to pass arguments to configurator scripts. @diml has a promising idea on how to address this #594. We'd like to adopt this, but a user should still be able to use command line arguments. That is still useful for debugging and makes configurator useful for contexts out of jbuilder. Not to mention that it makes it easy for people to migrate their current `discover.ml` scripts.

* Currently, configurator requires `-ocamlc` to be passed explicitly. This is a bit annoying, but not so bad because omitting will lookup ocamlc in the current context using `$PATH` anyway. That should still be correct. We can leave this functionality for now but eventually pass `ocamlc` properly using the general mechanism in the first bullet.

* Given that we're being cautious about breaking user code, we should version the API from the start. Should we place the current Configurator API under a `V1` module? This will make it it easy for people to migrate to the new configurator. All they'll need to do is `module Configurator = Configurator.V1` and their configurator scripts will work as they expect them to. While we'll still be able to make improvements to Configurator under `V2`.

Anyway, I'd like the search for the perfect API not prevent us from shipping the already extremely useful Configurator to users.  Further adoption of Configurator will uncover many new use cases anyway, so let's not allow perfect be the enemy.

**Comment by Chris00** [comment]
> Given that we're being cautious about breaking user code, we should version the API from the start. Should we place the current Configurator API under a V1 module? 

I think this is a good idea.  User code usually defines a shortcut for the name `Configurator` already so it will be easy to update.  (I personally would like to have the have the interface evolve to one where, for example, all C functions are in a `C` submodule... ☺)

**Comment by diml** [comment]
Putting the API under a V1 module seems fine.

Regarding passing `-ocamlc ...`, there is the case of cross-compilation as well. It's not clear that the `ocamlc` in the path is the right one when cross-compiling. For instance it seems reasonable that it might be called `x86_64-...-ocamlc`. What about setting an environment variable in jbuilder and reading it in configurator to point to the ocamlc to use?

**Comment by rgrinberg** [comment]
> It's not clear that the ocamlc in the path is the right one when cross-compiling

I see. When we made the change to augment the `PATH` of target contexts, I thought that we committing to trying to resolve things through `PATH`.

Anyway, I'm fine with passing in this stuff through an environment variable. Though it seems like it's simpler to just pass the entire `Ocaml_config` as an sexp in the env var. Anyway, just passing `ocamlc` is fine for now. We don't have a `Sexp.t -> Ocaml_config.t` function at the moment.

**Comment by rgrinberg** [comment]
Configurator is now ready for an initial release.

**Comment by diml** [comment]
We should also publish the generated API doc on the web

**Comment by diml** [comment]
Ok. Yh, I'm just thinking that it's better than nothing in the meantime and it's easy enough to do with topkg/dune-release
