### ISSUE TITLE
melange: js artifacts do not honor original source layout when using include_subdirs

### ISSUE THREAD

**Issue by jchavarri** [ocaml/dune#6807]
When using `melange.emit` stanza or Melange libraries in combination with `include_subdirs unqualified`, the resulting `js` artifacts are all placed under a single folder, the folder where the `dune` file leaves.

This breaks the assumption that is inherited from ReScript, where users can assume they can reference assets using relative paths from the folder where the module lives, not the folder where `dune` file is.

Ideally dune will place `js` artifacts with the same layout as the original sources.

**Comment by jchavarri** [comment]
Fixed by @rgrinberg in https://github.com/ocaml/dune/pull/6811.

**Comment by rgrinberg** [comment]
There's a similar problem for installed libraries. Do we have a ticket for it?

**Comment by jchavarri** [comment]
I don't think so, created https://github.com/ocaml/dune/issues/6970.
