### ISSUE TITLE
Clarify the CLA situation

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#682]
Hi,

I'd like to open a discussion about the Contributor License Agreement (CLA) that dune requires (see e.g. #666 and #678).

My understanding was that since this project was moved under the `ocaml` organization, it was more or less a community project. Apparently that is not the case, and it is necessary to sign a CLA with Jane Street.

I think it'd be useful for this project to:
- document a bit more the situation, for example by adding a `CONTRIBUTING.md` file that will be linked when opening a PR.
- if possible, move to something lighter like a DCO, as mentioned in #678.

Thanks!

**Comment by yminsky** [comment]
To reiterate some things I said on the other thread:

Changing the org in Github doesn't really change the legal status. That legal status, though, doesn't I hope cut against this being a community-oriented project. Note that contributing to OCaml itself also requires a CLA (though to a different organization), and until fairly recently, it was considered part of best practices for responsibly managing the licensing of an open-source project.

And to be clear, the source code itself is licensed liberally, and there are contributors for a number of organizations.

FWIW, we do hope to move to a new more lenient license and to a DCO, not just for Dune, but also for all of Jane Street's open source code. But until then, the CLA is still required.

**Comment by diml** [comment]
To follow up on this, we are going to switch to DCO and change the license to MIT, see #737.

We actually took the decision a few weeks ago but then I realized that we were missing a few CLA from past contributions. We are still waiting for 2 of them and then we will be able to switch.

**Comment by rgrinberg** [comment]
The CLA situation has been clarified in https://github.com/ocaml/dune/blob/master/CONTRIBUTING.md

Please re-open this ticket if the description isn't adequate.
