### ISSUE TITLE
dune doc

### ISSUE THREAD

**Issue by EmileTrotignon** [ocaml/dune#6831]
This would be a new command `dune doc` that would do the following :

- Call `dune build @doc`
- Open the doc index in the user's browser.

Do you think this is a good idea ? 
If maintainers like the feature, I will start working on it soon.

**Comment by Alizter** [comment]
Can you not open the index in the browser and just refresh everytime you do a `dune build @doc`?

**Comment by esope** [comment]
Maybe some issue that is related is: once I have built de doc using `dune build @doc`, where is the generated documentation?
Providing some easy, quick access to the documentation (through a link to the right target, or by printing out a message that shows the path of the generated documentation) could already be helpful?

**Comment by Alizter** [comment]
Have a look in `_build/default/_doc`. This is where `odoc` will but all the doc artifacts. The reference manual even mentions the location of the documentation: https://dune.readthedocs.io/en/stable/documentation.html

**Comment by Alizter** [comment]
`dune build fmt` is really the same as `dune build @fmt --auto-promote`.

**Comment by Alizter** [comment]
We are currently in the process of designing a new terminal UI for Dune, to allow for a sleeker user experience. One thing that might be useful to add is the ability to view newly build targets. So a user could do the following:

1. Have Dune running the TUI in watch mode
2. Ask Dune to build the `@doc` alias.
3. Inspect (the locations of) all the newly built targets.

**Comment by EmileTrotignon** [comment]
> Have a look in `_build/default/_doc`. This is where `odoc` will but all the doc artifacts. The reference manual even mentions the location of the documentation: https://dune.readthedocs.io/en/stable/documentation.html

I am sure it is explained in the documentation, but the documentation is hard to navigate, and even if it wasn't, beginners will not have read it back to back (and if they did, will not remember this detail). The existing workflow for someone who doesn't know this by heart is :
- Call `dune build @doc`
- Open your browser, then the dune doc, then find the right page.
- Go back to your terminal to open the index, 

I propose to have the following workflow : 
- Call `dune doc`.

@esope 's proposal is the following :
- Call `dune build @doc`
- Click / copy the link from your terminal.

To me, this seems a bit worst, but also a more minor change, so it may be the best choice.

> > Have a look in `_build/default/_doc`. This is where `odoc` will but all the doc artifacts. The reference manual even mentions the location of the documentation: https://dune.readthedocs.io/en/stable/documentation.html

I am sure it is explained in the documentation, but the documentation is hard to navigate, and even if it wasn't, beginners will not have read it back to back (and if they did, will not remember this detail). The existing workflow for someone who doesn't know this by heart is :
- Call `dune build @doc`
- Open your browser, then the dune doc, then find the right page.
- Go back to your terminal to open the index, 

I propose to have the following workflow : 
- Call `dune doc`.

@esope 's proposal is the following :
- Call `dune build @doc`
- Click / copy the link from your terminal.

To me, this seems a bit worst, but also a more minor change, so it may be the best choice.

>> Have a look in `_build/default/_doc`. This is where `odoc` will but all the doc artifacts. The reference manual even mentions the location of the documentation: https://dune.readthedocs.io/en/stable/documentation.html

I am sure it is explained in the documentation, but the documentation is hard to navigate, and even if it wasn't, beginners will not have read it back to back (and if they did, will not remember this detail). The existing workflow for someone who doesn't know this by heart is :
- Call `dune build @doc`
- Open your browser, then the dune doc, then find the right page.
- Go back to your terminal to open the index, 

I propose to have the following workflow : 
- Call `dune doc`.

@esope 's proposal is the following :
- Call `dune build @doc`
- Click / copy the link from your terminal.

To me, this seems a bit worst, but also a more minor change, so it may be the best choice.

The watchmode workflow looks not too bad, but I doubt it is going to be found by a beginner. The inspection command might also be quite hard to discover and remember, making it less useful to beginners.

**Comment by rgrinberg** [comment]
Adding the command seems alright. However, let's keep it away from the toplevel. `dune ocaml doc` is better because I don't see how we're going to generalize this to things other than odoc. Printing the link before opening it seems like a good idea.

**Comment by EmileTrotignon** [comment]
I am not completely aware of other documentation tools. Don't they also provide an index page ?

**Comment by Alizter** [comment]
@EmileTrotignon There are not any other documentation tools, however Dune is able to build other kinds of projects other than OCaml. Previous experience suggests that if we wish to do the same for those kinds of projects, we will have to move it to the `ocaml` subcommand anyway.

**Comment by tmattio** [comment]
Would it be acceptable to have the top-level commands targeted to OCaml projects while having the commands specific to other projects in groups?

Dune is a build system for OCaml so it seems sensible to have the default command targetted to OCaml users, and moving OCaml commands outside of the top-level doesn't seem like a win for anyone:
- It hurts the discoverability of these commands for OCaml users
- It doesn't change anything for other users

**Comment by rgrinberg** [comment]
I'm not against `dune doc` in principle, but the proposed command in its current form is just an alias to build something and open a webpage. That's a useful addition, but not something I imagine users running day to day. There should be a higher bar for utility to add a new command at the top level.

**Comment by rgrinberg** [comment]
It's not the complexity, but rather the frequency of usage that earns a command a short name. Which is why I've promoted `fmt` but not this particular command in its current form.

I agree that writing documentation is important, but this command is more useful for testing the final product rather than developing it. Which is why I've asked the odoc team on how to incorporate odoc's diagnostics into `dune build @check`. For development, opening a per module preview of the doc would also be more useful.

I could imagine this command to be extended for browsing documentation of dependencies as well - e.g. `dune doc library $library-name`. That would make it a lot more useful.

**Comment by EmileTrotignon** [comment]
After this discussion, what I want to do is the following : 
- Have a `dune ocaml doc` that does what was proposed at the start, with the idea to maybe promote it to `dune doc` in the future.
- Have `dune build @doc` print the link to the index at the end of the build.

I was told by @rgrinberg that the second goal would require changes to the engine to ensure that the message is always displayed at the end, and not drowned in odoc warnings. This could also have uses for #6865.
The engine would have some sort of hook to do something at the end of a build. @snowleopard are you fine with this ?

**Comment by snowleopard** [comment]
> The engine would have some sort of hook to do something at the end of a build. @snowleopard are you fine with this ?

Personally, I find this kind of "do something at the end of the build" functionality outside of the scope of a build system. It seems to me that it goes along the lines of stuffing too much functionality into a single tool, which makes it challenging to understand the tool's semantics. I'd rather people develop other tools around the simple and robust build engine. Now that we have Dune RPC, it seems easier than ever.

Having said that, Dune is a community project and I'm not the sole arbiter who decides its future :) So, the above is just my opinion, nothing more.

**Comment by rgrinberg** [comment]
@snowleopard I'm not sure how to implement this feature in a reliable way without at least some minor changes to the engine. In particular, our goal is to display a message in the end of the build *if a particular target is included in the build request* (the documentation index page in this case). I don't see how this condition can be detected at the moment though.

**Comment by snowleopard** [comment]
Well, you can change your rule to create a file pointing to the documentation index. Then you can `cat` it, or do anything else with it, since it's just a normal target. In my mind, supporting a new kind of build action in the engine is a major change that requires a proper RFC describing the semantics (including in the file-watching mode), some motivation, etc.

**Comment by rgrinberg** [comment]
> Well, you can change your rule to create a file pointing to the documentation index. Then you can cat it, or do anything else with it, since it's just a normal target

I don't think that will work. The message needs to come specifically after the build and must be displayed even if the index isn't rebuilt.

But here's something that might work:

1. We introduce a custom action that updates that status line that the docs are ready at a particular path
2. Add this custom action to the `doc` alias. Specifically in the directory where we produce `index.html`
3. Make the `doc` alias depend on `universe` in the directory where `index.html` is produced.

**Comment by snowleopard** [comment]
> The message needs to come specifically after the build and must be displayed even if the index isn't rebuilt.

You can add `dun build_and_cat --file my_file` command (bikeshedding welcome) that will `cat` the file you want after the build. No need to modify the build engine to introduce some kind of "always run this code" for this.

**Comment by rgrinberg** [comment]
> You can add dune build_and_cat --file my_file command (bikeshedding welcome) that will cat the file you want after the build. No need to modify the build engine to introduce some kind of "always run this code" for this.

I think what Emile is getting at is to avoid a custom command.

> (Also, you didn't really explain how these custom actions will work. There is a lot of code that potentially needs to change if we add a new action with a weird "run always" semantics.)

The action would call some function in `Dune_console.Status_line` to update the status line accordingly.

**Comment by snowleopard** [comment]
A custom command is much much simpler than introducing a new kind of actions in the build engine.

> The action would call some function in `Dune_console.Status_line` to update the status line accordingly.

That doesn't tell me much. There is Memo and the file-watching mode, there is workspace-local cache, there is shared cache, and a lot of associated complexity that goes into executing actions. It's probably easy to hack something up but we'll then need to maintain this functionality for years, so it's worth thinking it through in more detail.

**Comment by snowleopard** [comment]
> If I may ask a slightly noob question, doesn't dune work roughly like make in the sense that it tracks inputs and outputs and recalculates the outputs if the inputs change?

Dune's build engine treats files as inputs/outputs; stdout is a side-effect that's currently not cached.
