### ISSUE TITLE
Unclear documentation about dune files in the project root

### ISSUE THREAD

**Issue by Vvalter** [ocaml/dune#6845]
I'm new to dune and started reading the documentation. I got confused by the following sentence in the description of the term "project" in the [Terminology](https://dune.readthedocs.io/en/stable/overview.html#terminology) section:
> Each directory in the tree, including the root, must have a dune file specifying how to build the files in its directory.

This implies to me that I need to have a `dune` file at the root of each project (i.e. everywhere where I put a `dune-project` file, I must put a `dune` file).
However, this seems to contradict the examples (and the layout of the dune repository itself):
```bash
> ls example/hello_world.t/
bin  dune-project  hello_world.opam  lib  README.org  run.t  test
```
There is no `dune` file in the root of the project.

Maybe the problem is that I misunderstand the term "root". From the sentence
> root: the top-most directory in a GitHub repo, workspace, and project, differentiated by variables such as %{workspace_root} and %{project_root}.

it's not really clear to me whether "root" means a specific directory or whether there is a "repository root", a "workspace root", and a "project root", which might or might not be the same?

**Comment by Alizter** [comment]
You only need a `dune` file in a directory in which you wish to have stanzas. Stanzas tell Dune what and how to build.

You need a `dune-project` file for your project. This could be at the top directory of your repository. Dune projects files can be "composed" meaning that you can place many directories each containing their own `dune-project` file under a common `dune-project` file. Project files describe packages that your project has and other things, and this will affect all the `dune` files within.

A special variant of the `dune-project` file exists called a `dune-workspace`. This let's you further configure opam switches and so on.

>it's not really clear to me whether "root" means a specific directory or whether there is a "repository root", a "workspace root", and a "project root", which might or might not be the same?

It is repository root, but if those repositories further sit in a workspace, then it will be the workspace root. When you call `dune` it will climb to the top most workspace/project file. You can further specify where you want the root to actually be by passing `--root=dir`. The root directory is where special Dune directories like `_build` will appear.

**Comment by emillon** [comment]
> This implies to me that I need to have a `dune` file at the root of each project (i.e. everywhere where I put a `dune-project` file, I must put a `dune` file).

I agree that there's an ambiguity here. What this sentence means is:

> instructions to build files go in the `dune` file of that directory, even at the root.

(they can't go in `dune-project`). I'll open a PR to try to clarify that point.

**Comment by Vvalter** [comment]
Thanks, this clears up what a project is and I like the documentation improvement in #6852 :+1:
