### ISSUE TITLE
Rule using a `cp ${^} .` action

### ISSUE THREAD

**Issue by briancaine** [ocaml/dune#687]
([Cross posting from the ocaml discussion board](https://discuss.ocaml.org/t/jbuilder-rule-with-a-cp-action/1826))

I'm working on a web project. I'm trying to maintain a `webstatic` directory containing all my html and css, and then `websrc` holds my `*.ml`s, and finally a `web` directory containing a jbuilder file that concatenates the two.

`websrc/main.ml`:
```
type t = string
```

`websrc/jbuild`:
```
(jbuild_version 1)

(executables
 ((names (main))))
```

`webstatic/index.html`:
```

<html>

<head>

<title>why</title>
<script src="main.bc.js">

</head>

<body>

<p>sup</p>

</body>

</html>
```

`web/jbuild`:
```
; -*- mode: lisp -*-

(jbuild_version 1)

(rule
 ((targets ("index.html"))
  (deps ("../websrc/main.bc.js"
         (files_recursively_in "../webstatic")))
  (action
   (system "echo cp ${^} . && cp ${^} ."))))
```

My goal is to be able to run `jbuilder build web/index.html` and have `_build/default/web` get populated with everything from `webstatic` alongside the `main.bc.js` that's built from `websrc`.

It works but only once.

In fact, it does something weird, it actually deletes the `main.bc.js` when I modify the `main.ml` and rebuild:

```
$ find
.
./web
./web/jbuild
./webstatic
./webstatic/index.html
./websrc
./websrc/jbuild
./websrc/main.ml
$ jbuilder build web/index.html
          sh web/index.html
cp ../websrc/main.bc.js ../webstatic/index.html .
$ ls -lh _build/default/web
total 16K
-rw-r--r-- 1 brian brian 108 Apr  8 02:27 index.html
-rw-r--r-- 1 brian brian 11K Apr  8 02:27 main.bc.js
$ nano websrc/main.ml 
$ cat websrc/main.ml 
type t = unit
$ jbuilder build web/index.html
$ ls -lh _build/default/web
total 4.0K
-rw-r--r-- 1 brian brian 108 Apr  8 02:27 index.html
$ 
```

My logic is:
1. `websrc/main.bc.js` is a dependency of `web/index.html`
2. running `jbuilder build web/index.html` should notice that `websrc/main.bc.js` is out of date
3. thus it should be rebuilt and the rule to generate `web/index.html` (the `cp` command) should get rerun

I'm perplexed. Am I missing something obvious? Also, is there an easy way to debug jbuilder dependency trees?

**Comment by diml** [comment]
Even without editing the file, just calling `jbuilder build ...` a second time will delete `main.bc.js`. It's because it is not listed as a target of the rule, so jbuilder thinks it's a stale artifacts.

**Comment by briancaine** [comment]
When are stale artifacts cleaned up?

**Comment by diml** [comment]
The stale artifacts for a given directory are cleaned up when jbuilder starts building things in that directory.

**Comment by rgrinberg** [comment]
@briancaine do you think this issue can be closed?

@diml did we document this fact about cleaning up stale artifacts? I'm not sure that users are aware that they should specify targets exhaustively.

**Comment by briancaine** [comment]
@rgrinberg Yeah, it can be closed.
