### ISSUE TITLE
Object-only libraries.

### ISSUE THREAD

**Issue by Drup** [ocaml/dune#689]
ocamlfind allows to define libraries that are only composed of objects/`cmo` file, and are only linked for their
side effects, but do not expose any modules. There are many use cases for that ([toplevel printers](https://github.com/ocaml/dune/issues/688) is a very simple example, but you could also consider driverified ppxs and lot's of other things).

Is it possible to define such libraries with jbuider ? I haven't found how.

**Comment by diml** [comment]
Once we support private modules, you should be able to hide all the modules. Then linking the library with `-linkall` should provide the same features.

**Comment by diml** [comment]
Nope, but @rgrinberg told me he started looking at it

**Comment by rgrinberg** [comment]
Yeah, I have a WIP branch that gets us most of the way there but it's way out of date. IIRC it was just a matter of having 2 object dirs per library and then being careful with passing the `-I` flag.

@Drup if you're feeling adventurous, we could guide you to implement this.

**Comment by Drup** [comment]
@rgrinberg Please, no, my todolist is overflowing and my time budget is already in the negative. Don't ask me to dive into a whole new codebase.

**Comment by rgrinberg** [comment]
@Drup now that private modules are done, is there anything else you'd like to see here?

**Comment by rgrinberg** [comment]
It's not enough to compile the lib with `-linkall`? I though that the archive file would inherit this flag whenever this library would be used.

Okay, I'll close this issue then. Feel free to create more if you have an idea for a concrete suggestion.
