### ISSUE TITLE
Compiler errors are not clickable in terminal/VSCode

### ISSUE THREAD

**Issue by mimoo** [ocaml/dune#6908]
Hey hey,

When the terminal (at least on mac) or vscode returns an error, for example:

<img width="736" alt="Screenshot 2023-01-19 at 10 06 47 PM" src="https://user-images.githubusercontent.com/1316043/213628775-cd598d63-9ed9-4cbb-bfba-4998671be12d.png">

I often can't click on the file because it isn't relative to where I am, and when I can click it doesn't get me to the line number. I'm not sure how other languages do it but I don't remember having that problem in other ecosystems.

I'm also not sure how to fix it. I believe the terminal / vscode will detect filename:linenumber all the time, but the "File "src/base/snark_intf.ml", line 588, characters 50-75" is not recognized.

**Comment by Alizter** [comment]
These requires tweaking vscode line number detection regex. An alternative is to use the problems tab which let's you click directly on any errors. For this you will need the OCaml platform extension, OCaml Lsp and also run dune in watch mode (pass `-w`).

**Comment by mimoo** [comment]
ohh, I didn't know about the `-w` mode interesting, and indeed the problems tab highlights it.

<img width="568" alt="Screenshot 2023-01-20 at 11 23 17 AM" src="https://user-images.githubusercontent.com/1316043/213787595-19903e2a-8b1e-48ad-820f-ce3b8cb7b215.png">

Thanks for the tips! I still thing something should be done with the plain errors though as other languages don't have that problem : D

**Comment by rgrinberg** [comment]
Can you re-open the issue in the vscode repo? This is a bug with the regex that is supposed to recognize compiler errors.

I would move the issue myself, but it's in a different org so it's not possible.

**Comment by Alizter** [comment]
There were similar issues in the past which I opened issues for and they got fixed: https://github.com/microsoft/vscode/issues/145394

**Comment by mimoo** [comment]
interesting, looks like they fixed it but the issue still exist? posted there
