### ISSUE TITLE
Incorrect HTML generation when library has an ML file to control exports

### ISSUE THREAD

**Issue by stevebleazard** [ocaml/dune#691]
[dune version: beta18-284-g02b04e1]

When I have a library ML file the generated html contains links to private modules as well as the public ones. Thus given:

A private module `src/priv_module.ml`:
```ocaml
(** Private module *)

(** Some private function doc *)
let privfun () = ()
```
The public module `src/pub_module.ml`:
```ocaml
(** Public module *)

(** Some public function doc *)
let pubfun () = ()
```
A library ML file to only export the public module, `src/testlb.ml`:
```ocaml
module Pub_module = Pub_module
```
And the following `src/jbuild` file:
```
(jbuild_version 1)

(library
 ((name testlib)
  (public_name testlib)
  ))
```
`jbuilder build '@doc'` results in a tree with the following structure (> indicates a link):
```
testlib > Testlib__ >
  Priv_module > (priv module doc)
  Pub_module > (pub module doc)
  Testlib > Pub_module > (pub module doc) 
```
I would have expected `testlib > Testlib > Pub_module > (pub module doc)` at most given that this is pub doc only build.

**Comment by rgrinberg** [comment]
This is with beta 18? Would you mind updating this issue after trying it out with master (or the upcoming beta 20)

**Comment by stevebleazard** [comment]
I retested with today's master branch (1.0+beta20-10-g7a3917b) fixed the issue, I have closed this ticket
