### ISSUE TITLE
Cram test, dune file at root, and clean build makes test fail

### ISSUE THREAD

**Issue by rjbou** [ocaml/dune#6932]
## Actual Behavior
Using only cram tests, when you have a clean directory (no previous build), and dune file only at root and not in the test directory ; the command  `dune build @runtest` make test failing because the binary is not found.

## Expected Behavior
In the same conditions, find the binary to run the test, or display a message prior to invite user to put its cram directive in the test directory.

## Reproduction
- PR with a reproducing test: #6931

## Specifications

- Version of `dune` (output of `dune --version`): 3.6.1
- Version of `ocaml` (output of `ocamlc --version`): 4.14.0
- Operating system (distribution and version): debian, alpine

**Comment by rgrinberg** [comment]
Left a comment in the PR.
