### ISSUE TITLE
`dune describe pp` doesn't work with staged pps

### ISSUE THREAD

**Issue by ejgallego** [ocaml/dune#6945]
`dune describe pp foo.ml` doesn't work when a staged pps is used. Example:

```ocaml
type t = { foo : string } [@@deriving ppx_yojson]
```

with dune file:
```lisp
 (preprocess (pps ppx_deriving_yojson))
```
works fine, but with dune file:
```lisp
 (preprocess (staged_pps ppx_deriving_yojson))
```
it produces the input file

**Comment by tatchi** [comment]
> A first thing we can do is add an error message when we detect that case.

Happy to give it a try 😁

**Comment by ejgallego** [comment]
#7167 just adds an error message, but still `dune describe pp` doesn't work for staged pps so this bug has not been fixed.

**Comment by emillon** [comment]
I'd count that as a separate fix. we've already improved the situation, let's open a new issue for this.
