### ISSUE TITLE
melange: installed artifacts should keep original layout for sources and assets

### ISSUE THREAD

**Issue by jchavarri** [ocaml/dune#6970]
Similar to https://github.com/ocaml/dune/issues/6807, but for installation. We would need a way to recreate the original layout from the sources after installing, including assets.

@rgrinberg mentioned:

> The only thing we need from melange to facilitate this is a `meldep` that will interpret all the ppx attributes and extensions and give us the paths of all assets

cc @anmonteiro

**Comment by rgrinberg** [comment]
This is also needed to install sources for `(include_subdirs qualified)`. Taking care of this now.
