### ISSUE TITLE
Real custom toplevels

### ISSUE THREAD

**Issue by Drup** [ocaml/dune#698]
In tyxml, I use a toplevel to test that some constructs do *not* typecheck. 
For that, I need a toplevel loaded with the `tyxml` library. The usual trick (build a toplevel linked with the library) is not sufficient here, because it only takes care of the runtime aspect, not the typing ones. I still need to provide an include path pointing to the `cmi` files. 

Currently, I [hardcode the path inside `_build`](https://github.com/ocsigen/tyxml/blob/dunification/test/jbuild#L29). @rgrinberg said [here](https://github.com/ocsigen/tyxml/pull/197#issuecomment-380548097) that jbuider could provide a better API that leverages the machinery used by `jbuilder utop`.

**Comment by samoht** [comment]
Can something like https://github.com/realworldocaml/topexpect would help? You could have a sessions where you check that something does not indeed typecheck. See for instance [this fragment of code from RWO](https://github.com/realworldocaml/book/blob/master/examples/code/maps-and-hash-tables/main.mlt#L208-L217).

**Comment by Drup** [comment]
Yes, I'm aware of that lib. I would be happy to use it once it's not in beta anymore and it doesn't depend on half the janestreet universe (arguably, it's the part that is fast-ish to build, but still).

**Comment by diml** [comment]
There are quite a few toplevel expect tests tools out there:
- https://github.com/janestreet/toplevel_expect_test
- https://github.com/realworldocaml/topexpect
- https://github.com/ocaml/ocaml/blob/trunk/testsuite/tools/expect_test.ml
- https://github.com/ocaml/dune/blob/master/test/unit-tests/expect_test.mll

I was thinking that we should just add this functionality directly in the regular toplevel.

**Comment by emillon** [comment]
The recommended way to do that in dune is using [mdx](https://github.com/realworldocaml/mdx/) and the [mdx stanza](https://dune.readthedocs.io/en/stable/dune-files.html#mdx-since-2-4).
