### ISSUE TITLE
Quoting problem when there are several targets

### ISSUE THREAD

**Issue by diml** [ocaml/dune#701]
Problem exposed by the test added in #699

**Comment by diml** [comment]
I suggest that we use the following model, that I find slightly simpler than the current one:

A variable always expand to a list of values. When a variable expands to exactly 1 value, there is no ambiguity and it can appear anywhere. When it expands to 0 or more than 2 values, it can appear:
- either inside a quoted string, in which case it expands to the list of values concatenated by spaces
- either as a whole atom inside a variadic functions, in which case it expands to one argument per value

**Comment by Chris00** [comment]
I'll try to have a look later today (in the evening CET).

**Comment by Chris00** [comment]
I'm afraid it'll have to wait for tomorrow.

**Comment by diml** [comment]
@Chris00 do you think you'll have some time to look at this in the coming weeks? I'm thinking that it'd be nice to sort this out before we release Dune 1.0.0.

**Comment by Chris00** [comment]
> I'm thinking that it'd be nice to sort this out before we release Dune 1.0.0.

I agree.  I'll try to find the time but there are a couple of things I definitely need to finish first...

**Comment by rgrinberg** [comment]
@Chris00 I'll take over this if you don't mind. I'd like to have this fixed to support version comparisons.

**Comment by Chris00** [comment]
@rgrinberg Thanks — I'm doing too many things ATM...

**Comment by rgrinberg** [comment]
Fixed in master.
