### ISSUE TITLE
regression (3.7): crunch.3.3.1 - module is used in several stanzas

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#7015]
Hi,

`crunch.3.3.1` does not build with `3.7.0~alpha1`, though it does with `3.6.2`. Here is the error:

```
File "src/dune", line 1, characters 0-0:
Error: Module "Realpath" is used in several stanzas:
- src/dune:1
- src/dune:17
To fix this error, you must specify an explicit "modules" field in every
library, executable, and executables stanzas in this dune file. Note that
each module cannot appear in more than one "modules" field - it must belong
to a single library or executable.
```

I bisected that down to fb085c087e330dc8c4a1909d5493170817369cca (#6594). The corresponding `dune` file can be found [here](https://github.com/mirage/ocaml-crunch/blob/v3.3.1/src/dune). The tricky stanza seems to be:

```
(library
 ; Dummy library to detect the OCaml version
 (name realpath)
 (modules)
 (enabled_if
  (< %{ocaml_version} "4.13")))
```

I'm not too familiar with the offending PR so can you have a look @rgrinberg ? Thanks!

**Comment by emillon** [comment]
I think that this is related to the empty `(modules)` since `pbrt.2.3` fails with the same error and [the corresponding dune file](https://github.com/mransan/ocaml-protoc/blob/2.3.0/src/ocaml-protoc/dune) has an empty one too.

**Comment by rgrinberg** [comment]
Thanks for snooping. We have `gh5267.t` for this bug already. I guess I didn't notice the failure. Will investigate.
