### ISSUE TITLE
Where to search *.cmt files?

### ISSUE THREAD

**Issue by camlspotter** [ocaml/dune#702]
I have noticed that the recent dune moved the place of storing *.cm* files of dir/x.ml  from

    _build/<default or something>/dir/package__X.cm*

to

    _build/<default or something>/dir/.package.objs/package__X.cm*

or sometimes

    _build/<default or something>/dir/.package.eobjs/package__X.cm*

Could you explain how they are determined?  Is there an easy way to find where I can find *.cmt files for dir/x.ml ?  I have several cmt file tools but they stopped working with this change...

Best regards,
Jun

**Comment by rgrinberg** [comment]
Sure. The `.objs` suffix is for collecting objects of libraries. While the `.eobjs` suffix collects the object files of executables.

>  Is there an easy way to find where I can find *.cmt files for dir/x.ml 

Probably the most reliable way today is to read the `B` lines in `dir/.merlin`. This is how we communicate to merlin where the object files are stored. This isn't ideal, and we'd love to improve the situation, but we're not really sure how to expose this information to users.

**Comment by camlspotter** [comment]
Thanks.  It makes sense.  I was wondering how Merlin could follow the change of Dune!
