### ISSUE TITLE
`modules` field in conjunction with `private_modules`, `virtual_modules`, etc.

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#7026]
The issues #7022, #7023, #7024 demonstrate a similar set of issues where a module is absent from `modules`, but is present in some other module list. Dune unfortunately ignores this discrepancy. At best, this is a harmless mistake, and at worst, this leads to some confusing build errors.

I propose that we do the following:

1. We warn the user when this mistake is made for now.
2. In 3.8, we turn this into a hard error.

Wdyt @nojb @emillon

**Comment by nojb** [comment]
Sounds good to me. When turning it into an error, a hint ("Have you forgotten to add it to `(modules ...)`") may be useful as well.

**Comment by emillon** [comment]
I agree about the feature, but I'd push back the cycle by 1: add the warning in 3.8 and make it fatal in 3.9. It's late in the 3.7 cycle and I could see add many unforeseen warnings.

**Comment by emillon** [comment]
It's still a good time to implement the warning so that it can be tested in an 3.8~alpha release.

**Comment by Alizter** [comment]
Was an easy fix: https://github.com/ocaml/dune/pull/7608
