### ISSUE TITLE
Engine: Refactor Source Handling

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#7046]
This ticket is born out of a discussion I've had with @snowleopard. The goal is to increase the separation of concerns between the engine and the rules. This will allow the rules to evolve more independently and the engine to be more flexible and correct.

## Problem

At the moment, the engine isn't fully independent from dune's own rules because it relies on a source tree abstraction that is very much aware of rule specific peculiarities. For example:

* The source tree attaches a "dune project" to every directory.
* The source tree attaches a version control value to every directory.
* The source tree interprets dune files to know which directories to ignore and which directories to vendor
* The source discovers cram tests based on directory extensions.

In other words, the source tree is doing a lot of things that can be considered as "build rules" and shouldn't live in a generic engine.

## Analysis

To move our existing source tree back to the rules, we need to replace it in the engine with something more primitive. To do that, we need to enumerate all the existing use cases of the source tree in the engine and see how they might be rewritten or removed. I'll enumerate them one by one.

### Traversals

Source trees in the engine are often traversed for various purposes. The most common reason is to build dependency sets (`Dep.source_tree`, recursive aliases, etc). Another place where the source tree is traversed is rule printing (`dune rules`).

### Copying Rules

The build engine sets up copying rules from the source tree to every defined context automatically. This requires the engine to have a function to have of the form `Path.Source.t -> Path.Source.Set.t` to list any source directory. 

## Action Plan

I'll propose the a step by step plan to uncouple the source tree from the engine by addressing each of the problems above.

### Copying Rules

The standard way for users of the engine to configure is to provide the appropriate values in `Build_config.t`. For example, to configure the rules for every directory, we provide a callback to do so. Therefore the source tree the engine should use to setup the copying rules should also originate from a callback. E.g.

```
val set :
  ..
 -> source:(Path.Source.t -> listing Memo.t)
 ..
```

### Rule Printing

Printing the rules in a directory does not seem like a fundamental part of the engine and it can be moved to its own library. There it will be free to use the source tree for traversal or it can take a more generic representation of a directory tree that can be traversed.

### Dependency Construction

Here we have two options:

* Move all the dependency constructors to the rules where they can freely depend on the current source tree
* Make them generic and have them accept a generic source tree that can be traversed. E.g.:

```ocaml
module type Source_tree = sig
  type t
  type listing = { files : String.Set.t ; dirs : t String.Map.t }
  val list : t -> listing Memo.t 
end
```

I would lean towards the first solution as it's simpler and it's not clear if some of these dependency constructors are worth making generic. But the second option might make it easier to transition code inside of janestreet.

**Comment by snowleopard** [comment]
Great write up, thanks! 

I quite like the idea of abstracting the source tree away with something like your `Source_tree` module type. 

It seems to be missing a seed like `root : t`, and probably also a way to turn a leaf of the tree to the actual file system path like: `to_path : t -> filename:string -> Path.Source.t`.

**Comment by rgrinberg** [comment]
Lots of progress on this work and we have a good idea what the final result is going to look like. We're going to remove source tree completely from the engine (we're almost there) and introduce a much simpler source module as a separate library:

```
type t
val create : filter:(dir:Path.Source.t -> (Filename.Set.t -> bool) Memo.t) -> t
val find_dir : Path.Source.t -> t option Memo.t
..
```

This source tree will only cover two concerns:

* Lazily loading the file tree starting from some root
* Making sure that walking the file tree never makes dune get stuck with an infinite loop

Everything else is going to be implemented on top of this construct. In particular:

* Interpretation of dune project files
* Directory statuses
* Dune files

Will be added in the rules.
