### ISSUE TITLE
Support (include_subdirs unqualified) in Coq

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#7054]
This should be quite straightforward. We simply `-Q` each subdirectory with the unqualified theory name. There are occasionally some projects in the wild that are setup like this, and we can also remove the arbitrary restriction we have in place today. It may indirectly address the issues in #3314.

**Comment by ejgallego** [comment]
The restriction we have today is not arbitrary, Coq upstream just doesn't support support `unqualified` as there will be a module clash in the library name resolution, so this is not implementable. Also something we don't want IMO.

**Comment by Alizter** [comment]
Very well.

**Comment by ejgallego** [comment]
What are the projects that need this? Are they really doing unqualified (that is to say, non-recursie) or are they doing namespace merging?

`-Q` / `-R` are always recursive so indeed you could implement this but at a large cost for Dune, in the sense that would need to understand fully loadpath and reject source layouts that would confuse Coq.

If you add a `-Q` version of Coq that is not recursive, then you can do this in a simpler way.

But actually I understand that unqualified in Dune even for OCaml may go away.

**Comment by ejgallego** [comment]
Another complication is achieving a good layout install, that is compatible with `user-contrib` setup.

How do the projects in the wild address this?

**Comment by Alizter** [comment]
Everything gets installed in user-contrib using the "theory name" so that is not a problem. I have seen projects in the past do things like
```
-Q lib1 Foo
-Q lib2 Foo
```
Obviously if lib1 or lib2 contains the other then this gets super confusing.

**Comment by ejgallego** [comment]
> ```
> -Q lib1 Foo
> -Q lib2 Foo
> ```

But indeed actually this doesn't correspond to `unqualified`, in the sense that often `lib1` and/or `lib2` do contain subdirectories, right?

That case is what we call "namespace merging", and may be different. I guess we'd need to see a concrete example here.
