### ISSUE TITLE
MDX does not rebuild when the prelude changes

### ISSUE THREAD

**Issue by talex5** [ocaml/dune#7077]
## Expected Behavior

When using `(mdx (preludes prelude.ml) ...)`, changing `prelude.ml` should cause the tests to be run again.

## Actual Behavior

It ignores this and you have to do `dune clean` first.

## Reproduction

```
$ ls
dune  dune-project  prelude.ml  README.md

$ cat dune
(mdx
  (preludes prelude.ml)
  (files README.md))

$ cat dune-project 
(lang dune 3.6)
(using mdx 0.3)

$ cat prelude.ml 
let foo () = 1

$ cat README.md 
```ocaml
# foo();;
- : int = 1

$ dune runtest

$ echo 'let foo () = 2' > prelude.ml
$ dune runtest

$ dune clean; dune runtest
File "README.md", line 1, characters 0-0:
...
```

## Specifications

- Version of `dune` (output of `dune --version`): 3.6.2
- Version of `ocaml` (output of `ocamlc --version`): 5.0.0
- Operating system (distribution and version): Debian 11

**Comment by emillon** [comment]
Confirmed from a quick look at the source code. I'll prepare a PR.
