### ISSUE TITLE
--force option no longer recognized. Tests always run once.

### ISSUE THREAD

**Issue by haskellcamargo** [ocaml/dune#708]
### Problem
- Running `jbuilder runtest --force` shows:

```sh
jbuilder: unknown option `--force'.
Usage: jbuilder runtest [OPTION]... [DIR]...
Try `jbuilder runtest --help' or `jbuilder --help' for more information.
```

- Running `jbuilder runtest` once runs the tests
- Running `jbuilder runtest` again doesn't re-run the tests, but now there is no way to force without recompiling or cleaning something.

### Environment

- `jbuilder` `1.0+beta16`
- `ocaml` `4.06.0`

**Comment by rgrinberg** [comment]
Can you try with the latest jbuilder?

**Comment by haskellcamargo** [comment]
It was a problem in `1.0+beta16`. Upgrading to `1.0+beta20` solves the issue!
