### ISSUE TITLE
Building Opam Packages

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#7096]
The following steps are needed to build an opam package in dune:

1. Fetch the sources
2. Interpret the opam file to get the build/install commands and the list of package dependencies
3. Prepare an environment that contains only the package dependencies
4. Run the build and install commands

The purpose of this ticket is to discuss the steps that we need to take to do all of the above. Our initial goal is to get something working quickly that will unblock us all and allow us to improve things independently.

## Source Fetching

I'm thinking we can just use `opam source` for now.

## Interpreting the Opam File

We're already parsing opam files, so we just need to fetch a couple of more fields. We also need to make sure that all the `dune` and `dune-project` files are ignored in these package source directories.

## Preparing a Build Environment

This will need the following steps:

* Construct the closure of all package dependencies (We'll assume the solver step has already been done for us).
* Build this closure
* Copy all the build artifacts to a directory structure resembling _build/install/default

## Running/Installing

Here we need to be a bit careful. Package sources are supposed to be immutable so we need to make sure that build commands do not overwrite them under any circumstances. Once we've built a package, we need to get the list of artifacts provided by this package by reading the generated .install file. If there's a manual install step, we need to run it into a dummy directory and read the result.

cc @gridbugs @Leonidas-from-XIV

**Comment by tmattio** [comment]
> We also need to make sure that all the dune and dune-project files are ignored in these package source directories.

Shouldn't the dune and dune-project files be used instead of relying on the opam build instruction if the package uses dune as a build system?

I'm thinking that support for building non-dune opam packages is an additional feature and doesn't change the current workflow, in particular:
- Users who vendor Dune packages keep the same behaviour
- Users can also vendor non-dune opam packages, and these are built the way you lay down in the issue

**Comment by rgrinberg** [comment]
> Shouldn't the dune and dune-project files be used instead of relying on the opam build instruction if the package uses dune as a build system?

For v1, that won't be needed. Since we plan to support non dune packages well, I'd like us to work on that first. Eventually, we'll take the opportunity to optimize for dune packages.

> I'm thinking that support for building non-dune opam packages is an additional feature and doesn't change the current workflow, in particular:

The problem is that the compiler isn't built with dune. So if we don't support building the compiler, dune's package management isn't going to be attractive to most users.

**Comment by samoht** [comment]
@rgrinberg How do you see this working with cross-compilation? Could the package inherit the right `dune-worskpace` x-compilation runes?

**Comment by rgrinberg** [comment]
We could make it work with cross compilation as long as non-dune packages follow the `OCAML_TOOLCHAIN` convention.

**Comment by rgrinberg** [comment]
This has been split into separate issues.
