### ISSUE TITLE
Quiet installation

### ISSUE THREAD

**Issue by glondu** [ocaml/dune#7106]
## Desired Behavior

`dune install` prints one line per installed file, and there seems to be no way to avoid this (other than redirecting output to /dev/null). I would like dune to output only errors.

## Example

I just discovered the `--display=quiet` option, but it seems to have no effect on `dune install`. Maybe it could be used to implement a quiet installation?

**Comment by nojb** [comment]
Makes sense to me.

**Comment by Alizter** [comment]
I've written a patch to do what you want. See #7116.

**Comment by ejgallego** [comment]
Duplicate of #4573
