### ISSUE TITLE
docs: `Uncaught ReferenceError: jQuery is not defined` error

### ISSUE THREAD

**Issue by jchavarri** [ocaml/dune#7107]
Opening

https://dune.readthedocs.io/en/stable/search.html?q=variables&check_keywords=yes&area=default

The page never ends loading, and the following error is shown in console:
```
Uncaught ReferenceError: jQuery is not defined
```

Yesterday it was working fine.

**Comment by emillon** [comment]
Hmm, that must be due to the new release which bumped the "stable" pointer. I'll investigate next week. Sorry this wasn't caught.
