### ISSUE TITLE
Dune init's `--public` doesn't allow dashes

### ISSUE THREAD

**Issue by reynir** [ocaml/dune#7108]
## Expected Behavior
Dune init's `--public` can take names with dashes in them.

## Actual Behavior
An error explaining only characters `[a-zA-Z0-9_]` are allowed.

## Reproduction

```shell
$ dune init lib mirage_pair --public mirage-pair
dune: option '--public': invalid component name `mirage-pair'
      Library names must be non-empty and composed only of the
      following
      characters: 'A'..'Z', 'a'..'z', '_' or '0'..'9'.
Usage: dune init library [OPTION]… NAME [PATH]
Try 'dune init library --help' or 'dune --help' for more information.
```

## Specifications

- Version of `dune` (output of `dune --version`): 3.6.1
- Version of `ocaml` (output of `ocamlc --version`) 4.14.0
- Operating system (distribution and version): debian 11.6

**Comment by Alizter** [comment]
Does putting it in quotations work?

**Comment by reynir** [comment]
Sorry how do you mean?

**Comment by Alizter** [comment]
I mean
```
dune init lib mirage_pair --public "mirage-pair"
```

**Comment by reynir** [comment]
No, that does the same.

**Comment by reynir** [comment]
The relevant code is here:
https://github.com/ocaml/dune/blob/d3d628f2eda2278bd2df6e37452d8693f367fcfd/bin/init.ml#L16-L48

The problem is the same converter for library names is used for the public library name. It uses `Lib_name.Local`

https://github.com/ocaml/dune/blob/d3d628f2eda2278bd2df6e37452d8693f367fcfd/src/dune_rules/lib_name.ml#L17-L19

I'm unsure if there's existing code that can be used for the public name or how to go forward on this.

**Comment by PizieDust** [comment]
currently having this issue too
