### ISSUE TITLE
${ROOT} and ${SCOPE_ROOT} not universally available 

### ISSUE THREAD

**Issue by gtrak** [ocaml/dune#712]
With jbuilder beta20, I would expect this to work:

```
  (preprocess (pps (ppx_jane bisect_ppx -conditional (-exclude-file "${ROOT} email_report/src/.exclude"))))
```
But
```
(cd _build/default && ./.ppx/ppx_jane+bisect_ppx/ppx.exe -conditional -exclude-file '${ROOT} email_report/src/.exclude' --dump-ast --cookie 'library-name="email_report"' -o email_report/src/screening_reminder_queries.pp.mli --intf email_report/src/screening_reminder_queries.mli)
File "_none_", line 1:
Error: I/O error: ${ROOT} email_report/src/.exclude: No such file or directory
```

This is needed to work around .merlin files requiring absolute paths.  I will file a separate issue for ppx-bisect needlessly breaking when unused.

**Comment by jeremiedimino** [comment]
@gtrak is that still an issue for you?

**Comment by rgrinberg** [comment]
I'm closing this for now. @emillon is investigating a way to make the dune language a little more consistent. Issues like this will be good motivation.

**Comment by gtrak** [comment]
I think we worked around it, thanks
