### ISSUE TITLE
Missing newline in "dune exec"

### ISSUE THREAD

**Issue by talex5** [ocaml/dune#7142]
This is the same problem reported in #6700, which was apparently fixed but is now broken again in dune 3.7.0 (I don't seem to be able to reopen issues). Note: it does not always happen, but seems more likely after a `dune clean`.

# Expected Behavior

`dune exec` should show the program's output starting on a new line, but instead it appears after the build status. It used to work correctly in dune 3.5.0.

## Reproduction

```
$ dune init project test
Entering directory '/tmp/test'
Success: initialized project component named test

$ cd test
$ dune exec -- ./bin/main.exe
Done: 92% (12/13, 1 left) (jobs: 1)Hello, World!
```

Happens with both `fish` and `bash` shells.

## Specifications

```
$ dune --version
3.7.0

$ ocamlc --version
5.0.0

$ cat /etc/debian_version
11.6
```

**Comment by gadmm** [comment]
I observed this problem and another one that came with it, so it may or may not be related: the output of one of our benchmarking script became garbled with such dune output:
```
$ […] dune exec […] && […] dune exec […] && […] dune exec […]
Done: 86% (20/23, 3 left) (jobs: 0)gc: 1.02s
Done: 50% (4/8, 4 left) (jobs: 0)ocaml: 0.74s
Done: 66% (4/6, 2 left) (jobs: 0)generational: 1.01s
```
Expected:
```
$ […] dune exec […] && […] dune exec […] && […] dune exec […]
gc: 1.02s
ocaml: 0.74s
generational: 1.01s
```
We worked around it by adding `--display=quiet` so we no longer see dune progress status, but this was an unexpected breakage.

```
$ dune --version
3.7.0
$ ocamlc --version
5.0.0
```

**Comment by rgrinberg** [comment]
@gadmm it's a separate issue

**Comment by gadmm** [comment]
@rgrinberg: thanks, good to know!
