### ISSUE TITLE
Missing left side panel stanza links

### ISSUE THREAD

**Issue by toots** [ocaml/dune#7143]
Looks like the different stanza have disappeared from the left side navigation panel https://dune.readthedocs.io/en/stable/dune-files.html#dune

**Comment by jchavarri** [comment]
This is same issue as #7107, caused by jQuery missing, because in latest it does not occur:

https://dune.readthedocs.io/en/latest/dune-files.html#dune

**Comment by emillon** [comment]
Yes, that's the same one. I'm looking for a way to fix the `stable` version.

**Comment by emillon** [comment]
This is now fixed in `stable` too.

**Comment by emillon** [comment]
(thanks for reporting this! this means that somebody reads these docs :) )

**Comment by toots** [comment]
> (thanks for reporting this! this means that somebody reads these docs :) )

All the time! Thanks for the quick fix!
