### ISSUE TITLE
dune formats in new lines when flags in pps, breaking later

### ISSUE THREAD

**Issue by davesnx** [ocaml/dune#7177]
**Describe the bug**

dune formats `(pps ppx1 -- --flag true)` in new lines when the line is too long and in the next dune build it breaks since interprets `--flag` as a ppx.

## Expected Behavior

dune should format into something that allows dune to build/execute.

Worth mentioned a closed issue slightly related to where the proposed syntax might solve elegantly the issue https://github.com/ocaml/dune/issues/2573.

## Actual Behavior

```
(* dune *)

(library
 (name content_explorer)
 (libraries
  bs_css
  bs_css_emotion
  reason_react
  webapi)
 (preprocess
  (pps
   bs-react-intl-ppx.lib
   bs-emotion-ppx.lib
   styled-ppx.lib -- --compat-with-bs-emotion-ppx true)))
```

```
$ dune fmt
File "dune", line 1, characters 0-0:
diff --git a/_build/default/dune b/_build/default/.formatted/dune
index 133c0ed..ad9a112 100644
--- a/_build/default/dune
+++ b/_build/default/.formatted/dune
@@ -1,12 +1,11 @@
 (library
  (name content_explorer)
- (libraries
-  bs_css
-  bs_css_emotion
-  reason_react
-  webapi)
+ (libraries bs_css bs_css_emotion reason_react webapi)
  (preprocess
   (pps
    bs-react-intl-ppx.lib
    bs-emotion-ppx.lib
-   styled-ppx.lib -- --compat-with-bs-emotion-ppx true)))
\ No newline at end of file
+   styled-ppx.lib
+   --
+   --compat-with-bs-emotion-ppx
+   true)))
Promoting _build/default/.formatted/dune to dune.
``` 

If I run `dune build` it doesn't apply arguments into the ppx and fails to build since treats `--compat-with-bs-emotion-ppx` as a ppx. 

## Specifications

- Version of `dune` (output of `dune --version`): 3.7.0
- Version of `ocaml` (output of `ocamlc --version`): 4.14

**Comment by nojb** [comment]
Sorry, but this feels more like a problem with the way we interpret whitespace (is there a reason why we don't ignore it altogether?), rather than with the formatter; do you agree, or am I missing something?

**Comment by emillon** [comment]
I agree that it's a problem with the parser, not the formatter. I'll have a look at this.

**Comment by emillon** [comment]
I had a look and wrote something to check that the ASTs are similar, but it couldn't find a difference.
Do you have a self-contained repro case somewhere?
Also to rule that out:
- are you on windows? (if so, what are the newlines in the input and output files?)
- are there any non-ascii characters in the input files (e.g.: non-breaking space)

**Comment by emillon** [comment]
ping @davesnx - have you been able to reproduce the issue?

**Comment by davesnx** [comment]
Hey @emillon, I haven't, once I created a repro case `dune fmt` didn't break into new lines. 

Probably worth closing this, thanks for the support.

**Comment by davesnx** [comment]
Got the time to repro under cram tests and pushed the PR https://github.com/ocaml/dune/pull/7253

**Comment by emillon** [comment]
Based on the comment in #7253 I'm closing this too. Please reopen if you encounter the bug and can investigate. Thanks!
