### ISSUE TITLE
`dune build --release` doesn't generate library files

### ISSUE THREAD

**Issue by emchristiansen** [ocaml/dune#7276]
When building with `--release`, `dune` doesn't generate `.o` or `.so` files, even though they are explicitly requested via e.g. `(modes object)`.
This seems like a bug, but it could also be surprising intended behavior.

Please see [this issue](https://github.com/zshipko/rust-ocaml-starter/issues/5) for a more complete description of the problem.

I'm using Ubuntu 22.04, OCaml 4.14.1, and Dune 3.7.

**Comment by nojb** [comment]
The `--release` flag is intended for OPAM builds and will only build installable executables and libraries. Perhaps you wanted to use `--profile release` instead?

**Comment by emchristiansen** [comment]
Got it - `--profile release` works as intended.
Thanks!
