### ISSUE TITLE
Exit codes don't match help text

### ISSUE THREAD

**Issue by sim642** [ocaml/dune#7296]
## Expected Behavior
`dune --help` output says:
```
EXIT STATUS
       dune exits with the following status:

       0   on success.

       123 on indiscriminate errors reported on standard error.

       124 on command line parsing errors.

       125 on unexpected internal errors (bugs).
```
This is the default from Cmdliner.

## Actual Behavior
Possible exit codes are 0, 1 and 130:
https://github.com/ocaml/dune/blob/449cbd322ca2a2c50d437d2a2b69d81d5bdf0439/bin/main.ml#L90-L106

## Reproduction

1. Run dune with invalid arguments: `dune --foo`.
2. Check exit code: `echo $?` – currently outputs 1, not 124.

## Specifications

- Version of `dune` (output of `dune --version`): 3.7.0
- Version of `ocaml` (output of `ocamlc --version`): 4.14.0
- Operating system (distribution and version): Xubuntu 22.04.2

**Comment by Alizter** [comment]
These are the untouched cmdliner defaults. We should document this correctly. I don't believe that we output any fancy exit codes (perhaps on internal errors?).
cc @emillon
