### ISSUE TITLE
cinaps fails with Error: Unable to resolve symlink

### ISSUE THREAD

**Issue by smuenzel** [ocaml/dune#7376]
When creating a dune project with `cinaps 1.2` and a file to run cinaps on, `@runtest` will fail with
```
Error: Unable to resolve symlink
```
on the file we apply cinaps to. `cinaps 1.0` works fine.
@hhugo suspects it's related to #6176

## Steps to reproduce
```
git clone git@github.com:smuenzel/sandbox2.git
cd sandbox2
dune build @runtest
```
Note: this is a repo with just one ml file and dune files, cut down from the original repo where I had the issue

## Specifications

```
$ dune --version
3.7.0
$ ocamlopt.opt --version
4.14.1
$ head -n1 /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
```

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag):
- https://gist.github.com/smuenzel/6b84b94a500fa148a40a3b814215c6f8

**Comment by Alizter** [comment]
I am unable to reproduce your example. I just get:
```diff
 |  $ git clone git@github.com:smuenzel/sandbox2.git
+|  Cloning into 'sandbox2'...
 |  $ cd sandbox2
 |  $ dune build @runtest
+|  File "bindings/boolector.ml", line 1, characters 0-0:
+|  Error: Files _build/default/bindings/boolector.ml and
+|  _build/default/bindings/boolector.ml.cinaps-corrected differ.
+|  [1]
 |  $ exit
```

**Comment by hhugo** [comment]
I can reproduce the issue on my machine. @Alizter, you seem to be using some cram tests, could it explain the difference ?

**Comment by Alizter** [comment]
Yes, I can confirm the issue outside of a cram test.

**Comment by Alizter** [comment]
OK, so the issue here is that the build action fails, but we want to print the diff. However since the action is sandboxed, the original failed file gets cleaned up before we can diff it.

**Comment by Alizter** [comment]
OK the issue was that the action we had for the cinaps rule didn't record the source files hence they were missing from the sandbox. I have fixed this and tested that the example here now works (fails) correctly.

https://github.com/ocaml/dune/pull/7618

**Comment by smuenzel** [comment]
> Also FTR `--sandbox none` will get ignored, so that can't be a workaround.

Do you know why this happens? Seems kind of bad if it can't be used to avoid problems with the sandbox.

**Comment by Alizter** [comment]
@smuenzel some actions in Dune rules use sandboxing in a critical way where disabling it would break the rules. The sandbox option is really only for sandboxing declared by the user where it might not be critical.
