### ISSUE TITLE
(Better) Support for Termux Android

### ISSUE THREAD

**Issue by anzhi0708** [ocaml/dune#7385]
Hi, I tried both `opam install dune` and compiling with `make` from source on my Redmi Note 11, but compiler could not find:
- some macros like `PTHREAD_CANCEL_DISABLE`
- related functions like `pthread_setcancelstate(int, int*)`
on Android, Termux.

I used to have a unrootable OPPO phone and successfully installed both `OCaml 5` and `dune` inside of its `proot-distro alpine linux` (Termux emulated Linux environment) but still, that OPPO device was not able to install other packages e.g. `utop` due to the same `pthread` related issues. I didn't try to compile `utop` from source tho. 

Now, I switched my device and found it pretty hard to install `dune` even with `proot-distro` distributions.

The reason I keep using Android is that my laptop / PC are frequently used for serious tasks which always make me feel stressful so whenever it's possible, I want to stay away from those machines. In fact I gained most of my Linux related knowledge using Termux :3

By modifying `configure.ac`, OCaml 5 was installed successfully on native Termux; but I could not find any `configure.ac` inside of this repo, and seems like there's no Android-related code in `boot/` either (I found code for win32 & unix in .ml files tho)

**Comment by Alizter** [comment]
I have also tried to compile Dune in the past on an android phone and ran into the same pthread issues as you have mentioned. AFAIK we don't officially support any mobile platforms, although I don't see why it shouldn't be possible.

I did get dune compiled using Nix however. There should be an app that gives you a Nix shell in Termux which you should be able to use to compile and install dune. Once you have dune and OCaml you can build most OCaml packages yourself anyway.

**Comment by rgrinberg** [comment]
> ; but I could not find any configure.ac inside of this repo, and seems like there's no Android-related code in boot/ either (I found code for win32 & unix in .ml files tho)

There shouldn't be a need for one. If you notice dune relying on some functions that depend on android, just let us know.

**Comment by rgrinberg** [comment]
Please re-open if there are concrete problems or things dune could improve
