### ISSUE TITLE
`dune describe pp` creates an empty `profile.dump` file at the root of the project

### ISSUE THREAD

**Issue by Khady** [ocaml/dune#7430]
## Expected Behavior

`dune describe pp some/file.ml` should print the preprocess file.

## Actual Behavior

It does print the preprocessed file but also creates a `profile.dump` file at the root of the project. This file is empty. I couldn't find a mention of this file in `_build/log`,

## Reproduction

```shell
git clone https://github.com/hhugo/merge-fmt
dune describe pp test/merge.ml
```

## Specifications

- Version of `dune` (output of `dune --version`): 3.6.1 (but also happening on an experimental version of dune)
- Version of `ocaml` (output of `ocamlc --version`): 4.14.0
- Operating system (distribution and version): debian 11

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag): https://gist.github.com/Khady/9660bc040c9c8fc3af90aa50e1fab0cc

**Comment by rgrinberg** [comment]
@nojb any idea what causes this flag to appear?

**Comment by nojb** [comment]
> @nojb any idea what causes this file to appear?

I looked around a bit, but no idea, sorry.

**Comment by emillon** [comment]
I had a look, this file is being created by the compiler [here](https://github.com/ocaml/ocaml/blob/4.14.1/driver/maindriver.ml#L113) (we're invoking the compiler with `-dsource -dump-into-file`).

**Comment by emillon** [comment]
(I'm not very familiar with the compiler driver, but I suppose that since no compilation happens, we end up in that case because no  `Exit_with_status 0` was raised, and the file is empty because `profile_columns` is empty)

**Comment by emillon** [comment]
possible fixes: we could run that command in `_build` (seems fair), we could use `dump-into _build`, we could fix the compiler so that this function is a noop is profile_columns is empty.

**Comment by rgrinberg** [comment]
> we could run that command in _build (seems fair),

That would be a good idea. We should also delete it manually after running the action.

> we could fix the compiler so that this function is a noop is profile_columns is empty.

Worth doing as well.
