### ISSUE TITLE
usability: print separator between reports with `dune build -w`

### ISSUE THREAD

**Issue by askvortsov1** [ocaml/dune#7433]
When I run `dune build`, it's pretty clear what the current errors are. The `[terminal prompt] dune build` line is a pretty clear separator.

Lately, I've been using `dune build -w`, which has a smoother integration with VSCode, and makes me do less overall. Unfortunately, this makes it difficult to see where the current error report starts, and old error reports end. I think readability would greatly improve if we printed a header at the beginning of each error report outputted by `dune build -w`. This could be something as detailed as

```

Build failed with X errors:`
``` 

(hopefully with nice colors), or as simple as a line of `=` or `-` signs.

Note that this also applies to the first error report, as `dune build -w` seems to clear the terminal line that invoked it.

**Comment by Alizter** [comment]
Hi, this was implemented in https://github.com/ocaml/dune/pull/6823 and will appear in Dune 3.8. There is a new command line options `--display-separate-messages` that can be passed.
