### ISSUE TITLE
Building Opam Packages

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#7435]
The goal of this ticket is to design and explain how we're going to build and install opam packages in dune. This is part of the project of turning dune into a full blown package manager capable of being an alternative to opam for some project based workflows.

We assume we've already obtained package sources and their build steps after constructing the lock file.

To build a package, we need to construct a single rule that will produce a directory target that contains all the artifacts in the package. Like all other rules, it will have dependencies, targets, and an action.

### Target

The target will be a directory with all the installed artifacts of the package

### Dependencies

The dependencies will be:

1. The sources of the package being built.
2. For every single package dependency, the target directory with all the build artifacts will be added as a dependency

### Action

The action will produce the directory with the build artifacts by executing the following steps:

1. Apply whatever source patches
2. Set `PATH` and `OCAMLPATH` to include all the bin/ and lib/ directories of all the dependency packages 
3. Run the command in the `build` step of the opam file.
4. If there's an `install` field, we run it with the destination directory being our directory target.
5. If the build step produced the .install file, we move all of its targets to the target directory

## Future Development

For v1, our goal is to put something usable enough that other people can work on and fill in the remaining features. The goal is not to have something users can experiment with. Once we have this ready, we can start working on the various features required for a complete implementation:

1. Sandboxing of the build/installation steps
2. Package Variables
3. Filters
4. Substitutions
6. Patches

(and many others)

**Comment by tonyhuang12138** [comment]
Hello! This might not be related exactly to this update but after updating to the latest macOS (Version 13.3 (22E252)) today and latest dune version (3.6.1), running `dune build` produces the error "Error: write(): Operation timed out" for me.

**Comment by rgrinberg** [comment]
This has been split into separate issues. All the ideas above still hold more or less.
