### ISSUE TITLE
error: unknown field inline_tests

### ISSUE THREAD

**Issue by eriklovlie** [ocaml/dune#745]
I've installed the latest jbuilder in opam 1.2.2 and get this error when trying to do what the published documentation on inline tests state:

```
Error: Unknown field inline_tests
```

**Comment by rgrinberg** [comment]
What is `$ jbuilder --version` say? It should be greater than `1.0+beta19` (latest is `1.0+beta20`)

**Comment by eriklovlie** [comment]
Sorry, should have mentioned that of course:

```
$ jbuilder --version
1.0+beta20

$ cat jbuild
(executable
 ((name foo)
  (libraries (core))
  (inline_tests)
  (preprocess (pps (ppx_jane)))))
```

**Comment by rgrinberg** [comment]
Could you try doing `$ opam reinstall ppx_inline_test` and see if the problem goes away?

**Comment by diml** [comment]
Wait, executable stanzas cannot have inline tests, that's the issue

**Comment by eriklovlie** [comment]
Ah, I see! Ok, so I have to make a library pulling in the modules I want to test?

**Comment by diml** [comment]
Yes. The reason for this limitation is that the entry point of OCaml programs is a toplevel expression which would run before the test runner entry point. So we can only have inline tests in libraries.

One way to workaround this would be to specify programs not by modules but by function. I.e. rather that write `(name foo)`, you would write something like `(main Foo.main)`.

**Comment by eriklovlie** [comment]
Thanks guys!

**Comment by eriklovlie** [comment]
I suppose the error message could have been clearer, but meh.

**Comment by yminsky** [comment]
It would be nice for dune to have an error message that called this issue
out more explicitly. Not sure it's worth the trouble, though.

**Comment by diml** [comment]
it's easy enough to do: #748

**Comment by cogumbreiro** [comment]
> Yes. The reason for this limitation is that the entry point of OCaml programs is a toplevel expression which would run before the test runner entry point. So we can only have inline tests in libraries.
> 
> One way to workaround this would be to specify programs not by modules but by function. I.e. rather that write `(name foo)`, you would write something like `(main Foo.main)`.

Could someone please suggest that need to be done to fix the script below:

```
(executable
 ((name foo)
  (libraries (core))
  (inline_tests)
  (preprocess (pps (ppx_jane)))))
```

Currently,  #745 points to this issue, but there is no self-contained indication on how to work around this problem.

**Comment by diml** [comment]
I was describing one way we could allow inline tests in executable, however it is no (yet) implemented.

For now, you need to move your code to a library `foo_lib` and have your executable be just `Foo_lib.main ()`.

**Comment by olleharstedt** [comment]
Since this is the first result on Google, and I'm having the same issue...

> Error: Unknown field inline_tests

My dune file in the test/ folder:

```
(test                                                                                                                                                                                          
 (name pholyglot)                                                                                                                                                                              
 (inline_tests)                                                                                                                                                                                
 (preprocess (pps ppx_inline_test)))                                                                                                                                      
```

Any ideas...? I did run `opam install ppx_inline_test` without any problems.

**Comment by rgrinberg** [comment]
`(inline_tests)` is only available on library stanzas.

**Comment by olleharstedt** [comment]
> `(inline_tests)` is only available on library stanzas.

That is a more useful error message, hahaha.
