### ISSUE TITLE
Dune can be use to format non-OCaml files ! Is it an accidental feature?

### ISSUE THREAD

**Issue by mbarbin** [ocaml/dune#7615]
Hi!

I've managed to setup dune to format files with a custom extension, using a pretty-printer defined in the repository as a binary, by adding actions to the `fmt` alias that looks like this:

```dune
(rule
 (with-stdout-to
  my-file.ext.pp.output
  (bash "%{bin:my-formatter} file %{dep:my-file.ext}")))

(rule
 (alias fmt)
 (action
  (diff my-file.ext my-file.ext.pp.output)))
```

This works just fine ! When running `dune fmt` all such files get nicely formatted and auto-promoted if needed.

I couldn't find a mention of this setup in the documentation nor in another repository, so I wonder if this is an accidental feature, or if it is reasonable to count on this behavior to keep working with future versions of dune.

## Generating rules for many files

I've gone one step further in that adding such pair of rules for each file in the dune file for each directory is a bit tedious. So in fact these rules are generated in a dune.inc file with another sub-command of the custom formatter.

```dune
(include dune.inc)

(rule
 (deps
  (glob_files *.ext))
 (action
  (with-stdout-to
   dune.inc.gen
   (pipe-stdout
    (bash "%{bin:my-formatter} gen-dune *.ext")
    (run dune format-dune-file)))))

(rule
 (alias runtest)
 (action
  (diff dune.inc dune.inc.gen)))
```

See an actual live example [here](https://github.com/mbarbin/bopkit/blob/main/test/netlist/check/dune.inc)

## Next step?

I suppose maybe someday there will be a more principal way of doing this (perhaps with customizable rules), but I wanted to report that it's very convenient that this already works with the current production dune. Thank you!

Perhaps this was made possible since the introduction of the `fmt` alias? How would you feel about documenting this workaround in the doc, and perhaps adding a test to avoid breaking this workflow? (If you think it is reasonable).

### Cinaps?

The setup to maintain `dune.gen` requires the stanza above (1 include and 2 rules) to be added to the dune files in every directory with files to format, so it is repeated many times. I would love to be able to use `cinaps` here, but I haven't managed to do so yet. I am considering whether to open another ticket regarding cinaps, so perhaps I'll talk about this some place else. I have an intuition that cinaps + generated dune files can go a long way as an alternate power of expression to a more general generic rule mechanism. What do yo think?

Thanks!

**Comment by mbarbin** [comment]
Related #3368 #3836

**Comment by Alizter** [comment]
`dune fmt` is essentially just a command alias for `dune build @fmt --auto-promote`. The ocamlformat rules fall under the `@fmt` alias and you can add to that alias as you wish.

I think this use case may be worth documenting as you say. cc @emillon

**Comment by emillon** [comment]
I think that this use case can be supported by defining a custom `(dialect)`. At the moment I believe that dialects are only meaningful if the source language (`*.ext`) is used to generate OCaml code (is that your case?), but it seems reasonable to extend the dialect mechanism to formatting-only languages.

**Comment by mbarbin** [comment]
Hi @emillon thank you for looking into it!

I am talking specifically about the use case of formatting files that are not dialect of OCaml. Things like a mini-language, a DSL, a specific config, whatever other files you may have in your repo and have a formatter for, etc.

In #3368 it looks like someone perhaps tried using the `(dialect)` construct to format non-OCaml files, but I don't think this works well without requiring changes to dune (I don't know, I haven't tried).

What I was saying is that the "trick" of adding diff actions to the `fmt` alias just works. So the use case I have is already working in the production dune without requiring changes (I am using 3.7.1).

```
(rule
 (alias fmt)
 (action
  (diff my-file.ext my-file.ext.pp.output)))
```

I wasn't sure whether that was intended, hence my question. Based on @Alizter response, it seems you wouldn't have objections to add to the `fmt` alias as needed, so perhaps that's an OK use case to document and support ? Unless you're saying there will be another mechanism to support formatting more generally ?

Thanks!

**Comment by emillon** [comment]
Let me clarify what I meant:

1. The fact that you can attach diff actions to the `fmt` alias and expect it to be picked up by `dune fmt` is something you can rely on. It relies on several documented behaviors, but it's true that you have to connect the dots a bit and it can be documented in itself.
2. The fact that you have to do that by hand (or with a generator) for each `*.ext` file is not a great experience and I wish there was a better way to do it. It seems valid to extend the dialects mechanism to support this. If (/when) this is implemented, you'll be able to set an integration between your formatter and `dune fmt` with a single stanza in `(dune-project)`.

**Comment by mbarbin** [comment]
Got it, this sounds good to me. Thank you!

**Comment by mbarbin** [comment]
The added doc for aliases looks great. Thank you!

**Comment by emillon** [comment]
Glad you like it!
