### ISSUE TITLE
Vendor the 0install solver

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#7641]
The 0install solver will be needed to generate lock files. To use it, we must vendor it in dune.

**Comment by gridbugs** [comment]
Why is it necessary to vendor the solver? Why not add it as a regular dependency?

**Comment by Alizter** [comment]
@gridbugs because 0install is built using dune itself, so as we do with every such dependency we need to vendor it.

**Comment by rgrinberg** [comment]
Even if 0install was built without dune, we would still need to vendor it. This is because we require only two things to build dune:

1. And OCaml compiler
2. A C Compiler

This makes it easy for anyone to get started with dune.
