### ISSUE TITLE
byte_complete modes for project using mixed C/OCaml library.

### ISSUE THREAD

**Issue by guangshengfan** [ocaml/dune#7649]
I use dune to develop a project, which use Apron (https://github.com/antoinemine/apron). I try to compile my project use dune, and wish to get a binary_complete executable file that can copy to any other machine without OCaml evironment. 
I use: 

(executable
  (name ai )
  (public_name ai)
  (modes  byte_complete) ; 
  (libraries apron  ...)
  (flags -w  )
)

However,  I meet a problem:

/usr/bin/ld: _opam/lib/apron/libapron_caml.a(scalar_caml.o): in function `camlidl_apron_scalar_c2ml':
scalar_caml.c:(.text+0x104): undefined reference to `camlidl_mpq_ptr_c2ml'

how can we use byte_complete modes for project using mixed C/OCaml library?

**Comment by nojb** [comment]
I haven't looked in detail at your specific question, but is there a reason you are using `byte_complete` (which is bytecode) instead of a normal native executable?

**Comment by guangshengfan** [comment]
I just want to compile my project into an executable file and copy it to other machine that can not install  OCaml nor other dependencies. I have tried to use native executable, but it alert "can not find dependency ***". Therefore, I want to compile my project into an executable file that includes all dependencies. It seems byte_complete mode help this, but I failed.

**Comment by anmonteiro** [comment]
> /usr/bin/ld: _opam/lib/apron/libapron_caml.a(scalar_caml.o): in function camlidl_apron_scalar_c2ml': scalar_caml.c:(.text+0x104): undefined reference to camlidl_mpq_ptr_c2ml'

- This error probably means that some dynamically linked C names aren't installed in the target machine
- It doesn't seem, to me, that this is a dune issue. If you're looking to compile executables for other machines, you might want to try linking a native executable (`.exe`) statically.

**Comment by guangshengfan** [comment]
Thank you very much!
