### ISSUE TITLE
Can we add Seq.t to dyn?

### ISSUE THREAD

**Issue by yawaramin** [ocaml/dune#7678]
Currently, dyn supports many standard OCaml types including lists, arrays, maps, and sets: https://github.com/ocaml/dune/blob/main/otherlibs/dyn/dyn.mli

Can we add the `Seq.t` type to the supported representations? This would enable building dyn values from sequences of elements that could work in constant memory.

**Comment by rgrinberg** [comment]
To do anything useful (compare, serialize, hash) with this `Seq.t` as `Dyn.t` you would have to force it anyway.

**Comment by yawaramin** [comment]
Sure. But the question is would we be able to do it in constant memory. E.g. if we had a variant case `Seq of t Seq.t`, the `t Seq.t` would be built lazily by mapping over some source Seq. To serialize it, suppose we are printing it using `pp`. We would use `Seq.iter` to process the elements one at a time. So the source Seq would be consumed one element at a time, only at the point of serialization.

Unless there is some other reason why we would need to first consume the entire Seq into memory.

**Comment by Alizter** [comment]
What do you want to do with this Dyn other than printing? Since i think pping will have to load it all into memory, maybe you have another use case in mind?

**Comment by yawaramin** [comment]
I actually don't understand why printing a Seq would have to force loading it all into memory first, can you explain? Let's say we are copying a file line by line into a new file. Would we not read and print one line at a time when using a Seq?

**Comment by Alizter** [comment]
For printing directly, that can be the case. However we are first converting to the Pp.t data structure which will necessarily all be loaded into memory before it can be printed.

**Comment by yawaramin** [comment]
Oh, I see. The `pp` library itself requires having the entire data structure in memory before it can do anything with it. It can't process a lazy stream of data. Got it.

**Comment by yawaramin** [comment]
I was looking at more generalized marshalling/unmarshalling use cases. `pp` may have the limitation, but if we ignore that for a second I don't think `dyn` inherently requires loading all data into memory?

**Comment by rgrinberg** [comment]
To marshal `Seq.t`, you would have to marshal a closure. While that's possible, it has a lot of limitations.

**Comment by Alizter** [comment]
I thought about this a bit more today and I suppose we could add a `Thunk : unit -> Dyn.t` constructor. This would allow us to write a to_dyn for `Seq.t` and perhaps anything else that needs side effects or delaying.

Whether or not this is useful for Dune is another question. (I don't think so). There is nothing stopping you from using your own version of dyn though.

Something like this might work:
```diff
diff --git a/otherlibs/dyn/dyn.ml b/otherlibs/dyn/dyn.ml
index 72d499b27..32d25e302 100644
--- a/otherlibs/dyn/dyn.ml
+++ b/otherlibs/dyn/dyn.ml
@@ -2,6 +2,7 @@ module Array = Stdlib.ArrayLabels
 module List = Stdlib.ListLabels
 module String = Stdlib.StringLabels
 module Bytes = Stdlib.Bytes
+module Seq = Stdlib.Seq

 type t =
   | Opaque
@@ -23,6 +24,7 @@ type t =
   | Variant of string * t list
   | Map of (t * t) list
   | Set of t list
+  | Thunk of (unit -> t)

 let unsnoc l =
   match List.rev l with
@@ -113,6 +115,7 @@ let rec pp =
     Pp.hvbox ~indent:2
       (Pp.concat
          [ Pp.verbatim v; Pp.space; Pp.concat_map ~sep:(Pp.char ',') xs ~f:pp ])
+  | Thunk f -> pp (f ())

 let to_string t = Format.asprintf "%a" Pp.to_fmt (pp t)

@@ -156,6 +159,12 @@ let opaque _ = Opaque

 let variant s args = Variant (s, args)

+let rec seq f (s : 'a Seq.t) = Thunk (fun () -> seq_node f (s ()))
+
+and seq_node f = function
+  | Nil -> List []
+  | Cons (x, s) -> List [ f x; seq f s ]
+
 let hash = Stdlib.Hashtbl.hash

 let compare x y = Ordering.of_int (compare x y)
diff --git a/otherlibs/dyn/dyn.mli b/otherlibs/dyn/dyn.mli
index f59297cb6..5a5d7f498 100644
--- a/otherlibs/dyn/dyn.mli
+++ b/otherlibs/dyn/dyn.mli
@@ -22,6 +22,7 @@ type t =
   | Variant of string * t list
   | Map of (t * t) list
   | Set of t list
+  | Thunk of (unit -> t)

 val equal : t -> t -> bool

@@ -70,3 +71,5 @@ val opaque : _ builder
 val record : (string * t) list -> t

 val variant : string -> t list -> t
+
+val seq : 'a builder -> 'a Seq.t builder
```

**Comment by nojb** [comment]
I don't have a horse in this race, but I fail to see a reason to complicate `Dyn.t` with thunks. Right now `Dyn.t` is serializable; with thunks it would no longer be so.

More generally, my understanding was that `Dyn.t` was intended for the use of Dune and associated tools. I'm not sure it is wise to start adding features for other unrelated use-cases. Instead, a separated, dedicated general-purpose library should be developed for such use-cases by those interested, which will be better placed to evaluate the design choices of such a library.

**Comment by Alizter** [comment]
@nojb I absolutely agree. Note that I didn't suggest that it should be done, but rather attempted to answer how it could be done.

**Comment by yawaramin** [comment]
Understood, and that makes sense.
