### ISSUE TITLE
Make OpamSysPoll usable in dune

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#7690]
This opam module is needed to evaluate forms such as `%{os-family}`. At the moment, the module runs system commands. This doesn't work with dune's process reaper.  To make this module usable in dune, it should allow the caller to spawn the processes.

**Comment by Leonidas-from-XIV** [comment]
Upstream PR to implement this in OPAM: https://github.com/ocaml/opam/pull/5549

**Comment by rgrinberg** [comment]
Thanks. Perhaps you could try using this code on the dune side to substitute os-family in pkg_rules.ml?

Just to make sure that your PR works as expected.
