### ISSUE TITLE
melange: expose a mechanism to enable conditional compilation

### ISSUE THREAD

**Issue by jchavarri** [ocaml/dune#7717]
## Desired Behavior

While virtual libraries are a great mechanism to support conditional compilation, and Melange already supports them, sometimes it is useful to introduce branching at the module level.

For example, [cppo](https://github.com/ocaml-community/cppo) allows to check for defined values to conditionally compile some code.

One could generate a cppo rule like:

```
(rule
 (targets foo.ml)
 (deps
  (:first-dep foo.cppo.ml))
 (action
  (run %{bin:cppo} -D MELANGE %{first-dep} -o %{targets})))
```

Some other analog rule would be defined for native, but without the `-D MELANGE` part.

Unfortunately at the moment, it is not possible to express from a `dune` file which rules are applied only for Melange targets, or only for OCaml targets.

A similar feature was added for foreign stubs in https://github.com/ocaml/dune/pull/5649.

cc @davesnx @anmonteiro

**Comment by anmonteiro** [comment]
I believe this has been superseded by #10222. Please reopen if not.
