### ISSUE TITLE
Add note about .mli-generation methods in docs

### ISSUE THREAD

**Issue by mars0i** [ocaml/dune#772]
Two issues, #150 and #443, requested a way for `dune` to automatically generate .mli files.  I don't object to the issues being closed--there are other methods available--but given that `oasis` generated .mli files automatically (and many projects will continue to use `oasis` for a while, so some people will be aware of what it does), and given that `ocamlc` can generate .mli contents using `-i`, I suspect that there will be recurring questions about how to generate .mli files with `dune`.  So maybe it would be worth adding a note in the documentation pointing out that `merlin` and `cmitomli` can generate .mli files.  It's not a `dune` issue, of course, but people will keep asking it about `dune`.  Maybe in the FAQ section of the manual?

**Comment by diml** [comment]
Updating the documentation seems fine.

Personally, I wouldn't object to adding a command that would wrap the call to `cmitomli` for convenience. For instance:

```
$ dune print-intf src/foo.ml
type t
val x : t
...
```

**Comment by avsm** [comment]
This would be useful for us to have in RWO, as there are several places where calling `ocamlc -i` would be useful for exposition purposes.  However, the `dune print-intf` does introduce a dependency on the OCaml compiler version that was used to compile the `dune` binary, so this seems like a no-go for dune 2.0 (where the binary is compiler-version independent).

What's the best way to expose this as a dune command otherwise?  We could publish this as a standalone binary in opam if there's no easy way to do as a dune sub-command.

**Comment by diml** [comment]
Oh, I was thinking for `dune print-intf` to call `cmitomli` (or `ocamlc -i`).

**Comment by avsm** [comment]
ok, I'll publish a cmitomli into opam then, to make the binary available to dune to invoke.

**Comment by diml** [comment]
BTW, we could also upstream this, or make it an option of `ocamlobjinfo`. It looks very small

**Comment by avsm** [comment]
I just wrote a ocaml-print-intf executable here as it was so small: https://github.com/avsm/ocaml-print-intf

**Comment by avsm** [comment]
@NathanReb if you get a chance, the dune integration here to do the invocation of ocaml-print-intf with the cmi file would let us get rid of the remaining corebuild uses

**Comment by NathanReb** [comment]
Sure I'll take a look!

**Comment by emillon** [comment]
Now that this works and is published on opam, I think a pointer to `ocaml-print-intf` can be added to the doc and this should be enough to close this issue.

**Comment by jeremiedimino** [comment]
Agreed

**Comment by mars0i** [comment]
I'll trust you guys on this.  I am working on other things lately.  Thanks.
