### ISSUE TITLE
Windows: Merlin configuration incompatible after 3.6.2

### ISSUE THREAD

**Issue by jonahbeckford** [ocaml/dune#7753]
Summary: Works on Dune `3.6.2`. But fails with Dune `3.7.1`,` 3.8.0_alpha~2` and `3.8.0_alpha~3`

## Expected Behavior

No problems when I rebuild my code with Dune 3.6.2.

## Actual Behavior

1. Compile with Dune `3.7.1`,` 3.8.0_alpha~2` and `3.8.0_alpha~3`

2. In Visual Studio Code through `ocamllsp` I get:

   ```
   The current Merlin configuration has been
   generated by another, incompatible, version of Dune.
   Please rebuild the project. (Using the same version of Dune
   as the one running the `ocaml-merlin` server.) ocamllsp
   ```

3. Recompile with Dune `3.6.2`
4. No problems with `ocamllsp`.

## Reproduction

I don't think this is specific to my (internal) source code project. All four (4) versions of Dune work with macOS for example.

*For my notes: scratch_6.md in dksdk-cmake project*

## Specifications

* IDE: Visual Studio Code
* OS: Windows 64-bit
* OCaml Platform plugin: v1.12.2 (Latest)
* ocamllsp: 1.15.1-4.14 (latest for ocaml 4.x)
* OCaml: 4.14.0

**Comment by nojb** [comment]
Hello, is this a problem of having a stale Merlin server left running in the background? See eg https://github.com/ocaml/merlin/issues/1591

**Comment by jonahbeckford** [comment]
Don't think so. Did the following to confirm that no servers were in the background:

```powershell
taskkill /F /IM ocamllsp.exe
taskkill /F /IM ocamlmerlin.exe
taskkill /F /IM dune.exe
taskkill /F /IM dune-real.exe
```

**Comment by jonahbeckford** [comment]
Figured it out. `ocamllsp` was picking up `dune` from the system PATH; must be spawning out to `dune` transparently. More specifically, it was ignoring the custom PATH set through `ocaml.sandbox`:

```json
{
    "ocaml.sandbox": {
        "kind": "custom",
        "template": "...PATH-setting-script... $prog $args"
    }
}
```

I'll transfer the issue to the right queue since nothing is wrong with Dune.
