### ISSUE TITLE
extra $TESTCASE_ROOT print since #7703

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#7779]
Since #7703 got merged, I'm seeing local consistent failures like this. This is very strange since it looks fairly unrelated. Do you have an idea what this could be?

```diff
--- a/_build/.sandbox/ab08f82e1b66bb77b75f14bbbc41fe2c/default/test/blackbox-tests/test-cases/action-runner/build-e2e.t
+++ b/_build/.sandbox/ab08f82e1b66bb77b75f14bbbc41fe2c/default/test/blackbox-tests/test-cases/action-runner/build-e2e.t.corrected
@@ -18,4 +18,5 @@ dune command
   # mkdir -p _build/default/ar1;cd _build/default/ar1;echo -n xxx > aaa
   $ ar2="_build/ar2.*.log"
   $ grep bbb $ar2
+  # $TESTCASE_ROOT
   # mkdir -p _build/default/ar2;cd _build/default/ar2;echo -n yyy > bbb
make: *** [Makefile:102: test] Error 1   
```

_Originally posted by @emillon in https://github.com/ocaml/dune/issues/7703#issuecomment-1557323433_

**Comment by rgrinberg** [comment]
I've seen this error a few times before the relevant PR.  We should just the `grep` command to look for a `# mkdir` in the beginning to keep things more precise.

**Comment by emillon** [comment]
It looked deterministic to me but I can't repro it anymore. Possibly it's when the tempdir contains `bbb` which seems less likely than I've seen it, but it's still flaky. I'm leaving this off the milestone.
