### ISSUE TITLE
Error: "Missing mandir" (dune install)

### ISSUE THREAD

**Issue by bentxt** [ocaml/dune#7814]
## Expected Behavior

run 
```
 dune install
``` 
in a project folder in order to install the project and its built artefact in the default locations

## Actual Behavior

```
> dune install
Error: The mandir installation directory is unknown.
Hint: It could be specified with --mandir
```

## Specifications
```
> dune --version
3.7.0
> opam --version
2.1.4
> ocaml --version
The OCaml toplevel, version 4.14.1
```

## Additional information 

My default mandir directory exists, so no need for specifying a folder I think

```
ls /usr/local/share/man
de/   ja/   man1/ man3/ man5/ man7/ man8/
```

Here some additional info on mandir:

https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

> ‘mandir’
>The top-level directory for installing the man pages (if any) for this package. It will normally be /usr/local/share/man, but you >should write it as $(datarootdir)/man. (If you are using Autoconf, write it as ‘@mandir@’.)

**Comment by bentxt** [comment]
Specifying `--mandir` was no enough. I had to specify all the locations like this
```
sudo dune install --mandir=/usr/local/share/man --docdir=/usr/local/share/doc/p5scm --etcdir=/usr/local/etc/ --datadir=/usr/local/share/p5scm --sbindir=/usr/local/sbin --bindir=/usr/local/bin/ --libexecdir=/usr/local/libexec/ --libdir=/usr/local/lib/
```

Additional problem 
 --libexecdir=/usr/local/libexec/ is now at a non-standard location since /usr/libexec is non-sudoable on macos

**Comment by NielsMommen** [comment]
Did you configure dune with custom locations before building it? I know it might happen in that case.

You can also try to pass `--prefix=usr/local` instead of passing all paths individually. Paths that occur after this option override the `prefix` path. E.g. `--prefix=usr/local --libexecdir=/my/custom/path/to/override/usr/local/libexec`

**Comment by bentxt** [comment]
> You can also try to pass `--prefix=usr/local`

This works thanks

**Comment by bentxt** [comment]
Just a note: It seems like the problems I had with dune asking for all this directories was due to lacking Opam initialization. 

No that the Opam init script is invoked during shell initialization, those problems are solved

I wrote also small tip about it in the ocaml forum: https://discuss.ocaml.org/t/tipp-if-opam-gives-you-grief-check-your-init-ba-fi-c-sh-file/12265

**Comment by Alizter** [comment]
Yes, that probably explains why we don't see this issue so often in the wild. However I have seen and been confused by this message before and I do not use opam so at least we can improve this.
