### ISSUE TITLE
return code is 0 when no jbuild file found

### ISSUE THREAD

**Issue by gares** [ocaml/dune#795]
```
gares@gargamel:~$ eval `opam config --root=~/opam-roots/4.06/ env`
gares@gargamel:~$ mkdir foo
gares@gargamel:~$ cd foo
gares@gargamel:~/foo$ jbuilder build @install # terminates immediately
gares@gargamel:~/foo$ echo $?
0
```
For reference https://github.com/coq/coq/pull/7575#issuecomment-391267779

**Comment by rgrinberg** [comment]
This isn't necessarily wrong. You're essentially asking dune to build an empty alias. You can probably replicate this with any alias with an empty `deps` field.

**Comment by ejgallego** [comment]
Yeah I guess what Enrico wants is `jbuilder -p $PKG build`, but indeed it took me a while to realize about the distinction about the two.

**Comment by gares** [comment]
I see you POV but I quite don't see the usecase.

In my opinion you miss the opportunity to tell the user "hey, you are in the wrong directory" or the opportunity to make a script using jbuilder fail early (eg someone changed the FS layout and now jbuilder is being invoked in the wrong place). The latter is actually what happens in https://github.com/coq/coq/pull/7575#issuecomment-391267779 that made me open this issue.

Is there are use case for expecting jbuilder (even in "developer mode") to do nothing without complaining?

**Comment by rgrinberg** [comment]
Yeah, I'm just not sure what's a good way to fix this without breaking other legitimate use cases. For example, I can imagine a build where the test alias (`runtest`) is defined conditionally and doesn't include any dependencies on a particular platform. In this situation, building this empty alias should succeed.

Perhaps we can fail builds where dune fails to discover at least 1 dune file?

**Comment by gares** [comment]
Well, that is what the title of this PR is about (to my limited knowledge of dune, "dune file" is named `jbuild`).

The fact that a target (I guess this is what you call alias) is a no-op on some platforms is OK to me, but it is not what I'm complaining about. Sorry if my dune jargon and understanding is poor.

**Comment by diml** [comment]
That's basically the idea. I suppose we could have a special case for the `install` alias, since I don't think the current behaviour is useful in practice and it can be surprising if you don't know the details. For `runtest` I agree with @rgrinberg that dune shouldn't fail when it's empty.

Maybe:

```
$ dune build
Error: The "install" alias is empty as there are no packages in the current workspace.
Hint: Did you run dune from the right place?
```

**Comment by gares** [comment]
Maybe to make my "surprise" more clear I should compare dune with other tools.

For example `make` givens an error if there is no `Makefile`. The same for `cmake` if there is no `CMakeLists.txt`. I'm pretty sure you can find others.

If you see `$tool` as in interpreter for its "build language", then calling `$tool` with no program makes little sense, while calling it on an "empty" program is fine and it just does what it was asked to do (that is nothing).

**Comment by rgrinberg** [comment]
I think that failing the build when no dune (or jbuild) file is found is reasonable. Dune doesn't have any implicit rules so a project without a dune file is almost certainly wrong.

Your comparison with other tools isn't quite apple to apples. `$ dune build` is the same as `$ dune build @install`. Make also allows you to run rules without a Makefile:

```
$ touch foo && make foo
[rgrinberg:~/tmp] % touch foo && make foo
make: Nothing to be done for `foo'.
[rgrinberg:~/tmp] % echo $?
0
```

Even worse:

```
[rgrinberg:~/tmp] % touch foo.c && make foo.o
cc    -c -o foo.o foo.c
```

**Comment by rgrinberg** [comment]
@gares please re-open if you have any fresh objections to the current behavior.
