### ISSUE TITLE
Can't install dune 3.8 in Windows CI

### ISSUE THREAD

**Issue by davesnx** [ocaml/dune#7963]
## Expected Behavior
I should install dune in setup-ocaml when dune >= 3.8.0, I'm unsure if it's because mingw don't have the version updated or some other reason. Nevertheless, opening the issue 

## Actual Behavior
```
Install system packages required by opam packages
  C:\Windows\system32\cmd.exe /D /S /C "D:\cygwin\wrapperbin\opam.cmd depext reactjs-jsx-ppx reason-react"
  # Detecting depexts using vars: arch=x86_64, os=win32, os-distribution=cygwinports, os-family=windows
  [ERROR] No solution for reactjs-jsx-ppx & reason-react: The following dependencies couldn't be met:
            - reason-react -> dune >= 3.8
                no matching version
```

## Reproduction

This is a repo: https://github.com/reasonml/reason-react/actions/runs/5242063430/jobs/9464982708

## Specifications

- Version of `dune` (output of `dune --version`): 3.8.0
- Version of `ocaml` (output of `ocamlc --version`): 4.14.x
- Operating system (distribution and version): Windows

**Comment by emillon** [comment]
Hi,
That seems to be an issue with how ocaml/setup-ocaml sets up repositories. Apparently it uses https://github.com/ocaml-opam/opam-repository-mingw, which is not kept up to date. That seems to be on purpose, the situation is described [here](https://github.com/ocaml-opam/opam-repository-mingw#updates) and there's a workaround with an example setup-ocaml configuration mentioned.
I'm closing this since it's not an issue with dune itself, but if the workaround is not enough I would suggest opening an issue on ocaml/setup-ocaml.
Thanks!

**Comment by davesnx** [comment]
I believe the mingw repository is used when is Windows per: https://github.com/ocaml/setup-ocaml/blob/df82ae6bd3aad42c88dff020d3fab98ef5a2c668/packages/setup-ocaml/src/constants.ts#L77-L80

This means that dune 3.8 isn't available under https://github.com/ocaml-opam/opam-repository-mingw, right?

**Comment by emillon** [comment]
Yes, these points are both correct.
The recommended fix in the "Updates" part of the README is to set up both remotes with:

```
uses: ocaml/setup-ocaml@v2
with:
  opam-repositories: |
    opam-repository-mingw: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
    default: https://github.com/ocaml/opam-repository.git
```

That way, it will take 3.8.0 even if it's just in `default`. My understanding is that opam-repository-mingw is just an "overlay" for packages that need special patches (which is not the case of dune 3.8.0).

**Comment by davesnx** [comment]
I tried that exact thing after reading the readme and didn't work not even in ubuntu :(

https://github.com/reasonml/reason-react/pull/738
