### ISSUE TITLE
Support the "word_size" variable in "enabled_if".

### ISSUE THREAD

**Issue by rlepigre** [ocaml/dune#7997]
## Desired Behavior

The variables accessible as part of the `enabled_if` field of the `library` stanza (and probably others like `executable`) only support a limited range of variables that does not include `word_size`. I think it would make sense to include it so that one can restrict the compilation of a library to 64-bit architectures, which makes sense if you rely, e.g., on an `int` counters not overflowing, but you do not want to pay the extra cost of using an `Int64.t`.

**Comment by Alizter** [comment]
I've started a draft, but I will have to do some more detailed testing later.

**Comment by hhugo** [comment]
There exists Int63 for this very use case (see https://discuss.ocaml.org/t/advantage-of-int63-compared-to-int64/7465)

**Comment by rlepigre** [comment]
> There exists Int63 for this very use case (see https://discuss.ocaml.org/t/advantage-of-int63-compared-to-int64/7465)

Good to know, thanks. In the use case I had in mind that would not work though, because it is not really an option to pull in a new dependency. It's be great if a type like this was in the OCaml standard library.

**Comment by hhugo** [comment]
> > There exists Int63 for this very use case (see https://discuss.ocaml.org/t/advantage-of-int63-compared-to-int64/7465)
> 
> Good to know, thanks. In the use case I had in mind that would not work though, because it is not really an option to pull in a new dependency. It's be great if a type like this was in the OCaml standard library.

It also exists in https://opam.ocaml.org/packages/optint/

**Comment by hhugo** [comment]
The doc mentions the `arch_sixtyfour` variable which seems to fit your usecase.
Note that word_size/int_size is a property of the runtime when building a bytecode executable because one could build a bytecode on 64bit arch and run it on a 32bit one.

**Comment by rlepigre** [comment]
I see, makes sense. However, `arch_sixtyfour` is not supported either in `enabled_if`.
```
File "perf/dune", line 7, characters 18-35:
7 |  (enabled_if (and %{arch_sixtyfour} (= %{system} linux))))
                      ^^^^^^^^^^^^^^^^^
Error: Only architecture, system, model, os_type, ccomp_type, profile,
ocaml_version and context_name variables are allowed in this 'enabled_if'
field. If you think that arch_sixtyfour should also be allowed, please file
an issue about it.
```

**Comment by hhugo** [comment]
cc @Alizter

**Comment by Alizter** [comment]
Yes, we could probably add this in. I'll draft somrthing later on.

**Comment by Alizter** [comment]
OK here is the PR https://github.com/ocaml/dune/pull/8023
