### ISSUE TITLE
Better Digest Handling

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#8009]
This ticket describes some issues I've ran into trying to cleanup our digest handling. The issues are

* We're actually not computing all digests asynchronously as we expected. In particular, all digests in `Cached_digest` are done synchronously.

* We're likely recomputing some digests. The shared cache is computing its own digests and this is unnecessary.

* We have a safety mechanism that tries to protect files from being modified as we compute their digest. This safety mechanism should be pushed to dune's local cache so that it's done as early as possible. It should also decouple the "mode" that it uses to achieve this safety from the "mode" the dune cache uses for restoring artifacts.

To solve the first problem, it would be be best to push the asynchronous behavior all the way up to our digest library. That would work make sure that we are unable to introduce any synchronous digest computation accidentally. However, this would require splitting the scheduler from the engine which isn't the easiest thing to do. As a compromise, it might be easier to just introduce the asynchronicity in `Cached_digest`. 

The second problem is easily solved via refactoring.

cc @snowleopard

**Comment by Alizter** [comment]
Would it be possible for the digest computation to just take a "generic scheduler" and then instantiate it with the scheduler from the engine when needed?

**Comment by rgrinberg** [comment]
> Would it be possible for the digest computation to just take a "generic scheduler" and then instantiate it with the scheduler from the engine when needed?

We did that before and it's very annoying to have to juggle forward declarations. It's a possibility though.

**Comment by Alizter** [comment]
You could probably do it without forward declarations however. If the digests were a functor taking in a scheduler, then you can create a version of the digests library instantiated in the engine. Is the digest library used elsewhere?
