### ISSUE TITLE
Caching of Directory Targets

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#8067]
Currently, rules which produce directories are ignored by the cache. This is unfortunate, because such rules are often quite heavy and would benefit a lot from caching.

It should be straightforward to extend the cache to support directories. The only requirement is that we store them in the cache which reuses equivalent files between directories targets produced by different rules.

There's a couple of approaches we can take. Our current representation of cache entries is essentially `Filename.t list`. The simplest way to extend it would be to make it `Path.Local.t list`. Which would allow for entries relative to sub directories. This is already enough for sharing all files between targets and doesn't require us to change the format of the cache.

If we we wanted to share entire directories between entries, we could imagine imagine changing the format to `(kind * Filename.t) list` where `type kind = File | Directory`. The advantage of this representation is that we don't need to repeat the same file lists if they're reused. The disadvantage is that it requires changing our entries format.

cc @snowleopard

**Comment by snowleopard** [comment]
We are planning to take a look at this internally, as part of an intern project that starts next week.

**Comment by snowleopard** [comment]
The intern project didn't happen unfortunately, so as far as I know noone is currently working on this.
