### ISSUE TITLE
Patch files in lockdir

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#8093]
Opam files have a `patches` field which lists patches to apply to the source before building. The patch files are stored in the opam repository itself (not within the package source). In order to build a dune package from a lockdir without consulting the opam repository the lockdir will need to store patches for any locked packages which require them. Patch files will be stored in the directory `<package>.files` inside the lockdir (see https://github.com/ocaml/dune/issues/8095 for more on the `<package>.files` directory).

Not all the files in `<package>.files` will necessarily be patches, and opam allows patches to be conditionally applied based on filters so we'll need a field in the `<package>.pkg` metadata file which includes a list of packages and the conditions under which they should be applied.

**Comment by rgrinberg** [comment]
This is implemented in the build rules (see `pkg/patch.t`) but we still need to convert .opam files to the appropriate build rules.

**Comment by rgrinberg** [comment]
@gridbugs assigning the conversion step to you

**Comment by Alizter** [comment]
@rgrinberg This is done now.
