### ISSUE TITLE
Opam variable interpolation while building packages with dune

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#8094]
Opam applies [variable interpolation](https://opam.ocaml.org/doc/Manual.html#Interpolation) when building packages replacing <file>.in with <file> after substituting variables with their values using the syntax `%{var}%`. Dune will need to copy this behavior while building packages. Note that variable interpolation is also applied to patch files (see https://github.com/ocaml/dune/issues/8093 for details on patch files in dune).

**Comment by rgrinberg** [comment]
More information here: https://github.com/ocaml/dune/issues/7698

**Comment by rgrinberg** [comment]
@Leonidas-from-XIV do you think this can be closed?

**Comment by Leonidas-from-XIV** [comment]
Yes, I think we're good.
