### ISSUE TITLE
Per-package files from opam repository in lockdir

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#8095]
Each package version in the opam repo can have a "files" directory containing files that are copied into the root of the package source before building. This mechanism is used to provide patches for packages but can also be used to copy arbitrary files. Since these files are taken from the opam repo itself rather than the package source, in order for dune to build a package from a lockdir without consulting the opam repo, the files associated with a package version will need to be stored inside the lockdir. For packages with extra files, these files should be stored in a directory `<package>.files` inside the lockdir.

**Comment by rgrinberg** [comment]
We have this now.
