### ISSUE TITLE
Support instrumention settings in profile definitions

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#8116]
Today one can enable an instrumentation globally or on a per-context basis. I think it would be useful to also allow enabling an instrumentation on a per-profile basis:
```
(env
 (bisect
  (instrument_with bisect_ppx))
 (_ (...)))
```
This would allow toggling instrumentations by switching profiles, without needing to define different contexts.

What do you think?

**Comment by Alizter** [comment]
Will this allow us to stop having to add `(instrument_with)` to stanzas? If so, how do we prevent instrumentation on stanzas?

**Comment by nojb** [comment]
> Will this allow us to stop having to add `(instrument_with)` to stanzas?

Do you mean `(instrumentation)`? Assuming I understood correctly, the answer is: no; you still need to add this field manually to those stanzas that you want instrumented.

**Comment by rgrinberg** [comment]
Sounds OK to me. But the way you have it with `env`, you're implying that you can set this field per directory. Is that intended?

**Comment by nojb** [comment]
> Sounds OK to me. But the way you have it with `env`, you're implying that you can set this field per directory. Is that intended?

No, it is not. I put it under `(env)` because I don't think we have any other stanza that can specify per-profile settings...

**Comment by rgrinberg** [comment]
What about allowing some sort of match expression in the `instrument_with` field?

```
(instrument_with
 (case %{profile}
  (dev (foo))
  (* ()))
```

**Comment by nojb** [comment]
After a bit more thought, I'm closing this as I think it is too much of a fringe feature to spend time on.
