### ISSUE TITLE
jbuilder disappears when installing from pinned master

### ISSUE THREAD

**Issue by bluddy** [ocaml/dune#812]
I pinned jbuilder to master in ocaml 4.06.1 and opam 1.2, and jbuilder disappeared. No jbuilder, no dune executable present.

**Comment by bobbypriambodo** [comment]
I think this is due to renaming `jbuilder.opam` into `dune.opam` in #721. This doesn't work (no executables are present):

```
opam pin add jbuilder https://github.com/ocaml/dune.git#master
```

but this works:

```
opam pin add dune https://github.com/ocaml/dune.git#master
```

It puts both `jbuilder` and `dune` in your `bin` directory.

**Comment by bluddy** [comment]
Furthermore, `dune` doesn't seem to exist as a package in opam 1.2

**Comment by hcarty** [comment]
My understanding is that the first release of `dune` to opam will be when 1.0.0 is released.

**Comment by bluddy** [comment]
I can confirm that forcing a dune package to be created when pinning will cause both `dune` and `jbuilder` to appear.

**Comment by diml** [comment]
#796 should help with this

**Comment by diml** [comment]
This should be fixed now
