### ISSUE TITLE
it would be nice if jbuilder would build on older ocaml versions

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/dune#823]
This is not a bug, and was probably already reported by other people, though I could not find it.
I think the current limit is ocaml >= 4.02.3.
This is pretty high an ocaml version number.
I would have liked that jbuilder can build on older versions too; because it also binds
software using jbuilder to not build on older versions.
For example, I think obuild and ocamlbuild both build from 3.12.1 and upward.
Maybe this can be a problem for some people in order to adopt jbuilder.

Then, maybe a feature request would be for jbuilder to be able to create a shell script, so that a given software has a last-resort way of being compiled when jbuilder is not available (the maintainer would ship
this jbuilder-generated script with the software archive).

**Comment by diml** [comment]
The problem with generating build scripts is that all the high-level logic has already been interpreted and you end with something that will only work in the same environment as the one it was generated in. It's exactly the same comparison between distributing source code and pre-compiled binaries.

Regarding the minimum OCaml version, have you tried building a project with an older OCaml versions with jbuilder? Jbuilder itself will not build with older OCaml versions, but it should be quite easy to make a jbuilder built with a modern OCaml to build projects using an older OCaml. The two versions don't need to match.

**Comment by UnixJunkie** [comment]
Thanks for the workaround. But the problem is that usually you build and install everything via opam with a given ocaml version. So, if jbuilder doesn't ship, your things also will not ship with that compiler version.
If jbuilder becomes packaged for most linux distro (opam is, so why not), this may lessen the problem since we would not need jbuilder to be installed by opam in the current switch but would use the system-wide jbuilder.

**Comment by diml** [comment]
That's true that it's a bit complicated for users. On the other hand it's already sometimes frustrating for us to not be able to use newer features of the language in Dune, so I'm not fond of the idea pushing down the lower bound.

I believe the general consensus is that support the version of OCaml in Debian stable is the right answer, and currently Debain stable has OCaml 4.02.3.

**Comment by avsm** [comment]
I don't believe pushing the lower bound below 4.02.3 will ever be practical.  Our opam CI only tests 4.02.3 and up, and with 4.07.0 around the corner we will likely have to deprecate some older versions soon.

Do you actually have an example of a user requesting 4.01.0 support and Jbuilder, with a valid reason not to upgrade their compiler version while also porting to Jbuilder?  This seems like a vanishingly small intersection of users :)

**Comment by samoht** [comment]
I know an old version of OCaml was once certified to be used in avionics, and people stick with that version for ever because of this. Not sure what's the status today :-) /cc @bobot who might know more (or maybe it was someone from Esterel who told me that)

**Comment by diml** [comment]
@samoht, yeah that's where I used to work :) It was OCaml 3.09. But Dune would have to be certified as well, so using Dune at all wouldn't be realistic.

**Comment by diml** [comment]
I'm labelling this issue with `wontfix` as we have no plan to officially support older versions of OCaml.

**Comment by rgrinberg** [comment]
We might as well close this then. I think this has been discussed a few times before already and I agree that this is just not practical. We use gadt's, open types, constructor disambiguation very liberally.
