### ISSUE TITLE
dune describe pp not expanding ppx

### ISSUE THREAD

**Issue by bluddy** [ocaml/dune#8373]
Running `dune describe pp` on a file in my [repo](https://github.com/bluddy/rails) (e.g. `dune describe pp src/rails_lib/backend/backend.ml` does not seem to expand any of the ppxs. 

The dune file at `src/rails_lib/dune` uses staged_pps.

**Comment by Alizter** [comment]
We don't support `staged_pps` with `dune describe pp`. The fact that it doesn't error is a bug probably to do with `include_subdirectories unqualified`. You will see that `dune describe pp` will reject `.ml` files in `rails_lib` (at the same level).

**Comment by rgrinberg** [comment]
There's actually a WIP PR for it already https://github.com/ocaml/dune/pull/7522

**Comment by ejgallego** [comment]
Duplicate of #6945
