### ISSUE TITLE
Change the name of a few variables

### ISSUE THREAD

**Issue by diml** [ocaml/dune#842]
The names and casing of variables are not very consistent. I propose to use lowercase for all variables such as `OCAML` and additionally do the following renaming:

- [x] `%{path:file}` --> `%{dep:file}`, I think this way it's clearer what it means
- [x] `%{path-no-dep:file}` --> `%{path:file}`
- [ ] `SCOPE_ROOT` --> `project_root`
- [x] remove `%{findlib:...}` which is redundant with `%{lib:...}`

#576 adds a `dir_kind` in the code that tells us whether the directory contains a `jbuild` or `dune` file. We can use that to use the new names only in `dune` files

**Comment by emillon** [comment]
We can also use the `~syntax` argument passed to the expansion functions (added in #887).

**Comment by diml** [comment]
Indeed, it's the same kind of change

**Comment by rgrinberg** [comment]
@emillon which parts of this PR are you tackling?

Btw, the listing of variables to be renamed is incomplete in this PR. Are you planning on tackling all the renames, or just those in this PR?

**Comment by emillon** [comment]
I have no precise plans yet, but I was thinking about the path vs deps ones. Maybe we can close this and add bugs for individual items? That'll be easier to track & coordinate.

**Comment by rgrinberg** [comment]
Up to you. I can handle the renames that aren't mentioned in this ticket for now.

**Comment by emillon** [comment]
OK, I'll take care of the ones mentioned in here then.

**Comment by diml** [comment]
This is done
