### ISSUE TITLE
Watcher

### ISSUE THREAD

**Issue by kennetpostigo** [ocaml/dune#847]
Hey, I've been using dune(jbuilder) for some time with [reasonml](https://github.com/facebook/reason) for native projects and find myself wishing dune had a built in watcher to track changes and rebuild when they occur. Is this something that folks working on dune might have considered adding to dune? Some prior art, bucklescript and it's native counter part bsb-native have a built in watcher that works really well, and could be a project to draw inspiration from for a watcher.

**Comment by yminsky** [comment]
I haven't really tried it out myself, but there is this:

http://opam.ocaml.org/packages/dune_watch/

**Comment by kennetpostigo** [comment]
Interesting! would it be a good idea to have it included in dune itself?

**Comment by diml** [comment]
I tried `dune_watch` and it works well. At some point we'll probably include a polling mode directly in Dune, because if we do it in the Dune process we can avoid redoing some of the work on every start.

**Comment by kennetpostigo** [comment]
diml Sounds awesome,  Look forward to it in the future!
