### ISSUE TITLE
Link-time dependencies

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#852]
Hi,

I'm linking a shared object and I want to use a version script when linking it. The following sort of works:

```
(link_flags (-ccopt "-Wl,--version-script version.map"))
```

But of course the linking step needs `version.map`, so this fails.

I think that dune is missing a way to add a custom dependency to the executable, or just to the link operation.

At the moment I'm using this as a workaround, but this is obviously not great:

```
(preprocessor_deps ((file version.map)))
```

Is there a way to do that at the moment or should an extra field be added?

Thanks!

**Comment by diml** [comment]
We need an extra field

**Comment by diml** [comment]
Seems good.

BTW, in the future, we could also allow this:

```
(link_flags (-ccopt "-Wl,--version-script %{dep:version.map}"))
```
