### ISSUE TITLE
DSL for filtering actions with blang

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#8556]
Writing down my thoughts on a new DSL for dune files that will allow filtering the arguments to actions and actions themselves based on filters expressed with the blang DSL.

This problem comes up when translating opam files to dune lockfiles. Opam has two types of filtering which it applies to commands:

### Filtering entire commands
```
build: [
  ["dune" "subst"] {dev}
]
```

Here the entire command `dune subst` is omitted unless the variable `dev` resolves to `true`.

### Filtering individual terms
```
build: [
  [
    "dune"
    "build"
    "-p"
    name
    "-j"
    jobs
    "@install"
    "@runtest" {with-test}
    "@doc" {with-doc}
  ]
]
```

Here the `@runtest` and `@doc` terms are only included in the command if the variables `with-test` and `with-doc` are `true` respectively.

Note that this filtering even applies to the first term so the program that gets run can be dynamically chosen. E.g.

 ```
[ "make" {os-family != "freebsd"} "gmake" {os-family = "freebsd"} "install" ]
```

Since supporting this behavior in dune will require adding some type of conditional construct it would be nice if it could also handle other types of conditional construct in opam:

### String Conversions

Inside a string in an opam file you can write:
```
"%{var?string-if-true:string-if-false-or-undefined}%"
```

So one string is chosen if the variable is true and the other is chosen if it's false or undefined. The else case is mandatory.

### Package Conjunctions

Boolean package variables may be combined using the following form: `name1+name2+name3:var` is the conjunction of var for each of `name1`, `name2` and `name3`, i.e it is equivalent to `name1:var & name2:var & name3:var`.

## In dune

The most complex opam expression I can think of to exercise all the features we'll need is:
```
build: [
  [ "foo-%{pkg1+pkg2+_:var1?aaa:bbb}%-bar" {var2 & var3 = "baz"} "qux" ] {var4 | var5}
]
```

Dune does currently have a feature for interpolating variables in strings (pforms like "%{os}") but I'm against extending it to handle opam variable expressions like the one in the example involving a string conversion and a package conjunction as dune's pform syntax is too limited to express such a complex term in a readable way.

Breaking down the string interpolation in the example, the condition `pkg1+pkg2+_:var1` could be expressed today with a dune blang:
```
(and %{pkg:var1:pkg1} %{pkg:var1:pkg2} %{pkg-self:var1})
```
Following dune's convention of copying scheme's syntax, the choice between the strings "aaa" and "bbb" could be expressed as:
```
(if (and %{pkg:var1:pkg1} %{pkg:var1:pkg2} %{pkg-self:var1}) aaa bbb)
```

Now we need to add the rest of the string interpolation (the "foo-" prefix and "-bar" suffix). The simplest way I can think of expressing this is with string concatenation:

```
(concat "foo-" (if (and %{pkg:var1:pkg1} %{pkg:var1:pkg2} %{pkg-self:var1}) aaa bbb) "-bar")
```

That entire term is optional based on the `{var2 & var3}` filter. I propose introducing a `when` operator to this language for excluding terms based on a predicate.

```scheme
(when
  (and var1 (= %{var2} "baz"))
  (concat "foo-" (if (and %{pkg:var1:pkg1} %{pkg:var1:pkg2} %{pkg-self:var1}) aaa bbb) "-bar"))
```

The entire action would corresponding to this command would look like:
```scheme
(run
  (when
    (and var1 (= %{var2} "baz"))
    (concat "foo-" (if (and %{pkg:var1:pkg1} %{pkg:var1:pkg2} %{pkg-self:var1}) aaa bbb) "-bar"))
  qux)
```

That entire command is optional based on the filter `{var4 | var5}`. I recently added a new action type to dune (also called `when`) which acts like a no-op unless a given blang resolves to `true`:

```scheme
(when
  (or %{var4} %{var5})
  (run
    (when
      (and var1 (= var2 "baz"))
      (concat "foo-" (if (and %{pkg:var1:pkg1} %{pkg:var1:pkg2} %{pkg-self:var1}) aaa bbb) "-bar"))
    qux))
```

I want to open this up for discussion before going further. There are some things about this design that I don't really like and I'd be keen to hear suggestions for alternatives. In particular the fact that we have an action `when` and also a construct in this proposed DSL called `when` which do very similar things despite technically being in different DSLs. Could lead to confusion. I thought about using `if` for the latter and making the `else` branch optional. That might be more familiar to people coming from other languages but I also worry that it complicates the semantics of `if`.

I'm also not sure about how `concat` and `when` should interact. For example what would `(concat "foo" (when false "bar"))` resolve to? Would it just be `"foo"` or would it be an error? If it's an error should we add a type system to catch this sort of thing before resolving its condition or make it a runtime error which only happens if the condition is false?

PS. While we're at it there's another feature of opam that's tangentially related that I haven't tried to tackle yet, but it might fit into this DSL. Opam has a unary `?` operator which takes an expression and returns true iff it doesn't depend on undefined variables. The easiest way to implement this in dune would be adding undefined values to blang along with an operator to check if a value is undefined. Since the `"%{var?string-if-true:string-if-false-or-undefined}%"` syntax resolves to the else case if the variable is undefined we should keep this in mind when designing the `if` operator.

**Comment by rgrinberg** [comment]
> There are some things about this design that I don't really like and I'd be keen to hear suggestions for alternatives. In particular the fact that we have an action when and also a construct in this proposed DSL called when which do very similar things despite technically being in different DSLs. Could lead to confusion

I don't see it that way. `when` isn't really an action, but a part of our DSL to construct an action. For comparison, do you consider `no-infer` to be an action as well? To me, those are analogous.

> I'm also not sure about how concat and when should interact. For example what would (concat "foo" (when false "bar")) resolve to?

I think the issue here is that we'd this to be `(concat "foo" (if false "bar" ""))` but without having to write the else clause explicitly. We could inherit the following lisp `(when false ..) = ()` and allow `concat` to take lists or string as arguments.

> While we're at it there's another feature of opam that's tangentially related that I haven't tried to tackle yet, but it might fit into this DSL. Opam has a unary ? operator which takes an expression and returns true iff it doesn't depend on undefined variables. The easiest way to implement this in dune would be adding undefined values to blang along with an operator to check if a value is undefined. Since the "%{var?string-if-true:string-if-false-or-undefined}%" syntax resolves to the else case if the variable is undefined we should keep this in mind when designing the if operator.

Would it help to add a `defined?` predicate? E.g. `(if (defined? "foo") x y)`?

**Comment by Leonidas-from-XIV** [comment]
I would agree with @rgrinberg that `when` and `when` is not really a conflict. The only case where this matters to the user is when the language either understands is meaningfully different to cause frustration.

>  If it's an error should we add a type system to catch this sort of thing before resolving its condition or make it a runtime error which only happens if the condition is false?

Is that even possible? If the condition is computed at runtime (e.g. from `%{os}`) then this would be impossible to determine unless we resolve it. Otherwise we'd have to ban `when` in `concat` (or other constructs where "no value" might happen).

OTOH I think `concat` interpreting a part that evaluated to no value as `""` is entirely fine. That's what e.g. bash does by default, however we might consider printing a warning (like `set -e`) in that case.

**Comment by gridbugs** [comment]
As an exercise to make my ideas more concrete and to test how intuitive they are I'm going to write some fictional documentation for the new DSL.

An **action** is expressed with the syntax `(<action> <arg1> <arg2> ...)`.

The **concat** operator takes a variable number of strings as arguments and returns their concatenation. For example `(concat Hello ", " World "!")` is equivalent to `"Hello, World!"`.

The **if** operator takes a boolean condition and two values and resolves to the first value if the boolean is true and the second value if the boolean is false.

The **pkg-var-defined** operator takes a single argument and returns a boolean which is true if and only if evaluating its argument did not result in expanding an undefined package variable. (Side note: I think we can use this mechanism to remove the need to explicitly introduce undefined values into the dune language.)

The **when** operator takes a boolean condition and a value and takes on the value if the boolean resolves to true. If the condition resolves to false then the when-statement takes on the special value **nil**.

The **nil** value cannot be written in dune syntax but is the result on a when-statement whose condition is false. When nil appears in an argument list (to an action or operator) then it is ignored. That is `(run foo (when false bar) baz)` is equivalent to `(run foo baz)` and `(concat foo (when false bar) baz)` is equivalent to `foobaz`.

Note that when-statements can also appear outside of actions. For example `(progn (when true (echo foo)) (when false (echo bar)) (echo baz))` is equivalent to `(progn (echo foo) (echo baz))`.

**Comment by rgrinberg** [comment]
> The nil value cannot be written in dune syntax but is the result on a when-statement whose condition is false. When nil appears in an argument list (to an action or operator) then it is ignored. That is (run foo (when false bar) baz) is equivalent to (run foo baz) and (concat foo (when false bar) baz) is equivalent to foobaz.

One fact that we can inherit from lisp is that `nil` equivalent to the empty list. So we could understand this behavior as: `(run foo (concat (when false bar) baz))` if `val run : string -> string list -> action`. Unfortunately, `run` takes a variable number of arguments. However, we already have this auto expansion of lists with pforms - e.g. `(run foo %{deps})` will expand `deps` into multiple arguments. So it's fine to have it here as well I suppose.

**Comment by gridbugs** [comment]
I'm aware that `nil` is the empty list in lisp but do we really want that behaviour in dune? I'd prefer to keep it as a separate concept to make dune easier for people who have never used lisp. This new DSL doesn't allow users to create lists directly and I don't see much value in adding lists (empty or otherwise) and automatically concatenating them into argument lists to operations to this DSL.

**Comment by gridbugs** [comment]
Oh actually variables that expand to multiple strings complicates my plan a little. I need to think more about how `(run foo %{deps})` will fit into my design.

**Comment by gridbugs** [comment]
Ah yes after some thought I agree with you about representing `nil` with the empty list. This is consistent with how dune treats pforms that expand to lists in that they are flattened into the argument list for whatever they are being passed to.

**Comment by gridbugs** [comment]
I've made a PR with a first pass at this feature: https://github.com/ocaml/dune/pull/8596
