### ISSUE TITLE
env-vars behaviour

### ISSUE THREAD

**Issue by progman1** [ocaml/dune#8585]
for 
```
(env
 (_ (env-vars (X 1)))
```
in a dune file housing a library stanza
1. the final library build command  has the env-var set
2. the component module file compilation commands do not have env-vars set

in a dune file housing an executable stanza
1. for final link the env-vars are set
2. the component module compilation commands do not have env-vars set
3. any libraries in sub-directories have the env-vars set for library linking only

is this a bug or a feature? to me it is completely counter-intuitive and contrary to the documentation.

**Comment by emillon** [comment]
I could see one of 2 things happening:
- `(env)` is scoped by directory, so if a stanza sets up a rule in a different directory, the rule might not inherit from this
- some rules are sandboxed and run with a cleared environment. If dune does not know that a step will attempt to read a particular environment variable, it will not be available in the sandboxed environment.

If you can provide an example, we can try to see what's happening.

> to me it is completely counter-intuitive and contrary to the documentation

can you share what part of the documentation you're referring to?

**Comment by progman1** [comment]
"(env-vars (<var1> <val1>) .. (<varN> <valN>)) will add the corresponding variables to the environment where the build commands are executed and are used by dune exec."

that seems clear enough except the qualification 'dune exec' which confuses matters: why not 'dune build ...'?

I don't follow you - what is 'sets up a rule in a different directory,'  what's wrong with the simple interpretation of being per-directory or per-directory and sub-directories as it is stated?

why would dune not assume that the envar would be accessed if the (env ...) declares
it?  why should the link mode invocations of the compiler be given these envars but the build mode invocations not?  with this behaviour I cannot understand what this was intended for! 
surely it was meant that any static tools used or rule generated binaries  run could access these envars. the compiler itself is one such static tool and the one whose behaviour I am trying to control.

**Comment by emillon** [comment]
> the compiler itself is one such static tool and the one whose behaviour I am trying to control.

what environment variable are you setting?

**Comment by progman1** [comment]
one I've inserted into the compiler to control backend emission, regular or embedded assembler. it's a way of modding any existing project  simply, to choose parts for JIT assembly into a whole.

**Comment by rgrinberg** [comment]
What is the version of the dune language in your `dune-project` file?

**Comment by progman1** [comment]
```
(lang dune 3.0)
```

**Comment by rgrinberg** [comment]
Try setting it to `(lang dune 3.7)`.

**Comment by progman1** [comment]
perfect. thanks.
