### ISSUE TITLE
Opam Compatibility: Better Error Messages for features that we don't support

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#8683]
Dune doesn't (can't) support the following the features:

* The `%{root}%` variable.
* The `misc` install section.

Currently, we just pretend these things don't exist. Instead, we should:

1. Error if we try to generate a lock directory with this variable
2. Reject building packages that use this `misc` section.

**Comment by Alizter** [comment]
Shall we add `build-doc` and `build-test` to the list?

**Comment by rgrinberg** [comment]
If somebody is using dune for their project, I don't think they would use `build-test`. For `build-doc`, we don't have a system for generating docs for the installed packages yet anyway. Eventually we might though.

**Comment by rjbou** [comment]
`build-test` and `build-doc` are [deprecated] (https://opam.ocaml.org/doc/Manual.html#opamfield-build-doc).

**Comment by Alizter** [comment]
@rjbou Yes, but there are some older packages that use those fields in the opam repo. We are currently not planning to support them in the pkg workflow however mentioning them here might be useful for good error messages.

**Comment by Alizter** [comment]
We now have nice error messages for our unsupported features.

https://github.com/ocaml/dune/blob/main/test/blackbox-tests/test-cases/pkg/opam-var/opam-var-unsupported.t
