### ISSUE TITLE
User interruptions to solver

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#8718]
Out of curiosity I ran `./dune.exe pkg lock` in the dune repo and it takes quite some time. It would also not respond to `Ctrl+C` until the solver step had finished.

1. I think that it would be good to have more user feedback during the solver step, so that the user won't think dune has frozen.
2. We should respond to interrupts in the middle of the solver step.

**Comment by Alizter** [comment]
Actually, after #8826 I see that the actual solver step is not taking that long. What really is the bottleneck is the download.

**Comment by Alizter** [comment]
The download times have improved a lot with the work on the rev_store. As of now, the initial fetch of the opam repos takes the longest, but that can easily be interrupted by the user. Subsequent fetches are quick enough that it's actually difficult to interrupt them quickly enough. :+1: 

The actual solve step that follow however cannot be interrupted, so this issue is really about that. I know that Fiber was threaded into the solver, but I'm not sure why the scheduler won't listen to the interrupt signals given.

**Comment by emillon** [comment]
This seems to have been fixed by #10438.
