### ISSUE TITLE
Solver variables in package lockfiles

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#8730]
Some opam variables are both used to determine a package's dependencies during solving and also used to determine which commands to run while building and installing the package. To make sure both the solving step and building/installing step see the same variables the solver variables used to generate a lockdir should also be used during the build/installation. I think it would be appropriate to store the value of solver valiables in the `lock.dune` file and then read them from that file to make the variables available during build/installation.

**Comment by rgrinberg** [comment]
This only applies to a subset of variables. Otherwise how would it work for `%{os_family}` for example?

Could you list the variables you intend for this to work?

**Comment by gridbugs** [comment]
I had the flags defined in `Solver_env.Variable.Flag` (`with-test` and `with-doc`) in mind when I wrote this but you raise an interesting point about `os-family` and other system variables. If a lockfile is generated with `os = linux` for example, what should the behaviour be when a build is attempted on a system where `os = macos`?

**Comment by gridbugs** [comment]
Thinking about this more and we only want `with-test` and `with-doc` to be set for packages which are defined in the current project. So I think they should be set in individual package lockfiles rather than `lock.dune` as they'll have different values for different packages.

**Comment by gridbugs** [comment]
But for system variables like `os-family` we might want to record the variables that were set when the solve was done so on systems that are incompatible with those variables we can detect it and possibly print a warning or something. For system variables it makes sense to record them in `lock.dune` as they'll be the same for all packages.

**Comment by rgrinberg** [comment]
>  If a lockfile is generated with os = linux for example, what should the behaviour be when a build is attempted on a system where os = macos?

I would imagine the build instructions to be evaluated with `os = macos` and the build having a reasonable chance of succeeding. Especially if `%{os}` isn't used anywhere.

> Thinking about this more and we only want with-test and with-doc to be set for packages which are defined in the current project

Yeah, that seems like a reasonable first approximation. However, the following somewhat niche use cases also exist:
1. Building docs for dependencies
2. Verifying that the dependencies are working by running their test

> But for system variables like os-family we might want to record the variables that were set when the solve was done so on systems that are incompatible with those variables we can detect it and possibly print a warning or something. For system variables it makes sense to record them in lock.dune as they'll be the same for all packages.

I think that makes sense

**Comment by gridbugs** [comment]
@rgrinberg and I discussed this and the plan is to abstract the `with-test` and `with-doc` variables away from users so we won't store these in lockfiles. I'll just add the system variables for now.

**Comment by rgrinberg** [comment]
As discussed on slack, our algorithm for including the test dependencies is tentatively:

1. Solve with `{with-test}` to get a package set `A`
2. Solve without `{with-test}` using the versions of `A` as “user constraints” to get set a `B`
3. `A \ B` is going to be the set of packages that will be marked as “test only” in the lock dir

This requires running the solver twice, but it should work fairly well.

**Comment by gridbugs** [comment]
@rgrinberg what do you think of this alternative:

At solve time, run the solver once with `{with-test}`. For each package in the solution determine which of its dependencies are test-only by evaluating its dependency formula once with `{with-test}` and once without (the difference will be test-only deps). Annotate the list of dependencies stored for each package with whether it is a test-only dependency. Then when instantiating the lockdir the test-only dependency annotations can be used to quickly build a set of dependencies that are non-test if necessary. This step could also be done at solve-time as an optimization though I doubt that will be necessary.

The benefit of doing it this way is the solver only needs to be run a single time. Can you think of any drawbacks?

**Comment by rgrinberg** [comment]
I think that should work.

> For each package in the solution determine which of its dependencies are test-only by evaluating its dependency formula once with {with-test} and once without (the difference will be test-only deps). Annotate the list of dependencies stored for each package with whether it is a test-only dependency

This step needs to be clarified. My understanding of it is as follows:

1. Given a package `x`, evaluate it's dependencies without `with-test` to get some set of deps `A`.
2. Take the transitive closure of `A` and mark all the packages found in this closure.
3. Do step 1. for every single "local" package.
4. Any packages that remain unmarked by step 2. are now considered test deps.

Is this what you had in mind?

**Comment by gridbugs** [comment]
Not exactly.

1. Run the solver with `{with-test}` to identify all the packages that form the solution
2. For each package identified by 1, evaluate its dependency formula twice: once with `{with-test}` and once without. The delta will be that packages _immediate_ test-only dependencies. Record which of the package's immediate dependencies are test-only.
3. The set of packages along with their lists of immediate dependencies forms a DAG where some edges are test-only. Traverse the DAG starting with the set of "local" packages, only following the non-test edges. The packages that aren't visited by this traversal are the test-only deps.

Also step 3 can be deferred to when the lockdir is instantiated as it's fast and doesn't rely on any external information.

**Comment by rgrinberg** [comment]
Okay, so the difference from how I understood it, and how you understood it is as follows:

1. I want to keep a single bit per package to determine if it's "test only"
2. You want to keep a single bit per dependency to determine if it's "test only"

I think my approach has less redundant information, but yours can be used to answer the question "why is this dependency included in the build plan?" (b/c it's a test dep of `x`).

I prefer mine because it's not obvious to me that we care about this info. But both solutions are acceptable to me.

**Comment by gridbugs** [comment]
How do you think we should deal with packages which depend on different versions of a package conditionally on `{with-test}`? For example if `a` depends on `b` and also has a test-only dependency on `c`, and `c` depends on `b.0.5` and the latest version of `b` is `0.6`. The solver will pick `b.0.5` when solving with `{with-test}` and `b.0.6` without `{with-test}`. In that case there is a solution that works for both (picking `b.0.5`) but it's technically possible for a package to have no general solution that works both with and without `{with-test}` (though this is probably rare in practice). I think our options are to detect this case and make it an error or to allow a solution to contain multiple versions of the same package.

**Comment by rgrinberg** [comment]
I think that such a situation having no solution is a sensible result or an older version of a dependency being picked is quite sensible. 

>  I think our options are to detect this case and make it an error or to allow a solution to contain multiple versions of the same package.

I don't think it's necessary. Mostly because this is leading to a situation where the build plan for testing and for "release" builds are different. I don't recommend having such a situation, but if it's needed, it's fine for the user to manually create it with our existing mechanisms.
