### ISSUE TITLE
`dune -prefix` should warn that is not `dune --prefix`

### ISSUE THREAD

**Issue by Matafou** [ocaml/dune#8790]
## Current behavior

I got bitten by a silly CLI syntax error when typing  `dune install -prefix <path>` instead of `dune install --prefix <path>`. This triggered no warning or error and was interpreted as `-p -r -e -f -i -x` as pointed by @ejgallego.

## Desired Behavior

This is of course not a bug but maybe we could have a warning when a chain of short options (e.g. `-xy` being read as `-x -y`) matches exactly a long option name?

**Comment by emillon** [comment]
This behavior is due to the CLI argument library we use. You can try to open a feature request over there: https://github.com/dbuenzli/cmdliner/
Thanks
