### ISSUE TITLE
windows: dune rpc status not working

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#8799]
## Expected Behavior

`dune rpc status` should work correctly on windows.

## Actual Behavior

`duen rpc status` reports that there is no running RPC server. This is not true as ocamllsp is able to connect to it just fine.

## Reproduction

1. On Windows with dkml ocaml, start dune in watch mode in a project.
2. From another terminal do `dune rpc status`
3. Dune will complain nothing is running.

## Specifications

- Version of `dune` (output of `dune --version`): 3.10.0
- Version of `ocaml` (output of `ocamlc --version`): 4.14.0
- Operating system (distribution and version): Windows 11

**Comment by nojb** [comment]
I can reproduce with 3.8.3, I guess that it is the same for `main`. I will try to investigate more later.

As a data point, `ocaml-lsp` can connect to the Dune running in watch mode in spite of this.

**Comment by nojb** [comment]
@rgrinberg is the RPC server separate from the watch mode server, or is it the same thing?

**Comment by Alizter** [comment]
@nojb Same thing.

**Comment by nojb** [comment]
> @nojb Same thing.

OK, thanks.

**Comment by Alizter** [comment]
> As a data point, `ocaml-lsp` can connect to the Dune running in watch mode in spite of this.

I was not able to reproduce this. What version of ocaml-lsp do you have? I'm using 1.12.2.

**Comment by nojb** [comment]
> > As a data point, `ocaml-lsp` can connect to the Dune running in watch mode in spite of this.
> 
> I was not able to reproduce this. What version of ocaml-lsp do you have? I'm using 1.12.2.

I think your version is too old. I am using 1.16.1 (which includes some Windows fixes for precisely this if memory serves).

**Comment by Alizter** [comment]
Yes, I can confirm after upgrading lsp it is correctly connecting. Therefore it appears that this is an issue with `dune rpc status` on Windows.
