### ISSUE TITLE
ld: warning: directory not found for option '-L/opt/local/lib'

### ISSUE THREAD

**Issue by loxs** [ocaml/dune#883]
I get this warning when compiling my software:

    ld: warning: directory not found for option '-L/opt/local/lib'

I'm on Mac OS and dune is installed via OPAM and is `jbuilder   version: 1.0+beta20`

Of course, I don't have this directory, but I'm not sure I need to.

**Comment by diml** [comment]
Dune doesn't pass this directory, it must come from somewhere else. You can look at the output of `ocamlc -config` to see if it's the compiler itself

**Comment by jberdine** [comment]
Perhaps due to zarith, see https://github.com/ocaml/opam-repository/issues/3000.

**Comment by loxs** [comment]
Thanks probably Zarith then...  I'll close the issue
