### ISSUE TITLE
Opam Repository Storage

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#8843]
## Problem

Dune will now manage opam repositories on a per project basis. This will require juggling a bunch of opam repositories. To do this effectively, we need to manage these two problems:

1. Opam repositories can be quite large and we'd like to make sure we deduplicate what we store.
2. We'd like to access opam repositories concurrently from multiple running instances of dune.

## Solution

1. store opam repositories in a single git repositories.
2. new repositories are added as remotes and fetched whenever the user asks for an update
3. when running the solver, we read the data from the git repository at the correct commit hash.

The last step requires a bit of clarification. We have two approaches. The simple and slow approach is to use `git archive` to materialize the opam state for solving. The complicated and fast approach is to read directly from the object files.

**Comment by Alizter** [comment]
Will this mean `git` will be necessary for dune to function here?

**Comment by rgrinberg** [comment]
Yes

**Comment by nojb** [comment]
> 3\. when running the solver, we read the data from the git repository at the correct commit hash.

For my own understanding: when running the solver, do you need access to the whole repository, or just the subset consisting in the dependency closure of the packages that you are solving for? (I would imagine the latter.) In general, this would be considerably smaller than the whole repository, right?

**Comment by rgrinberg** [comment]
Yes, that's exactly it. We usually need a small subset of the repository. This means that reading package metadata without checking the whole repo will be a substantial optimization.

**Comment by rgrinberg** [comment]
Now complete. There are still some problems, but we've created separate issues for them.
