### ISSUE TITLE
Inline_tests with empty partition 

### ISSUE THREAD

**Issue by hhugo** [ocaml/dune#8848]
When no inline test is declared (aka empty partition list) in a library using (inline_tests), dune complains with
```
- Error: Rule dependencies are configured to require sandboxing, but the rule
- has no actions that could potentially require sandboxing.
```

**Comment by Alizter** [comment]
@rgrinberg This is a common issue with sandboxing and has appeared before. Would it be sensible to stop any sandboxing if there are no actions that require it rather than throwing this somewhat cryptic error? Perhaps something like "maybe_sandbox".

**Comment by rgrinberg** [comment]
Yeah, that was discussed before and agreed that it would be the better behavior. Nobody wrote an official proposal though.

**Comment by Alizter** [comment]
@rgrinberg I created an RFC: https://github.com/ocaml/dune/issues/8854
