### ISSUE TITLE
ocaml expects `%{prefix}` to be absolute

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#8861]
As evidenced by the following error:
```
$ dune build
...
configure: error: expected an absolute directory name for --prefix: ../target
-> required by _build/_private/default/.pkg/ocaml-variants/target/cookie
-> required by - package ocaml-config
-> required by - package ocaml
```

Generating an absolute directory name is actually quite problematic because it would completely break the dune cache without #7502

**Comment by Alizter** [comment]
Does `BUILD_PATH_PREFIX_MAP` work here?

**Comment by rgrinberg** [comment]
Nope, because the issue is with the configure script. It just refuses all relative paths.

**Comment by nojb** [comment]
The OCaml compiler is not (yet) relocatable (it hardcodes a number of absolute paths inside its executables). Isn't this the root issue?

**Comment by rgrinberg** [comment]
It should still allow us to build it.

Right now, it's not even letting us go through `./configure`.
