### ISSUE TITLE
pkg: OCaml configure selects i386-apple-darwin as host system type

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#8867]
OCaml misconfigures itself as i386-apple-darwin host on multiple platforms past the prefix issue in #8862. I've tried both on linux and macos. The target system is configured correctly, something is wrong with the host detection.

I tried Windows as well but ran into a different issue there #8866.

#### linux
```
   configure default/.pkg/ocaml-variants/target [_private] (exit 77)
configure: creating cache config.cache
configure: Configuring OCaml version 5.2.0+dev0-2023-04-11
checking build system type... x86_64-pc-linux-gnu
checking host system type... i386-apple-darwin13.2.0
checking target system type... i386-apple-darwin13.2.0
checking for i386-apple-darwin13.2.0-ld... ld
checking how to print strings... printf
checking for i386-apple-darwin13.2.0-gcc... gcc -Wl,-read_only_relocs,suppress -arch i386 -m32
checking whether the C compiler works... no
configure: error: in `/home/ali/HoTT/_build/_private/default/.pkg/ocaml-variants/source':
configure: error: C compiler cannot create executables
See `config.log' for more details
-> required by _build/_private/default/.pkg/ocaml-variants/target/cookie
-> required by - package ocaml-config
-> required by - package ocaml
-> required by - package dune
-> required by - package coq
```

#### macos (virtualbox)
![image](https://github.com/ocaml/dune/assets/8614547/f1999982-22fd-4712-b5a7-0f8cb24878f8)

**Comment by Alizter** [comment]
This is a bug in OCaml trunk, nothing to do with us.

**Comment by Alizter** [comment]
Some more data points. Purposefully scrubbing `gcc` from `PATH` leads to a different error. So there must be something else we are triggering.
```
[ali@allosaurus:~/ocaml]$ PATH=$(echo $PATH | tr ':' '\n' | grep -v "$(dirname $(which gcc))" | tr '\n' ':' | sed 's/:$//') ./configure
configure: Configuring OCaml version 5.2.0+dev0-2023-04-11
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for ld... no
checking for link... link
checking how to print strings... printf
checking for gcc... no
checking for cc... no
checking for cl.exe... no
checking for clang... no
configure: error: in `/home/ali/ocaml':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
```

**Comment by rgrinberg** [comment]
Doesn't seem like a dune issue. If it is, please create a test case or explain the problem more clearly.

**Comment by Alizter** [comment]
It's not possible to test until we make progress on the configure script for OCaml, before I was using the hack for allowing absolute paths and running into this issue.

Concretely CC was being missed by the OCaml configure, but I have no idea if this will work again now, until we can run it. Keeping it closed for now is fine I suppose.
