### ISSUE TITLE
Running `make dev-deps` depends on OCaml 4

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#8891]
The development dependency `ppx_expect.v0.15.0` is incompatible with OCaml 5.

## Expected Behavior

Running `make dev-deps` should install dev dependencies when OCaml 5 is installed.

## Actual Behavior

Running `make dev-deps` with OCaml 5 installed will downgrade the compiler to version 4.something:
```
downgrade ocaml                       5.1.0 to 4.13.0
```

Alternatively if the switch invariant requires OCaml 5, the package `ppx_expect.v0.15.0` will fail to install, as it depends on OCaml < 5.

## Reproduction

1. Make an opam switch with OCaml 5
1. Run `make dev-deps` from the dune repo

**Comment by rgrinberg** [comment]
Is this still relevant? We now require ppx_expect >= 0.16.0.

**Comment by gridbugs** [comment]
I tried to test test if this is fixed but I ran into a different issue and can't seem to initialize a switch.

```
$ opam switch create . -y
...
[ERROR] The compilation of ocplib-endian.1.2 failed at "dune build -p ocplib-endian -j 31 @install".
...
#=== ERROR while compiling ocplib-endian.1.2 ==================================#
# context     2.1.5 | linux/x86_64 | ocaml.5.1.0 | https://opam.ocaml.org#0ac3fc79
# path        ~/src/dune/_opam/.opam-switch/build/ocplib-endian.1.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ocplib-endian -j 31 @install
# exit-code   1
# env-file    ~/.opam/log/ocplib-endian-5324-d227dc.env
# output-file ~/.opam/log/ocplib-endian-5324-d227dc.out
### output ###
# File "src/dune", line 75, characters 26-34:
# 75 |  (libraries ocplib_endian bigarray bytes))
#                                ^^^^^^^^
# Error: Library "bigarray" not found.
# -> required by library "ocplib-endian.bigstring" in _build/default/src
# -> required by _build/default/META.ocplib-endian
# -> required by _build/install/default/lib/ocplib-endian/META
# -> required by _build/default/ocplib-endian.install
# -> required by alias install
```

Still trying to work out the problem. I can't reproduce it in other projects besides dune. The `biigarray` library is part of the standard library.

**Comment by gridbugs** [comment]
Ok confirming that running `make dev-deps` no longer downgrades the compiler to 4.14.1.
