### ISSUE TITLE
Run inline tests in different modes

### ISSUE THREAD

**Issue by let-def** [ocaml/dune#894]
It would be nice to have the possibility to run inline tests both in native and bytecode, especially for testing bindings.

Also I think that in the current version, even if the stanza has an entry `(modes (byte))`, the tests are run with native backend.

**Comment by rgrinberg** [comment]
> It would be nice to have the possibility to run inline tests both in native and bytecode, especially for testing bindings.

@diml should inline_tests inherit the `modes` of the library they're derived from?

Btw, I think this is a good argument for a `(modes)` in the env. Then, Fred would be able to solve his issue by defining a context where `(modes byte)` is the default.

**Comment by diml** [comment]
> @diml should inline_tests inherit the modes of the library they're derived from?

If a library has `(modes byte)`, then it seems good to only run the tests in byte-code. However, it feels a bit overkill to systematically run the tests in both native and byte code. I suggest to add a way to select in what modes the tests should be run, for instance:

```ocaml
(library
 ...
 (inline_tests (modes ...))
```

and by default, `modes` will be `native` if enabled in the `modes` field of the library and `bytes` otherwise.

> Btw, I think this is a good argument for a (modes) in the env (#1073). Then, Fred would be able to solve his issue by defining a context where (modes byte) is the default.

Would you have to run a separate `dune` command to run the tests in byte-code? That feels a bit heavy, we should be able to test both modes at once.

**Comment by rgrinberg** [comment]
> If a library has (modes byte), then it seems good to only run the tests in byte-code. However, it feels a bit overkill to systematically run the tests in both native and byte code

Hmm, I thought this would still only run the tests once. When we set `(modes)` on an executable, only one of them gets the `.exe` extension.

> Would you have to run a separate dune command to run the tests in byte-code? That feels a bit heavy, 

I don't think so. But you would need to pass a workspace file where 2 contexts are defined with different `(modes)` as the default.

> we should be able to test both modes at once.

Sure, but I don't really see a way of making this work for tests defined using aliases for example. We could however make it work for the `tests` stanza.

**Comment by diml** [comment]
> I don't think so. But you would need to pass a workspace file where 2 contexts are defined with different (modes) as the default.

I would prefer if using custom workspace file is not necessary most of the time. It adds one level of complexity for users, and a simple notion like this one this should be directly expressible with plain dune files.

> Sure, but I don't really see a way of making this work for tests defined using aliases for example. We could however make it work for the tests stanza.

It would indeed only work for inline tests and for the test stanza. For custom tests, it's up to the user to write two stanzas.

**Comment by rgrinberg** [comment]
Sounds fine. Though I think that currently `tests` already accepts a `modes` field (with the same meaning as for executables). Should we create a new field name?

**Comment by diml** [comment]
For the `test` stanza, it seems fine to use the `modes` field for both purposes: choosing in what mode to compile and execute. It doesn't seem useful to build a test in a given mode but not execute it.

**Comment by atagunov** [comment]
Hi, documentation [adverstises](https://dune.readthedocs.io/en/latest/tests.html#running-tests-in-bytecode-or-javascript) `(inline_tests (modes byte best js))` yet `dune build` on version `1.10.0` yields
```
3 |  (inline_tests (modes native))
```
when `lib/dune` reads
```
(library
 (name lib)
 (inline_tests (modes byte))
 (preprocess (pps ppx_inline_test)) )
```

I imagine one or the other needs to be fixed?

**Comment by diml** [comment]
The `latest` version of the documentation is for the master of github.com/ocaml/dune. For the stable version, you need to consule the `stable` documentation. You can select it via the selector in the botton left corner of the page on readthedocs, or you replacing `latest` by `stable` in the URL.

**Comment by diml** [comment]
BTW, I believe that this feature is now supported in master, so I'm closing this ticket.

**Comment by atagunov** [comment]
Great, makes sense

I guess it might be helpful if https://dune.readthedocs.io redirected to
https://dune.readthedocs.io/en/stable rather than latest since this what
most people would expect?

Thx,
Anton

**Comment by diml** [comment]
That seems good yes as users often get confused by this. I don't know how to do this change though.

**Comment by diml** [comment]
@rgrinberg do you know how to change that?

**Comment by rgrinberg** [comment]
Done.

**Comment by rgrinberg** [comment]
This has the slight disadvantage that fixes to the docs will not be immediately available unfortunately.

I still think it would be useful for users to know in which version a particular feature was introduced. This would automatically solve this problem as well.

**Comment by atagunov** [comment]
> Done.

Nice :) BTW when I click any of

"v: stable" in green
down arrow in white

seen at bottom left of https://dune.readthedocs.io/en/stable/
I do not get a version toggle

Instead I see a PDF/HTML/ePUB/search panel. I'm on Google Chrome 73.0.3683.86 behind a corporate firewall, not sure if there is any special in this corporate issue of Chrome build

**Comment by diml** [comment]
@rgrinberg agreed. IIRC, we discussed this quickly in the past and agreed to add this info to the manual as long as it was available consistently. Though, we can probably start doing that now for new features.
