### ISSUE TITLE
[macOS] `dune` 3.11.1 errors (build itself works now, but building dependents fails)

### ISSUE THREAD

**Issue by barracuda156** [ocaml/dune#8941]
```
--->  Building ocaml-dune
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-dune/ocaml-dune/work/dune-3.11.1" && /usr/bin/make -j6 -w release 
make: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-dune/ocaml-dune/work/dune-3.11.1'
ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot unix.cma boot/libs.ml boot/duneboot.ml
./.duneboot.exe
cd _boot && /opt/local/bin/ocamlc -c -g -I +threads copyfile_stubs.c
otherlibs/stdune/src/copyfile_stubs.c: In function 'stdune_copyfile':
otherlibs/stdune/src/copyfile_stubs.c:45:39: error: 'COPYFILE_CLONE' undeclared (first use in this function); did you mean 'COPYFILE_MOVE'?
otherlibs/stdune/src/copyfile_stubs.c:45:39: note: each undeclared identifier is reported only once for each function it appears in
make: *** [_boot/dune.exe] Error 2
make: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-dune/ocaml-dune/work/dune-3.11.1'
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-dune/ocaml-dune/work/dune-3.11.1" && /usr/bin/make -j6 -w release 
Exit code: 2
```

How could we fix this?

**Comment by Alizter** [comment]
What macos version are you using?

**Comment by barracuda156** [comment]
@Alizter This is on 10.6, so pretty old, but it is the last one to run on PowerPC.

I only get this error with `dune` now though. Multiple OCaml packages build fine.

**Comment by Alizter** [comment]
@barracuda156 We recently switched to using clone file on macos:
- https://github.com/ocaml/dune/pull/7210.

The issue in this case is that the stubs don't compile in the case that copyfile is unavailable. @rgrinberg are there any work arounds to this?

According to the man pages, this API was introduced in 10.5. https://www.unix.com/man-page/mojave/3/copyfile/ So theoretically this should be available. Are we not passing the right link flags I wonder?

**Comment by Alizter** [comment]
It seems that `COPYFILE_CLONE` is missing on some older version which is unfortunate. LLVM on macports has this patch for example:

https://github.com/macports/macports-ports/blob/master/lang/llvm-12/files/0009-lib-Support-Unix-Path.inc-define-COPYFILE_CLONE-if-n.patch

we could do something similar:

```
#ifndef COPYFILE_CLONE
#define COPYFILE_CLONE		(1<<24)
#endif
```

**Comment by barracuda156** [comment]
@Alizter That would be very helpful if you could add an appropriate fallback from your side. We can do testing then.

10.4 is not really a concern, IMO, but having 10.5–10.6 working on PPC would be great. (I think 10.6 may be still used on some older Intel too.)
P. S. My primary interest in OCaml is due to Stan, and Stan compiler needs quite a bunch of dependencies, which are mostly built via Dune. So a broken Dune is a pain :)

**Comment by Alizter** [comment]
@barracuda156 Try this PR. I can't test it myself as I don't have a powerpc VM setup.

https://github.com/ocaml/dune/pull/8942

Hopefully this fixes the issue, if not we will need to think a little harder.

**Comment by barracuda156** [comment]
@Alizter Thank you, I will test this tonight and update here.

**Comment by barracuda156** [comment]
@Alizter After applying the patch to `dune` 3.11.1, I got the following:

```
--->  Building ocaml-dune
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-dune/ocaml-dune/work/dune-3.11.1" && /usr/bin/make -j6 -w release 
make: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-dune/ocaml-dune/work/dune-3.11.1'
ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot unix.cma boot/libs.ml boot/duneboot.ml
./.duneboot.exe
Error: posix_spawn(): Exec format error
-> required by _build/default/doc/dune-build.1
-> required by _build/install/default/man/man1/dune-build.1
-> required by _build/default/dune.install
-> required by alias install
make: *** [release] Error 1
```
What could I try now?

**Comment by Alizter** [comment]
If you try
```
DUNE_CONFIG__BACKGROUND_DIGESTS=disabled
DUNE_CONFIG__BACKGROUND_SANDBOXES=disabled
```
this should disabled Dune's digest and sandbox code from running in background threads. I believe these were recently enabled on macos in https://github.com/ocaml/dune/pull/8090.

**Comment by barracuda156** [comment]
@Alizter Oh well, code there has errors:

1. This is wrong for macOS: `extern char ** environ;`.
2. This is incorrect too, AFAIK (need to verify): `# if defined(__MAC_OS_X_VERSION_MAX_ALLOWED)`. Firstly, header is missing where those are defined, secondly, leading __ should be dropped.

**Comment by barracuda156** [comment]
@Alizter @rgrinberg Could you please comment on the errors with 3.11.1 when trying to build dependents?
```
--->  Configuring ocaml-compiler-libs
--->  Building ocaml-compiler-libs
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-compiler-libs/ocaml-compiler-libs/work/ocaml-compiler-libs-0.12.4" && /opt/local/bin/dune build -j 6 --root=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-compiler-libs/ocaml-compiler-libs/work/ocaml-compiler-libs-0.12.4 --profile=release --ignore-promoted-rules --no-config --only-packages=ocaml-compiler-libs --default-target=@install @install 
File "src/shadow/dune", line 10, characters 0-147:
10 | (rule
11 |  (targets ocaml_shadow.ml)
12 |  (deps
13 |   (:first_dep gen/gen.exe))
14 |  (action
15 |   (run %{first_dep} -dir %{ocaml_where}/compiler-libs -o %{targets})))
Error: Rule failed to generate the following targets:
- src/shadow/ocaml_shadow.ml
File "src/ocaml_common/dune", line 8, characters 0-185:
 8 | (rule
 9 |  (targets ocaml_common.ml)
10 |  (deps
11 |   (:first_dep ../gen/gen.exe))
12 |  (action
13 |   (run
14 |    %{first_dep}
15 |    -archive
16 |    %{ocaml_where}/compiler-libs/ocamlcommon.cma
17 |    -o
18 |    %{targets})))
Error: Rule failed to generate the following targets:
- src/ocaml_common/ocaml_common.ml
File "src/ocaml_bytecomp/dune", line 8, characters 0-189:
 8 | (rule
 9 |  (targets ocaml_bytecomp.ml)
10 |  (deps
11 |   (:first_dep ../gen/gen.exe))
12 |  (action
13 |   (run
14 |    %{first_dep}
15 |    -archive
16 |    %{ocaml_where}/compiler-libs/ocamlbytecomp.cma
17 |    -o
18 |    %{targets})))
Error: Rule failed to generate the following targets:
- src/ocaml_bytecomp/ocaml_bytecomp.ml
File "src/ocaml_toplevel/dune", line 8, characters 0-189:
 8 | (rule
 9 |  (targets ocaml_toplevel.ml)
10 |  (deps
11 |   (:first_dep ../gen/gen.exe))
12 |  (action
13 |   (run
14 |    %{first_dep}
15 |    -archive
16 |    %{ocaml_where}/compiler-libs/ocamltoplevel.cma
17 |    -o
18 |    %{targets})))
Error: Rule failed to generate the following targets:
- src/ocaml_toplevel/ocaml_toplevel.ml
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-compiler-libs/ocaml-compiler-libs/work/ocaml-compiler-libs-0.12.4" && /opt/local/bin/dune build -j 6 --root=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-compiler-libs/ocaml-compiler-libs/work/ocaml-compiler-libs-0.12.4 --profile=release --ignore-promoted-rules --no-config --only-packages=ocaml-compiler-libs --default-target=@install @install 
Exit code: 1
```
Ref to https://github.com/ocaml/dune/pull/8090#issuecomment-1764480522

**Comment by Alizter** [comment]
Unfortunately Dune support for building the compiler itself is quite lacking. So I wouldn't recommend trying it unless your know what you are doing. If however you do want to press on https://github.com/ocaml-flambda/flambda-backend is a version of the compiler that are developing compiler optimisations, and notably they have a much better time building (their fork of) the compiler with Dune. So there might be some things to learn there.

Unfortunately its unlikely we will be able to help you with the compiler build as it relies a lot on a custom rule set and custom layout. Which isn't really up to us to make sure it works.

The recommended option would be to use `make` to build the compiler.

**Comment by barracuda156** [comment]
@Alizter Thank you. Here what I tried to build was `ocaml-compiler-libs` package, not OCaml itself. The package builds fine with Dune 3.7, in identical otherwise set-up.

**Comment by barracuda156** [comment]
@Alizter @rgrinberg Update on `dune`: whatever failed in example above, `dune` 3.11.1 itself works fine on 10.6 PowerPC. I have built two dependents of janestreet ports, it worked normally.

@emillon I got you. Once I am sure that everything works neatly, I will submit a PR.
