### ISSUE TITLE
feature: clear dune cache

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#8971]
It is pretty common to use `dune cache trim` to completely remove the cache. The right invocation is `dune cache trim --size 0B` but it requires finding about `--size` vs `--trimmed-size`, adding a `B` suffix, etc.

I suggest adding a dedicated way to do that. Either `dune cache trim --all`, or `dune cache clear`, to be determined.

**Comment by nojb** [comment]
+1 for `dune cache clear`.

Another cache-related "missing" feature: some way to print the cache location (maybe as part of `dune --verbose` output)

**Comment by Alizter** [comment]
I've had this idea to have a configurable default size for `trim` for some time now. The idea is that you put some config value in your dune config that gives a default value for size. That way you just have to write `dune cache trim` on its own with no arguments necessary. This would presumably subsume `dune cache clear`.

**Comment by nojb** [comment]
> This would presumably subsume `dune cache clear`.

Not really. `dune cache trim` without an argument would be used to _trim_ the cache (to your configured size). But sometimes you want to get rid of the cache, not trim it, which is when you would use `dune cache clear`.

**Comment by Alizter** [comment]
Right, I was thinking configuring the size to be 0. In which situations would you want to clear the cache rather than trim it?

**Comment by nojb** [comment]
> Right, I was thinking configuring the size to be 0.

I know, but my sense is that the two operations are independently useful.

> In which situations would you want to clear the cache rather than trim it?

Liberating disk space punctually, debugging purposes, ...

**Comment by Alizter** [comment]
I suppose one way `dune cache clear` would be distinct from `dune cache trim` is in speed. Trim takes its time calculating sizes, but if you just want to remove all the cache then `dune cache clear` doesn't need to concern itself with these calculations.

**Comment by nojb** [comment]
> `dune cache clear` doesn't need to concern itself with these calculations.

Good point.

**Comment by nojb** [comment]
I took a quick stab at this: #8975

**Comment by nojb** [comment]
> Another cache-related "missing" feature: some way to print the cache location (maybe as part of `dune --verbose` output)

And also this: #8974
