### ISSUE TITLE
melange: `.js` artifacts not copied when cram tests depend on `melange.emit` alias

### ISSUE THREAD

**Issue by jchavarri** [ocaml/dune#8977]
## Expected Behavior

Consider a case like this:

```
$ cat > dune <<EOF
> (melange.emit
>  (target app)
>  (alias app-alias))
> EOF

$ cat > a.ml <<EOF
> let () = Js.log "foo"
> EOF

$ cat > test/dune <<EOF
> (cram
>  (deps (alias_rec %{workspace_root}/app-alias)))
> EOF
```

I was expecting that the `.js` artifacts generated by `melange.emit` would be made available to the test.

## Actual Behavior

Only some empty folder structure is copied over.

## Reproduction

https://github.com/ocaml/dune/pull/8976

## Specifications

- Version of `dune`: latest
- Version of `ocaml`: 4.14.1

**Comment by rgrinberg** [comment]
Try adding `(expand_aliases_in_sandbox)` in your `dune-project` file.

**Comment by jchavarri** [comment]
Thanks. It doesn't seem to change the behavior: https://github.com/ocaml/dune/pull/8976/commits/c78ef35c422fabf0400cfe19e5090a9391ca568f

**Comment by jchavarri** [comment]
I just needed to call `dune clean` before running the test again 🎉 I updated the PR with the repro accordingly, feel free to merge or close accordingly.

**Comment by jchavarri** [comment]
btw, why is `expand_aliases_in_sandbox` not the default behavior?

**Comment by rgrinberg** [comment]
Because it can make sandboxing a lot slower. Although maybe it's the right default anyway? @snowleopard  might have  some comments.

**Comment by rgrinberg** [comment]
>  I just needed to call dune clean before running the test again 🎉 I updated the PR with the repro accordingly, feel free to merge or close accordingly.

This is actually a bug that you've detected. I've fixed it in https://github.com/ocaml/dune/pull/8990

**Comment by snowleopard** [comment]
> Because it can make sandboxing a lot slower. Although maybe it's the right default anyway? @snowleopard might have some comments.

Actually, at Jane Street, `expand_aliases_in_sandbox = true` by default (this is needed for compatibility with Jenga's behaviour).
