### ISSUE TITLE
What's the goal of the TUI mode?

### ISSUE THREAD

**Issue by favonia** [ocaml/dune#8982]
Hi, I was curious about `dune build --watch --display tui` when I saw 3.11 is out, but then got confused about its purpose after trying it. What do I gain besides `dune build --watch`? It seems I cannot do anything more than that. I checked through [GitHub issues tagged with `tui`](https://github.com/ocaml/dune/labels/tui) and became more puzzled. It seems the leading developer of this feature is [targeting the integrated terminal inside VS Code (see #8770)](https://github.com/ocaml/dune/issues/8770), and maybe there are plans to tighten the integration with the editor. However, if we are already inside VS Code, wouldn't it be easier to use LSP instead? What's the goal of this new TUI mode within VS Code? I failed to find more information from the changelog and the codebase, and felt I must have missed something here.

---

_PS: There are also some Unicode issues: It assumes `᚛`, `―`, and `᚜` will always align, but that's not the case in my terminal font (and nothing in the Unicode standard implies they should). It also seems to assume the box drawing characters with "Ambiguous" East Asia width always have the visual width of one cell, which is unfortunately not true, either, and that's why they are "Ambiguous". However, before trying to fix the character choice, I feel it's more important to understand the goal of the TUI mode._

**Comment by emillon** [comment]
Hi,
Thanks for your interest. I suggest opening a [discussion](https://github.com/ocaml/dune/discussions) since this is not an issue with dune and there's no action required to fix it.

**Comment by Alizter** [comment]
@emillon There is an option to convert this issue into a discussion on the side. I had an answer partially written out but I didn't finish it due to time. I'll try to finish it soon.
