### ISSUE TITLE
`ld: warning: -undefined suppress is deprecated` when running tests on macos

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#8983]
Creating this issue to reference https://github.com/ocaml/ocaml/issues/12641 in case people search for this error in dune. A simple repro at the moment is to run `dune build @test/libraries` in the dune repo. The output on my machine has some extra lines:
```
+  ld: warning: -undefined suppress is deprecated
+  ld: warning: -undefined suppress is deprecated
```

This is on an m1 mac running Sonoma 14.0 with clang 15.0.0

**Comment by gridbugs** [comment]
https://github.com/ocaml/ocaml/issues/12641 suggests it will also go away if we move to 4.14.2

**Comment by emillon** [comment]
Closing now that we're on 4.14.2
