### ISSUE TITLE
Change compiler flags based on OCaml version

### ISSUE THREAD

**Issue by talex5** [ocaml/dune#90]
I'd like to compile a library with `-O3`. Since OCaml 4.02 doesn't support that flag, I'd like to skip it for that version of the compiler.

I tried using `:include`, but it looks like `ocamlopt_flags` doesn't support that (`undefined symbol :include`). Is there another way (short of switching to the OCaml jbuild syntax)?

I guess #56 would also solve my problem, if implemented.

**Comment by diml** [comment]
`:include` is only supported for C compilation/link flags for historical reasons. I guess we could support it everywhere for uniformity, although you rarely need complex computation to determine the ocaml flags.

I don't think #56 will ever be implemented. It won't be enough in the long term; jbuilder will have to support OCaml plugins properly.

For simple things, I have been working on a small meta-programming language for jbuild files, see [this jbuild](https://github.com/janestreet/jbuilder/blob/meta-lang/doc/jbuild) for instance. Eventually there'll also be a way to change the default flags for a given scope, so you'll be able to write this in a toplevel jbuild file:

```scheme
(set_defaults
 ((ocamlopt_flags
   (:standard
    (:if (:ver> %{ocaml_version} 4.02) -O3)
    (:if %{dev} -w @a)))))
```

In the meantine, you indeed need to resort to the OCaml syntax.

**Comment by dra27** [comment]
#235 makes the suggestion that we could automate the removal of flags (which I think is a good idea)

**Comment by kit-ty-kate** [comment]
Here is an example where this can be useful: https://github.com/ocurrent/ocaml-ci/pull/265
Also I just noticed that the documentation says this feature is definitely coming in the future: https://dune.readthedocs.io/en/stable/concepts.html?highlight=flags#ordered-set-language.
```
Note that inside an ordered set, the first element of a list cannot be an atom except if it starts with -
or :. The reason for this is that we are planning to add simple programmatic features in the futures
so that one may write:

(flags (if (>= %{ocaml_version} 4.06) ...))
```
Any news on that?

**Comment by emillon** [comment]
`:include` in all flags has been added in #153, so I'm closing this. Thanks!
