### ISSUE TITLE
pkg: unable to depend on `seq` package

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#9017]
There are legacy library compatibility packages for OCaml such as `seq`. When we translate their opam files we have no build plan:
```
(version base)

(deps ocaml)
```
which is fine however this leads to the following problems when building:
```
DUNE_PKG_OVERRIDE_OCAML=1 ~/dune/_build/install/default/bin/dune build
Error:
open(_build/_private/default/.pkg/seq/source/seq.install): No such file or directory
-> required by _build/_private/default/.pkg/seq/target/cookie
```
Ideally in this situation, since there is no install step, we should not try to depend on seq.install or at least generate a dummy value.

**Comment by Alizter** [comment]
Specifically it seems that `seq` includes `seq.install` in its `extra-files` field.

**Comment by Alizter** [comment]
Here is the repro:
- https://github.com/ocaml/dune/pull/9026

**Comment by Alizter** [comment]
We are getting further with this build, now the permissions are read-only causing issue:
```
Error:
open(_build/_private/default/.pkg/seq/source/META.seq): Permission denied
-> required by _build/_private/default/.pkg/seq/target/cookie
```

**Comment by rgrinberg** [comment]
Should be fixed. Please re-open with a test case if something is still broken.

**Comment by Alizter** [comment]
I can confirm that this now builds.
