### ISSUE TITLE
Improve error message when a rule fails to generate a target

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#903]
See [this issue](https://github.com/ocsigen/lwt/issues/599) for an example. In the case where a rule fails to generate a target we get the fairly cryptic error:

```
Error: Rule failed to generate the following targets:
- src/unix/dlllwt_unix_stubs.so
```

It would be nice to improve this message by including the Action that tried to produce this target and possibly a location (if it exists). Right now, we have to dig through the build logs.

@diml I'm willing to improve this if you think this is a good idea. I haven't looked at the code yet, but it seems like this would be fairly simply. Any thing I need to keep in mind?

**Comment by diml** [comment]
I'm for it. I agree that it should be straightforward

**Comment by rgrinberg** [comment]
This was fixed a while ago.
