### ISSUE TITLE
pkg: rename rev_store's "git-repo"

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#9053]
We should rename `git-repo` before people start using `dune pkg` as the name is not very descriptive. When a user looks at `.cache/dune` they see
```
db
git-repo
```
and that doesn't really indicate this has anything to do with package management.

Some alternative naming suggestions are:
- `registry`
- `repo-registry`
- `repo-cache`
- `pkg-repos`
- `pkg-registry`

**Comment by rgrinberg** [comment]
The directory is an implementation of dune and users have no business looking into it. Therefore the current name is fine.
