### ISSUE TITLE
Discrepancy between copy and copy_files

### ISSUE THREAD

**Issue by trefis** [ocaml/dune#911]
`copy_files` seems to only accept copying from subdirectories, while the `copy` action is perfectly happy to fetch things from an arbitrary directory.

Is there any fundamental reason to this restriction `copy_files` implements or could it be lifted?

**Comment by diml** [comment]
There was one initially but we should now be able to lift this restriction. Basically to determine what files `copy_files <dir>/<glob>` produces, dune must first determine what files can be generated in `<dir>`. When `copy_files` was implemented we couldn't express this fact, so we were simply interpreting the jbuild files in subdirectories first and restricted `copy_files` to copy files from subdirectories.

**Comment by trefis** [comment]
This seems to have been fixed since v1.3.0
