### ISSUE TITLE
`dune init project foo` gives poor default name for test

### ISSUE THREAD

**Issue by tjdevries** [ocaml/dune#9131]
## Expected Behavior

When creating a new project with `dune init project foo`, the default dune file for the test folder could look like:

```
(test
 (name test_foo))
```

## Actual Behavior

When creating a new project with `dune init project foo`, the default dune file for the test folder will look like:

```
(test
 (name foo))
```
This makes it really confusing to new people when they try and add their `foo` library as a library dependency in this dune file. 

## Reproduction

- PR with a reproducing test: 

1. dune init project foo

**Comment by rgrinberg** [comment]
Sounds reasonable. A PR to fix this issue would be very much appreciated.
