### ISSUE TITLE
Typo in command ('format' instead of 'fmt') hangs `dune`

### ISSUE THREAD

**Issue by yashrk** [ocaml/dune#9151]
## Expected Behavior

Output of `dune format` (there is no such command, just `fmt` and `format-dune-file`) produces error.

## Actual Behavior

`dune` hangs. The last thing in `strace` log is:
```
ioctl(2, TCGETS, {c_iflag=ICRNL|IXON|IXOFF|IUTF8, c_oflag=NL0|CR0|TAB0|BS0|VT0|FF0|OPOST|ONLCR, c_cflag=B38400|CS8|CREAD, c_lflag=ISIG|ICANON|ECHO|ECHOE|ECHOK|IEXTEN|ECHOCTL|ECHOKE, ...}) = 0
read(0,
```

## Reproduction

Just type `dune format` in any project.

## Specifications

- Version of `dune` (output of `dune --version`): 3.8.1
- Version of `ocaml` (output of `ocamlc --version`): 4.14.1
- Operating system (distribution and version): Ubuntu 23.04

**Comment by nojb** [comment]
When you type `dune format` you are actually executing `dune format-dune-file` (this is due to the desambiguation logic of the library the Dune uses for its command-line interface). This commands expects input on `stdin`, which is why it appears to hang.

**Comment by yashrk** [comment]
O'k, thank you, so not a bug (although a bit confusing anyway).
