### ISSUE TITLE
Invalid Package_version.t

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#9176]
Sometimes the we gen "Invalid Package_version.t" errors. This happens for example while building `ezcurl.0.1`:

```
# Internal error, please report upstream including the contents of _build/log.
# Description:
#   ("Invalid Package_version.t", { s = "" })
# Raised at Stdune__Code_error.raise in file
#   "otherlibs/stdune/src/code_error.ml", line 10, characters 30-62
# Called from Stdune__Option.O.(>>|) in file "otherlibs/stdune/src/option.ml",
#   line 9, characters 21-26
# Called from Stdune__Option.map in file "otherlibs/stdune/src/option.ml"
#   (inlined), line 22, characters 15-28
# Called from Dune_rules__Findlib.to_dune_library in file
#   "src/dune_rules/findlib.ml" (inlined), line 127, characters 47-86
# Called from Dune_rules__Findlib.to_dune_library in file
#   "src/dune_rules/findlib.ml", line 127, characters 18-86
# Called from Fiber__Core.O.(>>|).(fun) in file "vendor/fiber/src/core.ml",
#   line 252, characters 36-41
# Called from Fiber__Scheduler.exec in file "vendor/fiber/src/scheduler.ml",
#   line 76, characters 8-11
```

**Comment by emillon** [comment]
Test in #9186.

**Comment by gridbugs** [comment]
My preference is to relax `Package_version.t` to allow empty strings.

**Comment by rgrinberg** [comment]
I don't think we can. Because opam doesn't accept empty strings as valid version numbers (AFAIK). 

The issue is that the version specified in the META is looser.

**Comment by emillon** [comment]
FYI, we were already parsing and exposing the version numbers through `dune-build-info`. We would return `Some ""` and if we decide to change `Some ""` to `None, it is going to make it return `None` now.

**Comment by emillon** [comment]
To add to that, there's already a difference between `Package_version.t` and `OpamPackage.Version.t`: the latter does not allow, say, `%` or `/` while I believe that anything is accepted in META files.

**Comment by rgrinberg** [comment]
> handle version = "" as if it was not set; this changes the behavior of dune-build-info; we keep Package_version.t compatible with opam version numbers. We recognize that it's a change in behavior but we think that this is a problem with the META files. (we could add a warning too, though it's not very actionnable)

If we ignore backwards compatibility, I think this is the way to go. The opam version is the one that we use to feed to the solver, while the META version is only there to make `ocamlfind list` pretty. Seems like it's obvious which one is more important.

**Comment by emillon** [comment]
Yes I'm now leaning into that solution as well. The last alpha run revealed that just interpreting the empty string as `None` fixes it (there are no other types of invalid version numbers in the wild) so that looks like a reasonable break.
