### ISSUE TITLE
dune does not recognise paths starting with `C:/` as absolute on Windows

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/dune#9218]
## Expected Behavior

dune produces correct paths in Windows cygwin MinGW cross environments

## Actual Behavior

Path normalization in dune produces invalid paths. The likely cause is that paths starting with C:/ are not recognized as absolute paths. Please note that Windows file APIs do accept / as path separator (since pretty much ever) without any pre processing (say by MinGW C library). So dune should support this as well.

Example paths produced in a Coq Platform 2023.11 / 8.18 build are:
```
src/C/bin/cygwin64_coq_platform/home/Michael/.opam/CP.2023.11.0~8.18~2023.11/lib/coq/theories/extraction/ExtrOcamlString.vo
src/C/bin/cygwin64_coq_platform/home/Michael/.opam/CP.2023.11.0~8.18~2023.11/lib/coq/theories/ZArith/ZArith.vo
theories/C/bin/cygwin64_coq_platform/home/Michael/.opam/CP.2023.11.0~8.18~2023.11/lib/coq-core/plugins/ltac/ltac_plugin.cmxs
```
these paths result in error messages like:
```
# 10 |  (modules :standard)
# 11 |  (flags -noinit -indices-matter -color on))
# Error: No rule found for
# theories/C/bin/cygwin64_coq_platform/home/Michael/.opam/CP.2023.11.0~8.18~2023.11/lib/coq-core/plugins/ltac/ltac_plugin.cmxs
```

A few notes:
- I am using a cygwin MinGW cross build environment. The produced dune is a MinGW exe, not a cygwin exe.
- paths usually use a mix of / and \ as path separators in such an environment

## Reproduction

- follow these [instructions](https://github.com/coq/platform/blob/main/doc/README_Windows.md) to setup a Coq Platform build environment on Windows - select extent "basic".
- open a shell of the newly created cygwin (which has opam)
- opam install dune 3.10.0 and any of these packages:
  - coq-simple-io.1.8.0
  - coq-mathcomp-word.2.1
  - coq-hott.8.18

## Specifications

```
$ dune --version
3.10.0

$ ocamlc --version
4.14.1

cygwin 64 bit on Windows 10, MinGW cross (that is using https://github.com/ocaml-opam/opam-repository-mingw)
```

**Comment by nojb** [comment]
> The likely cause is that paths starting with C:/ are not recognized as absolute paths.

Do you have a theory as to why there are no colons `:` in the (incorrect) paths produced in your setup?

**Comment by MSoegtropIMC** [comment]
@nojb : no. But since the opam packages don't pass paths to dune, I expect that this are issues with normalising CWD.

Can someone point me to the path normalisation code in dune, so that I can review it? I might also search for it, but it is hard to tell if I get all of it.

**Comment by Alizter** [comment]
The path normalization code is in `otherlibs/stdune/src/path.ml`. I'm currently trying to setup Coq platform as per your instructions (thank you very much for detailed instructions by the way), and I will see what the issue is soon enough.

**Comment by Alizter** [comment]
Here is what coqdep in Coq 8.18 is outputting:
```
  $ coqdep a.v -noinit -boot -R 'C:\cygwin64_coq\home\ali\.opam\CP.2023.03.0~8.17~2023.08\lib/coq/theories' Coq
  a.vo a.glob a.v.beautified a.required_vo: a.v C\:\cygwin64_coq\home\ali\.opam\CP.2023.03.0~8.17~2023.08\lib/coq/theories/Init/Prelude.vo
  a.vio: a.v C\:\cygwin64_coq\home\ali\.opam\CP.2023.03.0~8.17~2023.08\lib/coq/theories/Init/Prelude.vio
```

Newer versions of Dune started calling coqdep with -boot by default and passing the `-R` for Coq. `coqdep` appears to be outputting `C\:\cygwin64_coq\` which is complete garbage and confuses Dune into thinking this is a relative path.

**Comment by MSoegtropIMC** [comment]
@Alizter : many thanks for the root cause analysis! So it is apparently and issue in coqdep and not in dune.

Since it is apparently not an issue in dune, I am closing this.

**Comment by MSoegtropIMC** [comment]
@nojb: I reopen this since an analysis showed that the produced path syntax `C\:\cygwin64_coq\...` appears to be the correct escaping in make files (and the dependency files generated by coqdep are in makefile syntax). The colon character is a special character in make and must be escaped. This is the reason for the strange looking `C:\:\..`.  The escaping code in coqdep is [here](https://github.com/coq/coq/blob/2f3e6c2c70574d8d9e2ef1df37f3739ad18948a7/tools/coqdep/lib/makefile.ml#L11) and contains some explanations. Please note that according to this, the backskash itself need not be escaped in most cases.

So the root cause of the issue appears to be that dune does not properly unescape makefile syntax in dependency files.

**Comment by Alizter** [comment]
I am currently preparing a patch that you can use for Coq Platform. The relevant code is:

https://github.com/ocaml/dune/blob/7debf4e6224fea31c043e7306894f7a7da6a61e5/src/dune_rules/coq/coq_rules.ml#L438-L456

I am already not so happy that we have to do any parsing of coqdep output as this is very fragile, but now we have to also take into account the escaping.

It would be great if coqdep had a machine readable output like canonical S-expressions so that we didn't have to do this. Alternatively, if we vendored some of the `coqdep` library and simply called it in OCaml, however this is fragile for other reasons.

In any case, adding the extra parsing steps here and in the platform seems the best and most practical way forward.

**Comment by MSoegtropIMC** [comment]
Indeed it would be an option to have an alternate output format for coqdep. What I wouldn't appreciate though is if we would introduce simplified variants of make file syntax in order to simplify the communication between coqdep and dune. We should always use standard formats - S expressions would be a good choice IMHO. I don't care which format we use, but let's stick to whatever standard we use.

**Comment by ejgallego** [comment]
Indeed the way `coqdep` constructs paths could be improved; it's been in my TODO for a while, but not happening any time soon due to lack of time.

@Alizter thank you very much, your patch is IMO the right thing to do. `coqdep`, as called by `dune`, outputs paths in `Makefile` format as correctly noted by @MSoegtropIMC ; thus, `dune` should unescape the strings assuming they come in `Makefile` format.

**Comment by nojb** [comment]
> thus, `dune` should unescape the strings assuming they come in `Makefile` format.

Where can one find a specification of the format? I couldn't see anything related in the manual of GNU Make.

**Comment by MSoegtropIMC** [comment]
Indeed, as far as I can tell, the manual only says that # and a line trailing backslash can be escaped with a backslash. It is fairly obvious that a colon must be escaped if it appears in a target path - if make requires to escape it if it appears in a dependency I haven't tried.

The comment explaining escaping in coqdep was written by @ejgallego. Emilio: do you have a reference or evidence?

**Comment by ejgallego** [comment]
@MSoegtropIMC I'm unsure if that's what you are asking for, but the escape code for `coqdep` is here

https://github.com/coq/coq/blob/0c40866dc1b2f0c54c0f9bba4d965d961e6655cb/tools/coqdep/lib/makefile.ml#L18

Dune should be in sync with that code an unescape the paths properly.

**Comment by MSoegtropIMC** [comment]
@ejgallego : the question was if you have some references for the quoting rules in coqdep. There are some comments in the coqdep sources - from GIT history I guess by you - so I guess you have read about this somewhere. I couldn't fund much about this in the gnu make reference manual. Afaikt it only explains the escaping of \ and #.

**Comment by ejgallego** [comment]
The quoting rules were mostly added in Coq's commits:
- coq/coq@9a22ebe1d46b8f00980941ea0f54532595757f4e
- coq/coq@c6b7976677b943fbe8fa88a3e01e4b549e95ea90

and to the best of my knowlegde, they remain unchanged.
