### ISSUE TITLE
Package stanza missing from stanza reference

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#9251]
It seems we don't document the package stanza in the manual. At least not in any detail. We mention it in package-spec.rst and also the analogous fields for dune-project in dune-file.rst. Ideally, there should be a stanza entry in the stanza reference so that we have a more complete stanza specification.

**Comment by emillon** [comment]
It's documented at https://github.com/ocaml/dune/blob/3.14.0/doc/dune-files.rst#package and will be more visible with #9904.
