### ISSUE TITLE
Handle depexts field of opam files in a principled way

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#9294]
When an opam file has a `depexts` field, opam is instructed to use it's opam-depext library, historically a separate program, to find a good error message or suggestion of commands to run, later versions even running those commands.

In the context of Dune package management, we have access to the depexts field in an opam file, however currently we just ignore it. I propose that instead of ignoring it, we raise a user error with some detailed information about which commands should be run.

Here are my proposals with their strengths and drawbacks:

1. Run `opam-depext`
  + Advantages:
    - We can reuse opam-depext command suggestions and logic.
    - making it very easy for users to install external dependencies.
  + Disadvantages:
    - We rely on an external program or more internal opam libraries.
    - We shouldn't really involve ourselves with system installs, as that might introduce permission issues into the workflow with less experienced users (already (or used to be) a problem with opam).

2. Warn the user of all the depexts that were found during locking. We can even give system specific ones by using the filters on the depexts field.
  + Advantages:
    - Users will no longer get cryptic error messages during the building of the package.
  + Disadvantages:
    - Users not locking and just running the build won't get the messages.
    - It's not always obvious what commands to run from just the depexts entries. opam-depext solves this by having os-distribution specific suggestions for the external library or program.
    - This is noisy during locking, especially if the user already has the external dependencies installed. We cannot really determine if a depext is resolved.

3. Record the depexts in the lock file, and report them as hints during an unsuccessful build.
  + Advantages:
    - This doesn't affect locking.
    - When the user encounters a build error from a package, we give them a useful starting point to resolve it.
  + Disadvantages: 
    - Not clear what to do with depexts during locking, do we keep filters or not?
    - As in 2, it might not be useful simply to report the depexts field.

4. Keep the status quo.
   + Advantages:
     - We don't need to design or maintain any special handling of depexts.
   + Disadvantages:
     - User will get cryptic errors for missing dependencies in package builds, with no clear way to move forward.

These are the proposals on how to handle this issue. My personal opinion would be 3 with a mix of 1. Which would become the following proposal:

5. Do 3, but use opam-depext, if available, to give better hints.

I'm interested to hear other proposals and opinions on how to handle this situation.

**Comment by rgrinberg** [comment]
Solved by @moyodiallo
