### ISSUE TITLE
pkg: rev_store can't handle symlinks

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#9328]
Some opam repositories such as [dune-universe/opam-overlays](https://github.com/dune-universe/opam-overlays/tree/master/test/rwo.t) contain symlinks. This causes the rev_store to fail since the parser cannot understand the output of `git-ls`. Dune raises 
```
Error: exception Not_found
Raised at Dune_re__Core.exec in file "vendor/re/src/core.ml", line 937,
  characters 20-35
Called from Dune_pkg__Rev_store.File.parse.(fun) in file
  "src/dune_pkg/rev_store.ml", line 227, characters 14-29
```
in this case which under inspection gives the following line from `git-ls` as problematic:
```
160000 commit 0f8ea69ad66f745bd52ecae7189b72f8b6d50da8       -	test/rwo.t/book
```

Presumably this is due to the fact that `book` is a symlink in that repo and therefore changes the output of `git-ls`.

In this particular case the symlink occurs outside of `packages/` so the case could be made to ignore it, however it seems sensible after discussing with @Leonidas-from-XIV that symlinks could be supported in the `files/` directory of packages. Therefore the rev_store should be modified to handle them correctly.

To reproduce my error above, use the following `dune-workspace` file:
```
(lang dune 3.11)

(repository
 (name opam-overlays)
 (source "git+https://github.com/dune-universe/opam-overlays.git"))

(context
 (default
  (name default)
  (repositories opam-overlays)))
```

**Comment by Leonidas-from-XIV** [comment]
Turns out it is not a symlink, it is a `commit` object which… I don't know how this happened there. I wonder how to create those, since it seems very strange that a tree contains something else than a file.

**Comment by Leonidas-from-XIV** [comment]
So given this turned out not to be about symlinks but `commit` objects and it is fixed now, I'll close this as done.
