### ISSUE TITLE
Add support for the new -H <dir> argument in OCaml 5.2

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/dune#9333]
Would fix:
* https://github.com/ocaml/dune/issues/2733
* https://github.com/ocaml/dune/issues/4963

https://github.com/ocaml/ocaml/pull/12246 added support for the `-H <dir>` argument, which, similarly to `-I <dir>` adds the given directory to the list of directories the compiler will look into for interfaces. However contrary to `-I`, `-H` forbids explicit calls to the modules and instead only resolves their type.

Using this would fix a foundamental flaw in the `(implicit_transitive_deps false)` option which causes regular annoyance for users and opam-repository maintainers alike.

Dune should be able to detect which version of the OCaml compiler it’s using, and if it’s OCaml >= 5.2, then instead of not adding any of the implicit directories in `(implicit_transitive_deps false)` mode, it would instead use `-H`, the same way `-I` is used with `(implicit_transitive_deps true)`

**Comment by nojb** [comment]
I took a quick look. A clean way to approach this would be if the calculation of the transitive closure of a set of libraries (eg `Lib.closure`) could return a list `(bool * lib) list` indicating whether each `lib` is in the root set of simply reachable by transitiveness. Maybe this is easy, I haven't checked.
