### ISSUE TITLE
pkg: ocaml-config should not be built when overriding ocaml

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#9334]
Lock a project with no dependencies and build with `DUNE_PKG_OVERRIDE_OCAML=1`, and you will see the following:
```
$ dune pkg lock
Solution for dune.lock:
- ocaml.4.14.1
- ocaml-base-compiler.4.14.1
- ocaml-config.2

$ DUNE_PKG_OVERRIDE_OCAML=1 dune build --display short
       ocaml default/.pkg/ocaml/target [_private]
Error:
File "_build/.sandbox/70c0c2e7b0991d808e788b058d70ec81/_private/default/.pkg/ocaml/source/ocaml.config", line 8, characters 10-11:
8 |   compiler: "22"
              ^
Error parsing ocaml.config
Reason: Parse error
-> required by _build/_private/default/.pkg/ocaml/target/cookie

```
The `ocaml-config` package is built even though we passed `DUNE_PKG_OVERRIDE_OCAML`. Since we are not building the compiler locally, `ocaml-config` does not have access to the build configuration and cannot be built in a reasonable way. Furthermore, `ocaml-config` is only used by the `ocaml` package in opam, which we are already ignoring.

Therefore it makes sense to ignore this package also.

**Comment by rgrinberg** [comment]
This is incorrect. ocaml-config should indeed be built even if the package is provided by the system. That package provides important variables that other packages can use.

**Comment by Alizter** [comment]
No other package uses `ocaml-config`: https://ocaml.org/p/ocaml-config/latest

**Comment by Alizter** [comment]
@rgrinberg Even if you think that ocaml-config should be built, can we reopen this issue? It shows the current inability of Dune to parse ocaml.config.
