### ISSUE TITLE
pkg: ocaml-variants, ocaml-base-compiler, ocaml-system and dkml-base-compiler should be ignored by DUNE_PKG_OVERRIDE_OCAML

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#9335]
The following packages
- ocaml-variants
- ocaml-base-compiler
- ocaml-system
- dkml-base-compiler

Are dependencies of the package `ocaml` which is ignored when using `DUNE_PKG_OVERRIDE_OCAML`. For the reasons outlined in #9334, it is not desirable for these to also be built when passing `DUNE_PKG_OVERRIDE_OCAML`. Therefore, these packages should be additionally ignored.

Even if these packages could be built, which for other reasons today they cannot, they would not be used by any other package as the `ocaml` "meta" package organizes them, and we ignore that.

**Comment by rgrinberg** [comment]
All the packages listed in this ticket are already by `flags: compiler`. Which means that we should skip them when the solver chooses them.

**Comment by Alizter** [comment]
Only `ocaml-base-compiler` is not skipped. Is that expected?

**Comment by rgrinberg** [comment]
`ocaml-base-compiler` is skipped for me. what is the contents of your `lock.dune` file?

**Comment by Alizter** [comment]
```
(lang package 0.1)

(dependency_hash dd942da8befc9bd7cf38280bb9abb184)

(ocaml ocaml-base-compiler)

(repositories
 (complete true)
 (used
  ((source https://github.com/ocaml/opam-repository.git)
   (repo_id
    (git_hash bc52affc41b55ff00c0d3ac9a376538d79695aaf)))))

(expanded_solver_variable_bindings
 (variable_values
  (os-family nixos)
  (os-distribution nixos)
  (os linux)
  (opam-version 2.2.0~alpha-vendored)
  (arch x86_64))
 (unset_variables
  with-test
  with-doc
  sys-ocaml-version
  post
  enable-ocaml-beta-repository
  dev
  build))
```

**Comment by rgrinberg** [comment]
No idea what the issue is then. ocaml-base-compiler is clearly marked as the ocaml package to be skipped when the environment variable is set.

**Comment by Alizter** [comment]
For me, the `ocaml` package itself is skipped, but the rules for `opam-base-compiler` are still present and can be triggered with `dune build`. You mentioned that they are skipped when the solver chooses them, do you mean they are skipped in the locking or build phases?

AFAIK the override only works for the build phase.

**Comment by rgrinberg** [comment]
The solving step chooses which package is the compiler. While the build step has the option to ignore it.

This is the relevant line that connects the two:

```
(ocaml ocaml-base-compiler)
```
