### ISSUE TITLE
Support packages without checksums

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#9336]
Some packages in the opam repository do not include checksums. One such example are the `+trunk` OCaml compiler packages.

We should download such packages as part of the solving stage and include the newly computed checksums.

**Comment by gridbugs** [comment]
@rgrinberg can you clarify what is meant by "support" here. Lots of our existing pkg tests construct tiny packages with no checksums in them. Do you mean when creating the lockfile for a package, if that package has a source but no checksum, we should compute the checksum of the source and include that in the lockfile?

**Comment by rgrinberg** [comment]
>  Do you mean when creating the lockfile for a package, if that package has a source but no checksum, we should compute the checksum of the source and include that in the lockfile?

Yes, this is exactly what I meant. When we generate such a lock directory, we should compute the checksums and include them.
