### ISSUE TITLE
Support dune projects with only opam metadata

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#9341]
Currently, we read all package metadata from the dune-project file. While that's correct thing to do when dune-project contain all the metadata, we completely fail for projects where this metadata only lives in the .opam file. Instead, we should fallback to .opam files when the project files don't define the relevant packages.

cc @tmattio

**Comment by gridbugs** [comment]
Is it correct to assume that all the .opam files in the top-level of a project are local packages in that project?

**Comment by gridbugs** [comment]
Do you mean that currently dune reads opam files from both the project's root directory and also from a directory named "opam" located in the root directory if one exists? Are there any other places where dune reads opam files or is that it? I'm poking around with `Dune_project.load` to try to understand its current behaviour but it only seems to read opam files from the top level.

**Comment by gridbugs** [comment]
The docs for `Dune_project.load` is
```ocaml
(** Load a project description from the following directory. [files] is the set
    of files in this directory.

    If [infer_from_opam_files] is true and the directory contains no
    [dune-project] file but contains at least one [<package>.opam] files, then a
    project description is inferred from the opam files. *)
val load
  :  dir:Path.Source.t
  -> files:Filename.Set.t
  -> infer_from_opam_files:bool
  -> t option Memo.t
```

I guess we could call this multiple times for different directories where we want to look for opam files?

Also while I'm looking at this function, do you understand why the `files` argument is necessary? It sounds like we should be able to compute it by enumerating the files in `dir`. Am I missing the intent of this argument?

**Comment by rgrinberg** [comment]
How about we start with a cram test demonstrating what is/isn't working? E.g. a project without any `(package ..)` stanzas but with corresponding .opam files.

> Also while I'm looking at this function, do you understand why the files argument is necessary? It sounds like we should be able to compute it by enumerating the files in dir. Am I missing the intent of this argument?

To read the directory, you need the source tree. The source tree depends on project settings, so projects cannot read the source for that would cause a dependency cycle between their respective modules.

**Comment by gridbugs** [comment]
From the look of things all that's required to handle package metadata in opam files in the project root directory is to parse the `depends` fields of those files (we already parse other metadata from them but I'm not sure what it's used for yet). I'll work on that and put together some tests to demonstrate which directories are currently supported.
