### ISSUE TITLE
Submodules Support

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#9377]
Make sure that we support submodules in the following two contexts:

1. Pulling package sources from git
2. Using opam repositories from git that contain submodules

cc @Leonidas-from-XIV

**Comment by Alizter** [comment]
In both these cases, we shouldn't actually fetch the submodules right? That's for the build process to do in 1., but I am unsure about 2.

**Comment by Leonidas-from-XIV** [comment]
I don't see an alternative to fetching in case 2 and even in case 1 I think the expectation is that the submodules are checked out before building.

**Comment by rgrinberg** [comment]
I think this feature has been implemented? What's missing is a few test cases for recursive submodules.

**Comment by Leonidas-from-XIV** [comment]
I'll add a test for recursive submodules and close this then.
