### ISSUE TITLE
readdir_with_kind_if_available_unix expects non-POSIX d_type

### ISSUE THREAD

**Issue by donncave** [ocaml/dune#9389]
## Expected Behavior
(while expecting a successful build of src_ext/dune-local in opam-2.1.0)

## Actual Behavior
C compilation error with src/dune_filesystem_stubs/readdir.c, undefined symbols DT_REG etc.

Per POSIX, d_type isn't a required member of the dirent struct, so this isn't surprising.

It looks to me like if the Haiku version returns 7 (unknown), the caller will go on to get file type from lstat(2)?

## Reproduction

- PR with a reproducing test: 

1.  Build opam-2.1.0 on Haiku operating system.
1.
1.

## Specifications

- Version of `dune` (output of `dune --version`):
2.9.0?  (from CHANGES.md)
- Version of `ocaml` (output of `ocamlc --version`)
4.12.0
- Operating system (distribution and version):
Haiku x86_64 hrev57434

**Comment by Alizter** [comment]
Older versions of Dune are not supported on Haiku, but support was added in 3.11. If its possible, try using a more recent version of Dune.

**Comment by emillon** [comment]
Yes, it looks correctly `#ifndef`'d it main.

**Comment by donncave** [comment]
OK, thanks, 3.12.1 builds here.  With some work.  (wait4() isn't POSIX either, but I'm going to assume that waitpid(...) followed by getrusage(RUSAGE_CHILDREN, &ru) will serve the same purpose.)
