### ISSUE TITLE
Choose an appropriate lockdir for the current system

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#9451]
If a project has different dependencies on different systems it will require separate lockdir for each system. For the purpose of this discussion assume that a project can be built on both linux and windows, but has different dependencies on each system which are locked in directories "dune.linux.lock" and "dune.windows.lock" respectively.

Currently each build context is associated with a single lockdir and each dune project has a single default build context. If the default build context uses its lockdir as "dune.linux.lock" then windows users will need to manually specify an alternative build context which uses "dune.windows.lock". More generally, each dune project with system-specific dependencies will need to nominate a particular system to be favoured by the default context and require developers on other systems to manually override the context (via command line args) to the one compatible with their system. This will likely lead to frustration as it means the default behaviour of dune (without choosing an alternative context) doesn't work for some users, depending on their system.

To address this dune will need to choose which lockdir to use by interrogating the current system. To motivate discussion, here's my initial proposal for how it should look:

```
; dune-workspace
...
(context
  (default
    (name default)
    (lockdir_choice
     (dune.linux.lock (= %{os} linux)
     (dune.windows.lock (= %{os} windows)))
```

I'm proposing to add a new `lockdir_choice` field to `context`, mutually-exclusive with the `lockdir` field, which defines a list of (path, blang) pairs encoding the conditions under which each lockdir can be chosen. I'm against using a more general select statement or the slang language here so that in the event that the user's system isn't in the list, dune can print an appropriate error message. The reason the predicates are expressed as blangs rather than just naming the system is so that users can discriminate on other aspects of the system such as arch and version. The reason I propose dynamically choosing the lockdir of a context rather than dynamically choosing the context itself is because the other fields of the context don't depend on the current system.

**Comment by nojb** [comment]
Sorry for naïve question, but what is the obstacle to Dune taking care of a per-system dependencies using a single metadata directory/file and doing so automatically (without needing intervention from the developers or the users of the project)?

**Comment by rgrinberg** [comment]
The suggestion is fine, but I dislike adding such specific conditional constructs to the dune language. I'd prefer a more general construct, even if it's only available in a single location at the start. If we had many constructs like this, I fear that the dune language will become impossible to learn or remember.

> but what is the obstacle to Dune taking care of a per-system dependencies using a single metadata directory/file and doing so automatically (without needing intervention from the developers or the users of the project)?

To handle every single system, we would essentially need the entirety of the opam repository. That would be quite a useful way of working, but it would be useless for deployment to end users. Since downloading the opam repository to generate the build plan would be rather time consuming.

In the future, we do plan to have a mode where you can just write the version of the opam repository you want to use and work without a lock directory. Such a mode would work with every single platform that opam-repository supports.

**Comment by Alizter** [comment]
For context, do we know of any examples of windows locks being different from the rest?

**Comment by gridbugs** [comment]
> For context, do we know of any examples of windows locks being different from the rest?

Wouldn't this be any project that uses system solver vars (like `os`) to filter dependencies?

> I dislike adding such specific conditional constructs to the dune language. I'd prefer a more general construct

Fair point, I can see how that would help people learn dune. The main obstacle to using the slang dsl here is how to represent the case when there is no lockdir for the current system. We could use nil for this case and have dune print an error message if the lockdir was nil. E.g.

```scheme
(context
  (default
    (name default)
    (lockdir
     (if (= %{os} linux) dune.linux.lock
       (if (= %{os} windows) dune.windows.lock ()))
```

This has the added bonus of using the same field as when there's only one choice of lockfile for a context since a string literal is a valid slang expression.

Also I think it would be more ergonomic to use a match-statement rather than nested if-statements here. Slang currently doesn't have match statements but it would be easy to add.

**Comment by rgrinberg** [comment]
> Also I think it would be more ergonomic to use a match-statement rather than nested if-statements here. Slang currently doesn't have match statements but it would be easy to add

You could add a `cond` statement. It's similar to a `switch` in C like languages but without the fall through. The advantage over match-statement is that you don't have to think of clauses introducing binders.

**Comment by gridbugs** [comment]
Ah yes that would be preferable. And we don't need to think about the case where the value being matched on isn't a string. For example the example dune-workspace snipped would look like:
```
(context
  (default
    (name default)
    (lockdir
      (cond
        ((= %{os} linux) dune.linux.lock)
        ((= %{os} windows) dune.windows.lock)
        ()))))
```

The last argument (the `()` above) is the catchall if none of the other conditions are met. We could also consider allowing the catchall to be omitted and to default to nil. If we did that then `cond` would become a generalization of `when` allowing multiple condition/value pairs rather than just one.

**Comment by rgrinberg** [comment]
The `cond` idea sounds like a pretty safe bet to me. Even if it's not ideal for this task, it woudl be useful in other situations.

**Comment by gridbugs** [comment]
Fixed in https://github.com/ocaml/dune/pull/9750
