### ISSUE TITLE
Add --dry-run option to `dune pkg lock`

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#9459]
Users might find it useful to run `dune pkg lock` without updating their local lock directories to inspect what would change. This can be especially useful in the rare case a user doesn't use version control.

I propose that we add `--dry-run` option to `dune pkg lock` that prevents Dune from deleting and writing the `dune.lock/` file and simply displays the solution to the lock directory.

**Comment by rgrinberg** [comment]
It was discussed before and rejected. It's easy enough to point `dune pkg lock` onto some dummy target and then throw away the result.
