### ISSUE TITLE
Validate solver vars in lockdir against those in the workspace

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#9511]
The solver variables that were read while generating a lockdir are stored in the lockdir. Some operations on lockdirs use the variables in the lockdir while others read the whole solver variable environment from the workspace. To avoid inconsistencies we should validate that all the solver variables in the lockdir are assigned the same values in workspace file. The two ways inconsistencies can be introduced is by a user changing a variable in the workspace file in a way that would affect the dependency solution, and by directly tampering with the lockdir.

Note that there will likely be variables in the lockdir with no counterpart in the workspace file. These would have been polled from the system where the lockdir was generated and should be ignored by this validation.

**Comment by rgrinberg** [comment]
I think this is done?

**Comment by gridbugs** [comment]
Yep
