### ISSUE TITLE
`jbuilder subst -n <name>` is sometimes not properly rooted

### ISSUE THREAD

**Issue by samoht** [ocaml/dune#954]
To reproduce:

- install opam 2.0rc3, enable sandboxing
- clone ocaml-cohttp: https://github.com/mirage/ocaml-cohttp
- in that directory, create a local switch: `opam switch create . 4.06.1`
- then `opam install cohttp`. You will get:

```
#=== ERROR while compiling cohttp.1.1.0 =======================================#
# context     2.0.0~rc3 | macos/x86_64 | ocaml-base-compiler.4.06.1 | pinned(git+file:///Users/thomas/git/ocaml-cohttp#master#2de6f277)
# path        ~/git/ocaml-cohttp/_opam/.opam-switch/build/cohttp.1.1.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build jbuilder subst -n cohttp
# exit-code   1
# env-file    ~/.opam/log/cohttp-63694-6cc03f.env
# output-file ~/.opam/log/cohttp-63694-6cc03f.out
### output ###
# Entering directory '/Users/thomas/git/ocaml-cohttp'
# Error: exception Sys_error("cohttp-async.opam: Operation not permitted")
# Backtrace:
# Raised by primitive operation at file "pervasives.ml", line 315, characters 29-55
# Called from file "src/stdune/io.ml", line 16, characters 15-36
# Called from file "list.ml", line 100, characters 12-15
# Called from file "src/watermarks.ml", line 226, characters 2-100
# Called from file "src/fiber/fiber.ml", line 359, characters 6-13
```

You can reproduce that by going into the local switch and running the command again:

```
$ cd _opam/.opam-switch/build/cohttp.1.1.0
$ ~/.opam/opam-init/hooks/sandbox.sh build jbuilder subst -n cohttp
Entering directory '/Users/thomas/git/ocaml-cohttp'
Error: exception Sys_error("cohttp-async.opam: Operation not permitted")
Backtrace:
Raised by primitive operation at file "pervasives.ml", line 315, characters 29-55
Called from file "src/stdune/io.ml", line 16, characters 15-36
Called from file "list.ml", line 100, characters 12-15
Called from file "src/watermarks.ml", line 226, characters 2-100
Called from file "src/fiber/fiber.ml", line 359, characters 6-13
```

`jbuilder` tries to modify the source directory, not the temporary checkout!

And this works:

```
$ ~/.opam/opam-init/hooks/sandbox.sh build jbuilder subst -n cohttp --root .
```

/cc @rjbou

**Comment by diml** [comment]
Are these commands part of the build command of a package? These should always be passed `-p <package>` to force a more reproducible behavior. In particular `-p` implies:

- disabling root detection
- not reading the user configuration file
- other stuff

**Comment by samoht** [comment]
This is not what instructions says (or used to say) as it recommends to use `-n`. So you reckon we should use `jbuilder subst -p <name>`  instead?

btw, you can just reproduce it with:

```
$ cat FOO
%%NAME%%
$ tree
├── FOO
├── _build
│   ├── FOO
│   └── foo.opam
├── foo.opam
└── jbuild-workspace.dev
$ cd _build && jbuilder subst -n foo
$ cat FOO
foo
```

**Comment by diml** [comment]
Yes, we need to upgrade the instructions then

**Comment by samoht** [comment]
So there's a bit of work to do in opam-repository then :-)

```
$ git grep '"jbuilder" "subst"' | grep -v "\p" | wc -l
     507
```

**Comment by samoht** [comment]
https://github.com/ocaml/opam-repository/pull/12279 adds `-p` everywhere (and replaces `-n` by `-p` when necessary). Does it look like the good change to you?

**Comment by diml** [comment]
The `-n` is for something else, so it should be kept. It is used to define what `NAME` will be replaced by

**Comment by diml** [comment]
For Dune we probably won't need it though, since the name can be written in the `dune-project` file

**Comment by diml** [comment]
I created #960 to improve the behavior of `dune subst`.
