### ISSUE TITLE
Modules generated for sites use an implicit transitive dep

### ISSUE THREAD

**Issue by rizo** [ocaml/dune#9661]
## Expected Behavior
Compiling modules created with `generate_sites_module` when `implicit_transitive_deps` is set to `false` should work.

## Actual Behavior
It doesn't, failing with:

```
     ~section:Dune_section.Share
              ^^^^^^^^^^^^^^^^^^
Error: Unbound module Dune_section
```

From what I understand, the `dune-site` lib implicitly depends on `dune-private-libs.dune-section`.

As a workaround the library that uses sites can directly depend on `dune-private-libs.dune-section`.

## Specifications

- Version of `dune` (output of `dune --version`): 3.12.1
- Version of `ocaml` (output of `ocamlc --version`): 5.1.0
- Operating system (distribution and version): macOS 14

**Comment by nojb** [comment]
While working on #9333, @MA0010 remarked that the issue here is that the `dune-site` library should "re-export" `dune-section` library, since the code generated by Dune for sites mention `Dune_section` which is a module of `dune-section`. @MA0010 will submit a PR with the fix.
