### ISSUE TITLE
Request: rule to account for tests that should fail to compile

### ISSUE THREAD

**Issue by ElectreAAS** [ocaml/dune#9671]
This issue is part of a series of comments, criticisms, and requests on dune I gathered during my last visit at Inria. If some of these seem trivial or incoherent at face value, I'd wager we should press the authors for more context.
Everything below is paraphrased from my notes.

## Desired Behavior

I am working on a compiler internal thingy, and I'd like to have tests that are supposed to fail to compile. Something like this :

```sexp
(test
 (name wont-compile)
 (<special-setting-here> false))
```

Where `wont-compile.ml` is a file that doesn't contain test executable, but rather some edge-case for the compiler internal thingy that should be rejected.

**Comment by ElectreAAS** [comment]
(This comment is my own)
I believe this is somewhat solved by `(rule (action (with-accepted-exit-codes 1 ...)))`, but afaik that might involve putting some bespoke incantation in the `...` part.

**Comment by rgrinberg** [comment]
Following your comment, I suppose it would b e enough to fix the issue with:

```
(test
 (name wont-compile)
 (action (with-accepted-exit-codes 1 (run ./wont-compile.exe)))
```

The only issue I see here is the redundancy of having to repeat the test's executable. I suppose we could introduce a percent form in the action field that expands to the old action or to the test name to remove this redundancy.

**Comment by emillon** [comment]
is the test expected to fail at runtime or at compile time?

**Comment by ElectreAAS** [comment]
It is expected to fail at compile time

**Comment by emillon** [comment]
I think that's out of scope for dune, TBH.
