### ISSUE TITLE
Request: build errors order should be deterministic

### ISSUE THREAD

**Issue by ElectreAAS** [ocaml/dune#9674]
This issue is part of a series of comments, criticisms, and requests on dune I gathered during my last visit at Inria. If some of these seem trivial or incoherent at face value, I'd wager we should press the authors for more context.
Everything below is paraphrased from my notes.

## Current Behavior

When `dune build` fails with multiple errors, they might come in different orders due to parallel builds. This makes it hard to diff when the wall of errors gets big.

## Desired Behavior

All reported errors on a given `dune build` are in a deterministic order.

## Workaround

On small projects, it can be reasonable to `dune build -j 1`, but that's obviously not ideal.

**Comment by emillon** [comment]
This is controlled by a `--error-reporting` flag in `dune build`: `early` (the default) will display them earlier (useful while developing in general), but `dune build --error-reporting=deterministic` will switch to a deterministic order at the end of a build.

**Comment by ElectreAAS** [comment]
(This comment is my own)
I agree that the functionnality is there. However maybe it could be better advertised.
Or maybe it's a niche option that has few users, I'll ask around and notify the author of this claim.
