### ISSUE TITLE
Request: build only a desired .cmo, and not everything after that

### ISSUE THREAD

**Issue by ElectreAAS** [ocaml/dune#9675]
This issue is part of a series of comments, criticisms, and requests on dune I gathered during my last visit at Inria. If some of these seem trivial or incoherent at face value, I'd wager we should press the authors for more context.
Everything below is paraphrased from my notes.

## Desired Functionality

Something like `dune build foo.cmo` which would only build what is necessary for `foo.cmo`, and nothing else.
It would be very useful in `--watch` scenarios, where the .cmo file will be manually inspected.

**Comment by nojb** [comment]
Hello, this is already possible: `dune build '%{cmo:<name of compilation unit>}'.

**Comment by nojb** [comment]
Of course, this is also possible by doing `dune build <path to the .cmo in the _build directory>`, but one needs to know how the `_build` directory is laid out.

**Comment by ElectreAAS** [comment]
So in this example, that would be `dune build '%{cmo:foo}'`?
Do you know if that would work even if `foo` had multiple dependencies? The point in that scenario is to not have to specify the whole thing in command line if it's already written in `dune` files.
If that's the case, the syntax is a little bit weird, but more importantly I (and the person who requested this) never heard of it, which means the documentation should probably be improved.

**Comment by nojb** [comment]
> So in this example, that would be `dune build '%{cmo:foo}'`?

Yes (in general you need to type in the path to the folder where the source file for `foo` lives, ie `%{cmo:a/b/foo}`).

> Do you know if that would work even if `foo` had multiple dependencies?

Yes, it works fine.

> I (and the person who requested this) never heard of it, which means the documentation should probably be improved.

It is documented here: https://dune.readthedocs.io/en/stable/advanced/variables-artifacts.html

**Comment by ElectreAAS** [comment]
Oh that's great! Thanks!
I'll notify the author of the request
