### ISSUE TITLE
log rules that are executed

### ISSUE THREAD

**Issue by Khady** [ocaml/dune#9691]
in `_build/log` we get all the "external" commands that dune runs. But we don't have a list of all the rules that are executed during a build. That would be nice to have. Even nicer if for a rule we had the start and end times, and if we could see which by which rules it was triggered, creating a tree that could later have a visualiser, but it would already be useful without those extra info.

**Comment by emillon** [comment]
It's possible to do that by adding a logging function in `Action_exec.run`. The challenges with this are:
- this is going to be very noisy, so it needs a new `--debug` parameter
- it's part of the engine, where I don't think we can access the serializer for actions. So this will likely require a custom pretty-printer. One nice thing about this is that it's possible to add syntax highlighting that's specific to actions.

**Comment by Khady** [comment]
I mentioned _build/log as it is what exists now, but it’s probably fine if it is in another file and only created if a given flag is passed. I assume that this will be used mostly to debug a build, which is relatively infrequent.

**Comment by ELLIOTTCABLE** [comment]
Pending some sort of benchmarking — log in-memory by default, dump to a marshalled log-format somewhere by default, don't include in text-logs; use a flag to decide whether to print log-messages to stderr; provide ability to load-and-print marshalled log from most recent build?

**Comment by rgrinberg** [comment]
Why don't you work with the trace output? It's going to be a lot easier to visualize that than parsing the output of _build/log

**Comment by Khady** [comment]
Sorry I missed this question. The current trace output has the same limitations, it's not complete enough

**Comment by rgrinberg** [comment]
The build log has its own limitations

**Comment by Khady** [comment]
as I said before we are fine with something that is not the build log

> I mentioned _build/log as it is what exists now, but it’s probably fine if it is in another file and only created if a given flag is passed. I assume that this will be used mostly to debug a build, which is relatively infrequent.

The point is to find a way to "audit" a build. I'd be interested to know if this is currently something possible without having to modify dune (the straight rejection gives me the impression that it's something that you consider already doable). I think that one possible thing would be to have a visualiser for the sexp output of `dune rules`, but that would lack some runtime info such as duration taken to run a rule. Otherwise how to create a trace which would have enough information?

Btw this is something that we could work on and contribute, so long as it's not duplicating an effort or an already existing features.

**Comment by rgrinberg** [comment]
I think you need to look into the trace file. If there's any information that's missing, we can always add more. Visualizing `dune rules` is indeed doable, but the result would be a representation of the build graph, and not a particular execution of a build.

> Btw this is something that we could work on and contribute, so long as it's not duplicating an effort or an already existing features.

After you take a look at the trace file, let us know which concrete bits of information you still need. We can discuss adding more.
