### ISSUE TITLE
Remove the `copy` constructor from `Dune_pkg.Source.t`

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#9700]
Writing `(source (copy ..))` should be the same as `(source (fetch file://..))` so `(copy ..)` is redundant.

**Comment by rgrinberg** [comment]
cc @gridbugs @Leonidas-from-XIV any objections to doing this?

**Comment by gridbugs** [comment]
No objection from me.

**Comment by Leonidas-from-XIV** [comment]
Nor from me.
