### ISSUE TITLE
copy_files glob should operate on source files (not target files inside _build folder)

### ISSUE THREAD

**Issue by davesnx** [ocaml/dune#9709]
## Desired Behavior

```
(copy_files#
 (mode fallback)
 (files "../src/*.{re,rei}"))
```

Currently the glob applies to all generated by targets with the following extensions: .re/.re.ml/.pp.ml/.rei.mli/.rei.pp.mli which makes writing a glob a bit challenging since groups and sets can't be negated together.

Anyway, when you are just copying reason files is fine, but as soon as you want to copy all reason and all ocaml files, dune finds all the refmt generated or pp generated files and becomes a duplicated target.

## Example

```
(copy_files#
 (mode fallback)
 (files "../src/*.{re,rei,ml,mli}"))
```

Should glob on all source files and not the generated.

**Comment by nojb** [comment]
This sounds reasonable; we could add a `(source_files <glob>)` alterantive for the `(copy_files#)` stanza, similar to what we do in the dependency language.

**Comment by rgrinberg** [comment]
Will this work as expected if you're generating some of your sources? E.g.

```
(rule
 (with-stdout-to foo.ml (run gen.exe)))
```

**Comment by jchavarri** [comment]
> Will this work as expected if you're generating some of your sources?

Depends on what the expected behavior is 😄 I think in this case I would expect `foo.ml` to not be copied over, because it's not technically a "source" file.

**Comment by rgrinberg** [comment]
Yes, I'm just making sure that it is files that exist in the source tree is what you want. In any case, the suggestion made by @nojb seems fine by me if you'd like to implement this feature.
