### ISSUE TITLE
Re-downloading the same sources when computing pins or packages without checksums

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#9746]
If we have two packages such as:

```
$ cat lwt/1.0.0/opam
..
url {
  src: "http://github.com/1.0.0/lwt.tar.gz"
}
$ cat lwt-unix/1.0.0/opam
..
url {
  src: "http://github.com/1.0.0/lwt.tar.gz"
}
```

We are going to download them twice during the solve phase. A similar problem exists with `pin-depends`. This is all rather wasteful, especially for projects that define multiple packages - common for dune-projects.

We should maintain the already downloaded sources as part of the solve phase and not redo this work.

@gridbugs could you have a look at this one?

**Comment by gridbugs** [comment]
@rgrinberg is this issue just about reusing downloaded files within a single run of dune, or across multiple invocations of dune?

**Comment by Leonidas-from-XIV** [comment]
I've seen #9771 but I'm wondering that if we're adding a cache, wouldn't it be better to store the artifacts persistently? This is what the previous OPAM code did: download the file and add it to the cache if the checksum matches, then pull it out of the cache the next time the file is requested (and reverify the checksums in case of data corruption).

**Comment by rgrinberg** [comment]
It's an option, but not my first one. We'd have to re-implement the dune cache without deduplication, sharing, the UI to manage it. If we realize that the dune cache can't be used for this purpose, then we can consider creating our own parallel implementation.
