### ISSUE TITLE
`enabled_if` is accepted in `test` stanza but has no effect

### ISSUE THREAD

**Issue by edwintorok** [ocaml/dune#9855]
## Expected Behavior

`enabled_if` has some effect on `test` stanzas: it should at least prevent them from running,
and ideally prevent them from building.

## Actual Behavior

Dune attempts to build a test that cannot be built on that platform.

E.g. https://ocaml.ci.dev/github/backtracking/ocaml-hashcons/commit/e445076586f99fc8d18c4d09c132e85a744603e5/variant/debian-12-4.14_arm32_opam-2.1 failed with
```
File "rule110.ml", line 208, characters 33-52:
208 | let () = test "1010100010111101" 1152921504606846975 682111393702695301
                                       ^^^^^^^^^^^^^^^^^^^
Error: Integer literal exceeds the range of representable integers of type int
```

But there was an `enabled_if` on the `test`:
```
(test
 (name rule110)
 (modules rule110)
 (deps quicksort.term)
 (enabled_if %{arch_sixtyfour})
 (libraries hashcons))
```

Setting `enabled_if false` doesn't prevent running the test either.

## Reproduction

```
(test
  (name test)
  (modules test)
  (enabled_if false)
)
```

Where `test.ml` contains something that doesn't compile (e.g. a syntax error).
Dune should not attempt to compile or run it at all.
Or it should warn that the `enabled_if` is not effective.

This can be worked around by splitting up the stanza into an `executable` and `rule (alias runtest)`, e.g. like this:
https://github.com/backtracking/ocaml-hashcons/pull/13/files

## Specifications

- Version of `dune` (output of `dune --version`): 3.13.0
- Version of `ocaml` (output of `ocamlc --version`): 5.1.1
- Operating system (distribution and version): Fedora 39

**Comment by rgrinberg** [comment]
Did you try using `build_if`? `enabled_if` for tests means running them not building them.

**Comment by edwintorok** [comment]
> Did you try using `build_if`? `enabled_if` for tests means running them not building them.

You're right, I didn't know that flag existed.
The docs say
> The optional fields supported are a subset of the alias and executables fields

and I stopped reading there, but if I would've continued reading then they also say

> The (enabled_if) field has special semantics: when present, it only applies to running the tests. The test executable is always built by default. If you need to restrict building the test executable, use (build_if) instead.

So they're not a strict subset, `build_if` is only for `test` and `tests`.

And I can't seem to reproduce `enabled_if` not working
