### ISSUE TITLE
Regression: 3.12 -> 3.13, huge performance loss for dune files with a lot of rules.

### ISSUE THREAD

**Issue by AllanBlanchard** [ocaml/dune#9857]
With Dune 3.13, we detected that when a project has dune files with a lot of rules, it can kill performances. For example, on Frama-C and Alt-Ergo, tests files are generated and can be quite long. In Alt-Ergo, the `dune.inc` file is 205 kLOC long. In Frama-C, files are much shorter, but there are many of them and it basically has the same effect : the build never starts.

## Reproduction

Clone Alt-Ergo v2.5.2 from GitHub and try to compile it:
```
dune build @install
```
This will block for minutes. With 3.12, it takes a few seconds.

## Specifications

- Version of `dune` (output of `dune --version`): 3.12 -> 3.13
- Version of `ocaml` (output of `ocamlc --version`): at least 4.13 and 4.14.
- Operating system (distribution and version): Ubuntu

**Comment by jchavarri** [comment]
Potentially related to https://github.com/ocaml/dune/issues/9738 (just based on a hunch, I haven't done any triage or investigation of any sort related to this new issue, but 3.13 was released with the performance regression reported in 9738).

To confirm the hunch, might be worth testing pinning dune to latest (`opam pin add dune.dev --dev-repo `) to see if there is any noticeable change.

**Comment by vprevosto** [comment]
I confirm that with `dune.dev`  installing Alt-Ergo 2.5.2 through `opam` is back to a reasonable compilation time. Thanks for pointing to this issue.

**Comment by nojb** [comment]
I'm wondering: why wasn't this regression caught in the `opam-repository` CI? Isn't Alt-Ergo in OPAM?

**Comment by AllanBlanchard** [comment]
It happens that on Alt-Ergo, it takes a really long time ... but it still finishes at some point. For Frama-C, the build does not involve those dune files that are generated only in the test target. However, I suspect that using the Opam CI now for Frama-C with tests would fail. Alt-Ergo has a about 19k `rule`s for its tests, Frama-C has 62k for them.

**Comment by emillon** [comment]
> I'm wondering: why wasn't this regression caught in the `opam-repository` CI? Isn't Alt-Ergo in OPAM?

opam-repo-ci doesn't track build times. Doing so requires isolating the builds, which is fairly difficult to do and couldn't work at scale.

As for this particular issue: it looks to be resolved in main, so I'm closing the issue.
I'll backport #9769 to a 3.13.1 release.

Thanks!
