### ISSUE TITLE
.install file contains absolute paths when built with --build-dir

### ISSUE THREAD

**Issue by andreypopp** [ocaml/dune#986]
I'm continuing testing with the same project as in #979 and noticed that `*.install` file is being generated with absolute paths inside. Few observations/questions regarding this:

1. `opam-installer` fails for me on those absolute paths (it tries to join it with the current dir)
2. What's the workflow with `*.install` files and dune:
   - a. should one commit them to VCS
   - b. should one include them in the released tarball?

   Either case doesn't work with absolute paths, I suppose.

**Comment by diml** [comment]
Does `dune install` succeeds? It doesn't use opam-installer anymore. (1) looks like a bug in opam-installer.

Regarding (2), .install files shouldn't be committed or  included in release tarballs since their contents depend on the OS and on other parameters. You should just add them to your .gitignore file.

**Comment by diml** [comment]
I just tried the following:

```
$ dune build --build-dir /tmp/x
$ dune install --build-dir /tmp/x
$ dune uninstall --build-dir /tmp/x
```

and it seems to work well.

**Comment by andreypopp** [comment]
Yes, `dune install` works.

If `dune install` is going to be a primary way to install dune built artifacts shouldn’t dune put .install files into a build for instead? Less files to ignore and less churn in the project root overall.

**Comment by diml** [comment]
Well, opam packages shouldn't use `dune install` explicitly. Instead they should let opam read the generated .install files and opam expects them at the root of the project.
