### ISSUE TITLE
Dune fails to build or hangs while `build @install` (android)

### ISSUE THREAD

**Issue by mcagabe19** [ocaml/dune#9878]
## Expected Behavior
To dune `build @install`/`make release` work

## Actual Behavior
Hang, keep being D in htop in while `dune.exe build @install -p dune --profile dune-bootstrap` with no updates and got this randomly
![Screenshot_20240131_201947_Termux](https://github.com/ocaml/dune/assets/82843871/5b082667-bfa4-41fe-b410-0b77f66bc26a)

## Specifications

- Version of `dune`: 85cf623
- Version of `ocaml`: 5.3.0+dev0-2023-12-22
- Operating system: Android 13

**Comment by emillon** [comment]
possibly related to #8720 but I don't have a way to debug this.

**Comment by mcagabe19** [comment]
> possibly related to #8720 but I don't have a way to debug this.

yeah I think `wait4` change broke android

**Comment by Alizter** [comment]
`wait4` should be supported on android. How did you setup OCaml? Are you using a rooted shell? I've only ever tested android using termux.

**Comment by mcagabe19** [comment]
solved with these:
## OCaml
```
apt install git build-essential libandroid-shmem binutils
git clone https://github.com/ocaml/ocaml --depth=1
cd ocaml
make configure
./configure --prefix=$PREFIX --disable-warn-error --without-afl LDFLAGS="-landroid-shmem"
make install -j$(nproc)
```
## Dune
```
apt install git proot
unset LD_PRELOAD
termux-chroot
git clone https://github.com/ocaml/dune --depth=1
cd dune
make release
make install PREFIX=$PREFIX
```

**Comment by mcagabe19** [comment]
and @Alizter no I didn't use root in these

**Comment by Alizter** [comment]
AFAIK we don't "officially" support android, but we should at least document the procedure for setting up dune there. We can also document support for various other niche systems such as BSD and Haiku.

@emillon could you create an issue to do this? I created https://github.com/ocaml/dune/pull/9298 some time back, but we could probably turn this into a document in the manual.

**Comment by Sylvain78** [comment]
> AFAIK we don't "officially" support android, but we should at least document the procedure for setting up dune there. We can also document support for various other niche systems such as BSD and Haiku.
> 
> @emillon could you create an issue to do this? I created #9298 some time back, but we could probably turn this into a document in the manual.

I can help on the Haiku port as i did a lot of port from ocaml ecosystem to Haiku.

**Comment by Alizter** [comment]
@Sylvain78 I worked on the Haiku port here https://github.com/ocaml/dune/pull/8795 and last I checked it was working.
