### ISSUE TITLE
Output of successful build commands for dependencies should not go to the terminal by default

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#9900]
Currently the output build actions for dependencies is printed to the terminal. This can produce a lot of noise, e.g. the build step for `conf-pkg-config` is `pkg-config --help`. The output of successful build commands should be logged to `_build/log` but not appear on the terminal.

**Comment by rgrinberg** [comment]
Same as https://github.com/ocaml/dune/issues/9281?

**Comment by gridbugs** [comment]
Ah yep
