### ISSUE TITLE
In pkg files, pforms inside string interpolations should be substituted with absolute paths

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#9919]
Currently section pforms in string interpolations such as `--prefix=%{prefix}` are substituted with relative paths while section pforms on their own are substituted with absolute paths. They should both be substituted by absolute paths.

**Comment by gridbugs** [comment]
Repro: https://github.com/ocaml/dune/pull/9920

**Comment by rgrinberg** [comment]
There's still some premature stringification going on in `String_with_vars.t`. I think you can fix this by modifying `String_with_vars.expand_result` to add a `Concat` constructor like i did with slang.
