### ISSUE TITLE
Additional constraints can't be used to force solver to choose `ocaml-system`

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#9972]
One of the goals of the `constraints` field of the `lock_dir` stanza in `dune-workspace` files is to allow users to use the the system compiler rather than a compiler packaged in opam. Adding `ocaml-system` as an additional constraint should cause the solver to choose `ocaml-system`.

_Why should that work? Additional constraints don't add new dependencies._

The behavior of `constraints` is to add each listed package to the `depends` list of each dependency that already depends on the package in some capacity. The `ocaml` package has dependencies:
```
depends     "ocaml-config" {>= "3"}
            "ocaml-base-compiler" {>= "5.0.0~" & < "5.0.1~"} |
            "ocaml-variants" {>= "5.0.0~" & < "5.0.1~"} |
            "ocaml-system" {>= "5.0.0" & < "5.0.1~"}
```

So `ocaml-system` is already among `ocaml`'s dependencies, though it's part of a disjunction. `ocaml-base-compiler` and `ocaml-variants` both conflict with `ocaml-system`, so adding a new dependency on `ocaml-system` to `ocaml` should force the solver to choose `ocaml-system` instead of `ocaml-base-compiler` or `ocaml-variants`.

**Comment by gridbugs** [comment]
Reproduced in https://github.com/ocaml/dune/pull/9973

**Comment by rgrinberg** [comment]
I think the issue is with how we try to insert the constraint:
```
      OpamFormula.map_up_formula
        (fun formula ->
          match formula with
          | Atom (pkg, _) ->
            let name = Package_name.of_opam_package_name pkg in
            (match Package_name.Map.find t.constraints name with
             | None -> formula
             | Some additional -> OpamFormula.And (formula, additional))
          | _ -> formula)
        filtered_formula
```
I assumed that `map_up_formula` would traverse every atom in the formula, but it doesn't.
